### ISSUE TITLE
need better compiler error/diagnistics output

### ISSUE THREAD

**Issue by yonghong-song** [iovisor/bcc#1]
The following is a buggy b-language program.
plumgrid@yhs-plumgrid:~/iovisor/bcc/tests/jit$ cat bpfdev1.b
#packed "false"

// hash
struct FwdKey {
  u32 dip:32;
};
struct FwdLeaf {
  u32 ifindex:32;
};
Table<FwdKey, FwdLeaf, FIXED_MATCH, NONE> fwd_map(1);

// array
struct ConfigKey {
  u32 index:32;
};
struct ConfigLeaf {
  u32 bpfdev_ip:32;
  u32 slave_ip:32;
};
Table<ConfigKey, ConfigLeaf, INDEXED, NONE> config_map(1);

// hash
struct MacaddrKey {
  u32 ip:32;
};
struct MacaddrLeaf {
  u64 mac:48;
};
Table<MacaddrKey, MacaddrLeaf, FIXED_MATCH, AUTO> macaddr_map(11);

// hash
struct SlaveKey {
  u32 slave_ip:32;
};
struct SlaveLeaf {
  u32 slave_ifindex:32;
};
Table<SlaveKey, SlaveLeaf, FIXED_MATCH, NONE> slave_map(10);

u32 main(struct proto::skbuff *skb) {
  u32 ret:32 = 0xffffffff;

  goto proto::ethernet;

  state proto::ethernet {
  }

  state proto::dot1q {
  }

  if (skb.pkt_type) {
     state proto::arp {
       if $arp.oper != 1 {
	  return 0;
       }
       macaddr_map[$arp.spa] = $arp.sha;
     }
     state proto::ip {
     }
     state proto::udp {
       if $udp.dport != 5000 {
          return 0;
       }
       FwdKey fwd_key = {.dip = $ip.dst};
       FwdLeaf *fwd_idx_p = fwd_map[$ip.dst];
       if (fwd_idx_p) {
          return fwd_idx_p->fwd_idx;
       } else {
          return 0;
       }
     }
  } else {
     state proto::ip {
     }
  }

  state EOP {
    return ret;
  }
}
plumgrid@yhs-plumgrid:~/iovisor/bcc/tests/jit$ 

The compiler error message like the below:

Checking test dependency graph end
test 5
    Start 5: py_bpfdev1

5: Test command: /home/plumgrid/iovisor/bcc/build/tests/wrapper.sh "py_bpfdev1" "/home/plumgrid/iovisor/bcc/tests/jit/bpfdev1.py" "namespace"
5: Test timeout computed to be: 9.99988e+06
5: Error: 42.1-5 syntax error
5: In file: bpfdev1.b
5: E

It does not provide sufficient information about where the problem occurs.
Maybe 42.1-5 indicates something, but the message should be better communicated.

**Comment by drzaeus77** [comment]
Closing this as the clang frontend has much better diagnostics now.
