### ISSUE TITLE
Use "ausyscall --dump" to generate dynamic map for syscount

### ISSUE THREAD

**Issue by wcohen** [iovisor/bcc#1001]
syscount uses a static list ot map between syscall name and number.  The static list is tied to x86 and may miss new syscalls added to more recent kernels.  The "ausyscall --dump" can generate a list of event numbers and names.  Using ausyscall might provide a more portable way of getting that mapping information that avoids having to perform manual updates on a static list.

**Comment by goldshtn** [comment]
@wcohen That's pretty awesome, yeah. Are we guaranteed to have ausyscall OOTB? I noticed on FC it's part of the audit package.

**Comment by wcohen** [comment]
I am not sure whether it installed by default.  The command does seem to exist on ubuntu.  Maybe code syscuont to mention need for ausyscall command and fallback gracefully to just using printing the numbers used by the syscall.

**Comment by brendangregg** [comment]
I just found it not installed by default on Ubuntu Yakkety 16.10. On our production Ubuntu Xenial systems, it is there, but might have been added at some point.

**Comment by goldshtn** [comment]
Hmm. Then maybe we should try to detect ausyscall and if it's present, use the syscall list it provides. Otherwise, stick with the hard-coded one, which will unfortunately become stale.
