### ISSUE TITLE
Install failure on Ubuntu 15.04 with 4.2.0-rc4

### ISSUE THREAD

**Issue by tuxology** [iovisor/bcc#101]
I tried to follow [INSTALL.md] (https://github.com/iovisor/bcc/blob/master/INSTALL.md#ubuntu---from-source ) with a new Ubuntu 15.04 VM with kernel 4.2.0-rc4. I could not complete it because cmake was finding LLVM in wrong path. I could verify by output of [this] (https://github.com/iovisor/bcc/blob/master/CMakeLists.txt#L20)

```
Found LLVM: /usr/include
```

Output of `${LLVM_LIBRARY_DIRS}` was `/usr/lib` as well, whereas it should be `/usr/lib/llvm-3.7/lib`.

I proceeded to make my own install scripts for llvm and bcc setup based on your kickstart file. This resulted into another issue #100 My lab folks were really interested in bcc. #100 fix did get it to work and I demoed it.

**Comment by drzaeus77** [comment]
Were you installing from llvm.org/apt packages? If so, there is an open bug in the LLVM deb packaging that I am tracking here:

https://llvm.org/bugs/show_bug.cgi?id=24154

For now, the manual LLVM compile+install is the right workaround to follow. Does that work?

**Comment by tuxology** [comment]
Oh, thanks! Didn't know there was already an open bug. As I mentioned, manual install takes me to #100 and with some patchwork, it works for me :smile:

**Comment by drzaeus77** [comment]
Just to update this:

The mentioned LLVM breakage was reverted, but the issue has permuted and now is hanging around in another email thread:

http://thread.gmane.org/gmane.comp.compilers.llvm.cvs/255502/focus=255724

Hopefully this will resolve in the near future. For now, the workaround remains.

**Comment by drzaeus77** [comment]
Testing has shown the deb packages to be free of this problem. Closing.
