### ISSUE TITLE
tools/trace.py: type object 'BPF' has no attribute 'monotonic_time'

### ISSUE THREAD

**Issue by ldorau** [iovisor/bcc#1019]
tools/trace.py does not work - it always prints message "type object 'BPF' has no attribute 'monotonic_time'" and exits with code 0:
```
# ./trace.py 'sys_execve "%s", arg1'
type object 'BPF' has no attribute 'monotonic_time'

# ./trace.py 'sys_open "%s", arg1'
type object 'BPF' has no attribute 'monotonic_time'

# ./trace.py 'sys_open'
type object 'BPF' has no attribute 'monotonic_time'

# ./trace.py 'sys_close'
type object 'BPF' has no attribute 'monotonic_time'
```
Environment:
Fedora 24
kernel-4.9.12-100.fc24.x86_64  and  kernel-4.8.4-200.fc24.x86_64
bcc: v0.2.0-443-g601a13f  and  v0.2.0-433-gcc0ff79

**Comment by ldorau** [comment]
@vitalyvch, @marcinslusarz, @GBuella, @plebioda, @sarahjelinek

**Comment by goldshtn** [comment]
That's odd. Can you test if it works with master?

**Comment by ldorau** [comment]
I have done it - v0.2.0-443-g601a13f is a master

**Comment by ldorau** [comment]
... or was few hours ago

**Comment by goldshtn** [comment]
And just to confirm, you built bcc and ran 'sudo make install'? Because the `monotonic_time` method is there on the BPF object.  https://github.com/iovisor/bcc/blob/master/src/python/bcc/__init__.py

**Comment by ldorau** [comment]
Yes, I confirm

**Comment by sarahjelinek** [comment]
I was able to run tracer.py after I did the build and 'sudo make install' from the latest sources.  I ran tracer.py do_sys_open and it appears to be running ok.

**Comment by goldshtn** [comment]
Yup, that looks fine. Thanks for testing this!

**Comment by brendangregg** [comment]
I just got this error, and a make, make install fixed it.

Previously, I've had issues with make install adding a new libbcc and not deleting the old one, and the old one getting picked up by tools. Have a look in /usr/lib/x86_64-linux-gnu/libbcc.*

**Comment by goldshtn** [comment]
@ldorau can you update please if you are still seeing this on a clean box? I can't reproduce this.

**Comment by ldorau** [comment]
I had two versions of libbcc: one in /usr and another in /usr/local/. Removing the one in /usr/local/ and reinstalling the one in /usr/ fixed the issue. Closing. Thanks.
