### ISSUE TITLE
trace kernel's skb_shinfo  

### ISSUE THREAD

**Issue by williamtu** [iovisor/bcc#1028]
Hi,
I'm trying to debug some GSO issue using bcc trace tools to print out skb_shinfo(skb)->gso_type, I'm doing
```
# ./trace 'skb_udp_tunnel_segment\
 (struct sk_buff *skb, netdev_features_t features, bool is_ipv6)  "%x", skb_shinfo(skb)->gso_type'
```
is it a valid syntax to call "skb_shinfo"?, I got verifier error as below:
```
1 warning generated.
bpf: Permission denied
0: (bf) r6 = r1
1: (79) r8 = *(u64 *)(r6 +112)
2: (85) call 14
3: (bf) r7 = r0
4: (bf) r9 = r7
5: (77) r9 >>= 32
6: (15) if r9 == 0x83a3 goto pc+29
 R0=inv R6=ctx R7=inv R8=inv R9=inv32 R10=fp
7: (b7) r1 = 0
8: (7b) *(u64 *)(r10 -8) = r1
9: (7b) *(u64 *)(r10 -16) = r1
10: (7b) *(u64 *)(r10 -24) = r1
11: (7b) *(u64 *)(r10 -32) = r1
12: (7b) *(u64 *)(r10 -40) = r1
13: (85) call 5
14: (7b) *(u64 *)(r10 -40) = r0
15: (63) *(u32 *)(r10 -32) = r9
16: (63) *(u32 *)(r10 -28) = r7
17: (bf) r1 = r10
18: (07) r1 += -24
19: (b7) r2 = 16
20: (85) call 16
21: (61) r1 = *(u32 *)(r8 +204)
R8 invalid mem access 'inv'
```
Thanks!
William

**Comment by drzaeus77** [comment]
Doubtful this should work, since clang rewriter needs to see the dereferences as non-macro/non-inlined-functions in order to convert easily to bpf_probe_read(). Try manually expanding the function+macro.

**Comment by williamtu** [comment]
thanks. I tried manually expand the macro
```
# ./trace 'skb_udp_tunnel_segment(struct sk_buff *skb, netdev_features_t features, bool is_ipv6) "%x",\
 ((struct skb_shared_info *)(skb->head + skb->end))->nr_frags'
```
since 
 #define skb_shinfo(SKB) ((struct skb_shared_info *)(skb_end_pointer(SKB)))
but still fails the verifier due to invalid mem access 'inv'

**Comment by drzaeus77** [comment]
Try expanding this into multiple simple statements inside a `({})` block.

`sudo /usr/share/bcc/tools/trace -I linux/skbuff.h -I linux/netdev_features.h 'skb_udp_tunnel_segment(struct sk_buff *skb, netdev_features_t features, bool is_ipv6) "%x", ({struct skb_shared_info *sh = skb->head+skb->end; sh->nr_frags;})'`

**Comment by williamtu** [comment]
thanks a lot, it works. Pretty amazing!
