### ISSUE TITLE
Discard upper 32-bits assumes little-endian hardware

### ISSUE THREAD

**Issue by cloojure** [iovisor/bcc#1029]
I have noticed the docs repeat several times the idea of truncating 64 -> 32 bits, like this:

> 3. bpf_get_current_pid_tgid()
> ....
> By directly setting this to a u32, we discard the upper 32 bits.

Does this imply that BPF only runs on little endian-hardware?  At the least a warning such as 

> "This implies that on little-endian hardware we can extract the tgid via an unchecked cast to u32"

**Comment by cloojure** [comment]
tgid -> pid

**Comment by 4ast** [comment]
type cast of bpf_get_current_pid_tgid() to u32 works on both little and big-endian.
