### ISSUE TITLE
solisten: No module named netaddr

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#1035]
```
# ./solisten.py 
Traceback (most recent call last):
  File "./solisten.py", line 22, in <module>
    import netaddr
ImportError: No module named netaddr
```

It's using netaddr for IP address to string. This could be switched to use the socket library like tcpconnect.py does, on the assumption it's more readily available than netaddr.

**Comment by goldshtn** [comment]
Where are you missing netaddr? I think I have it OOTB on all my boxes.

**Comment by brendangregg** [comment]
Netflix BaseAMI.

**Comment by brendangregg** [comment]
Also missing in Amazon Linux.

I'd just switch to the socket library.

**Comment by pchaigno** [comment]
It's also missing on my Ubuntu 16.04.
