### ISSUE TITLE
Xenial-nightly pkg into repo.iovisor  not signed 

### ISSUE THREAD

**Issue by tutelacooldouce** [iovisor/bcc#1038]
Hello ,  This is my apt-key list    (imported : https://repo.iovisor.org/GPG-KEY ) :  
```
 # apt-key list
/etc/apt/trusted.gpg
--------------------
pub   4096R/D4284CDD 2015-08-05
uid                  Brenden Blanco <bblanco@plumgrid.com>
sub   4096R/8C2D767C 2015-08-05
sub   4096R/C5946DB1 2015-08-05 [expires: 2025-08-02]
sub   4096R/C30E5EE6 2015-08-05 [expires: 2025-08-02]

```

when I try to install the nightly-xenial package.  

```
WARNING: The following packages cannot be authenticated!
  libbcc python-bcc bcc-tools
Install these packages without verification? [y/N] n
E: Some packages could not be authenticated
```

I know that you guys force with [trusted=yes]  -   may I ask you to sign the packages on Xenial ? 

used key:  https://repo.iovisor.org/GPG-KEY
réf. instruction :  https://github.com/iovisor/bcc/blob/master/INSTALL.md#ubuntu-xenial---binary

**Comment by drzaeus77** [comment]
I'll do this for the tagged packages (it's time we built a new one), but not for the nightly builds. I prefer to have a manual intervention step for package signing, which makes the automated process difficult.

**Comment by tutelacooldouce** [comment]
okay  thanks for your feedback . Do you have any date (more or less)  when you guys trigger stable and non nightly packages for Ubuntu 16.04 Xenial ?

**Comment by goldshtn** [comment]
I believe 0.3.0 has now been released -- can you please verify and close if it's OK?

**Comment by goldshtn** [comment]
Closing for now, I believe this is addressed.
