### ISSUE TITLE
ucalls -S - crash/resource exhaustion 

### ISSUE THREAD

**Issue by jason-azze** [iovisor/bcc#1047]
**Version of bcc tools**
0.3.0-11.git.dd3867d from https://repo.iovisor.org/apt/xenial
**OS version**
Ubuntu 16.04.2 LTS
**Kernel**
Linux protactinium 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Steps to reproduce**
```
root@protactinium:/usr/share/bcc/tools# ps -ef |grep ntpd
ntp      10102     1  0 08:04 ?        00:00:00 /usr/local/sbin/ntpd -p /var/run/ntpd.pid -g -u 126:139
```
```
root@protactinium:/usr/share/bcc/tools#./ucalls -S $(pidof ntpd)
```
**Expected behavior**
ucalls traces syscalls

**Observed behavior**
complete system freeze, requiring power cycle to reboot

**Notes**
@goldshtn and I exchanged email on this issue on 2017-02-13. At that time he said
 "this specific issue actually might be the result of a recent regression,
which seems to be fixed now: https://github.com/iovisor/bcc/issues/940
If this fix still doesn't help, please let me know."

**Comment by goldshtn** [comment]
Hmm. To triage this a bit further: do you see the same behavior with `funccount 'SyS_*'`? Also, I know it's quite a bit more effort, but does it happen with bcc built from source? Although the version you have (dd3867d) looks quite new, so it's got to have the fix from #940.

**Comment by jason-azze** [comment]
`funccount` does not cause the freeze.
```
root@protactinium:/usr/share/bcc/tools# ./funccount 'SyS_*'
Tracing 334 functions for "SyS_*"... Hit Ctrl-C to end.
^C
FUNC                                    COUNT
SyS_tgkill                                  1
[snip]
SyS_poll                               517308
SyS_recvmsg                            542990
Detaching...
root@protactinium:/usr/share/bcc/tools# 
```
I'll try building from source when I have some more free cycles. :-)

**Comment by goldshtn** [comment]
I'll try to repro this. Is this a clean Ubuntu 16.04? Any special setup instructions?

**Comment by jason-azze** [comment]
Sadly, this is not a clean Ubuntu. It's my "daily driver", which has enjoyed many adventures in the last three years.

In fact, I just discovered this in syslog from around the time of my hang.
```
Mar 13 07:45:42 protactinium kernel: [258830.742367] **   NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE   **
Mar 13 07:45:42 protactinium kernel: [258830.742368] **                                                      **
Mar 13 07:45:42 protactinium kernel: [258830.742369] ** trace_printk() being used. Allocating extra memory.  **
Mar 13 07:45:42 protactinium kernel: [258830.742369] **                                                      **
Mar 13 07:45:42 protactinium kernel: [258830.742370] ** This means that this is a DEBUG kernel and it is     **
Mar 13 07:45:42 protactinium kernel: [258830.742370] ** unsafe for production use.                           **
Mar 13 07:45:42 protactinium kernel: [258830.742371] **                                                      **
Mar 13 07:45:42 protactinium kernel: [258830.742372] ** If you see this message and you are not debugging    **
Mar 13 07:45:42 protactinium kernel: [258830.742372] ** the kernel, report this immediately to your vendor!  **
Mar 13 07:45:42 protactinium kernel: [258830.742373] **                                                      **
Mar 13 07:45:42 protactinium kernel: [258830.742373] **   NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE NOTICE   **
Mar 13 07:45:42 protactinium kernel: [258830.742374] **********************************************************
```
I have just tried to reproduce the hang on a fresh Ubuntu 16.04.2 VM and cannot.

So, that's good news, I think. Not for my laptop--but for bcc-tools.

**Comment by goldshtn** [comment]
All right, so would you be OK with closing this issue? Unless there is something else that we could try in order to reproduce this.

**Comment by jason-azze** [comment]
Yes. Closing. Thanks for taking a look.
