### ISSUE TITLE
syscount doesn't seem to work on Arch

### ISSUE THREAD

**Issue by darthdeus** [iovisor/bcc#1062]
I'm not sure if I did anything wrong, but I've installed following the guide `pacaur -S bcc bcc-tools python-bcc python2-bcc`, then went into `/usr/share/bcc/tools` and tried to run `syscount`

```
$ sudo ./syscount
Traceback (most recent call last):
  File "./syscount", line 13, in <module>
    from itertools import izip_longest
ImportError: cannot import name 'izip_longest'
```

**Comment by goldshtn** [comment]
Which version of Python do you have installed? It seems that this function is new in Python 2.6 (which is to say, not very new but still...).

**Comment by darthdeus** [comment]
@goldshtn `python` is 3.6.0 and `python2` is 2.7.13 ... could it be the issue that on Arch the default `python` named binary is Python 3.x instead of 2.x?

**Comment by goldshtn** [comment]
Right! It was renamed to zip_longest in Python 3. Would you like to submit a PR that chooses the right function according to the Python version? Or I could fix it.

**Comment by darthdeus** [comment]
If you could that'd be great :) I don't really have any experience with Python.

**Comment by goldshtn** [comment]
Sure thing. Should be fixed by #1068, perhaps you could confirm on your system? You'd only need to fetch syscount.py from that patch.

**Comment by darthdeus** [comment]
@goldshtn just tried it out and it works!

**Comment by goldshtn** [comment]
Lovely, thanks. This will auto-close when the PR is merged.
