### ISSUE TITLE
How do I print the user-space stack backtraces

### ISSUE THREAD

**Issue by monadbobo** [iovisor/bcc#1070]
I want to print the backstrace in the stack,(it's like the ubacktrace of Systemtap), and i can't find the api can do this. So how do i do this in bcc?

Thanks!

**Comment by markdrayton** [comment]
The APIs are documented here:

https://github.com/iovisor/bcc/blob/master/docs/reference_guide.md#4-bpf_stack_trace

You need to create a map of type `BPF_STACK_TRACE` then call `map.get_stackid()` with the `BPF_F_USER_STACK` flag to store a userspace trace. On the python side, use `map.walk()` to iterate over the stack addresses and `BPF.sym(addr, tgid)` to resolve them to names.

`offcputime` (and other scripts) have examples of this:

https://github.com/iovisor/bcc/blob/78948e4aae6aa0d06806d452d193320936d59dc7/tools/offcputime.py#L190

**Comment by monadbobo** [comment]
Thanks for your reply. 

I use BPF_STACK_TRACE, but I can only get the current stack sym. My bcc's program was used to trace the stack of the Nginx.

```c
#!/usr/bin/python
#
from __future__ import print_function
from bcc import BPF, USDT
import sys
import ctypes as ct

bpf_text="""
#include <uapi/linux/ptrace.h>
#include <linux/sched.h>
struct data_t {
        int stack_id;
        u32 pid;
};
BPF_PERF_OUTPUT(events);
BPF_STACK_TRACE(stack_traces, 10280)

void trace_header_filter(struct pt_regs *ctx) {
    u32 pid = bpf_get_current_pid_tgid();
    u64 stack_id = stack_traces.get_stackid(ctx, BPF_F_REUSE_STACKID | BPF_F_USER_STACK);
    struct data_t data = {stack_id, pid};
    events.perf_submit(ctx, &data, sizeof(data));
}
"""
pid = int(sys.argv[1])

b = BPF(text=bpf_text)
b.attach_uprobe(name="/home/test/tools/nginx/sbin/nginx", sym="ngx_http_send_header", fn_name="trace_header_filter", pid=pid)
stack_traces = b.get_table("stack_traces")
class Data(ct.Structure):
    _fields_ = [
        ("stack_id", ct.c_int),
        ("pid", ct.c_ulong),
    ]

def print_event(cpu, data, size):
    data = ct.cast(data, ct.POINTER(Data)).contents
    stack_id = data.stack_id
    stack = list(stack_traces.walk(stack_id))
    line = [b.sym(addr, pid) for addr in reversed(stack)]
    print("%s" % (";".join(line)))


# loop with callback to print_event
b["events"].open_perf_buffer(print_event, page_cnt=64)

while 1:
    b.kprobe_poll()

```
And when I start this trace program, I can only get the output:

>ngx_http_send_header

And so I don't know why don't get the all stacktrace.

**Comment by goldshtn** [comment]
Is nginx built with omit-frame-pointer? This could prevent the stack walker from obtaining an accurate stack trace.

**Comment by goldshtn** [comment]
By the way what you're currently doing can be done with `trace nginx:ngx_http_send_header -U` ;-)

**Comment by monadbobo** [comment]
@goldshtn 
1. Nginx is not built with omit-frame-pointer. And I can use  gdb set break point, and it can print all stack.
2.  I use trace script to trace nginx, output the error.
```shell
sudo ./trace.py /home/test/tools/nginx/sbin/nginx:ngx_http_send_header -U -p 7649
```
error message:
>Failed to attach BPF to kprobe

**Comment by goldshtn** [comment]
gdb can use debuginfo and resolve stacks in more sophisticated ways than just by using the frame pointer. Is this something easily reproducible? What would I need to repro this - which distro, which nginx build etc.?

The trace error is suspicious. What do you get with -v?

**Comment by tuxology** [comment]
Not to divert away from the current discussion, but `libunwind` allows stack unwinding even with omit-frame-pointer. Maybe for userspace case we could support that.

**Comment by goldshtn** [comment]
Yes, but the stack is grabbed by BPF in-kernel. Wouldn't we need libunwind there?

**Comment by tuxology** [comment]
@goldshtn Oh, yes indeed. I was thinking we should have such support on the kernel side itself. Here is something that a ex-colleague of mine did to circumvent this issue : https://github.com/giraldeau/kunwind 
In addition, I think `perf` allows storing 2 pages worth of stack data and unwinding it in userspace. Could we do something of that sorts?

**Comment by 4ast** [comment]
we can probe_read 16k bytes from given %sp into map's value and then perf_event_output from there. So user space unwind is possible, just very inefficient.

**Comment by monadbobo** [comment]
@goldshtn 
1 The nginx was built by myself, and so it hasn't extern debuginfo, This is Nginx's cflag:

> -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g

2. I correct my usage, and then the trace.py output the same message with my bcc' script.(the current stack sym).

**Comment by goldshtn** [comment]
Right, so your nginx likely has frame pointer omission. Can you build it with `-fno-omit-frame-pointer`?

**Comment by monadbobo** [comment]
@goldshtn Thanks a lot, When using -fno-omit-frame-pointer for compiling Nginx, everything is fine.

**Comment by goldshtn** [comment]
Excellent! OK to close then?
