### ISSUE TITLE
How do I get the type info in bcc?

### ISSUE THREAD

**Issue by monadbobo** [iovisor/bcc#1087]
When i tracing Nginx, I want get the type of data in the function of trace. In systemtap I can use 'cast' keyword, for example, this script can get the buffered filed of the struct ngx_connection_t :
```c
b = @cast(c, "ngx_connection_t")->buffered
```
And then  my question is How do i doing this in bcc?

**Comment by goldshtn** [comment]
I'm not completely sure that's what you mean, but the tracing part (the BPF program) is written in C. You can simply use a C-style cast, e.g. `((struct ngx_connection_t *)ptr)->buffered` -- granted, of course, that `ngx_connection_t` is defined somewhere.

**Comment by monadbobo** [comment]
@goldshtn Yes, if i want use struct ngx_connection_t, i must include the header of  the nginx in bcc.But i don't include any header in systemtap doing the same thing.

**Comment by goldshtn** [comment]
Well, it's C -- not a custom language like SystemTap's. You need to provide the struct's definition. You don't have to include the original header, you could just include the struct definition inline. Or you could access fields by offset. But it won't work automagically, if that's what you ask.

**Comment by monadbobo** [comment]
@goldshtn Thanks.
