### ISSUE TITLE
ClangLoader default to have -Wno-pragma-once-outside-header

### ISSUE THREAD

**Issue by palmtenor** [iovisor/bcc#1100]
Some times we share a header file between user space C++ binary and the kernel space BPF program, mostly for struct definition.

Because we can only load one file / string in `bpf_module`, we normally just concatenate the header file to the rest of the kernel BPF program code. On the other hand, we would normally add an include guard `#pragma once` in the header file in order to use it across user-space code. Therefore, the full content sent to `ClangLoader` will also have a `#pragma once` include guard.

This will cause Clang to emit a warning to `stderr`, unless the `ClangLoader` has a default `-Wno-pragma-once-outside-header` CFLAGS passed to the compiler.

Raising the issue just to see if everyone is OK on adding that to the default `ClangLoader` CFLAGS.

cc @myreg

**Comment by 4ast** [comment]
makes sense to me. Suppressing the warn is harmless.
