### ISSUE TITLE
long compilation time if table key or value structure size is big

### ISSUE THREAD

**Issue by yonghong-song** [iovisor/bcc#1154]
The following test case can demonstrate the problem:

```
[yhs@localhost test]$ cat test.py
#!/usr/bin/env python

from bcc import BPF

prog = """
#define STACK_MAX_LEN 64
#define STR_MAX_LEN 128

typedef struct {
  char name[STR_MAX_LEN];
  char file[STR_MAX_LEN];
} Symbol;

typedef struct {
  uint32_t pid;
  uint32_t tid;
  int tls_key;
  uint32_t stack_len;
  int32_t kernel_stack_id;
  int32_t user_stack_id;
  uint64_t pthread_id;
  uint64_t pthread_created;
  bool thread_state_different;
  bool stack_complete;
  Symbol stack[STACK_MAX_LEN];
} Event;

BPF_TABLE("percpu_array", int, Event, eventTable, 1);
__attribute__((section(".bpf.fn.log_py_stack")))
int log_py_stack(struct pt_regs* ctx) {
  return 0;
}
;
"""

# load BPF program
b = BPF(text=prog, debug=1)
[yhs@localhost test]$ 
```

Here the value type `Event` is pretty big. Internally, for each key and value type of each structure, BCC generates `readerX` and `writerX` functions, which utilizes `sscanf` and `snprintf`. For data structure with large size (e.g., array or array of array). The number of parameters to `sscanf` and `snprintf` could be pretty big, and compiler seems having a hard time to digest, thus resulting in pretty big compilation time.

@drzaeus77 what is your opinion on this?

**Comment by yonghong-song** [comment]
CC the group: @iovisor/iovisor

**Comment by drzaeus77** [comment]
Have been staring at this for a while today, and so far my best proposal is to use "%s" instead of "%i %i %i %i %i ..." for input of arrays of type u8. This reduces the running time on my machine from 50s to <1s. However, I haven't quite figured out how to convince sscanf to handle empty strings in a clean way.

Besides this approach, the other would be to conditionally compile these helper functions on an as-needed basis.

**Comment by yonghong-song** [comment]
On Thu, May 4, 2017 at 5:23 PM, Brenden Blanco <notifications@github.com>
wrote:

> Have been staring at this for a while today, and so far my best proposal
> is to use "%s" instead of "%i %i %i %i %i ..." for input of arrays of type
> u8. This reduces the running time on my machine from 50s to <1s. However, I
> haven't quite figured out how to convince sscanf to handle empty strings in
> a clean way.
>

Could you elaborate how this is done? I could not figure it out :-)


> Besides this approach, the other would be to conditionally compile these
> helper functions on an as-needed basis.
>
This is a good idea. For the people having large value structure sizes,
they are unlikely using sscanf/snprintf features.

**Comment by yonghong-song** [comment]
I wil work on a patch for this (conditionally not compile for readerX/writerX helper functions).

**Comment by drzaeus77** [comment]
Thanks. It would be nice if this is done in a late-binding fashion, rather than introducing new flags or some such. That is, keep enough state around, and if BPFModule::table_key/leaf_printf/scanf is called then try to invoke finalize for the functions.

**Comment by yonghong-song** [comment]
Late binding is a very good suggestion.
