### ISSUE TITLE
BCC without root

### ISSUE THREAD

**Issue by rvansa** [iovisor/bcc#1166]
Is there any possibility to use bcc (particularly offcputime) without root privileges, if I want to monitor only a process started by the same user? Something like setting `kernel.perf_event_paranoid=-1`.

I want to use offcputime in a complex automated test setup, which is not executed as root. Or is the only option to set allow sudo in sudoers file (as I can't set SUID for a python script)?

The problem with using sudoers file is that I can't later send any signal to the process (sudo), and adding `sudo kill` to sudoers doesn't sound like a good idea.

**Comment by pchaigno** [comment]
You need root privileges to attack eBPF programs to kprobes. That's not a restriction of bcc, but a kernel one. This is unlikely to change since eBPF programs attached to kprobes can retrieve a great deal of information, including information on all users.

**Comment by rvansa** [comment]
It seems that this restriction is not going to be lifted any time soon.
