### ISSUE TITLE
TableStorage's unique_ptr ownership of MapTypesVisitor breaks the visitor pattern

### ISSUE THREAD

**Issue by jsedgwick** [iovisor/bcc#1173]
TableStorage takes a MapTypesVisitor by unique_ptr. However, the idea behind the visitor pattern is to plug in a custom behavior so that you can e.g. create your own state based on the visited structures. Unique ownership makes that more difficult than it should be because you then have to create some sort of back reference to your code within the visitor. This situation easily leads to circular ownership that must be broken with undesirable abstractions like shared_from_this() and raw pointers back to your code. TableStorage should take a shared_ptr to MapTypesVisitor instead.

I can fix this, but I'm putting up the issue for tracking purposes.

**Comment by drzaeus77** [comment]
Why not just create a wrapper MapTypesVisitor subclass that wraps the real implementation (with shared_ptr, etc.) however you want. Same as is done with TableStorage/TableStorageImpl split.

**Comment by jsedgwick** [comment]
Of course I subclass MapTypesVisitor. This is the restrictive line: https://github.com/iovisor/bcc/blob/master/src/cc/table_storage.h
