### ISSUE TITLE
TableStorage::iterator is incompatible with many utilities in standard library because it is noncopyable

### ISSUE THREAD

**Issue by jsedgwick** [iovisor/bcc#1174]
See https://github.com/iovisor/bcc/blob/master/src/cc/table_storage.h#L60
Why is it noncopyable? Just because it has a unique pointer to an implementation?
In that case, the copy constructor can just copy the underlying implementation.
There's really no reason for what's ultimately a simple wrapper around standard iterators to be noncopyable.

**Comment by drzaeus77** [comment]
I can't recall why it was this way. Seems like a reasonable change. Please send a PR.

**Comment by jsedgwick** [comment]
I'm off the grid for a couple weeks starting tonight but I'll get to it once I'm back. Feel free to assign to me.
