### ISSUE TITLE
TableStorage and Path coupling is forced

### ISSUE THREAD

**Issue by jsedgwick** [iovisor/bcc#1175]
Only the bpffs implementation makes any sense with paths, so that specialization belongs in the subclass. Why force paths and delimiters on all implementations, e.g. the presumably common SharedTableStorage?

https://github.com/iovisor/bcc/blob/master/src/cc/table_storage.h#L90

**Comment by drzaeus77** [comment]
I wanted a scoping concept, and a directory structure made the most sense to me. SharedTableStorage especially needs a scoping concept, in the sense that you should export a table to a global scope and import it only from there. A program shouldn't be able to import a table that isn't exported/shared (i.e. in the file-local/BPFModule scope).

**Comment by jsedgwick** [comment]
Can you explain the need for global table scoping vs the per-BPF instance scoping we had before? I don't understand what process wide static state helps with.

And if you want scoping, hand rolled paths are not a good solution. It's hacky. There should be a simple scoping tree where each node has references to the tables at that scope. No need for arbitrary string manipulation. When I was first trying to use it, there was zero indication that my table names would get arbitrarily mangled. That at least need very thorough documentation with justification for the pattern.
