### ISSUE TITLE
StatusTuple vs exceptions

### ISSUE THREAD

**Issue by jsedgwick** [iovisor/bcc#1177]
https://github.com/iovisor/bcc/blob/e2a037779c2b8c6ca83648699f0af670668a92b5/src/cc/bcc_exception.h

I know this was a hot topic of debate when it was first introduced, but I truly do not understand why there's a customized error/value wrapper thrown around the API. This is a C++ library, and it should use C++ features.

If we're opposed to exceptions for performance reasons (which doesn't make any sense in this context) we can adopt a non-half-baked version of StatusTuple, e.g. folly::Try https://github.com/facebook/folly/blob/master/folly/Try.h. I don't know why else we'd be opposed to exceptions.

StatusTuple is a crippled exception supporting only opaque integer codes and an overflow-prone char message buffer. Am I missing something?

If you have to wrap a small and basic abstraction in a macro to make it usable in the common case (see TRY2), it's not a useful abstraction.

**Comment by 4ast** [comment]
bcc is a C library in it's core, hence no exceptions allowed.

**Comment by jsedgwick** [comment]
@4ast - The portion of bcc that I'm referencing is not a C library - it's a C++ wrapper around a C library. Why no exceptions? Perhaps the BPF class and its friends should be moved into a separate cpp library to make this distinction clear?

**Comment by jsedgwick** [comment]
Also, that reasoning doesn't make sense if you replace exceptions with a (not-so-great) C++ class - StatusTuple.

**Comment by 4ast** [comment]
let's ask the question differently. What do we get by using exceptions? I see only negatives.
The main concern is never ending bugs due to complexity of frame unwind.
