### ISSUE TITLE
Separate perf event buffer readers from kprobe readers in Python API

### ISSUE THREAD

**Issue by palmtenor** [iovisor/bcc#1197]
I'm planning to improve Perf Event clean-up to make BCC more reliable.

I noticed in Python API, the `perf_reader` from `PerfEventArray.open_perf_buffer` are put into `BPF.open_kprobes`, along with `perf_reader` from actual kprobes. Also, in `BPF.kprobe_poll`, they are also being polled together.

Is this intentional? I would like to have a separated dict for the Perf Event buffer readers, are there any concerns for that?

cc @drzaeus77 @4ast

**Comment by drzaeus77** [comment]
They are treated the same because both regular kprobes and perf buffers can be polled, and hence have the same underlying perf_reader struct. See the test in tests/python/test_callchain.py, or the original commit #255
