### ISSUE TITLE
How can i get the information about tracepoint__net__netif_receive_skb

### ISSUE THREAD

**Issue by JerryChenBupt** [iovisor/bcc#1242]
I write a python program to test tracepoint net:netif_receive_skb. The c code is as follow:
```python
# load BPF program
b = BPF(text="""
TRACEPOINT_PROBE(net, netif_receive_skb) {
    bpf_trace_printk("%s\\n", args->name);
    return 0;
};
""")
```
The output is:
```
/virtual/main.c:9:36: error: no member named 'name' in 'struct tracepoint__net__netif_receive_skb'
    bpf_trace_printk("%s\n", args->name);
                             ~~~~  ^
1 error generated.
Traceback (most recent call last):
  File "./get_packet_protocol.py", line 12, in <module>
    """)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 294, in __init__
    raise Exception("Failed to compile BPF module %s" % src_file)
Exception: Failed to compile BPF module
```
I use `cat /sys/kernel/debug/tracing/events/net/netif_receive_skb/format` to see the format of this tracepoint. I get this:
```
name: netif_receive_skb
ID: 1172
format:
	field:unsigned short common_type;	offset:0;	size:2;	signed:0;
	field:unsigned char common_flags;	offset:2;	size:1;	signed:0;
	field:unsigned char common_preempt_count;	offset:3;	size:1;	signed:0;
	field:int common_pid;	offset:4;	size:4;	signed:1;

	field:void * skbaddr;	offset:8;	size:8;	signed:0;
	field:unsigned int len;	offset:16;	size:4;	signed:0;
	field:__data_loc char[] name;	offset:20;	size:4;	signed:1;

print fmt: "dev=%s skbaddr=%p len=%u", __get_str(name), REC->skbaddr, REC->len
```
But, how can i get the information about the struct `tracepoint__net__netif_receive_skb`?

**Comment by goldshtn** [comment]
Please see #928 - we added support for this a few months ago, but it's not automatic: you need to use a special macro to read the `__data_loc` fields, because of the way they are stored by the kernel.

**Comment by JerryChenBupt** [comment]
Thanks! Another question: If i want to see what is in struct tracepoint__net__netif_receive_skb.(Sometimes, things in it are different from the format i cat), what should i do?@goldshtn

**Comment by goldshtn** [comment]
You can add a debug flag to the BPF object constructor, and that would print out the resulting C program before it's being compiled. I'm writing this from memory but I think it's `debug=1` to see the C program.

**Comment by yonghong-song** [comment]
Actually, it is debug=4 to see the C program. debug=1 see the IR, debug=2
see the byte code back from verifier if any.
