### ISSUE TITLE
Can i use structs such as sk_buff *skb in TRACEPOINT_PROBE()

### ISSUE THREAD

**Issue by JerryChenBupt** [iovisor/bcc#1243]
Recently, i use `TRACEPOINT_PROBE()` to get access to the packets received by kernel. And it works.
But it seems that i can only get the specific struct given by the tracepoint. So, can i use structs such as `struct sk_buff *skb` in `TRACEPOINT_PROBE()`?( I want to change things in the packets!)

I can get access to `struct sk_buff *skb`  by kprobes:
```python
#!/usr/bin/python

from bcc import BPF

# load BPF program
b = BPF(text="""
#include <uapi/linux/ptrace.h>

int kprobe__netif_receive_skb(struct pt_regs *ctx, struct sk_buff *skb)
{
	bpf_trace_printk("Get a packet!\\n");
	return 0;
}
""", debug = 4)

# header
print("Tracing... Hit Ctrl-C to end.")

while 1:
	try:
		(task, pid, cpu, flags, ts, msg) = b.trace_fields()
	except ValueError:
		continue
	print("%s" % (msg))

```
Also, I can get some specific values like protocol by using `TRACEPOINT_PROBE()`:
```python
#!/usr/bin/python

from __future__ import print_function
from bcc import BPF

# load BPF program
b = BPF(text="""
TRACEPOINT_PROBE(net, netif_receive_skb_entry) {
    bpf_trace_printk("get a packet! protocol = %x\\n",args->protocol);
    return 0;
};
""", debug = 4)

# header
print("%-18s %-16s %-6s %s" % ("TIME(s)", "COMM", "PID", "GOTBITS"))

# format output
while 1:
    try:
        (task, pid, cpu, flags, ts, msg) = b.trace_fields()
    except ValueError:
        continue
    print("%-18.9f %-16s %-6d %s" % (ts, task, pid, msg))
```

**Comment by yonghong-song** [comment]
On Tue, Jul 4, 2017 at 9:06 AM, JerryChenBupt <notifications@github.com> wrote:
>
> Recently, i use TRACEPOINT_PROBE() to get access to the packets received by kernel. And it works.
> But it seems that i can only get the specific struct given by the tracepoint. So, can i use structs such as struct sk_buff *skb in TRACEPOINT_PROBE()?( I want to change things in the packets!)

Yes, you can only access tracepoint structs with TRACEPOINT_PROBE.
There are a few kernel tracepoint functions you may access skb, but
not too many and they seems related to skb memory management instead
of packet processing.
