### ISSUE TITLE
zpl_read/zpl_write no longer exist

### ISSUE THREAD

**Issue by mmlb** [iovisor/bcc#1248]
Removed in https://github.com/zfsonlinux/zfs/commit/933ec999511f3d29de005bfa8966ae007b161c0f.

**Comment by goldshtn** [comment]
@brendangregg This probably breaks the zfs tools.

**Comment by mmlb** [comment]
So, the fix is pretty simple rename of a couple of functions in zfs* tools. But it won't be backwards compatible with previous releases of zol. There is module version I can check under /sys, and generate the correct program based on the value found, is that the correct/only solution?

**Comment by goldshtn** [comment]
@mmlb: I think it would preferable to just look for the symbol itself. You can use `BPF.get_kprobe_functions` with a regex.

**Comment by mmlb** [comment]
Thanks @goldshtn I'll checkout/go that route then.

**Comment by mskarbek** [comment]
Any news on that?

**Comment by mmlb** [comment]
@mskarbek sorry no, I haven't had the time to look into this.
