### ISSUE TITLE
[question] Is there a way to call ``perf_submit`` from a ``TRACEPOINT_PROBE``?

### ISSUE THREAD

**Issue by yadutaf** [iovisor/bcc#1251]
Sorry if this is not the appropriate place to ask a question. I am looking for a way to sent perf events from a TRACEPOINT_PROBE like:

```c
// Event structure
struct route_evt_t {
    /* Event data */
};
BPF_PERF_OUTPUT(route_evt);

TRACEPOINT_PROBE(net, netif_rx) {
    // Load some fields
    struct sk_buff *skb = args->skbaddr;
    struct net_device *dev = skb->dev;

    // Build and send event
    struct route_evt_t evt = {}; 
    route_evt.perf_submit(ctx, &evt, sizeof(evt));
}
```

This will obviously fail as there is no ``ctx`` here.

I also tried with something like ``route_evt.perf_submit_skb(skb, skb->len, sizeof(evt));`` introduced by commit bdad3840c02db5b93a2c39f26fb01f916caf94df with support from kernel 3.7 on a 3.10 kernel with no success.

The ultimate goal is to trace interfaces crossed by a "ping" as a tool to debug Linux inner networking. My current implementation works as a kprobe on ``dev_hard_start_xmit`` and ``__dev_forward_skb`` but it still misses packets going from a veth to a bridge or incoming a wireless interface and most common points are static and/or inline and hence non traceable.

Do you have any advice?

**Comment by goldshtn** [comment]
`TRACEPOINT_PROBE` hides some details from you but it takes an `args` parameter which you can use in lieu of `ctx` in your example, if I remember correctly. In any case tracepoints are only supported as BPF attach targets since 4.7.

**Comment by yadutaf** [comment]
Indeed. Thanks! (I meant 4.7 and 4.10)
