### ISSUE TITLE
Is there any helper function in bpf for ip checksum?

### ISSUE THREAD

**Issue by JerryChenBupt** [iovisor/bcc#1253]
I change the ip header `tos` field in the bpf program. **It works**. 

But this change requires the update of **ip checksum**. 

I searched the helper function in bpf. I only found the function `bpf_l3_csum_replace()`. But i can't use the kernel function like `ip_fast_csum()` and `ip_compute_csum()` in the bpf program. 

**So, do i really have to implement the code myself?**

**Comment by mauriciovasquezbernal** [comment]
`bpf_l3_csum_replace()` should suffice your needs in this case, it expects the old and new value of a field in the header, this example in [1] is possibly that you need:

```
static inline void set_ip_tos(struct __sk_buff *skb, __u8 new_tos)
{
  __u8 old_tos = load_byte(skb, TOS_OFF);
  
  bpf_l3_csum_replace(skb, IP_CSUM_OFF, htons(old_tos), htons(new_tos), 2);
  bpf_skb_store_bytes(skb, TOS_OFF, &new_tos, sizeof(new_tos), 0);
}
```

[1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=91bc4822c3d61b9bb7ef66d3b77948a4f9177954

**Comment by borkmann** [comment]
You can also use bpf_csum_diff() and then feed the diff to bpf_l3_csum_replace() or bpf_l4_csum_replace().

**Comment by JerryChenBupt** [comment]
Thanks indeed!
