### ISSUE TITLE
(dbslower/dbstat) Exception: Failed to compile BPF module

### ISSUE THREAD

**Issue by kirantpatil** [iovisor/bcc#1254]
When I run dbslower/dbstat with postgres as below, it is showing an error. But if I provide PID it runs.

Environment:
```
fueb@localhost:~$ stap --version
Systemtap translator/driver (version 2.9/0.165, Debian version 2.9-2ubuntu2 (xenial))
Copyright (C) 2005-2015 Red Hat, Inc. and others
This is free software; see the source for copying conditions.
enabled features: AVAHI LIBSQLITE3 NLS NSS TR1_UNORDERED_MAP

fueb@localhost:~$ uname -a
Linux localhost 4.8.0-58-generic #63~16.04.1-Ubuntu SMP Mon Jun 26 18:08:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

fueb@localhost:~$ cat /etc/issue
Ubuntu 16.04.2 LTS \n \l

fueb@localhost:~$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

### fueb@localhost:~$ ps -e | grep postgres
---
31132 pts/1    00:00:00 postgres
31134 ?        00:00:00 postgres
31135 ?        00:00:00 postgres
31136 ?        00:00:00 postgres
31137 ?        00:00:00 postgres
31138 ?        00:00:00 postgres

### fueb@localhost:~$ sudo /usr/share/bcc/tools/dbslower  postgres 
---
/virtual/main.c:13:28: error: redefinition of '_bpf_readarg_probe_start_1'
static __always_inline int _bpf_readarg_probe_start_1(struct pt_regs *ctx, void *dest, size_t len) {
                           ^
/virtual/main.c:2:28: note: previous definition is here
static __always_inline int _bpf_readarg_probe_start_1(struct pt_regs *ctx, void *dest, size_t len) {
                           ^
/virtual/main.c:18:28: error: redefinition of '_bpf_readarg_probe_end_1'
static __always_inline int _bpf_readarg_probe_end_1(struct pt_regs *ctx, void *dest, size_t len) {
                           ^
/virtual/main.c:7:28: note: previous definition is here
static __always_inline int _bpf_readarg_probe_end_1(struct pt_regs *ctx, void *dest, size_t len) {
                           ^
2 errors generated.
Traceback (most recent call last):
  File "/usr/share/bcc/tools/dbslower", line 113, in <module>
    bpf = BPF(text=program, usdt_contexts=usdts)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 294, in __init__
    raise Exception("Failed to compile BPF module %s" % src_file)
Exception: Failed to compile BPF module 

### fueb@localhost:~$ sudo /usr/share/bcc/tools/dbslower -m 1000 postgres -p 31138
---
Tracing database queries for pids 31138 slower than 1000 ms...
TIME(s)        PID          MS QUERY

### fueb@localhost:~$ sudo /usr/share/bcc/tools/dbstat postgres
---
/virtual/main.c:13:28: error: redefinition of '_bpf_readarg_probe_start_1'
static __always_inline int _bpf_readarg_probe_start_1(struct pt_regs *ctx, void *dest, size_t len) {
                           ^
/virtual/main.c:2:28: note: previous definition is here
static __always_inline int _bpf_readarg_probe_start_1(struct pt_regs *ctx, void *dest, size_t len) {
                           ^
/virtual/main.c:18:28: error: redefinition of '_bpf_readarg_probe_end_1'
static __always_inline int _bpf_readarg_probe_end_1(struct pt_regs *ctx, void *dest, size_t len) {
                           ^
/virtual/main.c:7:28: note: previous definition is here
static __always_inline int _bpf_readarg_probe_end_1(struct pt_regs *ctx, void *dest, size_t len) {
                           ^
2 errors generated.
Traceback (most recent call last):
  File "/usr/share/bcc/tools/dbstat", line 95, in <module>
    bpf = BPF(text=program, usdt_contexts=usdts)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 294, in __init__
    raise Exception("Failed to compile BPF module %s" % src_file)
Exception: Failed to compile BPF module 

### fueb@localhost:~$ sudo /usr/share/bcc/tools/dbstat postgres -p 31138
---
Tracing database queries for pids 31138 slower than 0 ms...

**Comment by kirantpatil** [comment]
Postgres is compiled with --enable-dtrace.

### fueb@localhost:~$ sudo /usr/share/bcc/tools/tplist -p $(pgrep -n postgres)
/usr/local/pgsql/bin/postgres postgresql:clog__checkpoint__start
/usr/local/pgsql/bin/postgres postgresql:clog__checkpoint__done
/usr/local/pgsql/bin/postgres postgresql:multixact__checkpoint__start
/usr/local/pgsql/bin/postgres postgresql:multixact__checkpoint__done
/usr/local/pgsql/bin/postgres postgresql:subtrans__checkpoint__start
/usr/local/pgsql/bin/postgres postgresql:subtrans__checkpoint__done
/usr/local/pgsql/bin/postgres postgresql:twophase__checkpoint__start
/usr/local/pgsql/bin/postgres postgresql:twophase__checkpoint__done
/usr/local/pgsql/bin/postgres postgresql:transaction__start
/usr/local/pgsql/bin/postgres postgresql:transaction__commit
/usr/local/pgsql/bin/postgres postgresql:transaction__abort
/usr/local/pgsql/bin/postgres postgresql:wal__buffer__write__dirty__start
/usr/local/pgsql/bin/postgres postgresql:wal__buffer__write__dirty__done
/usr/local/pgsql/bin/postgres postgresql:xlog__switch
/usr/local/pgsql/bin/postgres postgresql:checkpoint__start
/usr/local/pgsql/bin/postgres postgresql:checkpoint__done
/usr/local/pgsql/bin/postgres postgresql:xlog__insert
/usr/local/pgsql/bin/postgres postgresql:statement__status
/usr/local/pgsql/bin/postgres postgresql:buffer__flush__start
/usr/local/pgsql/bin/postgres postgresql:buffer__flush__done
/usr/local/pgsql/bin/postgres postgresql:buffer__read__start
/usr/local/pgsql/bin/postgres postgresql:buffer__read__done
/usr/local/pgsql/bin/postgres postgresql:buffer__write__dirty__start
/usr/local/pgsql/bin/postgres postgresql:buffer__write__dirty__done
/usr/local/pgsql/bin/postgres postgresql:buffer__sync__done
/usr/local/pgsql/bin/postgres postgresql:buffer__sync__start
/usr/local/pgsql/bin/postgres postgresql:buffer__sync__written
/usr/local/pgsql/bin/postgres postgresql:buffer__checkpoint__start
/usr/local/pgsql/bin/postgres postgresql:buffer__checkpoint__sync__start
/usr/local/pgsql/bin/postgres postgresql:buffer__checkpoint__done
/usr/local/pgsql/bin/postgres postgresql:lock__wait__start
/usr/local/pgsql/bin/postgres postgresql:lock__wait__done
/usr/local/pgsql/bin/postgres postgresql:deadlock__found
/usr/local/pgsql/bin/postgres postgresql:lwlock__wait__start
/usr/local/pgsql/bin/postgres postgresql:lwlock__wait__done
/usr/local/pgsql/bin/postgres postgresql:lwlock__acquire
/usr/local/pgsql/bin/postgres postgresql:lwlock__condacquire
/usr/local/pgsql/bin/postgres postgresql:lwlock__condacquire__fail
/usr/local/pgsql/bin/postgres postgresql:lwlock__acquire__or__wait
/usr/local/pgsql/bin/postgres postgresql:lwlock__acquire__or__wait__fail
/usr/local/pgsql/bin/postgres postgresql:lwlock__release
/usr/local/pgsql/bin/postgres postgresql:smgr__md__read__start
/usr/local/pgsql/bin/postgres postgresql:smgr__md__read__done
/usr/local/pgsql/bin/postgres postgresql:smgr__md__write__start
/usr/local/pgsql/bin/postgres postgresql:smgr__md__write__done
/usr/local/pgsql/bin/postgres postgresql:query__parse__start
/usr/local/pgsql/bin/postgres postgresql:query__parse__done
/usr/local/pgsql/bin/postgres postgresql:query__rewrite__start
/usr/local/pgsql/bin/postgres postgresql:query__rewrite__done
/usr/local/pgsql/bin/postgres postgresql:query__plan__start
/usr/local/pgsql/bin/postgres postgresql:query__plan__done
/usr/local/pgsql/bin/postgres postgresql:query__start
/usr/local/pgsql/bin/postgres postgresql:query__done
/usr/local/pgsql/bin/postgres postgresql:query__execute__start
/usr/local/pgsql/bin/postgres postgresql:query__execute__done
/usr/local/pgsql/bin/postgres postgresql:sort__start
/usr/local/pgsql/bin/postgres postgresql:sort__done

**Comment by goldshtn** [comment]
Thanks for the report, @kirantpatil. Unfortunately that's a known bug with attaching to the same USDT probe in multiple processes; it's tracked here: https://github.com/iovisor/bcc/issues/1106

For now, you can use the `-p` parameter, as you discovered.

**Comment by kirantpatil** [comment]
Thanks @goldshtn.
