### ISSUE TITLE
RFC: Remove cpu / pid parameters from probe interfaces

### ISSUE THREAD

**Issue by palmtenor** [iovisor/bcc#1278]
Kernel `TRACEPOINT` type events (which includes kprobes, uprobes and Kernel Tracepoint probes) do not seem to support to be created per-CPU or per-task. All script tools needing CPU / Process filtering are all doing so within the BPF program. However, BCC's probe user APIs (C / C++ / Python) all have `pid` and `cpu` parameters, and they don't seem to make any difference.

I could guess that is in order to make BCC APIs look similar to `perf_event_open`. However that is creating some confusions for new users as they would expect passing the `cpu` / `pid` parameters would make the probes only attach on particular CPU / Process, but they "don't actually work".

Would it be good for us to remove `pid` and `cpu` parameters from C / C++ / Python's probe-attaching interfaces? Probably except for `pid` on uprobes as it is used for event name alias / USDT since #1263 / #1270 

cc @4ast @drzaeus77 @yonghong-song

**Comment by pchaigno** [comment]
> I could guess that is in order to make BCC APIs look similar to `perf_event_open`.

`bpf_attach_kprobe` [may call `bpf_attach_tracing_event`](https://github.com/iovisor/bcc/blob/861102b4372cadef3d7ee9a03fe46bdbdcf37565/src/cc/libbpf.c#L428), which itself [calls `perf_event_open`](https://github.com/iovisor/bcc/blob/861102b4372cadef3d7ee9a03fe46bdbdcf37565/src/cc/libbpf.c#L364). The same happens with [`bpf_attach_uprobe`](https://github.com/iovisor/bcc/blob/861102b4372cadef3d7ee9a03fe46bdbdcf37565/src/cc/libbpf.c#L551).

**Comment by palmtenor** [comment]
Correct, `bpf_attach_tracing_event` handles all `TRACEPOINT` events by BCC, including kprobes, uprobes and Kernel Tracepoint probes. My guess is that `bpf_attach_tracing_event` has `pid` / `cpu` parameter just so that it could pass to the underlying `perf_event_open`, and then they got populated to upper level API functions
