### ISSUE TITLE
tcpv4connect example not working

### ISSUE THREAD

**Issue by mccormickt12** [iovisor/bcc#1281]
In file included from /virtual/main.c:3:
In file included from include/net/sock.h:51:
In file included from include/linux/netdevice.h:38:
In file included from include/linux/dmaengine.h:20:
In file included from include/linux/device.h:24:
In file included from include/linux/pinctrl/devinfo.h:21:
In file included from include/linux/pinctrl/consumer.h:17:
In file included from include/linux/seq_file.h:10:
include/linux/fs.h:2659:9: warning: comparison of unsigned enum expression < 0 is always false
      [-Wtautological-compare]
        if (id < 0 || id >= READING_MAX_ID)
            ~~ ^ ~
1 warning generated.

______INFO_______
uname -r
4.10.0-27-generic

ubuntu 16

Its just a warning so i tried the example, but even when I create traffic to the box running the program, nothing is printed. I can see the traffic in tcpdump and the connection goes through.

**Comment by alban** [comment]
> I create traffic to the box

If they are incoming connections, they would not be traced by tcpconnect but by tcpaccept.

Could you try with the other tools [tcpaccept](https://github.com/iovisor/bcc/blob/master/tools/tcpaccept_example.txt) and [tcptracer](https://github.com/iovisor/bcc/blob/master/tools/tcptracer_example.txt) and see if there is still no output?

**Comment by mccormickt12** [comment]
Yes, i confirmed i was using it backwards. When I send traffic tcpconnect works. The tcpaccept doesn't seem to work for me though. And the tcptracer worked for both, inbound and outbound.

thanks

**Comment by brendangregg** [comment]
sounds like not an issue. closing.
