### ISSUE TITLE
Weird results if frequency/accuracy of biotop is increased from 1s to 10ms

### ISSUE THREAD

**Issue by HarryWei** [iovisor/bcc#1304]
Currently, biotop traces processes' disk I/O information every 1 second by default but this frequency is not accuracy sometimes. Therefore, I change the frequency of biotop to trace processes' disk I/O information every 10 milliseconds but the output of 'AVGms' is weird as follows. I cannot understand why the 'AVGms' can be more than 10ms since 'AVGms' just traces the time cost of each I/O in average during a time duration of 10ms, and 'AVGms' is far more than 10 ms in my experiments, which will be 100+ms as follows. 

```
PID    COMM             D MAJ MIN DISK       I/O  Kbytes  AVGms
9056   dd               W 253 0   vda         14   14336 138.17 
10:22:47 loadavg: 0.75 0.36 0.16 1/168 9339

PID    COMM             D MAJ MIN DISK       I/O  Kbytes  AVGms
9056   dd               W 253 0   vda          8    8192 156.73 
10:22:47 loadavg: 0.75 0.36 0.16 1/168 9340

PID    COMM             D MAJ MIN DISK       I/O  Kbytes  AVGms
10:22:47 loadavg: 0.75 0.36 0.16 1/168 9341

PID    COMM             D MAJ MIN DISK       I/O  Kbytes  AVGms
10:22:47 loadavg: 0.75 0.36 0.16 2/168 9342

PID    COMM             D MAJ MIN DISK       I/O  Kbytes  AVGms
9056   dd               W 253 0   vda         16   16384 109.19 
9056   dd               R 253 0   vda          1       4 103.53 
10:22:47 loadavg: 0.75 0.36 0.16 1/168 9343

PID    COMM             D MAJ MIN DISK       I/O  Kbytes  AVGms
9056   dd               W 253 0   vda         16   16384 152.37 
10:22:47 loadavg: 0.75 0.36 0.16 1/168 9344

PID    COMM             D MAJ MIN DISK       I/O  Kbytes  AVGms
10:22:47 loadavg: 0.75 0.36 0.16 1/168 9345

PID    COMM             D MAJ MIN DISK       I/O  Kbytes  AVGms
9056   dd               W 253 0   vda         16   16384  93.31 
10:22:47 loadavg: 0.75 0.36 0.16 1/168 9346

PID    COMM             D MAJ MIN DISK       I/O  Kbytes  AVGms
9056   dd               W 253 0   vda         16   16384 135.92 
```

Improve the frequency of biotop from 1 second to 10 ms.
```
...
while 1:
    try:
        sleep(10.0/1000.0)
    except KeyboardInterrupt:
        exiting = 1
...
```

System Environments

1. I compile bcc from source codes, and the version is v0.3.0.
2.  $ lsb_release -a
       No LSB modules are available.
       Distributor ID:	Ubuntu
       Description:	Ubuntu 14.04.4 LTS
       Release:	14.04
       Codename:	trusty
3. $ uname -r
       4.7.4

**Comment by brendangregg** [comment]
You've changed the reporting frequency, but the I/O latency itself may well be over 100ms. In each 10ms reporting interval, it summarizes those >100ms I/O that completed during that 10ms interval. This includes tracking their start times from well before that interval.

For more detailed reporting, you might want to switch to biosnoop.

**Comment by HarryWei** [comment]
Hi Brendan,

Thank you for your comments. I have understood it. Yes, it should be because the I/O latency of my workload itself is more than 100ms for each I/O. I will look into biosnoop and close this issue since it is related to my test workload rather than biotop itself. Thank you.
