### ISSUE TITLE
map.increment() is not performance efficient.

### ISSUE THREAD

**Issue by 4ast** [iovisor/bcc#1314]
currently map.increment(&key); does
update(zero, noexist);
if (leaf) *(leaf)++;
so it's hitting spinlocks() in the hashmap for every increment,
we should change it to
leaf = lookup(key)
if (leaf) *(leaf)++; else update(zero);
to avoid spinlocks for all increments.

**Comment by yonghong-song** [comment]
> leaf = lookup(key)
> if (leaf) *(leaf)++; else update(zero); 

I guess the above "update(zero)" should be "update(one)?

**Comment by 4ast** [comment]
ahh. yes :)

**Comment by drzaeus77** [comment]
I have a patch for this ready, unless @yonghong-song wants to take care of it in a particular way.

**Comment by yonghong-song** [comment]
@drzaeus77  go ahead to proceed with your patch. What I will do is exactly like the above @4ast suggested change.
