### ISSUE TITLE
Add support to Map-in-Map in BCC

### ISSUE THREAD

**Issue by palmtenor** [iovisor/bcc#1318]
`BPF_MAP_TYPE_ARRAY_OF_MAPS` and `BPF_MAP_TYPE_HASH_OF_MAPS` were introduced in Kernel a few months ago. They are useful in many production scenarios and I'm planning to work on adding support to them in BCC. Opening an issue here for discussion on best approach for implementation, easy to use interface and reduce possible duplicated work.

### Creation
- Map-in-Map tables require an existing inner map instance as "template" at creation time. This means we would probably need to do two passes of `VisitVarDecl`, first one creating all normal tables and second time use FD of the created table to create the Map-in-Map table. Any suggestion on how to do this more effectively without complicating the rewriter code too much?
- If I understand correctly, Map-in-Map tables only need and will store the attributes of the template inner map, and won't need it anymore after creation. So if user create a table only for templating Map-in-Map, should we provide the option to free that map after creating the Map-in-Map table to save memory?
- What would be the best user interface? Would it be better to extend current `struct` defined by `BPF_F_TABLE` for new field (`inner_map_fd`), or have separated helper Macros / `struct` for Map-in-Map tables?

### Access
Updating and deleting elements for Map-in-Map tables from user space (through syscall) seems straightforward and just like other FD arrays we have now.

However, within the BPF program, lookup result from Map-in-Map table would be FD of the inner map, and currently it's not obvious to users how to access the inner map using a FD. Users could call `bpf_map_xyz_elem_(bpf_pseudo_fd(...` directly, but that doesn't feel like very nice to use. Users would probably like to keep using the familiar `map. lookup_or_init`, `map.update`, etc. interfaces just like other tables, but we would probably need some new structs so that the rewriter would convert them correctly without knowing the lookup result at compile time. What do you think would be the best approach to handle this?

cc @drzaeus77 @yonghong-song @4ast

**Comment by pchaigno** [comment]
> This means we would probably need to do two passes of `VisitVarDecl`, first one creating all normal tables and second time use FD of the created table to create the Map-in-Map table.

I've had a similar issue in #1285, where I needed to go through all map helpers in a first time, before replacing dereferences. To perform the two passes on the AST without parsing it twice, I relied on `HandleTranslationUnit`, which is called after a whole translation unit has been parsed. In this way, the first pass happens with `HandleTopLevelDecl`, the second with `HandleTranslationUnit`.

Not sure that's the best approach, but it's probably worth noting that there might be other needs for two passes.

> Users would probably like to keep using the familiar `map.lookup_or_init`, `map.update`, etc. interfaces just like other tables, but we would probably need some new structs so that the rewriter would convert them correctly without knowing the lookup result at compile time.

What about an alias for the type of map-in-map FDs? That would significantly ease the rewriter's job when converting map accesses. Trying to infer the origin of variables without help from developers is what the rewriter currently does for `bpf_probe_read`s. It becomes pretty complex if you try to handle all cases...

**Comment by mauriciovasquezbernal** [comment]
Hello @palmtenor,

Thanks for starting the discussion, we are also interested in having this support in BCC.
> If I understand correctly, Map-in-Map tables only need and will store the attributes of the template inner map, and won't need it anymore after creation. So if user create a table only for templating Map-in-Map, should we provide the option to free that map after creating the Map-in-Map table to save memory?

As a user I'll be only interested in the map-of-maps, the map used as template would not be useful for me. So I think we could directly close it without asking the user.

> What would be the best user interface? Would it be better to extend current struct defined by BPF_F_TABLE for new field (inner_map_fd), or have separated helper Macros / struct for Map-in-Map tables?

I think it is more clear to have a separated set of macros, `BPF_HASH_OF_MAPS` and `BPF_ARRAY_OF_MAPS` for example, thee macros should accept all the configuration parameters for both, the outside and the inside maps.

> Users could call bpf_map_xyz_elem_(bpf_pseudo_fd(... directly, but that doesn't feel like very nice to use

I completely agree, we should extend `map.lookup`, `map.delete` etc... to support it in a better way.

> Updating and deleting elements for Map-in-Map tables from user space (through syscall) seems straightforward and just like other FD arrays we have now.

Have you considered how the C++ api could look like?. I am curious about what could be a possible implementation.

**Comment by yonghong-song** [comment]
@palmtenor thanks for taking initiative on this. @pchaigno  and @mauriciovasquezbernal already have good comments. Just had a couple of additional points.
  . Reuse the existing interface as much as possible. But if the outer map carries unique semantics, it will be worthwhile to creat its own.
  . You can free the template inner map fd. However, you may not know that unless user tells you. But if it is the common use case, you can add a construct to let users to explicitly specify the template inner map id so you know you can free it after outer map is created.

**Comment by palmtenor** [comment]
@HousedHorse Sorry for the delay. I have been having some personal issues and probably won't be able to get to this in a few weeks:(

**Comment by palmtenor** [comment]
I got the creation flow worked out. You just need to define the inner-Map before the outer-Map, and I just looked up the inner-Map's FD by name, which is pretty easy.

Updating is also not so hard (either in BPF program or in User space), just need to lookup the FD and rewrite correctly.

Accessing the lookup result is the tricky part. I have tried a few approaches but none of them work nicely.

For regular Maps, BCC Macros has a `struct _name##_table_t` defined for each of them and rewriting is done at member function of it. For the Map-in-Map lookup result, we only get back an FD.

One of the approach I tried is to have the outer-Map's `lookup` method return
```
struct inner_map_t {
  int fd;
  ALL_OTHER_MAP_MEMBER_FUNCTIONS
};
```
and rewrite the outer-Map's `lookup` method to create such a struct and put the returned FD in the `fd` field. Then I plan to change the `VisitCallExpr` rewriting to differentiate if a call (like `update`) is from a regular Map struct or from an inner-Map struct, and if later use the struct's `fd` field instead of looking up from `TableDesc`. This needs a lot of changes, but I think I could get it done. However, the issue is all of our Map struct member function came with the correct returning key / leaf type (like ` _leaf_type * (*lookup) (_key_type *);`), which I have no way of getting from just the FD on-the-fly:(

@yonghong-song What do you think?

**Comment by HousedHorse** [comment]
@palmtenor Do you have a partially completed solution we could look at?

**Comment by yonghong-song** [comment]
@palmtenor do you have time working on this or do you have any partial codes which can be shared here? We have internal requests to use map-in-map in bcc. It would be great if you can post your work (even wip) so we can iterate and get it done. Thanks!

**Comment by palmtenor** [comment]
@yonghong-song Sorry I was traveling for the past two weeks and just got back home. I see you already got a version of implementation in #2612. I will take a look in a bit and see if I can make it better for C++ API. Will ping you offline, thanks a lot!
