### ISSUE TITLE
Add macro for BPF_HASH

### ISSUE THREAD

**Issue by drzaeus77** [iovisor/bcc#135]
It's nice to have a lot of control over BPF maps, but I wonder if we
could have some simplified macros for the really common cases, like: hash
of one key -> u64.

Before:
```c
struct key_t {
  struct request *req;
};
BPF_TABLE("hash", struct key_t, u64, start, 10240);
```
After:
```
BPF_HASH(start, struct request *);
```

Where the name is "start", the single key is "struct request *", and it
assumes the value is u64 (common case), and there is a global default for
number of entries (10240). If people want to customize, then do BPF_TABLE.

**Comment by brendangregg** [comment]
Or even supporting both explicit or implicit value types (3rd argument optional):

{code}
BPF_HASH(start, struct request *, u64);
BPF_HASH(start, struct request *);
{code}

**Comment by brendangregg** [comment]
This has been working, so the ticket can be closed.

It works for hashes that exist only for the C program; eg, temporarily storing timestamps.

I hit issues accessing a BPF_HASH() key (when a key_t is not in use, like in the example above) from Python, complaining about it not being c_int, but that can be a separate issue.

**Comment by drzaeus77** [comment]
For the python case you mentioned, what I tend to do is wrap things that should be a ctype with a Table.Key() or Table.Leaf() type.

For instance, if Key is a complex type like `struct { int a; int b; }`:
```python
b["stats"][b["stats"].Key(0, 1)] = b["stats"].Leaf(42)
```
