### ISSUE TITLE
probe of c++ function

### ISSUE THREAD

**Issue by axot** [iovisor/bcc#1362]
How to trace a c++ function like `a::b::c` in trace.py ?

**Comment by goldshtn** [comment]
You need to use the mangled name of the function. I usually run `objdump -tT myfile` to find the desired symbol name.

**Comment by palmtenor** [comment]
Alternatively, defined a [USDT Tracepoint](http://www.brendangregg.com/blog/2015-07-03/hacking-linux-usdt-ftrace.html) in the function for more stable probe and better experience.

**Comment by axot** [comment]
Thank you, mangled name works. Using USDT Tracepoint may a easy way for debugging!

**Comment by bveldhoen** [comment]
I'm aware this is a closed issue, but I'm running into a question that seems relevant here. I can't get funclatency to work **with function symbols** in the usdt_sample C++ binary:

```
~/src/projects/bcc/tools$ objdump -tT ../examples/usdt_sample/build_gcc/usdt_sample_app1/usdt_sample_app1 | grep executeAsync
0000000000000000       F *UND*  0000000000000000              _ZN17OperationProvider12executeAsyncERK16OperationRequest
0000000000000000      DF *UND*  0000000000000000              _ZN17OperationProvider12executeAsyncERK16OperationRequest
~/src/projects/bcc/tools$ pidof usdt_sample_app1
1391792
~/src/projects/bcc/tools$ sudo python3 ./funclatency.py _ZN17OperationProvider12executeAsyncERK16OperationRequest -p $(pidof usdt_sample_app1)
Traceback (most recent call last):
  File "./funclatency.py", line 349, in <module>
    b.attach_kprobe(event_re=pattern, fn_name="trace_func_entry")
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 823, in attach_kprobe
    raise Exception("Failed to attach BPF program %s to kprobe %s" %
Exception: Failed to attach BPF program b'trace_func_entry' to kprobe 
```

(I understand that this would only measure the latency of the executeAsync method itself, not of the entire operation, as is done in the usdt_sample using the probes; I'm looking to use function symbols in an entirely unrelated scenario, and trying to understand how to make it work in C++ binaries). 

Is there something I can do to make this work using symbols?

Any help is much appreciated, thanks in advance!

**Comment by chenhengqi** [comment]
Look like you have wrong parameters to funclatency.

Try `/path/to/binary:symbol_name` instead.

**Comment by bveldhoen** [comment]
Thank you, that seems to work.

`./funclatency.py ~/src/projects/bcc/examples/usdt_sample/build_gcc/usdt_sample_lib1/libusdt_sample_lib1.so:_ZN17OperationProvider12executeAsyncERK16OperationRequest -p $(pidof usdt_sample_app1)
`
