### ISSUE TITLE
Add macro for BPF_COUNTER

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#138]
Instead of this code (C):

``` C
enum stat_types {
    S_COUNT = 1,
    S_MAXSTAT
};

BPF_TABLE("array", int, u64, stats, S_MAXSTAT + 1);
```

This could be just:

``` C
BPF_COUNTER(count);
```

Where the name is "count".

There could then be a macro for incrementing BPF_COUNTERs. Eg (two examples):

``` C
BPF_INC(count);
BPF_INC(sum, value);
```

And/or, an increment BPF helper:

``` C
count.increment(1);
sum.increment(value);
```

**Comment by pchaigno** [comment]
Is this addressed by #247?

**Comment by bobrik** [comment]
This one looks like it's safe to close.

**Comment by yonghong-song** [comment]
Close this one, issue #1742 is opened for increment for a particular value.
