### ISSUE TITLE
dotnet core program symbol resolving support

### ISSUE THREAD

**Issue by sillyousu** [iovisor/bcc#1381]
```
sudo python stackcount.py -p  `pgrep dotnet` '/home/su21/project/bcclab/console_app/bin/Debug/netcoreapp2.0/console_app.dll:console_app.Program::Work'

Too many ':'-separated components in pattern /home/su21/project/bcclab/console_app/bin/Debug/netcoreapp2.0/console_app.dll:console_app.Program::Work
```
stackcount can't handle dotnet  program symbol correctly.

```
 sudo python stackcount.py -p  `pgrep dotnet` '/home/su21/project/bcclab/console_app/bin/Debug/netcoreapp2.0/console_app.dll:*Work*'

No functions matched by pattern ^.*Work.*$
```
It seems bcc symbol resolving doesn't  work with perf map.

**Comment by yonghong-song** [comment]
Hi, @sillyousu Could you provide a self-contained example? This way, people will be able to help and possibly fix it in bcc if there is an issue. Thanks!

**Comment by palmtenor** [comment]
> It seems bcc symbol resolving doesn't work with perf map.

BCC uses perf map for address to symbol resolution. I don't think we can use it for symbol name to binary offset resolution as we are using here for uprobe, because perf map normally contains virtual addresses, and uprobe needs offset of binary. Given an entry in the perf map, it's even unclear which binary (exectuable, shared object) that entry belongs to.

So your binary (`console_app.dll`) is fully stripped without any symbol, but it outputs perf map? That's an unusual behavior......

**Comment by sillyousu** [comment]
>Hi, @sillyousu Could you provide a self-contained example? This way, people will be able to help and possibly fix it in bcc if there is an issue. Thanks!
working on this.

>So your binary (console_app.dll) is fully stripped without any symbol, but it outputs perf map? That's an unusual behavior......
console_app.dll is a dotnet assembly, not a native ELF binary.

file console_app.dll:
PE32 executable (console) Intel 80386 Mono/.Net assembly, for MS Windows

**Comment by sillyousu** [comment]
>BCC uses perf map for address to symbol resolution. I don't think we can use it for symbol name to binary offset resolution as we are using here for uprobe, because perf map normally contains virtual addresses, and uprobe needs offset of binary. Given an entry in the perf map, it's even unclear which binary (exectuable, shared object) that entry belongs to.

hello @palmtenor , 
Is that means we can't probe user function  on VM (like Java, dotnet core, python)?

**Comment by goldshtn** [comment]
Yes, uprobes will not currently work for anything that’s not backed by a file on disk. This has been brought up here before, and unfortunately isn’t supported by the kernel.

**Comment by sillyousu** [comment]
closing. 
uprobes doesn't work with functions in VM.
thanks to all!

**Comment by palmtenor** [comment]
> PE32 executable (console) Intel 80386 Mono/.Net assembly, for MS Windows

That's not gonna work well lol:)
