### ISSUE TITLE
dbstat / dbslower don't work with PostgreSQL 10

### ISSUE THREAD

**Issue by afiskon** [iovisor/bcc#1392]
Hi,

I'm trying to use dbstat and dbslower with PostgreSQL 10 but neither utility works:

```
$ /usr/share/bcc/tools/dbstat postgres -p 1495
Traceback (most recent call last):
  File "/usr/share/bcc/tools/dbstat", line 88, in <module>
    usdt.enable_probe("query__start", "probe_start")
  File "/usr/lib/python3.6/site-packages/bcc/usdt.py", line 146, in enable_probe
    probe
bcc.usdt.USDTException: failed to enable probe 'query__start'; a possible cause can be that the probe requires a pid to enable

$ sudo /usr/share/bcc/tools/dbslower postgres -p 1495
Traceback (most recent call last):
  File "/usr/share/bcc/tools/dbslower", line 186, in <module>
    usdt.enable_probe("query__start", "query_start")
  File "/usr/lib/python3.6/site-packages/bcc/usdt.py", line 146, in enable_probe
    probe
bcc.usdt.USDTException: failed to enable probe 'query__start'; a possible cause can be that the probe requires a pid to enable
```

I'm using Arch Linux x64 with kernel 4.13.3. PostgreSQL is compiled from source (branch name REL_10_STABLE) using quick-build.sh and single-install.sh scripts from [pgscripts](https://github.com/afiskon/pgscripts) repository. (I'm a full-time PostgreSQL developer, this is why I'm installing it in such a weird way).

Some piece of advice on what could be a reason of such a behavior or how to debug it would be much appreciated. Naturally I will be happy to provide any additional information that might help.

**Comment by goldshtn** [comment]
I'm sorry for the possibly obvious suggestion, but did you build PostgreSQL with the USDT probes enabled? You can test by using `tplist -p $PID` or `readelf -n /path/to/postgres`.

**Comment by afiskon** [comment]
I'm sorry, it's my mistake. I didn't notice that I have to build dtrace4linux first.

As a side note it would be much more convenient if bcc included all necessary tools required to build a project with enabled USDT.

**Comment by goldshtn** [comment]
I think just SystemTap-dev is usually enough. The problem is really that some header files are required so I don’t know if bcc could or should ship with these files.
