### ISSUE TITLE
bcc does not compile (0.3.0-7bb52337, Fedora 26)

### ISSUE THREAD

**Issue by ldorau** [iovisor/bcc#1394]
$ cmake ..
-- The C compiler identification is GNU 7.2.1
-- The CXX compiler identification is GNU 7.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Latest recognized Git tag is v0.3.0
-- Git HEAD is 7bb52337cae18c4fc079970855dc6b67e3c7270d
-- Revision is 0.3.0-7bb52337
-- Performing Test HAVE_NO_PIE_FLAG
-- Performing Test HAVE_NO_PIE_FLAG - Success
-- Found BISON: /usr/bin/bison (found version "3.0.4") 
-- Found FLEX: /usr/bin/flex (found version "2.6.1") 
-- Found LLVM: /usr/include 4.0.1
-- Found LibElf: /usr/lib64/libelf.so  
-- Performing Test ELF_GETSHDRSTRNDX
-- Performing Test ELF_GETSHDRSTRNDX - Success
-- Found LuaJIT: /usr/lib64/libluajit-5.1.so;/usr/lib64/libdl.so;/usr/lib64/libm.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ldorau/work/bcc/build

$ make
Scanning dependencies of target bpf-shared
[  1%] Building C object src/cc/CMakeFiles/bpf-shared.dir/libbpf.c.o
[  2%] Building C object src/cc/CMakeFiles/bpf-shared.dir/perf_reader.c.o
/home/ldorau/work/bcc/src/cc/perf_reader.c: In function ‘read_data_head’:
/home/ldorau/work/bcc/src/cc/perf_reader.c:205:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   uint64_t data_head = *((volatile uint64_t *)&perf_header->data_head);
   ^~~~~~~~
[  3%] Linking C shared library libbpf.so
[  3%] Built target bpf-shared
Scanning dependencies of target bpf-static
[  4%] Building C object src/cc/CMakeFiles/bpf-static.dir/libbpf.c.o
[  5%] Building C object src/cc/CMakeFiles/bpf-static.dir/perf_reader.c.o
/home/ldorau/work/bcc/src/cc/perf_reader.c: In function ‘read_data_head’:
/home/ldorau/work/bcc/src/cc/perf_reader.c:205:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
   uint64_t data_head = *((volatile uint64_t *)&perf_header->data_head);
   ^~~~~~~~
[  6%] Linking C static library libbpf.a
[  6%] Built target bpf-static
Scanning dependencies of target bcc-loader-static
[  7%] Building CXX object src/cc/CMakeFiles/bcc-loader-static.dir/bcc_syms.cc.o
[  8%] Building C object src/cc/CMakeFiles/bcc-loader-static.dir/bcc_elf.c.o
[ 10%] Building C object src/cc/CMakeFiles/bcc-loader-static.dir/bcc_perf_map.c.o
[ 11%] Building C object src/cc/CMakeFiles/bcc-loader-static.dir/bcc_proc.c.o
[ 12%] Building CXX object src/cc/CMakeFiles/bcc-loader-static.dir/ns_guard.cc.o
[ 13%] Building CXX object src/cc/CMakeFiles/bcc-loader-static.dir/common.cc.o
[ 14%] Linking CXX static library libbcc-loader-static.a
[ 14%] Built target bcc-loader-static
Scanning dependencies of target clang_frontend
[ 15%] Building CXX object src/cc/frontends/clang/CMakeFiles/clang_frontend.dir/loader.cc.o
/home/ldorau/work/bcc/src/cc/frontends/clang/loader.cc:34:10: fatal error: clang/Basic/FileManager.h: No such file or directory
 #include <clang/Basic/FileManager.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/cc/frontends/clang/CMakeFiles/clang_frontend.dir/build.make:63: src/cc/frontends/clang/CMakeFiles/clang_frontend.dir/loader.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:524: src/cc/frontends/clang/CMakeFiles/clang_frontend.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

**Comment by ldorau** [comment]
And after having installed clang and clang-devel packages:

$ make 
[  3%] Built target bpf-shared
[  6%] Built target bpf-static
[ 14%] Built target bcc-loader-static
[ 21%] Built target clang_frontend
[ 24%] Built target api-static
[ 27%] Built target usdt-static
[ 40%] Built target b_frontend
[ 41%] Linking CXX shared library libbcc.so
/usr/bin/ld: cannot find -lLLVMCoroutines
/usr/bin/ld: cannot find -lLLVMCoverage
/usr/bin/ld: cannot find -lLLVMLTO
/usr/bin/ld: cannot find -lLLVMX86CodeGen
/usr/bin/ld: cannot find -lLLVMX86Desc
/usr/bin/ld: cannot find -lLLVMX86Info
/usr/bin/ld: cannot find -lLLVMMCDisassembler
/usr/bin/ld: cannot find -lLLVMX86AsmPrinter
/usr/bin/ld: cannot find -lLLVMX86Utils
/usr/bin/ld: cannot find -lLLVMGlobalISel
/usr/bin/ld: cannot find -lLLVMPasses
/usr/bin/ld: cannot find -lLLVMipo
/usr/bin/ld: cannot find -lLLVMVectorize
/usr/bin/ld: cannot find -lLLVMInstrumentation
/usr/bin/ld: cannot find -lLLVMOption
/usr/bin/ld: cannot find -lLLVMObjCARCOpts
/usr/bin/ld: cannot find -lLLVMMCJIT
/usr/bin/ld: cannot find -lLLVMExecutionEngine
/usr/bin/ld: cannot find -lLLVMRuntimeDyld
/usr/bin/ld: cannot find -lLLVMLinker
/usr/bin/ld: cannot find -lLLVMIRReader
/usr/bin/ld: cannot find -lLLVMAsmParser
/usr/bin/ld: cannot find -lLLVMDebugInfoDWARF
/usr/bin/ld: cannot find -lLLVMBPFCodeGen
/usr/bin/ld: cannot find -lLLVMSelectionDAG
/usr/bin/ld: cannot find -lLLVMBPFDesc
/usr/bin/ld: cannot find -lLLVMBPFInfo
/usr/bin/ld: cannot find -lLLVMBPFAsmPrinter
/usr/bin/ld: cannot find -lLLVMAsmPrinter
/usr/bin/ld: cannot find -lLLVMDebugInfoCodeView
/usr/bin/ld: cannot find -lLLVMDebugInfoMSF
/usr/bin/ld: cannot find -lLLVMCodeGen
/usr/bin/ld: cannot find -lLLVMTarget
/usr/bin/ld: cannot find -lLLVMScalarOpts
/usr/bin/ld: cannot find -lLLVMInstCombine
/usr/bin/ld: cannot find -lLLVMTransformUtils
/usr/bin/ld: cannot find -lLLVMBitWriter
/usr/bin/ld: cannot find -lLLVMAnalysis
/usr/bin/ld: cannot find -lLLVMProfileData
/usr/bin/ld: cannot find -lLLVMObject
/usr/bin/ld: cannot find -lLLVMMCParser
/usr/bin/ld: cannot find -lLLVMMC
/usr/bin/ld: cannot find -lLLVMBitReader
/usr/bin/ld: cannot find -lLLVMCore
/usr/bin/ld: cannot find -lLLVMSupport
/usr/bin/ld: cannot find -lLLVMDemangle
collect2: error: ld returned 1 exit status
make[2]: *** [src/cc/CMakeFiles/bcc-shared.dir/build.make:451: src/cc/libbcc.so.0.3.0] Error 1
make[1]: *** [CMakeFiles/Makefile2:241: src/cc/CMakeFiles/bcc-shared.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

**Comment by pchaigno** [comment]
Are clang-devel and llvm-devel installed?

**Comment by ldorau** [comment]
Yes, they are. Anyway, cmake should fail if something required is not installed, but cmake succeeds.

**Comment by ldorau** [comment]
There are three llvm packages installed:
```
$ rpm -qa | grep llvm
llvm-4.0.1-1.fc26.x86_64
llvm-devel-4.0.1-1.fc26.x86_64
llvm-libs-4.0.1-1.fc26.x86_64
```

**Comment by yonghong-song** [comment]
FC26 llvm package does not have static libraries, and bcc will not work. Your need an earlier version of llvm as suggested in other posts or you can build llvm from trunk (the instruction in INSTALL.md)

**Comment by ldorau** [comment]
Solution: llvm-static is also required!

**Comment by ldorau** [comment]
The issue is: cmake does not check if ```clang-devel``` and ```llvm-static``` are installed in case of Fedora26

**Comment by ldorau** [comment]
Opened a new issue for it: #1399.
