### ISSUE TITLE
Kernel symbol translation

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#140]
There should be a Python function for translating kernel addresses to symbol names: eg, BPF.ksym(addr). As an example, here's some code I was using (feel free to use/improve):

```Python
# kernel symbol translation
ksym_addrs = []			# addresses for binary search
ksym_names = []			# same index as ksym_addrs
def load_kallsyms():
	symfile = "/proc/kallsyms"
	try:
		syms = open(symfile, "r")
	except:
		print >> stderr, "ERROR: reading " + symfile
		exit()
	line = syms.readline()
	for line in iter(syms):
		cols = line.split()
		name = cols[2]
		addr = int(cols[0], 16)
		ksym_addrs.append(addr)
		ksym_names.append(name)
	syms.close()
def ksym(addr):
	start = -1
	end = len(ksym_addrs)
	while end != start + 1:
		mid = (start + end) / 2
		if addr < ksym_addrs[mid]:
			end = mid
		else:
			start = mid
	if start == -1:
		return "[unknown]"
	return ksym_names[start]
load_kallsyms()
```

The python program could then call ksym() on an address, to get the symbol name from /proc/kallsyms.

In hindsight I'd adjust this so that ksym() checked if symbols were loaded, and if not, called load_kallsyms() itself. That would avoid needing to call load_kallsyms() explicitly. The end-user would simply use ksym() if they needed it.

It may also be useful to provide a ksymaddr() function, which returned the symbol name followed by the instruction offset. Eg, "vfs_read+0x18" instead of just "vfs_read".

**Comment by brendangregg** [comment]
mid assignment line should be:

```Python
        mid = (start + end) / 2
```

**Comment by brendangregg** [comment]
Here's a newer example implementation:

```Python
# kernel symbol translation
ksym_addrs = []			# addresses for binary search
ksym_names = []			# same index as ksym_addrs
def _load_kallsyms():
	symfile = "/proc/kallsyms"
	try:
		syms = open(symfile, "r")
	except:
		print("ERROR: reading " + symfile, file=sys.stderr)
		exit()
	line = syms.readline()
	for line in iter(syms):
		cols = line.split()
		name = cols[2]
		if name[:4] != "vfs_":	# perf optimization
			continue
		addr = int(cols[0], 16)
		ksym_addrs.append(addr)
		ksym_names.append(name)
	syms.close()
def _ksym_addr2index(addr):
	start = -1
	end = len(ksym_addrs)
	while end != start + 1:
		mid = int((start + end) / 2)
		if addr < ksym_addrs[mid]:
			end = mid
		else:
			start = mid
	return start
def ksym(addr):
        idx = _ksym_addr2index(addr)
        if idx == -1:
                return "[unknown]"
        return ksym_names[idx]
def ksymaddr(addr):
        idx = _ksym_addr2index(addr)
        if idx == -1:
                return "[unknown]"
        offset = int(addr - ksym_addrs[idx])
        return ksym_names[idx] + hex(offset)
_load_kallsyms()
```

This exports two functions:
- ksym(): return the name. Eg, "vfs_read"
- ksymaddr(): return the name and offset. Eg, "vfs_read0x1"

I've been considering a third function, a hybrid which would return ksym() for close matches, and ksymaddr() for distant matches, since that's the behavior I really want (to get confidence that the match is accurate; eg, if the offset is very large, and beyond the function end address, then returning the prior symbol is misleading; at least by including the suspiciously large offset, you've given a clue to the end-user). But the trick is defining what is "distant": ideally that would mean greater than the function size, but I don't think we have size info without kernel debuginfo...

**Comment by drzaeus77** [comment]
I have an alternative approach entirely for this tool, which avoids correlation with kallsyms. Tell me what you think:
When registering the count function, it is known what is being attached to, so wouldn't it be preferable to tell the function what exactly it is counting? If I could provide a nice way to do that, would you prefer it?
```python
b.attach_kprobe(event="vfs_read", fn_name="do_count(vfs_read)")
b.attach_kprobe(event="vfs_write", fn_name="do_count(vfs_write)")
...
```

Then later:
```python
for k, v in b["counts"]:
  print("%-12s %8d" % (counter_to_name(k), v.value))
```

If you're curious how I'm planning to implement this, I have experimented with generating the text of a c file with the python templating engine, and then loading different generated functions at different points. This should run overall much faster than loading and parsing kallsyms.

**Comment by drzaeus77** [comment]
That said, if you'd like to send a pull request with the ksym and ksymaddr added as staticmethods in BPF, I would happily merge it, as it seems generally good to have. Pretty soon that file should get a refactoring, but for now it can all go in one place.

**Comment by brendangregg** [comment]
I like the idea, and ksymall loading does take >100ms of CPU. But the raw mechanics may be too weird for the end user. Imagine exposing a function like this:

```Python
b.count_kprobe(event_re="^vfs_.*", counter="counts")
[...]
counts = b.get_table("counts")
for k, v in sorted(counts.items(), key=lambda counts: counts[1].value):
	print("%-16x %-26s %8d" % (k, counter_to_name(k), v.value))
```

With the intent of providing "function counting" as a high level activity, similar to how ftrace provides a specific interface for doing function counting and more (/sys/kernel/debug/tracing/trace_stat/function*). This may be a separate ticket.

I'd still keep the ksym()/ksymaddr(), since I'm sure they'll be useful. And here's how vfscount can look:

```Python
b.attach_kprobe(event_re="^vfs_.*", fn_name="do_count")
[...]
counts = b.get_table("counts")
for k, v in sorted(counts.items(), key=lambda counts: counts[1].value):
	print("%-16x %-26s %8d" % (k.ip, ksym(k.ip), v.value))
```

I can do a PR when I'm back on normal Internet.

**Comment by 4ast** [comment]
On Wed, Aug 26, 2015 at 10:44 PM, Brendan Gregg <notifications@github.com>
wrote:

> I like the idea, and ksymall loading does take >100ms of CPU. But the raw
> mechanics may be too weird for the end user. Imagine exposing a function
> like this:
>
> b.count_kprobe(event_re="^vfs_.*", counter="counts")
> [...]
> counts = b.get_table("counts")for k, v in sorted(counts.items(), key=lambda counts: counts[1].value):
>     print("%-16x %-26s %8d" % (k, counter_to_name(k), v.value))
>
> With the intent of providing "function counting" as a high level activity,
> similar to how ftrace provides a specific interface for doing function
> counting and more (/sys/kernel/debug/tracing/trace_stat/function*). This
> may be a separate ticket.
>
counter="counts" feels very cumbersome to me.


> I'd still keep the ksym()/ksymaddr(), since I'm sure they'll be useful.
> And here's how vfscount can look:
>
> b.attach_kprobe(event_re="^vfs_.*", fn_name="do_count")
> [...]
> counts = b.get_table("counts")for k, v in sorted(counts.items(), key=lambda counts: counts[1].value):
>     print("%-16x %-26s %8d" % (k.ip, ksym(k.ip), v.value))
>
>
on the other side the ksym() usage looks quite straightforward and useful.
