### ISSUE TITLE
64-bits BPF intruction

### ISSUE THREAD

**Issue by andreviniciusgsg** [iovisor/bcc#1400]
Is it possible to obtain the entire BPF instruction while compiling a C program to eBPF using BCC? I'm able to get the opcode using `BPF(src_file="my_prog.c", debug=2)`. This is 8-bits long. However, I would like to the the final 64-bits long instruction.

**Comment by drzaeus77** [comment]
See `def dump_func(self, func_name)` in `bcc/__init__.py`, it returns the program as a string.

**Comment by yonghong-song** [comment]
If you are using latest llvm trunk, you can use debug=8, it will print out the insn with source embedded. The insn includes both encoding and asm syntax.

**Comment by yonghong-song** [comment]
If you are using latest llvm trunk, you can use debug=8, it will print out the insn with source embedded. The insn includes both encoding and asm syntax.
