### ISSUE TITLE
Please tag a new version v0.4.0

### ISSUE THREAD

**Issue by schu** [iovisor/bcc#1403]
It would be great if you could tag a new version. As gobpf follows releases, we are several months behind and would like to catch up.

**Comment by schu** [comment]
That was quick :) Thanks!

**Comment by drzaeus77** [comment]
I'm still working on publishing the deb/rpms...gpg is giving me trouble :)

**Comment by drzaeus77** [comment]
Okay, repos are updated.

**Comment by schu** [comment]
https://repo.iovisor.org/yum/main/ doesn't include `f26` yet. Installing from `f25` doesn't work for me on Fedora 26:

```
dnf install bcc-tools-0.4.0
Repository 'iovisor' is missing name in configuration, using id.
Last metadata expiration check: 0:06:40 ago on Tue Oct 24 11:05:10 2017.
Error: 
 Problem: package bcc-tools-0.4.0-1.x86_64 requires python-bcc = 0.4.0-1, but none of the providers can be installed
  - package python-bcc-0.4.0-1.x86_64 requires libbcc = 0.4.0-1, but none of the providers can be installed
  - conflicting requests
  - nothing provides libclangAST.so()(64bit) needed by libbcc-0.4.0-1.x86_64
```

`clang-libs` is installed though. Something I'm missing here?

**Comment by drzaeus77** [comment]
The most obvious solution would be to create an f26 buildbot and build the package properly. That will take some time, I will try to get to that today or tomorrow.
