### ISSUE TITLE
BPF.attach_kprobe() to accept glob or regexp

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#141]
It may be handy to use globs or regexps when specifying kprobe function names. Eg (Python):

```Python
BPF.attach_kprobe(fn, "vfs_*")
```

... for globbing, or "vfs_.*" for regexp.

**Comment by drzaeus77** [comment]
Did you give this a try?

**Comment by brendangregg** [comment]
Ah, event_re works. Thanks!
