### ISSUE TITLE
Zero maps from Python

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#142]
When using maps to store per-interval sums, it would be handy if we could clear the maps from Python, otherwise it's necessary to store the prior values and then calculate the delta each interval. Of course, Python could pretend to clear the maps and keep its own tally of what to expose.

**Comment by drzaeus77** [comment]
This actually already works! Python conveniently implements a bunch of functions (like clear) when one inherits from MutableMapping. I will add a test case to capture this.

**Comment by brendangregg** [comment]
I couldn't get clear() to work. Maybe I'm using it incorrectly? From pidpersec:

```Python
# output
while (1):
        try:
                sleep(1)
        except KeyboardInterrupt:
                pass; exit()

        print("%s: PIDs/sec: %d" % (strftime("%H:%M:%S"),
            b["stats"][S_COUNT].value))
        b["stats"].clear()
```

```Shell
# ./pidpersec 
Tracing... Ctrl-C to end.
19:29:33: PIDs/sec: 0
19:29:34: PIDs/sec: 0
19:29:35: PIDs/sec: 0
19:29:36: PIDs/sec: 0
19:29:37: PIDs/sec: 17
19:29:38: PIDs/sec: 17
19:29:39: PIDs/sec: 18
19:29:40: PIDs/sec: 19
19:29:41: PIDs/sec: 19
19:29:42: PIDs/sec: 19
19:29:43: PIDs/sec: 19
```

**Comment by brendangregg** [comment]
this now works, thanks!
