### ISSUE TITLE
Installing stable 0.4.0-1 packages for Ubuntu Xenial?

### ISSUE THREAD

**Issue by ldorau** [iovisor/bcc#1440]
https://github.com/iovisor/bcc/blob/master/INSTALL.md#ubuntu-xenial---binary says:
```"Only the nightly packages are built for Ubuntu 16.04"```

But there are stable 0.4.0-1 packages available at:
https://repo.iovisor.org/apt/xenial/pool/main/b/bcc/

How can one install them?
What should be the content of ```/etc/apt/sources.list.d/iovisor.list``` in this case?
Please update https://github.com/iovisor/bcc/blob/master/INSTALL.md#ubuntu-xenial---binary

**Comment by ldorau** [comment]
Please update https://github.com/iovisor/bcc/blob/master/INSTALL.md#ubuntu-xenial---binary

**Comment by yonghong-song** [comment]
@ldorau  Do you mind to send a PR?

**Comment by ldorau** [comment]
@yonghong-song I do not know what should be the content of ```/etc/apt/sources.list.d/iovisor.list``` in this case. If I knew, I could submit a PR.

**Comment by yonghong-song** [comment]
cc @drzaeus77

**Comment by ldorau** [comment]
@yonghong-song  I have just submitted a PR fixing this issue.
