### ISSUE TITLE
running 'sync_timing.py' gets invalid BPF_LD_IMM insn

### ISSUE THREAD

**Issue by liubogithub** [iovisor/bcc#1463]
Hi,

I was building an environment in my kvm box and encountered this issue, hello_world.py works fine, but sync_time.py has the following 'Invalid argument'.  Given 'hello_world.py' works well, I assume the kernel has met the requirement, I searched the issues but couldn't find a fix for this, so could anyone please advise?

[root@localhost ~]# python /usr/share/bcc/examples/tracing/sync_timing.py                                                                                                                   
bpf: Invalid argument
0: (b7) r7 = 0
1: (7b) *(u64 *)(r10 -16) = r7
2: (18) r1 = 0xffff880079dab800
4: (bf) r2 = r10
5: (07) r2 += -16
6: (85) call bpf_map_lookup_elem#1
7: (bf) r6 = r0
8: (b7) r1 = 1
9: (5d) if r6 != r7 goto pc+1
 R0=map_value_or_null(id=1,off=0,ks=8,vs=8,imm=0) R1=inv1 R6=map_value_or_null(id=1,off=0,ks=8,vs=8,imm=0) R7=inv0 R10=fp0
10: (b7) r1 = 0
11: (67) r1 <<= 3
12: BUG_ld_00
invalid BPF_LD_IMM insn

Traceback (most recent call last):
  File "/usr/share/bcc/examples/tracing/sync_timing.py", line 41, in <module>
    b.attach_kprobe(event="sys_sync", fn_name="do_trace")
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 460, in attach_kprobe
    fn = self.load_func(fn_name, BPF.KPROBE)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 291, in load_func
    (func_name, errstr))
Exception: Failed to load BPF program do_trace: Invalid argument

**Comment by yonghong-song** [comment]
My FC25 VM works fine with latest net-next and latest llvm compiler.

Typically "invalid BPF_LD_IMM insn" error signals an error where a global
variable is used. Looking at the source code, it could be that
"bpf_ktime_get_ns"
is not resolved properly. You could debug around this.

**Comment by liubogithub** [comment]
@yonghong-song Thanks for the reply, forgot to mention I'm using fedora 23, since I use qemu-kvm to boot my own built kernel directly, I did make modules_install and make headers_install.  Also I followed the instructions of fedora, and installed bcc-tools and libbcc-examples, etc.
I checked the kernel source about the error, it showed that the error comes from
if (BPF_SIZE(insn->code) != BPF_DW) {
  verbose("invalid BPF_LD_IMM insn\n");
  return -EINVAL;
}

I'm still new to bcc & ebpf, could you please advise how to debug it or is there any tutorial somewhere about debugging bcc scripts?

**Comment by yonghong-song** [comment]
This signals an un-recognized insn. Typically, this is a pseudo insn referring the global map or function, which needs to rewrite by verifier.

You can try to reduce the bpf program to minimum and you can still reproduce the issue. (e.g., just call bpf_ktime_get_ns). You can add "debug=4" to your BPF constructor (see tests/python/test_usdt.py) to see rewriter output and see whether the code makes sense or could have any issues or not.

**Comment by liubogithub** [comment]
```
# load BPF program                                                                                                                      
b = BPF(text="""                                                                                                                        
#include <uapi/linux/ptrace.h>                                                                                                          
#include <linux/blkdev.h>                                                                                                               
                                                                                                                                        
BPF_HASH(last);                                                                                                                         
                                                                                                                                        
void do_trace(struct pt_regs *ctx) {                                                                                                    
    u64 *tsp;                                                                                                                           
    u64 key = 0;                                                                                                                        
                                                                                                                                        
    // attempt to read stored timestamp                                                                                                 
    tsp = last.lookup(&key);                                                                                                            
    if (!tsp) {                                                                                                                         
        ;                                                                                                                               
    }                                                                                                                                   
}                                                                                                                                       
""", debug=4)

```
Minimize the code to just look up timestamp, so tsp should always be NULL, however, this still end up with "Invalid argument".

```
#include <uapi/linux/ptrace.h>
#include <linux/blkdev.h>

BPF_HASH(last);

__attribute__((section(".bpf.fn.do_trace")))
void do_trace(struct pt_regs *ctx) {
    u64 *tsp;
    u64 key = 0;

    // attempt to read stored timestamp
    tsp = bpf_map_lookup_elem((void *)bpf_pseudo_fd(1, 3), &key);
    if (!tsp) {
        ;
    }
}
Traceback (most recent call last):
  File "sync_timing.py", line 33, in <module>
    b.attach_kprobe(event="sys_sync", fn_name="do_trace")
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 460, in attach_kprobe
    fn = self.load_func(fn_name, BPF.KPROBE)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 291, in load_func
    (func_name, errstr))
Exception: Failed to load BPF program do_trace: Invalid argument

```

Can any expert take a look at this?

**Comment by liubogithub** [comment]
```
[root@localhost ~]# python /usr/share/bcc/examples/tracing/sync_timing.py
bpf: Invalid argument
0: (b7) r7 = 0
1: (7b) *(u64 *)(r10 -16) = r7
2: (18) r1 = 0xffff880079dab800
4: (bf) r2 = r10
5: (07) r2 += -16
6: (85) call bpf_map_lookup_elem#1
7: (bf) r6 = r0
8: (b7) r1 = 1
9: (5d) if r6 != r7 goto pc+1
R0=map_value_or_null(id=1,off=0,ks=8,vs=8,imm=0) R1=inv1 R6=map_value_or_null(id=1,off=0,ks=8,vs=8,imm=0) R7=inv0 R10=fp0
10: (b7) r1 = 0
11: (67) r1 <<= 3
12: BUG_ld_00
invalid BPF_LD_IMM insn
```

the 12nd instruction refers to one thing: insn->code is 0, why could it be zero?

**Comment by yonghong-song** [comment]
The below is an example when similar verifier complain can happen.

```
$ cat ./hello_world.py                                          
#!/usr/bin/env python
from bcc import BPF
BPF(text='int g; int kprobe__sys_clone(void *ctx) { bpf_trace_printk("%d\\n", g); return 0; }').trace_print()
$ sudo ./hello_world.py 
bpf: Failed to load program: Invalid argument
0: (b7) r1 = 680997
1: (63) *(u32 *)(r10 -4) = r1
2: BUG_ld_08
invalid BPF_LD_IMM insn

Traceback (most recent call last):
  File "./hello_world.py", line 3, in <module>
    BPF(text='int g; int kprobe__sys_clone(void *ctx) { bpf_trace_printk("%d\\n", g); return 0; }').trace_print()
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 308, in __init__
    self._trace_autoload()
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 915, in _trace_autoload
    fn = self.load_func(func_name, BPF.KPROBE)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 348, in load_func
    (func_name, errstr))
Exception: Failed to load BPF program kprobe__sys_clone: Invalid argument
```

In your case, some global variables are not resolved properly. It could be a map pointer or a function pointer. You can debug along this line to really make sure all helper functions are converted to numbers, and all map pointers are converted to bpf_pseudo thing. 

With latest bcc repo, you can try debug=1 (IR), debug=8 (byte code) as well. Hopefully, they can give your more clue.

**Comment by liubogithub** [comment]
I will dig into this more, but seriously I was using the 'sync_timing.py' from libbcc-examples, which should have been verified to be 100% correct, so I _guess_ there's something wrong in my setup.

Thanks for your reply.

**Comment by yonghong-song** [comment]
Yes, sync_timing.py works fine in my environment, FC25 VM booted with latest net-next and with latest llvm built from source.

**Comment by liubogithub** [comment]
@yonghong-song Can you please share how you configure you F25 VM? A few questions I have are
a) what do you put in /lib/modules/$(uname -r)/build?  (I used 9pfs to share the whole build directory, and made a symbolic link to /lib/modules/$(uname -r)/build)
b) did you make headers_install? and how do you let VM access these headers files?  ( I tried to put them in /usr/local/include inside VM, but still no luck)

I had tried bcc with a newer Fedora 27, on the vanilla F27 bcc worked fine, but when I booted to my own built kernel and set up modules and /lib/modules/$(uname -r)/build and /usr/local/include, it ended up with 'segment fault' when running python ext4slower.

**Comment by yonghong-song** [comment]
I am using virtualbox. FC25 VM is an iso image got from Fedora website. So I do not need 9pfs ...

I do have a qemu and 9pfs to share linux repo. I am using it for linux only work. Anything involves bcc, I am using virtualbox VM.

Other people can comment or share experience on how to use qemu on VM with bcc.

**Comment by liubogithub** [comment]
I see, I don't think 9pfs really matters here though, anyway I'm closing this since it's not really a bug of bcc itself.
