### ISSUE TITLE
Access task_struct in python scripts

### ISSUE THREAD

**Issue by atishp04** [iovisor/bcc#1469]
Currently, several scripts directly access task_struct member variables directly assuming the offsets are in order. However, latest upstream kernel randomizes section of this data structure.
Kernel Commit 29e48ce87f1e ("task_struct: Allow randomized layout")
(https://patchwork.kernel.org/patch/9797817/)

The details are discussed in the following pull request as well.
https://github.com/iovisor/bcc/pull/1439

bpf_probe_read() can currently read the data correctly. However, the scripts under tools & examples/tracing/task_switch.py missing this. 

Alternatively, the following patch can be used to resolve the correct offset.
diff --git a/include/linux/compiler-clang.h b/include/linux/compiler-clang.h
index de17999..7433ee9 100644
--- a/include/linux/compiler-clang.h
+++ b/include/linux/compiler-clang.h
@@ -15,3 +15,6 @@
  * with any version that can compile the kernel
  */
 #define __UNIQUE_ID(prefix) __PASTE(__PASTE(__UNIQUE_ID_, prefix), __COUNTER__)
+
+#define randomized_struct_fields_start struct {
+#define randomized_struct_fields_end   };

Is it okay to change the existing scripts to use bpf_probe_read() ? Here are the scripts that needs to be changed.
/tools
runqlat.py
runqlen.py
cpuunclaimed.py
offwaketime.py
offcputime.py
wakeuptime.py
oomkill.py
mountsnoop.py
examples/tracing/task_switch.py 

I am open to any other approach as well as long as the scripts work out of the box.
cc: @yonghong-song 
cc: @sandip4n 
cc: @rnav 
Regards,
Atish

**Comment by yonghong-song** [comment]
This is bad news. Apparently, this kernel patch did not make into 4.14 release yet.
http://www.spinics.net/lists/kernel/msg2644958.html

@4ast , maybe you could help push a little to see whether this can get into 4.14?

**Comment by 4ast** [comment]
right it's in 4.15 only so far.

**Comment by sandip4n** [comment]
As @4ast pointed out, the fix is available starting with `4.15`. This affects the `4.13` and `4.14` series only. So, older kernels should be fine.

**Comment by atishp04** [comment]
Thanks . I saw @4ast's request to get it merged into 4.14 & 4.13 as well.
I will close the issue.
