### ISSUE TITLE
Python function to print the bpf_log

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#147]
For debugging. This could be done in an error handler.

**Comment by drzaeus77** [comment]
Is there a particular reason to have an error handler instead of printing to stderr? Currently we do support printing in that manner already:


```bash
$ sudo python
Python 3.4.3 (default, Mar 25 2015, 17:13:50) 
[GCC 4.9.2 20150304 (prerelease)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from bpf import BPF
>>> text = """
... int hello(void *ctx) {
...   bpf_trace_printk("foo %d\\n", *(volatile int*)0);
...   return 0;
... }
... """
>>> b = BPF(text=text)
>>> b.attach_kprobe("sys_clone", "hello")
bpf: Permission denied
0: (18) r1 = 0x206f6f66
2: (7b) *(u64 *)(r10 -8) = r1
3: (b7) r1 = 0
4: (61) r3 = *(u32 *)(r1 +0)
R1 invalid mem access 'imm'
```

I don't have a problem with an error handler, and in fact the C backend already supports saving the log buf to a user buffer (see #96 ), but it would be good to know the specific use case in order to structure the API appropriately.

**Comment by drzaeus77** [comment]
To be more specific, on the kernel side, the bpf_log is only ever generated when the verifier fails for some reason. It is not possible to arbitrarily collect the verifier's view of a valid program.

Another option is to dump the assembly version of the compiled program before calling bpf_prog_load. The LLVM IR is emitted in this way when debug=1 is passed to the BPF() constructor.

**Comment by 4ast** [comment]
> To be more specific, on the kernel side, the bpf_log is only ever generated when the verifier fails for
> some reason. It is not possible to arbitrarily collect the verifier's view of a valid program.

actually with log_level > 0 kernel emits the verification log even for valid programs...

**Comment by drzaeus77** [comment]
So it does, I must have been remembering a conversation with you about something else. Didn't check the code until now.

**Comment by brendangregg** [comment]
debug=0x2 works for me. I lost the initial use case, but had been writing a program that didn't work and was hoping for a clue from the bpf_log (maybe it was the map zeroing). Since it already supports printing on errors (as shown by that example), I guess the bpf_log wouldn't have helped me in that case anyway.
