### ISSUE TITLE
bpf_prog_load prints verifier messages to stderr always

### ISSUE THREAD

**Issue by iaguis** [iovisor/bcc#1472]
It seems there was a change in v0.5.0's `bpf_prog_load()`. It now prints verifier messages to stderr always.

Doesn't it make more sense to skip writing to stderr if the user provided a `log_buf`?

**Comment by yonghong-song** [comment]
cc @palmtenor

**Comment by palmtenor** [comment]
That is true, apologize for the unexpected change.

Will put up a change to skip printing to stderr if user provided log buffer. Do we want to skip the printed message on error as well?

**Comment by iaguis** [comment]
It seems v0.4.0 did print the log to stderr on failure.

However, as a user of libbcc, I'd rather have control over printing logs than have the library print things to stderr, even when there're errors.

**Comment by palmtenor** [comment]
The `stderr` message we print has some "hints", i.e. interpreting common errors to actionable instructions, which I feel would be useful for beginner users. Probably will go for keeping the original behavior, that is, only skip printing when user provided log buffer in non-error cases.
