### ISSUE TITLE
Add docs about using structs in trace tool

### ISSUE THREAD

**Issue by bobrik** [iovisor/bcc#1478]
Today I was trying to debug an issue with CFS incorrectly throttling tasks:

* https://marc.info/?l=linux-kernel&m=151270583632566&w=2

I was looking at CFS code and found functions like `__account_cfs_rq_runtime`:

* http://elixir.free-electrons.com/linux/v4.14.4/ident/__account_cfs_rq_runtime

Function signature is:

```
static void __account_cfs_rq_runtime(struct cfs_rq *cfs_rq, u64 delta_exec)
```

I wanted to print out `cfs_rq->runtime_remaining`, but wasn't able to figure out how. This is probably the third time I need to poke inside of structs and failed, so it seems to be worth documenting.

**Comment by brendangregg** [comment]
```
(root) /mnt/src/linux-4.15-rc2 # /usr/share/bcc/tools/trace 'p::__account_cfs_rq_runtime(struct cfs_rq *cfs_rq, u64 delta_exec) "%d", cfs_rq->runtime_remaining'
/virtual/main.c:40:32: error: incomplete definition of type 'struct cfs_rq'
        __data.v0 = (int)cfs_rq->runtime_remaining;
                         ~~~~~~^
/lib/modules/4.15.0-rc2-virtual/build/include/linux/sched.h:36:8: note: forward declaration of 'struct cfs_rq'
struct cfs_rq;
       ^
1 error generated.
Failed to compile BPF module
```

Ok, so cfs_rq is declared in kernel/sched/sched.h, which isn't in /usr/include, so I need to run this from the kernel source directory -- assuming you have it!

```
(root) /mnt/src/linux-4.15-rc2 # /usr/share/bcc/tools/trace -I 'kernel/sched/sched.h' 'p::__account_cfs_rq_runtime(struct cfs_rq *cfs_rq, u64 delta_exec) "%d", cfs_rq->runtime_remaining'
PID    TID    COMM         FUNC             -
^C
```

This, or something like it, should be put in trace_example.txt at least.
