### ISSUE TITLE
Failed to compile BPF module while accessing struct cfs_rq

### ISSUE THREAD

**Issue by atishp04** [iovisor/bcc#1479]
Currently, runqlen.py & cpuunclaimed.py uses a partially defined cfs_rq to get the runq length value.
With the latest kernel, I am getting following error. 

[tools]# ./runqlen.py 
/virtual/main.c:31:41: error: cannot take the address of an rvalue of type 'typeof(struct cfs_rq *)' (aka 'struct cfs_rq *')
  ...&({ typeof(struct cfs_rq *) _val; memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)&task->se.cfs_rq); _val; }));
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Traceback (most recent call last):
  File "./runqlen.py", line 114, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 301, in __init__
    raise Exception("Failed to compile BPF module %s" % src_file)
Exception: Failed to compile BPF module 

I am still trying understand what exactly this error mean. Does it have to do anything with the latest clang front-end rewriter fix? https://github.com/iovisor/bcc/pull/1439
cc: @yonghong-song
cc: @sandip4n

Any explanation about the error would also help.

**Comment by yonghong-song** [comment]
I cannot reproduce the issue. In my VM with latest net-next code:
```
-bash-4.3$ sudo ./cpuunclaimed.py 
Sampling run queues... Output every 1 seconds. Hit Ctrl-C to end.
ERROR: CPU samples arrived at skewed offsets (CPUs may have powered down when idle), spanning 7493243 ns (expected < 4040404 ns). Debug with -J, and see the man page. As output may begin to be unreliable, exiting.
-bash-4.3$ sudo ./runqlen.py 
Sampling run queue length... Hit Ctrl-C to end.
^C
Traceback (most recent call last):
  File "./runqlen.py", line 179, in <module>
    dist.print_linear_hist("runqlen", "cpu")
  File "/usr/lib/python2.7/site-packages/bcc/table.py", line 360, in print_linear_hist
    "exceeds max of %d.") % (k.value, linear_index_max))
IndexError: Index in print_linear_hist() of 1048575 exceeds max of 1025.
-bash-4.3$ uname -a
Linux localhost.localdomain 4.15.0-rc2+ #143 SMP Fri Dec 8 16:51:56 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
-bash-4.3$
```
The cpuunclaimed error may be due to my VM environment, and bpf program compilation is still successful.

The error complains, it cannot get the address of:
```
&({ typeof(struct cfs_rq *) _val; memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)&task->se.cfs_rq); _val; }))
```
because it does not produce a `lvalue`.

In my run, I got:
```
    my_q = (struct cfs_rq_partial *)({ typeof(struct cfs_rq *) _val; memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)&task->se.cfs_rq); _val; });
```
I did not get address taken here.

Original code:
```
    my_q = (struct cfs_rq_partial *)task->se.cfs_rq;
```
I did not see the reason where address taken (`&({ typeof(struct cfs_rq *) _val...`) should be there.

Did you hack the code?

**Comment by atishp04** [comment]
Thanks for the verification. I was carrying another temporary fix in the lkml. My apologies.
Closing the issue.
