### ISSUE TITLE
IOVisor repo isn't providing latest release for xenial

### ISSUE THREAD

**Issue by joestringer** [iovisor/bcc#1495]
Looking at:
https://repo.iovisor.org/apt/xenial/dists/xenial/main/binary-amd64/Packages

The v0.5.0 version is not listed in the above file, so when users add this repository they fetch the older v0.4.0 version.

**Comment by yonghong-song** [comment]
cc @drzaeus77

**Comment by drzaeus77** [comment]
Please try again, the index has been updated.

**Comment by joestringer** [comment]
Seems to be fixed, thanks!
