### ISSUE TITLE
offcputime.py: opLoc is invalid...

### ISSUE THREAD

**Issue by stunes** [iovisor/bcc#1498]
I tried running offcputime.py from commit 25be6bb4; it failed with:

```
/virtual/main.c:20:15: error: internal error: opLoc is invalid while preparing probe rewrite
    u32 pid = prev->pid;
```

I fixed it locally by replacing `u32 pid = prev->pid;` with:

```c
u32 pid;
bpf_probe_read(&pid, sizeof(pid), (u8 *)prev + offsetof(struct task_struct, pid));
```

Likewise for tgid immediately following it.

I'm not sure if that's the "right" (or even a good) way of fixing it, or if anyone except me is having this problem. Thanks!

**Comment by yonghong-song** [comment]
It works fine to me with latest llvm compiler in fc25. Could you this be a llvm compiler issue? What is your llvm version?

**Comment by stunes** [comment]
I tried recompiling/reinstalling bcc, and now it works with no problem. I'm wondering if it got out of whack from upgrading llvm after installing it originally? Anyway, it works now. Sorry for the noise!

**Comment by goldshtn** [comment]
@yonghong-song I just hit the same issue with FC27, installed BCC from our nightly build. People will be running into this, so I think it's worth the effort to investigate further.

**Comment by goldshtn** [comment]
All righty, false alarm from me as well: I was not actually installing the latest BCC. Confirmed as working with a clean FC27 (from cloud.fedora.org) and the nightly build per INSTALL.md.
