### ISSUE TITLE
offcputime doesn't work on linux 4.14.8

### ISSUE THREAD

**Issue by samofatov** [iovisor/bcc#1499]
If you run offcputime on kernel 4.14.8 it produces empty output. No stacks.
On 4.9.71 on the same system with the same configuration it works fine.

**Comment by yonghong-song** [comment]
I tried 4.14.8 by cloning 
```
https://kernel.googlesource.com/pub/scm/linux/kernel/git/stable/linux-stable.git
```
and checkout the tag `v4.14.8`.

```
-bash-4.3$ uname -a
Linux localhost.localdomain 4.14.8+ #178 SMP Sun Dec 24 10:58:39 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
-bash-4.3$
```
The offcputime actually works fine:
```
-bash-4.3$ sudo ./offcputime.py 
Tracing off-CPU time (us) of all threads by user + kernel stack... Hit Ctrl-C to end.
^C
    finish_task_switch
    schedule
    schedule_timeout
    wait_for_completion
    flush_work
    tty_buffer_flush_work
    n_tty_poll
...
```

**Comment by samofatov** [comment]
Sorry this issue appears to be CentOS 6 related (appears with Elrepo kernel).
I installed kernel 4.14.8 on CentOS 7 and it works just fine.
Kernel 4.9.71 works with CentOS 6. I guess this should be closed for now. Sorry.
