### ISSUE TITLE
Build fails on Centos 6

### ISSUE THREAD

**Issue by samofatov** [iovisor/bcc#1500]
Build on CentOS 6 requires a few symbols not present in Glibc 2.12. Otherwise it works just fine.
Attached is patch to build BCC on such system. Consider adding something like this to main source tree.

[bcc_rhel6.patch.txt](https://github.com/iovisor/bcc/files/1584318/bcc_rhel6.patch.txt)

**Comment by yonghong-song** [comment]
Could you add proper comment such as
```
// TODO: remove these defines when centos 6 support is not necessary
```
So that the related codes can be removed easily.

Could you submit a formal patch? Thanks.

**Comment by samofatov** [comment]
The changes have been merged. Thanks!
