### ISSUE TITLE
bcc/eBPF book

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#1506]
This ticket will describe some details about a future bcc/eBPF book.

Q) When?
A) Not in the short term future -- bcc and eBPF are still being developed, so a book written today would be out of date by the time it could be printed.

Q) Why?
A) To help teach and promote bcc/eBPF.

Q) Who will write it?
A) Co-authored by one or more core maintainers. Recognized experts with bcc/eBPF.

Q) What will it cover?
A) Using bcc/eBPF tools and one-liners, and some developing new programs. It will show insight beyond what is already available in the bcc docs, and will be edited to higher quality. Any (good) book project involves paid technical copy-editors, who improve the documentation and make it easier to read and understand by a larger audience.

Q) Who is the audience?
A) Sysadmins and SREs with an interest in deeper analysis. The audience will not really be for bcc/eBPF developers, such as showing how to engineer a software defined networking product with bcc, as the market there is tiny (<200?), and from that tiny market most people are already up to speed, so the number that need a book is even fewer (<20?). It's not enough for a book.

Q) What is the current status?
A) It would be in the spirit of open source to always answer this in detail, however, books with major publishers involve contracts, lawyers, procedures, and include various bits of confidential information along the way. There are times when it's ok to share details, and times when it isn't. We'll update this when we can.

**Comment by brendangregg** [comment]
Many of you already know what's going on as I've spoken about it at conferences and in meetings (there are also 40 people involved in this book: thanks for all the help). To provide a quick update here:

Author: Brendan Gregg
Publisher: Addison Wesley
Timeline: 2019

Since bpftrace has been the winning higher-lever front-end, it must cover it as well, however, we're still finalizing the API. We can't publish until that's in good enough shape to commit to print.

Title: TBD. It's about using BPF for performance analysis and observability.

**Comment by brendangregg** [comment]
Soon http://www.brendangregg.com/bpfperftools.html

**Comment by mcaleavya** [comment]
Looking forward to it

**Comment by brendangregg** [comment]
http://www.brendangregg.com/blog/2019-07-15/bpf-performance-tools-book.html

![bpfperftools_bookcover_908](https://user-images.githubusercontent.com/1101211/61246719-5a683f80-a704-11e9-8770-d07d38d3d909.png)

**Comment by brendangregg** [comment]
closing ticket, it's done
