### ISSUE TITLE
Invalid dereference silently removed

### ISSUE THREAD

**Issue by pchaigno** [iovisor/bcc#1519]
In the following code, the invalid dereference is silently removed (without warning or error):
```python
from bcc import BPF
b = BPF(text = """
typedef struct {
    u64 key[2];
} test_t;

int prog(struct xdp_md *ctx) {
    test_t *key = 0;
    u64 v = key->key[0];
    if (v) {
        return XDP_DROP;
    }
    return XDP_PASS;
}
""", debug=2)
fn = b.load_func("prog", BPF.XDP)
```

If I switch the array index from `0` to `1`, I get an `invalid mem access` from the verifier as expected.

Clang and Linux versions:
```
$ clang --version
clang version 5.0.1-svn319952-1~exp1 (branches/release_50)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

$ uname -r
4.14.0-041400-generic
```

**Comment by yonghong-song** [comment]
clang optimized the load away.
In llvm:lib/Transforms/Scalar/SCCP.cpp
```
  // load null is undefined.
  if (isa<ConstantPointerNull>(Ptr) && I.getPointerAddressSpace() == 0)
    return;
```

The compiler considers load null as undefined.
clang takes advantage of this and optimize the branch away, and gcc did not do anything about this.

**Comment by pchaigno** [comment]
Okay... so it's the expected behavior. I'll close.
Thanks for the details @yonghong-song!
