### ISSUE TITLE
Function not in available_filter_functions

### ISSUE THREAD

**Issue by pchaigno** [iovisor/bcc#1537]
In tools that use a regular expression to match functions to trace, bcc relies on the `/sys/kernel/debug/tracing/available_filter_functions` list [to derive the actual names of the functions](https://github.com/iovisor/bcc/blob/3763380057f0ad771dee657bcff5c35f6db2e9f5/src/python/bcc/__init__.py#L480-L484). However, that list doesn't seem to be exhaustive. For instance, on my system, I can trace function `seq_print_ip_sym` with kprobes even though it's not in the list. (I'm not sure whether functions that are not in the list are simply functions ftrace cannot trace or functions unsafe to trace.)

Because of this, I haven't found a way to trace functions that are not in the list with tools that expect a regular expression:
```
$ ./tools/funcslower.py seq_print_ip_sym # expects a function name
Tracing function calls slower than 1 ms... Ctrl+C to quit.
COMM           PID    LAT(ms)             RVAL FUNC
$ ./tools/stackcount.py seq_print_ip_sym # expects a pattern
No functions matched by pattern ^seq_print_ip_sym$
$ ./tools/stackcount.py -r seq_print_ip_sym
No functions matched by pattern seq_print_ip_sym
```

**Comment by yonghong-song** [comment]
cc @liu-song-6 who hit a similar issue before.

**Comment by liu-song-6** [comment]
The last time I hit the issue, it was inline function. This one (seq_print_ip_sym) is not. But it is in trace_output.c, so it does make it tricky. 
The kernel uses a script (scripts/recordmcount.pl) to scan source code for functions to list in available_filter_functions. I guess it is possible to improve the logic in the script. 
I will look more into this topic, and update here.

**Comment by palmtenor** [comment]
Would it be better for us to use `/proc/kallsyms` instead of `/sys/kernel/debug/tracing/available_filter_functions` for the kprobe regex filtering?

**Comment by liu-song-6** [comment]
/proc/kallsyms has functions that we cannot/shouldn't probe. I guess it is better to start with available_filter_functions.

**Comment by yonghong-song** [comment]
It looks like using `/proc/kallsyms` should be okay and this is what debugfs kprobe can do. Since we are using the underlying kprobe infrastructure, we should allow to trace functions which underlying technology allows.
