### ISSUE TITLE
Device or resource busy from BPF cleanup()

### ISSUE THREAD

**Issue by myllynen** [iovisor/bcc#1553]
From issue #1533:

When using the PCP BCC PMDA plugin (see https://github.com/myllynen/pcp-bcc-pmda), otherwise everything works as expected but occasionally when exiting we see:

pmdabcc(16113) Info: Cleaning up modules:
pmdabcc(16113) Info: tcplife
write(-:kprobes/p_tcp_set_state_bcc_16113): Device or resource busy
pmdabcc(16113) Info: tcplife: BPF/kprobes detached.

The plugin has registered an atexit function which simply does:

```
if self.bpf:
    self.bpf.cleanup()
```

It was shown in #1533 that the error mostly comes from linux/kernel/trace/trace_kprobe.c:

```
static int unregister_trace_kprobe(struct trace_kprobe *tk)
{
        /* Enabled event can not be unregistered */
        if (trace_probe_is_enabled(&tk->tp))
                return -EBUSY;

        /* Will fail if probe is being used by ftrace or perf */
        if (unregister_kprobe_event(tk))
                return -EBUSY;

        __unregister_trace_kprobe(tk);
        list_del(&tk->list);

        return 0;
}
```

It's unclear what might be causing this occasionally and whether it can be ignored or not. Thanks.

**Comment by yonghong-song** [comment]
@myllynen maybe you can comment on how to show additional logs (in the above to demonstrate the issue) in PCP BCC PMDA plugin ?

**Comment by myllynen** [comment]
When the message is not seen, we see bpf.cleanup() called, the poller thread calling bpf.kprobe_poll() repeatedly until the poller thread exits when bpf becomes None, and then the main thread calling bpf.cleanup() exits as well, terminating the program. So in this case everything seems to work well.

When the message is seen, we see first bpf.cleanup() being called from the main thread, the message appearing, and then the main thread returning from bpf.cleanup() and program exiting. In this case the poller thread is not logging anything so it is being blocked in bpf.kprobe_poll().

Thanks.

**Comment by yonghong-song** [comment]
I see. When the message is seen, perf_reader_poll `poll` function may hold the file descriptor for the trace event, so the above `unregister_kprobe_event` will return -EBUSY. The best strategy is to deal with at pcpbcc level. In `pcpbcc.py` when you are about to do cleanup, you may want to make sure the polling thread exit.

**Comment by myllynen** [comment]
I don't instantly see a way in Python to terminate a thread which is blocked from another thread. From PCP point of view, this sounds to be more like a cosmetic issue which is safe to ignore when exiting so ok if you want to close this one. Thanks.

**Comment by yonghong-song** [comment]
could you try `kprobe_poll(timeout)` instead of blocking `kprobe_poll()`? This way, it won't stuck in the kernel for ever.

**Comment by myllynen** [comment]
I'm not sure would that be helpful, usually blocking in `kprobe_poll()` is ok but when exiting we wouldn't want to wait for any timeout to merely prevent such a message. Since we now have this documented here in this ticket, I think we're ok.

Thanks for all your help!
