### ISSUE TITLE
test_shared_table fails nosetests,

### ISSUE THREAD

**Issue by joelagnel** [iovisor/bcc#1562]
```
~/repo/bcc# nosetests -w tests/python/
......E
======================================================================
ERROR: test_close_extern (test_shared_table.TestSharedTable)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/joel/repo/bcc/tests/python/test_shared_table.py", line 14, in test_close_extern
    t2 = b2["table1"]
  File "/home/joel/repo/bcc/src/python/bcc/__init__.py", line 441, in __getitem__
    self.tables[key] = self.get_table(key)
  File "/home/joel/repo/bcc/src/python/bcc/__init__.py", line 431, in get_table
    keytype = BPF._decode_table_type(json.loads(key_desc.decode()))
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 6 - line 1 column 11 (char 5 - 10)
--
```
Seems the issue is the table descriptor fed to `json.loads` is "int""int". So there's some extra data passed to it causing the issue.

**Comment by yonghong-song** [comment]
Thanks for reporting. This is caused by map type traversing related to export/extern maps. Will fix this shortly.

**Comment by joelagnel** [comment]
Great, thanks!
Also just some questions on testing, what's the recommended set of tests to run when making changes to  the core (python and cc)? I went through docs and couldn't find a testing section stating how to run the tests. At the moment I only run python smoketests like so:
`nosetests -w tests/python/ test_tools_smoke -v`
but I am not very confident about the test coverage it provides.

I could run tests in `tests/python/` using `nosetests` however some tests need executable permissions vs others aren't. The executable ones need `--exe` parameter passed to `nosetests` for them to run. What's the rationale for that?

Lastly, would it make sense to integrate some kind of a more advanced CI that can run these tests, instead of travis-ci and the pep8 style tests? Thanks.

**Comment by yonghong-song** [comment]
In your build directory, you can run `make test`. This is also the commit gating test running in various platforms.

**Comment by joelagnel** [comment]
Got it, thanks!
