### ISSUE TITLE
offcputime gives me empty result when I try to attach it to a specific process 

### ISSUE THREAD

**Issue by zhexuany** [iovisor/bcc#1566]
uname -r 
4.13.0-16-generic

Is it normal for this particular case? I am using it to do performance analysis against our product which is written in go. I first thought this maybe the problem but I tried to attach `sshd` and other process. None of them gives me useful output. By saying "useful output", I mean it is empty output.

**Comment by palmtenor** [comment]
Does it give you any result if you do system-wide profiling (without specifying a PID)?

**Comment by zhexuany** [comment]
Yes. If I run `offcputime` without specifying pid, then it works. That is why I am so confused.

**Comment by yonghong-song** [comment]
You probably hit this issue:
https://github.com/iovisor/bcc/blob/master/docs/reference_guide.md#7-bpf_get_current_task

You can try the following workaround in offcputime.py file:
```
#define randomized_struct_fields_start  struct {
#define randomized_struct_fields_end    };
#include <linux/sched.h>
```
to see whether it solves your issue or not.

**Comment by zhexuany** [comment]
That solved my issue. Maybe we case add this in FAQ? Closing this issue.

**Comment by yockie** [comment]
@yonghong-song hi，I have the same issue ：run offcputime with specifying pid, its output is empty. It works without specifying pid.
environment:
$uname -r
4.19.95-27
$cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)

And above solution is useless. Thanks.

**Comment by dnb02** [comment]
offcputime libbpf-tools version also gives empty results when attaching to a specific pid.

```
 ➜  libbpf-tools git:(master) ✗ sudo ./offcputime -k -p `pgrep iperf3`
Tracing off-CPU time (us) of PID [12135]... Hit Ctrl-C to end.
^C%
➜  libbpf-tools git:(master) ✗ 
```

```
➜  libbpf-tools git:(master) ✗ sudo ./offcputime -k 
Tracing off-CPU time (us) of all threads... Hit Ctrl-C to end.
^C    bpf_prog_843e5058b30c0620_handle_sched_switch
    bpf_prog_843e5058b30c0620_handle_sched_switch
    bpf_prog_385e1df70d194ccb_sched_switch
    bpf_trace_run4
    __bpf_trace_sched_switch
    __schedule
    schedule
    worker_thread
    kthread
    ret_from_fork
    ret_from_fork_asm
    -                kworker/kworker (20331)
        3839556
   [....]
```
