### ISSUE TITLE
Importing bcc first could block curses.initscr()

### ISSUE THREAD

**Issue by lcp** [iovisor/bcc#1590]
While testing tools/cachetop.py, I found that importing bcc before curses could make the program hang. For a simple test, it can be done with the python shell:

$ python3
Python 3.6.4 (default, Jan 03 2018, 13:52:55) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bcc
>>> import curses
>>> curses.initscr()

The shell just got stuck and didn't even respond to SIGINT. If curses was imported first, then everything was fine.

The strace log ends in futex():

ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(1, TIOCGWINSZ, {ws_row=41, ws_col=172, ws_xpixel=0, ws_ypixel=0}) = 0
futex(0x7f4f05f9fff0, FUTEX_WAIT_PRIVATE, 2, NULL

It seems a mutex in ncurses stopped the process, but I have no idea of why bcc would affect the mutex in ncurses.

OS: openSUSE Tumbleweed
Python: 3.6.4
ncurses: 6.0

**Comment by drzaeus77** [comment]
Just off the top of my head, you might want to look at the build options for your clang...I believe we have debugged an issue like this before, and it was in there somewhere.

**Comment by lcp** [comment]
The root causes is actually in ncurses which provides libtinfo and libtinfow but those two libraries cannot coexist. Unfortunately, our python loaded libtinfo and libLLVM indirectly loaded libtinfow and caused the deadlock. Close this issue since it's not relevant to bcc.
