### ISSUE TITLE
zfsslower/zfsdist rely on not-exported symbols

### ISSUE THREAD

**Issue by jepio** [iovisor/bcc#1597]
I'm on gentoo, kernel 4.13.12, zfs 0.7.6, system compiler is gcc 6.4.0. Neither of zfsslower/zfsdist work, they fail trying to attach to kprobe
```
Traceback (most recent call last):
  File "/usr/share/bcc/tools/zfsslower", line 286, in <module>
    b.attach_kprobe(event="zpl_read", fn_name="trace_rw_entry")
  File "/usr/lib64/python2.7/site-packages/bcc/__init__.py", line 524, in attach_kprobe
    raise Exception("Failed to attach BPF to kprobe")
Exception: Failed to attach BPF to kprobe
```
At first I thought that this is related to #1248, and that I could work-around it by attaching to a different variant of zpl_read/write, but that would fail as well as zpl_open/zpl_fsync are missing too.

\# grep zpl /proc/kallsyms:
```
ffffffffa03a9380 d sa_legacy_zpl_layout [zfs]
ffffffffa0373c80 r zpl_dops_snapdirs    [zfs]
ffffffffa02fba30 t zpl_read_common      [zfs]
ffffffffa0374860 r zpl_xattr_trusted_handler    [zfs]
ffffffffa02fcec0 t zpl_prune_sb [zfs]
ffffffffa02fba60 t zpl_write_common     [zfs]
ffffffffa0374040 r zpl_file_operations  [zfs]
ffffffffa0374540 r zpl_inode_operations [zfs]
ffffffffa03a9ee0 d zpl_fs_type  [zfs]
ffffffffa03747e0 r zpl_xattr_acl_access_handler [zfs]
ffffffffa0373d00 r zpl_ops_root [zfs]
ffffffffa0374480 r zpl_dir_inode_operations     [zfs]
ffffffffa0374620 r zpl_super_operations [zfs]
ffffffffa02fe070 t zpl_xattr_list       [zfs]
ffffffffa0373ec0 r zpl_export_operations        [zfs]
ffffffffa02fba90 t zpl_fallocate_common [zfs]
ffffffffa0374280 r zpl_dentry_operations        [zfs]
ffffffffa02fe650 t zpl_init_acl [zfs]
ffffffffa0374820 r zpl_xattr_security_handler   [zfs]
ffffffffa0374300 r zpl_special_inode_operations [zfs]
ffffffffa03748a0 r zpl_xattr_user_handler       [zfs]
ffffffffa0373dc0 r zpl_fops_root        [zfs]
ffffffffa0374140 r zpl_address_space_operations [zfs]
ffffffffa02dc3f0 t zfs_get_zplprop      [zfs]
ffffffffa02faed0 t zpl_putpage  [zfs]
ffffffffa02fc4b0 t zpl_vap_init [zfs]
ffffffffa0373ac0 r zpl_ops_snapdir      [zfs]
ffffffffa03739c0 r zpl_fops_shares      [zfs]
ffffffffa02fe2e0 t zpl_xattr_security_init      [zfs]
ffffffffa0373b80 r zpl_fops_snapdir     [zfs]
ffffffffa03a9f40 d zpl_xattr_handlers   [zfs]
ffffffffa03743c0 r zpl_symlink_inode_operations [zfs]
ffffffffa02fdf20 t zpl_xattr_readdir    [zfs]
ffffffffa02fc350 t zpl_get_link [zfs]
ffffffffa02fe4c0 t zpl_get_acl  [zfs]
ffffffffa03747a0 r zpl_xattr_acl_default_handler        [zfs]
ffffffffa0373900 r zpl_ops_shares       [zfs]
ffffffffa0373f40 r zpl_dir_file_operations      [zfs]
ffffffffa02fe5d0 t zpl_posix_acl_release_impl   [zfs]
ffffffffa02fe300 t zpl_set_acl  [zfs]
ffffffffa02feb00 t zpl_chmod_acl        [zfs]
ffffffffa048b638 b sa_dummy_zpl_layout  [zfs]
ffffffffa0197060 T zfs_zpl_version_map  [zcommon]
```

So it seems that these tools rely on symbols that are not exported. Any ideas of what can be done here? Ask the zfs people to export them? The "correct" address for the kprobes _could_ probably be extracted from `zpl_file_operations`, but I'm not sure whether that is a good idea. Thoughts?

**Comment by mskarbek** [comment]
Strange, all mentioned symbols are properly available on my installation - Fedora 27 and official ZoL repo, kernel-4.15.9-300.fc27.x86_64 and zfs-0.7.6-1.fc27.x86_64.

**Comment by jan-krieg** [comment]
I've run into the same issue with Gentoo and found that the solution is to set the `debug` USE flag for `sys-fs/zfs-kmod`. This way, the required symbols are not stripped out of the `extra/zfs/zfs.ko` module.

As such, I think this issue can be closed.

**Comment by jepio** [comment]
Fair enough. This is a general fragility of kprobe based tracing.

**Comment by jan-krieg** [comment]
> I've run into the same issue with Gentoo and found that the solution is to set the `debug` USE flag for `sys-fs/zfs-kmod`. This way, the required symbols are not stripped out of the `extra/zfs/zfs.ko` module.

As short update to above: apparently due to introduction of [linux-mod-r1.eclass](https://devmanual.gentoo.org/eclass-reference/linux-mod-r1.eclass/index.html) which has the default-on USE flag `strip`, one now needs to set `-strip` for `sys-fs/zfs-kmod` (or soon for `sys-fs/zfs` following the package merger at 2.4.0), while `debug` is not needed.
