### ISSUE TITLE
Can we remove perf reader for TRACEPOINT events?

### ISSUE THREAD

**Issue by palmtenor** [iovisor/bcc#1601]
If I understand correctly, the `perf_reader` in TRACEPOINT (kprobe / uprobe / Kernel Tracepoint) events logic is mostly in order to get the Callchain / IP for these events. However we already have the in-Kernel Stack-trace table and it was added quite early in BPF's development process. A quick check shows all our current BCC tools are using the in-Kernel Stack-trace table, and I would imagine most other users are probably also doing that as well.

Would it be possible for us to remove the `PERF_SAMPLE_RAW` / `PERF_SAMPLE_CALLCHAIN` / `perf_reader` logic from BCC's kprobe / uprobe / Kernel Tracepoint API? This would make the code simpler and more efficient, reduce possible issues like #1533 and make fixes like #1595 easier.

cc @4ast @drzaeus77 @yonghong-song

**Comment by 4ast** [comment]
makes sense to me

**Comment by yonghong-song** [comment]
Indeed, looks like 
```
class BPF(object):
...
    def __init__(self, src_file=b"", hdr_file=b"", text=None, cb=None, debug=0,
            cflags=[], usdt_contexts=[]):
```

No tools really uses `cb`, so I think it is safe to remove it.

But the issue with #1533 and #1595 could be different, they are from RAW output due to bpf_perf_event_output, so we may have to address them somehow.
