### ISSUE TITLE
Insecure GPG key download in Ubuntu installation instructions

### ISSUE THREAD

**Issue by Shnatsel** [iovisor/bcc#1604]
[Ubuntu installation instructions for BCC](https://github.com/iovisor/bcc/blob/master/INSTALL.md) list the following command:

`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys D4284CDD`

It uses a shortened GPG key ID, which is wildly insecure: a colliding GPG key can be found on a modern GPU in 4 seconds (see https://evil32.com/ for more info). The command then unconditionally marks the downloaded key as trusted by the package manager.

Please list the full key fingerprint for download via `apt-key adv`, or list an HTTPS download of the key instead.

**Comment by browdus** [comment]
It seems like this might be resolved with https://github.com/iovisor/bcc/commit/e55c68acfad72ce19cc51ecc73d4938bd5a6ff86
