### ISSUE TITLE
Porting bcc to other platforms

### ISSUE THREAD

**Issue by YutaroHayakawa** [iovisor/bcc#1606]
I’m currently trying to port eBPF to FreeBSD (https://github.com/YutaroHayakawa/generic-ebpf). It is based on ubpf (https://github.com/iovisor/ubpf) and I added some functionality to that (make it runnable in FreeBSD kernel space, added maps, added character device + ioctl interface as an alternative of bpf(2), and so on). 

I think it could be useful if we can reuse bcc for it. Is there any way to port bcc to other platforms? Or is this project already tied to Linux?

**Comment by brendangregg** [comment]
I think it should be possible to have bcc work on FreeBSD one day. Perhaps the biggest engineering work would be to map Linux's kprobes, uprobes, and tracepoints, to whatever BSD provides, as well as the perf_event ring buffers for passing per-event data to user space. The implementation details of these are already behind libbcc functions. Take bpf_attach_kprobe() for example, from src/cc/libbpf.c. That implements Linux details, like how kprobes work from /sys, but it could be changed to support a different instrumentation service.

**Comment by YutaroHayakawa** [comment]
Thank you for your reply. I see, that was exactly what I concerned. Probably we need to separate such platform dependent things (like kprobes, tracepoints, XDP and so on) and platform independent things (like ELF file parsing, map manipulation, etc) for porting bcc to other platforms. Well, even the map manipulation, or ELF parsing, it seems it’s tend to tied to the underlying Linux functionality right now and generalizing it is bit challenging.

Now I think it was too early to ask this. Since now eBPF is only for Linux, there is no reason to generalize bcc. If some other eBPF implementation appeared, please let someone re-open this issue.

Thank you very much for your help.
