### ISSUE TITLE
stackcount.py can show same stacks counted as separate entries 

### ISSUE THREAD

**Issue by joelagnel** [iovisor/bcc#1613]
On kernel 4.10, I observe that `tools/stackcount.py` can show duplicate stacks. At first I thought this was because the IPs could be different even though they resolve to be belonging to the same function, however I ran verbose mode and I see that the IPs are the same too.

For example, when reading a 20MB file using dd:
```
 # echo 3 > /proc/sys/vm/drop_caches 
 # dd if=tmp1 of=/dev/null bs=4k
```
And then `./tools/stackcount.py '*readpage*' -v`

Following is an excerpt showing 2 identical stacks counted as separate entries ([full stackcount output attached](https://github.com/iovisor/bcc/files/1769826/fullstackoutput.txt)).
```
  ffffffff900da451 ext4_readpages
  ffffffff8ffc21cd ondemand_readahead
  ffffffff8ffc235b page_cache_async_readahead
  ffffffff8ffb37c3 generic_file_read_iter
  ffffffff900d6142 ext4_file_read_iter
  ffffffff90045982 new_sync_read
  ffffffff900459f6 __vfs_read
  ffffffff90046356 vfs_read
  ffffffff90047865 sys_read
  ffffffff906dc37b entry_SYSCALL_64_fastpath
  7fc532d28890     [unknown]
    dd [8870]
    79

  ffffffff900da451 ext4_readpages
  ffffffff8ffc21cd ondemand_readahead
  ffffffff8ffc235b page_cache_async_readahead
  ffffffff8ffb37c3 generic_file_read_iter
  ffffffff900d6142 ext4_file_read_iter
  ffffffff90045982 new_sync_read
  ffffffff900459f6 __vfs_read
  ffffffff90046356 vfs_read
  ffffffff90047865 sys_read
  ffffffff906dc37b entry_SYSCALL_64_fastpath
  7fc532d28890     [unknown]
    dd [8870]
    83
```

**Comment by joelagnel** [comment]
Now come to think of it, could this be because the 2 stacks were collected on different CPUs?

**Comment by yonghong-song** [comment]
Yes, I think so. The perf event will attach to all online cpus and aggregation happens in the bpf program.

**Comment by joelagnel** [comment]
But the stacktrace map itself is not a per-cpu map right?
What baffles me a bit, is that, if the IPs are the same, then the hash entry (`stack_traces.get_stackid`) key into the `counts` map should be the same. Perhaps something else is making it non-unique?

**Comment by yonghong-song** [comment]
Sorry, my previous comments for `perf event attaching to all online cpus` refers to `profile.py`. The question here refers to `stackcount.py`.

Right stacktrace map is not per-cpu map.

I cannot reproduce the issue on latest bpf-next. The key to bucket stacktraces is:
```
struct key_t {
    // no pid (thread ID) so that we do not needlessly split this key
    u32 tgid;
    int kernel_stack_id;
    int user_stack_id;
    char name[TASK_COMM_LEN];
};
```
The above two stacks you showed should have the same key. Could you apply the following diff to debug a little bit?

```
diff --git a/tools/stackcount.py b/tools/stackcount.py
index 8a35bc0..cbeee03 100755
--- a/tools/stackcount.py
+++ b/tools/stackcount.py
@@ -358,6 +358,7 @@ class Tool(object):
                     if not self.args.pid and k.tgid != 0xffffffff:
                         self._print_comm(k.name, k.tgid)
                     print("    %d\n" % v.value)
+                    print(" us %d, ks %d, tgid %d\n" % (k.user_stack_id, k.kernel_stack_id, k.tgid))
             counts.clear()
```

**Comment by joelagnel** [comment]
Thanks @yonghong-song . Using the above debug patch, it seems the "us" is different. But still in the stack, the userspace IP is the same.

Here's the output with the patch:
```
  ffffffff900da451 ext4_readpages
  ffffffff8ffc21cd ondemand_readahead
  ffffffff8ffc235b page_cache_async_readahead
  ffffffff8ffb37c3 generic_file_read_iter
  ffffffff900d6142 ext4_file_read_iter
  ffffffff90045982 new_sync_read
  ffffffff900459f6 __vfs_read
  ffffffff90046356 vfs_read
  ffffffff90047865 sys_read
  ffffffff906dc37b entry_SYSCALL_64_fastpath
  7fca419f9890     [unknown]
    dd [11560]
    32
 us 930, ks 433, tgid 11560

  ffffffff900da451 ext4_readpages
  ffffffff8ffc21cd ondemand_readahead
  ffffffff8ffc235b page_cache_async_readahead
  ffffffff8ffb37c3 generic_file_read_iter
  ffffffff900d6142 ext4_file_read_iter
  ffffffff90045982 new_sync_read
  ffffffff900459f6 __vfs_read
  ffffffff90046356 vfs_read
  ffffffff90047865 sys_read
  ffffffff906dc37b entry_SYSCALL_64_fastpath
  7fca419f9890     [unknown]
    dd [11560]
    130
 us 883, ks 433, tgid 11560
```

**Comment by yonghong-song** [comment]
I cannot reproduce the issue on latest bpf-next. However, by looking at the kernel code, I think we do have a race condition which could lead to this scenario:
(1). user tries to get ip addresses for a particular stack id, and it grabs a bucket successfully (in function `bpf_stackmap_copy`.
(2). another asynchronously calls `bpf_get_stackid`. due to bucket collision with the same ID but not the same hash, the bucket grabbed by (1) is freed. the freed bucket is put into percpu free list.
(3). another `bpf_get_stackid` called and grabs the bucket from the percpu free list and sets the new value.
(4). the `bpf_stackmap_copy` in step (1) continues, but now it copies the IP addresses set in step (3).

This should be really really rare. I am not sure whether this is the cause of this issue or not since I cannot reproduce easily.

**Comment by 4ast** [comment]
could you please check what stack_traces.walk(k.user_stack_id) actually walking.
I think StackWalker may skip addresses that are not resolving ? so python printed output may look the same, but user stack traces are actually different.

**Comment by yonghong-song** [comment]
The stack walker code for `next`:
```
        def next(self):
            self.n += 1
            if self.n == StackTrace.MAX_DEPTH:
                raise StopIteration()

            addr = self.stack.ip[self.n]
            if addr == 0 :
                raise StopIteration()

            return self.resolve(addr) if self.resolve else addr
```

In this particular instance, `resolve = None`. Maybe in one of stacks, there is an address is `0` and the other not? The code in `table.py`. @joelagnel, maybe you could add some debug information there to debug a little bit?

**Comment by joelagnel** [comment]
addr 0 marks the end of the iteration so that's normal I think. Probably I need to debug deeper (at the time to the stack is generated). I am also on slightly older kernel (4.10), I will see if I can repro on bpf-next as well.

**Comment by joelagnel** [comment]
@4ast StackWalker itself doesn't stop iterating if a symbol can't be resolved I think. @yonghong-song both stacks have an address 0 to mark the termination.

**Comment by yonghong-song** [comment]
@joelagnel The code portion to compute hash in stackmap did not really change since its inception.... I am using the latest bpf-next and not able to reproduce the issues with your commands in the above.

**Comment by joelagnel** [comment]
I looked into the IPs of the user stack and compared 4.10 and 4.16-rc2 (bpf-next). It seems that on 4.10, many times the stacks have 0 as of one of the address, followed by some more non-0 addresses. I feel this is some difference in the stack unwinding differences between the 2 kernel versions. However, even on 4.16-rc2, I can still see 0s (although rarely) among the IPs.

To see the IPs, you could apply the following diff and run the commands I shared:
```
diff --git a/kernel/bpf/stackmap.c b/kernel/bpf/stackmap.c
index b0ecf43f5894..8facea3dcd91 100644
--- a/kernel/bpf/stackmap.c
+++ b/kernel/bpf/stackmap.c
@@ -128,6 +128,7 @@ BPF_CALL_3(bpf_get_stackid, struct pt_regs *, regs, struct bpf_map *, map,
        bool user = flags & BPF_F_USER_STACK;
        bool kernel = !user;
        u64 *ips;
+       int i;
 
        if (unlikely(flags & ~(BPF_F_SKIP_FIELD_MASK | BPF_F_USER_STACK |
                               BPF_F_FAST_STACK_CMP | BPF_F_REUSE_STACKID)))
@@ -153,6 +154,12 @@ BPF_CALL_3(bpf_get_stackid, struct pt_regs *, regs, struct bpf_map *, map,
        trace_len = trace_nr * sizeof(u64);
        ips = trace->ip + skip + init_nr;
        hash = jhash2((u32 *)ips, trace_len / sizeof(u32), 0);
+
+       trace_printk("user=%d kernel=%d hash=%x\n", !!user, !!kernel, hash);
+       for (i = 0; i < (trace_len / sizeof(u32)); i++)
+               trace_printk("ip = %x\n", ips[i]);
+       trace_printk("----\n");
+
        id = hash & (smap->n_buckets - 1);
        bucket = READ_ONCE(smap->buckets[id]);
```
and check the ftrace buffer.

With this diff, on one occassion I saw the following on bpf-next (second IP for this stack is 0).
```
          python-1933  [003] ....  8334.758706: bpf_get_stackid: user=1 kernel=0 hash=117d64aa
          python-1933  [003] ....  8334.758708: bpf_get_stackid: ip = 75081820
          python-1933  [003] ....  8334.758708: bpf_get_stackid: ip = 0
          python-1933  [003] ....  8334.758709: bpf_get_stackid: ip = a79b9bfc
          python-1933  [003] ....  8334.758709: bpf_get_stackid: ip = a7b004bc
          python-1933  [003] ....  8334.758709: bpf_get_stackid: ----
```

I think `perf_callchain_user` can return stacks with 0 in them. Probably due to stack unwinding challenges? One fix could be to only hash IPs until the 0 address and ignore ones after since we don't walk anything after the 0 anyway.

**Comment by joelagnel** [comment]
Apologies, I screwed up the debug patch printing the IPs. I will redo it and clean up these comments. thx

**Comment by palmtenor** [comment]
Maybe `dd` was compiled without preserving frame pointer, and the frame pointer register is used for other purposes. So even the current IP (top frame) is the same, because of different runtime context we may walk an additional 0 frame. I think I've seen this on `ps` on Cent OS before.

**Comment by palmtenor** [comment]
Maybe `dd` was compiled without preserving frame pointer, and the frame pointer register is used for other purposes. So even the current IP (top frame) is the same, because of different runtime context we may walk an additional 0 frame. 

The proposed patch would definitely be a good improvement, but I don't think it really addressed the root cause. The incorrectly walked frame might be 0 or some other garbage, and if that address coincide with some content we may walk even more incorrect frames. I've seen that on `ps` from Cent OS before.

Using LBR for the stack trace in such case might be a more fundamental solution, but that for sure would also has its own issues......

**Comment by yonghong-song** [comment]
The following code is the perf stack walking code (function `perf_callchain_user`):

```
        pagefault_disable();
        while (entry->nr < entry->max_stack) {
                unsigned long bytes;

                frame.next_frame             = NULL;
                frame.return_address = 0;

                if (!valid_user_frame(fp, sizeof(frame)))
                        break;

                bytes = __copy_from_user_nmi(&frame.next_frame, fp, sizeof(*fp));
                if (bytes != 0)
                        break;
                bytes = __copy_from_user_nmi(&frame.return_address, fp + 1, sizeof(*fp));
                if (bytes != 0)
                        break;

                perf_callchain_store(entry, frame.return_address);
                fp = (void __user *)frame.next_frame;
        }
        pagefault_enable();
```

So, yes, if user application does not maintain frame pointer properly. The return address copied could be garbage...

**Comment by joelagnel** [comment]
Thanks. In my disassembly of `dd`, I couldn't find ebp being used properly. Here's the output of `objdump -d` on `/bin/dd` on my Ubuntu 17.04 machine:
[dd.txt](https://github.com/iovisor/bcc/files/1778965/dd.txt)
I suspect that unwinding for this reason fails early (as you guys also mentioned).

Interestingly though it seems the `perf_callchain_user` is exactly the same on both kernels I am comparing (4.10 and 4.16-rc2/bpf-next) however the unwinding behavior seems different. On 4.10 I have a 0 as the last IP much more often.

Lastly, I wonder if it makes sense to do some basic sanity checking in `perf_callchain_user` itself for the `frame.return_address` before storing it (such as is it within the range of the code section, non-zero etc) and if not terminate the loop.

**Comment by joelagnel** [comment]
Sorry for the late reply as I'm traveling at a conf.
> However, it may still be garbage, so it cannot completely resolve the issue.
True but atleast we know 0 is also an "invalid" IP so we can check for that and avoid it in the IP list? I will float a patch to LKML and see what folks think as well (will CC you). Agreed LBR or binary debug info based unwinding if can be done in-kernel is better.

**Comment by yonghong-song** [comment]
Sounds good to me. Thanks!

**Comment by joelagnel** [comment]
Considering other higher priority issues, and since on mainline the stack unwinding doesn't show this issue, I am closing this bug for now. Lets reopen it in the future if needed. Thanks
