### ISSUE TITLE
opensnoop.py and ArgString

### ISSUE THREAD

**Issue by b3t4Test3r** [iovisor/bcc#1622]
When I try to execute opensnoop.py I got the follow error :

```
 File "opensnoop.py", line 17, in <module>
    from bcc import ArgString, BPF
ImportError: cannot import name ArgString
```
on ubuntu desktop
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
```

Can someone help me, because I've no idea.
Thanks

**Comment by pchaigno** [comment]
What version of bcc do you have? How did you install it?

**Comment by b3t4Test3r** [comment]
I installed bcc has racommended here:

[](https://github.com/iovisor/bcc/blob/master/INSTALL.md#ubuntu---binary)

**Comment by b3t4Test3r** [comment]
I installed bcc as recommended here:

https://github.com/iovisor/bcc/blob/master/INSTALL.md#ubuntu---binary

**Comment by pchaigno** [comment]
Are you running the version of `execsnoop` from the packages or the last version from the source?

**Comment by b3t4Test3r** [comment]
I was running the opensnoop.py from sources. Now I installed bcc from sources and it's ok.
Thanks for your support :)

**Comment by pmcgrath** [comment]
Seeing the same issue with opensnoop.py on ubuntu 16.04 where I also installed bcc via the ubuntu binary installation
