### ISSUE TITLE
attaching multiple functions to a single kprobe from the same process

### ISSUE THREAD

**Issue by andihit** [iovisor/bcc#1631]
I want to extend a daemon which runs multiple BCC programs at the same time ([PCP BCC PMDA](https://github.com/performancecopilot/pcp/tree/master/src/pmdas/bcc)).

At the moment I can't attach to the same kprobe multiple times from the same process:
```
b1 = BPF(text="int probe1(void *ctx) { return 0; }")
b1.attach_kprobe(event="sys_clone", fn_name="probe1")

b2 = BPF(text="int probe2(void *ctx) { return 0; }")
b2.attach_kprobe(event="sys_clone", fn_name="probe2")
```

Looking at #872 and #918 it seems this is mainly due to the event naming pattern `$(eventname)_bcc_$(pid)`.

I'd suggest to extend this unique identifier with an unique id of the BPF class (e.g. address of the `ebpf::BPF` instance in memory for C++, and `id()` of the `bcc.BPF` class for Python)

A possible workaround at the moment would be to group all kprobes from all BCC tools into a single one by merging the C code (and rewriting all identifiers etc.). However, I think extending the event naming pattern with an unique ID per BPF class instance is the cleaner approach here.

What do you think? Should I start working on a PR?

**Comment by palmtenor** [comment]
Definitely a valid issue. But I think the Perf Event based k/uprobes are already in Kernel which shouldn't have these issues at all (see #1518). Is it still worth adding more complicated logic to the `debugfs`-based interface anymore?

**Comment by andihit** [comment]
Do you know if this code is already merged? I'm looking at this commit right now: https://git.kernel.org/pub/scm/linux/kernel/git/peterz/queue.git/commit/?h=perf/core&id=e12f03d7031a977356e3d7b75a68c2185ff8d155 but can't find it in the mainline kernel sources.

**Comment by palmtenor** [comment]
Looks like these patches are in `tip` now, should get merged in next window. @yonghong-song probably knows better about this~

**Comment by yonghong-song** [comment]
It just merged in tip master:
https://kernel.googlesource.com/pub/scm/linux/kernel/git/tip/tip/

So it should show up in linus tree in the next kernel merge window.

**Comment by yonghong-song** [comment]
It may take a few weeks (~3) to reach linus tree.

**Comment by andihit** [comment]
Thanks! I'll close this issue then.

**Comment by myllynen** [comment]
For the record this seems to work ok with 4.17-rc5 and a recent bcc nightly.

**Comment by maxdml** [comment]
I have a 4.15 kernel. Would it make sense to allow users to give an additional `event_id` argument to `attach_kprobe` and `detach_kprobe`, so that the same process can attach multiple functions to the same event?

Something like:
```

diff --git a/src/python/bcc/__init__.py b/src/python/bcc/__init__.py
index 4024afd..40b7f46 100644
--- a/src/python/bcc/__init__.py
+++ b/src/python/bcc/__init__.py
@@ -580,11 +580,12 @@ class BPF(object):
             if name.startswith(prefix):
                 return self.get_syscall_fnname(name[len(prefix):])
         return name
-       
-    def attach_kprobe(self, event=b"", event_off=0, fn_name=b"", event_re=b""):
+
+    def attach_kprobe(self, event=b"", event_off=0, fn_name=b"", event_re=b"", event_id=b""):
         event = _assert_is_bytes(event)
         fn_name = _assert_is_bytes(fn_name)
         event_re = _assert_is_bytes(event_re)
+        event_id = _assert_is_bytes(event_id)
 
         # allow the caller to glob multiple functions together
         if event_re:
@@ -599,7 +600,7 @@ class BPF(object):
 
         self._check_probe_quota(1)
         fn = self.load_func(fn_name, BPF.KPROBE)
-        ev_name = b"p_" + event.replace(b"+", b"_").replace(b".", b"_")
+        ev_name = b"p_" + event.replace(b"+", b"_").replace(b".", b"_") + event_id
         fd = lib.bpf_attach_kprobe(fn.fd, 0, ev_name, event, event_off)
         if fd < 0:
             raise Exception("Failed to attach BPF program %s to kprobe %s" %
@@ -642,9 +643,9 @@ class BPF(object):
             raise Exception("Failed to detach BPF from kprobe")
         self._del_kprobe_fd(ev_name)
 
-    def detach_kprobe(self, event):
+    def detach_kprobe(self, event, event_id):
         event = _assert_is_bytes(event)
-        ev_name = b"p_" + event.replace(b"+", b"_").replace(b".", b"_")
+        ev_name = b"p_" + event.replace(b"+", b"_").replace(b".", b"_") + event_id
         self.detach_kprobe_event(ev_name)
 
     def detach_kretprobe(self, event):
```

**Comment by yonghong-song** [comment]
On Fri, Nov 30, 2018 at 7:54 AM Max dml <notifications@github.com> wrote:

> I have a 4.15 kernel. Would it make sense to allow users to give an
> additional event_id argument to attach_kprobe and detach_kprobe, so that
> the same process can attach multiple functions to the same event and
> distinguish them with a unique ID?
>

Linux 4.17 and later implemented FD-based kuprobe:
```
commit e12f03d7031a977356e3d7b75a68c2185ff8d155
Author: Song Liu <songliubraving@fb.com>
Date:   Wed Dec 6 14:45:15 2017 -0800

    perf/core: Implement the 'perf_kprobe' PMU

    A new PMU type, perf_kprobe is added. Based on attr from
perf_event_open(),
    perf_kprobe creates a kprobe (or kretprobe) for the perf_event. This
    kprobe is private to this perf_event, and thus not added to global
    lists, and not available in tracefs.

    Two functions, create_local_trace_kprobe() and
    destroy_local_trace_kprobe()  are added to created and destroy these
    local trace_kprobe.
```
bcc has implemented this. So for 4.17 and later, bcc user space is able to
attach to the same
process multiple times for the same kprobe.

Also, what is you use case to attach multiple programs to the same kprobe?

Something like:

**Comment by maxdml** [comment]
> Also, what is you use case to attach multiple programs to the same kprobe?

I was designing my program the wrong way, attaching and detaching multiple variants of what was otherwise mostly the same ePBF program to the same kprobe, rather than updating the shared maps. If need be I will update to 4.17 :)

Thanks for the clarification.
