### ISSUE TITLE
BPF stack size

### ISSUE THREAD

**Issue by ggaurav10** [iovisor/bcc#1650]
I am trying to read the data that is written on the disk in block size of 4k by attaching probe to kernel functions.
For this, i tried to initialise a char array of size 4k in which I intend to copy the data from the buffers. I get the error reported in #212
I tried to reduce the size of the char array until I stop getting the above error. After reducing it below 1k, i get the below error
```
invalid stack off=-520 size=8

HINT: Looks like you exceeded the BPF stack limit. This can happen if you allocate too much local variable storage. For example, if you allocated a 1 Kbyte struct (maybe for BPF_PERF_OUTPUT), busting a max stack of 512 bytes.
```
Finally, currently I am working with size 350 bytes and then submitting event for each chunk of 4k data (in an unrolled loop). Is there a way around it? Is it possible to define a char pointer and allocating 4k bytes of memory (using kmalloc maybe) in the bpf program?

Thanks.

**Comment by yonghong-song** [comment]
Currently, no. The stack size is limited to 512 bytes, and there is no kmalloc style dynamic allocation inside the bpf program either. One way you could try is with per-cpu map with value size of 4k and fill in the 4k map value and submit it with the map value. But I never tried this before.
