### ISSUE TITLE
bcc complie failed on centos7 use llvm

### ISSUE THREAD

**Issue by wenxq** [iovisor/bcc#1651]
compile bcc with llvm(master or stable branch) failed, follow is error message:

/home/source/perf/bcc/src/cc/frontends/b/codegen_llvm.cc: In member function ‘virtual ebpf::StatusTuple ebpf::cc::CodegenLLVM::visit_string_expr_node(ebpf::cc::StringExprNode*)’:
/home/source/perf/bcc/src/cc/frontends/b/codegen_llvm.cc:428:52: error: no matching function for call to ‘llvm::IRBuilder<>::CreateMemCpy(llvm::Value*&, llvm::Value*&, std::basic_string<char>::size_type, int)’
   B.CreateMemCpy(ptr, global, n->val_.size() + 1, 1);
                                                    ^
/home/source/perf/bcc/src/cc/frontends/b/codegen_llvm.cc:428:52: note: candidates are:
In file included from /home/source/perf/bcc/src/cc/frontends/b/codegen_llvm.cc:31:0:
/home/install/include/llvm/IR/IRBuilder.h:423:13: note: llvm::CallInst* llvm::IRBuilderBase::CreateMemCpy(llvm::Value*, unsigned int, llvm::Value*, unsigned int, uint64_t, bool, llvm::MDNode*, llvm::MDNode*, llvm::MDNode*, llvm::MDNode*)
   CallInst *CreateMemCpy(Value *Dst, unsigned DstAlign, Value *Src,
             ^
/home/install/include/llvm/IR/IRBuilder.h:423:13: note:   candidate expects 10 arguments, 4 provided
/home/install/include/llvm/IR/IRBuilder.h:434:13: note: llvm::CallInst* llvm::IRBuilderBase::CreateMemCpy(llvm::Value*, unsigned int, llvm::Value*, unsigned int, llvm::Value*, bool, llvm::MDNode*, llvm::MDNode*, llvm::MDNode*, llvm::MDNode*)
   CallInst *CreateMemCpy(Value *Dst, unsigned DstAlign, Value *Src,
             ^
/home/install/include/llvm/IR/IRBuilder.h:434:13: note:   candidate expects 10 arguments, 4 provided

**Comment by yonghong-song** [comment]
What is LLVM version you are using?

**Comment by wenxq** [comment]
LLVM version is 7.0.0


________________________________
发件人: yonghong-song <notifications@github.com>
发送时间: 2018年3月26日 15:57
收件人: iovisor/bcc
抄送: wenxq; Author
主题: Re: [iovisor/bcc] bcc complie failed on centos7 use llvm (#1651)


What is LLVM version you are using?

―

**Comment by yonghong-song** [comment]
Could you try latest bcc trunk? It is supposed to fix a CreateMemCpy issue.

**Comment by wenxq** [comment]
ok, compile pass


________________________________
发件人: yonghong-song <notifications@github.com>
发送时间: 2018年4月11日 14:09
收件人: iovisor/bcc
抄送: wenxq; Author
主题: Re: [iovisor/bcc] bcc complie failed on centos7 use llvm (#1651)


Could you try latest bcc trunk? It is supposed to fix a CreateMemCpy issue.

―
