### ISSUE TITLE
Unable to get stack trace from a TRACEPOINT_PROBE

### ISSUE THREAD

**Issue by joelagnel** [iovisor/bcc#1706]
Hi, I'm writing a tool to get the stack trace from a `TRACEPOINT_PROBE` however this needs a `ctx` (`struct pt_regs`). 

Unlike a kprobe, From a tracepoint probe, we don't have `ctx` though. Any ideas on how we can solve this? The program looks something like this
```
TRACEPOINT_PROBE(preemptirq, irq_enable)
{
    struct data_t data = {};

    /* ISSUE: probes don't have ctx, what do you pass for stacks? */
    data.stack_id = stack_traces.get_stackid(ctx, BPF_F_REUSE_STACKID);
[...]
}
```

`trace_dump_stack()` and `dump_stack()` don't need `ctx` so in theory it ought to be possible if we can export a helper for a non-ctx based stack trace mechanism?

**Comment by goldshtn** [comment]
Using `args` should work, it’s the context equilavent for tracepoints. I
think you can see an example in trace.py where you can use -U and -K with
tracepoints, such as:

trace t:block:block_rq_insert -K

**Comment by joelagnel** [comment]
Ah yes! I should have tried that. Thanks a lot Sasha! I'll close this for now and reopen if I still have issues. Best,
