### ISSUE TITLE
bpf_trace_printk() prints garbled text on powerpc64

### ISSUE THREAD

**Issue by sandip4n** [iovisor/bcc#1723]
As reported by @chandanr, upon running a simple script like the following on a `powerpc64` (big endian) system, the text printed by `bpf_trace_printk()` is garbled.

```
#!/usr/bin/env python

from bcc import BPF

program = r"""
int hello(void *ctx)
{
        bpf_trace_printk("Hello, World!\\n");
        return 0;
}
"""

b = BPF(text=program)
b.attach_kprobe(event="sys_write", fn_name="hello")
print("%-18s %-16s %-6s %s" % ("TIME(s)", "COMM", "PID", "MESSAGE"))

while True:
    try:
        (task, pid, cpu, flags, ts, msg) = b.trace_fields()
    except ValueError:
        continue
    print "hello: %-18.9f %-16s %-6d %s" % (ts, task, pid, msg)
```

The output from this script is:
```
TIME(s)            COMM             PID    MESSAGE
hello: 60275.886506000    bash             9907   W ,olleHdlro
hello: 60368.518992000    !         system -1     W ,olleHdlro
hello: 60421.502999000    !            tmu -9617  W ,olleHdlro
...
```
Also, if either `,` or `!` is removed from the format string, the probe handler is not even invoked.
If similar `bpf_trace_printk()` calls are added to any of the kernel samples (`samples/bpf/*_kern.c`), the output is as expected.
The test system is running Fedora 27 with upstream `net-next` kernel and `bcc`.
There were no problems with running this on `powerpc64le` though.

**Comment by yonghong-song** [comment]
So the indicates, as expected, the issue is in bcc for `powerpc64be`. Maybe you could debug this a little more? `trace_fields` is defined in `src/python/bcc/__init__.py`. It takes the lines directly from
`/sys/kernel/debug/tracing/trace_pipe`. So, you can
 - first verify `/sys/kernel/debug/tracing/trace_pipe` contents are good, and then
 - verify `trace_fields` does right parseing for `powerpc64be`.

Thanks!

**Comment by sandip4n** [comment]
Hi @yonghong-song 

Sorry I forgot to mention this earlier but the `trace_pipe` content is itself garbled.
From what I am seeing in the `bpftool dump xlated` output for the `bcc` script and the modified kernel sample, the string `Hello, World!\n` is pushed on to the stack by a series of stores that write constant values. These constant values seem to be have one or more bytes of the string.

This is the dump from the `bcc` script:
```
   0: (b7) r1 = 2593
   1: (6b) *(u16 *)(r10 -4) = r1
   2: (b7) r1 = 1684828783
   3: (63) *(u32 *)(r10 -8) = r1
   4: (18) r1 = 0x57202c6f6c6c6548
   6: (7b) *(u64 *)(r10 -16) = r1
   7: (b7) r1 = 0
   8: (73) *(u8 *)(r10 -2) = r1
   9: (bf) r1 = r10
  10: (07) r1 += -16
  11: (b7) r2 = 15
```
And this is the dump from the kernel sample:
```
   0: (b7) r1 = 8458
   1: (6b) *(u16 *)(r10 -4) = r1
   2: (b7) r1 = 1869769828
   3: (63) *(u32 *)(r10 -8) = r1
   4: (18) r1 = 0x48656c6c6f2c2057
   6: (7b) *(u64 *)(r10 -16) = r1
   7: (b7) r1 = 0
   8: (73) *(u8 *)(r10 -2) = r1
   9: (bf) r1 = r10
  10: (07) r1 += -16
  11: (b7) r2 = 15
```

`r1` is `fmt` and `r2` is `fmt_size` for `bpf_trace_printk()`
We can see that the same string is being encoded in two different ways and the encoding used by the `bcc` script is definitely wrong.

**Comment by yonghong-song** [comment]
This may be LLVM compiler issue generating incorrect code for big endian machine. Let me do more investigation on this.

**Comment by yonghong-song** [comment]
Looking at llvm code, I did not find any issue. This is consistent with your experiment that kernel samples/bpf works fine with powerpc64be.

Could you try the following two hacks on you big endian platform?
hack 1:
```
diff --git a/src/cc/bpf_module.cc b/src/cc/bpf_module.cc
index 65f6b7e..4a40628 100644
--- a/src/cc/bpf_module.cc
+++ b/src/cc/bpf_module.cc
@@ -616,7 +616,7 @@ int BPFModule::finalize() {
       *sections_p;
 
   mod->setDataLayout("e-m:e-p:64:64-i64:64-n32:64-S128");
-  mod->setTargetTriple("bpf-pc-linux");
+  mod->setTargetTriple("bpf");
   sections_p = rw_engine_enabled_ ? &sections_ : &tmp_sections;
 
   string err;
```
hack 2:
```
diff --git a/src/cc/bpf_module.cc b/src/cc/bpf_module.cc
index 65f6b7e..4cc1f20 100644
--- a/src/cc/bpf_module.cc
+++ b/src/cc/bpf_module.cc
@@ -616,14 +616,14 @@ int BPFModule::finalize() {
       *sections_p;
 
   mod->setDataLayout("e-m:e-p:64:64-i64:64-n32:64-S128");
-  mod->setTargetTriple("bpf-pc-linux");
+  mod->setTargetTriple("bpfeb");
   sections_p = rw_engine_enabled_ ? &sections_ : &tmp_sections;
 
   string err;
   EngineBuilder builder(move(mod_));
   builder.setErrorStr(&err);
   builder.setMCJITMemoryManager(ebpf::make_unique<MyMemoryManager>(sections_p));
-  builder.setMArch("bpf");
+  builder.setMArch("bpfeb");
   builder.setUseOrcMCJITReplacement(false);
   engine_ = unique_ptr<ExecutionEngine>(builder.create());
   if (!engine_) {
```

**Comment by sandip4n** [comment]
No luck with either of the hacks.

**Comment by sandip4n** [comment]
@yonghong-song 
I tried dumping the LLVM IR generated for the probe handler through this hack.
```
diff --git a/src/cc/frontends/clang/loader.cc b/src/cc/frontends/clang/loader.cc
index eb6a307..49b918f 100644
--- a/src/cc/frontends/clang/loader.cc
+++ b/src/cc/frontends/clang/loader.cc
@@ -382,6 +382,7 @@ int ClangLoader::do_compile(unique_ptr<llvm::Module> *mod, TableStorage &ts,
   if (!compiler2.ExecuteAction(ir_act))
     return -1;
   *mod = ir_act.takeModule();
+  mod->get()->print(llvm::errs(), nullptr);
 
   return 0;
 }
```

If I manually generate the object file from this IR dump by piping it to `llc -march=bpf -filetype=obj -o bcc-hello.o` and then run `llvm-objdump -d bcc-hello.o` I see the correct values being used for representing the string.

```
Disassembly of section .bpf.fn.hello:
hello:
       0:       b7 10 00 00 00 00 21 0a         r1 = 8458
       1:       6b a1 ff fc 00 00 00 00         *(u16 *)(r10 - 4) = r1
       2:       b7 10 00 00 6f 72 6c 64         r1 = 1869769828
       3:       63 a1 ff f8 00 00 00 00         *(u32 *)(r10 - 8) = r1
       4:       18 10 00 00 6f 2c 20 57 00 00 00 00 48 65 6c 6c         r1 = 5216694956356018263ll
       6:       7b a1 ff f0 00 00 00 00         *(u64 *)(r10 - 16) = r1
       7:       b7 10 00 00 00 00 00 00         r1 = 0
       8:       73 a1 ff fe 00 00 00 00         *(u8 *)(r10 - 2) = r1
       9:       bf 1a 00 00 00 00 00 00         r1 = r10
      10:       07 10 00 00 ff ff ff f0         r1 += -16
      11:       b7 20 00 00 00 00 00 0f         r2 = 15
      12:       85 00 00 00 00 00 00 06         call 6
      13:       b7 00 00 00 00 00 00 00         r0 = 0
      14:       95 00 00 00 00 00 00 00         exit
```

So, there must be something going wrong in the IR to BPF object conversion stage.

**Comment by sandip4n** [comment]
Found a fix but am not sure if this might break something else.
```
diff --git a/src/cc/bpf_module.cc b/src/cc/bpf_module.cc
index 65f6b7e..9344340 100644
--- a/src/cc/bpf_module.cc
+++ b/src/cc/bpf_module.cc
@@ -615,7 +615,6 @@ int BPFModule::finalize() {
   std::map<std::string, std::tuple<uint8_t *, uintptr_t>> tmp_sections,
       *sections_p;
 
-  mod->setDataLayout("e-m:e-p:64:64-i64:64-n32:64-S128");
   mod->setTargetTriple("bpf-pc-linux");
   sections_p = rw_engine_enabled_ ? &sections_ : &tmp_sections;
 
```
The data layout in the IR dump is `E-m:e-i64:64-n32:64`. If I set it to this or don't set it explicitly at all (in which case I am assuming it uses whatever is defined in the IR), I see the correct output.

@drzaeus77 Since the original commit `52b0a903` was authored by you, maybe you could throw some light on the matter.

**Comment by yonghong-song** [comment]
@sandip4n This is the correct fix.

In LLVM BPF target, we have
```
static std::string computeDataLayout(const Triple &TT) {
  if (TT.getArch() == Triple::bpfeb)
    return "E-m:e-p:64:64-i64:64-n32:64-S128";
  else
    return "e-m:e-p:64:64-i64:64-n32:64-S128";
}
```,

So for big endian it should be `E-m:e ...`. But for `IR->bytecode` translation, as long as we pass triple/arch `bpf` to LLVM, we do not need to specify layout any more.

So your change above looks good. Could you submit a patch? Thanks!

**Comment by sandip4n** [comment]
@yonghong-song Thanks for the quick review and explanation.
Sure, I'll open a pull request for this.
