### ISSUE TITLE
Fail to compile bcc on debian stretch

### ISSUE THREAD

**Issue by yuzibo** [iovisor/bcc#1735]
Hello, 
i have followed the instructions 
[https://github.com/iovisor/bcc/blob/master/INSTALL.md#debian---source](debian)
Please note: i don't install linux-image-xx,because i installed my custom kernel : 4.17-rc2.
Then,  i installed BCC building  dependencies,
Last, i got the error:
69% tests passed, 11 tests failed out of 35

Total Test time (real) = 186.24 sec

The following tests FAILED:
	  7 - py_test_xlate1_c (Failed)
	  8 - py_test_call1 (Failed)
	 10 - py_test_trace2 (Failed)
	 11 - py_test_trace3_c (Failed)
	 15 - py_test_brb (Failed)
	 16 - py_test_brb2 (Failed)
	 17 - py_test_clang (Failed)
	 18 - py_test_histogram (Failed)
	 27 - py_test_tools_smoke (Failed)
	 29 - py_test_usdt (Failed)
	 32 - lua_test_clang (Failed)
Errors while running CTest
Makefile:86: recipe for target 'test' failed
make[2]: *** [test] Error 8
make[2]: Leaving directory '/home/yubo/git/bcc/obj-x86_64-linux-gnu'
dh_auto_test: make -j1 test ARGS+=-j1 returned exit code 2
debian/rules:16: recipe for target 'override_dh_auto_test' failed
make[1]: *** [override_dh_auto_test] Error 2
make[1]: Leaving directory '/home/yubo/git/bcc'
debian/rules:12: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
debuild: fatal error at line 1116:
dpkg-buildpackage -rfakeroot -us -uc -b failed

How i can pass the python_test_*?
Thank you!

**Comment by pchaigno** [comment]
Could you add the error messages for these tests to your original post?

**Comment by yuzibo** [comment]
@pchaigno 
　Thank you very much for your fast reply!
bcc install log is [https://github.com/yuzibo/linux-programming/blob/master/tmp/bcc_0.5.0-1_amd64.build](here)
Thanks again

**Comment by yonghong-song** [comment]
cc @AndrewAday @arssher
Maybe you can refer to the issue https://github.com/iovisor/bcc/issues/1434 for more information about pass effort on debian. For some networking related tests, probably you lack certain python modules.

**Comment by yuzibo** [comment]
Thanks all.
I have install bcc refer to [here](https://opensource.com/article/17/11/bccbpf-performance#comments)
Just try:
```bash
cmake .
sudo make
sudo make install 
```
