### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by bobrik** [iovisor/bcc#1740]
While working on #1728 I found that some APIs changed since the last release. We should probably cut another release to allow people to hack on tools easily.

Examples of errors I'm facing:

```
Traceback (most recent call last):
  File "/tmp/runqslower.py", line 213, in <module>
    is_support_raw_tp = BPF.support_raw_tracepoint()
AttributeError: type object 'BPF' has no attribute 'support_raw_tracepoint'
```

```
Traceback (most recent call last):
  File "/tmp/runqslower.py", line 261, in <module>
    b.perf_buffer_poll()
AttributeError: 'BPF' object has no attribute 'perf_buffer_poll'
```

cc @yonghong-song, @drzaeus77, @palmtenor

**Comment by palmtenor** [comment]
@brendangregg

**Comment by rushabh268** [comment]
To add to the list, here are some more errors that I'm seeing:

**Comment by myllynen** [comment]
Just wanted kindly to check is there any sort of rough estimate for the release date of the next release yet? There seems to be some Python 3 fixes in the master since 0.5.0 as well so a new release would be nice in that sense as well. Thanks.

**Comment by drzaeus77** [comment]
I'm hoping to enable a Fedora 28 buildbot in the next day or two, and will tag a release after that. Hopefully by the end of the week.

**Comment by myllynen** [comment]
This is wonderful news, thanks for letting us know!

**Comment by drzaeus77** [comment]
Hi, just to update, I've fixed a few of the Fedora 28 issues and am working on the last one, so the tag hasn't been created yet but shouldn't be much longer.

**Comment by yonghong-song** [comment]
@drzaeus77 Just wandering what is the progress on the new release? Any help you need?

**Comment by drzaeus77** [comment]
v0.6.0 is tagged and packages published. Unfortunately, fedora 28 support is not included.

**Comment by bobrik** [comment]
Apt packages seem to only have 0.5.0 in the index:

```
$ curl -s https://repo.iovisor.org/apt/xenial/dists/xenial/main/binary-amd64/Packages | grep ^Version
Version: 0.5.0-1
Version: 0.5.0-1
Version: 0.5.0-1
Version: 0.5.0-1
Version: 0.5.0-1
```

Actual deb files are there, it's just index that is out of date:

![image](https://user-images.githubusercontent.com/89186/41812768-088b2e0e-76de-11e8-974d-d0d17969fd1f.png)

Can you regenerate the index?

**Comment by yonghong-song** [comment]
cc @drzaeus77

**Comment by drzaeus77** [comment]
It is updated now.

**Comment by bobrik** [comment]
Thanks!

**Comment by Lakshmipathi** [comment]
On Fedora 28, I still see error like `AttributeError: 'BPF' object has no attribute 'get_syscall_fnname'` Fixes not yet available F28?

**Comment by palmtenor** [comment]
Is that because `https://repo.iovisor.org/yum/{nightly|main}/` doesn't have a `f28` subfolder yet?

**Comment by JerryOpenix** [comment]
Hit below error on ubuntu 18.04 which isn't hit on ubuntu 16.04:
            'BPF' object has no attribute 'get_syscall_fnname'
On ubuntu 18.04, I find that bcc version is 0.5.0
On ubuntu 16.04, bcc module version is 0.6.0

However, I failed to install 0.6.0 bcc python module on ubuntu 18.04. Any suggestion?

**Comment by yonghong-song** [comment]
cc @drzaeus77

**Comment by drzaeus77** [comment]
The 0.6.1 version is the latest, and only bionic supported version. The following should work for the tagged packages:

```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys D4284CDD
echo "deb https://repo.iovisor.org/apt/bionic bionic main" | sudo tee /etc/apt/sources.list.d/iovisor.list
sudo apt-get update
sudo apt-get install python-bcc
```

**Comment by chaiken** [comment]
I have installed 0.7.0-100 packages for bcc-tools, python-bcc, pyth3-bcc and libbcc-examples, yet I'm still hitting the 'BPF' object has no attribute 'get_syscall_fnname' problem.   'python -m site' shows that both python2.7 and python3 know about the bcc python package.     Might it be easier just to install from source, or won't that help?   

$ dpkg -l "*bcc*"
ii  bcc-tools         0.7.0-100.git.aed9b1e2 all          Command line tools for BPF Co
ii  libbcc            0.7.0-100.git.aed9b1e2 all          Shared Library for BPF Compil
ii  libbcc-examples   0.7.0-100.git.aed9b1e2 amd64        Examples for BPF Compiler Col
ii  libcc1-0:amd64    8.2.0-13               amd64        GCC cc1 plugin for GDB
ii  libccolamd2:amd64 1:5.4.0+dfsg-1         amd64        constrained column approximat
ii  python-bcc        0.7.0-100.git.aed9b1e2 all          Python wrappers for BPF Compi
ii  python3-bcc       0.7.0-100.git.aed9b1e2 all          Python3 wrappers for BPF Comp

**Comment by disconnect3d** [comment]
So... what's the proper way to fix errors like the one below?
```
Traceback (most recent call last):
  File "/tmp/runqslower.py", line 261, in <module>
    b.perf_buffer_poll()
AttributeError: 'BPF' object has no attribute 'perf_buffer_poll'
```

Or, in other words, is there any documentation for API changes?
