### ISSUE TITLE
trace.py with bad binary path and correct pid

### ISSUE THREAD

**Issue by javierhonduco** [iovisor/bcc#1749]
Hi,

While tracing some programs I usually add the program path and the pid: 
```shell
$ sudo /usr/share/bcc/tools/trace -p $(pidof ruby) 'u:ruby:array__create'
```
Unfortunately, if the path is not correct, like in this case, but the PID is correct, this fails with:
```
error in probe 'u:ruby:array__create': unrecognized USDT probe array__create
```

Do you think it would be interesting to check [here](https://github.com/iovisor/bcc/blob/master/src/python/bcc/usdt.py#L131) if the provided `path` actually exists and in that case throwing an error? informing somehow the user?, or checking the pid to verify if its valid and raise an exception if none of them are valid?

Let me know if checking this kind of stuff is out of the scope of the Python library and by default we assume this kind of data is correct!

Thanks!! :) 

cc/ @yonghong-song

**Comment by yonghong-song** [comment]
The `bcc_usdt_new_frompid` is used by C++, python and lua APIs, so the best place is in
`src/cc/usdt/usdt.cc`:
```
    393 void *bcc_usdt_new_frompid(int pid, const char *path) {
    394   USDT::Context *ctx;
    395 
    396   if (!path)
    397     ctx = new USDT::Context(pid);
    398   else
    399     ctx = new USDT::Context(pid, path);
```
When `path` is not NULL, you can verify `path` and print out the proper error message here.
