### ISSUE TITLE
Events from bcc generated programs in perf-record?

### ISSUE THREAD

**Issue by Mic92** [iovisor/bcc#1751]
I would like to use bcc to generate events from raw_syscall and 
feed the results into my running `perf-record`. 
Note that I cannot use bcc's own perf_event implementation
since I also dump processor trace events.
I saw that `bpf.dump_func` dumps BPF byte code however I cannot directly load this into perf.
It would be great if I somehow could use bcc to register a perf event that I could dump with the perf tool.

**Comment by palmtenor** [comment]
> Note that I cannot use bcc's own perf_event implementation since I also dump processor trace events.

What does it mean by processor trace events and what's not working?

**Comment by Mic92** [comment]
I would like to record processor trace events like `perf record -e intel_pt//` which are also described here: http://halobates.de/blog/p/410 and here https://github.com/torvalds/linux/blob/master/tools/perf/Documentation/intel-pt.txt
and combine this information with events submitted by bcc.

**Comment by Mic92** [comment]
perf seems to support something called `bpf-output`. Maybe I can use this event for bcc?

**Comment by Mic92** [comment]
`perf record -e bpf-output` does not record any event when I use simple examples such as https://github.com/iovisor/bcc/blob/master/examples/tracing/hello_perf_output.py

**Comment by palmtenor** [comment]
I see, makes sense. Yes we don't parse all the perf event samples, and I don't think BCC is a good place for those logic. I think running `perf` with BPF is generally possible, but I have never done it myself. Would [this presentation](https://events.static.linuxfound.org/sites/events/files/slides/Performance%20Monitoring%20and%20Analysis%20Using%20perf%20and%20BPF_1.pdf) be helpful to you?

**Comment by Mic92** [comment]
I found out that clang was adding hardening flags to my program. I finally got the following running:

```console
clang -fno-stack-protector -I /nix/store/c2bzlf0iwxg3f25s2i2vp16hkkmgk5k3-linux-4.14.35-dev/lib/modules/4.14.35/source/include/ -I /nix/store/c2bzlf0iwxg3f25s2i2vp16hkkmgk5k3-linux-4.14.35-dev/lib/modules/4.14.35/build/include -target bpf -O2 -c /home/joerg/git/hase/filter.c -o filter.o
```

```c
#include <uapi/linux/bpf.h>
#define SEC(NAME) __attribute__((section(NAME), used))
#define LINUX_VERSION_CODE 0x40e23
int _version SEC("version") = LINUX_VERSION_CODE;
char _license[] SEC("license") = "GPL";
// BPF_FUNC_trace_printk is a member of an enum, its value is 6
static int (*bpf_trace_printk)(const char *fmt, int fmt_size, ...) = (void *) BPF_FUNC_trace_printk;
#define printt(fmt, ...)                                                   \
        ({                                                                 \
                char ____fmt[] = fmt;                                      \
                bpf_trace_printk(____fmt, sizeof(____fmt), ##__VA_ARGS__); \
})
/* filter.c */
SEC("func=sys_clone")
int kprobe__sys_clone(struct pt_regs *ctx) {
        printt("hello\n");
  return 0;
}
```

```console
$ cat /sys/kernel/debug/tracing/trace
```
