### ISSUE TITLE
Strict version dependencies for debian packages

### ISSUE THREAD

**Issue by bobrik** [iovisor/bcc#1770]
Currently we have:

```
Package: python-bcc
Architecture: all
Depends: libbcc, python, binutils
Description: Python wrappers for BPF Compiler Collection (BCC)
```

```
Package: bcc-tools
Architecture: all
Depends: python-bcc
Description: Command line tools for BPF Compiler Collection (BCC)
```

We upgraded `bcc-tools` (it's the package end users care about) and it broke, because APIs changed in `libbcc`. I think we should require the same package version for all packages to avoid this.

**Comment by yonghong-song** [comment]
cc @drzaeus77

**Comment by palmtenor** [comment]
We should definitely make sure scripts and the library are from the same version......
