### ISSUE TITLE
Need for uapi/linux/ptrace.h include

### ISSUE THREAD

**Issue by bobrik** [iovisor/bcc#1771]
We have `uapi/linux/ptrace.h` included 90 times in `tools`:

```
$ fgrep 'uapi/linux/ptrace.h' -r tools | wc -l
      90
```

I removed it from `pidpersec` and it's stil working just fine. Do we need this?

**Comment by palmtenor** [comment]
I think that's probably for `struct pt_regs`. My guess is before the rewriter is less good on rewriting function parameters to `ctx` access, so people would use `struct pt_regs*` as type of `ctx` and then use `PT_REGS_PARMX` to access function parameters in kprobe / uprobe, or even just access `ctx->di` etc. directly.

Is this causing any particular issue for you?

**Comment by bobrik** [comment]
I'm copy-pasting it into my own programs, wanted to know why / if it's needed. If rewriter is smart enough now, should we remove the include?

**Comment by yonghong-song** [comment]
This is not related to rewriter. The `src/cc/export/helpers.h` is included in compilation by clang frontend. The `helpers.h` has a forward declaration for `struct pt_regs`. So if you reference to `struct pt_regs *`, but do not access any its members, you do not need `ptrace.h`. However, if you do need to access individual registers, you will need to include `ptrace.h` by yourself.
