### ISSUE TITLE
Python tutorial examples broken

### ISSUE THREAD

**Issue by myllynen** [iovisor/bcc#1777]
The examples using sys_clone in https://github.com/iovisor/bcc/blob/master/docs/tutorial_bcc_python_developer.md seem to be broken on 4.17-rc6 / latest bcc nightly, changing sys_clone to __x64_sys_clone would be a way to fix this that's of course platform dependent.

**Comment by pchaigno** [comment]
Since it's only for the tutorial, we could switch to some other, easy-to-trigger syscall. Do you want to open a pull request?

**Comment by fche** [comment]
Do you have access to the general sys_enter tracepoint?

**Comment by palmtenor** [comment]
Actually, can we have Python's `BPF._trace_autoload` to check if the kprobe function name is starting with `sys` or `SyS` and if yes, call `BPF.get_syscall_fnname`?

**Comment by yonghong-song** [comment]
`_trace_autoload` already implemented the checking.

**Comment by dustin-decker** [comment]
I think #1869 is related.
