### ISSUE TITLE
tcplife port filtering not working with tracepoints

### ISSUE THREAD

**Issue by myllynen** [iovisor/bcc#1788]
While generating TCP traffic using remote port 80 this command on 4.17 does not produce any output:

```
tcplife -D 80
```

If I omit port filtering, then I see results as expected.

It turns out that if I modify the tcplife script so that the old kprobe based approach is used, then port filtering works as expected. It is not immediately clear to me why port filtering does not work with the tracepoint based BPF variant.

**Comment by pchaigno** [comment]
Thanks for reporting the issue!

#1789 should fix it. Can you try it out?

**Comment by myllynen** [comment]
Fix confirmed, thanks for your prompt response!
