### ISSUE TITLE
Consider adding method providing bcc version

### ISSUE THREAD

**Issue by myllynen** [iovisor/bcc#1791]
Since there are still occasional changes in bcc affecting (at least external Python) applications using it, perhaps might make sense to add a helper method to determine easily what version of bcc is available and thus allow applications to select the suitable BPF program and/or BCC method variants accordingly.

**Comment by andihit** [comment]
I'd suggest adding a `__version__` attribute for the python module ([PEP 396](https://www.python.org/dev/peps/pep-0396/))

**Comment by myllynen** [comment]
Yes, that `__version__` sounds much better.

@drzaeus77 do you think this could still be added before cutting the next release?

Thanks.

**Comment by yonghong-song** [comment]
@myllynen  @andihit  Could you create a pull request for this feature? It is totally possible to add this.
cc @drzaeus77

**Comment by andihit** [comment]
created PR #1826
