### ISSUE TITLE
Is it possible to return the pt_regs ctx in perf_submit?

### ISSUE THREAD

**Issue by fabio-oesch** [iovisor/bcc#1832]
I would like to monitor system calls like [vltrace](https://github.com/pmem/vltrace). Vltrace does not work anymore though with the new version of bpf and that is why I am trying to make my own.

To trace which syscall is being invoked I want to return the pt_regs in the signature but get a permission denied error when I try to call `events.perf_submit(ctx, ctx, sizeof(*ctx))`. Trying to copy ctx into a struct of pt_regs will only return 0 in all fields.

While I am on it. What is the structure of pt_regs since [pt_regs](https://elixir.bootlin.com/linux/latest/ident/pt_regs) exists in a lot of packages. Is this specific to the hardware I use?

**Comment by pchaigno** [comment]
> To trace which syscall is being invoked I want to return the pt_regs in the signature but get a permission denied error when I try to call `events.perf_submit(ctx, ctx, sizeof(*ctx))`. Trying to copy ctx into a struct of pt_regs will only return 0 in all fields.

[bcc rewrites](https://github.com/iovisor/bcc/blob/a9f96c0288db784eeea604762f202609b3f7ea3c/src/cc/frontends/clang/b_frontend_action.cc#L690-L696) `events.perf_submit(...)` to use the `bpf_perf_event_output` helper. That helper [expects a fourth argument](https://elixir.bootlin.com/linux/v4.17.1/source/kernel/trace/bpf_trace.c#L427) (second argument before rewrite, `ctx` in your case) of type `ARG_PTR_TO_MEM`. Then, because the type of `ctx` is `PTR_TO_CTX`, I think you're hitting [this check](https://elixir.bootlin.com/linux/v4.17.1/source/kernel/bpf/verifier.c#L1992) in the verifier. Not sure whether that's intentional.

It would help to see the exact error message you're getting.

> While I am on it. What is the structure of pt_regs since pt_regs exists in a lot of packages. Is this specific to the hardware I use?

Yes, that structure contains information on registers and other architecture-dependent information, so the specific structure used depends on your architecture.

> Vltrace does not work anymore though with the new version of bpf and that is why I am trying to make my own.

Perhaps a naive question, but wouldn't it be easier to fix vltrace?

**Comment by fabio-oesch** [comment]
Thank you for your answer. It seems that the error is as you have said that I hit a check in the verifier. I think I am getting this error because I try to access the pt_regs which is not on the stack, at least that's what I think is happening. I have found that someone had a [similar](https://github.com/iovisor/bcc/issues/209) issue as me. The error message I receive is as follows
```
29: (18) r2 = 0xffff92f7ce326f00
31: (bf) r1 = r6
32: (18) r3 = 0xffffffff
34: (bf) r4 = r6
35: (b7) r5 = 168
36: (85) call bpf_perf_event_output#25
R4 type=ctx expected=fp
```
> Perhaps a naive question, but wouldn't it be easier to fix vltrace?

To be perfectly honest I am not too good at c and the whole program is written in that language. Which makes it very difficult for me to read and understand the code. My first thoughts were exactly like that as well though.

So is there an easier way to return the whole struct without having to copy it manually into another struct?

**Comment by pchaigno** [comment]
@4ast Is there any reason why `ARG_PTR_TO_MEM` [doesn't allow direct access to context](https://elixir.bootlin.com/linux/v4.18-rc1/source/kernel/bpf/verifier.c#L2010)?

**Comment by yonghong-song** [comment]
ARG_PTR_TO_MEM is defined to pointing to the memory which is valid and the helper can write contents into. For example, for helper `bpf_get_stack_raw_tp`, 
```
BPF_CALL_4(bpf_get_stack_raw_tp, struct bpf_raw_tracepoint_args *, args,
           void *, buf, u32, size, u64, flags)
{
        struct pt_regs *regs = this_cpu_ptr(&bpf_raw_tp_regs);

        perf_fetch_caller_regs(regs);
        return bpf_get_stack((unsigned long) regs, (unsigned long) buf,
                             (unsigned long) size, flags, 0);
}

static const struct bpf_func_proto bpf_get_stack_proto_raw_tp = {
        .func           = bpf_get_stack_raw_tp,
        .gpl_only       = true,
        .ret_type       = RET_INTEGER,
        .arg1_type      = ARG_PTR_TO_CTX,
        .arg2_type      = ARG_PTR_TO_MEM,
        .arg3_type      = ARG_CONST_SIZE_OR_ZERO,
        .arg4_type      = ARG_ANYTHING,
};
```
The context memory has much stricter read/write constraints.

**Comment by pchaigno** [comment]
Thanks for the answer @yonghong-song! I hadn't see that some helpers were writing to their `ARG_PTR_TO_MEM` argument (i.e., `bpf_get_stack_xxx` and in some way `bpf_xxx_fib_lookup_proto`).

Unrelated: any reason why `bpf_get_stack_proto_raw_tp` has `ARG_PTR_TO_MEM` and not `ARG_PTR_TO_UNINIT_MEM`? `bpf_get_stack` has `ARG_PTR_TO_UNINIT_MEM`. It changed between versions 1 and 2 of your patchset.

@fabio-oesch You'll have to copy ctx to the stack. Depending on which fields are relevant to you, you may not need to copy all of `struct pt_regs` of course.

**Comment by fabio-oesch** [comment]
@pchaigno That's exactly what I thought and that's what I did. Thank you for all the help and understanding the way it works. Do you want me to close the issue already or should I wait until your question has been answered?

**Comment by yonghong-song** [comment]
> Unrelated: any reason why bpf_get_stack_proto_raw_tp has ARG_PTR_TO_MEM and not ARG_PTR_TO_UNINIT_MEM? bpf_get_stack has ARG_PTR_TO_UNINIT_MEM. It changed between versions 1 and 2 of your patchset.

I cannot remember the details. One possible reason is that I may try to add two buffers, one for kernel stack and one for user stack, but in kernel, we have the following restrictions,
```
static bool check_raw_mode_ok(const struct bpf_func_proto *fn)
{
        int count = 0;

        if (fn->arg1_type == ARG_PTR_TO_UNINIT_MEM)
                count++;
        if (fn->arg2_type == ARG_PTR_TO_UNINIT_MEM)
                count++;
        if (fn->arg3_type == ARG_PTR_TO_UNINIT_MEM)
                count++;
        if (fn->arg4_type == ARG_PTR_TO_UNINIT_MEM)
                count++;
        if (fn->arg5_type == ARG_PTR_TO_UNINIT_MEM)
                count++;

        /* We only support one arg being in raw mode at the moment,
         * which is sufficient for the helper functions we have
         * right now.
         */
        return count <= 1;
}
```
That is, at most one ARG_PTR_TO_UNINIT_MEM. But later on, I dropped this approach, but
ARG_PTR_TO_MEM remains.

**Comment by pchaigno** [comment]
@yonghong-song I see. Thanks for the explanation!
