### ISSUE TITLE
bpf: nlmsg error Cannot allocate memory

### ISSUE THREAD

**Issue by fzyitt** [iovisor/bcc#1833]
Hi,

I am currently trying to enable XDP inside VM in OpenStack. The NIC of VM is **virtio**. 

After I have set up bcc, when I try to run XDP, it will always show the error below.

**Error**:

```
Attach XDP filter to device: ens2
bpf: nlmsg error Cannot allocate memory
Traceback (most recent call last):
  File "./xdp_udp_forwarding.py", line 41, in <module>
    bpf.attach_xdp(if_dev, fn, 0)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 642, in attach_xdp
    % (dev, errstr))
Exception: Failed to attach BPF to device ens2: Cannot allocate memory
```

The strange thing is that when my VM has only one queue, the **log** shows:

```
kernel: virtio_net virtio0 ens2: request 2 queues but max is  1
```

When my VM has two queues, the log shows: 

```
kernel: virtio_net virtio0 ens2: request 4 queues but max is  2
```

Can someone please tell me why XDP is always asking for double queues than VM has?

Thank you very much in advance!

**Program**:

I have followed the example from the Repo
https://github.com/iovisor/bcc/blob/master/examples/networking/xdp/xdp_drop_count.py

**Comment by nirmoy** [comment]
try with e1000 virtual nic

**Comment by fzyitt** [comment]
Thanks for reply.

I have tried e1000 virtual nic with vagrant. It works well.

But now my environment is OpenStack with DPDK, and the VM can only use virtio-vhostuser interface pair on top of that.

Is there any way I can enable XDP with virtio virtual nic?

**Comment by pchaigno** [comment]
@fzyitt Could you add your program to the original post?

**Comment by fzyitt** [comment]
@pchaigno  I followed example xdp_drop_count.py.

**Comment by pchaigno** [comment]
Ok. Just to be sure, the original `xdp_drop_count.py` doesn't work either, right?
What's the version of your VM's kernel?

**Comment by fzyitt** [comment]
@pchaigno Yes. All original programs in XDP show the same problem.
My VM kernel version is `4.17.0-041700-generic`

**Comment by pchaigno** [comment]
Ok, so the error occurs in [`drivers/net/virtio_net.c`](https://elixir.bootlin.com/linux/v4.17.2/source/drivers/net/virtio_net.c#L2213). According to [the commit that added this check](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=672aafd5d88a951f394334802b938b502010d9eb), the goal is to have a TX queue per core dedicated to XDP. These queues will be allocated when the XDP program is attached to the interface and won't be visible to the network stack.

Could you try to start a VM with 2 pairs of queues and a single core, then reduce the number of queues from inside the VM to a single pair (`sudo ethtool -L ens3 combined 1`), and start the XDP program again?

**Comment by fzyitt** [comment]
Thanks for you reply!

It seems that in OpenStack the maximum number of queues in the VM interface is set to the same value as the number of vCPUs in the guest.

I am not able to launch a VM with 1 vCPU and 2 pair of queues. If I want to have 2 pair of queues, I must launch a VM with 4 vCPUs and then XDP will claim for 4 pairs of queues.

**Comment by pchaigno** [comment]
Then, short of changing OpenStack's source code, you're stuck :-/
It looks like [they considered](https://specs.openstack.org/openstack/nova-specs/specs/liberty/implemented/libvirt-virtiomq.html#alternatives) letting the user configure the number of queues they want, but I don't see it [in the documentation](https://docs.openstack.org/python-novaclient/latest/cli/nova.html#nova-boot), so I'm guessing it wasn't implemented after all.

**Comment by fzyitt** [comment]
Thanks very much for your help!

We will look deep into OpenStack source code to see if it is possible to enable XDP in OpenStack.
