### ISSUE TITLE
`bashreadline` requires statically linked `libreadline`

### ISSUE THREAD

**Issue by juergenhoetzel** [iovisor/bcc#1851]
I suspect most Linux distributions use a dynamic linked `bash/readline`:

```
juergen@samson:~/cxx/bcc → ldd /usr/bin/bash
	linux-vdso.so.1 (0x00007ffdefa81000)
	libreadline.so.7 => /usr/lib/libreadline.so.7 (0x00007f4059494000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f4059290000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f4058ed4000)
	libncursesw.so.6 => /usr/lib/libncursesw.so.6 (0x00007f4058c67000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f40599c2000)
```

Can't resolve symbol:
```
juergen@samson:~ → sudo /usr/share/bcc/tools/bashreadline 
Traceback (most recent call last):
  File "/usr/share/bcc/tools/bashreadline", line 52, in <module>
    b.attach_uretprobe(name="/bin/bash", sym="readline", fn_name="printret")
  File "/usr/lib/python3.6/site-packages/bcc/__init__.py", line 957, in attach_uretprobe
    (path, addr) = BPF._check_path_symbol(name, sym, addr, pid)
  File "/usr/lib/python3.6/site-packages/bcc/__init__.py", line 671, in _check_path_symbol
    raise Exception("could not determine address of symbol %s" % symname)
Exception: could not determine address of symbol b'readline'
```

Should `bashreadline` check for dynamic linking and attach the probe to symbol in `libreadline.so`?

**Comment by yonghong-song** [comment]
Both my ubuntu 17.04 and FC27 does not use libreadline.so.
Which distro did you use which uses libreadline.so?

If this is indeed an issue for some distro's, the tool need to check all share library of the `bash` binary, if `libreadline.so` is linked, the attach_uretprobe `name` should be that shared library instead of `/bin/bash`. Maybe you can work on a patch since you do have environment to reproduce and verify the change?

**Comment by juergenhoetzel** [comment]
> Both my ubuntu 17.04 and FC27 does not use libreadline.so.
> Which distro did you use which uses libreadline.so?

Arch Linux: [Bash](https://www.archlinux.org/packages/core/x86_64/bash/)
 
> If this is indeed an issue for some distro's, the tool need to check all share library of the bash binary, if libreadline.so is linked, the attach_uretprobe name should be that shared library instead of /bin/bash. Maybe you can work on a patch since you do have environment to reproduce and verify the change?

I will check it out.

**Comment by JayceCao** [comment]
Though my `/sbin/bash` on latest Arch Linux uses libreadline.so, the script still can not run.
![image](https://user-images.githubusercontent.com/17915615/52839475-2d9e0500-3131-11e9-91d1-f75cc86dc26e.png)

**Comment by yonghong-song** [comment]
The script tries to find `readline` symbol in '/sbin/bash` file and it failed.
In your case, you can change to
```
b.attach_uretprobe(name="/usr/lib/libreadline.so.8", sym="readline", fn_name="printret")
```
It should fix your issues.
Could you submit a pull request for this issue as it may happen to other users as well?
Basically if the symbol is not available, `ldd` link is searched to get the potential .so library for libreadline and attach uprobe from there?

**Comment by brendangregg** [comment]
Please make it clear in the commit message that this change was because of Arch Linux.

**Comment by juergenhoetzel** [comment]
> The script tries to find `readline` symbol in '/sbin/bash` file and it failed.
> In your case, you can change to
> 
> ```
> b.attach_uretprobe(name="/usr/lib/libreadline.so.8", sym="readline", fn_name="printret")
> ```
> 
> It should fix your issues.
> Could you submit a pull request for this issue as it may happen to other users as well?
> Basically if the symbol is not available, `ldd` link is searched to get the potential .so library for libreadline and attach uprobe from there?

Using this fix  (merged in https://github.com/iovisor/gobpf/pull/173) `bashreadline` will also output `readline` calls from other binaries (For example `gnuplot`):
```
17:48:38  5640   plot(x*x)
```

**Comment by yonghong-song** [comment]
Yes, this is expected if you use shared library as some other binary (other than /bin/bash) may link to libreadline.so.
