### ISSUE TITLE
Ubuntu 18.04 LTS Bionic support

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#1854]
The Ubuntu packages are currently built for Xenial, but not Bionic:

https://repo.iovisor.org/apt/

Can it please appear there for bionic as well? It would make our build systems happy. (I'm not sure anything has to change with bcc between xenial and bionic.)

**Comment by yonghong-song** [comment]
cc @drzaeus77

**Comment by Birch-san** [comment]
> I'm not sure anything has to change with bcc between xenial and bionic

The 17.10 Artful distribution is working okay for me on 18.04 LTS Bionic. That is to say, I am running the http_filter example with no issues.

**Comment by brendangregg** [comment]
Is there an idea of when the bionic dist will appear, in addition to the bionic-nightly? We're setting up our build servers for our BaseAMI (bcc will be a default install on 150k+ cloud instances at Netflix).

**Comment by yonghong-song** [comment]
cc @drzaeus77

**Comment by drzaeus77** [comment]
This should be done now. Packages are there in https://repo.iovisor.org/apt/bionic for both bionic (signed, v0.6.1) and bionic-nightly.
