### ISSUE TITLE
Linux kernel 4.11, get_table_offline gives a segmentation fault for percpu maps

### ISSUE THREAD

**Issue by mohankku** [iovisor/bcc#1860]
I have a pinned map of type BPF_MAP_TYPE_LRU_PERCPU_HASH,  which gives std::bad_alloc when I invoke get_table_offline for that map.  

Is someone looking at this issue, or some one faced the same problem ?

**Comment by palmtenor** [comment]
Do you have a stack trace? Can you show your code for repro?

**Comment by mohankku** [comment]
I analyzed the issue, and it seems that BPFPercpuHashTable passes vector of ValueType to BPFHashTable. BPFHashTable passes this vector pointer to bpf_lookup_elem, which considers this as a pointer to the value structure. And, when I looked at the vector, it seems to be corrupt after bpf_lookup_elem. I used a structure array of ncpus, instead of a vector. And, that seems to solve the problem.

**Comment by mauriciovasquezbernal** [comment]
@mohankku could you please try this?

```
diff --git a/src/cc/api/BPFTable.h b/src/cc/api/BPFTable.h
index 3c83b25..e1fbeb6 100644
--- a/src/cc/api/BPFTable.h
+++ b/src/cc/api/BPFTable.h
@@ -236,7 +236,7 @@ class BPFHashTable : public BPFTableBase<KeyType, ValueType> {
       return res;
 
     while (true) {
-      if (!this->lookup(&cur, &value))
+      if (!this->lookup(&cur, get_value_addr(value)))
         break;
       res.emplace_back(cur, value);
       if (!this->next(&cur, &cur))
```

If this works I'll open a PR with the fix and some tests case for it.

**Comment by mohankku** [comment]
Mauricio, the above fix solved the issue. I can send a PR with the fix tomorrow.
