### ISSUE TITLE
/tools/tcplife.py can not run in the 4.17

### ISSUE THREAD

**Issue by kernel-z** [iovisor/bcc#1861]
tcplife.py can not work in the 4.17, but it works in the 4.13.  
 4.17 will use tracepoint, and 4.13 still use kprobe.
I don't know why it errors.
Can you help me , @yonghong-song, @pchaigno

4.17-kernel #./tcplife.py

> bpf: Failed to load program: Permission denied
0: (bf) r6 = r1
1: (71) r1 = *(u8 *)(r6 +30)
2: (55) if r1 != 0x6 goto pc+208
 R1=inv6 R6=ctx(id=0,off=0,imm=0) R10=fp0,call_-1
3: (85) call bpf_get_current_pid_tgid#14
4: (bf) r7 = r0
5: (79) r1 = *(u64 *)(r6 +8)
6: (7b) *(u64 *)(r10 -8) = r1
7: (61) r9 = *(u32 *)(r6 +24)
8: (61) r1 = *(u32 *)(r6 +20)
9: (67) r1 <<= 32
10: (c7) r1 s>>= 32
11: (65) if r1 s> 0x3 goto pc+11
 R0=inv(id=0) R1=inv(id=0,smax_value=3) R6=ctx(id=0,off=0,imm=0) R7=inv(id=0) R9=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R10=fp0,call_-1
12: (85) call bpf_ktime_get_ns#5
13: (7b) *(u64 *)(r10 -112) = r0
14: (18) r1 = 0xffff8bbd725e5200
16: (bf) r2 = r10
17: (07) r2 += -8
18: (bf) r3 = r10
19: (07) r3 += -112
20: (b7) r4 = 0
21: (85) call bpf_map_update_elem#2
22: (61) r1 = *(u32 *)(r6 +20)
23: (77) r7 >>= 32
24: (bf) r2 = r1
25: (67) r2 <<= 32
26: (77) r2 >>= 32
27: (15) if r2 == 0x9 goto pc+1
 R0=inv(id=0) R1=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R2=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R6=ctx(id=0,off=0,imm=0) R7=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R9=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R10=fp0,call_-1
28: (55) if r2 != 0x2 goto pc+19
 R0=inv(id=0) R1=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R2=inv2 R6=ctx(id=0,off=0,imm=0) R7=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R9=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R10=fp0,call_-1
29: (bf) r1 = r10
30: (07) r1 += -108
31: (b7) r2 = 0
32: (63) *(u32 *)(r1 +4) = r2
33: (63) *(u32 *)(r10 -96) = r2
34: (63) *(u32 *)(r10 -100) = r2
35: (63) *(u32 *)(r10 -108) = r2
36: (63) *(u32 *)(r10 -112) = r7
37: (b7) r2 = 16
38: (85) call bpf_get_current_comm#16
39: (18) r1 = 0xffff8bbd725e5400
41: (bf) r2 = r10
42: (07) r2 += -8
43: (bf) r3 = r10
44: (07) r3 += -112
45: (b7) r4 = 0
46: (85) call bpf_map_update_elem#2
47: (61) r1 = *(u32 *)(r6 +20)
48: (67) r1 <<= 32
49: (77) r1 >>= 32
50: (55) if r1 != 0x7 goto pc+160
 R0=inv(id=0) R1=inv7 R6=ctx(id=0,off=0,imm=0) R7=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R9=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R10=fp0,call_-1
51: (18) r1 = 0xffff8bbd725e5200
53: (bf) r2 = r10
54: (07) r2 += -8
55: (85) call bpf_map_lookup_elem#1
56: (bf) r8 = r0
57: (55) if r8 != 0x0 goto pc+1
 R0=inv0 R6=ctx(id=0,off=0,imm=0) R7=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R8=inv0 R9=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R10=fp0,call_-1
58: (05) goto pc+147
206: (18) r1 = 0xffff8bbd725e5400
208: (bf) r2 = r10
209: (07) r2 += -8
210: (85) call bpf_map_delete_elem#3
211: (b7) r0 = 0
212: (95) exit

from 57 to 59: R0=map_value(id=0,off=0,ks=8,vs=8,imm=0) R6=ctx(id=0,off=0,imm=0) R7=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R8=map_value(id=0,off=0,ks=8,vs=8,imm=0) R9=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R10=fp0,call_-1
59: (7b) *(u64 *)(r10 -120) = r9
60: (85) call bpf_ktime_get_ns#5
61: (bf) r9 = r0
62: (79) r1 = *(u64 *)(r8 +0)
 R0=inv(id=0) R6=ctx(id=0,off=0,imm=0) R7=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R8=map_value(id=0,off=0,ks=8,vs=8,imm=0) R9_w=inv(id=0) R10=fp0,call_-1
63: (7b) *(u64 *)(r10 -128) = r1
64: (18) r1 = 0xffff8bbd725e5200
66: (bf) r8 = r10
67: (07) r8 += -8
68: (bf) r2 = r8
69: (85) call bpf_map_delete_elem#3
70: (79) r1 = *(u64 *)(r10 -128)
71: (1f) r9 -= r1
72: (18) r1 = 0xffff8bbd725e5400
74: (bf) r2 = r8
75: (85) call bpf_map_lookup_elem#1
76: (15) if r0 == 0x0 goto pc+1
 R0=map_value(id=0,off=0,ks=8,vs=20,imm=0) R6=ctx(id=0,off=0,imm=0) R7=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R8=fp-8,call_-1 R9=inv(id=0) R10=fp0,call_-1
77: (61) r7 = *(u32 *)(r0 +0)
 R0=map_value(id=0,off=0,ks=8,vs=20,imm=0) R6=ctx(id=0,off=0,imm=0) R7_w=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R8=fp-8,call_-1 R9=inv(id=0) R10=fp0,call_-1
78: (7b) *(u64 *)(r10 -128) = r0
79: (79) r8 = *(u64 *)(r10 -120)
80: (bf) r1 = r8
81: (77) r1 >>= 16
82: (7b) *(u64 *)(r10 -136) = r1
83: (37) r9 /= 1000
84: (79) r2 = *(u64 *)(r10 -8)
85: (79) r1 = *(u64 *)(r2 +1344)
R2 invalid mem access 'inv'

HINT: The invalid mem access 'inv' error can happen if you try to dereference memory without first using bpf_probe_read() to copy it to the BPF stack. Sometimes the bpf_probe_read is automatic by the bcc rewriter, other times you'll need to be explicit.

Traceback (most recent call last):
  File "./tcplife.py", line 479, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 328, in __init__
    self._trace_autoload()
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 1013, in _trace_autoload
    fn = self.load_func(func_name, BPF.TRACEPOINT)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 368, in load_func
    (func_name, errstr))
Exception: Failed to load BPF program tracepoint__sock__inet_sock_set_state: Permission denied

**Comment by pchaigno** [comment]
The last version, from 44c28bf, works for me and does use tracepoints.
Did you change anything in the script? Could you add a `debug=4` argument to the `BPF` call and post the output here?

**Comment by kernel-z** [comment]
The https://github.com/iovisor/bcc/commit/44c28bf979f068cd7ace66a28e97becf1862ef5d  is tcpconnlat.py, the issue is about tcplife.py.
I add debug=4 in the script like this, "b = BPF(text=bpf_text,debug=4)",is right?

> # ./tcplife.py 
Running from kernel directory at: /lib/modules/4.17.2/source
clang -cc1 -triple x86_64-unknown-linux-gnu -emit-llvm-bc -emit-llvm-uselists -disable-free -disable-llvm-verifier -discard-value-names -main-file-name main.c -mrelocation-model static -mthread-model posix -fmath-errno -masm-verbose -mconstructor-aliases -fuse-init-array -target-cpu x86-64 -momit-leaf-frame-pointer -dwarf-column-info -debugger-tuning=gdb -coverage-file /kernel/linux-4.17.2/main.c -nostdsysteminc -nobuiltininc -resource-dir ../lib64/clang/3.9.0 -isystem /virtual/lib/clang/include -include ./include/linux/kconfig.h -include /virtual/include/bcc/bpf.h -include /virtual/include/bcc/helpers.h -isystem /virtual/include -I /root/bcc/tools -I /lib/modules/4.17.2/build/arch/x86/include -I /lib/modules/4.17.2/build/arch/x86/include/generated/uapi -I /lib/modules/4.17.2/build/arch/x86/include/generated -I /lib/modules/4.17.2/build/include -I /lib/modules/4.17.2/build/./arch/x86/include/uapi -I /lib/modules/4.17.2/build/arch/x86/include/generated/uapi -I /lib/modules/4.17.2/build/include/uapi -I /lib/modules/4.17.2/build/include/generated -I /lib/modules/4.17.2/build/include/generated/uapi -I ./arch/x86/include -I arch/x86/include/generated/uapi -I arch/x86/include/generated -I include -I ./arch/x86/include/uapi -I arch/x86/include/generated/uapi -I ./include/uapi -I include/generated/uapi -D __KERNEL__ -D __HAVE_BUILTIN_BSWAP16__ -D __HAVE_BUILTIN_BSWAP32__ -D __HAVE_BUILTIN_BSWAP64__ -O2 -Wno-deprecated-declarations -Wno-gnu-variable-sized-type-not-at-end -Wno-pragma-once-outside-header -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-unused-value -Wno-pointer-sign -fdebug-compilation-dir /kernel/linux-4.17.2 -ferror-limit 19 -fmessage-length 138 -fobjc-runtime=gcc -fdiagnostics-show-option -vectorize-loops -vectorize-slp -o main.bc -x c /virtual/main.c

#include <uapi/linux/ptrace.h>
#define KBUILD_MODNAME "foo"
#include <linux/tcp.h>
#include <net/sock.h>
#include <bcc/proto.h>

BPF_HASH(birth, struct sock *, u64);

// separate data structs for ipv4 and ipv6
struct ipv4_data_t {
    // XXX: switch some to u32's when supported
    u64 ts_us;
    u64 pid;
    u64 saddr;
    u64 daddr;
    u64 ports;
    u64 rx_b;
    u64 tx_b;
    u64 span_us;
    char task[TASK_COMM_LEN];
};
BPF_PERF_OUTPUT(ipv4_events);

struct ipv6_data_t {
    u64 ts_us;
    u64 pid;
    unsigned __int128 saddr;
    unsigned __int128 daddr;
    u64 ports;
    u64 rx_b;
    u64 tx_b;
    u64 span_us;
    char task[TASK_COMM_LEN];
};
BPF_PERF_OUTPUT(ipv6_events);

struct id_t {
    u32 pid;
    char task[TASK_COMM_LEN];
};
BPF_HASH(whoami, struct sock *, struct id_t);

struct tracepoint__sock__inet_sock_set_state {
	u64 __do_not_use__;
	const void * skaddr;
	int oldstate;
	int newstate;
	__u16 sport;
	__u16 dport;
	__u16 family;
	__u8 protocol;
	__u8 saddr[4];
	__u8 daddr[4];
	__u8 saddr_v6[16];
	__u8 daddr_v6[16];
};
__attribute__((section(".bpf.fn.tracepoint__sock__inet_sock_set_state")))
TRACEPOINT_PROBE(sock, inet_sock_set_state)
{
    if (args->protocol != IPPROTO_TCP)
        return 0;

    u32 pid = bpf_get_current_pid_tgid() >> 32;
    // sk is mostly used as a UUID, and for two tcp stats:
    struct sock *sk = (struct sock *)args->skaddr;

    // lport is either used in a filter here, or later
    u16 lport = args->sport;
    

    // dport is either used in a filter here, or later
    u16 dport = args->dport;
    

    /*
     * This tool includes PID and comm context. It's best effort, and may
     * be wrong in some situations. It currently works like this:
     * - record timestamp on any state < TCP_FIN_WAIT1
     * - cache task context on:
     *       TCP_SYN_SENT: tracing from client
     *       TCP_LAST_ACK: client-closed from server
     * - do output on TCP_CLOSE:
     *       fetch task context if cached, or use current task
     */

    // capture birth time
    if (args->newstate < TCP_FIN_WAIT1) {
        /*
         * Matching just ESTABLISHED may be sufficient, provided no code-path
         * sets ESTABLISHED without a tcp_set_state() call. Until we know
         * that for sure, match all early states to increase chances a
         * timestamp is set.
         * Note that this needs to be set before the PID filter later on,
         * since the PID isn't reliable for these early stages, so we must
         * save all timestamps and do the PID filter later when we can.
         */
        u64 ts = bpf_ktime_get_ns();
        bpf_map_update_elem((void *)bpf_pseudo_fd(1, 3), &sk, &ts, BPF_ANY);
    }

    // record PID & comm on SYN_SENT
    if (args->newstate == TCP_SYN_SENT || args->newstate == TCP_LAST_ACK) {
        // now we can PID filter, both here and a little later on for CLOSE
        
        struct id_t me = {.pid = pid};
        bpf_get_current_comm(&me.task, sizeof(me.task));
        bpf_map_update_elem((void *)bpf_pseudo_fd(1, 6), &sk, &me, BPF_ANY);
    }

    if (args->newstate != TCP_CLOSE)
        return 0;

    // calculate lifespan
    u64 *tsp, delta_us;
    tsp = bpf_map_lookup_elem((void *)bpf_pseudo_fd(1, 3), &sk);
    if (tsp == 0) {
        bpf_map_delete_elem((void *)bpf_pseudo_fd(1, 6), &sk);     // may not exist
        return 0;               // missed create
    }
    delta_us = (bpf_ktime_get_ns() - *tsp) / 1000;
    bpf_map_delete_elem((void *)bpf_pseudo_fd(1, 3), &sk);

    // fetch possible cached data, and filter
    struct id_t *mep;
    mep = bpf_map_lookup_elem((void *)bpf_pseudo_fd(1, 6), &sk);
    if (mep != 0)
        pid = mep->pid;
    

    // get throughput stats. see tcp_get_info().
    u64 rx_b = 0, tx_b = 0, sport = 0;
    struct tcp_sock *tp = (struct tcp_sock *)sk;
    rx_b = tp->bytes_received;
    tx_b = tp->bytes_acked;

    if (args->family == AF_INET) {
        struct ipv4_data_t data4 = {.span_us = delta_us,
            .rx_b = rx_b, .tx_b = tx_b};
        data4.ts_us = bpf_ktime_get_ns() / 1000;
        bpf_probe_read(&data4.saddr, sizeof(u32), args->saddr);
        bpf_probe_read(&data4.daddr, sizeof(u32), args->daddr);
        // a workaround until data4 compiles with separate lport/dport
        data4.ports = dport + ((0ULL + lport) << 32);
        data4.pid = pid;

        if (mep == 0) {
            bpf_get_current_comm(&data4.task, sizeof(data4.task));
        } else {
            bpf_probe_read(&data4.task, sizeof(data4.task), (void *)mep->task);
        }
        bpf_perf_event_output(args, bpf_pseudo_fd(1, 4), CUR_CPU_IDENTIFIER, &data4, sizeof(data4));

    } else /* 6 */ {
        struct ipv6_data_t data6 = {.span_us = delta_us,
            .rx_b = rx_b, .tx_b = tx_b};
        data6.ts_us = bpf_ktime_get_ns() / 1000;
        bpf_probe_read(&data6.saddr, sizeof(data6.saddr), args->saddr_v6);
        bpf_probe_read(&data6.daddr, sizeof(data6.daddr), args->saddr_v6);
        // a workaround until data6 compiles with separate lport/dport
        data6.ports = dport + ((0ULL + lport) << 32);
        data6.pid = pid;
        if (mep == 0) {
            bpf_get_current_comm(&data6.task, sizeof(data6.task));
        } else {
            bpf_probe_read(&data6.task, sizeof(data6.task), (void *)mep->task);
        }
        bpf_perf_event_output(args, bpf_pseudo_fd(1, 5), CUR_CPU_IDENTIFIER, &data6, sizeof(data6));
    }

    if (mep != 0)
        bpf_map_delete_elem((void *)bpf_pseudo_fd(1, 6), &sk);

    return 0;
}
1 warning generated.
bpf: Failed to load program: Permission denied
0: (bf) r6 = r1
1: (71) r1 = *(u8 *)(r6 +30)
2: (55) if r1 != 0x6 goto pc+208
 R1=inv6 R6=ctx(id=0,off=0,imm=0) R10=fp0,call_-1
3: (85) call bpf_get_current_pid_tgid#14
4: (bf) r7 = r0
5: (79) r1 = *(u64 *)(r6 +8)
6: (7b) *(u64 *)(r10 -8) = r1
7: (61) r9 = *(u32 *)(r6 +24)
8: (61) r1 = *(u32 *)(r6 +20)
9: (67) r1 <<= 32
10: (c7) r1 s>>= 32
11: (65) if r1 s> 0x3 goto pc+11
 R0=inv(id=0) R1=inv(id=0,smax_value=3) R6=ctx(id=0,off=0,imm=0) R7=inv(id=0) R9=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R10=fp0,call_-1
12: (85) call bpf_ktime_get_ns#5
13: (7b) *(u64 *)(r10 -112) = r0
14: (18) r1 = 0xffff8bbd7cab9600
16: (bf) r2 = r10
17: (07) r2 += -8
18: (bf) r3 = r10
19: (07) r3 += -112
20: (b7) r4 = 0
21: (85) call bpf_map_update_elem#2
22: (61) r1 = *(u32 *)(r6 +20)
23: (77) r7 >>= 32
24: (bf) r2 = r1
25: (67) r2 <<= 32
26: (77) r2 >>= 32
27: (15) if r2 == 0x9 goto pc+1
 R0=inv(id=0) R1=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R2=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R6=ctx(id=0,off=0,imm=0) R7=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R9=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R10=fp0,call_-1
28: (55) if r2 != 0x2 goto pc+19
 R0=inv(id=0) R1=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R2=inv2 R6=ctx(id=0,off=0,imm=0) R7=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R9=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R10=fp0,call_-1
29: (bf) r1 = r10
30: (07) r1 += -108
31: (b7) r2 = 0
32: (63) *(u32 *)(r1 +4) = r2
33: (63) *(u32 *)(r10 -96) = r2
34: (63) *(u32 *)(r10 -100) = r2
35: (63) *(u32 *)(r10 -108) = r2
36: (63) *(u32 *)(r10 -112) = r7
37: (b7) r2 = 16
38: (85) call bpf_get_current_comm#16
39: (18) r1 = 0xffff8bbd7cab9e00
41: (bf) r2 = r10
42: (07) r2 += -8
43: (bf) r3 = r10
44: (07) r3 += -112
45: (b7) r4 = 0
46: (85) call bpf_map_update_elem#2
47: (61) r1 = *(u32 *)(r6 +20)
48: (67) r1 <<= 32
49: (77) r1 >>= 32
50: (55) if r1 != 0x7 goto pc+160
 R0=inv(id=0) R1=inv7 R6=ctx(id=0,off=0,imm=0) R7=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R9=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R10=fp0,call_-1
51: (18) r1 = 0xffff8bbd7cab9600
53: (bf) r2 = r10
54: (07) r2 += -8
55: (85) call bpf_map_lookup_elem#1
56: (bf) r8 = r0
57: (55) if r8 != 0x0 goto pc+1
 R0=inv0 R6=ctx(id=0,off=0,imm=0) R7=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R8=inv0 R9=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R10=fp0,call_-1
58: (05) goto pc+147
206: (18) r1 = 0xffff8bbd7cab9e00
208: (bf) r2 = r10
209: (07) r2 += -8
210: (85) call bpf_map_delete_elem#3
211: (b7) r0 = 0
212: (95) exit

from 57 to 59: R0=map_value(id=0,off=0,ks=8,vs=8,imm=0) R6=ctx(id=0,off=0,imm=0) R7=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R8=map_value(id=0,off=0,ks=8,vs=8,imm=0) R9=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R10=fp0,call_-1
59: (7b) *(u64 *)(r10 -120) = r9
60: (85) call bpf_ktime_get_ns#5
61: (bf) r9 = r0
62: (79) r1 = *(u64 *)(r8 +0)
 R0=inv(id=0) R6=ctx(id=0,off=0,imm=0) R7=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R8=map_value(id=0,off=0,ks=8,vs=8,imm=0) R9_w=inv(id=0) R10=fp0,call_-1
63: (7b) *(u64 *)(r10 -128) = r1
64: (18) r1 = 0xffff8bbd7cab9600
66: (bf) r8 = r10
67: (07) r8 += -8
68: (bf) r2 = r8
69: (85) call bpf_map_delete_elem#3
70: (79) r1 = *(u64 *)(r10 -128)
71: (1f) r9 -= r1
72: (18) r1 = 0xffff8bbd7cab9e00
74: (bf) r2 = r8
75: (85) call bpf_map_lookup_elem#1
76: (15) if r0 == 0x0 goto pc+1
 R0=map_value(id=0,off=0,ks=8,vs=20,imm=0) R6=ctx(id=0,off=0,imm=0) R7=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R8=fp-8,call_-1 R9=inv(id=0) R10=fp0,call_-1
77: (61) r7 = *(u32 *)(r0 +0)
 R0=map_value(id=0,off=0,ks=8,vs=20,imm=0) R6=ctx(id=0,off=0,imm=0) R7_w=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R8=fp-8,call_-1 R9=inv(id=0) R10=fp0,call_-1
78: (7b) *(u64 *)(r10 -128) = r0
79: (79) r8 = *(u64 *)(r10 -120)
80: (bf) r1 = r8
81: (77) r1 >>= 16
82: (7b) *(u64 *)(r10 -136) = r1
83: (37) r9 /= 1000
84: (79) r2 = *(u64 *)(r10 -8)
85: (79) r1 = *(u64 *)(r2 +1344)
R2 invalid mem access 'inv'

HINT: The invalid mem access 'inv' error can happen if you try to dereference memory without first using bpf_probe_read() to copy it to the BPF stack. Sometimes the bpf_probe_read is automatic by the bcc rewriter, other times you'll need to be explicit.

Traceback (most recent call last):
  File "./tcplife.py", line 479, in <module>
    b = BPF(text=bpf_text,debug=4)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 328, in __init__
    self._trace_autoload()
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 1013, in _trace_autoload
    fn = self.load_func(func_name, BPF.TRACEPOINT)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 368, in load_func
    (func_name, errstr))
Exception: Failed to load BPF program tracepoint__sock__inet_sock_set_state: Permission denied

**Comment by pchaigno** [comment]
> The 44c28bf is tcpconnlat.py, the issue is about tcplife.py.

I meant I tested tcplife.py as it is as of 44c28bf (the last bcc commit).

It looks like it fails to rewrite the two following statements:
```c
rx_b = tp->bytes_received;
tx_b = tp->bytes_acked;
```
What version of bcc is installed on your system?

**Comment by kernel-z** [comment]
bcc: version 0.16.3
LLVM version 3.9.0

**Comment by pchaigno** [comment]
[I don't think there's a bcc v0.16.3](https://github.com/iovisor/bcc/releases). Did you mean v0.1.3?

**Comment by kernel-z** [comment]
I use bcc -version . 
# bcc -version
bcc: version 0.16.3

**Comment by kernel-z** [comment]
I forget when I git clone from the github and build the bcc.
I have download the v0.6.0 just now, and build it again.
After that, the tcplife.py is working.
Thanks @pchaigno 
I will close the issue.
But, what's the results of the command "bcc -v "  meanings?

**Comment by pchaigno** [comment]
Isn't that the bcc command from the bcc package? The bcc package has nothing to do with the present bcc repository. The BPF bcc doesn't have a bcc command anyway. (That's a lot of `bcc`s!)

To find bcc's version, if you installed it from sources, you can run:
```
pip list | grep bcc
```
