### ISSUE TITLE
Do not know what the arguments are of functions 

### ISSUE THREAD

**Issue by fabio-oesch** [iovisor/bcc#1864]
I am trying to modify the [opensnoop](https://github.com/iovisor/bcc/blob/master/tools/opensnoop.py) file to also return the mode and the flags. I thought this should be possible because when looking at the format of the open syscall it should have these as arguments. But when I add those the commands and path are getting cut off.
As an example this is what it looks like now:
`12951  bProces            31   0    1700230249    1264739671 lf/smaps`

Furthermore, the arguments in the file are dfd (which I assume is the directory file descriptor) and the filename. The open syscall does not actually include dfd. So is there a way to find out exactly what the different arguments of a specific call are.

Sorry if this might be a stupid question but I could not find any information to it.

**Comment by fabio-oesch** [comment]
```
@@ -64,6 +64,8 @@
     u64 ts;
     char comm[TASK_COMM_LEN];
     const char *fname;
+    int mode;
+    int flags;
 };
 
 struct data_t {
@@ -72,12 +74,14 @@
     int ret;
     char comm[TASK_COMM_LEN];
     char fname[NAME_MAX];
+    int mode;
+    int flags;
 };
 
 BPF_HASH(infotmp, u64, struct val_t);
 BPF_PERF_OUTPUT(events);
 
-int trace_entry(struct pt_regs *ctx, int dfd, const char __user *filename)
+int trace_entry(struct pt_regs *ctx, int dfd, const char __user *filename, int flags, int mode)
 {
     struct val_t val = {};
     u64 id = bpf_get_current_pid_tgid();
@@ -89,6 +93,8 @@
         val.id = id;
         val.ts = bpf_ktime_get_ns();
         val.fname = filename;
+        val.mode = mode;
+        val.flags = flags;
         infotmp.update(&id, &val);
     }
 
@@ -110,6 +116,8 @@
     }
     bpf_probe_read(&data.comm, sizeof(data.comm), valp->comm);
     bpf_probe_read(&data.fname, sizeof(data.fname), (void *)valp->fname);
+    data.mode = valp->mode;
+    data.flags = valp->flags;
     data.id = valp->id;
     data.ts = tsp / 1000;
     data.ret = PT_REGS_RC(ctx);
@@ -146,6 +154,8 @@
         ("id", ct.c_ulonglong),
         ("ts", ct.c_ulonglong),
         ("ret", ct.c_int),
+        ("mode", ct.c_int),
+        ("flags", ct.c_int),
         ("comm", ct.c_char * TASK_COMM_LEN),
         ("fname", ct.c_char * NAME_MAX)
     ]
@@ -155,8 +165,8 @@
 # header
 if args.timestamp:
     print("%-14s" % ("TIME(s)"), end="")
-print("%-6s %-16s %4s %3s %s" %
-      ("TID" if args.tid else "PID", "COMM", "FD", "ERR", "PATH"))
+print("%-6s %-16s %4s %3s %13s %13s %s" %
+      ("TID" if args.tid else "PID", "COMM", "FD", "ERR", "FLAGS", "MODE", "PATH"))
 
 # process event
 def print_event(cpu, data, size):
@@ -184,9 +194,9 @@
         delta = event.ts - initial_ts
         print("%-14.9f" % (float(delta) / 1000000), end="")
 
-    print("%-6d %-16s %4d %3d %s" %
+    print("%-6d %-16s %4d %3d %13d %13d %s" %
           (event.id & 0xffffffff if args.tid else event.id >> 32,
-           event.comm.decode(), fd_s, err, event.fname.decode()))
+           event.comm.decode(), fd_s, err, event.flags, event.mode, event.fname.decode()))
 
 # loop with callback to print_event
 b["events"].open_perf_buffer(print_event, page_cnt=64)
```

**Comment by pchaigno** [comment]
`struct data_t` on the C side and `class Data` on the Python side need to define their fields in the same order for ctypes to correctly parse the binary data. On the C side, `mode` and `flags` should be before `comm` for example.

**Comment by fabio-oesch** [comment]
Thank you very much. I didn't know that was the case. I expected it to be a little mistake I did not know about. 

But I'm still unsure what arguments I have to use. I expected the list of identifiers I can use would be the same ones as the ones from the output `# /usr/share/bcc/tools/tplist -v 'syscalls:sys_enter_open`. But this list includes the `__syscall_nr` but not `dfd`. So is there a reference where I can find which syscall has which arguments?

**Comment by pchaigno** [comment]
opensnoop does not attach to the syscall but to the kernel function [`do_sys_open`](https://elixir.bootlin.com/linux/v4.17.3/source/fs/open.c#L1086).

**Comment by fabio-oesch** [comment]
Thank you very much for the clarification. I did not realise that at all.
