### ISSUE TITLE
tcptop: possibly wrong display of received bytes

### ISSUE THREAD

**Issue by andreasgerstmayr** [iovisor/bcc#1871]
Looking at tcptop, in line
https://github.com/iovisor/bcc/blob/4ac63076a2ceb8b348894f6e025366bfef43768f/tools/tcptop.py#L227
`keys` now points to the `ipv4_recv_bytes` table, and all keys from `ipv4_send_bytes` which are not yet in `ipv4_recv_bytes` will be copied (referenced).

For the case that there is a key in `ipv4_send_bytes` but not in `ipv4_recv_bytes`, this line will always evaluate to true anyway:
https://github.com/iovisor/bcc/blob/4ac63076a2ceb8b348894f6e025366bfef43768f/tools/tcptop.py#L242
because this table contains *all* the keys now (because `keys` is a reference to `ipv4_recv_bytes` and not a copy of this table)

So in this case it will display an equal amount of received and sent bytes, but in reality received bytes should be zero.
Did I miss some magic here, or is this a bug?

My probably not so elegant solution would be to create new dicts of the tables where the key is a tuple of pid, laddr, lport, daddr, dport, and use a new dict for merging the keys of the two tables.

**Comment by palmtenor** [comment]
Good catch. In reality, I think it's pretty rare for something to only do TCP send but not receive, which means both `_send_bytes` and `_recv_bytes` tables would contain the same set of keys and thus we didn't see the bug when using the tool.

Also note that the `_send_bytes` and `_recv_bytes` tables are not normal Python `dict` instances. They are BCC's `HashTable` instances (see [`table.py`](https://github.com/iovisor/bcc/blob/master/src/python/bcc/table.py)) which means all the `in` operator and `items()` calls require doing actual (a lot of) BPF syscalls. It would be good if we can go over both tables just once and merge the keys and values purely in user space.

Would you submit a patch for these fixes / improvements?
