### ISSUE TITLE
Open a socket in bpf

### ISSUE THREAD

**Issue by fabio-oesch** [iovisor/bcc#1889]
I want to run a bpf program on my local machine and send the information to a server. I can easily do this by returning the output of bpf to user mode and send it from there. Is it possible to send raw udp packets straight out of bpf since it just creates unnecessary overhead to send it first back to the user mode.

I would understand if this is not possible since, as far as I understand, bpf runs in some kind of sandbox. This is a small test program I tried to run.

```
from bcc import BPF
import ctypes as ct

# define BPF program
prog = """
#include <linux/in.h>
#include <linux/net.h>
#include <linux/netpoll.h>

#define MESSAGE_SIZE 1024
#define INADDR_LOCAL ((unsigned int)0x7F000001) //127.0.0.1
#define INADDR_SEND ((unsigned int)0x7F000001)
static struct netpoll* np = NULL;
static struct netpoll np_t;
static int flag = 0;

TRACEPOINT_PROBE(syscalls, sys_enter_read) {
    u32 pid = bpf_get_current_pid_tgid();
    u8 socket = 0;
    if (!flag) {
        flag++;
        np_t.name = "LRNG";
        strlcpy(np_t.dev_name, "eth0", IFNAMSIZ);
        np_t.local_ip.ip = htonl(INADDR_LOCAL);
        np_t.remote_ip.ip = htonl(INADDR_SEND);
        np_t.local_port = 6665;
        np_t.remote_port = 6666;
        memset(np_t.remote_mac, 0xff, ETH_ALEN);
        netpoll_print_options(&np_t);
        netpoll_setup(&np_t);
        np = &np_t;
    }

    char message[MESSAGE_SIZE];
    sprintf(message, "%s", "Hello World");
    int len = strlen(message);
    netpoll_send_udp(np,message,len);

    return 0;
}"""

# load BPF program
b = BPF(text=prog)
```

This was my test to send udp packets via netpoll but this is my error
`error: <unknown>:0:0: in function tracepoint__syscalls__sys_enter_read i32 (%struct.tracepoint__syscalls__sys_enter_read*): Looks like the BPF stack limit of 512 bytes is exceeded. Please move large on stack variables into BPF per-cpu array map.`
So I'm guessing I have to use the BPF_CPUMAP but I'm not certain how to actually use them. 

Any help is appreciated.

**Comment by yonghong-song** [comment]
Besides stack limit error, you cannot directly call kernel functions `netpoll_print_options`, `netpoll_setup` and `netpoll_send_udp`. Only helper functions can be called w.r.t. external functions. BPF_CPUMAP is only available for XDP programs so you cannot use it in the above tracepoint program.

Based on current infrastructure, you may have to use send to user space first and then send to the server from the your user space application.

**Comment by fabio-oesch** [comment]
I did expect that this will not be possible and thank you for confirming this for me. 

> Based on current infrastructure, you may have to use send to user space first and then send to the server from the your user space application.

That's what I was doing so far. But I just wanted to see if there's a 'cleaner' version where I don't have to go back to user space.
