### ISSUE TITLE
Trying to read buffer from read syscall

### ISSUE THREAD

**Issue by fabio-oesch** [iovisor/bcc#1906]
I would like to get the information from the read syscall but I seem to have some difficulties. My code is as follows:

```
#!/usr/bin/env python

from bcc import BPF
import ctypes as ct
import os

bpf_text = """
    struct read_syscall_t {
        u32 fd;
        u32 count;
        char *buf;
        int pid;
    };

    BPF_PERF_OUTPUT(read_syscall_event);

    TRACEPOINT_PROBE(syscalls, sys_enter_read) 
    {
        struct read_syscall_t read = {};
        read.pid = bpf_get_current_pid_tgid();
        if (read.pid == CURRENT_PID) return false; // remove recursive calls
        read.fd = args->fd;
        read.count = args->count;
        bpf_probe_read_str(&read.buf, sizeof(args->buf), args->buf);
        read_syscall_event.perf_submit(args, &read, sizeof(read));

        return 0;
    }
"""


bpf = BPF(text=bpf_text.replace("CURRENT_PID", str(os.getpid())))


class ReadSyscall(ct.Structure):
    _fields_ = [
        ("fd", ct.c_uint32),
        ("count", ct.c_uint32),
        ("buf", ct.POINTER(ct.c_char)),
        ("pid", ct.c_uint32)
    ]


def print_event(cpu, data, size):
    event = ct.cast(data, ct.POINTER(ReadSyscall)).contents
    print("%-6d %-6d %-6d %s" % (event.pid, event.fd, event.count, event.buf))


bpf["read_syscall_event"].open_perf_buffer(print_event)

while True:
    bpf.perf_buffer_poll()
```

But all that is returned are `8 32768 <ctypes.LP_c_char object at 0x...>`. So I tried to get the contents out of it. This will only give me a segfault though (might this be because it is empty?). I have also tried c_char_p which which also did not work. 

The only way I could find that it works is when I use in the ReadSyscall class `("buf", ct.c_char * 8)` but this will only give me strings of maximum length 8 which would defeat the purpose.

Any help is appreciated

**Comment by palmtenor** [comment]
In the BPF program, you did
```
bpf_probe_read_str(&read.buf, sizeof(args->buf), args->buf);
```
Note `args->buf` is just a pointer hence has size 8, which means you are using this `char *buf` as a 8-byte buffer. Just to be clear, `bpf_probe_read_str` does not allocate memory for you. The first argument (destination) need to be pointing to the memory location where the result is read into.

What you need is an actual buffer, like `char buf[256]`.

**Comment by fabio-oesch** [comment]
I will close this issue because I can't remember what I did here
