### ISSUE TITLE
Tracing output of oomkill

### ISSUE THREAD

**Issue by smita-koralahalli** [iovisor/bcc#1911]
I was going through the example of invoking oomkill and tested the working through two different processes a.out and perl which causes out of memory. The second output is the one mentioned in the example of oomkill. I couldn't understand the line  "OOM kill of PID 1835561760 ("lukB high:%lukB ")" in both the cases.

Output 1 : 17:39:52 Triggered by PID 10505 ("a.out"), OOM kill of PID 1835561760 ("lukB high:%lukB "), 2361183241434822607 pages, loadavg: 1.88 1.70 1.24 3/479 10508

Output 2 : 17:34:29 Triggered by PID 10414 ("perl"), OOM kill of PID 1835561760 ("lukB high:%lukB "), 2361183241434822607 pages, loadavg: 3.18 2.08 1.15 2/486 10430

Additionally tried running both the processes simultaneously and got the following output:
19:03:13 Triggered by PID 917 ("in:imklog"), OOM kill of PID 1835561760 ("lukB high:%lukB "), 2361183241434822607 pages, loadavg: 1.58 0.79 0.58 2/506 13238
19:03:16 Triggered by PID 2023 ("gmain"), OOM kill of PID 1835561760 ("lukB high:%lukB "), 2361183241434822607 pages, loadavg: 1.58 0.79 0.58 1/506 13239.

What does this line mean ? "OOM kill of PID 1835561760 ("lukB high:%lukB ")" in all cases? Is it one of the process which is oom killed?

**Comment by yonghong-song** [comment]
%lukB means unsigned long kB (1024 Bytes)?
The following is the latest bpf-next will print:
```
        pr_info("oom_reaper: reaped process %d (%s), now anon-rss:%lukB, file-rss:%lukB, shmem-rss:%lukB\n",
                        task_pid_nr(tsk), tsk->comm,
                        K(get_mm_counter(mm, MM_ANONPAGES)),
                        K(get_mm_counter(mm, MM_FILEPAGES)),
                        K(get_mm_counter(mm, MM_SHMEMPAGES)));
```
or
```
        pr_err("Killed process %d (%s) total-vm:%lukB, anon-rss:%lukB, file-rss:%lukB, shmem-rss:%lukB\n",
                task_pid_nr(victim), victim->comm, K(victim->mm->total_vm),
                K(get_mm_counter(victim->mm, MM_ANONPAGES)),
                K(get_mm_counter(victim->mm, MM_FILEPAGES)),
                K(get_mm_counter(victim->mm, MM_SHMEMPAGES)));
```
Which kernel version you are using? You should not see `%lukB` in the user output ...

**Comment by smita-koralahalli** [comment]
Its 4.15.0-29-generic

**Comment by yonghong-song** [comment]
The current oomkill.py expects the function signature likes below (starting from the second parameter):
```
void kprobe__oom_kill_process(struct pt_regs *ctx, struct oom_control *oc,
    struct task_struct *p, unsigned int points, unsigned long totalpages)
{
```

The 4.15 oom_kill_process has a signature
```
static void oom_kill_process(struct oom_control *oc, const char *message)
```
So the following information is incorrect
```
OOM kill of PID 1835561760 ("lukB high:%lukB "), 2361183241434822607 pages,
```
The kernel implementation changes between 4.4 and 4.9.

In this case, it may be worthwhile to put the current oomkill.py script to old/ directory
and changes the tools/oomkill.py uses the new interface.

**Comment by smita-koralahalli** [comment]
I got it thank you!
