### ISSUE TITLE
deadlock_detector "TypeError: can't concat str to bytes"

### ISSUE THREAD

**Issue by aborniak** [iovisor/bcc#1926]
Fedora 28
kernel "4.17.12-200.fc28.x86_64" 
python3-bcc-0.6.1-2.git.492a2bf.x86_64
bcc-tools-0.6.1-2.git.492a2bf.x86_64

`[root@aborniakFC tools]# ./deadlock_detector 553`
`Traceback (most recent call last):`
 ` File "./deadlock_detector", line 556, in <module>`
    `main()`
`  File "./deadlock_detector", line 471, in main`
 `   bpf.attach_kretprobe(event=bpf.get_syscall_fnname('clone'), fn_name='trace_clone')`
 ` File "/usr/lib/python3.6/site-packages/bcc/__init__.py", line 562, in get_syscall_fnname`
 `   return self.get_syscall_prefix() + name`
`TypeError: can't concat str to bytes`
`[root@aborniakFC tools]#`

**Comment by aborniak** [comment]
"execsnoop" has the same issue.

`[root@aborniakFC tools]# ./execsnoop`
`Traceback (most recent call last):`
  `File "./execsnoop", line 167, in <module>`
    `execve_fnname = b.get_syscall_fnname("execve")`
  `File "/usr/lib/python3.6/site-packages/bcc/__init__.py", line 562, in get_syscall_fnname`
  `  return self.get_syscall_prefix() + name`
`TypeError: can't concat str to bytes`
`[root@aborniakFC tools]#`

**Comment by yonghong-song** [comment]
We have a few fixes in trunk for python3 compatibility. Could you try whether the issue is fixed or not?
If not, could you help fix it with a pull request since you are testing it? Thanks!

**Comment by aborniak** [comment]
I've compiled bcc from sources.

`[root@aborniakFC bcc]# ./tools/deadlock_detector 610`
`could not determine address of symbol pthread_mutex_unlock. Failed to attach to symbol` `pthread_mutex_unlock`
`[root@aborniakFC bcc]#`

But execsnoop works well.

**Comment by palmtenor** [comment]
You might need to run with the `--binary` argument: See documentation [here](https://github.com/iovisor/bcc/blob/master/tools/deadlock_detector.py#L425)

**Comment by aborniak** [comment]
It's correct . Thank you.
