### ISSUE TITLE
Rewritting gethostlatency.py in C++ API

### ISSUE THREAD

**Issue by teroz** [iovisor/bcc#1928]
Hi there
I'm trying to write the gethostlatency example in C++. The code fails at runtime with  the error below
I'm using ubuntu 16.04

_Unable to attach uprobe for binary c symbol gethostbyname2 addr 0 using do_entry_

The attach code is as follows. Not sure why it works in python

```auto attach_res = bpf->attach_uprobe("c","gethostbyname2","do_entry");```

Any ideas why this is so?

**Comment by yonghong-song** [comment]
In the below code,
`bpf->attach_uprobe("c","gethostbyname2","do_entry");`
the library name `c` is not enough, you need to give the full library path, e.g., `/usr/lib64/libc-2.26.so`.

**Comment by teroz** [comment]
oic awesome thank you  - worked super
