### ISSUE TITLE
ns->us

### ISSUE THREAD

**Issue by liubogithub** [iovisor/bcc#1944]
https://github.com/iovisor/bcc/blob/852e19be503d0509dd31305c4446e4c0006295d4/tools/argdist_example.txt#L189

It refers to 0.1ms, which is 100,000us instead of ns

**Comment by pchaigno** [comment]
1 ms = 1000 us = 1000,000 ns so 0.1ms = 100,000ns. Looks correct to me.

**Comment by liubogithub** [comment]
Urr...somehow I thought that was 0.1 second, sorry for the noise.
