### ISSUE TITLE
Multiple programs attached to same Kernel Tracepoint interfere each other

### ISSUE THREAD

**Issue by myllynen** [iovisor/bcc#1966]
This is similar to a part of the earlier issue of #1334 which was fixed in the kernel already but then later it was found out (https://github.com/iovisor/bcc/issues/1334#issuecomment-390602944) that a related issue still remains. I've now tested with kernel 4.18 / bcc 0.7.0 and see that this is still not fixed:

With one instance of `urandomread.py` running and _mktemp_(1) being run three times on a different terminal I see this which is fine (though not sure why that <...> is being printed occasionally):

```
1321.609039000     <...>            7347    80
1322.379914000     mktemp           7348    80
1323.092013000     mktemp           7349    80
```

However, with two instances of `urandomread.py` running and _mktemp_(1) invoked three times I see something like this:

```
1375.131577000     mktemp           7360    80
1375.131588000     mktemp           7360    80
1375.874894000     mktemp           7361    80
1375.874906000     mktemp           7361    80
1376.944264000     <...>            7362    80
1376.944275000     <...>            7362    80
```

So the other `urandomread.py` is reporting things twice and the second is not reporting anything. Sometimes it could be that the other is reporting two and the other four events, looks like they end up randomly to the clients. I don't know whether this is a kernel or a BCC issue.

Thanks.

**Comment by palmtenor** [comment]
Can you repro the same with C++ `RandomRead` example?

**Comment by myllynen** [comment]
Good catch, with the C++ example things work as expected.

**Comment by olsajiri** [comment]
does not look like kernel issue.. looks like both urandomread.py scriptsread traces
and whoever gets it first wins.. the other gets nothing.. might be intended behaviour

jirka

**Comment by palmtenor** [comment]
I don't think that's intended behavior. Each script has its own program attached to the Tracepoint and submits sample to its own Perf Buffer, it should really work independently. I also agree it's probably not Kernel issue as C++ example works fine. Should be some bug in the Python lib.

**Comment by olsajiri** [comment]
it's supposed to be like that.. the C++ example is using per-event
buffers to store/read data, while urandomread.py is writen to do
trace_printk into global buffer, and reads tracefs trace-pipe..
so any running urandomread.py will race with other trace-pipe readers

to store the data into local perf map/buffer, you need to use something like this:

---
from __future__ import print_function
from bcc import BPF
from bcc.utils import printb
import time

# load BPF program
b = BPF(text="""
BPF_PERF_OUTPUT(events);

struct event_t {
  int  pid;
  char comm[16];
  int  got_bits;
};

TRACEPOINT_PROBE(random, urandom_read) {
    struct event_t event = {};
    event.pid = bpf_get_current_pid_tgid();
    bpf_get_current_comm(&event.comm, sizeof(event.comm));
    event.got_bits = args->got_bits;
    events.perf_submit(args, &event, sizeof(event));
    return 0;
}
""")

start_ts = time.time()

# header
print("%-18s %-16s %-6s %s" % ("TIME(s)", "COMM", "PID", "GOTBITS"))

def print_event(cpu, data, size):
    event = b["events"].event(data)
    printb(b"%-18.9f %-16s %-6d %s" % (time.time() - start_ts, event.comm, event.pid, event.got_bits))


# loop with callback to print_event
b["events"].open_perf_buffer(print_event)
while 1:
    try:
        b.perf_buffer_poll()
    except KeyboardInterrupt:
        exit()
---

**Comment by myllynen** [comment]
Thanks for pointing this out! Confirmed, closing.
