### ISSUE TITLE
bcc not work on my fc28 env. 

### ISSUE THREAD

**Issue by asmca** [iovisor/bcc#1971]
error.
[root@suse tmp]# /usr/share/bcc/tools/profile 
Sampling at 49 Hertz of all threads by user + kernel stack... Hit Ctrl-C to end.
/virtual/main.c:14:1: error: could not open bpf map: Operation not permitted
is maps/hash map type enabled in your kernel?
BPF_HASH(counts, struct key_t);
^
/virtual/include/bcc/helpers.h:132:48: note: expanded from macro 'BPF_HASH'
  BPF_HASHX(__VA_ARGS__, BPF_HASH4, BPF_HASH3, BPF_HASH2, BPF_HASH1)(__VA_ARGS__)
                                               ^
/virtual/main.c:15:1: error: could not open bpf map: Operation not permitted
is maps/stacktrace map type enabled in your kernel?
BPF_STACK_TRACE(stack_traces, 16384);
^
/virtual/include/bcc/helpers.h:199:3: note: expanded from macro 'BPF_STACK_TRACE'
  BPF_TABLE("stacktrace", int, struct bpf_stacktrace, _name, roundup_pow_of_two(_max_entries))
  ^
/virtual/include/bcc/helpers.h:60:76: note: expanded from macro 'BPF_TABLE'
#define BPF_TABLE(_table_type, _key_type, _leaf_type, _name, _max_entries) \
                                                                           ^
/virtual/include/bcc/helpers.h:56:4: note: expanded from macro '\
BPF_F_TABLE'
}; \
   ^
/virtual/main.c:29:25: error: bpf_table stack_traces failed to open
    key.user_stack_id = stack_traces.get_stackid(&ctx->regs, BPF_F_USER_STACK);
                        ^
3 errors generated.
Traceback (most recent call last):
  File "/usr/share/bcc/tools/profile", line 246, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 318, in __init__
    raise Exception("Failed to compile BPF text")
Exception: Failed to compile BPF text

myenv:
fedora 28
I tried to install bcc/rpm and build from source, neither works.
 bcc-tools                                 x86_64                           0.6.1-2.fc28    
 python3-bcc                               x86_64                           0.6.1-2.fc28    
 bcc                                       x86_64                           0.6.1-2.fc28   

kernel env.
[root@suse suse]# rpm -qa|grep `uname -r`
kernel-modules-extra-4.18.5-200.fc28.x86_64
kernel-core-4.18.5-200.fc28.x86_64
kernel-devel-4.18.5-200.fc28.x86_64
kernel-modules-4.18.5-200.fc28.x86_64
kernel-headers-4.18.5-200.fc28.x86_64
kernel-debug-devel-4.18.5-200.fc28.x86_64
kernel-4.18.5-200.fc28.x86_64

**Comment by asmca** [comment]
it's strange that I have other fc28 environment and it works fine on bcc.
also it might not be codebug, just environment issue, any ideas on debug?

**Comment by asmca** [comment]
I tried both python27 and python3 environment ,neither works.

**Comment by seanmalloy** [comment]
I am also trying to get this to work on Fedora 28, and seeing similar errors. Any thoughts on what I'm missing?

```
[root@Unknown tools]# /usr/share/bcc/tools/profile
Sampling at 49 Hertz of all threads by user + kernel stack... Hit Ctrl-C to end.
/virtual/main.c:14:1: error: could not open bpf map: Operation not permitted
is maps/hash map type enabled in your kernel?
BPF_HASH(counts, struct key_t);
^
/virtual/include/bcc/helpers.h:132:48: note: expanded from macro 'BPF_HASH'
  BPF_HASHX(__VA_ARGS__, BPF_HASH4, BPF_HASH3, BPF_HASH2, BPF_HASH1)(__VA_ARGS__)
                                               ^
/virtual/main.c:15:1: error: could not open bpf map: Operation not permitted
is maps/stacktrace map type enabled in your kernel?
BPF_STACK_TRACE(stack_traces, 16384);
^
/virtual/include/bcc/helpers.h:199:3: note: expanded from macro 'BPF_STACK_TRACE'
  BPF_TABLE("stacktrace", int, struct bpf_stacktrace, _name, roundup_pow_of_two(_max_entries))
  ^
/virtual/include/bcc/helpers.h:60:76: note: expanded from macro 'BPF_TABLE'
#define BPF_TABLE(_table_type, _key_type, _leaf_type, _name, _max_entries) \
                                                                           ^
/virtual/include/bcc/helpers.h:56:4: note: expanded from macro '\
BPF_F_TABLE'
}; \
   ^
/virtual/main.c:29:25: error: bpf_table stack_traces failed to open
    key.user_stack_id = stack_traces.get_stackid(&ctx->regs, BPF_F_USER_STACK);
                        ^
3 errors generated.
Traceback (most recent call last):
  File "/usr/share/bcc/tools/profile", line 246, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python3.6/site-packages/bcc/__init__.py", line 318, in __init__
    raise Exception("Failed to compile BPF text")
Exception: Failed to compile BPF text
```

My environment

Running Fedora 28
```
[root@Unknown tools]# rpm -qa | grep $(uname -r)
kernel-4.18.9-200.fc28.x86_64
kernel-headers-4.18.9-200.fc28.x86_64
kernel-modules-4.18.9-200.fc28.x86_64
kernel-modules-extra-4.18.9-200.fc28.x86_64
kernel-devel-4.18.9-200.fc28.x86_64
kernel-core-4.18.9-200.fc28.x86_64
```

Running bcc tools v0.7.0
```
[root@Unknown tools]# rpm -qa | grep bcc
libbcc-0.7.0-1.x86_64
python3-bcc-0.7.0-1.x86_64
bcc-tools-0.7.0-1.x86_64
```

Linux Kernel Config(standard Fedora 28 config)
```
[root@Unknown tools]# grep BPF /boot/config-4.18.9-200.fc28.x86_64 
CONFIG_CGROUP_BPF=y
CONFIG_BPF=y
CONFIG_BPF_SYSCALL=y
CONFIG_BPF_JIT_ALWAYS_ON=y
CONFIG_IPV6_SEG6_BPF=y
CONFIG_NETFILTER_XT_MATCH_BPF=m
# CONFIG_BPFILTER is not set
CONFIG_NET_CLS_BPF=m
CONFIG_NET_ACT_BPF=m
CONFIG_BPF_JIT=y
CONFIG_BPF_STREAM_PARSER=y
CONFIG_LWTUNNEL_BPF=y
CONFIG_HAVE_EBPF_JIT=y
CONFIG_BPF_EVENTS=y
# CONFIG_BPF_KPROBE_OVERRIDE is not set
# CONFIG_TEST_BPF is not set
```

**Comment by asmca** [comment]
well, Im working on thinkpad T460s with fc28.

Just disable "Secure Boot" on EFI BIOS,  and it works... embarrassing

LOL to close this issue

**Comment by seanmalloy** [comment]
I had the same problem. Also running on a ThinkPad laptop. Disabled "Secure Boot" in BIOS, and now it is working.
