### ISSUE TITLE
RFE: Provide more map methods in Python

### ISSUE THREAD

**Issue by myllynen** [iovisor/bcc#1987]
In long-running Python tools utilizing BCC at times it's needed to adjust the running BPF program for environment changes or user requests, for instance to update the list of PIDs being traced. Currently this requires detaching the BPF program, generating new BPF text, and attaching the new BPF program. This might cause missing events for PIDs that were already being traced and, perhaps more importantly, resets all maps used in the BPF program.

Were map methods insert()/update()/delete() available in Python, long-running Python tools could e.g. update a BPF hash to contain entries for the PIDs to be traced, avoiding the needed to detach/attach BPF programs and resetting maps in the process as the BPF program could act based on the hash map contents updated on-the-fly from Python.

**Comment by palmtenor** [comment]
I think set / delete for most map types are supported in Python API. Can you explain a bit more what doesn't work for you?

**Comment by myllynen** [comment]
Right, I was doing something wrong, this seems to work:

```
# cat ./test
#!/usr/bin/python3
from ctypes import c_ulong
from bcc import BPF
b = BPF(text="BPF_HASH(test);")
b["test"][c_ulong(0)] = c_ulong(2)
b["test"][c_ulong(1)] = c_ulong(3)
print(b["test"].items())
del b["test"][c_ulong(0)]
print(b["test"].items())
# ./test
[(c_ulong(0), c_ulong(2)), (c_ulong(1), c_ulong(3))]
[(c_ulong(1), c_ulong(3))]
# 
```

Thanks.
