### ISSUE TITLE
Tracepoint structs incorrectly sized types

### ISSUE THREAD

**Issue by ajor** [iovisor/bcc#2010]
There's already code in tp_frontend_action.cc to resize integer types based on the size value in the tracepoint format file, but some more re-sizings are needed for:
- gid_t
- pid_t
- uid_t
- u32 (can sometime be 64-bit!)

I came across this when implementing tracepoint args for bpftrace (and copying most of the code from tp_frontend_action). I also wrote a script to find any mismatching types in the running kernel's tracepoint format files: https://github.com/iovisor/bpftrace/blob/24c5248d578774d13d69b001fad8f50e2eac192a/scripts/tracepoint_variable_sized_types.py

On my computer this returns:
```
gid_t: 4,8
int: 4,8
pid_t: 4,8
u32: 4,8
uid_t: 4,8
unsigned: 4,8
unsigned int: 4,8
```
But I notice that BCC resizes more than just the types listed here - is that required, or was it just done for consistency?

Here's a BCC script which currently doesn't work correctly, as pid_t is defined as 32-bit in the kernel headers but is 64-bit in the tracepoint args struct for sys_enter_kill. 
```
from __future__ import print_function
from bcc import BPF
 
b = BPF(text="""
TRACEPOINT_PROBE(syscalls, sys_enter_kill) {
    bpf_trace_printk("pids: %d %d\\n", args->pid, sizeof(args->pid));
    return 0;
}
""")
 
print("%-18s %-16s %-6s %s" % ("TIME(s)", "COMM", "PID", "MSG"))
 
while 1:
    try:
        (task, pid, cpu, flags, ts, msg) = b.trace_fields()
    except ValueError:
        continue
    print("%-18.9f %-16s %-6d %s" % (ts, task, pid, msg))
```

**Comment by yonghong-song** [comment]
Thanks for sharing the issue! What kinds of rewriting do you suggest? It is possible to add necessary padding between known integer types. But this will not work if you have something like
```
pid_t a; /* offset 8, size 8 */
pid_t b; /* offset 16, size 8 */
```
Or we could just recognize this few types (`gid_t`, `uid_t`, `pid_t`) and specially process them in tp_frontend_action.cc?

**Comment by ajor** [comment]
The way I did it in bpftrace was to add those extra types to the set of ones which get converted to integers - https://github.com/iovisor/bpftrace/blob/c0dbeaf50b94b15167ab291546be0862c5b7578d/src/tracepoint_format_parser.cpp#L100

So `pid_t` gets rewritten to `u64` if its size if 8 in the format file.

But I wasn't sure what you wanted for BCC because I noticed that you also perform these type conversions on some other types like `char`. Have you seen issues with these being incorrectly sized too? I should add them into our conversions in bpftrace if that's the case.



Also to be clear, on my kernel at least, I'm seeing `u32` types being sized at 64 bit but these aren't handled in BCC either (it handles `uint32_t`, but not `u32`).

**Comment by yonghong-song** [comment]
No, I did not really see incorrect usage like `char`. The implementation is there just able to `future` proof. So if any newer tracepoint has a usage like `char` but with size 8, we will automatically correct it. I will implement missing pieces in bcc soon. Thanks!

**Comment by yonghong-song** [comment]
@ajor I made the bcc part of the change. I am using `s64` for `pid_t` as in kernel `pid_t` is really a typedef of `int` type. `gid_t` and `uid_t` are typedef of `unsigned int` type in kernel.
