### ISSUE TITLE
Test coverage

### ISSUE THREAD

**Issue by erthalion** [iovisor/bcc#2026]
In #1940 I was asked to add test coverage for my scripts, but [Contributing bcc/eBPF scripts](https://github.com/iovisor/bcc/blob/master/CONTRIBUTING-SCRIPTS.md) only mention `test_tools_smoke.py`. Can someone confirm, that for a new script it's enough to add just one smoke test there?

**Comment by yonghong-song** [comment]
in general, adding one smoke test in `test_tools_smoke.py` should be enough. If the test is rather complex, then I would recommend a separate test script (e.g., `test_tools_memleak.py`).

**Comment by erthalion** [comment]
Thanks!
