### ISSUE TITLE
bcc on kubernetes and linux headers

### ISSUE THREAD

**Issue by erthalion** [iovisor/bcc#2028]
I'm struggling with using bcc tools in a Kubernetes environment. What I'm
trying to do is to create a pod with all (or most of) the required libraries
preinstalled, and then trace whatever I need by attaching it. The main issue
for me right now is that K8S nodes are running the linux kernel version, that
I'm failing to install inside my pod (there is no such linux-headers package
for Ubuntu there, not in the official or ppa repositories).

So far I've got two ideas - to use a slightly different kernel headers, or to
clone linux manually and tell bcc to use the correct headers. When I'm trying
to run bcc inside the pod with a slightly different kernel, I've got:

```
# funccount 'vfs_read' -D
#include <uapi/linux/ptrace.h>

BPF_ARRAY(counts, u64, 1);

int trace_count_0(void *ctx) {

    int loc = 0;
    u64 *val = counts.lookup(&loc);
    if (!val) {
        return 0;   // Should never happen, # of locations is known
    }
    (*val)++;
    return 0;
}

bpf: Failed to load program: Invalid argument

Traceback (most recent call last):
  File "./funccount", line 299, in <module>
    Tool().run()
  File "./funccount", line 262, in run
    self.probe.attach()
  File "./funccount", line 93, in attach
    fn_name="trace_count_%d" % index)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 601, in attach_kprobe
    fn = self.load_func(fn_name, BPF.KPROBE)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 377, in load_func
    (func_name, errstr))
Exception: Failed to load BPF program trace_count_0: Invalid argument
```

so, apparently even small incompatibility is a problem.

When I'm trying to tell bcc which headers, that I've just cloned, to use by
providing `C_INCLUDE_PATH`, I'm trapped in the chain of something being not
found, or included in a wrong order.

I haven't found any similar issues in the repo, so what would be an advice in
this situation? Any feedback is welcome, it feels like I'm missing something
simple.

**Comment by yonghong-song** [comment]
You may need kernel-devel package instead of kernel-headers.
There is env `BCC_KERNEL_SOURCE` which you sets to the root of you kernel source or kernel devel header source, e.g., `/lib/modules/$(uname -r)/source`.

**Comment by erthalion** [comment]
> You may need kernel-devel package instead of kernel-headers.

Do you mean something like `linux-source`? But how would it help, isn't it the same problem when versions of kernel sources are mismatched?

**Comment by ViviLearns2Code** [comment]
@erthalion hello, I found your post when searching for a solution to my problem. I want to run memleak in my application container running in a k8s pod (k3s cluster). And there I fail at the same step with the Linux headers.

I am not very familiar with kernel stuff, so I could not quite follow the discussion here. Could you explain to me what steps you needed to carry out to get install bcc tools in the pod container? 

Thanks a lot!

**Comment by erthalion** [comment]
@ViviLearns2Code in this case the version of linux headers available inside the pod was different from the version kernel on the host. If that's the case for you as well, and nothing has changed in bcc since then, the steps are:
* install `kernel-devel` package (or an equivalent)
* set `BCC_KERNEL_SOURCE` env variable to point to it (`/lib/modules/$(uname -r)/source`)
* set `BCC_LINUX_VERSION_CODE` env variable to match your host kernel version (the formula is `VERSION_CODE = a * 65536 + b * 256 + c`, where `a.b.c` is the version, e.g. `5.14.96`).
