### ISSUE TITLE
Duplicate code in xdp_drop_count.py

### ISSUE THREAD

**Issue by sevagh** [iovisor/bcc#2048]
Not sure if I'm misreading this but it looks like duplicate blocks of code here:
https://github.com/sevagh/bcc/blob/master/examples/networking/xdp/xdp_drop_count.py#L99-L107

**Comment by yonghong-song** [comment]
Looks like this is the case. Could you send a pull request to fix the issue? Could you also fix indentation issue for statement
```
h_proto = vhdr->h_vlan_encapsulated_proto;
```
Thanks!
