### ISSUE TITLE
make install not updating libbcc.so

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#207]
Just had to use:

```Shell
bcc# cp build/src/cc/libbcc.so.0.1.6-e292255e /usr/lib/x86_64-linux-gnu/libbcc.so.0.1.6 
```

To get it to work. make install wasn't updating it. Not sure why -- maybe my system is messed up. Looks like it was updating /usr/lib/libbcc.so.0, but not the x86_64-linux-gnu dir.

**Comment by drzaeus77** [comment]
Do you see a lot of libbcc.so.0.1.6-* in /usr/lib...?

**Comment by drzaeus77** [comment]
I ask because there is no make uninstall, so there might be a lot of buildup in /usr. One alternative could be to use $PWD as the install prefix, and use LD_LIBRARY_PATH/PYTHONPATH while developing. This would be for developers only.

**Comment by brendangregg** [comment]
```Shell
# ls -lthr /usr/lib/libbcc*
lrwxrwxrwx 1 root root  11 Sep  4 18:29 /usr/lib/libbcc.so -> libbcc.so.0
-rw-r--r-- 1 root root 38M Sep  4 18:56 /usr/lib/libbcc.so.0.1.6-5d89d5fd
-rw-r--r-- 1 root root 38M Sep  7 21:56 /usr/lib/libbcc.so.0.1.6-4135be22
-rw-r--r-- 1 root root 38M Sep  8 20:57 /usr/lib/libbcc.so.0.1.6-8d0425cb
-rw-r--r-- 1 root root 38M Sep  9 22:02 /usr/lib/libbcc.so.0.1.6-d014a293
-rw-r--r-- 1 root root 38M Sep  9 22:09 /usr/lib/libbcc.so.0.1.6-78823a8e
-rw-r--r-- 1 root root 38M Sep 10 00:54 /usr/lib/libbcc.so.0.1.6-076e8ab2
-rw-r--r-- 1 root root 38M Sep 10 22:35 /usr/lib/libbcc.so.0.1.6-fd093f34
lrwxrwxrwx 1 root root  24 Sep 11 21:30 /usr/lib/libbcc.so.0 -> libbcc.so.0.1.6-e292255e
-rw-r--r-- 1 root root 38M Sep 11 23:16 /usr/lib/libbcc.so.0.1.6-e292255e
```

**Comment by drzaeus77** [comment]
Does cleaning up that directory and re-installing fix the problem, or is there something else going on?

**Comment by brendangregg** [comment]
Ah, by deleting everything and redoing a make install, it only placed the /usr/lib version:

```Shell
# ls -lh /usr/lib/libbcc*
lrwxrwxrwx 1 root root  11 Sep 11 23:39 /usr/lib/libbcc.so -> libbcc.so.0
lrwxrwxrwx 1 root root  24 Sep 11 23:39 /usr/lib/libbcc.so.0 -> libbcc.so.0.1.6-e292255e
-rw-r--r-- 1 root root 38M Sep 11 23:05 /usr/lib/libbcc.so.0.1.6-e292255e
# ls -lh /usr/lib/x86_64-linux-gnu/libbcc*
ls: cannot access /usr/lib/x86_64-linux-gnu/libbcc*: No such file or directory
```

And it works.

So I guess people wouldn't hit this unless they were refreshing and building bcc.

**Comment by drzaeus77** [comment]
Exactly. That said, I think the change I just sent a pull request for will make your life just slightly easier without impacting the packaging.

**Comment by drzaeus77** [comment]
You might also want to try `pip uninstall bcc` in a loop until it starts complaining. My usual workflow is:

```
make -j8
sudo pip uninstall -y bcc; sudo make install
```

**Comment by drzaeus77** [comment]
Did the commit mentioned above improve the behavior? Would like to close this if so.

**Comment by brendangregg** [comment]
Yes, it looks like things work now, closing.
