### ISSUE TITLE
detach_kprobe_event use wrong variable to raise exception

### ISSUE THREAD

**Issue by maxdml** [iovisor/bcc#2088]
An application trying to gracefully detach a kprobe which failed to attach in the first place crashes, if `detach_kprobe_event` is not try'ed catched,  with:

```
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 637, in detach_kprobe
    self.detach_kprobe_event(ev_name)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 625, in detach_kprobe_event
    raise Exception("Kprobe %s is not attached" % event)
NameError: global name 'event' is not defined
```

It seems that `event` should be `ev_name` in `detach_kprobe_event`:
```
def detach_kprobe_event(self, ev_name):
    if ev_name not in self.kprobe_fds:
        raise Exception("Kprobe %s is not attached" % event)
```

BCC 0.7.0-1 on Ubuntu 16.04 with kernel 4.15.0-39-generic

**Comment by yonghong-song** [comment]
Yes, it should be `ev_name`. Do you mind to send a pull request to fix the issue? Thanks!
