### ISSUE TITLE
USDT tracing fails with the error 'LLVM Error: Cannot select: '

### ISSUE THREAD

**Issue by vijunag** [iovisor/bcc#2141]
static __always_inline int _bpf_readarg_do_trace_1(struct pt_regs *ctx, void *dest, size_t len) {
  if (len != sizeof(uint64_t)) return -1;
  *((uint64_t *)dest) = ctx->ax; __asm__ __volatile__("": : :"memory");
  return 0;
}

#include <uapi/linux/ptrace.h>
int do_trace(struct pt_regs *ctx) {
    uint64_t addr;
    char data[1200]={0};
    bpf_usdt_readarg(1, ctx, &addr);
    bpf_probe_read(&data, sizeof(data), (void *)addr);
    return 0;
};

LLVM ERROR: Cannot select: 0x565411698700: ch,glue = BPFISD::CALL 0x565411851370, TargetExternalSymbol:i64'memset', Register:i64 %R1, Register:i64 %R2, Register:i64 %R3, 0x565411851370:1
  0x565411698830: i64 = TargetExternalSymbol'memset'
  0x565411697c50: i64 = Register %R1
  0x56541184f8b0: i64 = Register %R2
  0x565411850c50: i64 = Register %R3
  0x565411851370: ch,glue = CopyToReg 0x565411850d80, Register:i64 %R3, Constant:i64<1200>, 0x565411850d80:1
    0x565411850c50: i64 = Register %R3
    0x56541147a230: i64 = Constant<1200>
    0x565411850d80: ch,glue = CopyToReg 0x565411a59060, Register:i64 %R2, Constant:i64<0>, 0x565411a59060:1
      0x56541184f8b0: i64 = Register %R2
      0x565411850fe0: i64 = Constant<0>
      0x565411a59060: ch,glue = CopyToReg 0x5654118506f0, Register:i64 %R1, FrameIndex:i64<0>
        0x565411697c50: i64 = Register %R1
        0x565411a58cd0: i64 = FrameIndex<0>
In function: do_trace

**Comment by yonghong-song** [comment]
It complains external symbol `memset`. I guess this comes from `char data[1200] = {0}`.
The `1200` is too big. The maximum bpf program stack size is 512. This will be surely
rejected by kernel.

The compiler is able to turn small memset (<= 128 bytes) into stores. Large memset will remain function call and bpf compilation will fail since bpf dos not allow external calls.

**Comment by vijunag** [comment]
@pchaigno  - Can you please give an example code excerpt ?

**Comment by pchaigno** [comment]
Something like:
```c
typedef struct data_t { char d[1200]; } data_t;
BPF_ARRAY(data, data_t, 1);

int do_trace(struct pt_regs *ctx) {
  u32 zero = 0;
  uint64_t addr;
  bpf_usdt_readarg(1, ctx, &addr);
  void *datap = data.lookup(&zero);
  if (!datap)
    return 0;
  bpf_probe_read(datap, 1200, (void *)addr);
  return 0;
};
```

**Comment by vijunag** [comment]
@pchaigno - Thanks for the reply. Is it possible to perf_output this structure ?

**Comment by pchaigno** [comment]
I guess, but I've not tested. You'll need a kernel 4.18+ though, to be able to use map values as the keys and values of other maps.

**Comment by pchaigno** [comment]
@vijunag I think this issue can be closed since it's not a bug in bcc?

**Comment by vijunag** [comment]
Sure.
