### ISSUE TITLE
function argument passing

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#215]
I've used extra C functions before (bitehist.c), but in this case the arguments are getting messed up. Boiling it down:

```C
#define TRACE_READ      0

int trace_return(struct pt_regs *ctx, int type)
{
        bpf_trace_printk("type %d\\n", type);
}

int trace_read_return(struct pt_regs *ctx)
{
        return trace_return(ctx, TRACE_READ);
}
```

```Python
b.attach_kretprobe(event="vfs_read", fn_name="trace_read_return")
```

output:

```Shell
           <...>-8945  [002] d... 31444677.040511: : type -726790832
           <...>-8945  [002] d... 31444677.047811: : type -921649152
        fsslower-8945  [002] d... 31444677.047933: : type -708351448
        fsslower-8945  [002] d... 31444677.047975: : type -920629936
[...]
```

**Comment by drzaeus77** [comment]
Did you check the warnings that LLVM gave?
<bcc-memory-buffer>:8:1: warning: control reaches end of non-void function [-Wreturn-type]
}
^
1 warning generated.

**Comment by drzaeus77** [comment]
Also, I would suggest that all helper functions be declared static inline.

**Comment by brendangregg** [comment]
```static int trace_return(...``` fixed it, thanks. Should have thought of that...
