### ISSUE TITLE
rename deadlock_detector to deadlock

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#2152]
The name is too long (doesn't fit well on diagrams) and doesn't follow the style of the other tools. Can this please be renamed to "deadlock"?

@kennyyu

**Comment by kennyyu** [comment]
@brendangregg Yep! I'll send a PR after the upcoming long weekend to rename this.

**Comment by Trundle** [comment]
I think this issue can be closed, given that #2160 is merged.
