### ISSUE TITLE
"Add build_id support for BPF stackmap" broke libbcc for ubuntu 18.04

### ISSUE THREAD

**Issue by rjmccabe3701** [iovisor/bcc#2159]
#2098 broke our code including ``bcc/BPFTable.h``

I'm running on a stock Ubuntu 18.04 system, with a 4.15 Linux kernel.

Example :

```c++
//BPFTable_failure.cpp
#include <bcc/BPFTable.h>
int main(void) { }
````

```bash
-> % g++ BPFTable_failure.cpp
In file included from BPFTable_failure.cpp:1:0:
/usr/include/bcc/BPFTable.h:320:54: error: field ‘trace’ has incomplete type ‘bpf_stack_build_id [127]’
   struct bpf_stack_build_id trace[BPF_MAX_STACK_DEPTH];
                                                      ^
In file included from /usr/include/bcc/BPFTable.h:30:0,
                 from BPFTable_failure.cpp:1:
/usr/include/bcc/bcc_syms.h:76:38: note: forward declaration of ‘struct bpf_stack_build_id’
                               struct bpf_stack_build_id *trace,
```

There should be pre-processor guards in these files if the features aren't supported by the host's kernel.

**Comment by yonghong-song** [comment]
@vijunag could you take a look? probably need to a correct include path in cmake file to contain bpf.h from libbpf/include/uapi/linux directory.

**Comment by vijunag** [comment]
Yes, will take a look at it. There is no -I incantation to that directory already ?

**Comment by yonghong-song** [comment]
I think your patch is tested against code base before libbpf work. That is why the buildbot did not catch the issue.

**Comment by yonghong-song** [comment]
Or I could be wrong as later buildbot seems fine. In any case, please take a look. Thanks.

**Comment by yonghong-song** [comment]
We do ship uapi headers at /usr/include/bcc/compat/linux directory. User codes should include the bpf header there with proper include patch.

**Comment by vijunag** [comment]
@yonghong-song - Can we close this PR if nothing needs to be done from bcc end ?

**Comment by rjmccabe3701** [comment]
For completeness, this is what makes it work:

```bash
g++ -I /usr/include/bcc/compat BPFTable_failure.cpp
```
Thanks.
