### ISSUE TITLE
attach_kretprobe missing in C API

### ISSUE THREAD

**Issue by teroz** [iovisor/bcc#2173]
The C api is missing the `attach_kretprobe` call which is available in the Python api and the `kretprobe__`  special prefix  in the C method declaration does not work in the C API as well. Am using version 0.8 of the library

**Comment by reenanair** [comment]
The `attach_uretprobe` is also missing in the C API.

**Comment by palmtenor** [comment]
kretprobe is attached through specifying `bpf_probe_attach_type` to be `BPF_PROBE_RETURN` in C API.

**Comment by teroz** [comment]
oic workers perfectly @palmtenor  thank you

**Comment by reenanair** [comment]
@palmtenor Thank you. Works like a charm..
