### ISSUE TITLE
Calling time function in Kprobe fails

### ISSUE THREAD

**Issue by iqbal-h** [iovisor/bcc#2216]
I am having trouble in fetching epoch time value inside kprobe. I am wondering whether it is allowed to call other linux library functions inside probe or not? 

Below is the BPF TEXT
bpf_text = """
#define _POSIX_C_SOURCE 199309L
#include <uapi/linux/ptrace.h>
#define KBUILD_MODNAME "foo"
#include <linux/tcp.h>
#include <net/sock.h>
#include <bcc/proto.h>
#include "linux/timekeeping.h"
#include "linux/ktime.h"
#include <linux/time.h>

struct timespec_t { 
    time_t tv_sec; /* seconds */ 
    long tv_nsec; /* nanoseconds */ 
};

struct data_t {
    u32 pid;  // PID as in the userspace term (i.e. task->tgid in kernel)
    char comm[TASK_COMM_LEN];
    int retval;
    u64 daddr;
};

struct ipv4_data_t {
    u64 pid;
    u64 saddr;
    u64 daddr;
    u64 ports;
    u8 protocol;
    u64 tstamp;
    u64 tstampk;
    u8 type;
    u16 seqno;
    u16 id;
};

struct iphdr {
    #if defined(__LITTLE_ENDIAN_BITFIELD)
        __u8    ihl:4,
            version:4;
    #elif defined (__BIG_ENDIAN_BITFIELD)
        __u8    version:4,
            ihl:4;
    #else
    #error  "Please fix <asm/byteorder.h>"
    #endif
        __u8    tos;
        __be16  tot_len;
        __be16  id;
        __be16  frag_off;
        __u8    ttl;
        __u8    protocol;
        __sum16 check;
        __be32  saddr;
        __be32  daddr;
        /*The options start here. */
};

struct icmphdr {
  __u8      type;
  __u8      code;
  __sum16   checksum;
  union {
    struct {
        __be16  id;
        __be16  sequence;
    } echo;
    __be32  gateway;
    struct {
        __be16  __unused;
        __be16  mtu;
    } frag;
    __u8    reserved[4];
  } un;
};

BPF_PERF_OUTPUT(ipv4_icmprcv_event);
//**************  RECEIVE  ******************
int kprobe__icmp_rcv(struct pt_regs *ctx, struct sk_buff *skb){
    u32 pid = bpf_get_current_pid_tgid() >> 32;
    //struct iphdr *iph =  ip_hdr(skb);
    
    struct timespec_t *tspec;
    clock_gettime(CLOCK_REALTIME, tspec);
    u64 temp_ts = tspec->tv_sec*1000000000 + tspec->tv_nsec;

    struct iphdr *iph = (struct iphdr *)(skb->head + skb->network_header);
    struct icmphdr *icmph = (struct icmphdr *)(skb->head + skb->transport_header);
    struct ipv4_data_t data4 = {};
   
    data4.saddr = iph->saddr;
    data4.daddr = iph->daddr;
    data4.pid = pid;
    data4.protocol = iph->protocol;
    data4.tstamp = skb->tstamp; 
    data4.tstampk = temp_ts;

    //data4.tstampk = bpf_ktime_get_ns()/1000;
    //data4.tstampk = ktime_get_real();
    data4.type = icmph->type;
    data4.seqno = icmph->un.echo.sequence;
    data4.id = icmph->un.echo.id;

    data4.seqno = (data4.seqno >> 8) | (data4.seqno << 8);
    data4.id = (data4.id >> 8) | (data4.id << 8);

    if(data4.protocol == 1){
        ipv4_icmprcv_event.perf_submit(ctx, &data4, sizeof(data4));
    }    
    return 0;
}
"""

Here is the output 
/virtual/main.c:101:5: warning: implicit declaration of function 'clock_gettime' is invalid in C99 [-Wimplicit-function-declaration]
    clock_gettime(CLOCK_REALTIME, tspec);
    ^
/virtual/main.c:160:1: warning: control reaches end of non-void function [-Wreturn-type]
}
^
2 warnings generated.
bpf: Failed to load program: Invalid argument
0: (7b) *(u64 *)(r10 -96) = r1
1: (79) r7 = *(u64 *)(r1 +112)
2: (85) call bpf_get_current_pid_tgid#14
3: (7b) *(u64 *)(r10 -80) = r0
4: (b7) r9 = 0
5: (b7) r1 = 0
6: (50) r0 = *(u8 *)skb[r9 + 0]
BPF_LD_[ABS|IND] instructions not allowed for this program type

Traceback (most recent call last):
  File "./bpfec2.py", line 430, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 337, in __init__
    self._trace_autoload()
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 1030, in _trace_autoload
    fn = self.load_func(func_name, BPF.KPROBE)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 377, in load_func
    (func_name, errstr))
Exception: Failed to load BPF program kprobe__icmp_rcv: Invalid argument

Above output is for clock_gettime().
If I use bpf_ktime_get_ns(), it works fine but it gives kernel boot time not real time.
Using ktime_get_real(); gives following error:-

LLVM ERROR: Program used external function 'ktime_get_with_offset' which could not be resolved!
Please, guide further. Thank you.

**Comment by iqbal-h** [comment]
Using data4.tstampk = ktime_get_real(); gives following error:-

LLVM ERROR: Program used external function 'ktime_get_with_offset' which could not be resolved!

**Comment by palmtenor** [comment]
You can not call arbitrary Kernel function in your BPF program. To get time information, you need to use the builtin helper function `bpf_ktime_get_ns`

**Comment by yonghong-song** [comment]
Note that `bpf_ktime_get_ns` won't give you epoch time. You could estimate by getting an epoch time and a monotonic time around prog load time and use it as a reference point. Later on, when you got a kernel `bpf_ktime_get_ns`, you can roughly correlate it to the epoch time. I did not verify it and you could experiment to see whether it works or not.

**Comment by iqbal-h** [comment]
Thank you for the input. I am now using `bpf_ktime_get_ns` and monotonic time as reference time to cater for the offset in the reading.
