### ISSUE TITLE
Compile failure main trunck

### ISSUE THREAD

**Issue by weixingsun** [iovisor/bcc#2221]
Dude, I am facing a building issue: 
I want to upgrade my old bcc-0.6.0 to latest git, but failed now 
Just want to know any software dependencies not addressed in wiki
My software:
Ubuntu 18.04 
sudo apt install libelf-dev flex netperf iperf3 
downloaded tars:
clang_llvm_7.0.1
LuaJIT-2.0.5
bison-3.3

Thanks for any comments
......
[ 90%] Building CXX object examples/cpp/CMakeFiles/UseExternalMap.dir/UseExternalMap.cc.o
[ 90%] Linking CXX executable FollyRequestContextSwitch
In file included from /home/sun/clang_llvm_7.0.1/include/clang/AST/DeclCXX.h:21:0,
                 from /home/sun/clang_llvm_7.0.1/include/clang/AST/RecordLayout.h:19,
                 from /home/sun/perf/bcc/src/cc/json_map_decl_visitor.cc:21:
/home/sun/clang_llvm_7.0.1/include/clang/AST/Attr.h: In static member function ‘static clang::ParamIdx clang::ParamIdx::deserialize(clang::ParamIdx::SerialType)’:
/home/sun/clang_llvm_7.0.1/include/clang/AST/Attr.h:249:48: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     ParamIdx P(*reinterpret_cast<ParamIdx *>(&S));
                                                ^
/home/sun/clang_llvm_7.0.1/include/clang/AST/Attr.h:249:49: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     ParamIdx P(*reinterpret_cast<ParamIdx *>(&S));
                                                 ^
/usr/bin/ld: cannot find -ltinfo
collect2: error: ld returned 1 exit status
examples/cpp/CMakeFiles/FollyRequestContextSwitch.dir/build.make:164: recipe for target 'examples/cpp/FollyRequestContextSwitch' failed
make[2]: *** [examples/cpp/FollyRequestContextSwitch] Error 1
CMakeFiles/Makefile2:822: recipe for target 'examples/cpp/CMakeFiles/FollyRequestContextSwitch.dir/all' failed
make[1]: *** [examples/cpp/CMakeFiles/FollyRequestContextSwitch.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 90%] Linking CXX executable UseExternalMap
/usr/bin/ld: cannot find -ltinfo
collect2: error: ld returned 1 exit status
examples/cpp/CMakeFiles/UseExternalMap.dir/build.make:164: recipe for target 'examples/cpp/UseExternalMap' failed
make[2]: *** [examples/cpp/UseExternalMap] Error 1
CMakeFiles/Makefile2:865: recipe for target 'examples/cpp/CMakeFiles/UseExternalMap.dir/all' failed
make[1]: *** [examples/cpp/CMakeFiles/UseExternalMap.dir/all] Error 2
[ 90%] Linking CXX shared library libbcc.so
/usr/bin/ld: cannot find -ltinfo
collect2: error: ld returned 1 exit status
src/cc/CMakeFiles/bcc-shared.dir/build.make:578: recipe for target 'src/cc/libbcc.so.0.8.0' failed
make[2]: *** [src/cc/libbcc.so.0.8.0] Error 1
CMakeFiles/Makefile2:198: recipe for target 'src/cc/CMakeFiles/bcc-shared.dir/all' failed
make[1]: *** [src/cc/CMakeFiles/bcc-shared.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by pchaigno** [comment]
I never had this issue with the setup you described. Could you try the following SO answer: https://stackoverflow.com/a/30199196/6884590?

**Comment by weixingsun** [comment]
thanks for your comments, I got it fixed by removing libtinfo6 from my OS
I saw libtinfo5 & libtinfo6 in my OS, by using dpdk -l |grep libtinfo
Not sure when I got it installed, thanks for your help
