### ISSUE TITLE
Attaching uprobes to fixed addresses

### ISSUE THREAD

**Issue by mephi42** [iovisor/bcc#2231]
I'm trying to trace an asm instruction at the known offset relative to module start. The Python doc for `attach_uprobe` says: "The real address addr may be supplied in place of sym." So I tried:

```
b.attach_uprobe(name=obj, addr=insn, fn_name='<redacted>')
```

which results in

```
Exception: could not determine address of symbol b''
```

I also tried

```
b.attach_uprobe(name=obj, sym=None, addr=insn, fn_name='<redacted>')
```

but then I get

```
Exception: could not determine address of symbol None
```

Is there some other way to do this? Is this supported at all?

**Comment by mephi42** [comment]
It turned out that the problem was that the module in question was non-PIE executable, and in that case the address must have been the absolute one, as opposed to the offset relative to the start of the module.

Maybe this could be added to the `attach_uprobe` documentation?

**Comment by palmtenor** [comment]
In the underlying logic, when you have provided a symbol name, we still resolve it to an address for attaching, so this should work. Can you repro this on some common library like `libc` etc. so that I could debug?

**Comment by mephi42** [comment]
This is the minimal repro of what I struggled with:

```
$ echo 'int main() {}' >test.c
$ gcc test.c
$ objdump -x a.out | grep -w -e "LOAD off" -e main
    LOAD off    0x0000000000000000 vaddr 0x0000000001000000 paddr 0x0000000001000000 align 2**12
    LOAD off    0x0000000000000e00 vaddr 0x0000000001001e00 paddr 0x0000000001001e00 align 2**12
00000000010004f8 g     F .text	000000000000001a              main

# offset = 0x10004f8 - 0x1000000 = 0x4f8

$ python3 -c 'import bcc; b = bcc.BPF(text="int foo() { return 0; }"); b.attach_uprobe(name="./a.out", addr=0x4f8, fn_name="foo")'
Exception: could not determine address of symbol b''
```

My fix/workaround:

```
$ python3 -c 'import bcc; b = bcc.BPF(text="int foo() { return 0; }"); b.attach_uprobe(name="./a.out", addr=0x10004f8, fn_name="foo")'
```

**Comment by yonghong-song** [comment]
In the above, the virtual address is needed, not the offset from the start of the section.

**Comment by mephi42** [comment]
Ok, but for shared libraries one needs an offset:

```
$ objdump -x /lib64/libc.so.6 | grep -w -e "LOAD off" -e __libc_main
    LOAD off    0x0000000000000000 vaddr 0x0000000000000000 paddr 0x0000000000000000 align 2**12
    LOAD off    0x0000000000198a60 vaddr 0x0000000000199a60 paddr 0x0000000000199a60 align 2**12
00000000000242a0 l     F .text	000000000000002a              __libc_main

# offset = 0x242a0 - 0x0 = 0x242a0

$ python3 -c 'import bcc; b = bcc.BPF(text="int foo() { return 0; }"); b.attach_uprobe(name="/lib64/libc.so.6", addr=0x242a0, fn_name="foo")'
```

It is clear why this is the case: shared library virtual address is not known at probe attachment time, and may even be different in different processes.

Still, these two examples highlight the difference between handling non-PIE executables and everything else, which confused me at the beginning. Therefore I think it is worth mentioning in the documentation of `attach_uprobe` (and whatever else has `addr` parameter).

**Comment by yonghong-song** [comment]
Totally agree with documentation part to make it clear how to assign values to `addr` field. Could you help submit a pull request for this since you are at it? Thanks!

**Comment by palmtenor** [comment]
@mephi42 I see what you mean now.

uprobe always take file offset. But for `ET_EXEC` binaries the symbol table is a mapping from symbol names to their loaded addresses, and normally users attach uprobe with symbol names so we translate them using symbol table, hence we have this translation. This should be excluded if user provided an address explicitly. I will put up a PR shortly.

**Comment by palmtenor** [comment]
Actually, I just realized I can't really do that PR. For USDTs in executable binaries, the note section has the loaded addresses of the Tracepoints and we rely on this behavior to correctly resolve them. It would be too much trouble to change that all along.

I guess you just need to provide loaded addresses for executable binaries. Think about it this way, it's consistent with the symbol table's behavior: for `ET_EXEC` it's loaded address and for `ET_DYN` it's absolute file address. If you always add an offset onto a function address you get from symbol table, you should be good...

**Comment by mephi42** [comment]
Ok, that's actually what I ended up doing. So I will send a PR for documentation tomorrow.
