### ISSUE TITLE
bpf_probe_read() returned -14

### ISSUE THREAD

**Issue by JayceCao** [iovisor/bcc#2245]
This is the code:
``` py
from bcc import BPF


text="""
#include <uapi/linux/ptrace.h>
#include <linux/sched.h>

int sys__execve(struct pt_regs *ctx, const char __user *filename,
        const char __user *const __user *__argv,
        const char __user *const __user *__envp)
{
    char name[256];
    int i = bpf_probe_read(name, sizeof(name), filename);
    bpf_trace_printk("i = %d\\n", i);

    return 0;
}

int ret_sys__execve(struct pt_regs *ctx)
{
    return 0;
}
"""

b = BPF(text=text)
b.attach_kprobe(event=b.get_syscall_fnname('execve'), fn_name="sys__execve")
b.attach_kretprobe(event=b.get_syscall_fnname('execve'), fn_name="ret_sys__execve")
b.trace_print()
```

The output is:
```
b'              tc-27662 [000] ...3 20802.736849: 0: i = -14'
b'    tmux: server-27663 [005] ...3 20803.072455: 0: i = -14'
b'              sh-27663 [005] ...3 20803.078700: 0: i = -14'
b'            bash-27664 [002] ...3 20803.742194: 0: i = -14'
```
And the content of `name` is nothing.

bcc version: `0.8.0`
kernel version: `4.20.13-arch1-1-ARCH`

**Comment by palmtenor** [comment]
Can you see what the actual value (maybe in `%lx`) of `filename` is?

**Comment by JayceCao** [comment]
> Can you see what the actual value (maybe in `%lx`) of `filename` is?

change the code:
```
bpf_trace_printk("filename = %lx\\n", filename);
```
the output:
```
b'            bash-2175  [004] ...3 23022.727082: 0: filename = ffffa6eb81a1ff58'
b'    tmux: server-2176  [007] ...3 23023.363794: 0: filename = ffffa6eb81a8ff58'
b'              sh-2176  [007] ...3 23023.370145: 0: filename = ffffa6eb81a8ff58'
b'            bash-2177  [002] ...3 23023.718074: 0: filename = ffffa6eb81bb7f58'
b'    tmux: server-2178  [003] ...3 23024.362750: 0: filename = ffffa6eb81ebbf58'
b'              sh-2178  [003] ...3 23024.367830: 0: filename = ffffa6eb81ebbf58'
b'            bash-2179  [003] ...3 23024.720046: 0: filename = ffffa6eb81eeff58'
b'    tmux: server-2180  [000] ...3 23025.362583: 0: filename = ffffa6eb81bb7f58'
b'              sh-2180  [000] ...3 23025.370168: 0: filename = ffffa6eb81bb7f58'
b'            bash-2181  [003] ...3 23025.723059: 0: filename = ffffa6eb81f13f58'
b'    tmux: server-2182  [005] ...3 23026.364206: 0: filename = ffffa6eb81f33f58'
```

**Comment by palmtenor** [comment]
It looks like the argument is wrong. BPF doesn't understand file argument and its format, here it's just blindly take value of "first argument", i.e., `rdi`, as the value of `filename`. I don't really know in details how the `SYSCALL_DEFINE` macros is expanded but maybe `filename` is not at where we think it is.

Maybe try trace the actual logic function `do_execve`. Or better, trace the `sched:sched_process_exec` Tracepoint which has much more stable and well structured data

**Comment by yonghong-song** [comment]
is this a x64 or a arm64 system?

**Comment by JayceCao** [comment]
> is this a x64 or a arm64 system?

x64.
I reimplement this through kprobe.
Actually the code is the simple version of `tools/execsnoop` and `execsnoop` can run normally.

**Comment by pchaigno** [comment]
@JayceCao How did you install bcc? From packages?

Could you add `debug=4` to `BPF(text=text)` and give us the output? I'd like to check that it's not an issue with the rewriter (seems unlikely).

**Comment by yonghong-song** [comment]
For 4.20, syscall parameters are wrapped in another pt_regs for x64 and needs special processing.
Using function name `syscall__execve` should resolve your issue. You can use debug=4 to check the rewriter output between function name `sys_execve` and `syscall_execve`. The `syscall_` prefix tells rewriter to do some massaging.

**Comment by JayceCao** [comment]
> For 4.20, syscall parameters are wrapped in another pt_regs for x64 and needs special processing.
> Using function name `syscall__execve` should resolve your issue. You can use debug=4 to check the rewriter output between function name `sys_execve` and `syscall_execve`. The `syscall_` prefix tells rewriter to do some massaging.

It works. Thanks for your help. It seems that the point don't mentioned in the doc. The doc needs to be perfect.

**Comment by yonghong-song** [comment]
@JayceCao since you are at this, could you help submit a pull request to fix the doc? Thanks!
