### ISSUE TITLE
failed with kallsyms_lookup_name

### ISSUE THREAD

**Issue by ethercflow** [iovisor/bcc#2247]
I want to get some kernel data's addr with `kallsyms_lookup_name` but failed.

``` python
#!/usr/bin/python

from bcc import BPF

# This may not work for 4.17 on x64, you need replace kprobe__sys_clone with kprobe____x64_sys_clone
bpf_text='''
#include <linux/kallsyms.h>

int kprobe__sys_clone(void *ctx)
{
    u64 *mem = (void*)kallsyms_lookup_name("vm_zone_stat");
    if (mem != NULL)
        bpf_trace_printk("mem: %p\\n", mem);
    else
        bpf_trace_printk("Hello, World!\\n");
    return 0;
}
'''
BPF(text=bpf_text, debug=12).trace_print()
```

On Ubuntu 18.04, I got error:

> Running from kernel directory at: /lib/modules/4.15.0-45-generic/build
> clang -cc1 -triple x86_64-unknown-linux-gnu -emit-llvm-bc -emit-llvm-uselists -disable-free -disable-llvm-verifier -discard-value-names -main-file-name main.c -mrelocation-model static -mthread-model posix -fmath-errno -masm-verbose -mconstructor-aliases -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debug-info-kind=limited -dwarf-version=4 -debugger-tuning=gdb -momit-leaf-frame-pointer -coverage-notes-file /usr/src/linux-headers-4.15.0-45-generic/main.gcno -nostdsysteminc -nobuiltininc -resource-dir lib/clang/6.0.0 -isystem /virtual/lib/clang/include -include ./include/linux/kconfig.h -include /virtual/include/bcc/bpf.h -include /virtual/include/bcc/helpers.h -isystem /virtual/include -I /home/ethercflow/work/src/trace/bcc/examples -D __BPF_TRACING__ -I ./arch/x86/include -I arch/x86/include/generated/uapi -I arch/x86/include/generated -I include -I ./arch/x86/include/uapi -I arch/x86/include/generated/uapi -I ./include/uapi -I include/generated/uapi -D __KERNEL__ -D __HAVE_BUILTIN_BSWAP16__ -D __HAVE_BUILTIN_BSWAP32__ -D __HAVE_BUILTIN_BSWAP64__ -O2 -Wno-deprecated-declarations -Wno-gnu-variable-sized-type-not-at-end -Wno-pragma-once-outside-header -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-unused-value -Wno-pointer-sign -fdebug-compilation-dir /usr/src/linux-headers-4.15.0-45-generic -ferror-limit 19 -fmessage-length 181 -fobjc-runtime=gcc -fdiagnostics-show-option -vectorize-loops -vectorize-slp -o main.bc -x c /virtual/main.c
> #if defined(BPF_LICENSE)
> #error BPF_LICENSE cannot be specified through cflags
> #endif
> #if !defined(CONFIG_CC_STACKPROTECTOR)
> #if defined(CONFIG_CC_STACKPROTECTOR_AUTO) \
>     || defined(CONFIG_CC_STACKPROTECTOR_REGULAR) \
>     || defined(CONFIG_CC_STACKPROTECTOR_STRONG)
> #define CONFIG_CC_STACKPROTECTOR
> #endif
> #endif
> 
> #include <linux/kallsyms.h>
> 
> __attribute__((section(".bpf.fn.kprobe__sys_clone")))
> int kprobe__sys_clone(void *ctx)
> {
> 
>     u64 *mem = (void*)kallsyms_lookup_name("vm_zone_stat");
>     if (mem != NULL)
>         ({ char _fmt[] = "mem: %p\n"; bpf_trace_printk_(_fmt, sizeof(_fmt), mem); });
>     else
>         ({ char _fmt[] = "Hello, World!\n"; bpf_trace_printk_(_fmt, sizeof(_fmt)); });
>     return 0;
> }
> 
> #include <bcc/footer.h>
> LLVM ERROR: Program used external function 'kallsyms_lookup_name' which could not be resolved!

And on Centos 7.6, I got a different error:
> Running from kernel directory at: /lib/modules/3.10.0-957.5.1.el7.x86_64/source
> clang -cc1 -triple x86_64-unknown-linux-gnu -emit-llvm-bc -emit-llvm-uselists -disable-free -disable-llvm-verifier -discard-value-names -main-file-name main.c -mrelocation-model static -mthread-model posix -fmath-errno -masm-verbose -mconstructor-aliases -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debug-info-kind=limited -dwarf-version=4 -debugger-tuning=gdb -momit-leaf-frame-pointer -coverage-notes-file /usr/src/kernels/3.10.0-957.5.1.el7.x86_64/main.gcno -nostdsysteminc -nobuiltininc -resource-dir lib/clang/7.0.1 -isystem /virtual/lib/clang/include -include ./include/linux/kconfig.h -include /virtual/include/bcc/bpf.h -include /virtual/include/bcc/helpers.h -isystem /virtual/include -I /root/bcc/examples -D __BPF_TRACING__ -I /lib/modules/3.10.0-957.5.1.el7.x86_64/build/arch/x86/include -I /lib/modules/3.10.0-957.5.1.el7.x86_64/build/arch/x86/include/generated/uapi -I /lib/modules/3.10.0-957.5.1.el7.x86_64/build/arch/x86/include/generated -I /lib/modules/3.10.0-957.5.1.el7.x86_64/build/include -I /lib/modules/3.10.0-957.5.1.el7.x86_64/build/./arch/x86/include/uapi -I /lib/modules/3.10.0-957.5.1.el7.x86_64/build/arch/x86/include/generated/uapi -I /lib/modules/3.10.0-957.5.1.el7.x86_64/build/include/uapi -I /lib/modules/3.10.0-957.5.1.el7.x86_64/build/include/generated -I /lib/modules/3.10.0-957.5.1.el7.x86_64/build/include/generated/uapi -I ./arch/x86/include -I arch/x86/include/generated/uapi -I arch/x86/include/generated -I include -I ./arch/x86/include/uapi -I arch/x86/include/generated/uapi -I ./include/uapi -I include/generated/uapi -D __KERNEL__ -D __HAVE_BUILTIN_BSWAP16__ -D __HAVE_BUILTIN_BSWAP32__ -D __HAVE_BUILTIN_BSWAP64__ -O2 -Wno-deprecated-declarations -Wno-gnu-variable-sized-type-not-at-end -Wno-pragma-once-outside-header -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-unused-value -Wno-pointer-sign -fdebug-compilation-dir /usr/src/kernels/3.10.0-957.5.1.el7.x86_64 -ferror-limit 19 -fmessage-length 181 -fobjc-runtime=gcc -fdiagnostics-show-option -vectorize-loops -vectorize-slp -o main.bc -x c /virtual/main.c -faddrsig
> #if defined(BPF_LICENSE)
> #error BPF_LICENSE cannot be specified through cflags
> #endif
> #if !defined(CONFIG_CC_STACKPROTECTOR)
> #if defined(CONFIG_CC_STACKPROTECTOR_AUTO) \
>     || defined(CONFIG_CC_STACKPROTECTOR_REGULAR) \
>     || defined(CONFIG_CC_STACKPROTECTOR_STRONG)
> #define CONFIG_CC_STACKPROTECTOR
> #endif
> #endif
> 
> #include <linux/kallsyms.h>
> 
> __attribute__((section(".bpf.fn.kprobe__sys_clone")))
> int kprobe__sys_clone(void *ctx)
> {
> 
>     u64 *mem = (void*)kallsyms_lookup_name("vm_stat");
>     if (mem != NULL)
>         ({ char _fmt[] = "mem: %p\n"; bpf_trace_printk_(_fmt, sizeof(_fmt), mem); });
>     else
>         ({ char _fmt[] = "Hello, World!\n"; bpf_trace_printk_(_fmt, sizeof(_fmt)); });
>     return 0;
> }
> 
> #include <bcc/footer.h>
> Disassembly of section .bpf.fn.kprobe__sys_clone:
> kprobe__sys_clone:
> Debug Error: disassembler failed: 0
> 
> bpf: Failed to load program: Invalid argument
> unknown opcode 00
> 
> HINT: The 'unknown opcode' can happen if you reference a global or static variable, or data in read-only section. For example, 'char *p = "hello"' will result in p referencing a read-only section, and 'char p[] = "hello"' will have "hello" stored on the stack.
> 
> Traceback (most recent call last):
>   File "./eg1.py", line 25, in <module>
>     BPF(text=bpf_text, debug=12).trace_print()
>   File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 344, in __init__
>     self._trace_autoload()
>   File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 1090, in _trace_autoload
>     fn = self.load_func(func_name, BPF.KPROBE)
>   File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 384, in load_func
>     (func_name, errstr))
> Exception: Failed to load BPF program kprobe__sys_clone: Invalid argument

These error messages make me feel confused. So I want to know:

1. What causes the difference？
2. Is there any kernel function can't be called and why?
3. How can I get kernel data's addr in a right way?

**Sys info**: Ubuntu 18.04
**Kernel info**: 4.15.0-45-generic
**Kernel header**: /usr/src/linux-headers-4.15.0-45/include/linux/kallsyms.h:21:unsigned long kallsyms_lookup_name(const char *name);
**LLVM**: 6.0.0

**Sys info**: Centos 7.6
**Kernel info**: 3.10.0-957.5.1.el7.x86_64
**Kernel header**: /usr/src/kernels/3.10.0-957.5.1.el7.x86_64/include/linux/kallsyms.h:20:unsigned long kallsyms_lookup_name(const char *name);
**LLVM**: 7.0.1

**Comment by pchaigno** [comment]
Is the newline in the middle of your bpf_trace_printks' first argument a copy-paste error, or is that part of your code too?

**Comment by ethercflow** [comment]
@pchaigno  Oh sorry, It's a copy-paste error, the real code is at the top, and I'll fix this.

**Comment by pchaigno** [comment]
> Is there any kernel function can't be called and why?

Kernel functions cannot be called because they are implemented outside the BPF VM, and as such, cannot be verified as safe.

> How can I get kernel data's addr in a right way?

I'd recommend resolving the address in userspace and passing that information to the BPF program.

**Comment by ethercflow** [comment]
@pchaigno  Thanks a lot, I'll explore the bpf internal implementation to have a deeper understanding of bpf.
