### ISSUE TITLE
kretprobe alias for retval

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#225]
On kprobe, I can declare and use the function arguments. On kretprobe, is there an alias for the return value? I'm currently using ```ctx->ax```, which is platform dependent.

**Comment by drzaeus77** [comment]
That's it for now. It's a fair ask.

**Comment by brendangregg** [comment]
x86_64 ABI references (these just confirm that %ax is correct to use): https://en.wikipedia.org/wiki/X86_calling_conventions#System_V_AMD64_ABI and http://x86-64.org/documentation/abi.pdf

**Comment by brendangregg** [comment]
This should also work for uretprobe

**Comment by brendangregg** [comment]
Extending on #529, perhaps we just need to add a PT_REGS_RVAL alias?

**Comment by brendangregg** [comment]
We now have PT_REGS_RC(ctx). Closing ticket.
