### ISSUE TITLE
 'linux/bpf_common.h' file not found on CentOS 7.6.1810

### ISSUE THREAD

**Issue by oneumyvakin** [iovisor/bcc#2264]
STEPS TO REPRODUCE
```
# cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)
#
# yum install bcc-tools kernel-headers
#
# find / | grep bpf_common
/usr/include/linux/bpf_common.h
#
# /usr/share/bcc/tools/execsnoop
In file included from <built-in>:2:
/virtual/include/bcc/bpf.h:13:10: fatal error: 'linux/bpf_common.h' file not found
#include <linux/bpf_common.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
Traceback (most recent call last):
  File "/usr/share/bcc/tools/execsnoop", line 166, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 318, in __init__
    raise Exception("Failed to compile BPF text")
Exception: Failed to compile BPF text
```

Do I've a miss something?

**Comment by pchaigno** [comment]
I'd expect the `find` command to find something akin to `/usr/src/linux-headers-`uname -r`/include/uapi/linux/bpf_common.h` (in addition to `/usr/include/`). Are you sure the kernel headers were correctly installed? I'm using Ubuntu so it may just be different.

**Comment by yonghong-song** [comment]
By default the bcc relies to find bpf_common.h at linux dev package, e.g., at /lib/modules/$(uname -r)/source/include/uapi/linux/bpf_common.h. Using debug=4, you will find the path /lib/modules/$(uname -r)/source/include/uapi/. Maybe your /lib/modules/.../ does not have `source` directory?

**Comment by oneumyvakin** [comment]
@yonghong-song the reason was package `kernel-devel` was not installed

Think issue can be closed. Sorry for disturbing.

**Comment by yonghong-song** [comment]
@oneumyvakin could you help submit a pull request to update doc?

**Comment by koxt** [comment]
@yonghong-song I could submit PR. But kernel-devel is among dependencies
```
CentOS Linux release 7.6.1810 (Core)

3.10.0-957.21.3.el7.x86_64
```

```
yum deplist bcc-tools | grep dependency
  dependency: /bin/bash
  dependency: /usr/bin/env
  dependency: /usr/bin/python
  dependency: kernel-devel
  dependency: libc.so.6(GLIBC_2.17)(64bit)
  dependency: python-bcc = 0.6.1-2.el7
  dependency: python-netaddr
  dependency: rtld(GNU_HASH)
```
