### ISSUE TITLE
zfsdist not working on Ubuntu 18.10

### ISSUE THREAD

**Issue by myllynen** [iovisor/bcc#2271]
I have a freshly installed Ubuntu 18.10 VM where zfsdist doesn't report anything, I'm pretty this used to work a year or so ago. ext4dist on the same system work just fine.

```
# modprobe zfs
# image=/tmp/tst-loop.zfs.img
# truncate -s 64M $image
# zpool create test $image
# zfsdist-bpfcc &
[1] 14149
# Tracing ZFS operation latency... Hit Ctrl-C to end.

# dd if=/dev/zero of=/test/foo bs=20971520 count=1 conv=fsync
1+0 records in
1+0 records out
20971520 bytes (21 MB, 20 MiB) copied, 1.22327 s, 17.1 MB/s
# dd of=/dev/null if=/test/foo bs=20971520 count=1       
1+0 records in
1+0 records out
20971520 bytes (21 MB, 20 MiB) copied, 0.00840551 s, 2.5 GB/s
# sync ; echo 3 > /proc/sys/vm/drop_caches ;      
# fg
[1]  + running    zfsdist-bpfcc
^C
# uname -r
4.18.0-16-generic
```

**Comment by yonghong-song** [comment]
zfsdist uses kprobes, maybe functionality got changed or get inlined? Please do check whether the kprobe functions get inlined in intended tracing places or not. It may explain the problem.

**Comment by myllynen** [comment]
Yes, something might well have changed, that was my assumption. But how would you check whether the functions get inlined in intended places or not? Thanks.

**Comment by yonghong-song** [comment]
Maybe some zfs experts can help here? @brendangregg @mskarbek @andihit

**Comment by myllynen** [comment]
D'oh, I had unintentionally FUSE ZFS in use, now with the kernel ZFS this works as expected. Closing.
