### ISSUE TITLE
USDT probe provider collisions 

### ISSUE THREAD

**Issue by dalehamel** [iovisor/bcc#2275]
I believe this is mentioned in https://github.com/iovisor/bcc/issues/1527, so perhaps this is a duplicate of that. Either way, I want to write up this problem specifically as I would like to make an attempt to solve it.

In the [current usdt implementation](https://github.com/iovisor/bcc/blob/master/src/cc/usdt/usdt.cc#L296-L320) if you have two tracepoints with the same name, but different provider, there will be a collision and the one found first will be used, hiding the other one.

This will result in unexpected and probably undesired behavior, where the same name may exist in different libraries included by an executable. 

The interface is currently broken, as the [interface doesn't require or accept a provider name](https://github.com/iovisor/bcc/blob/master/src/cc/usdt/usdt.cc#L445), so the collision is inevitable in certain circumstances. 

I propose that the existing signature of  to include the provider name. So the current signature

```
bcc_usdt_enable_probe(void *usdt, const char *probe_name, const char *fn_name)
```

would be changed to:

```
bcc_usdt_enable_probe(void *usdt, const char* provide_name, const char *probe_name, const char *fn_name)
```

Then, the enable_probe function would just need to be modified to search by namespace which should be pretty easy to implement, as this provider name just needs to be propagated. The probe object seems to [already support and store the provider name](https://github.com/iovisor/bcc/blob/master/src/cc/usdt/usdt.cc#L56-L59), so this seems like a small change, aside from it being a potentially breaking API change.

For compatibility, we may want to support signature requiring only 3 arguments at least until the next point release, preserving the current behavior but throwing a deprecation warning. This would give some time for consumers of the API to update to avoid the error, and then I would suggest eventually removing the 3 argument interface.

**Comment by palmtenor** [comment]
Yeah I believe the similar discussion happened on #1524 (new API, backward compatibility, etc.) as well. We mostly did it for attaching but not for enabling.

**Comment by yonghong-song** [comment]
cc @brendangregg 
We may need to modify tools usdt interface as well to really make use of this change. Currently, the usdt looks like `u:<binary_path>:<probe_name>` which does not have provider name.

**Comment by dalehamel** [comment]
Yes definitely, a number of included bcc tools would need to be updated, as well as bpftrace.

**Comment by yonghong-song** [comment]
Any suggestion how to incorporate provider into trace.py, argdist.py, etc?

**Comment by dalehamel** [comment]
Perhaps we could try and be clever, and only require it to be specified if there would be a collision for those tools? This would require using logic like in tplist to check the trace points ahead of time. If only one provider is found it could be used automatically, and if there’s multiple available (a collision) an error could be thrown. 

I’ll need to look closer at the code and come up with some more specific suggestions.

I think that fixing up the tools should be a separate PR, to be completed before deprecating the current API.

**Comment by dalehamel** [comment]
The approach i've done for bpftrace in https://github.com/iovisor/bpftrace/pull/508 is what I intend to do for trace.py, argdist.py, and anything else using USDT probes:

- If the provider isn't specified, but the function only exists on one provider, then the provider can be automatically detected
- If the provider isn't specified and the function exists on multiple providers, then an error must be thrown as the tracepoint is insufficiently specified.
- If the provider is specified, then there is no issue

This should allow for compatibility for cases where it currently works, while also enabling cases where there are currently collisions to work if the provider to use is specified manually.

FYI @yonghong-song ^
