### ISSUE TITLE
How to compile the kprobe C file manually? Or can I use pure C code instead of the python interface?

### ISSUE THREAD

**Issue by adam900710** [iovisor/bcc#2291]
Hi,

I'm trying to craft my own script to probe btrfs' locking concurrency.
The C part isn't that hard to craft but I prefer to compile it before integrating it into bcc python script, especially to solve all compile errors.

Is there any command line I can put into my Makefile to compile the C code?

And is it possible to use C to craft the user space decode part without using python?
As I'm more familiar with C other than python, if there is the interface it would be much easier to me.

Thanks.

**Comment by palmtenor** [comment]
Yes, BCC has both C and C++ interface in addition to Python. You can check the Unit Tests and `example` folder for some hint

**Comment by adam900710** [comment]
Thank you very much.

Got some example, but they still goes the same way by passing the kernel part inside the user space prog.
That's definitely not easy to debug the kernel part.

I understand that the kprobe code should be kept minimal, but it's still not that easy to debug.
So it would be much better for us to have an interface to compile the kprobe part and put it into a Makefile.

**Comment by yonghong-song** [comment]
bcc does not support object file input. If you really want, you can use bcc C API. But you will then need to parse the ELF file by yourself.

**Comment by adam900710** [comment]
I mean to compile kprobe code manually.

Is that possible?
yonghong-song <notifications@github.com> 于 2019年3月29日周五 00:37写道：

**Comment by yonghong-song** [comment]
On Thu, Mar 28, 2019 at 2:12 PM Qu Wenruo <notifications@github.com> wrote:

> I mean to compile kprobe code manually.
>
> Is that possible?
>

It is not possible since bcc does not have interface to take the compiled
byte codes.

**Comment by adam900710** [comment]
I only need to compile, with all bpf compiling requirements.
It's only to debug the kernel c code.

**Comment by yonghong-song** [comment]
technically it is doable. You can hack the bcc source code to find out the compiler flags emitted in loader. dump the source code after rewriter with debug=4, there are a few memory mapped files, you need to place them properly, .... I have not done that by myself.

**Comment by adam900710** [comment]
So bcc users just write the file and check all the compiler error reported by bcc?
No way to utilize things like clangd lsp warning or make command?

That looks very unhandy to me.

**Comment by lcp** [comment]
If you need the separate bpf object file, systemtap bpf could be the alternative solution.

**Comment by adam900710** [comment]
No, I don't need to separate bpf object.
I just need to ensure the C part can be compiled without problem.

Currently I just write a small python script the call `BFP()` to trigger the compiler, and let Makefile to run it.
The problem is, no matter whether I'm using `text=` or `src_file=`, it always shows the file to be `/virtual/main.c`. This makes vim quick fix never work.

Any idea on making the clang backend to pass real file instead of `/virtual/main.c`?

**Comment by adam900710** [comment]
After crafting several scripts, the C code is indeed so simple that there is completely no need to compile it outside of bcc.

Closing this issue.
