### ISSUE TITLE
error: <unknown>:0:0: A call to built-in function 'memset' is not supported

### ISSUE THREAD

**Issue by ethercflow** [iovisor/bcc#2306]
I have to do user-stack unwinding with fp omittd, so I want to read pages from sp to work with libunwind. The test code is below:

``` python
#!/usr/bin/python

from bcc import BPF

bpf_text = """
#include <linux/sched.h>

struct stack_dump {
  int pid;
  char name[16];
  char data[4096 * 4]; // PAGE_SIZE * 4
};

int kprobe__sys_clone(struct pt_regs *ctx)
{
        struct task_struct *task = NULL;
        struct pt_regs *regs = NULL;
        struct stack_dump sd = {};
        void *sp = NULL;
        int ret = 0;

        task = (void*)bpf_get_current_task();
        if (task->mm != NULL) {
                regs = ((struct pt_regs *)(task)->thread.sp0 - 1);
                bpf_probe_read(&sp, sizeof(sp), &regs->sp);
                ret = bpf_probe_read(&sd.data, sizeof(sd.data), sp);
                if (ret < 0) {
                    bpf_trace_printk("bpf_probe_read: %d\\n", ret);
                }
        }

        return 0;
}
"""

BPF(text=bpf_text).trace_print()
```

The program failed with error:

> error: <unknown>:0:0: in function kprobe__sys_clone i32 (%struct.pt_regs*): A call to built-in function 'memset' is not supported.

Enable debug=12, get:

> Running from kernel directory at: /lib/modules/3.10.0-957.10.1.el7.x86_64/source
> clang -cc1 -triple x86_64-unknown-linux-gnu -emit-llvm-bc -emit-llvm-uselists -disable-free -disable-llvm-verifier -discard-value-names -main-file-name main.c -mrelocation-model static -mthread-model posix -fmath-errno -masm-verbose -mconstructor-aliases -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debug-info-kind=limited -dwarf-version=4 -debugger-tuning=gdb -momit-leaf-frame-pointer -coverage-notes-file /usr/src/kernels/3.10.0-957.10.1.el7.x86_64/main.gcno -nostdsysteminc -nobuiltininc -resource-dir lib/clang/7.0.1 -isystem /virtual/lib/clang/include -include ./include/linux/kconfig.h -include /virtual/include/bcc/bpf.h -include /virtual/include/bcc/helpers.h -isystem /virtual/include -I /root/workspace/bcc-recipes/examples -D __BPF_TRACING__ -I /lib/modules/3.10.0-957.10.1.el7.x86_64/build/arch/x86/include -I /lib/modules/3.10.0-957.10.1.el7.x86_64/build/arch/x86/include/generated/uapi -I /lib/modules/3.10.0-957.10.1.el7.x86_64/build/arch/x86/include/generated -I /lib/modules/3.10.0-957.10.1.el7.x86_64/build/include -I /lib/modules/3.10.0-957.10.1.el7.x86_64/build/./arch/x86/include/uapi -I /lib/modules/3.10.0-957.10.1.el7.x86_64/build/arch/x86/include/generated/uapi -I /lib/modules/3.10.0-957.10.1.el7.x86_64/build/include/uapi -I /lib/modules/3.10.0-957.10.1.el7.x86_64/build/include/generated -I /lib/modules/3.10.0-957.10.1.el7.x86_64/build/include/generated/uapi -I ./arch/x86/include -I arch/x86/include/generated/uapi -I arch/x86/include/generated -I include -I ./arch/x86/include/uapi -I arch/x86/include/generated/uapi -I ./include/uapi -I include/generated/uapi -D __KERNEL__ -D __HAVE_BUILTIN_BSWAP16__ -D __HAVE_BUILTIN_BSWAP32__ -D __HAVE_BUILTIN_BSWAP64__ -O2 -Wno-deprecated-declarations -Wno-gnu-variable-sized-type-not-at-end -Wno-pragma-once-outside-header -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-unused-value -Wno-pointer-sign -fdebug-compilation-dir /usr/src/kernels/3.10.0-957.10.1.el7.x86_64 -ferror-limit 19 -fmessage-length 183 -fobjc-runtime=gcc -fdiagnostics-show-option -vectorize-loops -vectorize-slp -o main.bc -x c /virtual/main.c -faddrsig
> #if defined(BPF_LICENSE)
> #error BPF_LICENSE cannot be specified through cflags
> #endif
> #if !defined(CONFIG_CC_STACKPROTECTOR)
> #if defined(CONFIG_CC_STACKPROTECTOR_AUTO) \
>     || defined(CONFIG_CC_STACKPROTECTOR_REGULAR) \
>     || defined(CONFIG_CC_STACKPROTECTOR_STRONG)
> #define CONFIG_CC_STACKPROTECTOR
> #endif
> #endif
> 
> #include <linux/sched.h>
> 
> struct stack_dump {
>   int pid;
>   char name[16];
>   char data[4096 * 4]; // PAGE_SIZE * 4
> };
> 
> __attribute__((section(".bpf.fn.kprobe__sys_clone")))
> int kprobe__sys_clone(struct pt_regs *ctx)
> {
> 
> 	struct task_struct *task = NULL;
> 	struct pt_regs *regs = NULL;
>     struct stack_dump sd = {};
>     void *sp = NULL;
>     int ret = 0;
> 
> 	task = (void*)bpf_get_current_task();
> 	if (({ typeof(struct mm_struct *) _val; __builtin_memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)&task->mm); _val; }) != NULL) {
>  		regs = ((struct pt_regs *)({ typeof(unsigned long) _val; __builtin_memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)&(task)->thread.sp0); _val; }) - 1);
>         bpf_probe_read(&sp, sizeof(sp), &regs->sp);
>         ({ char _fmt[] = "regs->sp: %p, sp: %p\n"; bpf_trace_printk_(_fmt, sizeof(_fmt), ({ typeof(unsigned long) _val; __builtin_memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)&regs->sp); _val; }), sp); });
>         ret = bpf_probe_read(&sd.data, sizeof(sd.data), sp);
>         if (ret < 0) {
>             ({ char _fmt[] = "bpf_probe_read: %d\n"; bpf_trace_printk_(_fmt, sizeof(_fmt), ret); });
>         }
>     }
> 
> 	return 0;
> }
> 
> #include <bcc/footer.h>
> error: /virtual/main.c:26:23: in function kprobe__sys_clone i32 (%struct.pt_regs*): A call to built-in function 'memset' is not supported.

libbcc version: `libbcc.so.0.9.0`

**Comment by yonghong-song** [comment]
> struct stack_dump sd = {};
This won't work. This will exceed 512 byte stack limit.
And this will invoke __builtin_memset. But because the memset memory size is too big, __builtin_memset remains as a function call in the bpf program which will cause verification failure as indicated by the error message. You can try to allocate big data in a map instead of on the stack.

**Comment by ethercflow** [comment]
Thank you @yonghong-song, I'm curious as to where 
> error: <unknown>:0:0: in function kprobe__sys_clone i32 (%struct.pt_regs*): A call to built-in function 'memset' is not supported.

 was printed.

I tried `grep "A call to built-in function" ./ -nr` in the bcc root dir, only got:
> Binary file ./src/cc/libbcc.so.0.9.0 matches

And I want to know how to debug this kind of errors.

**Comment by ethercflow** [comment]
@yonghong-song 

> You can try to allocate big data in a map instead of on the stack.

I don't understand how to allocate big data in a map.  I read [maps](https://github.com/iovisor/bcc/blob/master/docs/reference_guide.md#maps) doc, and didn't find anyway to alloc key or val. Would you please provide some more details?

**Comment by pchaigno** [comment]
@ethercflow You can simply create an array map of a single element to hold this large object:
```c
BPF_ARRAY(sd, struct stack_dump, 1);
```

**Comment by ethercflow** [comment]
@pchaigno Oh, I understand what you mean. Thank you.
