### ISSUE TITLE
fetch kernel stack trace

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#231]
Would like a way to fetch a kernel stack trace (at some point, user-level as well). Different use cases:

- Printing it on an event. Would use it after a bpf_trace_printk().
- Key for maps. Count events by stack trace.
- Value for maps. Eg, printing a bio_strategy() code-path on I/O completion.

**Comment by 4ast** [comment]
we can do 'print on event' without kernel changes via proper flags in perf_even_open(), so we should do that first. stack trace as a key and as value are one of the highest on my todo list. The main gotcha there is stack trace needs to not include the program itself and it's complicated due to jit/interpreter differences.

**Comment by brendangregg** [comment]
Ok; for key/value I'm just expecting the kernel to walk the frame pointers and store these as a list of u64's, and leave symbol resolution to user-level. I'm not expecting function arguments to be part of the stack trace for now.

**Comment by 4ast** [comment]
yes. on kernel side the stack trace will be an array of pointers. user space will need to ksym them.

**Comment by brendangregg** [comment]
FWIW, We keep hitting the a 128 stack frame limit on our Java apps when profiling using perf_events. Would be nice if eBPF could go a bit deeper than 128.

**Comment by 4ast** [comment]
grr. I just implemented it via perf_callchain with existing 127 limit...
What depth is needed?

**Comment by brendangregg** [comment]
Most of the time, 20-30 deep is sufficient, which could be the default (I guess defaults are up to the macro helpers).

If it isn't a big problem now, I'd go with a max of 256. Otherwise we can bump it up later.

**Comment by 4ast** [comment]
bpf_get_stackid() is in net-next. Let's re-purpose this task to add support for in bcc

**Comment by drzaeus77** [comment]
I was thinking the same thing. Step 1 was getting the headers updated. Next will be a new "maps/XXX" type in b_frontend_action.cc, and finally a python support.

**Comment by goldshtn** [comment]
Maybe at the same time you could use some of the code from memleak that parses user symbols so that we have both kernel and user stack support at the same time?

**Comment by brendangregg** [comment]
@4ast since this looks like it is in 4.6-rc1, should we close this ticket?
