### ISSUE TITLE
Detach API for events?

### ISSUE THREAD

**Issue by belgarn** [iovisor/bcc#2331]
Hi,

I want to be able to detach my BPF objects from events. Is the only way to detach from an event to destroy the BPF object? 

I'm trying to avoid to having to create/destroy objects everytime a new program that I want to trace is launched and/or the user change tracing parameters. 

Thanks in advance for any help!

**Comment by belgarn** [comment]
I realize this is more of a question than an issue. Apologies.

**Comment by yonghong-song** [comment]
The best is still to create/destroy objects to cleanly release the memory.
