### ISSUE TITLE
Does BPF provides an API to create per CPU perf ring buffers?

### ISSUE THREAD

**Issue by yzhao1012** [iovisor/bcc#2337]
BPF_PERF_OUTPUT() seems only create one perf ring buffer shared by all CPUs, right?

Is there a syscall API that we can use to create per CPU ring buffer?

**Comment by yonghong-song** [comment]
No. It creates one ring buffer for each cpu. You can check `src/cc/api/BPFTable.cc`.

**Comment by yzhao1012** [comment]
Thanks Yonghong (hope this is the correct name)!

I have a followup question regarding the perf buffer polling behavior. BTW, is there a separate channel for asking questions, other than opening an issue like this?

Given the following C++ code:
BPF_PER_OUTPUT(buffer1);
BPF bpf;
... // Some code to setup the probes etc.
bpf.open_perf_buffer("buffer1", ...);
... // Some other code
auto perf_buffer = bpf.get_perf_buffer("buffer1");
perf_buffer.poll();

When the perf_buffer.poll() is called, will it read items from all of the ring buffers on every CPU? Or it just read one of them and return.

**Comment by yonghong-song** [comment]
It is okay to file issues or directly send email to the mailing list.

yes, it will read items from all the ring buffers on every cpu. Basically your callback function will be called on each cpu's ring buffer.

**Comment by yzhao1012** [comment]
I'll close, as the question is answered.
