### ISSUE TITLE
Package for Alpine

### ISSUE THREAD

**Issue by acj** [iovisor/bcc#2338]
I've submitted a [new package](https://pkgs.alpinelinux.org/packages?name=bcc&branch=edge) to Alpine's edge/testing repository. It's working well for me, but I'm looking for some help to test everything more fully.

#### Quick start

```
$ docker run --privileged -v /lib/modules:/lib/modules -v /usr/src:/usr/src -v /sys:/sys --rm -it alpine:edge
# apk add --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ bcc
```

The install path is `/usr/share/bcc`.

#### Notes

- The package is currently built from BCC 0.8.0 because of #2261.
- Only x86_64 and aarch64 are currently supported. The build is broken on x86 (and some ARM architectures) because of conditional defines for `parser` in test_usdt_args.cc.
- The test suite is disabled because we can't expect privileged access or the necessary kernel config in CI. Are there any tests that can run with ordinary privileges and that would be useful to run during the package build?

**Comment by yonghong-song** [comment]
@acj, that is great! 
For your notes, 
  1. regarding to #2261, not sure what is the correct way to fix it. Do you have a reference how some other projects which has similar issues fixed this issue?
  2. test_usdt_args.cc is just a test, I think this can be changed to be only enabled for supported architectures.
  3. For root requirement, currently, bpf syscalls requires root privilege. There are some discussion to relex this requirement, but probably still some time away. The only thing not needing root privilege is tcpdump style packet filter dumping and probably some cgroup bpf socket programs. In bcc, we probably do not have standalone tests for these.

**Comment by acj** [comment]
Thanks for your helpful reply.

> regarding to #2261, not sure what is the correct way to fix it. Do you have a reference how some other projects which has similar issues fixed this issue?

I've seen projects (e.g., micropython) upload a custom tarball for their releases instead of relying on the auto-generated one that GitHub provides. It would be extra work, but that way maintainers can download pseudo-dependencies like libbpf so that the tarball is self-contained.

Having tagged releases for libbpf would be helpful as well.

> test_usdt_args.cc is just a test, I think this can be changed to be only enabled for supported architectures.

Sounds good. For now, I can skip building the tests since the package build isn't running them anyway.

----

In the meantime, I've successfully built 0.9. At first, I was running into this error in several places:

```
`error: unknown type name '__always_inline'`
```

[Patching any source files](https://github.com/alpinelinux/aports/compare/master...acj:bcc-0.9) that include perf_event.h so that they include `linux/stddef.h` first fixes the build, but is that a reasonable fix? Should it be submitted upstream here (and in libbpf)? And if not, what do you recommend for a real fix?

**Comment by yonghong-song** [comment]
For `__always_inline` issue, it is bcc specific. Could you try whether the following patch fix the issue or not?

```
-bash-4.4$ git diff
diff --git a/src/cc/export/helpers.h b/src/cc/export/helpers.h
index 9c39dfd0..c9ab54c2 100644
--- a/src/cc/export/helpers.h
+++ b/src/cc/export/helpers.h
@@ -33,6 +33,7 @@ R"********(
 #endif
 
 #include <uapi/linux/bpf.h>
+#include <linux/stddef.h>
 #include <uapi/linux/if_packet.h>
 #include <linux/version.h>
 #include <linux/log2.h>
```

If it does fix the issue, could you help submit a pull request? Thanks!

**Comment by acj** [comment]
I get the same build errors with that patch applied. Here is more of the first error in case it's useful:

```
# make
[  0%] Building C object src/cc/CMakeFiles/bpf-shared.dir/libbpf.c.o
In file included from /usr/include/linux/byteorder/little_endian.h:13,
                 from /usr/include/asm/byteorder.h:5,
                 from /usr/include/linux/perf_event.h:20,
                 from /usr/src/app/bcc/src/cc/libbpf.c:28:
/usr/include/linux/swab.h:161:8: error: unknown type name '__always_inline'
 static __always_inline __u16 __swab16p(const __u16 *p)
        ^~~~~~~~~~~~~~~
/usr/include/linux/swab.h:161:30: error: expected '=', ',', ';', 'asm' or '__attribute__' before '__swab16p'
 static __always_inline __u16 __swab16p(const __u16 *p)
                              ^~~~~~~~~
```

**Comment by yonghong-song** [comment]
Sorry. I though it is a kernel missing def error and hence my patch is for bpf program. This is not correct. Looks like it is user space compilation issue.

For libbpf.c failure, most likely, one of the following libbpf headers
```
#include <arpa/inet.h>
#include <errno.h>
#include <fcntl.h>
#include <inttypes.h>
#include <limits.h>
#include <linux/bpf.h>
#include <linux/bpf_common.h>
#include <linux/if_packet.h>
```
recursively included stddef.h while it does not in your environment.

But your fix definitely fine. Please go ahead to submit a pull request.

**Comment by acj** [comment]
No worries -- I should have included more error context in my earlier posts.

One possible include chain is this:

```
linux/perf_event.h -> linux/types.h -> linux/posix_types.h -> linux/stddef.h
```

I found that this small (but ugly) patch against libbpf fixes the build:

```
--- a/include/linux/types.h
+++ b/include/linux/types.h
@@ -5,6 +5,7 @@

 #include <stdbool.h>
 #include <stddef.h>
+#include <linux/stddef.h>
 #include <stdint.h>

 #include <asm/types.h>
```

Otherwise, it includes `/usr/include/stddef.h` instead of the correct linux header. Maybe there's an import path issue in this environment?

**Comment by acj** [comment]
The Alpine maintainers asked me to create a separate package for libbpf instead of relying on the git submodule. That's [done](https://pkgs.alpinelinux.org/packages?name=libbpf&branch=edge).

The update to 0.9.0 is [waiting for review](https://github.com/alpinelinux/aports/pull/7628).

**Comment by yonghong-song** [comment]
Thanks @acj  We will discuss packaging versions for libbpf. Thanks for the packaging built for bcc purpose.

**Comment by mmarchini** [comment]
@ajor maybe we can start using this instead of building our own libbcc for the alpine builds of bpftrace?

**Comment by acj** [comment]
The package has been updated to 0.10.0. If there are no objections, I'll ask the maintainers to move it into the edge/community repo.

**Comment by acj** [comment]
Done -- bcc is in Alpine's community repo now. The libbpf package is there too.
