### ISSUE TITLE
clang librarie missing too makefile missing

### ISSUE THREAD

**Issue by Azaretdodo** [iovisor/bcc#2340]
Hello everybody,

I went to find the clang GitHub also I downloaded the repositorie ;)

For the makefile missing I Don't know how to repair this issue,

If you can repair the makefile missing thank you in advance for each help brought,

Regards.

Dorian ROSSE.

> /opt/bcc/build# cmake .. -DCMAKE_INSTALL_PREFIX=/usr
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Latest recognized Git tag is v0.9.0
-- Git HEAD is 21f24631a28cb308aaa76524b0df34e8f2acb097
-- Revision is 0.9.0-21f24631
-- Performing Test HAVE_NO_PIE_FLAG
-- Performing Test HAVE_NO_PIE_FLAG - Success
-- Performing Test HAVE_REALLOCARRAY_SUPPORT
-- Performing Test HAVE_REALLOCARRAY_SUPPORT - Success
-- Found BISON: /usr/bin/bison (found version "3.0.4") 
-- Found FLEX: /usr/bin/flex (found version "2.6.4") 
-- Found LLVM: /usr/lib/llvm-4.0/include 4.0.1
-- Found LibElf: /usr/lib/x86_64-linux-gnu/libelf.so  
-- Performing Test ELF_GETSHDRSTRNDX
-- Performing Test ELF_GETSHDRSTRNDX - Success
CMake Error at CMakeLists.txt:58 (message):
  Unable to find clang libraries

> -- Configuring incomplete, errors occurred!

> See also "/opt/bcc/build/CMakeFiles/CMakeOutput.log".

> make

> make: *** No targets specified and no makefile found.  Stop.

**Comment by pchaigno** [comment]
Which Linux distribution are you using? Which installation guidelines are you following? Did you try to install libclang-6.0-dev?

**Comment by Azaretdodo** [comment]
I have installed your program there is some days but clang is again missing I am in use ‘ make clang ‘ in llvm-projects GitHub repositorie for install clang if It is again missing I have found the clang download page here :

http://releases.llvm.org/download.html#8.0.0

I will answer you this night if the clang is installed by all step I will follow,

This time now this is the ‘ make clang ‘ command line in working !

Have a nice night,

Regards.


Dorian ROSSE.

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Paul Chaignon <notifications@github.com>
Envoyé : Tuesday, May 7, 2019 8:48:51 PM
À : iovisor/bcc
Cc : Azaretdodo; Author
Objet : Re: [iovisor/bcc] clang librarie missing too makefile missing (#2340)


Which Linux distribution are you using? Which installation guidelines are you following? Did you try to install libclang-6.0-dev?

**Comment by Azaretdodo** [comment]
Sorry but I am very tired I will be sleep…

The ' make clang ' was failed for bcc...

Thank you in advance to wait up than 1 Week please,

Have a nice night,

Regards.


Dorian ROSSE.

**Comment by pchaigno** [comment]
Please follow the guidelines for your distribution of you want to install from sources: https://github.com/iovisor/bcc/blob/master/INSTALL.md.

**Comment by Azaretdodo** [comment]
You Need to wait some days for my return on my Linux server firstly I will try the link I advice then I follow your install if It is again missing clang

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by tuilagio** [comment]
@Azaretdodo Please take a look at install tool:
```bash
# For bionic
sudo apt-get -y install bison build-essential cmake flex git libedit-dev \
  libllvm6.0 llvm-6.0-dev libclang-6.0-dev python zlib1g-dev libelf-dev
```

The "\" symbol can make your terminal misunderstand (as happened with me just a few minutes ago) and install the first half command before "\" and the prompt wait for the rest `libllvm6.0 llvm-6.0-dev libclang-6.0-dev python zlib1g-dev libelf-dev`.

**Comment by tuilagio** [comment]
@Azaretdodo #offtopic
How is the experience bcc on RHEL? I am using xubuntu for developing purpose and it seem to be alright.

**Comment by Azaretdodo** [comment]
It is a Ubuntu server become red hat by rpm installing now I can do nothing on them it begun install rpm by us on other Linux system

It is good it do leave my seek of IT lol

Télécharger Outlook pour Android<https://aka.ms/ghei36>
________________________________

**Comment by ghpgmer** [comment]
Hi I am running into a similar issue.

I have Ubuntu18.04-bionic. I ran into bcc cmake and had clang-6 initially. Some posts suggested to install clang-10, which I did. Now cmake fails with the error below.

I tried with git clone https://github.com/iovisor/bcc.git and it failed. I also tried by downloading latest release tar.gz, but its the same issue now.

Please let me know how to fix this. Thanks 

-----------------------------------------------------
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Latest recognized Git tag is HEAD-HASH-NOTFOUND
-- Git HEAD is GITDIR-NOTFOUND
-- Revision is EAD-HASH-NOTFOUND-GITDIR-N
-- Performing Test HAVE_NO_PIE_FLAG
-- Performing Test HAVE_NO_PIE_FLAG - Success
-- Performing Test HAVE_REALLOCARRAY_SUPPORT
-- Performing Test HAVE_REALLOCARRAY_SUPPORT - Success
-- Found BISON: /usr/bin/bison (found version "3.0.4") 
-- Found FLEX: /usr/bin/flex (found version "2.6.4") 
-- Found LLVM: /usr/lib/llvm-10/include 10.0.0
-- Found LibElf: /usr/lib/x86_64-linux-gnu/libelf.so  
-- Performing Test ELF_GETSHDRSTRNDX
-- Performing Test ELF_GETSHDRSTRNDX - Success
CMake Error at CMakeLists.txt:80 (message):
  Unable to find clang libraries


-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/bcc/build/CMakeFiles/CMakeOutput.log".

-----------------------------

**Comment by mehdipourfar** [comment]
Open `CMakeLists.txt` file and change
`set(CLANG_SEARCH "/opt/local/llvm/lib;/usr/lib/llvm-3.7/lib;${LLVM_LIBRARY_DIRS}")`
to:
`set(CLANG_SEARCH "/opt/local/llvm/lib;/usr/lib/llvm-7/lib;${LLVM_LIBRARY_DIRS}")`

**Comment by trivalik** [comment]
In my case I used LLVM11 on ubuntu 20.08.
Additional to @mehdipourfar hint, I installed `sudo apt install libclang-11-dev`, before I installed `libclang-common-11-dev`, not sure if necessary. But with this the `cmake` part runs through.

**Comment by therealak12** [comment]
In case you're following [the installation docs](https://github.com/iovisor/bcc/blob/master/INSTALL.md#ubuntu---binary) you install a specific version of libllvm such as libllvm-14. Open the `CMakeLists.txt` file and force the llvm version as described [here](https://github.com/iovisor/bcc/issues/2272#issuecomment-755277823).

**Comment by Azaretdodo** [comment]
Hello I am back on Ubuntu for bcc finally I don't happen any errors thus I close the ticket
