### ISSUE TITLE
How to test BPF C code?

### ISSUE THREAD

**Issue by yzhao1012** [iovisor/bcc#2342]
Hi All and the BCC maintainers,

I am looking for a way to test BPF C code as normal application code. The major issue is granting root privilege to the process calling BPF::init/attach_*() etc.

We thought about to let Jenkins run as root user, but that means when we running the test on local dev machine, we need to manually add 'sudo ...' to the test command. This seems only solve the half of the program.

We also thought about starting a VM and run the test inside the VM. But have not figured out how to do that.

Any suggestions or tips?

Thanks!

**Comment by alban** [comment]
We had a [CI setup with rkt on SemaphoreCI](https://kinvolk.io/blog/2017/02/using-custom-rkt-stage1-images-to-test-against-various-kernel-versions/) previously. gobpf uses this in [semaphore.sh](https://github.com/iovisor/gobpf/blob/master/semaphore.sh), but it needs some fixing.
/cc @schu

**Comment by yzhao1012** [comment]
Nice! @alban Thanks again, Alban, this will be super helpful!

You already saved a ton of my time in https://github.com/iovisor/bcc/issues/1875! :)

**Comment by yzhao1012** [comment]
We ends up granting docker containers ran by our Jenkins worker (running as 'root') with --privileged. We also uses 'bazel test', and needs --strategy=TestRunner=standalone to disable bazel's sandbox.
