### ISSUE TITLE
Is there a list of syscall can be probed by eBPF?

### ISSUE THREAD

**Issue by yzhao1012** [iovisor/bcc#2351]
Is https://github.com/torvalds/linux/blob/master/arch/x86/entry/syscalls/syscall_64.tbl the complete list?

We encountered a case where we try to probe send(), but it seems it's either not really a syscall, or it does not have the right interface for the bpf code to work.

**Comment by sauercrowd** [comment]
You should be able to probe all available syscalls, as far as I'm aware there is no limit.
What may be the issue is that glibc uses a different underlying syscall, I gave that a quick try with this code

```c
#include <sys/socket.h>                                                                                                   
                                                                                                                          
int main(void){                                                                                                           
        char *buffer = "hello";                                                                                           
        send(111, buffer, 6, 0);                                                                                          
} 
```

```bash
$ strace ./a.out                                                                                          
execve("./a.out", ["./a.out"], 0x7ffda1ffe2d0 /* 56 vars */) = 0                                                          
....                                                       
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3  # hello glibc                                         
...         
sendto(111, "hello\0", 6, 0, NULL, 0)   = -1 EBADF (Bad file descriptor)                                                  
...                                                                                       
``` 

So it looks like the syscall used, at least in this case, is actually `sendto` instead of `send`.
Maybe probing `sendto` is worth a try

**Comment by yzhao1012** [comment]
I think I got confused, and thought send() is a syscall, but in reality it's not really a syscall but a wrapper of the sendto() syscall, right?

**Comment by sauercrowd** [comment]
You're completely right, both `send` and `sendto` exist as a syscall. But the underlying c library, glibc in this case, uses `sendto` in both c functions.

Here a small excerpt from the `send` [manpage](https://linux.die.net/man/2/send)
>Also, the following call
`send(sockfd, buf, len, flags);`
is equivalent to
`sendto(sockfd, buf, len, flags, NULL, 0);`

So basically `send` is a subset of the functionality that `sendto` provides, and glibc just decided in this case to then just go with the `sendto` syscall in both cases

**Comment by yzhao1012** [comment]
Thanks for the help!
