### ISSUE TITLE
map.increment() returns the value before/after increment?

### ISSUE THREAD

**Issue by yzhao1012** [iovisor/bcc#2353]
It seems trivial to do so, which would saves the need to have another lookup when we need to obtain the value before/after increment.

Compared with:
val = map.lookup();
(*val)++;

val = map.increment(key);

Seems clearer and less error prone.

**Comment by yonghong-song** [comment]
First, 
  val = map.lookup();
  (*val)++;
is not quite right. it needs to
  val = map.lookup();
  if (val) (*val)++;
to avoid verifier error.

Second, you may not get a value with map.increment(key), e.g., if hash lookup failed. So we will not be able to return a valid "val".

**Comment by yzhao1012** [comment]
Thanks Yonghong for the tip! The null check is included.

It's a good point that increment() when the key does not exist is undefined. I see 2 possible fixes, neither of them is perfect:
1. Let increment() return NULL, if the key does not exist; or return pointer to the current key's value.
2. Add a new function init_and_increment(key, zero, increment_amount), if the key does not exist, init it to zero; otherwise, increment it with increment_amount.

I still see 2 relevant issues here: 
* Relevancy to general users. #1 probably is less intrusive to users and therefore easier to adopt; #2 could be of general interests, but I have no data.
* https://github.com/iovisor/bcc/issues/1521 Race condition of operations like increment and read value (as after increment, the obtained value might be already incremented again by another operation). #2 probably would be useful as it groups the operation of initialization + increment, which can be made atomic if it's decided that atomic operations should be implemented. On the other hand, map.init(key, zero), which does nothing if the key already exists, plus map.comp_and_wap(key, prev_value, incremented_value), would be sufficient as well, and would be superior.

But I just realized that, right now we are more concerned with the atomicity of lookup_or_init(), and less so about increment(). So I'd close this one.
