### ISSUE TITLE
BCC compilation macro

### ISSUE THREAD

**Issue by yzhao1012** [iovisor/bcc#2354]
When BCC compiles the C code, does it define any MACRO?

I am wondering if I can use that in the header/source file to enable sharing header between BPF C code and other non BPF code (C or C++).

**Comment by palmtenor** [comment]
It has standard predefined macros from the compiler. BCC doesn't do anything special. However, you can pass in your own CFlags to your BPF code and gate against whatever Macro you prefer accordingly.
