### ISSUE TITLE
attach_kprobe/kretprobe return number of attached probes

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#236]
For information, it could be useful for these functions to return the number of probes actually attached. When using unfamiliar event_re's, I'm not sure if it has matched 0 probes, 1 probe, or how many. Tools where I'm using attach_k[ret]probe, I'd likely print "attached to %d functions..." on initialization.

**Comment by tuxology** [comment]
Is it as simple as a `cnt += 1` whenever [`attach_kprobe`] (https://github.com/iovisor/bcc/blob/4afb3f87af57b3a1a160172efb63b82417143820/src/python/bcc/__init__.py#L496) is a success for each `line` event in this function? Am I right?

**Comment by drzaeus77** [comment]
Well, it's not that simple. If you'll notice, the return type of attach_kprobe is already taken (return self). The use case for that was to be able to do:

```python
BPF(text="").attach_kprobe(...).trace_print()
```

So, I see two options:
1. Add a new helper to BPF which just `returns len(open_kprobes)`
2. Deprecate `return self` and replace it with `return len(open_kprobes)` which gives the global count, or `cnt += 1; return cnt` as you described.

I am impartial as I don't really use either one, so votes welcome.

**Comment by brendangregg** [comment]
(1) seems fine.

**Comment by tuxology** [comment]
I am also inclined towards (1). I can take this if nobody is onto this feature.

**Comment by drzaeus77** [comment]
Go for it!
