### ISSUE TITLE
How to deal with uprobe process in docker container from host?

### ISSUE THREAD

**Issue by iAklis** [iovisor/bcc#2363]
I run a docker container(`docker run -it fedora:26 /bin/bash`) which runs bash.

![image](https://user-images.githubusercontent.com/7456486/57979020-01ed2c80-7a4a-11e9-948c-006bd6bb9949.png)

`18f3fa58fad7` is the docker container.   I installed bcc on hosts.

How could I make tool like bashreadline work for bash in container well as the bash on host.

**Comment by yonghong-song** [comment]
could you check whether uprobe is installed properly on the host or not? For early version, you can check debugfs /sys/kernel/debug/tracing/uprobe_events, newer kernel you can check using kernel `bpftool perf`. Maybe you want to try to use debugfs uprobe_events directly to check whether it works or not? May also check whether thee above /bin/bash has "readline" function or not?

**Comment by iAklis** [comment]
@yonghong-song  
Thank you for your reply.

I checked uprobe_events found uprobe_events worked (in uprobe_events). But there is nothing printed.

I can use ltrace to attach the bash(etc pid 31571 below), but uretprobe not worked.

Docker version 18.09.2, build 6247962
Storage Drive: aufs
Host Linux kernel version: 4.15.0-46-generic

![image](https://user-images.githubusercontent.com/7456486/58004859-c8cebe00-7b16-11e9-83e1-6716485b597d.png)

**Comment by iAklis** [comment]
I run the zlim/bcc attached one container for tracing the bash.

```
docker run -it \
    --pid=container:4b19b2305663 \
    --net=container:4b19b2305663 \
    --privileged \
    --cap-add sys_admin \
    --cap-add sys_ptrace \    
zlim/bcc
```

![image](https://user-images.githubusercontent.com/7456486/58020989-5375e400-7b3c-11e9-85c9-f965a5256a68.png)

But nothing got.

**Comment by iAklis** [comment]
I discovered was related to Storage Drive.

**Comment by yzhao1012** [comment]
Re: the last update

@iAklis 
Could you provide more details on what is "related to Storage Drive"? I've seen uprobe attached to overlay file path not working, while uprobe attached to the host file is working.

**Comment by palmtenor** [comment]
If by overlay you mean `overlayfs` then you need https://github.com/torvalds/linux/commit/f0a2aa5a2a406d0a57aa9b320ffaa5538672b6c5

**Comment by mgale** [comment]
@palmtenor or @yzhao1012 Does anyone have any more information on this topic? 
My binary works on the host os but only sees events from the host os, not from the container.
My binary works in the container but only sees events from inside the container, not from the host.

I would like to run the binary inside the container and capture events from the host (outside the container).

**Comment by edenzhong7** [comment]
@mgale uprobes are made of the program file inode, the instruction offset, the list of related actions and the replaced instruction code. When you create a probe, it is added to a specific binary tree. it means you can't use a binary copy, but you can attach to the binary in container's overlayfs, use `docker inspect <container id / name>` to get all layer, like:
