### ISSUE TITLE
cachestat cannot stop within script

### ISSUE THREAD

**Issue by sztsian** [iovisor/bcc#2374]
Given cachestat is installed as /usr/share/bcc/tools/cachestat, when I use it inside a script, like 

> cat > testint.sh <<EOF
#!/bin/bash
/usr/share/bcc/tools/cachestat &
tpid=\\$!
sleep 4
/usr/bin/kill -INT \\$tpid
ps -ef | grep \\$tpid
EOF

if you execute this script  testint.sh, I can see cachestat is still running after the kill line. This should be fixed to make it work within shell scripts.

**Comment by yonghong-song** [comment]
Not sure whether this is a bcc issue, or a python issue. Any idea what is possible reason here?

**Comment by palmtenor** [comment]
Maybe that's due to that the script is designed to interact with keyboard instead of signals? See https://github.com/iovisor/bcc/blob/master/tools/cachestat.py#L120

**Comment by olsajiri** [comment]
running cachestat like this forces bash to redirect standard input
to /dev/null and ignore SIGINT (for some job control reasons),
so it won't ever catch the KeyboardInterrupt exception

SIGTERM should work ok

**Comment by sztsian** [comment]
> running cachestat like this forces bash to redirect standard input
> to /dev/null and ignore SIGINT (for some job control reasons),
> so it won't ever catch the KeyboardInterrupt exception
> 
> SIGTERM should work ok

Thanks. I'll try SIGTERM.

**Comment by sztsian** [comment]
SIGTERM can fulfill my need. So I'm closing this.
Thanks.
