### ISSUE TITLE
USDT bpf_readarg_* functions are not generated when compiling BPF programs from a src_file

### ISSUE THREAD

**Issue by tobiasblass** [iovisor/bcc#2385]
To access the arguments of an USDT probe, bcc generates a bunch of helper functions that parse the `.note.stapsd` ELF section and take the arguments from the correct registers. In the python implementation, this is done  [here](https://github.com/iovisor/bcc/blob/master/src/python/bcc/__init__.py#L309-L319)

As you can see by the if statement, this is only done if the BPF program is passed as a string (using the `text` argument), but not if the BPF program is passed as a file (using the `src_file` argument). Using `bpf_usdt_readarg` in such a file therefore fails with a _function not defined_ error.

Is this an oversight, or is there a reason for this asymmetry?

----
Minimal example:
Running `test.py` fails with
```
bpf: Failed to load program: Invalid argument
0: (bf) r2 = r10
1: (07) r2 += -8
2: (b7) r3 = 8
3: (85) call unknown#-1
BPF_CALL uses reserved fields
```
unless `_bpf_readarg_test_1` is defined by hand in the BPF program.

test.py:
```Python
#!/usr/bin/env python3
import bcc

usdt = bcc.USDT(path='./test')
usdt.enable_probe(probe='main', fn_name='test')
bpf = bcc.BPF(src_file='test.bpf', usdt_contexts=[usdt])
bpf.trace_print()
```

test.c:
```C
#include<sys/sdt.h>
int main(int argc, char **argv) {
	DTRACE_PROBE1(test,main,argv[0]);
	return 0;
}
```

test.bpf:
```C
#include <uapi/linux/ptrace.h>
// SPDX-License-Identifier: GPL
#define BPF_LICENSE GPL

/* Uncomment this to define the readarg-function by hand. This fixes the issue,
   which proves that this function is indeed the culprit. */
//#define define_readarg_by_hand

#ifdef define_readarg_by_hand
static int _bpf_readarg_test_1(struct pt_regs *ctx, void *dest, size_t len) {
	if (len != sizeof(char*)) return -1;
        /* Adjust the register depending on the output of readelf -n test */
	*(void**)dest = (void*)ctx->ax;
	return 0;
}
#endif

int test(struct pt_regs *ctx) {
    void *ptr;
    char argv0[64];
    bpf_usdt_readarg(1, ctx, &ptr);
    bpf_probe_read_str(argv0, sizeof argv0, ptr);
    bpf_trace_printk("%s\n", argv0);
    return 0;
}
```

**Comment by yonghong-song** [comment]
This probably due to initial implementation.
```
        src_file = _assert_is_bytes(src_file)
        hdr_file = _assert_is_bytes(hdr_file)
        text = _assert_is_bytes(text)
......
        if text:
            ctx_array = (ct.c_void_p * len(usdt_contexts))()
            for i, usdt in enumerate(usdt_contexts):
                ctx_array[i] = ct.c_void_p(usdt.get_context())
            usdt_text = lib.bcc_usdt_genargs(ctx_array, len(usdt_contexts))
            if usdt_text is None:
                raise Exception("can't generate USDT probe arguments; " +
                                "possible cause is missing pid when a " +
                                "probe in a shared object has multiple " +
                                "locations")
            text = usdt_text + text
```

There is no reason why we cannot support with src_file. Since you are investigating this, maybe you can help fix this?

**Comment by palmtenor** [comment]
I guess this is more of a philosophical decision. You are going to need to provide the USDT Context (which includes your probe function name etc.) to get these generated. I guess the idea is that if you are using an source file then that source file should have everything included already.

**Comment by tobiasblass** [comment]
> Since you are investigating this, maybe you can help fix this?

Of  course. I only wanted to make sure this is actually a bug before I spend too much time on the issue. 

>  I guess the idea is that if you are using an source file then that source file should have everything included already.

Is there a way to provide this information in the (BCC-)C source file? I thought that a python/lua/C++ program is required that performs the setup from userspace.
