### ISSUE TITLE
__LINE__ macro is not consistent with the C file

### ISSUE THREAD

**Issue by yzhao1012** [iovisor/bcc#2388]
I suppose there is additional process done by BCC compiler during the loading process, but could it be improved to the point that the macro is the actual line number in the file?

This is for printing out debug information with bpf_trace_printk().

**Comment by yonghong-song** [comment]
bcc rewriter will change the source code and that is why __LINE__ is not consistent. You can use debug=4 to print out the source code. This way, the __LINE__ number should correspond to debug=4 outputed C file.

**Comment by yzhao1012** [comment]
debug=4 is for python API, right? We have been using BPF C++ API exclusively, what does debug=4 correspond to in C++ API?

**Comment by palmtenor** [comment]
First argument of `BPF` constructor (`flag`) is the debug flag

**Comment by yzhao1012** [comment]
Thanks Teng and Yonghong!

For BPF class, I cannot seem find any API that can print the rewritten C text with debug=4 in [1].

[1] https://github.com/iovisor/bcc/blob/master/src/cc/api/BPF.h

**Comment by palmtenor** [comment]
As said, just construct `BPF` object with [`flag` argument](https://github.com/iovisor/bcc/blob/master/src/cc/api/BPF.h#L49) being bitwise or of any of [these flags](https://github.com/iovisor/bcc/blob/master/src/cc/bpf_module.h#L43)

**Comment by yzhao1012** [comment]
Thanks Teng!

I tried what you said with ebpf::DEBUG_PREPROCESSOR, and it printed out the processed C code.

If I want to save the text some where, where can I extract it from the BPF class' API? Something like:
BPF bpf;
bpf.init(...);
bpf.PrintPreProcessedSource();  // Returns the text printed with DEBUG_PREPROCESSOR?

**Comment by palmtenor** [comment]
No, its from clang lib and it prints to stdout only

**Comment by yzhao1012** [comment]
Thanks Teng!

Close as the issue is clarified.
