### ISSUE TITLE
Newbie question: does the probe runs on the same CPU as the one that runs the syscall by traced by the probe?

### ISSUE THREAD

**Issue by yzhao1012** [iovisor/bcc#2390]
Hi All,

If I attach a probe for write(), when the probe code is executed, it's on the same CPU that runs the write() syscall, right?

**Comment by palmtenor** [comment]
Probe BPF program runs on wherever the thing triggered it is running on, in its virtual memory space.

**Comment by yzhao1012** [comment]
Thanks Teng!
