### ISSUE TITLE
capable: move TID and INSETID columns to -x

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#2392]
People have added extra columns to capable, and the default output is now > 80 chars. I can no longer use capable:

- in slide decks
- in blog posts
- in books
- in emails
- in ticketing systems

In each case, things go wrong with output > 80 chars. (e.g., I just copy-n-pasted some capable output in the book I'm writing, and it's wrapped horribly, and the publisher does not allow small font sizes to accommodate).

It's ok if you really really need to go beyond 80 chars, but I don't think TID and INSETID columns must be in the default output. I'd move them to a -x option (for extra fields).

I did mention this in https://github.com/iovisor/bcc/blob/master/CONTRIBUTING-SCRIPTS.md , but maybe that isn't enough. I'll add a ticket for doing a test suite for checking default output of these tools is < 80 chars, and if a PR exceeds 80 chars, it will get rejected and require an "is this really necessary?" override to continue.

CC @pothos @arighi

**Comment by pothos** [comment]
Sure, I've submitted a change.
