### ISSUE TITLE
Does bcc get function trace including inline functions?

### ISSUE THREAD

**Issue by mudongliang** [iovisor/bcc#2393]
I am a newbie to kernel tracing mechanism. I first tried ftrace and applied function plugin to obtain the kernel function trace for one or multiple system calls. But as shown in the results, it cannot record all the inline functions no matter CONFIG_DYNAMIC_FTRACE or not.

Does bcc trace kernel functions including inline functions? Or is it possible to trace all kernel functions including inline functions?

**Comment by palmtenor** [comment]
If a Kernel function is inlined in general you won't be able to trace it. In fact, more often functions are inlined only in certain call sites, making that you can still attach the kprobe but missing those inlined call sites. This is exactly the reason why Tracepoint is preferred over kprobe in Tracing tools.

That being said, you can still kprobe into a specific Kernel address, which you can figure out for a specific Kernel build and you still get all register context etc. But I wouldn't recommend that...

**Comment by mudongliang** [comment]
If I don't care about inline function, and only record the executed function list(in order) for one or multiple system calls, which tracing tool (e.g., ebpf, ftrace) could or is more suitable to complete this task?

**Comment by palmtenor** [comment]
What do you mean by `the executed function list(in order) for one or multiple system calls`? Do you mean stack trace?

**Comment by mudongliang** [comment]
I don't mean stack trace. Stack trace is the active stack frames at a certain point in time during the execution of a program. However, I need all the executed function during the runtime. For example,

If I run one mmap syscall, Linux kernel will run many kernel functions through sys_mmap,
```
sys_map
    Func A
         Func B
    Func C
    Func D
```
I need this function list with indentations that show the call relationship.

**Comment by mudongliang** [comment]
I found one temporary solution in perf_tools: funcgraph. If I set the function string with "SyS_XXX", it could show the executed function list.
