### ISSUE TITLE
Overflow events in perf buffer are silently dropped?

### ISSUE THREAD

**Issue by yzhao1012** [iovisor/bcc#2396]
Hi All,
We noticed that when calling BPFPerfBuffer::perf_submit(), if the perf buffer capacity is small enough that the perf_submit() call is known to overflow the perf buffer, then the events are silently dropped (at least loss callback is not called).

Say I have a perf buffer with 8 pages in size, when I submit 20 events to the perf buffer, all events submitted after the 8th events seems just disappear.

Is this expected?

PS: we are changing our code to be more efficient in using the perf buffer memory, and we were wasting a lot of memory before this.

**Comment by yonghong-song** [comment]
Typically, for each cpu, there is a perf event ring buffer and there is a user thread to read the buffers. If you have a burst of perf_submit() and user thread is not called to drain the ring buffer, some records may be lost. So you are right. In such cases, you probably need to a little large ring buffer.

Typically ring buffer should not be that big unless it is intensely used (e.g., every packet for millions packets per second ...).

**Comment by sfc-gh-gshe** [comment]
Just wondering if kernel provide any signal to let user space program know the overflow already happens.
