### ISSUE TITLE
Forked process run into failure when detaching kernel probes

### ISSUE THREAD

**Issue by yzhao1012** [iovisor/bcc#2406]
The code roughly does:
Attach kprobes
fork and exec another binary
child process exit
Detach kprobes in parent

In the end the parent process runs into failure when detaching kprobes.

Is this expected? Can this be avoided?

**Comment by yonghong-song** [comment]
Any test case to exhibit the issue?
Is the parent process still able to get events after child process exiting?
Maybe the parent perf_event fd gets closed when child did `exec`?

**Comment by yzhao1012** [comment]
Probably some mistake on my part. But no longer have any records of this particular issue.
Close.
