### ISSUE TITLE
Is there an API to report the utilization of a perf buffer?

### ISSUE THREAD

**Issue by yzhao1012** [iovisor/bcc#2415]
Hi All,

We are considering adaptive polling, i.e., increasing polling frequency when the perf buffer utilization is approaching its capacity. We need some way to report the used size of a perf buffer to user space code.

Is there such an API? I could not find relevant on from BPFTable.h.
If no, are you open to adding such an API? We might contribute if possible.

**Comment by yonghong-song** [comment]
> Is there such an API? I could not find relevant on from BPFTable.h.
No. There is no such API. The best place to check is probably in perf_reader.c,
if PERF_RECORD_LOST appears, some records are lost.

On the other hands, whenever user space drains the records, it can calculate the
buffer utilization to decide whether the ring buffer size could be shrinked.

Doing munmap and mmap may get some records lost.

We could make this adaptive approach as a config option (e.g., a parameter to perf_reader_new()).
So it won't penalize users who do not want this.

**Comment by yzhao1012** [comment]
> On the other hands, whenever user space drains the records, it can calculate the
> buffer utilization to decide whether the ring buffer size could be shrinked.

I think you imply that we can use the read data as an indirect signal of the utilization of the perf buffer, which makes perfect sense.

Thanks!
