### ISSUE TITLE
A bunch of warnings and probably nitpicks during build.

### ISSUE THREAD

**Issue by Earnestly** [iovisor/bcc#242]
This is just a collection of warnings I encountered, they're pretty harmless but exist here more as documentation/google fodder.

First during the cmake process there's a warning about creating a symlink (is this a legacy thing which was changed and cmakelists wasn't updated to reflect it?).  This seems harmless and doesn't seem to cause an issue.
```
-- Latest recognized Git tag is v0.1.6
-- Git HEAD is 15d1f3b4c80069e482131577721d60f731dd3808
-- Revision is 0.1.6-15d1f3b4
-- Found BISON: /usr/bin/bison (found version "3.0.4") 
-- Found FLEX: /usr/bin/flex (found version "2.5.39") 
-- Found LLVM: /usr/include
failed to create symbolic link '/home/earnest/build/lab/bcc-git/src/bcc/src/python/bcc' because existing path cannot be removed: Is a directory
```

Good old deprecation warnings.  I'm running a fairly recent userspace so switching away to the new API might not be feasable for the targets you wish to support just yet until they catch up.
```
[ 23%] [FLEX][Lexer] Building scanner with flex 2.5.39
lexer.ll:110: warning, -s option given but default rule can be matched
[ 28%] [BISON][Parser] Building parser with bison 3.0.4
parser.yy:19.9-17: warning: deprecated directive, use ‘%define api.namespace ebpf::cc’ [-Wdeprecated]
 %define namespace "ebpf::cc"
         ^^^^^^^^^
parser.yy:19.9-17: warning: %define variable 'api.namespace' requires '{...}' values [-Wdeprecated]
 %define namespace "ebpf::cc"
         ^^^^^^^^^
parser.yy:20.9-25: warning: %define variable 'parser_class_name' requires '{...}' values [-Wdeprecated]
 %define parser_class_name "BisonParser"
         ^^^^^^^^^^^^^^^^^
```

```
[ 66%] Building CXX object src/cc/frontends/b/CMakeFiles/b_frontend.dir/lexer.ll.cc.o
/home/earnest/build/lab/bcc-git/src/bcc/src/cc/frontends/b/lexer.ll.cc: In member function ‘virtual int ebpf::cc::Lexer::yylex()’:
/home/earnest/build/lab/bcc-git/src/bcc/src/cc/frontends/b/lexer.ll.cc:751:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
    for ( yyl = 0; yyl < yyleng; ++yyl )
```

**Comment by drzaeus77** [comment]
For the symbolic link, this is happening because you are running cmake in the source directory, I believe. I always suggest (and the INSTALL.md says this) to use a ./build directory separate from the source tree. The warning should go away then.

Deprecation warnings indeed will have to be lived with, as you can see from #6 some colleagues already complained about their Ubuntu 12.04 builds breaking.

The signed warning comes from generated code, I don't see an easy way to fix that up.

**Comment by Earnestly** [comment]
That's a fair response.  I'm aware of using a build directory but as this a package it shouldn't be necessary.  The warning is then perhaps just the result of an assumption instead of proper control flow.

I just hope those warnings for deprecation don't cause issues as we move forward (we don't use old software here), as there are already projects who are essentially vendor locked due to the inhertia of certain distributions.

Thanks for commenting on this.  I'll probably close it as a reference for anyone searching for the same thing, it should pop up on most search engines.
