### ISSUE TITLE
A Few Questions About Pinned Maps

### ISSUE THREAD

**Issue by HousedHorse** [iovisor/bcc#2426]
Hi all. Just had a few quick questions regarding support for pinned maps, which I noticed has recently been added to the Python API.

1. Is it possible to pin maps from a Python script?
2. Is it possible to load in arbitrary pinned maps on the fly in a BPF program? For example suppose I wanted to load a different pinned map based on what process is making a system call.

Any assistance would be appreciated.

**Comment by yonghong-song** [comment]
> Is it possible to pin maps from a Python script?

Currently, there is no API for this. Maybe you can contribute.

> Is it possible to load in arbitrary pinned maps on the fly in a BPF program? For example suppose I wanted to load a different pinned map based on what process is making a system call.
You can. bcc is compiling the bpf program on the fly. Like many of our bpf programs in bcc tools, you can tweak bpf programs right before compilation and loading into the kernel.

**Comment by HousedHorse** [comment]
Thanks for the reply. Regarding the second point, that's not quite what I meant; I'm pretty sure the behavior I'm looking for isn't possible currently. I'll certainly contribute if I can.
