### ISSUE TITLE
/usr/lib64 seems to be hardcoded.

### ISSUE THREAD

**Issue by Earnestly** [iovisor/bcc#243]
Looking at the `CMakeList.txt` I am having a hard time trying to figure out how to prevent it from using the `lib64/` library install paths by default.

Would you perhaps consider switching to [GNUInstallDirs](http://cmake.org/cmake/help/v3.3/module/GNUInstallDirs.html) instead?

With that change I could simply use `-DCMAKE_INSTALL_LIBDIR{,_FULL}` to define it as `/usr/lib`.

**Comment by drzaeus77** [comment]
Please test and close if successful. Thanks!

**Comment by Earnestly** [comment]
Yup, this solves the issue nicely.  Thank you for your efforts.
