### ISSUE TITLE
examples:cpp/PyPerf doesn't work!

### ISSUE THREAD

**Issue by 201341** [iovisor/bcc#2442]
I am trying to use this tool, but it doesn't work! my python3 version is `Python 3.6.6`
```
[root@db1 ~]# cat test3.py
def mul_helper(x):
  while True:
    x*x

def mul(x):
  mul_helper(x)

mul(10000)
```
And when I run `./PyPerf`, it shows as follow
```
Failed getting addresses in potential Python library in PID 30055
0 samples collected
0 samples lost
0 samples with truncated stack
0 times Python symbol lost
```

**Comment by palmtenor** [comment]
`Failed getting addresses in potential Python library` is probably the issue. Would you use the `/proc/PID/maps` to determine the path of your `libpython` and make sure symbols like `autoTLSkey`, `_PyThreadState_Current`, `gil_locked` and `gil_last_holder` are exposed?

**Comment by 201341** [comment]
My path of `libpython` is `/usr/lib64/libpython3.6m.so.1.0` . And when I use `nm` to find the symbols, it tells me no symbols. Does it mean I need to recompile the python3.6 with args `-g` using the source code?

**Comment by palmtenor** [comment]
I don’t think compile with `-g` is neccesary (i.e. you don’t need debug info), just don’t fully strip the symbol table (i.e. if you do `strip` do it with `-g`)
