### ISSUE TITLE
Is it expected that C standard libraries are not accessiable to BCC compiler

### ISSUE THREAD

**Issue by yzhao1012** [iovisor/bcc#2447]
BCC seems have no access to standard C libraries, like <string.h> etc.

Is this expected?

**Comment by yonghong-song** [comment]
You mean bpf program, right?
No, it does not since most APIs in string.h cannot be used in bpf program. They are available in libc.

**Comment by yzhao1012** [comment]
Thanks for your help!

By libc, you mean they are only available when link with libc, which is not
available to BCC C code, right?

**Comment by yonghong-song** [comment]
right. bcc c code does not allow external functions except helpers.
