### ISSUE TITLE
BCC use case: feasible?

### ISSUE THREAD

**Issue by adf54** [iovisor/bcc#2453]
I'd like to measure how long it takes on average to finish the TCP 3-way handshake, compiling this as timeseries data throughout the data. Looking at the documentation, the simplest way seems to be to do this via kprobes - specifically, look at the kernel source and understand which specific functions in the networking stack to instrument. 

I am using kernel version ~ 4.10 so there is a concern that underlying kernel specifics could change that would break bcc C code. TCP tracepoints are not available in 4.10.

Am I looking at the right tool to use, or should I be looking elsewhere?

**Comment by yonghong-song** [comment]
Using tracepoint still easiest one. There is a kernel function `tcp_set_state`. But I do not know whether it captures all the states or not. Or it could be inlined in some call sites, so you will miss those states.
