### ISSUE TITLE
Should all helper function be declared inline

### ISSUE THREAD

**Issue by yzhao1012** [iovisor/bcc#2459]
Hi All,

Helper functions are those called inside the probe functions, which are loaded to BPF module.

I am wondering, is there a preferred way to declare these helper functions? Should they be always inlined?

For example, given:
static int foo() {
...
}

int syscall_probe_write() {
foo();
}

The question is, should foo() be always inlined? Like static inline attribute((always_inline)).

**Comment by yonghong-song** [comment]
What helper functions are you referring to? Any example?

**Comment by yzhao1012** [comment]
Thanks Yonghong!

I am talking about the user-defined helper function. Like:
inline int foo() {
...
}

int syscall_probe_write() {
  foo();
}

The question is, should foo() be always inlined? Like static inline __attribute__((__always_inline__)).

Sorry I was not precise.

**Comment by yonghong-song** [comment]
At this point, yes.
But bcc can be improved to avoid always inlining user defined functions just like kernel libbpf.
Just need some people help do the ELF parsing work etc...

**Comment by yzhao1012** [comment]
Thanks!
> But bcc can be improved to avoid always inlining user defined functions just like kernel libbpf.
This seems to imply, ATM, BCC actually __"always inlining user defined functions"__, is that true?

Also, to be precise:
> At this point, yes.
By this, you mean foo() in the previous example should always be inlined and force inlined.
Note that originally, I was using inline merely for performance optimization purpose.
But with the above statement, it seems BCC has other limitations, such that all static functions are always inlined.

That sounds like we should not try to manually add inline modifier, as that would eventually at odds with BCC, when it decide that functions do not need to be inlined, as your implied above.

Does this make sense to you?

**Comment by yonghong-song** [comment]
If you decide that one function do not need to be inlined, yes, you do not need to add always_inline there. for unmarked static functions, compiler may inline them, but no guarantees. So with current implementation, I still suggest to mark them as always inline.
