### ISSUE TITLE
Directly Using the relation of cpu_id and max_cpu to check parameters ?

### ISSUE THREAD

**Issue by glennWang** [iovisor/bcc#2462]
https://github.com/iovisor/bcc/blob/master/examples/networking/xdp/xdp_redirect_cpu.py#L27

max_cpu = cpu_count()
cpu_id indexed from 0

Directly Using the relation of cpu_id and max_cpu to check parameters.

Is there a bug ?

**Comment by yonghong-song** [comment]
For most systems, this should be correct except a minor bug it should be 'cpu_id >= max_cpu`. For certain systems, e.g., with cpu ids like '0-1,4-5`. count is 4, the id is 0/1/4/5. the condition is not correctly. At least the condition should be corrected and some comments should be added.
Could you help?

**Comment by glennWang** [comment]
Okay, I see.

Thanks
