### ISSUE TITLE
BPF verifier cannot reliably detect size_t as unsigned.

### ISSUE THREAD

**Issue by yzhao1012** [iovisor/bcc#2473]
Hi All,

I am afraid that BCC might not be the right place for this question. But have no idea where is the BPF kernel portion of the community.

We use size_t extensively in our BCC code. And sometime BPF verifier complains that a size_t variable can be negative. This can be fixed by changing it to unsigned int.

Is it true that BPF verifier does not handle typedefs reliably, as size_t is a typedef of some unsigned integer type?

Thanks in advance!

**Comment by anakryiko** [comment]
Please write email (plain text, please) to bpf@vger.kernel.org, but also include example code that shows the issue, along with the BPF verifier log you get to make it easier to understand and reproduce the problem. Thanks!

**Comment by palmtenor** [comment]
Can you a minimal code that can reproduce the issue?

@anakryiko I feel this would be more of a frontend (compiler / LLVM) issue...

**Comment by yonghong-song** [comment]
@yzhao1012 please do share your example. size_t is 8 bytes and "unsigned int" is 4 bytes. there may be some optimization which makes verifier hard to track precision.

**Comment by yzhao1012** [comment]
I'll try to get a minimal code. But it might take a few weeks for me to find spare time.

**Comment by yzhao1012** [comment]
This probably is related/similar to issues like https://github.com/iovisor/bcc/issues/3738#issuecomment-992180484
But I no longer have records of this issue, and it's almost 3 years since the initial report.
Close.
