### ISSUE TITLE
How can I call getsockopt() on a int sockfd?

### ISSUE THREAD

**Issue by yzhao1012** [iovisor/bcc#2489]
Hi All,

I wan to apply filtering on the read()/write() calls on a socket file descriptor according to the parameters of the socket fd.

The bpf_getsockopt() helper function seems expect a struct bpf_sock_ops *bpf_socket, for which I don't know how to retrieve from a int sockfd.

Is it even possible to retrieve such information from a integer file descriptor?

**Comment by yonghong-song** [comment]
the context for `bpf_getsockopt()` is `bpf_sock_ops`. That is why it takes it as the first parameter.

Currently, there is no helpers for you to translate an int fd to socket data strcuture. This is done in special occasions like reuseport_array map or xsk map. You could trace through `current->files` and eventually compare to `&socket_file_ops`. You can check kernel
`sockfd_lookup` function. This may or may not work, I did not really check details.

**Comment by 201341** [comment]
I filter the read / write calls on socket by `file->f_inode->i_mode`. and then use the function ` S_ISSOCK(mode) `.

**Comment by yzhao1012** [comment]
Hi Wjie, thanks a lot!

Could you elaborate a bit how to get `file->f_inode->imode`, from a int fd? Let's say I have a kprobe looks like this:
`
probe_entry_write_send(struct pt_regs* ctx, int fd, char* buf, size_t count,
                                            const struct iovec* iov, size_t iovlen) {
`

**Comment by 201341** [comment]
If you probe the function `vfs_read`, you can get the struct `file`. And I'm not sure whether there is a function to get struct `file` from `fd` in kernel.

**Comment by yzhao1012** [comment]
That makes sense, thanks!
