### ISSUE TITLE
Exception: Failed to attach BPF program kprobe___copy_from_iter to kprobe _copy_from_iter

### ISSUE THREAD

**Issue by aaron-ai** [iovisor/bcc#2509]
I use debian 10 whose kernel version is `4.19.0-5-amd64`, and I use kprobe on function `_copy_from_iter`, which should be `copy_from_iter` on `4.9`. Because the symbol of `copy_from_iter` is not exposed on `4.19`, so I use `_copy_from_iter` instead of it. when I use `kprobe__copy_from_iter` on `4.9`, it works, but when I use `kprobe___copy_from_iter`(3 underlines) on `4.19.0-5-amd64`, it will show an exception:

**Exception: Failed to attach BPF program kprobe___copy_from_iter to kprobe _copy_from_iter**.

here is my code:
```cpp
int kprobe___copy_from_iter(struct pt_regs *ctx, void *addr, size_t bytes, struct iov_iter *i)
{
// do nothing here
    return 0;
}
```

**Comment by yonghong-song** [comment]
could you check for error message in `dmesg`?  A little bit more detailed log can be found at `/sys/kernel/debug/tracing/error_log`.

**Comment by aaron-ai** [comment]
> could you check for error message in `dmesg`? A little bit more detailed log can be found at `/sys/kernel/debug/tracing/error_log`.

I use dmesg, it gives me the info below: 
```bash
[   31.085841] trace_kprobe: Could not probe notrace function _copy_from_iter
[   31.087862] trace_kprobe: Could not probe notrace function _copy_from_iter
[   78.788978] trace_kprobe: Could not probe notrace function _copy_from_iter
[   78.790554] trace_kprobe: Could not probe notrace function _copy_from_iter
[  184.780877] trace_kprobe: Could not probe notrace function _copy_from_iter
[  184.782437] trace_kprobe: Could not probe notrace function _copy_from_iter
[35446.661824] trace_kprobe: Could not probe notrace function _copy_from_iter
[35446.663432] trace_kprobe: Could not probe notrace function _copy_from_iter
[38167.653602] trace_kprobe: Could not probe notrace function _copy_from_iter
[38167.655165] trace_kprobe: Could not probe notrace function _copy_from_iter
```
but I do not see the `error_log` file under `/sys/kernel/debug/tracing/`, should I do something to enable it ?

**Comment by palmtenor** [comment]
Do you have `_copy_from_iter` in your `/proc/kallsyms`?

**Comment by aaron-ai** [comment]
> Do you have `_copy_from_iter` in your `/proc/kallsyms`?

yes.

**Comment by yonghong-song** [comment]
In my environment, I have
```
[root@devbig003.ftw2 /home/yhs]# trace.py '_copy_from_iter'
cannot attach kprobe, Invalid argument
Failed to attach BPF program probe__copy_from_iter_1 to kprobe _copy_from_iter
[root@devbig003.ftw2 /home/yhs]# dmesg | tail
...
[1547427.099036] trace_kprobe: Could not probe notrace function _copy_from_iter
[root@devbig003.ftw2 /home/yhs]#
```
The attachment failed as `_copy_from_iter` is marked as notrace by the kernel.
I am using 5.2 kernel, your old kernel may not have this issue, but may be other issues.

Do you have more detailed error messages in dmseg?

**Comment by aaron-ai** [comment]
> In my environment, I have
> 
> ```
> [root@devbig003.ftw2 /home/yhs]# trace.py '_copy_from_iter'
> cannot attach kprobe, Invalid argument
> Failed to attach BPF program probe__copy_from_iter_1 to kprobe _copy_from_iter
> [root@devbig003.ftw2 /home/yhs]# dmesg | tail
> ...
> [1547427.099036] trace_kprobe: Could not probe notrace function _copy_from_iter
> [root@devbig003.ftw2 /home/yhs]#
> ```
> 
> The attachment failed as `_copy_from_iter` is marked as notrace by the kernel.
> I am using 5.2 kernel, your old kernel may not have this issue, but may be other issues.
> 
> Do you have more detailed error messages in dmseg?

It is marked as notrace on 4.19.0-5-amd64, too. Thanks！！

**Comment by aaron-ai** [comment]
> > In my environment, I have
> > ```
> > [root@devbig003.ftw2 /home/yhs]# trace.py '_copy_from_iter'
> > cannot attach kprobe, Invalid argument
> > Failed to attach BPF program probe__copy_from_iter_1 to kprobe _copy_from_iter
> > [root@devbig003.ftw2 /home/yhs]# dmesg | tail
> > ...
> > [1547427.099036] trace_kprobe: Could not probe notrace function _copy_from_iter
> > [root@devbig003.ftw2 /home/yhs]#
> > ```
> > 
> > 
> > The attachment failed as `_copy_from_iter` is marked as notrace by the kernel.
> > I am using 5.2 kernel, your old kernel may not have this issue, but may be other issues.
> > Do you have more detailed error messages in dmseg?
> 
> It is marked as notrace on 4.19.0-5-amd64, too. Thanks！！

if I do not change the function I trace (`_copy_from_iter `), what should I do? enable `CONFIG_KPROBE_EVENTS_ON_NOTRACE` and recompile the kernel ? is this the only solution ?

**Comment by yonghong-song** [comment]
Enabling `CONFIG_KPROBE_EVENTS_ON_NOTRACE` probably the only solutiion, I guess.
