### ISSUE TITLE
Profiling tasks in cgroup containers

### ISSUE THREAD

**Issue by jxiong** [iovisor/bcc#2510]
I'm planning to work on a project to profile jobs on computer nodes. Those jobs are executed inside containers, where the resources are constrained by cgroups. To make this work, there will be a job-profiler container running on computer host all the time, and whenever a new job is scheduled, which will cause new container to be created, a notification is sent to the job-profiler so that the resources used by job, including CPU, memory, block IO, and network will be profiled and reported.

I'm thinking about using BCC and ebpf to implement this, since it is well discussed in general. However, I figure out that BCC is not supporting cgroup well at this point. Kernel seems to already have cgroup support. Taking a look at the implementation of `perf_event_open()` where it accepts `cgroup_fd` from `pid` if flag `PERF_FLAG_PID_CGROUP` is set. It can only be set on a specific CPU(I don't know the reason behind this). Please let me know if I miss something here.

It doesn't seem to be a lot of work to add this support to BCC. I can work on this under some technical guidance.

**Comment by palmtenor** [comment]
`PERF_FLAG_PID_CGROUP` works as intended at least for perf events from my experience.

Another way is to just use `bpf_get_current_cgroup_id` in your BPF program and classify the cost from different cgroups yourself. Probably easier this way if you run the profiler on the host, since you won't need to do BPF program attaching and processing for each container individually.

**Comment by jxiong** [comment]
Thanks for replying. `perf_event` is the only API that can take extra flags for setting CGROUP from the implementation, specifically `bpf_attach_perf_event()`  function. I wonder how easy to use this to do whatever `PERF_KPROBE` does. Or do you have any example code to show me?

I thought about using `bpf_get_current_cgroup_id()` too. And I could define a map to keep track of cgroups that needs to profile; this map can be modified by job profiler from user space when containers come and go. However, I'm a little worrying about the atomic access to this map.

**Comment by yonghong-song** [comment]
@jxiong I do not particularly worry about racing between user and kernel accessing to the map in the above method. kernel has proper mutex lock and rcu to protect write and read properly.

Another option is to extend bcc python API `attach_perf_event`:
```
    def attach_perf_event(self, ev_type=-1, ev_config=-1, fn_name=b"",
            sample_period=0, sample_freq=0, pid=-1, cpu=-1, group_fd=-1)
```

Maybe we can add an extra_flags which can have PERF_FLAG_PID_CGROUP.
This way user can set pid to be cgroup id and extra_flags to be PERF_FLAG_PID_CGROUP.
Some other adjustment is also needed as in some places pid is used as a process id.

C++ side already have `bpf_attach_perf_event_raw()` to allow extra_flags.

**Comment by jxiong** [comment]
> I do not particularly worry about racing between user and kernel accessing to the map in the above method. kernel has proper mutex lock and rcu to protect write and read properly.

BPF has very limited kernel locking primitives to use. The first one, `spin_lock`, was added recently in 5.1 kernels, we can't upgrade kernels to that version or later on production servers.

I already had a patch to extend cpp API to support cgroup. However, it doesn't seem to have any effect. The test case I performed is basically as follows:
```
1. mkdir /sys/fs/cgroup/perf_event/tests
2. stress -c 1
3. ./examples/cpp/CPUDistribution 10 tests
 ```
What I would expect is that `CPUDistribution` should return idle results since `stress` process has not been added into the corresponding cgroup. However, the actual result still showed that one CPU is stressed.

After checking the kernel implementation a bit(v5.2.14), I realize that KPROBE support for perf event probably requires enhancement to handle this case properly; it doesn't have a callback to filter events before calling the actual BPF prog. More specifically, it should filter the events before calling `kprobe_perf_func()` in `kprobe_dispatcher()`.

**Comment by jxiong** [comment]
@yonghong-song ^^

**Comment by palmtenor** [comment]
If you have older Kernel, are you sure you are using Perf Event based kprobe not the `debugfs` text based kprobe? For the later your patch won't do anything.

**Comment by jxiong** [comment]
Yes, I have verified that it's using Perf Event Kprobe.
