### ISSUE TITLE
attach_uprobe to a function in a (C++) stripped executable debuginfo issue?

### ISSUE THREAD

**Issue by drandynisbet** [iovisor/bcc#2517]
Hi,
Could anyone please point me in the right direction on how to function hook a stripped (of symbols) executable.

Running Ubuntu 19.04
Kernel  5.0.0-27-generic 

Im trying to function hook some methods in a stripped executable (java openjdk) and have ran into problems. Specifically I am hooking methods in the java virtual machine and not the application that it is running. I could of course build openjdk with debug symbols included (this is an option but I'd prefer to avoid it as we want this to work on production systems), or preferably to install the appropriate debug symbol package for openjdk. 
I can do something like this in gdb on the command line after attaching to a running process ...
 info functions Deoptimization::deoptiimize
This will give me the address abcd of  a particular Deoptimization related method that I'm interested in ...
set print demangle off
info symbol abcd 
Gives me the mangled name of the method I'm interested in ....
I have attempted various ways to use bpf.attach_uprobe() but  end up with errors such as  
    raise Exception("Failed to attach BPF to uprobe") using an explicit symbol address and PID of a running process or when using the mangled symbol name
    raise Exception("could not determine address of symbol %s" % symname)

Any pointers gratefully received ... 
I've had no problem at all when the executable is not stripped.
 
Thanks,
Andy

**Comment by palmtenor** [comment]
- By "stripped" do you mean just debug info or symbol table as well? If you `nm` on your OpenJDK binary do you see the symbol you are interested in?
- By "using an explicit symbol address and PID of a running process", what address are you using exactly? If OpenJDK is dynamically loaded, providing the binary address won't help.

**Comment by drandynisbet** [comment]
Hi, thanks for the reply ...

nm java reports no symbols - I don't see any symbols there ... 
file java  reports that iava is dynamically linked, and stripped.
Using gdb to attach to a running java process gives me the correct addresses - I detach gdb and then attempt to attach_uprobe by altering the addresses in my python/eBPF code and running that as root  - the java process is still running and these are not JIT-ted  code symbols so the addresses should  be correct?

For  example ... commands and outputs
nm /usr/lib/jvm/default-java/bin/java
nm: /usr/lib/jvm/default-java/bin/java: no symbols
file /usr/lib/jvm/default-java/bin/java
/usr/lib/jvm/default-java/bin/java: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=b684a1a128946231b8dc3ebf1650d4bf70a249ea, for GNU/Linux 3.2.0, stripped

I have installed the relevant openjdk-8-jdk and also openjdk-8-dbg packages.  Similar issues with java 11 ... 

I guess this is some combination of  incorrect usage (by me) of the attach_uprobe for fixed addresses, perhaps the searching for symbols used by attach_uprobe does not search debuginfo in the same way as gdb.

I dont' have a problem if the symbols are included in the  binary. 


Andy

**Comment by drandynisbet** [comment]
Apologies it looks like it is my error in terms of usage ... need to point it at the appropriate library and look for the mangled symbol name then the debug symbols will be searched ... 
 sudo /usr/share/bcc/tools/funclatency  /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so:_ZN14Deoptimization19uncommon_trap_innerEP10JavaThreadi
Tracing 1 functions for "/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so:_ZN14Deoptimization19uncommon_trap_innerEP10JavaThreadi"... Hit Ctrl-C to end.

I haven't fully checked it on a real java application - this was just a toy but I guess if it's found the function then it is working.
