### ISSUE TITLE
Weird side effect of map.lookup_or_init()

### ISSUE THREAD

**Issue by pjsg** [iovisor/bcc#2518]
I discovered today that `map.lookup_or_init()` has bizarre behavior if the insert into the map fails (e.g. the map is full). It is either a documentation error, or an implementation error.

The actual behavior is that `lookup_or_init()` actually returns (with a return value of 0) from the function in which it is executed!! I would think that the more reasonable approach would be to make the `lookup_or_init` method itself return 0 if the insert fails....

Thoughts?

**Comment by yonghong-song** [comment]
@pjsg I agree with you.  I have numerous instances and people did not realize this and have surprise on the finding. `lookup_or_init` silently return is not good and hard to debug. 
Yes, let us make it explicit and return 0 if insert fails. Could you help craft a patch for this? In bcc repo, there are some places using lookup_or_init, and they did not check return value. They need change to check return values.
