### ISSUE TITLE
Complex BPF program leaking a lot of memory on exit

### ISSUE THREAD

**Issue by willfindlay** [iovisor/bcc#2537]
Possibly related to #1949. 
#### Background
I'm working on a relatively complex eBPF program that runs as a daemon and monitors system processes. As a part of the BPF program, I maintain a hashmap of pid_tgids associated with fairly large structs (too large for the BPF stack, so I init them from an array). I'm on Linux 5.3.0 and using bcc v0.10.0.r98.ba64f031-1 from the bcc-git AUR.
#### The Problem
When I stop my daemon, I experience a massive memory leak (96%+ RAM usage on 16GB of RAM, plus about 4GB of swap space). This doesn't happen all the time, but I have a pretty consistent reproduction case by opening 5 Google Chrome sessions while the daemon is running.
**Edit:** The problem seems to be related to iterating over the values of a large hashmap before I call `bpf.cleanup()`.
#### Some Steps I Have Tried
- I've tried setting `allow_rlimit=False` in the BPF constructor and setting my own hard limit of 4GB using the Python resource module
- I'm working on creating a minimal example to reproduce this issue. I will update this thread when I have one.

**Comment by yonghong-song** [comment]
the llvm compilation should just take around 20-30MB memory and it is reclaimable. For GB level of memory issues, maybe it is due to map memory leaking? How do you measure memory leaking? Yes, more details will help.

**Comment by willfindlay** [comment]
@yonghong-song In terms of how I'm measuring the memory issues, as of right now I've just been using htop. I'm having trouble getting a minimal example to do the same thing, so it seems that the issue might be more nuanced than I originally expected. In the mean time, I'll try to provide some details below.

The map contains entries of this type:
```c
struct profile
{
    u8 v1; /* I've changed the variable names here because they are not relevant */
    u8 v2;
    u64 v3;
    u64 v4;
    u64 v5;
    u64 v6;
    u64 v7;
    u64 v8;
    u8 flags[355 * 355];
    u64 key;
    char comm[128];
#if LINUX_VERSION_CODE >= KERNEL_VERSION(5,1,0)
    struct bpf_spin_lock lock;
#endif
};
```
The flags array contains entries that are updated whenever a process makes a systemcall.
I initialize entries in the map by using a BPF_ARRAY of size 1 which contains the same struct.

As soon as I attempt to call `self.bpf["profiles"].values()`, my RAM usage spikes to above 96% and my entire system locks up for a few seconds.

**Comment by yonghong-song** [comment]
`bpf["profiles"].values()` will get ALL elements from map 'profiles' to the user space. Each element is 100KB, if you have a lot of elements, it will consume a lot of memory.

**Comment by willfindlay** [comment]
I just came here to say I changed it to itervalues. Sorry for my silly mistake!
