### ISSUE TITLE
bpf_trace_printk() call in nested function results into BPF load failure

### ISSUE THREAD

**Issue by yzhao1012** [iovisor/bcc#2539]
I have the following setup:
static foo1() { ... }
static foo2() {
  ...
  foo1();
  ...
}
static foo3() {
  ...
  foo2();
  ...
}

If bpf_trace_printk() is placed inside foo1(), it would cause BPF load throw "invalid argument".

If it's placed inside foo3(), then it does not have the issue.

Is there any clue?

**Comment by palmtenor** [comment]
What exactly is the error message? Can you come with a minimal repro?

**Comment by ethercflow** [comment]
```
#!/usr/bin/env python

from bcc import BPF

bpf_text="""
static void foo1(void)
{
    bpf_trace_printk("foo1\\n");
}

static void foo2(void)
{
    foo1();
    bpf_trace_printk("foo2\\n");
}

static void foo3(void)
{
    foo2();
    bpf_trace_printk("foo3\\n");
}

int kprobe__sys_clone(void *ctx)
{
    foo3();
    return 0;
}
"""

BPF(text=bpf_text).trace_print()
```

>   zsh-9907  [005] .... 80580.108565: 0: foo1
>   zsh-9907  [005] .... 80580.108579: 0: foo2
>    zsh-9907  [005] .... 80580.108579: 0: foo3
>              zsh-9907  [005] .... 80580.131494: 0: foo1
>              zsh-9907  [005] .... 80580.131499: 0: foo2
>              zsh-9907  [005] .... 80580.131500: 0: foo3
>              zsh-12496 [027] .... 80580.132149: 0: foo1
>              zsh-12496 [027] .... 80580.132163: 0: foo2
>              zsh-12496 [027] .... 80580.132164: 0: foo3
>              zsh-12496 [027] .... 80580.135115: 0: foo1
>              zsh-12496 [027] .... 80580.135126: 0: foo2
>              zsh-12496 [027] .... 80580.135127: 0: foo3
>              zsh-12496 [027] .... 80580.138055: 0: foo1
>              zsh-12496 [027] .... 80580.138066: 0: foo2
>              zsh-12496 [027] .... 80580.138066: 0: foo3

@yzhao1012 I test this and cann't reproduce, are there other points to note?

**Comment by yzhao1012** [comment]
It was probably my fault elsewhere.
No longer have this issue anyway.
Close.
