### ISSUE TITLE
Missing support for asm_inline in Linux 5.4

### ISSUE THREAD

**Issue by bobrik** [iovisor/bcc#2546]
I'm observing the following issue:

```
$ sudo /usr/share/bcc/tools/opensnoop
In file included from /virtual/main.c:2:
In file included from include/uapi/linux/ptrace.h:142:
In file included from ./arch/x86/include/asm/ptrace.h:5:
./arch/x86/include/asm/segment.h:254:2: error: expected '(' after 'asm'
        alternative_io ("lsl %[seg],%[p]",
        ^
./arch/x86/include/asm/alternative.h:240:2: note: expanded from macro 'alternative_io'
        asm_inline volatile (ALTERNATIVE(oldinstr, newinstr, feature)   \
        ^
include/linux/compiler_types.h:210:24: note: expanded from macro 'asm_inline'
#define asm_inline asm __inline
                       ^
```

The cause appears to be this commit landed in 5.4.0-rc1:

* https://github.com/torvalds/linux/commit/40576e5e63ea5eeab814de7af83ad09dd64134ee

If I replace `asm_inline` with `asm` in the kernel headers, it works just fine.

I do have `CONFIG_CC_HAS_ASM_INLINE=y`:

* https://github.com/torvalds/linux/blob/v5.4-rc2/include/linux/compiler_types.h#L209-L213
* https://github.com/torvalds/linux/commit/eb111869301e15b737315a46c913ae82bd19eb9d

The kernel is compiled with GCC 9.2.0, BCC is using LLVM9.

**Comment by bobrik** [comment]
Adding the following at the very top of opensnoop C code also works:

```c
#ifdef asm_inline
#undef asm_inline
#define asm_inline asm
#endif
```

Should I make a PR to insert this in [`BFrontendAction::DoMiscWorkAround()`](https://github.com/iovisor/bcc/blob/76f31edfdbac03b02a4fc0bcd07fcd25c6dd5d03/src/cc/frontends/clang/b_frontend_action.cc#L1409-L1432) or is there a better way?

**Comment by yonghong-song** [comment]
Could you add the workaround to helpers.h? There is already asm_volatile_goto workaround there?
