### ISSUE TITLE
failed to compile BPF module task_switch.c

### ISSUE THREAD

**Issue by sshhj89** [iovisor/bcc#256]
Hello, I have a problem in compiling task_switch.c. Other examples works well. 
<img width="451" alt="screen shot 2015-09-30 at 2 50 13 am" src="https://cloud.githubusercontent.com/assets/7479718/10173244/27bb5fb0-671e-11e5-8ede-903ca5a9a113.png">
This image resulted from compiling task_switch.c with "debug = 0x4"
I think that the code should be compiled like "(*val)++", not "_val}))++;" in the middle line of image.
I followed the instruction in Install.md. I am sure that I done well because other examples works well.
I already installed different versions of linux kernel, llvm(3.7 and mirror git), and clang(3.7 and mirror version).

**Comment by yonghong-song** [comment]
@sshhj89 This is a bcc bug:

  val = stats.lookup_or_init(&key, &zero);
  (*val)++;

The compiler tries to do smart thing to automate bpf_probe_read. It tries to use
bpf_probe_read to read *val, which is not really needed in this case.
