### ISSUE TITLE
How did you get past invalid output constraint in asm?

### ISSUE THREAD

**Issue by phylake** [iovisor/bcc#2578]
I'm trying to `#include <net/sock.h>` in a bpf program (not using bcc) and getting
```
arch/x86/include/asm/atomic.h:184:9: error: invalid output constraint '+q' in asm
```
I found [this comment](https://lore.kernel.org/patchwork/patch/663307/) from Alexei Starovoitov which seems related
> ahh. yes. when processing kernel headers clang has to assume x86 style
inline asm, though all of these functions will be ignored.

I've started pouring through bcc source but I was hoping for a quicker answer. I'm on Kernel 4.19

**Comment by phylake** [comment]
Found the answer [here](https://www.mail-archive.com/linux-kernel@vger.kernel.org/msg1546605.html)

**Comment by pyang-1981** [comment]
The solution make compilation successful. However, the resulting bpf.o file have no maps section when inspected using objdump. Any idea?
