### ISSUE TITLE
include bcc-static in install target?

### ISSUE THREAD

**Issue by zlim** [iovisor/bcc#2580]
`bcc-static` is built (https://github.com/iovisor/bcc/blob/master/src/cc/CMakeLists.txt#L70) but not installed (https://github.com/iovisor/bcc/blob/master/src/cc/CMakeLists.txt#L111-L118).

This leads to workarounds being applied downstream, e.g. `bpftrace`: https://github.com/iovisor/bpftrace/blob/master/docker/Dockerfile.alpine#L33-L35.

Would it be okay to add `bcc-static` to install target?

**Comment by yonghong-song** [comment]
Yes, we can. Could you submit  a pull request?

**Comment by zlim** [comment]
Thanks @yonghong-song for the response!

Taking a closer look, it seems like various distros have packages for bcc (and libbpf) now. In the specific Alpine case I was referring to, given that the next Alpine release 3.11 (see #2338 and https://pkgs.alpinelinux.org/packages?name=bcc&branch=edge) should resolve the custom build issue, I don't think a patch like the following will have too much downstream impact :)

```
diff --git a/src/cc/CMakeLists.txt b/src/cc/CMakeLists.txt
index 571a4637..cd8318b1 100644
--- a/src/cc/CMakeLists.txt
+++ b/src/cc/CMakeLists.txt
@@ -116,3 +116,4 @@ install(FILES ${CMAKE_CURRENT_BINARY_DIR}/libbcc.pc DESTINATION ${CMAKE_INSTALL_
 endif(ENABLE_CLANG_JIT)
 install(FILES ${bcc_common_headers} DESTINATION include/bcc)
 install(TARGETS bpf-shared LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR})
+install(TARGETS bpf-static ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR})
```
In the course of this investigation, I came up with additional questions about bcc's use of libbpf submodule as well as its interaction with system libbpf. I'll try to ask in IRC or open new issue to followup.

**Comment by yonghong-song** [comment]
Most distro probably only have shared libraries, so static library should be okay, I think.

**Comment by yonghong-song** [comment]
> I'll try to ask in IRC or open new issue to followup.
open a new issue probably better, so we can record the discussion.
