### ISSUE TITLE
[BUG] runqslower reports the same PID to different processes

### ISSUE THREAD

**Issue by bodgergely** [iovisor/bcc#2588]
Please note that the same PID shows up many times with totally unrelated processes when using **runqslower** which is especially obvious when the latency level is set to low.
I find it very easy to reproduce consistently.
It almost "feels like" the prev PID remains the same, not sure if there is a race condition of some sort.

Kernel: 5.0.0-25-generic

This is something that I observed on other kernels as well

Excerpt (truncated) from running `sudo ./runqslower.py 100`:
Of course many other PIDs suffer from this.

TIME     COMM             PID           LAT(us)
**22:19:12 gnome-software   2435              178**
22:19:12 update-notifier  10581             191
**22:19:12 gsd-media-keys   2435              158**
**22:19:12 gsd-wacom        2435              139**
**22:19:12 ibus-x11         2435              146**
22:19:12 runqslower.py    2613              105
22:19:12 kworker/0:3      2615             1736
22:19:12 kworker/0:3      2615             1357
**22:19:12 swapper/1        2435              105**
22:19:12 chrome           22498             122

Running ps:

greg      **2435**  1.2  0.4 534412 77012 tty2     Sl+  Oct31 114:53 /usr/lib/xorg/Xorg vt2 -displayfd 3 -auth /run/user/1000/gdm/Xauthority -background none -noreset -keeptty -verbose 3

Meaning the real process with pid 2435 is Xorg

**Comment by bodgergely** [comment]
Can anyone else confirm they see this anomaly?
I am happy to help debugging/investigating this issue if others confirm that this is an actual bug.

**Comment by yonghong-song** [comment]
Yes, it does look like some bugs in raw_tracepoint based approach. The kprobe based solution looks more sane. Could you help take a look?

**Comment by bodgergely** [comment]
I created a PR above that fixes this issue. Let me know if it looks good or (bad).
