### ISSUE TITLE
[PR proposal] Shorten long file path if necessary

### ISSUE THREAD

**Issue by yzhao1012** [iovisor/bcc#2592]
There is now a 128 characters limit on the size of the uprobe event name, which is composed from file path (replacing / with _) and some additional prefix & suffix.

The API will fail if the file path length breaches this limit.

Instead of error out directly, does it make sense to shorten this file path, by stripping some characters at the right end of the string, and append a fixed number of random characters (to avoid name collision).

Users of BPF should have the option to turn on/off of this behavior.

The diff roughly looks like:

```
diff --git a/src/cc/api/BPF.cc b/src/cc/api/BPF.cc
index db2436d8..d204660a 100644
--- a/src/cc/api/BPF.cc
+++ b/src/cc/api/BPF.cc
@@ -22,6 +22,7 @@
 #include <exception>
 #include <iostream>
 #include <memory>
+#include <random>
 #include <sstream>
 #include <utility>
 #include <vector>
@@ -671,6 +672,34 @@ bool BPF::add_module(std::string module)
     false : true;
 }
 
+namespace {
+
+std::string random_alnum_string(int len) {
+  static constexpr char kDict[] = "0123456789abcdefghijklmnopqrstuvwxyz";
+  static std::random_device rd;
+  std::uniform_int_distribution<size_t> dist(0, sizeof(kDict));
+  std::string res;
+  res.reserve(len);
+  for (int i = 0; i < len; ++i) {
+    res.push_back(kDict[dist(rd)]);
+  }
+  return res;
+}
+
+constexpr size_t kEventNameSizeLimit = 224;
+
+std::string shorten_event_name(const std::string& name) {
+  constexpr size_t kRandomSuffixLen = 16;
+  std::string res;
+  res.reserve(kEventNameSizeLimit);
+  res.assign(name);
+  res.resize(kEventNameSizeLimit - kRandomSuffixLen);
+  res.append(random_alnum_string(kRandomSuffixLen));
+  return res;
+}
+
+}  // namespace
+
 std::string BPF::get_uprobe_event(const std::string& binary_path,
                                   uint64_t offset, bpf_probe_attach_type type,
                                   pid_t pid) {
@@ -679,6 +708,15 @@ std::string BPF::get_uprobe_event(const std::string& binary_path,
   res += "_0x" + uint_to_hex(offset);
   if (pid != -1)
     res += "_" + std::to_string(pid);
+  if (res.size() > kEventNameSizeLimit) {
+    auto iter = name_map_.find(res);
+    if (iter != name_map_.end()) {
+      return iter->second;
+    }
+    std::string shortend_name = shorten_event_name(res);
+    name_map_[res] = shortend_name;
+    return shortend_name;
+  }
   return res;
 }
 
diff --git a/src/cc/api/BPF.h b/src/cc/api/BPF.h
index 4b260887..b524c3e8 100644
--- a/src/cc/api/BPF.h
+++ b/src/cc/api/BPF.h
@@ -254,6 +254,9 @@ class BPF {
   std::vector<USDT> usdt_;
 
   std::map<std::string, open_probe_t> kprobes_;
+  // For uprobes, if the binary path is longer than 250, we'll shorten them. And then keep the
+  // mapping.
+  std::map<std::string, std::string> name_map_;
   std::map<std::string, open_probe_t> uprobes_;
   std::map<std::string, open_probe_t> tracepoints_;
   std::map<std::string, BPFPerfBuffer*> perf_buffers_;
```

**Comment by yonghong-song** [comment]
where did you get this 128 bytes limit? How did you come up with `kEventNameSizeLimit = 224`?

**Comment by yzhao1012** [comment]
There are at least 2 places:
https://github.com/iovisor/bcc/blob/eb018cf9e5df30c9748e4b31a33f0934a47cca6b/src/cc/libbpf.c#L957
https://github.com/iovisor/bcc/blob/eb018cf9e5df30c9748e4b31a33f0934a47cca6b/src/cc/libbpf.c#L1033

The 128 was wrong, I recalled it wrong.

**Comment by yonghong-song** [comment]
if we change these internal local array size from 128 to 256, do it solve your problem?

**Comment by yzhao1012** [comment]
They are now already 256, and worse, this will later run into linux path component size limit. Eg. https://www.quora.com/What-is-the-longest-file-path-allowed-for-Linux

**Comment by palmtenor** [comment]
I think these are exactly the reason we went for Perf Event based kprobe and uprobe instead of rely on debugfs. Does you Kernel support those?

**Comment by yzhao1012** [comment]
I think we are on 4.15; for backward compatibility, we do need this though.

**Comment by palmtenor** [comment]
How about we just make the event name consistent? I propose `bcc_<PID_OF_BCC>_<FILE_NAME>_<HASH_OF_FULL_PATH>_<PID_OF_UPROBE>`
This way we have both bounded length and good uniqueness.

**Comment by yzhao1012** [comment]
<FILE_NAME> can still be very large, right?

**Comment by yzhao1012** [comment]
We haven't been affected by this issue for a long time.
Although this might become a problem in the future, the likelihood is diminishing with the adoption of newer kernel versions.
As https://github.com/iovisor/bcc/issues/2592#issuecomment-553716621 pointed out that newer kernel, with Perf Event based approach, will nullify this issue.

Close.
