### ISSUE TITLE
BPF_TABLE array index access

### ISSUE THREAD

**Issue by SunKyu** [iovisor/bcc#260]
Hi
I think I found  a kind of array access bug, 
I try to use BPF_TABLE (type array), 
Here is my code

 index_bug.c
```C
#include <uapi/linux/ptrace.h>

BPF_TABLE("array", int, int, dist, 5);//size 5

int index_sys_clone (struct pt_regs *ctx, unsigned long flags){

    int index =0;
    int zero = 0;
    int  leaf =  0;
    int *val;
    val = dist.lookup_or_init(&index, &zero);//0,0
    (*val) = leaf;
    index++;leaf++;

    val = dist.lookup_or_init(&index, &zero);//1, 1
    (*val) = leaf;
    index++;leaf++;

    val = dist.lookup_or_init(&index,&zero);//2, 2
    (*val) = leaf;
    index++;leaf++;

    val = dist.lookup_or_init(&index,&zero);//3, 3
    (*val) = leaf;
    index++;leaf++;

    val = dist.lookup_or_init(&index,&zero);//4, 4
    (*val) = leaf;
    index++;leaf++;

    val = dist.lookup_or_init(&index,&zero);//5, 5
    (*val) = leaf;
    
    
    return 0;
}
```
That BPF_TABLE array's size is 5
and here is my python code
index_bug.py
```python
from bcc import BPF
from time import sleep

b = BPF(src_file = "index_bug.c")
b.attach_kprobe(event = "sys_clone", fn_name = "index_sys_clone")

interval = 5
do_exit = 0

while 1:
    for k,v in b["dist"].items():
        print (k.value, v.value)
    try:
        sleep(interval)
    except KeyboardInterrupt:
        pass; do_exit = 1

    if do_exit:
        exit()
```

But when I use this Python code, the result was shown like this
```bash
$ sudo python index_bug.py 
(1, 0)
(2, 0)
(3, 0)
(4, 0)
#before run bpf code 
(1, 1)
(2, 2)
(3, 3)
(4, 4)
```

So I can't use index 0 and  5
But no error in bpf compile and can't access index 0,5 in python 

edited. 
I just want to test , so  if  bcc use 1 base array access not 0 base array access, that is reason why I accessed index 5

**Comment by 4ast** [comment]
> BPF_TABLE("array", int, int, dist, 5);//size 5

it's C style array[5], so indices are [0] through [4]
Last lookup_or_init:
val = dist.lookup_or_init(&index,&zero);//5, 5
will try to access array[5] element and program will be aborted with return 0.
On a python side it looks like a bug that zero element is not printed.
