### ISSUE TITLE
Current runqslower.py seems filtering in bpf program based on task id instead of user visible pid.

### ISSUE THREAD

**Issue by bodgergely** [iovisor/bcc#2607]
Merged this patch. The change looks good. But current runqslower.py seems filtering in bpf program based on task id instead of user visible pid. 

Suppose pid is the task id and tgid is the actual process id,
the following code
```
bpf_text = bpf_text.replace('FILTER_PID', 'pid != %s' % args.pid)
```
probably should be
```
bpf_text = bpf_text.replace('FILTER_PID', 'tgid != %s' % args.pid)
```

Did you run into any issues with this? We probably should fix this issue as well.
The whole bpf program 'pid' thing can be then removed, `tgid` will be used then.

_Originally posted by @yonghong-song in https://github.com/iovisor/bcc/pull/2596#issuecomment-555230505_

**Comment by bodgergely** [comment]
@yonghong-song But the user can trace any task(process, thread) with the current method. He/she just needs to run pstree or or any other process tool to find the task he/she wants to trace. If we limit it to `tgid` then how will we be able to trace threads for example? Or I might misuderstand something in your proposal.

**Comment by yonghong-song** [comment]
It is totally good idea to trace with any task. What I mention is currently in .py program, we use pid but actually it means tid during filtering. If user want to filter a potential pid and he did so, he may still get events from that pid for other tid's. 

The best is to specify both pid and tid in the tool (making them exclusive to each other) which is similar to many other tools.

Could you draft a pull request for this? We need to 1. add '-t' flag to the tool, 2. properly implementing pid and tid based filtering in the bpf code.

**Comment by bodgergely** [comment]
> Could you draft a pull request for this? We need to 1. add '-t' flag to the tool, 2. properly implementing pid and tid based filtering in the bpf code.

Yep, I will draft a PR for this.

**Comment by bodgergely** [comment]
@yonghong-song
I started working on it but I want to clarify a few things:

1. If user specifies --pid: Means we are filtering based on `tgid`, meaning we are tracing all the tasks that belong to that `tgid`.
2. If user specied --tid: Means we are filtering on `pid` (thread) level and just tracing only that one single task.
3. If user specifies both --tid and --pid: We quit early and show an error message and the examples.

**Comment by yonghong-song** [comment]
@bodgergely yes, the above described change sounds good to me.

**Comment by bodgergely** [comment]
@yonghong-song I just created a PR for this issue. Let me know what you think.

**Comment by bodgergely** [comment]
It changes the behaviour somewhat as specifying --pid now will trace the parent and its children too.
Using --tid is to trace threads.
