### ISSUE TITLE
is there string helper STRSTR like STRCMP in trace tool

### ISSUE THREAD

**Issue by tty5** [iovisor/bcc#2616]
i use /usr/share/bcc/tools/trace -U 'do_sys_open (STRCMP("a.out", $task->comm)) "%s", arg2' to trace program open file and print user stack, but i want to filter filepath or exec filename by use STRSTR

is there string helper STRSTR like STRCMP in trace tool

thanks

**Comment by yonghong-song** [comment]
No, there is not. Maybe you can contribute one (STRSTR) if you feel it is useful?

**Comment by tty5** [comment]
i'm porting function from streq_x to strstr_x, but i fail on this error

/usr/share/bcc/tools/trace -UK 'do_sys_open (STRSTR("ls", $task->comm)) "%s", arg2'
/virtual/main.c:33:16: warning: implicit declaration of function 'strstr_0' is invalid in C99 [-Wimplicit-function-declaration]
        if (!((strstr_0("ls", ((struct task_struct *)bpf_get_current_task())->comm)))) return 0;
               ^
1 warning generated.
error: <unknown>:0:0: in function probe_do_sys_open_1 i32 (%struct.pt_regs*): A call to global function 'strstr_0' is not supported. Only calls to predefined BPF helpers are allowed.

is the function streq_x build-in function?

**Comment by tty5** [comment]
> No, there is not. Maybe you can contribute one (STRSTR) if you feel it is useful?

i'm porting function from streq_x to strstr_x, but i fail on this error

/usr/share/bcc/tools/trace -UK 'do_sys_open (STRSTR("ls", $task->comm)) "%s", arg2'
/virtual/main.c:33:16: warning: implicit declaration of function 'strstr_0' is invalid in C99 [-Wimplicit-function-declaration]
if (!((strstr_0("ls", ((struct task_struct )bpf_get_current_task())->comm)))) return 0;
^
1 warning generated.
error: :0:0: in function probe_do_sys_open_1 i32 (%struct.pt_regs): A call to global function 'strstr_0' is not supported. Only calls to predefined BPF helpers are allowed.

is the function streq_x build-in function?

**Comment by tty5** [comment]
i miss add function text to generate_program. now it is ok

**Comment by tty5** [comment]
> No, there is not. Maybe you can contribute one (STRSTR) if you feel it is useful?

i find it is hard to workout ststre, because the bpf program can't use loop, and all the loop will be unwind. so if the string is long, the size of code will overflow.

thanks
