### ISSUE TITLE
PT_REGS_PARM2 not working for syscalls in new kernels

### ISSUE THREAD

**Issue by yanivagman** [iovisor/bcc#2628]
After upgrading my kernel from 4.14 to 4.19 (Manjaro distro, but also reproduced on another distro with kernel 5.3), I'm getting wrong values when using PT_REGS_PARM2 macro (and probably other macros as well) with system calls.

For example, tracing openat syscall as follows, will print an empty value for fname (didn't happen on older kernels). I suspect this is related to the ABI change on x86 syscalls (from kernel 4.17?)
https://lore.kernel.org/patchwork/patch/937552/

```python
#!/usr/bin/python
from bcc import BPF
from bcc.utils import printb

bpf_text = """
#include <uapi/linux/ptrace.h>
#include <uapi/linux/limits.h>
#include <linux/sched.h>

struct val_t {
    u64 id;
    char comm[TASK_COMM_LEN];
    const char *fname;
};

struct data_t {
    u64 id;
    int ret;
    char comm[TASK_COMM_LEN];
    char fname[NAME_MAX];
};

BPF_HASH(infotmp, u64, struct val_t);
BPF_PERF_OUTPUT(events);

int syscall__openat(struct pt_regs *ctx, int dfd, const char __user *filename, int flags)
{
    struct val_t val = {};
    u64 id = bpf_get_current_pid_tgid();

    val.id = id;
    //val.fname = filename;
    val.fname = PT_REGS_PARM2(ctx);;
    infotmp.update(&id, &val);

    return 0;
};

int trace_return(struct pt_regs *ctx)
{
    u64 id = bpf_get_current_pid_tgid();
    struct val_t *valp;
    struct data_t data = {};

    u64 tsp = bpf_ktime_get_ns();

    valp = infotmp.lookup(&id);
    if (valp == 0) {
        // missed entry
        return 0;
    }
    bpf_get_current_comm(&data.comm, sizeof(data.comm));
    bpf_probe_read_str(&data.fname, sizeof(data.fname), (void *)valp->fname);
    data.id = valp->id;
    data.ret = PT_REGS_RC(ctx);

    events.perf_submit(ctx, &data, sizeof(data));
    infotmp.delete(&id);

    return 0;
}
"""

b = BPF(text=bpf_text)
syscall_fnname = b.get_syscall_fnname("openat")
b.attach_kprobe(event=syscall_fnname, fn_name="syscall__openat")
b.attach_kretprobe(event=syscall_fnname, fn_name="trace_return")

print("%-6s %-16s %4s %s" % ("PID", "COMM", "RET", "PATH"))

def print_event(cpu, data, size):
    event = b["events"].event(data)
    printb(b"%-6d %-16s %4d %s" % (event.id >> 32, event.comm, event.ret, event.fname))

b["events"].open_perf_buffer(print_event, page_cnt=64)
while True:
    try:
        b.perf_buffer_poll()
    except KeyboardInterrupt:
        exit()
```

**Comment by yonghong-song** [comment]
Yes, this is related syscall ABI changes. We invented `syscall__` prefix in bpf program to deal with this. https://github.com/iovisor/bcc/blob/master/docs/reference_guide.md#8-system-call-tracepoints
You can look at rewriter output (BPF constructor debug=4) for details.

**Comment by yanivagman** [comment]
Yes, I saw syscall__ prefix, and I'm using it in the above code:
`int syscall__openat(struct pt_regs *ctx, int dfd, const char __user *filename, int flags)`

Yet, this doesn't help with the above program...

**Comment by yonghong-song** [comment]
> I'm getting wrong values when using PT_REGS_PARM2 macro with system calls
You should not use PT_REGS_PARM2 macro. 
Did you get correct result without using PT_REGS_PARM2 macro?

**Comment by yanivagman** [comment]
Yes, if I'm using the argument (filename) directly, it works as expected (commented above)

**Comment by ghostpepper108** [comment]
Any resolution to this? I am also having the same issue even with kernel 5.10.0

**Comment by yonghong-song** [comment]
> Any resolution to this? I am also having the same issue even with kernel 5.10.0

What is your issue here? The previous @yanivagman's comment said it should work without using PT_REGS_PARMS. Please also take a look at rewriter output (debug=4 in the constructor).

**Comment by yanivagman** [comment]
@ghostpepper108 I was also confused about this because it is something that used to work before kernel 4.17.
As @yonghong-song said, you shouldn't use PT_REGS_PARMS when working with syscall wrappers.
The reason for this is https://lore.kernel.org/patchwork/patch/937552/ which defines CONFIG_ARCH_HAS_SYSCALL_WRAPPER that is enabled for x86 since 4.17. 
This patch changed the way that syscall arguments are passed from userspace to the kernel by wrapping them in struct `pt_regs` pointed by the first argument. You can see how we deal with it in Tracee here (we switched from using bcc to libbpf): https://github.com/aquasecurity/tracee/blob/v0.6.1/tracee-ebpf/tracee/tracee.bpf.c#L2041
