### ISSUE TITLE
What does BPF_CGROUP_ARRAY() do?

### ISSUE THREAD

**Issue by yzhao1012** [iovisor/bcc#2639]
It seems introduced in https://github.com/iovisor/bcc/commit/e5e9b1f5ab8be09f3cfe03ed602bda4928999529 by @palmtenor 

I thought it is related to cgroup as inside the container tech. But I searched the example, https://github.com/iovisor/bcc/blob/c00d10d4552f647491395e326d2e4400f3a0b6c5/examples/cpp/CGroupTest.cc#L35 which does not show anything specific to containers.

Google search BPF_CGROUP_ARRAY() does not reveal much either.

We do work on docker & Kubernetes workloads a lot, so if this indeed is designed for cgroup for containers, I'd guess there might be relevant features that are useful to our work.

**Comment by palmtenor** [comment]
It is array that stores cgroup FDs that can be later used to performance various operations such as checking if the BPF program is running in certain cgroup or other cgroup-BPF related things.

I'm not sure what do you mean by "container", can you be more specific about what do you want to do?

Take a look at https://lore.kernel.org/patchwork/cover/694438/ could also help

**Comment by yzhao1012** [comment]
Thanks Teng!

Is there a list of options as you mentioned by "various operations"?
The example code has check_current_task(), but I have no idea what does it do.

**Comment by palmtenor** [comment]
It checks if the task the BPF program running in is from the specified cgroup.
