### ISSUE TITLE
Do I need to manually detach an uprobe attached to a process after the process terminates?

### ISSUE THREAD

**Issue by yzhao1012** [iovisor/bcc#2640]
Hi All,

Let's say I have the following code:

`bpf.attach_uprobe("binary", "symbol", ...);  // pid is not provided`

Launch "binary", and this uprobe is triggered.
After the command finishes, do I need to manually call detach_uprobe on the pid just exists? Or Kernel will do that automatically?

**Comment by palmtenor** [comment]
In your case the uprobe is attached to the file (inode). As long as the inode does not change, all future processes mapping the file will have the uprobe.
You may read https://www.kernel.org/doc/Documentation/trace/uprobetracer.txt . BPF is on top of the generic uprobe

**Comment by yzhao1012** [comment]
As always, thanks for your prompt answer, Teng!

> "uprobe is attached to the file (inode)"
Are there more pointers to the details of uprobe's underlying mechanisms?

> As long as the inode does not change, all future processes mapping the file will have the uprobe.
Yes, that's what we observed as well. While any new processes that invoked with the executable triggers previously-attached uprobes.

Our confusion is around the case when a process with the attached uprobes, exits later. Is there any dangling resources inside kernel or user-space that we should manually release with BPF::detach_uprobe()?

**Comment by palmtenor** [comment]
If the target process exits, you still need to clean up, especially if you are using global uprobe not tied to the process.

If BCC exists abnormally like it crashed, if you are using the `debugfs`-file-based uprobe, then yes, the uprobe will still exist from the system's perspective and would still take effect on the attached binary. If you are using Perf Event-based uprobe, then even if BCC crashes it should be cleaned by by the Kernel, and that is exactly one of the reason we prefer Perf Event based probes.
