### ISSUE TITLE
If the load address is not set to 0 in libc elf, the offset of symbols cannot retrieve correctly 

### ISSUE THREAD

**Issue by jason-chenyixi-chengdu** [iovisor/bcc#2648]
Hi,
When I tried to deploy bcc in an embedded system, i found that invalid argument error orrcured. After troubleshooting, I found that is the offset of 'malloc'(i tried to execute memleak) in libc.so is bigger than the size of libc. That is because the load address is not set to 0 in my libc, so the value of malloc in symbol table is not offset. What i have done to fix it is retrieve the base load address from programe header first, then substracted the value by the base address.

**Comment by palmtenor** [comment]
Are you talking about symbol resolution or attaching uprobe? What tool / code are you using, ang what invalid argument error exactly?

**Comment by yonghong-song** [comment]
@jason-chenyixi-chengdu Could you show more details of `load address` and what the symbol values will look like in your symbol table? I would like to know whether the problem you saw is common or just due to some linker script tinkering or something else.

**Comment by jason-chenyixi-chengdu** [comment]
The program header and symbol tables in elf of libc.so is like below. As the virtAddr is start from 0,  the value of malloc cannot be set as offset in libc.so. The offset should be 0x34fd27b330-(0x34fd200040-0x40) in my case. The code impacted should be in src/cc/bcc_elf.c
Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  PHDR           0x0000000000000040 0x00000034fd200040 0x00000034fd200040
                 0x0000000000000230 0x0000000000000230  R E    8
.....
 00000034fd27b330   385 FUNC    GLOBAL DEFAULT   12 malloc

**Comment by yonghong-song** [comment]
Could you share your proposed code change?

**Comment by palmtenor** [comment]
I'd wish we keep `bcc_elf.c` as purely interacting with the ELF file (i.e. load symbol table, and for this case read program header), and maybe leave the translation to resolution. I think `ProcSym::Module` would be a good place keep load information and translate it when requested a name->addr resolution, which the uprobe code uses.

Do you feel like making the change? Or I could make that fix

**Comment by jason-chenyixi-chengdu** [comment]
My update in bcc_elf.h is like bellow, of cause you can fix it in other scritpt.


static int listsymbols(Elf *e, bcc_elf_symcb callback, void *payload,
                       struct bcc_symbol_option *option)
....
if(!gelf_getehdr(e, ehder)){
    return -1
  }
  gelf_getphdr(e, e_phoff, phdr);
  base_address = phdr[0].p_vaddr-phdr[0].p_offset; //get base address from program header
.....
int rc = list_in_scn(e, section, header.sh_link, header.sh_entsize,
                         option, callback, payload, base_address); //add a new argument base_address
 if (rc == 1)
      break;    // callback signaled termination
.......
static int list_in_scn(Elf *e, Elf_Scn *section, size_t stridx, size_t symsize,
                       struct bcc_symbol_option *option,
                       bcc_elf_symcb callback, void *payload, GElf_Addr base_address) {
...
if (callback(name, sym.st_value - base_address, sym.st_size, payload) < 0)//update second argument as  sym.st_value - base_address
        return 1;      // signal termination to caller
    }
  }

**Comment by yonghong-song** [comment]
@jason-chenyixi-chengdu thanks for explanation. I guess you must use a customized linker script so common libc symbols not in the segment starts with load address 0. The common distro like fedora, ubuntu should have address 0 for common symbols like malloc. But I agree that we probably should fix this in bcc. I think either you or @palmtenor can help. Thanks!

**Comment by jason-chenyixi-chengdu** [comment]
yes, the libc what we used is built by ourselves. All the changes are in attachment
