### ISSUE TITLE
Unable to read function arguments using uprobe's in Go binaries

### ISSUE THREAD

**Issue by grantseltzer** [iovisor/bcc#2656]
I have been trying to write uprobes that will print arguments to function arguments in go binaries. I however have not been able to use the `PT_REGS_PARM` macros, or getting them from registers directly. The data that is returned is inaccurate. I know go does a lot of moving the stack around, but from what I can tell uprobes should still work (uretprobes also ofc do not work). 

I've tried using both go bcc bindings and using `tools/trace.py`.

See example I'm working with:

Test program i'm attaching uprobe to:
 ```
//go:noinline
func test_function(x int) {
    x++
}

func main() {
    test_function(5)
}
```

How i'm loading uprobe

```
package main

import (
	"log"
	"os"
	"time"
	"path/filepath"
	bpf "github.com/iovisor/gobpf/bcc"
)

import "C"

const bpfText string = `
#include <uapi/linux/ptrace.h>

int print_symbol_arg(struct pt_regs *ctx) {
	bpf_trace_printk("%d\n", PT_REGS_PARM1(ctx));
	return 0;
}
`

func main() {

	binaryPath, err := filepath.Abs(os.Args[1])
	if err != nil {
		log.Fatal(err)
	}

	bpfModule := bpf.NewModule(bpfText, []string{})
	defer bpfModule.Close()

	uprobeFd, err := bpfModule.LoadUprobe("print_symbol_arg")
	if err != nil {
		log.Fatal(err)
	}

	err = bpfModule.AttachUprobe(binaryPath, "main.test_function", uprobeFd, -1)
	if err != nil {
		log.Printf("could not attach uprobe to symbol: %s: %s", "test_function", err)
	}

	time.Sleep(time.Hour)
}
```

After starting the program which loads the uprobe, running the test program binary will cause the uprobe to trigger properly, but will print out 72.

or with trace.py:
```
host grant in ~> test-prog on ~> master 
[*] sudo trace.py './test-prog:main.test_function "%d" arg1'                     
PID     TID     COMM            FUNC             -
656332  656332  test-prog       main.test_function 72
```

Does anyone know of recent changes in the go runtime that would be throwing off the arg macros?

EDIT: i'm on linux 5.3.8-300

**Comment by andreimatei** [comment]
Go's gc compiler doesn't use the standard calling conventions. Instead, all arguments are passed on the stack (instead of through registers). That's why simply using `PT_REGS_PARM1` doesn't work. You need to know the stack position relative to the `sp` register, and cast that to the type of the argument.

**Comment by grantseltzer** [comment]
Thank you @andreimatei! I've been working on manually getting arguments from Go programs, interesting how they did it that way. 

I think this is closable, this is more so an issue with uprobes and go than bcc.
