### ISSUE TITLE
Cannot get the correct module name if CONFIG_MM_INFO is configured

### ISSUE THREAD

**Issue by jason-chenyixi-chengdu** [iovisor/bcc#2668]
Hi,
In my system, if CONFIG_MM_INFO is configured as y in kernel configuration, there will be more columns in `/proc/<pid>/maps`, just like below. So module name cannot be got correctly since the format is not match `%lx-%lx %4s %llx %lx:%lx %lu%[^\n]` defined in bcc_proc.c. 
```
7fbb1b6ac000-7fbb1b843000 r-xp 00000000 08:00 132558  00000075 00000025 14781 /lib/libc-2.24.so
7fbb1b843000-7fbb1ba42000 ---p 00197000 08:00 132558  00000070 00000120 14781 /lib/libc-2.24.so
```

**Comment by palmtenor** [comment]
Good to know about this. AFAICT this is not a [documented behavior of `procfs`](http://man7.org/linux/man-pages/man5/proc.5.html). Is this something new?

**Comment by jason-chenyixi-chengdu** [comment]
Just got to know, this parameter is function developed in our own kernel, not isn any distribute version. So we need to update it in our side. Thanks!
