### ISSUE TITLE
mismatch structure size between bpf syscall and bpf program in bcc

### ISSUE THREAD

**Issue by yonghong-song** [iovisor/bcc#269]
For structure like:
struct routing_key_1 {
    u32 key_field_1;
    char key_field_0[6];
};

LLVM IR:
%struct.routing_key_1 = type { i32, [6 x i8] }

The bcc compiler infers size 12 and uses it for bpf create_map syscall.
The bpf program itself, however, uses the size 10. This mismatch
causes verifier failure.

To reproduce:
yhs@ubuntu:~/work/bcc/examples$ cat t.c
# include <uapi/linux/bpf.h>
# include <uapi/linux/if_ether.h>
# include <uapi/linux/if_packet.h>
# include <uapi/linux/ip.h>
# include <linux/skbuff.h>
# include <linux/netdevice.h>
# include <linux/pkt_cls.h>

enum ErrorCode {
    p4_pe_no_error,
    p4_pe_index_out_of_bounds,
    p4_pe_out_of_packet,
    p4_pe_header_too_long,
    p4_pe_header_too_short,
    p4_pe_unhandled_select,
    p4_pe_checksum,
};
# define EBPF_MASK(t, w) ((((t)(1)) << (w)) - (t)1)
# define BYTES(w) ((w + 7) / 8)

struct ethernet_t {
    char dstAddr[6]; /\* 48 bits _/
    u8 valid; /_ 1 bits _/
};
struct standard_metadata_t {
    u16 ingress_port; /_ 9 bits _/
    u32 packet_length; /_ 32 bits _/
    u16 egress_spec; /_ 9 bits _/
    u16 egress_port; /_ 9 bits _/
    u32 egress_instance; /_ 32 bits _/
    u32 instance_type; /_ 32 bits _/
    u32 clone_spec; /_ 32 bits _/
    u8 _padding; /_ 5 bits _/
};
struct ipv4_t {
    u32 srcAddr; /_ 32 bits _/
    u8 valid; /_ 1 bits */
};
struct ebpf_headers_t {
    struct ethernet_t ethernet;
    struct ipv4_t ipv4;
};
struct ebpf_metadata_t {
    struct standard_metadata_t standard_metadata;
};
struct routing_key_1 {
    u32 key_field_1;
    char key_field_0[6];
};
enum routing_actions_0 {
    routing_nop,
};
struct routing_value_2 {
    u32 action;
    union {
        struct {
        } nop;
    } u;
};
BPF_TABLE("hash", struct routing_key_1, struct routing_value_2, routing, 512);
BPF_TABLE("array", u32, struct routing_value_2, ebpf_routing_miss, 1);

int ebpf_filter(struct __sk_buff\* ebpf_packet) {
    struct ebpf_headers_t ebpf_headers = {
        .ethernet = {
            .valid = 0
        },
        .ipv4 = {
            .valid = 0
        },
    };
    struct ebpf_metadata_t ebpf_metadata = {
        .standard_metadata = {
            .ingress_port = 0,
            .packet_length = 0,
            .egress_spec = 0,
            .egress_port = 0,
            .egress_instance = 0,
            .instance_type = 0,
            .clone_spec = 0,
            ._padding = 0,
        },
    };
    unsigned ebpf_packetOffsetInBits = 0;
    enum ErrorCode ebpf_error = p4_pe_no_error;
    u8 ebpf_drop = 0;
    u32 ebpf_zero = 0;

```
goto start;
start: {
    goto parse_ethernet;
}
parse_ethernet: {
    if (ebpf_packet->len < BYTES(ebpf_packetOffsetInBits + 48)) {
        ebpf_error = p4_pe_header_too_short;
        goto end;
    }
    ebpf_headers.ethernet.dstAddr[0] = (u8)((load_byte(ebpf_packet, (ebpf_packetOffsetInBits / 8) + 0) >> 0));
    ebpf_headers.ethernet.dstAddr[1] = (u8)((load_byte(ebpf_packet, (ebpf_packetOffsetInBits / 8) + 1) >> 0));
    ebpf_headers.ethernet.dstAddr[2] = (u8)((load_byte(ebpf_packet, (ebpf_packetOffsetInBits / 8) + 2) >> 0));
    ebpf_headers.ethernet.dstAddr[3] = (u8)((load_byte(ebpf_packet, (ebpf_packetOffsetInBits / 8) + 3) >> 0));
    ebpf_headers.ethernet.dstAddr[4] = (u8)((load_byte(ebpf_packet, (ebpf_packetOffsetInBits / 8) + 4) >> 0));
    ebpf_headers.ethernet.dstAddr[5] = (u8)((load_byte(ebpf_packet, (ebpf_packetOffsetInBits / 8) + 5) >> 0));
    ebpf_packetOffsetInBits += 48;
    ebpf_headers.ethernet.valid = 1;
    goto parse_ipv4;
}
parse_ipv4: {
    if (ebpf_packet->len < BYTES(ebpf_packetOffsetInBits + 32)) {
        ebpf_error = p4_pe_header_too_short;
        goto end;
    }
    ebpf_headers.ipv4.srcAddr = ((load_word(ebpf_packet, (ebpf_packetOffsetInBits + 0) / 8)) >> (0));
    ebpf_packetOffsetInBits += 32;
    ebpf_headers.ipv4.valid = 1;
    goto routing_3;
}
{
    u8 ebpf_hit;
    struct routing_key_1 key;
    struct routing_value_2 *value;

    routing_3:
    /* construct key */
    memcpy(&key.key_field_0, &ebpf_headers.ethernet.dstAddr, 6);
    key.key_field_1 = (ebpf_headers.ipv4.srcAddr);
    ebpf_hit = 1;
    /* perform lookup */
    value = routing.lookup(&key);
    if (value == NULL) {
        ebpf_hit = 0;
        /* miss; find default action */
        value = ebpf_routing_miss.lookup(&ebpf_zero);
    }
    if (value != NULL) {
        /* run action */
        switch (value->action) {
            case routing_nop: 
            {
            }
            goto end;
        }
    }
}
end:
if (!ebpf_drop)
    bpf_clone_redirect(ebpf_packet, ebpf_metadata.standard_metadata.egress_port, 0);
return TC_ACT_SHOT /* drop packet; clone is forwarded */;
```

}
yhs@ubuntu:~/work/bcc/examples$ cat ex1.py
# !/usr/bin/python

from bcc import BPF
b = BPF(src_file="t.c")
b.load_func("ebpf_filter", BPF.SCHED_CLS)
yhs@ubuntu:~/work/bcc/examples$ sudo python ./ex1.py
bpf: Permission denied
0: (bf) r6 = r1
1: (b7) r1 = 0
2: (7b) *(u64 *)(r10 -8) = r1
3: (7b) *(u64 *)(r10 -16) = r1
4: (63) *(u32 *)(r10 -20) = r1
5: (61) r7 = *(u32 *)(r6 +0)
6: (b7) r1 = 6
7: (2d) if r1 > r7 goto pc+35
 R1=imm6 R6=ctx R7=inv R10=fp
8: (30) r0 = *(u8 *)skb[0]
9: (73) *(u8 *)(r10 -16) = r0
10: (30) r0 = *(u8 *)skb[1]
11: (73) *(u8 *)(r10 -15) = r0
12: (30) r0 = *(u8 *)skb[2]
13: (73) *(u8 *)(r10 -14) = r0
14: (30) r0 = *(u8 *)skb[3]
15: (73) *(u8 *)(r10 -13) = r0
16: (30) r0 = *(u8 *)skb[4]
17: (73) *(u8 *)(r10 -12) = r0
18: (30) r0 = *(u8 *)skb[5]
19: (73) *(u8 *)(r10 -11) = r0
20: (b7) r8 = 1
21: (73) *(u8 *)(r10 -10) = r8
22: (b7) r1 = 10
23: (2d) if r1 > r7 goto pc+19
 R0=inv R1=imm10 R6=ctx R7=inv R8=imm1 R10=fp
24: (20) r0 = *(u32 *)skb[6]
25: (63) *(u32 *)(r10 -8) = r0
26: (73) *(u8 *)(r10 -4) = r8
27: (69) r1 = *(u16 *)(r10 -12)
28: (6b) *(u16 *)(r10 -24) = r1
29: (61) r1 = *(u32 *)(r10 -16)
30: (63) *(u32 *)(r10 -28) = r1
31: (63) *(u32 *)(r10 -32) = r0
32: (18) r1 = 0x773dc180
34: (bf) r2 = r10
35: (07) r2 += -32
36: (85) call 1
regno 2, invalid indirect read from stack off -32+10 size 12

Traceback (most recent call last):
  File "./ex1.py", line 4, in <module>
    b.load_func("ebpf_filter", BPF.SCHED_CLS)
  File "/usr/lib/python2.7/dist-packages/bcc/**init**.py", line 431, in load_func
    raise Exception("Failed to load BPF program %s" % func_name)
Exception: Failed to load BPF program ebpf_filter
yhs@ubuntu:~/work/bcc/examples$

**Comment by 4ast** [comment]
On Tue, Oct 13, 2015 at 10:29 AM, yonghong-song <notifications@github.com>
wrote:

> For structure like:
> struct routing_key_1 {
> u32 key_field_1;
> char key_field_0[6];
> };
>
> LLVM IR:
> %struct.routing_key_1 = type { i32, [6 x i8] }
>
> The bcc compiler infers size 12 and uses it for bpf create_map syscall.
> The bpf program itself, however, uses the size 10. This mismatch
> causes verifier failure.
>

I don't see how this is a bcc bug.
The sizeof struct is 12 and map is created with key=12.
The padding is not inited by compiler.

**Comment by yonghong-song** [comment]
Oh, an uninitialized access (to padding) bug inherited in LLVM?

**Comment by yonghong-song** [comment]
My original statement:
>The bcc compiler infers size 12 and uses it for bpf create_map syscall.
>The bpf program itself, however, uses the size 10. This mismatch
>causes verifier failure.
is not correct. structure size is still 12, but bpf program only initializes size 10
and did not initialize the padding. And this caused the verification failure.

**Comment by 4ast** [comment]
it's not an llvm bug. compiler is allowed not to init the padding.
So it's really user bug. The fix:
- init the struct fully in user code
- add automatic pad generators in bcc rewriter
- teach llvm to init the whole thing
Last one is very hard, since it's front-end work and cannot really be
done by backend.

Iooking at the source code:

struct routing_key_1 key;
memcpy(&key.key_field_0, &ebpf_headers.ethernet.dstAddr, 6);
key.key_field_1 = (ebpf_headers.ipv4.srcAddr);

clearly last 4 bytes will not be inited.

**Comment by brendangregg** [comment]
Thanks @4ast, so not a bcc bug, closing.

Referenced by #382.
