### ISSUE TITLE
Could bcc load compiled ebpf program file

### ISSUE THREAD

**Issue by YanzhaoLi** [iovisor/bcc#2700]
I'd like to run bcc programs on hosts where `linux-$(uname -r)-headers` is not installed.
Currently we need install `linux-$(uname -r)-headers` into the hosts for bcc to compile the ebpf program. But sometimes we don't want install the headers, in such case we need compile them in advance and then be loaded.

**Comment by palmtenor** [comment]
Please take a look at https://facebookmicrosites.github.io/bpf/blog/2020/02/19/bpf-portability-and-co-re.html
