### ISSUE TITLE
Command executing failed on AArch64

### ISSUE THREAD

**Issue by jason-chenyixi-chengdu** [iovisor/bcc#2707]
Hi,
I have deployed bcc on arm64. But when i executed a BCC tool, below error is raised. Could anyone help to check? Thanks!
```
 #./syncsnoop
Could not create ExecutionEngine: Interpreter has not been linked in.
Segmentation fault
```

**Comment by jason-chenyixi-chengdu** [comment]
Just found that if disable rw engine, this problem is solved. But i wonder what this rw engine used in bcc?

**Comment by yonghong-song** [comment]
The rw engine is mostly used for python interface to translate between the key/value of their natural type and its string representation. You can check an example in test_clang.py, e.g., function `test_sscanf()`, `test_sscanf_array()` and `test_sscanf_string()`.

**Comment by jason-chenyixi-chengdu** [comment]
OK, I will check. Thanks!
