### ISSUE TITLE
Unknown error -1; Couldn't set RLIMIT_MEMLOCK for bpftrace.

### ISSUE THREAD

**Issue by nagmat1** [iovisor/bcc#2718]
while trying : 
sudo bpftrace -v -e 'tracepoint:syscalls:sys_enter_nanosleep { printf(%s is sleeping.\n",comm); }' 
got : 
Unknown error -1 : Couldn't set RLIMIT_MEMLOCK for bpftrace. If your program is not loading, you can try "ulimit -l 8192" to fix the problem
fatal error : '/lib/modules/5.3.0-26-generic/build/include/linux/kconfig.h' file not found. 

Have tried "ulimit -l 8102" but did not help. 

What may be the problem?

**Comment by yonghong-song** [comment]
This is related to bpftrace. Could you post in iovisor/bpftrace page?

**Comment by nagmat1** [comment]
Could you erase this issue, cos I transferred it to bpftrace issue.
