### ISSUE TITLE
Example video unavailable

### ISSUE THREAD

**Issue by gtataranni** [iovisor/bcc#2722]
The example video mentioned in the README.md
`examples/networking/tunnel_monitor/: Efficiently monitor traffic flows. Example video.` at https://www.youtube.com/watch?v=yYy3Cwce02k is unavailable

**Comment by yonghong-song** [comment]
We may need to delete this link. Do you want to help with a pull request? Thanks!

**Comment by gtataranni** [comment]
I was hoping someone had a working link, or could re-upload the video, but sure
