### ISSUE TITLE
stackcount: address resolution for user-space stack

### ISSUE THREAD

**Issue by rohgarg** [iovisor/bcc#2748]
I was playing around with `stackcount` when I noticed this issue: address-to-symbol
resolution doesn't work for user-space stacks without the "-P" flag when tracing
single, isolated processes. I'm not sure if this is the expected usage.

For example, the following command is unable to resolve addresses to symbols.

```bash
# # a.out is a simple hello-world program
# python stackcount -p `pgrep a.out` -s -U c:malloc
Tracing 1 functions for "c:malloc"... Hit Ctrl-C to end.

  7f35f5cef2c0     [unknown]
  7f35f5c791e3     [unknown]
  ...
```

Perhaps the documentation for the "-P" option could be improved to indicate
that it's a required parameter for resolving addresses when tracing single,
isolated processes. While the example provided in `stackcount_example.txt`
does use the "-P" option (`stackcount -P -p 4902 c:malloc`), it's not clear
why the option was used in the example. The current documentation just says:

> -P, --perpid          display stacks separately for each process

Another possible fix could be something along the lines of:

```patch
diff --git i/tools/stackcount.py w/tools/stackcount.py
index a58f9e31..d4284a38 100755
--- i/tools/stackcount.py
+++ w/tools/stackcount.py
@@ -358,7 +358,10 @@ class Tool(object):
                     if self.need_delimiter:
                         print("    --")
                     for addr in user_stack:
-                        self._print_uframe(addr, k.tgid)
+                        if self.args.perpid:
+                          self._print_uframe(addr, k.tgid)
+                        else:
+                          self._print_uframe(addr, self.args.pid)
                     if not self.args.pid and k.tgid != 0xffffffff:
                         self._print_comm(k.name, k.tgid)
                     print("    %d\n" % v.value)
```

For reference, this is the BPF program that `stackcount` generates in this case, without the "-P" option.

```C
#include <uapi/linux/ptrace.h>
#include <linux/sched.h>

struct key_t {
    // no pid (thread ID) so that we do not needlessly split this key
    u32 tgid;
    int kernel_stack_id;
    int user_stack_id;
    char name[TASK_COMM_LEN];
};

BPF_HASH(counts, struct key_t);
BPF_STACK_TRACE(stack_traces, 1024);

int trace_count(void *ctx) {
    struct key_t key = {};
    key.tgid = 0xffffffff; // Note that we explicitly set key.tgid to -1


                    key.user_stack_id = stack_traces.get_stackid(
                      ctx, BPF_F_USER_STACK
                    );key.kernel_stack_id = -1;
    counts.increment(key);
    return 0;
}
```

**Comment by yonghong-song** [comment]
Maybe if user specifies `-p <pid>`, perpid will be set to true if it is not. Otherwise, we can say it is an error. What do you think?

**Comment by rohgarg** [comment]
> Maybe if user specifies -p <pid>, perpid will be set to true if it is not.

@yonghong-song: That sounds like a reasonable option. I can generate a PR, if you'd like.
