### ISSUE TITLE
Can't include C standard header files

### ISSUE THREAD

**Issue by gfx** [iovisor/bcc#2753]
I'd like to use some standard C library functions in a BPF program, for example `sprintf(3)`, but `#include <...>` results in failure. Without C header files, I can actually use standard library functions by copying their declarations to the BPF program, but I'd like to use `#include <...>` instead.  Is there any way to use `#include`?

## How to reproduce this issue

Python script:

```python
#!/usr/bin/python
import bcc

bpf = """
#include <stdio.h>

int kprobe__sys_clone(void *ctx) {
        bpf_trace_printk("Hello, World!\\n");
        return 0;
}
"""
bcc.BPF(text=bpf).trace_print()
```

results:

```shell-session
/virtual/main.c:2:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
```

## Environment

* Ubuntu 19.10 
* bcc 0.12.0-0f92c845

**Comment by yonghong-song** [comment]
bcc mostly for tracing. Including standard files may cause type conflict. You could add additional include patch in BPF constructor in your case to see how it works.  Another option is to include `linux/kernel.h` which has kernel version of snprintf implementation.

**Comment by gfx** [comment]
@yonghong-song 

Thank you for the explanation! So if I can use `sprintf()`, it is not the one in libc's, right? `#include <linux/kernel.h>` works for me.
