### ISSUE TITLE
bpf() syscall fail with EAGAIN (Resource temporarily unavailable) when pprof is ON

### ISSUE THREAD

**Issue by yzhao1012** [iovisor/bcc#2785]
* We link [gperftools](https://github.com/gperftools/gperftools) with the binary that attaches kprobes.
* When turn on profiling `sudo CPUPROFILE=/tmp/pem.pprof <binary>`, we saw that one of the bpf() syscall constantly fail with `EAGAIN (Resource temporarily unavailable)`.
* When removing the CPUPROFILE=... the binary behaves normally, i.e., attaches the kprobe and moves on.

My question is that was there any known issues between gperftools' profiling runtime and bpf or BCC?

Any suggestions for debugging is greatly appreciated!

**Comment by yonghong-song** [comment]
Which bpf() syscall subcommand failed?

**Comment by yzhao1012** [comment]
Thanks!
Sorry, we lost track of this issue. It seems it's not showing up for a long time since the first report.
Close now.
I'll reopen with more information if this ever happens again.
