### ISSUE TITLE
lookup_or_try_init usage or trying to list all read and write kernel commands on vfs layer. 

### ISSUE THREAD

**Issue by nagmat1** [iovisor/bcc#2793]
I am planning to **list all read and write kernel commands on vfs layer** but having difficulties in understanding some commands in filetop.py
`struct val_t *valp, zero = {};
valp = counts.lookup_or_try_init(&info, &zero);`

Tried to implement some code to list all read and write kernel functions on virtual file system layer. 
`#VFS read_write profiler 

from __future__ import print_function
from bcc import BPF
from time import sleep,strftime
import argparse
import signal
from subprocess import call

loadavg = "/proc/loadavg"

#define BPF program
bpf_text= """ 
#include <uapi/linux/ptrace.h>
#include <linux/blkdev.h>

//the key for the output summary 
struct info_t {
    u32 pid;
    u32 name_len;
    char comm[TASK_COMM_LEN];
    char name[DNAME_INLINE_LEN];
    char type;
};

struct val_t{
    u32 tid;
    u64 size1;
    char oka;
};

BPF_HASH(counts, struct info_t);

static int do_entry(struct pt_regs *ctx, struct file *file, char __user *buf,size_t count, int oper)
{
    u32 pid = bpf_get_current_pid_tgid();   // Getting the process id
    
    struct dentry *de = file->f_path.dentry; // 
    int mode = file->f_inode->i_mode;
    struct qstr d_name = de->d_name;

    struct info_t info = {.pid = pid };
    bpf_get_current_comm(&info.comm, sizeof(info.comm));
    info.name_len = d_name.len;

    bpf_probe_read(&info.name,sizeof(info.name),d_name.name);
    if (S_ISREG(mode)) {
        info.type = 'R';
    } else if (S_ISSOCK(mode)) {
        info.type = 'S';
    } else { info.type= 'O';}
   
    struct val_t *valp,zero={};
    valp=counts.lookup_or_try_init(&info,&zero);
    if (valp) {
        if (oper) {
            valp->oka='R';
            valp->size1=count;
            valp->tid = bpf_get_current_pid_tgid() >> 32;  
        } else 
        {
            valp->oka='W';
            valp->size1=count;
            valp->tid= bpf_get_current_pid_tgid() >> 32;
        }
    }

    return 0; 
}

int trace_read_entry(struct pt_regs *ctx, struct file *file, char __user *buf, size_t count)
{
    return do_entry(ctx,file,buf,count,1);        
}

int trace_write_entry(struct pt_regs *ctx, struct file *file, char __user *buf, size_t count)
{
    return do_entry(ctx,file,buf,count,0);
}

"""

# initialize BPF
b = BPF( text = bpf_text )
b.attach_kprobe(event="vfs_read", fn_name="trace_read_entry")
b.attach_kprobe(event="vfs_write", fn_name="trace_write_entry")

DNAME_INLINE_LEN = 32 #linux/dcache.h

print('Tracing every 1 secs. Hit CTRL+C to end');

#output 
exiting=0 
clear =0
while 1: 
    try:
        sleep(1)
    except KeyboardInterrupt:
        exiting=1
    #header
    if clear:
        call("clear")
        #print('clear value %d ' %s (clear) )
    else: 
        print()
        print("%-6s %-6s %-6s %-16s %-6s %-3s %1s %s" % ("No","TID","PID","COMM","Size","R/W","T","FILE"))
        
        counts = b.get_table("counts")
        line = 0
        sayac=0
        for inf in counts.items():
            print('Baslady...')
            name = inf.name.decode('utf-8','replace')
            sayac+=1
            # print line
            print("%-6d %-6s %-6s %-16s %-6d %-3s %1s %s" % (sayac,inf.tid,inf.pid,inf.comm.decode('utf-8','replace'),info.size,info.oka, inf.type.decode('utf-8','replace'),name))
            
            line+=1

        counts.clear()

        if exiting : 
            exit()
`

**Comment by netedwardwu** [comment]
I don't really understand your problem....

Just simple code review...
```
valp=counts.lookup_or_try_init(&info,&zero);
if (valp) {
```
You don't have to check valp exist or not, because it will be initilizd after lookup_or_try_init()
