### ISSUE TITLE
Question: Is possible to send data from the python code (userland) to the ebpf program (kernel)

### ISSUE THREAD

**Issue by geoffreyPerrin** [iovisor/bcc#2796]
Hi,
I get data from the kernel with:
```
# loop with callback to print_event
b["events"].open_perf_buffer(print_event)
while 1:
    try:
        b.perf_buffer_poll()
    except KeyboardInterrupt:
        exit()
```
But can I send back data from python code to ebpf code (kernel) ?
Could the kernel wait for my response and then resume code execution ?

I'm actually tracing processes with the execve syscall. I want to analyse the process that will be executed by the syscall in my python code. Then send response to the kernel to stop or let the process start.
I have figured out how to prevent the process execution with:
`int bpf_override_return(struct pt_regs *, unsigned long rc)`

Thanks !

**Comment by yonghong-song** [comment]
> Hi,
> I get data from the kernel with:
> 
> ```
> # loop with callback to print_event
> b["events"].open_perf_buffer(print_event)
> while 1:
>     try:
>         b.perf_buffer_poll()
>     except KeyboardInterrupt:
>         exit()
> ```
> 
> But can I send back data from python code to ebpf code (kernel) ?

The typical way to send data back to kernel is write to a map and ebpf can respond to a map value change.

> Could the kernel wait for my response and then resume code execution ?

No. bpf program cannot be preempted. It needs to run to completion. 

> 
> I'm actually tracing processes with the execve syscall. I want to analyse the process that will be executed by the syscall in my python code. Then send response to the kernel to stop or let the process start.
> I have figured out how to prevent the process execution with:
> `int bpf_override_return(struct pt_regs *, unsigned long rc)`

You need to implement your logic inside the bpf program to decide whether to let process stop or go.

> 
> Thanks !

**Comment by geoffreyPerrin** [comment]
Thank you for your answer !
