### ISSUE TITLE
Grouped read of performance counters using BPF

### ISSUE THREAD

**Issue by nickjmeyer** [iovisor/bcc#2808]
I've been looking at the `llcstat` program as a guide for how to combine BPF and perf events.  I'm trying to build some libraries for sampling performance counters which is very similar to what `llcstat` does.  If I were to just use `perf_event_open`, I would open an event for the first counter.  Record the fd.  Then use that fd as the leader for the remaining counters.  That way all counters are grouped.  Per the documentation: 

> This means that the values of the member events can be meaningfully compared—added, divided (to get ratios), and so on—with each other, since they have counted events for the same set of executed instructions.
(Reference: http://man7.org/linux/man-pages/man2/perf_event_open.2.html)

However, when I look at the `llcstat` code, it looks like each call to `attach_perf_event` does not expose the fd created for a given event.  Thus it doesn't seem like the values that the counters record will be directly comparable even though the llcstat code combines cache references and cache misses to determine cache miss rate.

Is this reasoning correct?

If it is correct, what would be the correct way to group the counters so the values are directly comparable?  What would be the implication of exposing the leader fd and passing that as a group fd for all subsequent calls?  How would that affect the execution of the attached bpf program?

If that reasoning is not correct, then what causes the events to be grouped and the values to be comparable?

**Comment by yonghong-song** [comment]
> I've been looking at the `llcstat` program as a guide for how to combine BPF and perf events. I'm trying to build some libraries for sampling performance counters which is very similar to what `llcstat` does. If I were to just use `perf_event_open`, I would open an event for the first counter. Record the fd. Then use that fd as the leader for the remaining counters. That way all counters are grouped. Per the documentation:
> 
> > This means that the values of the member events can be meaningfully compared—added, divided (to get ratios), and so on—with each other, since they have counted events for the same set of executed instructions.
> > (Reference: http://man7.org/linux/man-pages/man2/perf_event_open.2.html)
> 
> However, when I look at the `llcstat` code, it looks like each call to `attach_perf_event` does not expose the fd created for a given event. Thus it doesn't seem like the values that the counters record will be directly comparable even though the llcstat code combines cache references and cache misses to determine cache miss rate.
> 
> Is this reasoning correct?

This should work on a x86 box where no other perf events on cache misses are running. Otherwise, your assessment is correct, multiplexing may cause different event triggering frequency, and in such cases, result will not be accurate.

> 
> If it is correct, what would be the correct way to group the counters so the values are directly comparable? What would be the implication of exposing the leader fd and passing that as a group fd for all subsequent calls? How would that affect the execution of the attached bpf program?

I think it is a good idea to get the result perf event fd back to application so that it can be used as a group leader.

Maybe we can return fd from attach_perf_event? Currently, nothing is returned. Adding a return value probably fine for existing python scripts?

> 
> If that reasoning is not correct, then what causes the events to be grouped and the values to be comparable?

**Comment by nickjmeyer** [comment]
I am indeed on an x86 box.  I've been playing a bit more with the tool and I'm seeing some weird data.  Maybe I'm misunderstanding how to interpret them.  In particular, I see cache misses far exceed cache references.  Sometimes by multiples as high as 2-10 times.  The script right now reports hit rate.  So it subtracts misses from references as long as misses do not exceed references.  If they do exceed references, then it truncates to zero for a hit rate.  However, if you print out the actual values for misses and references.  The results are odd.

Here is the relevant code snippet
https://github.com/iovisor/bcc/blob/master/examples/cpp/LLCStat.cc#L108
```
  for (auto it : refs.get_table_offline()) {
    uint64_t hit;
    try {
      auto miss = misses[it.first];
      hit = miss <= it.second ? it.second - miss : 0;
    } catch (...) {
      hit = it.second;
    }
    double ratio = (double(hit) / double(it.second)) * 100.0;
    std::cout << "PID " << std::setw(8) << std::setfill(' ') << it.first.pid;
    std::cout << std::setw(20) << std::setfill(' ') << std::left
              << " (" + std::string(it.first.name) + ") " << std::right;
    std::cout << "on CPU " << std::setw(2) << std::setfill(' ') << it.first.cpu;
    std::cout << " Hit Rate " << std::setprecision(4) << ratio << "% ";
    std::cout << "(" << hit << "/" << it.second << ")" << std::endl;
  }
```

If I instead change this the following which will show both hit rate and miss rate, then it shows how extreme the misses can be relative to the references.
```
  for (auto it : refs.get_table_offline()) {
    {
      uint64_t hit;
      try {
        auto miss = misses[it.first];
        hit = miss <= it.second ? it.second - miss : 0;
      } catch (...) {
        hit = it.second;
      }
      double ratio = (double(hit) / double(it.second)) * 100.0;
      std::cout << "PID " << std::setw(8) << std::setfill(' ') << it.first.pid;
      std::cout << std::setw(20) << std::setfill(' ') << std::left
                << " (" + std::string(it.first.name) + ") " << std::right;
      std::cout << "on CPU " << std::setw(2) << std::setfill(' ') << it.first.cpu;
      std::cout << " Hit Rate  " << std::setprecision(4) << ratio << "% ";
      std::cout << "(" << hit << "/" << it.second << ")" << std::endl;
    }
    {
      uint64_t miss{0};
      if (misses.get_value(it.first, miss).code() != 0)
      {
        miss = 0;
      }
      double ratio = (double(miss) / double(it.second)) * 100.0;
      std::cout << std::setw(52) << std::setfill(' ');
      std::cout << " Miss Rate " << std::setprecision(4) << ratio << "% ";
      std::cout << "(" << miss << "/" << it.second << ")" << std::endl;
    }
  }
```
Some look like reasonable values
```
PID    44079 (sh)               on CPU 14 Hit Rate  91.25% (7300/8000)
                                          Miss Rate 8.75% (700/8000)
```

Some look very extreme which makes me second guess if its accurate or not
```
PID    39048 (chrome)           on CPU  6 Hit Rate  0% (0/1900)
                                          Miss Rate 578.9% (11000/1900)
```

I tried modifying the API to return the FD to use as a leader.  Then starting the events as disabled through the `attr` struct, enabling the leader FD through `ioctl`, probing for N seconds, disabling the leader, and then finally detaching all events.  However, this shows similar distributions of data.

One thing I've noticed that seems to impact this is whether or not the event is for all `pid`s or for a specific `pid`.  I tried comparing results with `pid=-1` and `pid=53047` which corresponded to my emacs daemon.  I ran it both ways 4 times each (not the most rigorous study, but its something).

Here are some results when I specify the pid.
```
$ sudo ./examples/cpp/LLCStat 10
Probing for 10 seconds
PID    53047 (emacs)            on CPU  0 Hit Rate  24.54% (34300/139800)
                                          Miss Rate 75.46% (105500/139800)
$ sudo ./examples/cpp/LLCStat 10
Probing for 10 seconds
PID    53047 (emacs)            on CPU  2 Hit Rate  0% (0/15900)
                                          Miss Rate 100% (15900/15900)
PID    53047 (emacs)            on CPU  0 Hit Rate  0% (0/31800)
                                          Miss Rate 100% (31800/31800)
$ sudo ./examples/cpp/LLCStat 10
Probing for 10 seconds
PID    53047 (emacs)            on CPU  4 Hit Rate  0% (0/31800)
                                          Miss Rate 100% (31800/31800)
PID    53047 (emacs)            on CPU  5 Hit Rate  0% (0/15900)
                                          Miss Rate 100% (15900/15900)
$ sudo ./examples/cpp/LLCStat 10
Probing for 10 seconds
PID    53047 (emacs)            on CPU  6 Hit Rate  19.31% (5600/29000)
                                          Miss Rate 80.69% (23400/29000)
PID    53047 (emacs)            on CPU  5 Hit Rate  9.748% (3100/31800)
                                          Miss Rate 90.25% (28700/31800)
```

Here are the results with `pid=-1` but filtered for the same `pid` above.
```
$ sudo ./examples/cpp/LLCStat 10 | grep -A 1 "emacs"
PID    53047 (emacs)            on CPU 11 Hit Rate  0% (0/46100)
                                          Miss Rate 102.6% (47300/46100)
$ sudo ./examples/cpp/LLCStat 10 | grep -A 1 "emacs"
PID    53047 (emacs)            on CPU 13 Hit Rate  0% (0/48900)
                                          Miss Rate 103.7% (50700/48900)
$ sudo ./examples/cpp/LLCStat 10 | grep -A 1 "emacs"
PID    53047 (emacs)            on CPU 13 Hit Rate  0% (0/13500)
                                          Miss Rate 117% (15800/13500)
$ sudo ./examples/cpp/LLCStat 10 | grep -A 1 "emacs"
PID    53047 (emacs)            on CPU 14 Hit Rate  0% (0/74000)
                                          Miss Rate 134.3% (99400/74000)
--
PID    53047 (emacs)            on CPU 13 Hit Rate  2.642% (700/26500)
                                          Miss Rate 97.36% (25800/26500)
--
PID    53047 (emacs)            on CPU  2 Hit Rate  0% (0/7200)
                                          Miss Rate 100% (7200/7200)
--
PID    53047 (emacs)            on CPU 15 Hit Rate  0% (0/589600)
                                          Miss Rate 109.1% (643000/589600)
```

It's interesting that running with a specified `pid` seems to max out at 100% miss rate, but when recording all `pid`s and looking at the same `pid` the values exceed 100% quite often.  Maybe there is something wrong with the keys that are used to aggregate the data?

**Comment by yonghong-song** [comment]
Yes, this tool does have some pitfalls. the perf event is triggered at NMI context. For example, the perf_event is triggered by a softirq, and then cache miss/hit is attributed to the process underlying the softirq. But the cache miss/hit is not really generated by that process. This will skew the results.

**Comment by nickjmeyer** [comment]
Ah that makes sense.  So while you can figure out which process triggered the event, you still can't properly attribute the correct counter value by process.  

So is the only way to get accurate per-process counters is to open up a new event for each one?  My goal is to get per process data at a relatively course sampling rate (maybe 1Hz).  I'm guessing the best way to do this is to read `/proc` to enumerate the PIDs then open up a perf event for each one and read directly from the FD?  Originally I was hoping BPF would allow me to subscribe to all PIDs (e.g., pass `pid=-1`) and the filter in the BPF event handler.  Do you see any other way to leverage BPF here?  Or should I just use the `/proc` + raw perf events route?

**Comment by yonghong-song** [comment]
> So is the only way to get accurate per-process counters is to open up a new event for each one? 

It looks so. per-process perf event is the way to ensure we do not attirbute perf event results to wrong processes.

In bpf world, you can still create perf events for a lot of processes simultaneously. the same bpf programs can be attached to all perf_events with the same as events. this way, bpf program can do accounting in the kernel for you with pid as the key. kernel will do multiplexing since a lot of perf events shared the same hardware counter. But this should reflect in the number of bpf prog invocations for different processes.  So the only difference is to read from user space vs. from kernel. Maybe this can save a little bit time, not sure how much.

**Comment by nickjmeyer** [comment]
That makes sense.  So given that I'm binning processes, it could save some work by having that binning be done inside the BPF program instead of reading perf events for every process and then binning in user space.

Would be interesting to know how the workload compares between the two.  Might need to experiment a little.

Anyway, thanks for your help on this.  Much appreciated.
