### ISSUE TITLE
how to convert bpf_ktime_get_ns() value into normal time?

### ISSUE THREAD

**Issue by nagmat1** [iovisor/bcc#2813]
I am trying to make profiles of I/O commands. I get the bpf_ktime_get_ns() value every time but do not know how can I convert it to normal time like 01:07:00 05:03...

**Comment by yonghong-song** [comment]
People typically get a reference time at user space, say, at the attach time, and in bpf program, you calculate the bpf_ktime_get_ns() difference, and use the different and reference time to calculate the time. This is not precise, but should work in most cases.
