### ISSUE TITLE
Documentation: indicate CONFIG_BPF_SYSCALL=y required in kernel config

### ISSUE THREAD

**Issue by troyengel** [iovisor/bcc#283]
I think I just wasted a good 4-6 hours debugging python wondering why this was falling flat on it's face for me trying to run hello_world.py. :) The kernel *must* have CONFIG_BPF_SYSCALL=y set in order to enable the requisite code -- the general Arch kernel doesn't have it set (only CONFIG_BPF=y), and the error you're presented with gives no clue to the new-to-this user like myself.

````
# python2 hello_world.py 
bpf: Function not implemented

Traceback (most recent call last):
  File "hello_world.py", line 11, in <module>
    BPF(text='void kprobe__sys_clone(void *ctx) { bpf_trace_printk("Hello, World!\\n"); }').trace_print()
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 396, in __init__
    self._trace_autoload()
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 629, in _trace_autoload
    fn = self.load_func(func_name, BPF.KPROBE)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 431, in load_func
    raise Exception("Failed to load BPF program %s" % func_name)
Exception: Failed to load BPF program kprobe__sys_clone
````

From Brendan's slide deck from the Plumber's conference without using the kprobe__ autoloader:
````
# python2 hello.py 

Traceback (most recent call last):
  File "hello.py", line 10, in <module>
    fn = b.load_func("hello", BPF.KPROBE)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 431, in load_func
    raise Exception("Failed to load BPF program %s" % func_name)
Exception: Failed to load BPF program hello
````

I've opened an Issue in the Arch kernel to get this enabled. This should be documented in the INSTALL.md or somesuch to help the next person out...

**Comment by drzaeus77** [comment]
Ouch, sorry. Let me see about adding a sanity check and a more meaningful error message, as well as the docs.

**Comment by xyzora** [comment]
Hi I am using amazon linux and I dowloaded bcc as "Fedora - Binary" per https://github.com/iovisor/bcc/blob/master/INSTALL.md.

But I got error "Failed to load BPF program kprobe__sys_clone" when I run hello_world.py (see attached)

Can you pls shed some lights what s wrong with my settings?
thanks
Jeffrey
1) OS version:
uname -a
Linux ip-172-31-1-170 4.4.23-31.54.amzn1.x86_64 #1 SMP Tue Oct 18 22:02:09 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

2) and my OS compilation flags are: 
grep BPF /boot/config-4.4.23-31.54.amzn1.x86_64
CONFIG_BPF=y
CONFIG_BPF_SYSCALL=y
CONFIG_NETFILTER_XT_MATCH_BPF=m
CONFIG_NET_CLS_BPF=m
CONFIG_NET_ACT_BPF=m
CONFIG_BPF_JIT=y
CONFIG_HAVE_BPF_JIT=y
CONFIG_BPF_EVENTS=y
# CONFIG_TEST_BPF is not set

3) Errors got
./hello_world.py
bpf: Invalid argument

Traceback (most recent call last):
  File "./hello_world.py", line 11, in <module>
    BPF(text='int kprobe__sys_clone(void *ctx) { bpf_trace_printk("Hello, World!\\n"); return 0; }').trace_print()
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 247, in __init__
    self._trace_autoload()
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 845, in _trace_autoload
    fn = self.load_func(func_name, BPF.KPROBE)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 290, in load_func
    raise Exception("Failed to load BPF program %s: %s" % (func_name, errstr))
Exception: Failed to load BPF program kprobe__sys_clone: Invalid argument

**Comment by palmtenor** [comment]
@4ast Does it make sense for us to add more detailed `printk` messages in BPF sys calls? For this particular case it feels pretty hard to identify which `EINVAL` case was happening in the program load sys call.

**Comment by 4ast** [comment]
in this case it's not clear to me what is the problem. Looks like it's not root under root or what?
Thought root should have been eperm instead of einval...
in general, yes, we need to make errors more verbose.
