### ISSUE TITLE
Cmake Error of LibElf

### ISSUE THREAD

**Issue by simransinghal** [iovisor/bcc#2835]
Cmake Error of LibElf evn though it is installed.
Followed the steps given in the following link:-
https://github.com/iovisor/bcc/blob/master/INSTALL.md#ubuntu---source

```
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find LibElf (missing: LIBELF_LIBRARIES)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindLibElf.cmake:50 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:48 (find_package)
```

**Comment by yonghong-song** [comment]
@olsajiri could you help take a look?

**Comment by devidasjadhav** [comment]
this is strange 
as  following command should have installed libelf headers.


```
apt-get install libelf-dev
```

try above command and  do update whether this solves the problem.
Please update exact version of distro.

**Comment by simransinghal** [comment]
@yonghong-song @devidasjadhav I am able to resolve this issue.
Actually, I was working under Conda environment. Deactivating conda works for me.
