### ISSUE TITLE
how to print events on vfs layer and ext4 layer at the same time. 

### ISSUE THREAD

**Issue by nagmat1** [iovisor/bcc#2842]
I am trying to make some experiments using eBPF. I wanted to print events on vfs layer and ext4 layer trying to compare some values. The print is done on tmpfs not to disturb file system. I have merged codes of file_slow and ext4_slow files. As a result I can see the file slow results but unfortunately it doesn't print ext4 results. 

[vfs_and_ext_anal.txt](https://github.com/iovisor/bcc/files/4496162/vfs_and_ext_anal.txt)

**Comment by devidasjadhav** [comment]
output
--------
this is out put of attached code.

R    ->   vfs_read
W    ->  vfs_write
ER   ->  ext4_iter_read
EW   ->  ext4_iter_write

```
dev@debian:~/DATA/workspace/git/devbcc$ sudo ./tools/fileslower.py 1
Tracing sync read/writes slower than 1 ms
TIME(s)  COMM           TID    D BYTES   LAT(ms) FILENAME
115.114   Cache2 I/O     1881   EW 9444       1.62 439C70A0B3564324B14328C93AB6B...
15.114   Cache2 I/O     1881    W 9444       1.66 439C70A0B3564324B14328C93AB6B...
53.821   bash           22024  ER 256      100.75 dd
53.821   bash           22024   R 256      100.81 dd
68.549   dd             22030  EW 10240    207.79 test1M
68.550   dd             22030   W 10240    207.84 test1M
69.332   dd             22030  EW 10240     85.64 test1M
69.332   dd             22030   W 10240     85.66 test1M
69.751   dd             22030  EW 10240    182.01 test1M
69.751   dd             22030   W 10240    182.06 test1M
69.993   dd             22030  EW 10240    135.94 test1M
69.994   dd             22030   W 10240    135.99 test1M
70.655   dd             22030  EW 10240    122.77 test1M
70.655   dd             22030   W 10240    122.81 test1M

```
this is my implementation of same problem
I have modified fileslower as you can see in fileslower all over the file.
do let me know if you have any issue in this implementation.

```python
#!/usr/bin/python
# @lint-avoid-python-3-compatibility-imports
#
# fileslower  Trace slow synchronous file reads and writes.
#             For Linux, uses BCC, eBPF.
#
# USAGE: fileslower [-h] [-p PID] [-a] [min_ms]
#
# This script uses kernel dynamic tracing of synchronous reads and writes
# at the VFS interface, to identify slow file reads and writes for any file
# system.
#
# This works by tracing __vfs_read() and __vfs_write(), and filtering for
# synchronous I/O (the path to new_sync_read() and new_sync_write()), and
# for I/O with filenames. This approach provides a view of just two file
# system request types. There are typically many others: asynchronous I/O,
# directory operations, file handle operations, etc, that this tool does not
# instrument.
#
# WARNING: This traces VFS reads and writes, which can be extremely frequent,
# and so the overhead of this tool can become severe depending on the
# workload.
#
# By default, a minimum millisecond threshold of 10 is used.
#
# Copyright 2016 Netflix, Inc.
# Licensed under the Apache License, Version 2.0 (the "License")
#
# 06-Feb-2016   Brendan Gregg   Created this.

from __future__ import print_function
from bcc import BPF
import argparse
import time

# arguments
examples = """examples:
    ./fileslower             # trace sync file I/O slower than 10 ms (default)
    ./fileslower 1           # trace sync file I/O slower than 1 ms
    ./fileslower -p 185      # trace PID 185 only
"""
parser = argparse.ArgumentParser(
    description="Trace slow synchronous file reads and writes",
    formatter_class=argparse.RawDescriptionHelpFormatter,
    epilog=examples)
parser.add_argument("-p", "--pid", type=int, metavar="PID", dest="tgid",
    help="trace this PID only")
parser.add_argument("-a", "--all-files", action="store_true",
    help="include non-regular file types (sockets, FIFOs, etc)")
parser.add_argument("min_ms", nargs="?", default='10',
    help="minimum I/O duration to trace, in ms (default 10)")
parser.add_argument("--ebpf", action="store_true",
    help=argparse.SUPPRESS)
args = parser.parse_args()
min_ms = int(args.min_ms)
tgid = args.tgid
debug = 0

# define BPF program
bpf_text = """
#include <uapi/linux/ptrace.h>
#include <linux/uio.h>
#include <linux/fs.h>
#include <linux/sched.h>

enum trace_mode {
    MODE_READ,
    MODE_WRITE,
    EXT_READ,
    EXT_WRITE
};

struct val_t {
    u32 sz;
    u64 ts;
    u32 name_len;
    // de->d_name.name may point to de->d_iname so limit len accordingly
    char name[DNAME_INLINE_LEN];
    char comm[TASK_COMM_LEN];
};

struct data_t {
    enum trace_mode mode;
    u32 pid;
    u32 sz;
    u64 delta_us;
    u32 name_len;
    char name[DNAME_INLINE_LEN];
    char comm[TASK_COMM_LEN];
};

BPF_HASH(entryinfo, u64, struct val_t);
BPF_PERF_OUTPUT(events);

// store timestamp and size on entry
static int trace_rw_entry(struct pt_regs *ctx, struct file *file,
    char __user *buf, size_t count, int type)
{
    u32 tgid = bpf_get_current_pid_tgid() >> 32;
    if (TGID_FILTER)
        return 0;

    u32 pid = bpf_get_current_pid_tgid();
    u64 key = ((pid << 2) + type);
    // skip I/O lacking a filename
    struct dentry *de = file->f_path.dentry;
    int mode = file->f_inode->i_mode;
    if (de->d_name.len == 0 || TYPE_FILTER)
        return 0;

    bpf_trace_printk("rw_entry %d:%d %ld\\n", pid, type, key);
    // store size and timestamp by pid
    struct val_t val = {};
    val.sz = count;
    val.ts = bpf_ktime_get_ns();

    struct qstr d_name = de->d_name;
    val.name_len = d_name.len;
    bpf_probe_read(&val.name, sizeof(val.name), d_name.name);
    bpf_get_current_comm(&val.comm, sizeof(val.comm));
    entryinfo.update(&key, &val);

    return 0;
}

int trace_read_entry(struct pt_regs *ctx, struct file *file,
    char __user *buf, size_t count)
{
    // skip non-sync I/O; see kernel code for __vfs_read()
    if (!(file->f_op->read_iter))
        return 0;
    return trace_rw_entry(ctx, file, buf, count, MODE_READ);
}

int trace_write_entry(struct pt_regs *ctx, struct file *file,
    char __user *buf, size_t count)
{
    // skip non-sync I/O; see kernel code for __vfs_write()
    if (!(file->f_op->write_iter))
        return 0;
    return trace_rw_entry(ctx, file, buf, count, MODE_WRITE);
}

int trace_ext_read_entry(struct pt_regs *ctx, 
    struct kiocb *iocb, struct iov_iter *to)
{
    struct file *file = iocb->ki_filp;
    char __user *buf = to->iov->iov_base;
    size_t count = to->iov->iov_len;
    // skip non-sync I/O; see kernel code for __vfs_read()
    if (!(file->f_op->read_iter))
        return 0;
    return trace_rw_entry(ctx, file, buf, count, EXT_READ);
}

int trace_ext_write_entry(struct pt_regs *ctx,
    struct kiocb *iocb, struct iov_iter *to)
{
    struct file *file = iocb->ki_filp;
    char __user *buf = to->iov->iov_base;
    size_t count = to->iov->iov_len;
    // skip non-sync I/O; see kernel code for __vfs_write()
    if (!(file->f_op->write_iter))
        return 0;
    return trace_rw_entry(ctx, file, buf, count, EXT_WRITE);
}
// output
static int trace_rw_return(struct pt_regs *ctx, int type)
{
    struct val_t *valp;
    u32 pid = bpf_get_current_pid_tgid();
    u64 key = ((pid << 2) + type);

    valp = entryinfo.lookup(&key);
    if (valp == 0) {
        // missed tracing issue or filtered
        return 0;
    }
    u64 delta_us = (bpf_ktime_get_ns() - valp->ts) / 1000;
    entryinfo.delete(&key);
    if (delta_us < MIN_US)
        return 0;

    bpf_trace_printk("rw_return %d:%d %ld\\n", pid, type, key);
    struct data_t data = {};
    data.mode = type;
    data.pid = pid;
    data.sz = valp->sz;
    data.delta_us = delta_us;
    data.name_len = valp->name_len;
    bpf_probe_read(&data.name, sizeof(data.name), valp->name);
    bpf_probe_read(&data.comm, sizeof(data.comm), valp->comm);
    events.perf_submit(ctx, &data, sizeof(data));

    return 0;
}

int trace_read_return(struct pt_regs *ctx)
{
    return trace_rw_return(ctx, MODE_READ);
}

int trace_write_return(struct pt_regs *ctx)
{
    return trace_rw_return(ctx, MODE_WRITE);
}
int trace_ext_read_return(struct pt_regs *ctx)
{
    return trace_rw_return(ctx, EXT_READ);
}

int trace_ext_write_return(struct pt_regs *ctx)
{
    return trace_rw_return(ctx, EXT_WRITE);
}
"""
bpf_text = bpf_text.replace('MIN_US', str(min_ms * 1000))
if args.tgid:
    bpf_text = bpf_text.replace('TGID_FILTER', 'tgid != %d' % tgid)
else:
    bpf_text = bpf_text.replace('TGID_FILTER', '0')
if args.all_files:
    bpf_text = bpf_text.replace('TYPE_FILTER', '0')
else:
    bpf_text = bpf_text.replace('TYPE_FILTER', '!S_ISREG(mode)')

if debug or args.ebpf:
    print(bpf_text)
    if args.ebpf:
        exit()

# initialize BPF
b = BPF(text=bpf_text)

# I'd rather trace these via new_sync_read/new_sync_write (which used to be
# do_sync_read/do_sync_write), but those became static. So trace these from
# the parent functions, at the cost of more overhead, instead.
# Ultimately, we should be using [V]FS tracepoints.
b.attach_kprobe(event="__vfs_read", fn_name="trace_read_entry")
b.attach_kretprobe(event="__vfs_read", fn_name="trace_read_return")
try:
    b.attach_kprobe(event="__vfs_write", fn_name="trace_write_entry")
    b.attach_kretprobe(event="__vfs_write", fn_name="trace_write_return")
except Exception:
    # older kernels don't have __vfs_write so try vfs_write instead
    b.attach_kprobe(event="vfs_write", fn_name="trace_write_entry")
    b.attach_kretprobe(event="vfs_write", fn_name="trace_write_return")

b.attach_kprobe(event="ext4_file_read_iter", fn_name="trace_ext_read_entry")
b.attach_kretprobe(event="ext4_file_read_iter", fn_name="trace_ext_read_return")
b.attach_kprobe(event="ext4_file_write_iter", fn_name="trace_ext_write_entry")
b.attach_kretprobe(event="ext4_file_write_iter", fn_name="trace_ext_write_return")

mode_s = {
    0: 'R',
    1: 'W',
    2: 'ER',
    3: 'EW',
}

# header
print("Tracing sync read/writes slower than %d ms" % min_ms)
print("%-8s %-14s %-6s %1s %-7s %7s %s" % ("TIME(s)", "COMM", "TID", "D",
    "BYTES", "LAT(ms)", "FILENAME"))

start_ts = time.time()
DNAME_INLINE_LEN = 32 
def print_event(cpu, data, size):
    event = b["events"].event(data)

    ms = float(event.delta_us) / 1000
    name = event.name.decode('utf-8', 'replace')
    if event.name_len > DNAME_INLINE_LEN:
        name = name[:-3] + "..."

    print("%-8.3f %-14.14s %-6s %1s %-7s %7.2f %s" % (
        time.time() - start_ts, event.comm.decode('utf-8', 'replace'),
        event.pid, mode_s[event.mode], event.sz, ms, name))

b["events"].open_perf_buffer(print_event, page_cnt=64)
while 1:
    try:
        b.perf_buffer_poll()
    except KeyboardInterrupt:
        exit()
```

[vfs_ext_slower.txt](https://github.com/iovisor/bcc/files/4397457/vfs_ext_slower.txt)

**Comment by yonghong-song** [comment]
It looks like you are using the same map for vfs and ext4. the ext4 result will get lost and vfs result will be inaccurate. you probably need two different maps.

**Comment by forcedpoet** [comment]
I am using pid and type to create key and using that key as key for map.key will be different for vfs and ext4. Will it still miss events? 
If yes can you please explain? Or just give me pointers to read ?

**Comment by devidasjadhav** [comment]
@yonghong-song  above comment is by me from other account by mistake.

**Comment by nagmat1** [comment]
> ## output
> this is out put of attached code.
> 
> R -> vfs_read
> W -> vfs_write
> ER -> ext4_iter_read
> EW -> ext4_iter_write
> 
> ```
> dev@debian:~/DATA/workspace/git/devbcc$ sudo ./tools/fileslower.py 1
> Tracing sync read/writes slower than 1 ms
> TIME(s)  COMM           TID    D BYTES   LAT(ms) FILENAME
> 115.114   Cache2 I/O     1881   EW 9444       1.62 439C70A0B3564324B14328C93AB6B...
> 15.114   Cache2 I/O     1881    W 9444       1.66 439C70A0B3564324B14328C93AB6B...
> 53.821   bash           22024  ER 256      100.75 dd
> 53.821   bash           22024   R 256      100.81 dd
> 68.549   dd             22030  EW 10240    207.79 test1M
> 68.550   dd             22030   W 10240    207.84 test1M
> 69.332   dd             22030  EW 10240     85.64 test1M
> 69.332   dd             22030   W 10240     85.66 test1M
> 69.751   dd             22030  EW 10240    182.01 test1M
> 69.751   dd             22030   W 10240    182.06 test1M
> 69.993   dd             22030  EW 10240    135.94 test1M
> 69.994   dd             22030   W 10240    135.99 test1M
> 70.655   dd             22030  EW 10240    122.77 test1M
> 70.655   dd             22030   W 10240    122.81 test1M
> ```
> 
> this is my implementation of same problem
> I have modified fileslower as you can see in fileslower all over the file.
> do let me know if you have any issue in this implementation.
> 
> ```python
> #!/usr/bin/python
> # @lint-avoid-python-3-compatibility-imports
> #
> # fileslower  Trace slow synchronous file reads and writes.
> #             For Linux, uses BCC, eBPF.
> #
> # USAGE: fileslower [-h] [-p PID] [-a] [min_ms]
> #
> # This script uses kernel dynamic tracing of synchronous reads and writes
> # at the VFS interface, to identify slow file reads and writes for any file
> # system.
> #
> # This works by tracing __vfs_read() and __vfs_write(), and filtering for
> # synchronous I/O (the path to new_sync_read() and new_sync_write()), and
> # for I/O with filenames. This approach provides a view of just two file
> # system request types. There are typically many others: asynchronous I/O,
> # directory operations, file handle operations, etc, that this tool does not
> # instrument.
> #
> # WARNING: This traces VFS reads and writes, which can be extremely frequent,
> # and so the overhead of this tool can become severe depending on the
> # workload.
> #
> # By default, a minimum millisecond threshold of 10 is used.
> #
> # Copyright 2016 Netflix, Inc.
> # Licensed under the Apache License, Version 2.0 (the "License")
> #
> # 06-Feb-2016   Brendan Gregg   Created this.
> 
> from __future__ import print_function
> from bcc import BPF
> import argparse
> import time
> 
> # arguments
> examples = """examples:
>     ./fileslower             # trace sync file I/O slower than 10 ms (default)
>     ./fileslower 1           # trace sync file I/O slower than 1 ms
>     ./fileslower -p 185      # trace PID 185 only
> """
> parser = argparse.ArgumentParser(
>     description="Trace slow synchronous file reads and writes",
>     formatter_class=argparse.RawDescriptionHelpFormatter,
>     epilog=examples)
> parser.add_argument("-p", "--pid", type=int, metavar="PID", dest="tgid",
>     help="trace this PID only")
> parser.add_argument("-a", "--all-files", action="store_true",
>     help="include non-regular file types (sockets, FIFOs, etc)")
> parser.add_argument("min_ms", nargs="?", default='10',
>     help="minimum I/O duration to trace, in ms (default 10)")
> parser.add_argument("--ebpf", action="store_true",
>     help=argparse.SUPPRESS)
> args = parser.parse_args()
> min_ms = int(args.min_ms)
> tgid = args.tgid
> debug = 0
> 
> # define BPF program
> bpf_text = """
> #include <uapi/linux/ptrace.h>
> #include <linux/uio.h>
> #include <linux/fs.h>
> #include <linux/sched.h>
> 
> enum trace_mode {
>     MODE_READ,
>     MODE_WRITE,
>     EXT_READ,
>     EXT_WRITE
> };
> 
> struct val_t {
>     u32 sz;
>     u64 ts;
>     u32 name_len;
>     // de->d_name.name may point to de->d_iname so limit len accordingly
>     char name[DNAME_INLINE_LEN];
>     char comm[TASK_COMM_LEN];
> };
> 
> struct data_t {
>     enum trace_mode mode;
>     u32 pid;
>     u32 sz;
>     u64 delta_us;
>     u32 name_len;
>     char name[DNAME_INLINE_LEN];
>     char comm[TASK_COMM_LEN];
> };
> 
> BPF_HASH(entryinfo, u64, struct val_t);
> BPF_PERF_OUTPUT(events);
> 
> // store timestamp and size on entry
> static int trace_rw_entry(struct pt_regs *ctx, struct file *file,
>     char __user *buf, size_t count, int type)
> {
>     u32 tgid = bpf_get_current_pid_tgid() >> 32;
>     if (TGID_FILTER)
>         return 0;
> 
>     u32 pid = bpf_get_current_pid_tgid();
>     u64 key = ((pid << 2) + type);
>     // skip I/O lacking a filename
>     struct dentry *de = file->f_path.dentry;
>     int mode = file->f_inode->i_mode;
>     if (de->d_name.len == 0 || TYPE_FILTER)
>         return 0;
> 
>     bpf_trace_printk("rw_entry %d:%d %ld\\n", pid, type, key);
>     // store size and timestamp by pid
>     struct val_t val = {};
>     val.sz = count;
>     val.ts = bpf_ktime_get_ns();
> 
>     struct qstr d_name = de->d_name;
>     val.name_len = d_name.len;
>     bpf_probe_read(&val.name, sizeof(val.name), d_name.name);
>     bpf_get_current_comm(&val.comm, sizeof(val.comm));
>     entryinfo.update(&key, &val);
> 
>     return 0;
> }
> 
> int trace_read_entry(struct pt_regs *ctx, struct file *file,
>     char __user *buf, size_t count)
> {
>     // skip non-sync I/O; see kernel code for __vfs_read()
>     if (!(file->f_op->read_iter))
>         return 0;
>     return trace_rw_entry(ctx, file, buf, count, MODE_READ);
> }
> 
> int trace_write_entry(struct pt_regs *ctx, struct file *file,
>     char __user *buf, size_t count)
> {
>     // skip non-sync I/O; see kernel code for __vfs_write()
>     if (!(file->f_op->write_iter))
>         return 0;
>     return trace_rw_entry(ctx, file, buf, count, MODE_WRITE);
> }
> 
> int trace_ext_read_entry(struct pt_regs *ctx, 
>     struct kiocb *iocb, struct iov_iter *to)
> {
>     struct file *file = iocb->ki_filp;
>     char __user *buf = to->iov->iov_base;
>     size_t count = to->iov->iov_len;
>     // skip non-sync I/O; see kernel code for __vfs_read()
>     if (!(file->f_op->read_iter))
>         return 0;
>     return trace_rw_entry(ctx, file, buf, count, EXT_READ);
> }
> 
> int trace_ext_write_entry(struct pt_regs *ctx,
>     struct kiocb *iocb, struct iov_iter *to)
> {
>     struct file *file = iocb->ki_filp;
>     char __user *buf = to->iov->iov_base;
>     size_t count = to->iov->iov_len;
>     // skip non-sync I/O; see kernel code for __vfs_write()
>     if (!(file->f_op->write_iter))
>         return 0;
>     return trace_rw_entry(ctx, file, buf, count, EXT_WRITE);
> }
> // output
> static int trace_rw_return(struct pt_regs *ctx, int type)
> {
>     struct val_t *valp;
>     u32 pid = bpf_get_current_pid_tgid();
>     u64 key = ((pid << 2) + type);
> 
>     valp = entryinfo.lookup(&key);
>     if (valp == 0) {
>         // missed tracing issue or filtered
>         return 0;
>     }
>     u64 delta_us = (bpf_ktime_get_ns() - valp->ts) / 1000;
>     entryinfo.delete(&key);
>     if (delta_us < MIN_US)
>         return 0;
> 
>     bpf_trace_printk("rw_return %d:%d %ld\\n", pid, type, key);
>     struct data_t data = {};
>     data.mode = type;
>     data.pid = pid;
>     data.sz = valp->sz;
>     data.delta_us = delta_us;
>     data.name_len = valp->name_len;
>     bpf_probe_read(&data.name, sizeof(data.name), valp->name);
>     bpf_probe_read(&data.comm, sizeof(data.comm), valp->comm);
>     events.perf_submit(ctx, &data, sizeof(data));
> 
>     return 0;
> }
> 
> int trace_read_return(struct pt_regs *ctx)
> {
>     return trace_rw_return(ctx, MODE_READ);
> }
> 
> int trace_write_return(struct pt_regs *ctx)
> {
>     return trace_rw_return(ctx, MODE_WRITE);
> }
> int trace_ext_read_return(struct pt_regs *ctx)
> {
>     return trace_rw_return(ctx, EXT_READ);
> }
> 
> int trace_ext_write_return(struct pt_regs *ctx)
> {
>     return trace_rw_return(ctx, EXT_WRITE);
> }
> """
> bpf_text = bpf_text.replace('MIN_US', str(min_ms * 1000))
> if args.tgid:
>     bpf_text = bpf_text.replace('TGID_FILTER', 'tgid != %d' % tgid)
> else:
>     bpf_text = bpf_text.replace('TGID_FILTER', '0')
> if args.all_files:
>     bpf_text = bpf_text.replace('TYPE_FILTER', '0')
> else:
>     bpf_text = bpf_text.replace('TYPE_FILTER', '!S_ISREG(mode)')
> 
> if debug or args.ebpf:
>     print(bpf_text)
>     if args.ebpf:
>         exit()
> 
> # initialize BPF
> b = BPF(text=bpf_text)
> 
> # I'd rather trace these via new_sync_read/new_sync_write (which used to be
> # do_sync_read/do_sync_write), but those became static. So trace these from
> # the parent functions, at the cost of more overhead, instead.
> # Ultimately, we should be using [V]FS tracepoints.
> b.attach_kprobe(event="__vfs_read", fn_name="trace_read_entry")
> b.attach_kretprobe(event="__vfs_read", fn_name="trace_read_return")
> try:
>     b.attach_kprobe(event="__vfs_write", fn_name="trace_write_entry")
>     b.attach_kretprobe(event="__vfs_write", fn_name="trace_write_return")
> except Exception:
>     # older kernels don't have __vfs_write so try vfs_write instead
>     b.attach_kprobe(event="vfs_write", fn_name="trace_write_entry")
>     b.attach_kretprobe(event="vfs_write", fn_name="trace_write_return")
> 
> b.attach_kprobe(event="ext4_file_read_iter", fn_name="trace_ext_read_entry")
> b.attach_kretprobe(event="ext4_file_read_iter", fn_name="trace_ext_read_return")
> b.attach_kprobe(event="ext4_file_write_iter", fn_name="trace_ext_write_entry")
> b.attach_kretprobe(event="ext4_file_write_iter", fn_name="trace_ext_write_return")
> 
> mode_s = {
>     0: 'R',
>     1: 'W',
>     2: 'ER',
>     3: 'EW',
> }
> 
> # header
> print("Tracing sync read/writes slower than %d ms" % min_ms)
> print("%-8s %-14s %-6s %1s %-7s %7s %s" % ("TIME(s)", "COMM", "TID", "D",
>     "BYTES", "LAT(ms)", "FILENAME"))
> 
> start_ts = time.time()
> DNAME_INLINE_LEN = 32 
> def print_event(cpu, data, size):
>     event = b["events"].event(data)
> 
>     ms = float(event.delta_us) / 1000
>     name = event.name.decode('utf-8', 'replace')
>     if event.name_len > DNAME_INLINE_LEN:
>         name = name[:-3] + "..."
> 
>     print("%-8.3f %-14.14s %-6s %1s %-7s %7.2f %s" % (
>         time.time() - start_ts, event.comm.decode('utf-8', 'replace'),
>         event.pid, mode_s[event.mode], event.sz, ms, name))
> 
> b["events"].open_perf_buffer(print_event, page_cnt=64)
> while 1:
>     try:
>         b.perf_buffer_poll()
>     except KeyboardInterrupt:
>         exit()
> ```
> 
> [vfs_ext_slower.txt](https://github.com/iovisor/bcc/files/4397457/vfs_ext_slower.txt)

Thanks for the response. 

I have checked the code, it is showing the same pid for ext4 and vfs read/write. If I run the ext4_slow and vfs_slow seperately the kernel is assigning different pids for each of them. Why is it the same pid when we are running it in the same stored program?

**Comment by yonghong-song** [comment]
Now, I checked your code.  although pid the same, you have different types for vfs and ext4 layer, so you should get both vfs/ext4 results at the same time with the same pid since they are in the same process context.

**Comment by devidasjadhav** [comment]
@nagmat1 
I completely agree with yonghong-song.

ext4_file_read_iter is called by __vfs_read through file_operations -> read_iter.

it's not possible to have different results if two bpf programs run differently compare to cobined code.
2 questions 

1.  what events attached in ext4_slow and vfs_slow ? ie, `cat <filename> |grep attach_kretprobe`

2. run all 3 programs together vfs_ext_slower , ext4_slow and vfs_slow and provide output so that we can comment.
Make sure you provide output where you see different pid in vfs and ext.

**Comment by nagmat1** [comment]
@yonghong-song @devidasjadhav 
Thanks for your comments, 
Now I have two eBPF codes 
1. vea.txt (**vea.py**) for tracking kernel commands on vfs layer and ext4_layer 
2. vea_graph.txt (**vea_graph.py**) the same like vea,py, the only difference is tracking the timestamps to draw the graph of vfs and ext4 kernel commands. 

After executing vea.py and vea_graph.py at the same time. I am extracting 2.1GB ubuntu-18.04.4-desktop-amd64.iso file to trace vfs and ext kernel commands. These are the results after first unzip.  
[vea_graph_out1.log](https://github.com/iovisor/bcc/files/4526382/vea_graph_out1.log)
[vea_out1.log](https://github.com/iovisor/bcc/files/4526384/vea_out1.log)

after first execution I delete the unzipped files using : 
 sudo rm -R ubuntu-18.04.4-desktop-amd64

Then, clear caches using : 
# sync; echo 1 > /proc/sys/vm/drop_caches
# sync; echo 2 > /proc/sys/vm/drop_caches
# sync; echo 3 > /proc/sys/vm/drop_caches

These are the execution results of after second unzip. 
[vea_graph_out2.log](https://github.com/iovisor/bcc/files/4526383/vea_graph_out2.log)
[vea_out2.log](https://github.com/iovisor/bcc/files/4526385/vea_out2.log)
My first question is: Is there anything like unzip cache in the memory with capacity around 2.1 GB?
 
[vea.txt](https://github.com/iovisor/bcc/files/4526374/vea.txt)
[vea_graph.txt](https://github.com/iovisor/bcc/files/4526375/vea_graph.txt)
