### ISSUE TITLE
Is it possible to disable python?

### ISSUE THREAD

**Issue by DimaPuz** [iovisor/bcc#2847]
I want to bring BCC to a special architecture that doesn't have python. I want to bring BCC without python. Is it possible? Is there a config or variable?

**Comment by devidasjadhav** [comment]
Yes you can use BCC without python.
BCC has 3 supported languages as of now.
1. cpp check example [hello world cpp code](https://github.com/iovisor/bcc/blob/master/examples/cpp/HelloWorld.cc)
2. lua chek lua exaple of small [strlen count code](https://github.com/iovisor/bcc/blob/master/examples/lua/strlen_count.lua)
3. as you mentioned python

special mentions 
there are other languages supported but still in alpha stage 
i.e 

1. golang has [gobpf](https://github.com/iovisor/gobpf)
2. rust has [rust-bcc](https://github.com/rust-bpf/rust-bcc)

**Comment by DimaPuz** [comment]
Tthanks a lot.
