### ISSUE TITLE
How to create map with map size at runtime? (CO-RE)

### ISSUE THREAD

**Issue by ethercflow** [iovisor/bcc#2852]
Hi, @anakryiko I'm trying to covert https://github.com/iovisor/bcc/blob/master/tools/cpudist.py to CO-RE version. But I met a problem that I need to make sure the bpf map size at runtime, like https://github.com/iovisor/bcc/blob/master/tools/cpudist.py#L159
https://github.com/iovisor/bcc/blob/master/tools/cpudist.py#L67 did.

But it seems it's not supported:

cpudist.bpf.c:
```c
const volatile int pid_max = 0;

struct {
        __uint(type, BPF_MAP_TYPE_HASH);
        __uint(max_entries, pid_max);
        __type(key, u32);
        __type(value, u64);
} start SEC(".maps");
```

cpudist.c:

```c
obj->rodata->pid_max = pid_max; // from /proc/sys/kernel/pid_max
err = cpudist_bpf__load(obj);
```

the compile error:

>   BPF      cpudist.bpf.o
> cpudist.bpf.c:24:9: error: fields must have a constant size: 'variable length array in structure' extension will never be supported
>         __uint(max_entries, pid_max);
>                ^
> cpudist.bpf.c:31:9: error: fields must have a constant size: 'variable length array in structure' extension will never be supported
>         __uint(max_entries, pid_max);
>                ^
> cpudist.bpf.c:38:9: error: fields must have a constant size: 'variable length array in structure' extension will never be supported
>         __uint(max_entries, pid_max);
>                ^
> 3 errors generated.
> Makefile:50: recipe for target '.output/cpudist.bpf.o' failed
> make: *** [.output/cpudist.bpf.o] Error 1

So how to handle this?

**Comment by anakryiko** [comment]
On Sun, Mar 29, 2020 at 6:35 PM Zwb <notifications@github.com> wrote:

> Hi, @anakryiko <https://github.com/anakryiko> I'm trying to covert
> https://github.com/iovisor/bcc/blob/master/tools/cpudist.py to CO-RE
> version. But I met a problem that I need to make sure the bpf map size at
> runtime, like
> https://github.com/iovisor/bcc/blob/master/tools/cpudist.py#L159
> https://github.com/iovisor/bcc/blob/master/tools/cpudist.py#L67 did.
>
> But it seems it's not supported:
>
> cpudist.bpf.c:
>
> const volatile int pid_max = 0;
> struct {
>         __uint(type, BPF_MAP_TYPE_HASH);
>         __uint(max_entries, pid_max);
>
>
You can omit max_entries here...



>         __type(key, u32);
>         __type(value, u64);
> } start SEC(".maps");
>
> cpudist.c:
>
> obj->rodata->pid_max = pid_max; // from /proc/sys/kernel/pid_max
>
>
And use bpf_map__resize() to set map size before load:

bpf_map__resize(obj->maps.start, <whatever size>);

**Comment by ethercflow** [comment]
Got it, thanks.
