### ISSUE TITLE
Empty kprobe_profile & kprobe_events in BCC

### ISSUE THREAD

**Issue by geonheec** [iovisor/bcc#2853]
Hi, I'm using kernel 5.2 version (and Ubuntu 18.04)

There's nothing in kprobe_profile and kprobe_events when I use BCC.

I tried to monitor the I/O-related information.
Then I made a program and run. 
(This program attaches kprobes to some kernel functions and records the log.) 

From the log, I assumed that there are some missed kprobes.
So I tried the following command to check nmissed field.

> $ cd /sys/kernel/debug/tracing
> $ cat kprobe_profile

but nothing appears...
(but when I ran the bpf program in **/linux/samples/bpf** directory, kprobe_profile appears.)

I don't know why some kprobes are missed and why kprobe_profile is empty.
Please help if you know the solution.

**Comment by geonheec** [comment]
I solve this problem  by just migrating my code to c-based bpf.

**Comment by gashnya** [comment]
Hello, by c-based bpf you mean https://github.com/libbpf/libbpf?
