### ISSUE TITLE
Build process assumes "python" command

### ISSUE THREAD

**Issue by troyengel** [iovisor/bcc#287]
Dual-homed installations of python (such as Arch) have 'python' == python 3 and 'python2' == python. Many other distros are still using python 2 as the default 'python'; the build process needs a way to allow the builder/packager to specify the python command to override the default.

Pull request to follow, another simple fix.

**Comment by troyengel** [comment]
OK I lied - I'm useless at github and don't know how to only create a pull request from the latest commit that's on top of the other commit I have a pull request for, sorry. In the meantime, here's the exact commit diff:

https://github.com/troyengel/bcc/commit/576dc071b2fa1fa0ae6658bdf7d2a90d9ffbff68

I guess I can submit a new pull request with this one commit after the other one is processed - a quick Google show that it's brain surgery otherwise. :-/

**Comment by drzaeus77** [comment]
FYI, the procedure I usually follow when submitting simultaneous unrelated
patches is to create a separate clean (from master) branch for each, and
send a pull request from that branch (as in python-cmake-fix and
revision-cmake-fix). However, we aren't being too strict at this point as
there are not too many contributors to this project, so the style that you
followed is perfectly satisfactory, given the simplicity of the changes.
