### ISSUE TITLE
libbpf: failed to find valid kernel BTF

### ISSUE THREAD

**Issue by teroz** [iovisor/bcc#2872]
I compiled libbpf-tools with ubuntu 19.10 with clang version 10. The compilation works  but when I try and run any of the compiled tools I get the following error
```bash
libbpf: failed to find valid kernel BTF
``` 

I'm not sure which distribution would have this information

**Comment by anakryiko** [comment]
You'll probably need to re-compile your kernel with CONFIG_DEBUG_INFO_BTF=y. I don't think any existing distros enable kernel BTF by default...

You can check if your kernel has BTF built-int by:
```
# ls -la /sys/kernel/btf/vmlinux
```

If you have such file, then this must be a different problem.

**Comment by teroz** [comment]
oic. I did recompile my kernel to include that flag  and I am currently running that new kernel build. I still don't get that btf info exported in the sys fs as shown below. I do have the vmlinux ELF present though but I still get the `failed to find valid kernel BTF`

![Screenshot from 2020-04-16 17-20-47](https://user-images.githubusercontent.com/853846/79474440-ae42e480-8006-11ea-89a4-721a7a3cf01d.png)

**Comment by anakryiko** [comment]
Ok, so you have 5.3 kernel, which doesn't yet expose BTF under
/sys/kernel/btf/vmlinux. But libbpf should be able to locate vmlinux file
from /usr/lib/debug/lib/modules/5.3.18/vmlinux, but seems like it doesn't.
Can you enable verbose logging and get a full libbpf output? It should
enumerate which locations it attempted to load BTF from. That should help
move this discussion forward. Thanks!

Also, make sure that you have pahole 1.13 (or preferably 1.16+) during the
kernel build (it comes from dwarves package). Without it, BTF won't be
generated, and on older kernels you'd get only warning, but still would
build kernel successfully, which might be what happened here.

**Comment by teroz** [comment]
Boom. Thanks so much that was the issue. Once I installed `pahole` and recompiled it worked fine.
I tested both on 5.3 (without the exported `/sys/kernel/btf/vmlinux`) and 5.6 and it worked a treat. I have a pull request that updates the libbpf-tools/README.md with the a paragraph about compiling the kernel for the BTF type info with the takeaway from here https://github.com/iovisor/bcc/pull/2876

**Comment by mingregister** [comment]
Is there anaway to specify the location of vmlinux.h ?
