### ISSUE TITLE
cpp `./HelloWorld': double free or corruption on CentOS 7.5 and CentOS 7.7

### ISSUE THREAD

**Issue by DavadDi** [iovisor/bcc#2898]
See : [Centos - Source](https://github.com/iovisor/bcc/blob/master/INSTALL.md#toc27)

**Install build dependencies**
```
sudo yum install -y epel-release
sudo yum update -y
sudo yum groupinstall -y "Development tools"
sudo yum install -y elfutils-libelf-devel cmake3 git bison flex ncurses-devel
sudo yum install -y luajit luajit-devel  # for Lua support
```
**install clang && llvm** 
```
yum install -y centos-release-scl
yum-config-manager --enable rhel-server-rhscl-7-rpms
yum install -y devtoolset-7 llvm-toolset-7 llvm-toolset-7-llvm-devel llvm-toolset-7-llvm-static llvm-toolset-7-clang-devel
source scl_source enable devtoolset-7 llvm-toolset-7
```

**Install and compile BCC**
```
git clone https://github.com/iovisor/bcc.git
mkdir bcc/build; cd bcc/build
cmake3 ..
```
$ sudo yum install "kernel-devel-uname-r == $(uname -r)"

$ cd bcc/build/examples/cpp
$ ./HelloWorld
*** Error in `./HelloWorld': double free or corruption (out): 0x00000000022bbc40 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x81679)[0x2b10c040f679]
/opt/rh/llvm-toolset-7/root/usr/lib64/libclangDriver.so.5(+0xf6677)[0x2b10bc6e4677]
/opt/rh/llvm-toolset-7/root/usr/lib64/libclangDriver.so.5(+0xf8bb1)[0x2b10bc6e6bb1]
/opt/rh/llvm-toolset-7/root/usr/lib64/libclangDriver.so.5(+0x107284)[0x2b10bc6f5284]
/opt/rh/llvm-toolset-7/root/usr/lib64/libclangDriver.so.5(_ZNK5clang6driver6Driver12getToolChainERKN4llvm3opt7ArgListERKNS2_6TripleE+0x3a3)[0x2b10bc647d33]
/opt/rh/llvm-toolset-7/root/usr/lib64/libclangDriver.so.5(_ZN5clang6driver6Driver16BuildCompilationEN4llvm8ArrayRefIPKcEE+0x738)[0x2b10bc65b548]
./HelloWorld(_ZN4ebpf11ClangLoader10do_compileEPSt10unique_ptrIN4llvm6ModuleESt14default_deleteIS3_EERNS_12TableStorageEbRKSt6vectorIPKcSaISC_EESG_RKSsRKS1_INS2_12MemoryBufferES4_ISJ_EESI_RNS_10FuncSourceERSsbSI_RSt3mapIiSt5tupleIJiSsiiiijSsEESt4lessIiESaISt4pairIKiST_EEERSR_ISsSA_ISsSaISsEESU_ISsESaISW_ISH_S13_EEE+0x34c)[0x7ea30c]
./HelloWorld(_ZN4ebpf11ClangLoader5parseEPSt10unique_ptrIN4llvm6ModuleESt14default_deleteIS3_EERNS_12TableStorageERKSsbPPKciSB_RNS_10FuncSourceERSsSB_RSt3mapIiSt5tupleIJiSsiiiijSsEESt4lessIiESaISt4pairIKiSK_EEERSI_ISsSt6vectorISsSaISsEESL_ISsESaISN_ISA_SV_EEE+0x851)[0x7ed541]
./HelloWorld(_ZN4ebpf9BPFModule10load_cfileERKSsbPPKci+0x97)[0x78ca07]
./HelloWorld(_ZN4ebpf9BPFModule11load_stringERKSsPPKci+0x1b)[0x79392b]
./HelloWorld(_ZN4ebpf3BPF4initERKSsRKSt6vectorISsSaISsEERKS3_INS_4USDTESaIS8_EE+0x144)[0x19e3db4]
./HelloWorld(main+0x30b)[0x73972b]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x2b10c03b0505]
./HelloWorld[0x78c4e7]
======= Memory map: ========
00400000-01f79000 r-xp 00000000 fd:01 663894                             /home/lcsuper/diwh/bcc/build/examples/cpp/HelloWorld
02179000-022b5000 r--p 01b79000 fd:01 663894                             /home/lcsuper/diwh/bcc/build/examples/cpp/HelloWorld
022b5000-022bc000 rw-p 01cb5000 fd:01 663894                             /home/lcsuper/diwh/bcc/build/examples/cpp/HelloWorld
022bc000-022f0000 rw-p 00000000 00:00 0
02c3a000-02c76000 rw-p 00000000 00:00 0                                  [heap]
2b10bbcf7000-2b10bbd19000 r-xp 00000000 fd:01 1049976                    /usr/lib64/ld-2.17.so
2b10bbd19000-2b10bbd1f000 rw-p 00000000 00:00 0
2b10bbd26000-2b10bbd30000 rw-p 00000000 00:00 0
2b10bbf18000-2b10bbf19000 r--p 00021000 fd:01 1049976                    /usr/lib64/ld-2.17.so
2b10bbf19000-2b10bbf1a000 rw-p 00022000 fd:01 1049976                    /usr/lib64/ld-2.17.so
2b10bbf1a000-2b10bbf1b000 rw-p 00000000 00:00 0
2b10bbf1b000-2b10bc058000 r-xp 00000000 fd:01 657618                     /opt/rh/llvm-toolset-7/root/usr/lib64/libclangFrontend.so.5.0.1
2b10bc058000-2b10bc258000 ---p 0013d000 fd:01 657618                     /opt/rh/llvm-toolset-7/root/usr/lib64/libclangFrontend.so.5.0.1
2b10bc258000-2b10bc25e000 r--p 0013d000 fd:01 657618                     /opt/rh/llvm-toolset-7/root/usr/lib64/libclangFrontend.so.5.0.1
2b10bc25e000-2b10bc260000 rw-p 00143000 fd:01 657618                     /opt/rh/llvm-toolset-7/root/usr/lib64/libclangFrontend.so.5.0.1
2b10bc260000-2b10bc3e8000 r-xp 00000000 fd:01 657657                     /opt/rh/llvm-toolset-7/root/usr/lib64/libclangSerialization.so.5.0.1
2b10bc3e8000-2b10bc5e7000 ---p 00188000 fd:01 657657                     /opt/rh/llvm-toolset-7/root/usr/lib64/libclangSerialization.so.5.0.1
2b10bc5e7000-2b10bc5e9000 r--p 00187000 fd:01 657657                     /opt/rh/llvm-toolset-7/root/usr/lib64/libclangSerialization.so.5.0.1
2b10bc5e9000-2b10bc5ee000 rw-p 00189000 fd:01 657657                     /opt/rh/llvm-toolset-7/root/usr/lib64/libclangSerialization.so.5.0.1
2b10bc5ee000-2b10bc760000 r-xp 00000000 fd:01 657606                     /opt/rh/llvm-toolset-7/root/usr/lib64/libclangDriver.so.5.0.1
2b10bc760000-2b10bc95f000 ---p 00172000 fd:01 657606                     /opt/rh/llvm-toolset-7/root/usr/lib64/libclangDriver.so.5.0.1
2b10bc95f000-2b10bc98a000 r--p 00171000 fd:01 657606                     /opt/rh/llvm-toolset-7/root/usr/lib64/libclangDriver.so.5.0.1
2b10bc98a000-2b10bc98c000 rw-p 0019c000 fd:01 657606                     /opt/rh/llvm-toolset-7/root/usr/lib64/libclangDriver.so.5.0.1
2b10bc98c000-2b10bca75000 r-xp 00000000 fd:01 657639                     /opt/rh/llvm-toolset-7/root/usr/lib64/libclangParse.so.5.0.1
2b10bca75000-2b10bcc74000 ---p 000e9000 fd:01 657639                     /opt/rh/llvm-toolset-7/root/usr/lib64/libclangParse.so.5.0.1
2b10bcc74000-2b10bcc76000 r--p 000e8000 fd:01 657639                     /opt/rh/llvm-toolset-7/root/usr/lib64/libclangParse.so.5.0.1
2b10bcc76000-2b10bcc79000 rw-p 000ea000 fd:01 657639                     /opt/rh/llvm-toolset-7/root/usr/lib64/libclangParse.so.5.0.1
2b10bcc79000-2b10bd36c000 r-xp 00000000 fd:01 657654                     /opt/rh/llvm-toolset-7/root/usr/lib64/libclangSema.so.5.0.1
2b10bd36c000-2b10bd56c000 ---p 006f3000 fd:01 657654                     /opt/rh/llvm-toolset-7/root/usr/lib64/libclangSema.so.5.0.1
2b10bd56c000-2b10bd572000 r--p 006f3000 fd:01 657654                     /opt/rh/llvm-toolset-7/root/usr/lib64/libclangSema.so.5.0.1
2b10bd572000-2b10bd57a000 rw-p 006f9000 fd:01 657654                     /opt/rh/llvm-toolset-7/root/usr/lib64/libclangSema.so.5.0.1Aborted

$ # uname -r
3.10.0-1062.18.1.el7.x86_64

**Anything I missed?**

**Comment by yonghong-song** [comment]
Maybe other centos user can help? In my environment, using latest llvm 11 with static libraries (instead of the libclang*.so) works fine.

**Comment by DavadDi** [comment]
@yonghong-song Thank you very much for your quick reply. After I modified the installation method of llvm, the program can work normally.

```
curl  -LO  http://releases.llvm.org/7.0.1/llvm-7.0.1.src.tar.xz
curl  -LO  http://releases.llvm.org/7.0.1/cfe-7.0.1.src.tar.xz
tar -xf cfe-7.0.1.src.tar.xz
tar -xf llvm-7.0.1.src.tar.xz

mkdir clang-build
mkdir llvm-build

cd llvm-build
cmake3 -G "Unix Makefiles" -DLLVM_TARGETS_TO_BUILD="BPF;X86" \
  -DCMAKE_BUILD_TYPE=Release ../llvm-7.0.1.src
make
sudo make install

cd ../clang-build
cmake3 -G "Unix Makefiles" -DLLVM_TARGETS_TO_BUILD="BPF;X86" \
  -DCMAKE_BUILD_TYPE=Release ../cfe-7.0.1.src
make
sudo make install
cd ..
``` 

# ./HelloWorld
Starting HelloWorld with BCC 0.14.0-f4302f34
           runsv-11699 [000] d... 167603.819743: : Hello, World! Here I did a sys_clone call!
