### ISSUE TITLE
Does bpf helper function also operate on bpf virtual machine?

### ISSUE THREAD

**Issue by geonheec** [iovisor/bcc#2910]
Does bpf helper function operate on bpf virtual machine? Or does it work with x86 instructions on native CPU?

I tried to add a new bpf helper function for monitoring user stack. 
(To be precise, I modified the bpf_get_stack function a bit.)

By the way, this helper function takes much longer than expected.

Within my helper function, functions that may take a long time are _copy_from_user_ and _memcpy_ and _for loop_. 
But I didn't expect it to take so long. 
This function takes from a minimum of 1000 ns to a maximum of 100000 ns.

So I'm looking for the cause, and if the helper function works on bpf vm, I think it might be.

**Comment by danobi** [comment]
Helpers are kernel code, so they're native. Maybe your kernel changes are just slow (lots of copies would do that).

If you share the patch maybe someone can spot something.

**Comment by geonheec** [comment]
Thank you for the reply. 
The problem, which took longer than expected, was due to my wrong implementation.
Therefore, I'll close the issue.
