### ISSUE TITLE
Propose funcinterval memleaktop bcc tools

### ISSUE THREAD

**Issue by netedwardwu** [iovisor/bcc#2933]
Hi @yonghong-song ,

We got some good bcc tools that want to share with you.
**1. funcinterval**
WHAT: Time interval between the same function.
WHY:
_a. USB performance tuning_
In real-world problems, we often do some devices performance tuning, sometimes the problem is related to HW or SW.
And we want to know how long interval the USB host driver rings the doorbell register.
`funcinterval xhci_ring_ep_doorbell -i 2`
The above command helps us to profile the problem is that SW rings the doorbell too late or not.

_b. EMMC performance tuning_
One day, we got differences in EMMC throughput between two different ARM32 platforms.
And funclatency that shows us the same latency between these two cases.
Therefore we use funcinterval bcc tool, and find out there is a difference.
And find out the problem is related to dm-verity.

**2. memleaktop** 
WHAT: It can profile memory leak with PID as a table style.
WHY:
The current memleak bcc tool has no much PID support.
We implement a memleaktop that can analyze what PID causes how many outstanding allocations.
```
PID      NAME             CPU   TOTAL_OUTSTANDING_MEM
7000     bpfd             1          746368
6998     shell svc 6997   0          508160
4905     adbd             3          221440
4906     adbd             1          132480
6504     kworker/u8:0     2           64512
4899     adbd             1           60352
4906     adbd             2           42496
2161     composer@2.2-se  3            4096
4899     adbd             0            2624
6998     shell svc 6997   3            1536
1        init             0             576
7000     bpfd             2             128
7017     sh               1             128
7000     bpfd             3             128
4905     adbd             0             128
4899     adbd             2              64
4899     adbd             3              64
```

The above bcc tools are good for us to solve real-world problems. However, I'm not sure it's good for everybody.
How do you think?

Thanks

**Comment by yonghong-song** [comment]
Thanks @netedwardwu 
I think both tools are useful. `funcinterval` can be used to gauge the activity frequency in the system. `memleaktop` can help to get a better snapshot of user space allocations in the system. `funcinterval` can be a separate tool. Do you think we can fold `memleaktop` to exiting `memleak` tool if it will share a lot of codes with `memleak`?

https://github.com/iovisor/bcc/blob/master/CONTRIBUTING-SCRIPTS.md

**Comment by netedwardwu** [comment]
Hi @yonghong-song ,

> Do you think we can fold memleaktop to exiting memleak tool if it will share a lot of codes with memleak?

This is a good idea, and it's my first version.
However, I think as simple as possible for a bcc tool is a better way.
Therefore, I separate memleaktop feature from memleak to be a new bcc tool.

BTW, we use memleaktop to solve our memory leak problem in our customize driver(kthread).

I will try to release these two bcc tools by following the below link
https://github.com/iovisor/bcc/blob/master/CONTRIBUTING-SCRIPTS.md

Thanks

**Comment by yonghong-song** [comment]
memleaktop as a separate tool is okay. From the above description, `TOTAL_OUTSTANDING_MEM` is shown. This is not directly related to memory leak. But you use the tool to see whether total outstanding mem is increasing to decide memory leak? Maybe another column to show the delta from the previous show. Just an idea.

**Comment by netedwardwu** [comment]
Hi @yonghong-song ,

Thanks for your idea. The memory leak is a hard topic for debugging, you don't know the outstanding memory is really a memory leak problem or just the process really needs a lot of memory. Even the original memleak tool doesn't know
https://github.com/iovisor/bcc/blob/master/tools/memleak.py#L521
```
        print("[%s] Top %d stacks with outstanding allocations:" %
              (datetime.now().strftime("%H:%M:%S"), top_stacks))
```

The delta is a good idea, I will consider it.

Thank you

**Comment by netedwardwu** [comment]
#https://github.com/iovisor/bcc/pull/2939

**Comment by netedwardwu** [comment]
https://github.com/iovisor/bcc/issues/2997
Due to this problem, I won't push memleaktop yet. The result will mislead the user to the wrong path.
