### ISSUE TITLE
Does BCC support Chrome OS?

### ISSUE THREAD

**Issue by kloud1989** [iovisor/bcc#2944]
I can buid BCC on ChromeOS. But when I run the hello world, it reports 

> /virtual/include/bcc/helpers.h:52:10: fatal error: 'linux/version.h' file not found

I installed linux-source and Linuxheaders through ChromeBrew, and find that there is no such file still.
Is there anyone enabled BCC on Chrome OS? Does BCC support Chrome OS at this moment?

**Comment by yonghong-song** [comment]
Just kernel-source and linux headers are not enough. You need kernel development headers as well, which captures most of kernel internal headers and generated headers during build time.

**Comment by kloud1989** [comment]
@yonghong-song Thanks for your reply.
After some investigation, I made a workaround to provide kernel-build sources. However, I ended up with a new issue:

> create_probe_event: open(/sys/kernel/debug/tracing/kprobe_events): No such file or directory

I checked the debugfs, there is no _kprobe_events_.
I checked the kernel config and got:
```
$ /boot/config-`uname -r` | grep KPROBE
# CONFIG_KPROBES is not set
CONFIG_HAVE_KPROBES=y
CONFIG_HAVE_KPROBES_ON_FTRACE=y
```
So I have to build a new kernel, but to find there is no KPROBE related options in the config files. My kernel version is v4.19. Kind of difficult to make it work on ChromeOS.

**Comment by kloud1989** [comment]
I have finally enabled BCC on chromium os, although kernel build & update process is not very smooth. Chromium OS is not configured with kprobe by default, and kernel headers is not neither. Just open these two configs and BCC then can be enabled.
