### ISSUE TITLE
Get function params on return

### ISSUE THREAD

**Issue by kloud1989** [iovisor/bcc#2959]
Is there a way to retrieve function params on its return?
I want to trace every TCP send/recv event on both their entries and returns. I can get the params when tcp_sendmsg or tcp_recvmsg enters, but I can't get them on their returns.
Is it possible to retrieve them? How?
The current probe function is like this, it's not working, the family value can't be retrieved properly:

```
int trace_tcp_sendmsg_return(struct pt_regs *ctx, struct sock *sk,
    struct msghdr *msg, size_t size) {
    u64 ts_ns = bpf_ktime_get_ns();
    int ret = PT_REGS_RC(ctx);
    u32 pid = bpf_get_current_pid_tgid() >> 32;
    FILTER
    u16 family = sk->__sk_common.skc_family;
    if (family == AF_INET || family == AF_INET6) {
        struct ret_event_t ret_event = { };
        ret_event.ts_ns = ts_ns;
        ret_event.pid = pid;
        ret_event.type = TCP_EVENT_TYPE_SEND;
        ret_event.ret = ret;
        ret_events.perf_submit(ctx, &ret_event, sizeof(ret_event));
    }
    return 0;
}
```

**Comment by kloud1989** [comment]
This seems reasonable. Thanks @willfindlay 

> The usual pattern is to trace entry, store intermediate values in a percpu array and look up in return.

**Comment by anakryiko** [comment]
Check fexit BPF program type, it allows to read input arguments on function exit. Support for it in BCC was added by https://github.com/iovisor/bcc/pull/2726.

**Comment by kloud1989** [comment]
> Check fexit BPF program type, it allows to read input arguments on function exit. Support for it in BCC was added by #2726.

This seems cool. But as discussed in the PR, my kernel is not supporting BTF:
```
libbpf: failed to find valid kernel BTF
libbpf: vmlinux BTF is not found
```
I'm working on Chromium OS, and kernel v5.4.44.
I'll try the conventional method as suggested by @willfindlay first, and pay attention to this feature when new kernel versions are released.

**Comment by anakryiko** [comment]
5.4 is perfectly capable of BTF support, you just need to build your kernel with CONFIG_DEBUG_INFO_BTF=y.

As for fentry/fexit, seems like it's supported starting from 5.5, so yeah, unless you can upgrade, you are out of luck.

**Comment by kloud1989** [comment]
I updated the kernel with CONFIG_DEBUG_INFO_BTF=y. This time I got this report:
`libbpf: bpf_prog_put is not found in vmlinux BTF`. 
Any more config should I change?

**Comment by anakryiko** [comment]
On Mon, Jun 15, 2020 at 7:40 PM kloud <notifications@github.com> wrote:

> I updated the kernel with CONFIG_DEBUG_INFO_BTF=y. This time I got this
> report:
> libbpf: bpf_prog_put is not found in vmlinux BTF.
> Any more config should I change?
>

Oh, right, I keep forgetting. You need pahole 1.16+ (from dwarves package)
to get function information in kernel BTF.

**Comment by kloud1989** [comment]
Thanks for your updates @anakryiko.
Sadly, I'm building the Chromium kernel on Ubuntu 16.04. Since libc6>=2.26 is required to install the dwarves package(1.16+), I may need a new Ubuntu env. The Chromium kernel build env may take a long time, I'll try this some other time.
