### ISSUE TITLE
Return in LSM_PROBE not working as expected

### ISSUE THREAD

**Issue by willfindlay** [iovisor/bcc#2976]
A few days ago, I filed #2961 because I was confused that the LSM_PROBE program type was not behaving as expected. In particular, returning something like `-EPERM` should cause the operation to fail with EPERM.

I have done some experiments with https://github.com/iovisor/bpftrace/pull/1347 (bpftrace implementation for LSM probes) and compared generated bytecode from bcc with generated bytecode from bpftrace. I have found the problem.

bcc seems to be ignoring return value and always generating something like `r0 = 0; exit`, whereas bpftrace sets `r0` according to the specified value. Indeed, the following modifications to the below example produce the expected behavior:

```c
// Original code that doesn't work
#include <linux/fs.h>

LSM_PROBE(inode_permission, struct inode *inode, int mask) {
    bpf_trace_printk("lsm\n");
    return -1;
}
```

```c
// Modified code that does work
#include <linux/fs.h>

LSM_PROBE(inode_permission, struct inode *inode, int mask) {
    bpf_trace_printk("lsm\n");
    asm("r0 = -1; exit");
    return 0;
}
```

I think that LSM probes should be made to work like they do in https://github.com/iovisor/bpftrace/pull/1347, setting r0 according to the return value specified. Is this something that would be possible in bcc? If not, perhaps we could add a helper instead like `lsm_return` that results in the bytecode above?

**Comment by yonghong-song** [comment]
@willfindlay Could you check whether the pull request https://github.com/iovisor/bcc/pull/2978 fixed your problem or not?

**Comment by willfindlay** [comment]
@yonghong-song Yes this does fix the problem. Thanks!

**Comment by willfindlay** [comment]
#2978 closes
