### ISSUE TITLE
Fully support new ringbuf map type in bcc

### ISSUE THREAD

**Issue by willfindlay** [iovisor/bcc#2985]
Linux 5.7 added a new ringbuf map type that can be used as an alternative to perf ring buffers for outputting custom events. I would be interested in having support for this in bcc.

I am willing to try to take a stab at adding support for this, but would need a bit of guidance first from a more experienced contributor/maintainer in terms of what changes would need to be made.

**Comment by yonghong-song** [comment]
Thanks! The following is an example you can mimic.
https://github.com/iovisor/bcc/commit/6cacc41462bae12b1c38aabc7a6b85f40783da9a#diff-f37f0b7028086d94a9c9dfdadcec11ec

**Comment by willfindlay** [comment]
Thanks for the example @yonghong-song.

**Comment by anakryiko** [comment]
See also if you can just simply re-use libbpf's implementation for consuming ringbuf and keep API close enough to simplify porting. See https://github.com/libbpf/libbpf/blob/master/src/ringbuf.c for implementation itself.
