### ISSUE TITLE
support C-style /* ... */ comment?

### ISSUE THREAD

**Issue by yonghong-song** [iovisor/bcc#3]
I am adding arp support in proto.b, and I found /* ... */ is not supported.

......
state ethernet {
  switch $ethernet.type {
    case 0x0800 {
      next proto::ip;
    };
    case 0x0806 {
      next proto::arp;
    };
    case 0x8100 {
      next proto::dot1q;
    };
    case * {
      goto EOP;
    };
  }
}

/*
// struct arp {
//   u32 htype:16
//   u32 ptype:16
//   u32 hlen:8
//   u32 plen:8
//   u32 oper:16
//   u64 sha:48
//   u32 spa:32
//   u64 tha:48
//   u32 tpa:32
// }

// state arp {
//   goto EOP;
// }
*/
.....

If user want to comment out a large portion of code, a single /* ... */ is better than a bunch of //.
What do you think?

**Comment by drzaeus77** [comment]
Supported with clang frontend.
