### ISSUE TITLE
Can BCC be used to trace UDP send/recv events?

### ISSUE THREAD

**Issue by kloud1989** [iovisor/bcc#3001]
TCP events is well supported by BCC, and there are plenty of examples in the project. However, I find no such support for UDP events.
I tried to attach probes to _udp_sendmsg_ and _udp_recv_ msg, and the probes are not activated when UDP events happened.
Is it impossible to do UDP tracing and if yes why?

**Comment by netedwardwu** [comment]
Maybe you can use funclatency bcc tool to test those symbols at first.
Or using perf/ftrace to check is okay or not.

**Comment by kloud1989** [comment]
Thanks, @netedwardwu. Nice to know about this _funclatency bcc tool_.
The tool confirms UDP events can be traced.
It seems UDP socks are not valid at the event entry time. My probes will filter those events with non-valid ip/port like what the TCP tools do. That's why I can't observe those events from my tool.
