### ISSUE TITLE
Question: how to use map to save recent N events?

### ISSUE THREAD

**Issue by chengmingzhou** [iovisor/bcc#3004]
Hi all,
I want to use map to save recent N events in kernel, but I brower the bcc refrence guide: https://github.com/iovisor/bcc/blob/master/docs/reference_guide.md
i can't find the document about how to use the Queue Map...
btw, my system is using a 4.14 kernel.
Thanks.

**Comment by willfindlay** [comment]
Stack and Queue support for bcc was just added 6 days ago in #2993. There is no documentation yet (or Python API support afaik), but for now you should be able to figure out how it works from the commit messages / pull request.

**Comment by willfindlay** [comment]
@chengmingzhou I've taken the time to add Python API support as well as documentation for Queue/Stack in #3013. Feel free to check out that PR in the meantime until it gets merged.
