### ISSUE TITLE
kernel addresses generated by bcc

### ISSUE THREAD

**Issue by Anjali05** [iovisor/bcc#3025]
Hi, 

I am working with a script that does lock analysis using bcc, (https://github.com/prathyushpv/klockstat/blob/master/lockstat.py). My goal is to resolve the addresses generated to line number in the source code using _addr2line_(https://linux.die.net/man/1/addr2line). When  I try to pass the address generated by _sym()_ to _addr2line_ at line 242 in this script, addr2line is not able to resolve it and returns 0. 

I thought maybe passing _vmlinux_ to _addr2line_ would be a problem if the address being generated lies in any module. But I tried searching for the address in _/proc/modules_ and in _/proc/kallsyms_ but I am not able to find it. I am wondering if bcc does anything internally to the addresses that changes/modifies the address because if the addresses being generated is able to resolve into function names, it should work with _addr2line_ as well to get the line number in the source code? I would really appreciate some insights on this.

Thanks.

**Comment by yonghong-song** [comment]
kernel address won't work with addr2line. /proc/kallsyms is the right place to check. Do you have specific examples on which address/symbol you cannot find?

**Comment by Anjali05** [comment]
@yonghong-song I turned off KASLR and its working with addr2line. But I am still curious if bcc does something internally to the addresses that make them different from what is there in _vmlinux_.
