### ISSUE TITLE
When upgrade bcc version, how to avoid upgrade kernel

### ISSUE THREAD

**Issue by Mr-dot-lu** [iovisor/bcc#3027]
I'm want to upgrade bcc version, but how to avoid upgrade kernel version. Because I need kernel keep stable.

Thanks.

**Comment by yonghong-song** [comment]
There is no need to upgrade kernel. newer bcc should work with the kernel you are currently using.

**Comment by Mr-dot-lu** [comment]
Great reply, Thanks!
