### ISSUE TITLE
bcc.BPF() throws exception on CentOS 7.6 in Python

### ISSUE THREAD

**Issue by akki** [iovisor/bcc#3038]
Hi,

I am receiving the following exception when using `bcc.BPF()` method in Python:

```
Unable to find kernel headers. Try rebuilding kernel with CONFIG_IKHEADERS=m (module) or installing the kernel development package for your running kernel version.
chdir(/lib/modules/4.19.76-linuxkit/build): No such file or directory
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 359, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>
```

These are the steps I followed to hit this error:
```bash
akshesh$ docker run -itd --name centos-ebpf centos:7.6.1810
akshesh$ docker exec -it centos-ebpf bash

root@centos-ebpf$ # From https://github.com/iovisor/bcc/blob/master/INSTALL.md#centos---source
root@centos-ebpf$ yum install -y epel-release
root@centos-ebpf$ yum update -y
root@centos-ebpf$ yum groupinstall -y "Development tools"
root@centos-ebpf$ yum install -y elfutils-libelf-devel cmake3 git bison flex ncurses-devel

root@centos-ebpf$ git clone https://github.com/iovisor/bcc.git
root@centos-ebpf$ mkdir bcc/build; cd bcc/build
root@centos-ebpf$ cmake3 ..
root@centos-ebpf$ make
root@centos-ebpf$ sudo make install
```

Then I ran the following code:
```python
root@centos-ebpf$ python
Python 2.7.5 (default, Apr  2 2020, 13:16:51)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from bcc import BPF
>>> from threading import Thread
>>> from socket import socket
>>> import ctypes as ct
>>> import time
>>> from bcc import BPF
>>>
>>> prog = '''
... #include <linux/sched.h>
... /* This is a BCC macro for that creates a BPF data-structure that we can communicate with in user-mode */
... BPF_PERF_OUTPUT(events);
... // The following is the data-structure we'll pass to our user-land program
... struct data_t {
...     char process_name[TASK_COMM_LEN];    // Process name
...     u32 pid;                             // Process ID
...     int socket_fd;                       // Bound Socket FD
... };
... /* This is our BPF routine, it contains two arguments:
... - A pt_regs* struct, which contains the BPF VM registers
at gets the process name that invoked the bind operation
    bpf_get_current_comm(&data.process_name, sizeof(data.process_name));

    // Gets the pid via the bpf helper (pid is the upper 32 bits)
    data.pid = (u32) (bpf_get_current_pid_tgid() >> 32);
    data.socket_fd = sockfd;
    // Copies the data to the BPF structure, it is now available to user-mode
    events.perf_submit(ctx, &data, sizeof(data));
    return 0;
}
'''
# Compiles the BPF program via LLVM
b = BPF(text=prog)... - A socket fd - this will actually be transformed by bcc to a local variable that is set by the registers, see note below
... */
... int on_bind(struct pt_regs* ctx, int sockfd) {
...     struct data_t data = {};
...     // A bpf helper that gets the process name that invoked the bind operation
...     bpf_get_current_comm(&data.process_name, sizeof(data.process_name));
...
...     // Gets the pid via the bpf helper (pid is the upper 32 bits)
...     data.pid = (u32) (bpf_get_current_pid_tgid() >> 32);
...     data.socket_fd = sockfd;
...     // Copies the data to the BPF structure, it is now available to user-mode
...     events.perf_submit(ctx, &data, sizeof(data));
...     return 0;
... }
... '''
>>> # Compiles the BPF program via LLVM
... b = BPF(text=prog)
Unable to find kernel headers. Try rebuilding kernel with CONFIG_IKHEADERS=m (module) or installing the kernel development package for your running kernel version.
chdir(/lib/modules/4.19.76-linuxkit/build): No such file or directory
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 359, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>
```

Some details about my OS/environment:
```bash
root@centos-ebpf$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

root@centos-ebpf$ uname -a
Linux 681d46b746ef 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Can anyone please confirm that I have hit a bug or am I doing something wrong? I would appreciate if you can point me in the correct direction to fix this (either make a PR or fix my environment).

**Comment by willfindlay** [comment]
Do you have your distro's kernel headers package installed? bcc is telling you it can't find your kernel headers. It needs them to compile the BPF program.

**Comment by akki** [comment]
@willfindlay Thank you for the quick response.
I did try installing them (but I am not 100% sure if I am doing the right thing).

This is what I tried and the output:
```
[root@centos-ebpf]$ yum install kernel-headers
.
.
.
<successful installation output>
```

But I saw that it is trying to look for the directory `/lib/modules/4.19.76-linuxkit/build`, so I also tried:
```
[root@centos-ebpf]$ yum install kernel-headers-$(uname -r)
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: mirrors.thzhost.com
 * centos-sclo-rh: mirrors.thzhost.com
 * centos-sclo-sclo: mirrors.thzhost.com
 * epel: my.mirrors.thegigabit.com
 * extras: mirrors.thzhost.com
 * updates: mirrors.thzhost.com
No package kernel-headers-4.19.76-linuxkit available.
Error: Nothing to do
```

I get the same error on running that Python script, after doing these steps.

**Comment by willfindlay** [comment]
Not a centos user so I'm unsure what the package naming conventions are like. A quick Google search says that `kernel-devel` may be the package you are looking for. If you figure out your problem, you may wish to submit a PR to add it to the documentation for your distro.

**Comment by akki** [comment]
Appreciate your time & help.

The steps mentioned in https://github.com/iovisor/bcc/blob/master/INSTALL.md#centos---source do install the `kernel-debug-devel` package which I think is what the "or installing the kernel development package for your running kernel version" part of the error is referring to.

I'll try to investigate further. Maybe someone else knows the fix to this problem so it might be helpful like to keep this issue open.

**Comment by ethercflow** [comment]
@akki You need `yum install kernel-devel-$(uname -r)`.

**Comment by akki** [comment]
Hi @ethercflow 

Thanks for the advise.

I tried it out but I get
```
No package kernel-devel-4.19.76-linuxkit available.
```

Then I installed `kernel-devel` with `yum install kernel-devel` (note that I already had `kernel-debug-devel` installed) but I still get the same error from my Python code.


Can you think of anything that I might be doing wrong? (or if there is any other details about my environment which might help in investigating this issue, I would be happy to share).
I am running all this in a Docker container built upon `centos:7.6.1810` image on a Mac laptop.

**Comment by akki** [comment]
Ahh, I just found this:
```bash
root@centos-ebpf$ cat /etc/*release
CentOS Linux release 7.8.2003 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.8.2003 (Core)
CentOS Linux release 7.8.2003 (Core)
```

Seems like the `centos:7.6.1810` Docker image is actually building CentOS 7.8 ? 🤔 
And the [installation guide](https://github.com/iovisor/bcc/blob/master/INSTALL.md#centos---source) mentions that it is only for `7.6`.

Can this be the reason? 😐

**Comment by ethercflow** [comment]
> Hi @ethercflow
> 
> Thanks for the advise.

You're welcome.

> I tried it out but I get
> 
> ```
> No package kernel-devel-4.19.76-linuxkit available.
> ```

> I am running all this in a Docker container built upon centos:7.6.1810 image on a Mac laptop.

@akki, Please check if `/lib/modules/4.19.76-linuxkit/build` is in the VM which provide linux kernel.
If not exist, please try to run `yum install kernel-devel-$(uname -r)` or `apt get` depends on the distribution used by the VM.
Then make sure VM's `/lib/modules/4.19.76-linuxkit/build` can be accessed in container too.

**Comment by akki** [comment]
I am closing this issue for now as I have not been able to spend time since long and still not sure if it is a problem with my setup or bcc.
Many thanks for all the help in the thread though - really appreciate your time.
