### ISSUE TITLE
/usr/share/bcc/tools/trace cannot exit from loops

### ISSUE THREAD

**Issue by realhezhe** [iovisor/bcc#3049]
On python 3.8.5 and kernel 5.8
root@intel-x86-64:~# /usr/share/bcc/tools/trace do_sys_openat2 -M 1
PID     TID     COMM            FUNC             
179     179     systemd-journal do_sys_openat2   
Exception ignored on calling ctypes callback function: <function PerfEventArray._open_perf_buffer.<locals>.raw_cb_ at 0x7f2a75f060d0>
Traceback (most recent call last):
  File "/usr/lib64/python3.8/site-packages/bcc/table.py", line 685, in raw_cb_
    callback(cpu, data, size)
  File "/usr/share/bcc/tools/trace", line 630, in print_event
    exit()
  File "/usr/lib64/python3.8/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: None
The above repeated endlessly

The following change could make it work, but not sure if it's the best way to do.

diff --git a/tools/trace.py b/tools/trace.py
index 7a61594f..d09dd2a8 100755
--- a/tools/trace.py
+++ b/tools/trace.py
@@ -627,7 +627,7 @@ BPF_PERF_OUTPUT(%s);
                 Probe.event_count += 1
                 if Probe.max_events is not None and \
                    Probe.event_count >= Probe.max_events:
"-                        exit()"
"+                        os._exit(0)"
                 sys.stdout.flush()
 
"         def attach(self, bpf, verbose):"

**Comment by yonghong-song** [comment]
Maybe `sys.exit()`?

**Comment by yonghong-song** [comment]
It does not fail in my environment with python 3.7
```
$ sudo trace.py do_sys_openat2 -M 1 
PID     TID     COMM            FUNC             
117055  117055  tmux: server    do_sys_openat2
```

Do you know why it fails? Maybe due to python site packages?
https://www.geeksforgeeks.org/python-exit-commands-quit-exit-sys-exit-and-os-_exit/

**Comment by realhezhe** [comment]
sys.exit() and other way would trigger the same call trace.
Seems due to new python update. But it's not easy for me the turn between versions. I'll try.

**Comment by nurdann** [comment]
This could be related to #4649
