### ISSUE TITLE
[Question] Does BPF map, perf buffers, and other components in-kernel resources freed after process exits?

### ISSUE THREAD

**Issue by yzhao1012** [iovisor/bcc#3104]
A process invokes BCC to deploy BCC code, open map and perf buffers, and other components.

In the case of process abort or exit, if the process does not invoke the process of close map, perf buffers etc., will those things be cleaned up from inside kernel automatically?

PS: I think this must have been asked before, but I could not find a relevant issue in the history.

**Comment by yonghong-song** [comment]
Yes, all maps, progs, perf ring buffers will be auto cleaned up.
The only exception is probably for < 4.17 kernel, if you use debugfs to install kuprobes in /sys/kernel/debug/tracing/{k,u}probe_events. bcc registered atexit function to do this cleanup. But if your program e.g. segfaulted, the entry will leave in /sys/kernel/debug/tracing/{k,u}probe_events files. You will need to manually remove them.

**Comment by yzhao1012** [comment]
Thanks Yonghong!
