### ISSUE TITLE
BPF_HASH with value as a struct containing a pointer (linked list) or array

### ISSUE THREAD

**Issue by codekaust** [iovisor/bcc#3147]
I want to create a BPF_HASH with its value to be either:
1. A struct with a linked list pointer.
```
struct unit {
    __be16 tot_len;
    struct unit *next;
};

struct value {
   __be16 length;
   struct unit *unt;
};
```

2. A struct with array:
```
struct val {
    __be16 length;
    uint32_t asd[KEYLEN];
};
```

I tried both formats but error `invalid indirect read from stack off -16+13 size 16` appears.

Is it theoretically possible to have BPF_HASH values as such?

**Comment by yonghong-song** [comment]
The choice 1 won't work as you cannot access other values through pointer, there is risk for that, the value might be gone and reused form something else.

The choice 2 should work, maybe you can have complete code so people can help you.
