### ISSUE TITLE
error:redefinition of 'bpf_map_lookup_elem' with a different type

### ISSUE THREAD

**Issue by sachints123** [iovisor/bcc#3157]
Hi,
I am new to ebpf and bcc and facing some environment issues. Your help will be much appreciated.
I have taken a simple icmp packet processing code from xdp tutorial and trying to execute on my ubuntu20.04 server. 
I am using python3 to write user code and sandboxing ebpf program inside it.
Simple "hello world" program works fine BUT when i try an ebpf program with header files included, getting different errors. 

steps followed:
Enabled kernel configurations
installed dependency packages
installed bcc from source as per BCC tutorial page(https://github.com/iovisor/bcc/blob/master/INSTALL.md#ubuntu---source)

Below is the compilation errors and i have attached the source code files also. 
Thanks in advance.

Thanks,
Sachin

Files: **icmp.txt** - python script to just load ebpf program
**icmp_parsing.c.txt** - ebpf program

[icmp.txt](https://github.com/iovisor/bcc/files/5494766/icmp.txt)
[icmp_parsing.c.txt](https://github.com/iovisor/bcc/files/5494767/icmp_parsing.c.txt)

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
sac@dip-server:~/ebpf/examples$ sudo python icmp.py
In file included from /virtual/main.c:9:
In file included from /home/huawei/ebpf/bcc/src/cc/libbpf/src/bpf_helpers.h:11:
/home/huawei/ebpf/bcc/src/cc/libbpf/src/bpf_helper_defs.h:45:16: error: redefinition of 'bpf_map_lookup_elem'
      with a different type: 'void *(*)(void *, const void *)' vs 'void *(*)(void *, void *)'
static void *(*bpf_map_lookup_elem)(void *map, const void *key) = (void *) 1;
               ^
/virtual/include/bcc/helpers.h:431:16: note: previous definition is here
static void *(*bpf_map_lookup_elem)(void *map, void *key) =
               ^
In file included from /virtual/main.c:9:
In file included from /home/huawei/ebpf/bcc/src/cc/libbpf/src/bpf_helpers.h:11:
/home/huawei/ebpf/bcc/src/cc/libbpf/src/bpf_helper_defs.h:67:15: error: redefinition of 'bpf_map_update_elem'
      with a different type: 'long (*)(void *, const void *, const void *, __u64)' (aka 'long (*)(void *, const
      void *, const void *, unsigned long long)') vs 'int (*)(void *, void *, void *, u64)' (aka 'int (*)(void
      *, void *, void *, unsigned long long)')
static long (*bpf_map_update_elem)(void *map, const void *key, const void *value, __u64 flags) = (void *) 2;
              ^
/virtual/include/bcc/helpers.h:433:14: note: previous definition is here
static int (*bpf_map_update_elem)(void *map, void *key, void *value, u64 flags) =
             ^
In file included from /virtual/main.c:9:
In file included from /home/huawei/ebpf/bcc/src/cc/libbpf/src/bpf_helpers.h:11:
/home/huawei/ebpf/bcc/src/cc/libbpf/src/bpf_helper_defs.h:77:15: error: redefinition of 'bpf_map_delete_elem'
      with a different type: 'long (*)(void *, const void *)' vs 'int (*)(void *, void *)'
static long (*bpf_map_delete_elem)(void *map, const void *key) = (void *) 3;
              ^
/virtual/include/bcc/helpers.h:435:14: note: previous definition is here
static int (*bpf_map_delete_elem)(void *map, void *key) =
             ^
In file included from /virtual/main.c:9:
In file included from /home/huawei/ebpf/bcc/src/cc/libbpf/src/bpf_helpers.h:11:
/home/huawei/ebpf/bcc/src/cc/libbpf/src/bpf_helper_defs.h:91:15: error: redefinition of 'bpf_probe_read' with a
      different type: 'long (*)(void *, __u32, const void *)' (aka 'long (*)(void *, unsigned int, const void
      *)') vs 'int (*)(void *, u64, const void *)' (aka 'int (*)(void *, unsigned long long, const void *)')
static long (*bpf_probe_read)(void *dst, __u32 size, const void *unsafe_ptr) = (void *) 4;
              ^
/virtual/include/bcc/helpers.h:437:14: note: previous definition is here
static int (*bpf_probe_read)(void *dst, u64 size, const void *unsafe_ptr) =
             ^
In file included from /virtual/main.c:9:
In file included from /home/huawei/ebpf/bcc/src/cc/libbpf/src/bpf_helpers.h:11:
/home/huawei/ebpf/bcc/src/cc/libbpf/src/bpf_helper_defs.h:103:16: error: redefinition of 'bpf_ktime_get_ns'
static __u64 (*bpf_ktime_get_ns)(void) = (void *) 5;
               ^
/virtual/include/bcc/helpers.h:439:14: note: previous definition is here
static u64 (*bpf_ktime_get_ns)(void) =
             ^
In file included from /virtual/main.c:9:
In file included from /home/huawei/ebpf/bcc/src/cc/libbpf/src/bpf_helpers.h:11:
/home/huawei/ebpf/bcc/src/cc/libbpf/src/bpf_helper_defs.h:166:15: error: redefinition of 'bpf_trace_printk' as
      different kind of symbol
static long (*bpf_trace_printk)(const char *fmt, __u32 fmt_size, ...) = (void *) 6;
              ^
/virtual/include/bcc/helpers.h:447:5: note: previous definition is here
int bpf_trace_printk(const char *fmt, ...) asm("llvm.bpf.extra");
    ^
In file included from /virtual/main.c:9:
In file included from /home/huawei/ebpf/bcc/src/cc/libbpf/src/bpf_helpers.h:11:
/home/huawei/ebpf/bcc/src/cc/libbpf/src/bpf_helper_defs.h:182:16: error: redefinition of 'bpf_get_prandom_u32'
static __u32 (*bpf_get_prandom_u32)(void) = (void *) 7;
               ^
/virtual/include/bcc/helpers.h:441:14: note: previous definition is here
static u32 (*bpf_get_prandom_u32)(void) =
             ^
In file included from /virtual/main.c:9:
In file included from /home/huawei/ebpf/bcc/src/cc/libbpf/src/bpf_helpers.h:11:
/home/huawei/ebpf/bcc/src/cc/libbpf/src/bpf_helper_defs.h:195:16: error: redefinition of
      'bpf_get_smp_processor_id' with a different type: '__u32 (*)(void)' (aka 'unsigned int (*)(void)') vs
      'u64 (*)(void)' (aka 'unsigned long long (*)(void)')
static __u32 (*bpf_get_smp_processor_id)(void) = (void *) 8;
               ^
/virtual/include/bcc/helpers.h:454:14: note: previous definition is here
static u64 (*bpf_get_smp_processor_id)(void) =
             ^
In file included from /virtual/main.c:9:
In file included from /home/huawei/ebpf/bcc/src/cc/libbpf/src/bpf_helpers.h:11:
/home/huawei/ebpf/bcc/src/cc/libbpf/src/bpf_helper_defs.h:216:15: error: redefinition of 'bpf_skb_store_bytes'
      with a different type: 'long (*)(struct __sk_buff *, __u32, const void *, __u32, __u64)' (aka 'long
      (*)(struct __sk_buff *, unsigned int, const void *, unsigned int, unsigned long long)') vs 'int (*)(void
      *, unsigned long long, void *, unsigned long long, unsigned long long)'
static long (*bpf_skb_store_bytes)(struct __sk_buff *skb, __u32 offset, const void *from, __u32 len, __...
              ^
/virtual/include/bcc/helpers.h:824:14: note: previous definition is here
static int (*bpf_skb_store_bytes)(void *ctx, unsigned long long off, void *from,
             ^
In file included from /virtual/main.c:9:
In file included from /home/huawei/ebpf/bcc/src/cc/libbpf/src/bpf_helpers.h:11:
/home/huawei/ebpf/bcc/src/cc/libbpf/src/bpf_helper_defs.h:245:15: error: redefinition of 'bpf_l3_csum_replace'
      with a different type: 'long (*)(struct __sk_buff *, __u32, __u64, __u64, __u64)' (aka 'long (*)(struct
      __sk_buff *, unsigned int, unsigned long long, unsigned long long, unsigned long long)') vs 'int (*)(void
      *, unsigned long long, unsigned long long, unsigned long long, unsigned long long)'
static long (*bpf_l3_csum_replace)(struct __sk_buff *skb, __u32 offset, __u64 from, __u64 to, __u64 siz...
              ^
/virtual/include/bcc/helpers.h:827:14: note: previous definition is here
static int (*bpf_l3_csum_replace)(void *ctx, unsigned long long off, unsigned long long from,
             ^
In file included from /virtual/main.c:9:
In file included from /home/huawei/ebpf/bcc/src/cc/libbpf/src/bpf_helpers.h:11:
/home/huawei/ebpf/bcc/src/cc/libbpf/src/bpf_helper_defs.h:281:15: error: redefinition of 'bpf_l4_csum_replace'
      with a different type: 'long (*)(struct __sk_buff *, __u32, __u64, __u64, __u64)' (aka 'long (*)(struct
      __sk_buff *, unsigned int, unsigned long long, unsigned long long, unsigned long long)') vs 'int (*)(void
      *, unsigned long long, unsigned long long, unsigned long long, unsigned long long)'
static long (*bpf_l4_csum_replace)(struct __sk_buff *skb, __u32 offset, __u64 from, __u64 to, __u64 fla...
              ^
/virtual/include/bcc/helpers.h:830:14: note: previous definition is here
static int (*bpf_l4_csum_replace)(void *ctx, unsigned long long off, unsigned long long from,
             ^
In file included from /virtual/main.c:9:
In file included from /home/huawei/ebpf/bcc/src/cc/libbpf/src/bpf_helpers.h:11:
/home/huawei/ebpf/bcc/src/cc/libbpf/src/bpf_helper_defs.h:344:15: error: redefinition of 'bpf_clone_redirect'
      with a different type: 'long (*)(struct __sk_buff *, __u32, __u64)' (aka 'long (*)(struct __sk_buff *,
      unsigned int, unsigned long long)') vs 'int (*)(void *, int, u32)' (aka 'int (*)(void *, int, unsigned
      int)')
static long (*bpf_clone_redirect)(struct __sk_buff *skb, __u32 ifindex, __u64 flags) = (void *) 13;
              ^
/virtual/include/bcc/helpers.h:452:14: note: previous definition is here
static int (*bpf_clone_redirect)(void *ctx, int ifindex, u32 flags) =
             ^
In file included from /virtual/main.c:9:
In file included from /home/huawei/ebpf/bcc/src/cc/libbpf/src/bpf_helpers.h:11:
/home/huawei/ebpf/bcc/src/cc/libbpf/src/bpf_helper_defs.h:356:16: error: redefinition of
      'bpf_get_current_pid_tgid'
static __u64 (*bpf_get_current_pid_tgid)(void) = (void *) 14;
               ^
/virtual/include/bcc/helpers.h:456:14: note: previous definition is here
static u64 (*bpf_get_current_pid_tgid)(void) =
             ^
In file included from /virtual/main.c:9:
In file included from /home/huawei/ebpf/bcc/src/cc/libbpf/src/bpf_helpers.h:11:
/home/huawei/ebpf/bcc/src/cc/libbpf/src/bpf_helper_defs.h:366:16: error: redefinition of
      'bpf_get_current_uid_gid'
static __u64 (*bpf_get_current_uid_gid)(void) = (void *) 15;
               ^
/virtual/include/bcc/helpers.h:458:14: note: previous definition is here
static u64 (*bpf_get_current_uid_gid)(void) =
             ^
In file included from /virtual/main.c:9:
In file included from /home/huawei/ebpf/bcc/src/cc/libbpf/src/bpf_helpers.h:11:
/home/huawei/ebpf/bcc/src/cc/libbpf/src/bpf_helper_defs.h:381:15: error: redefinition of 'bpf_get_current_comm'
      with a different type: 'long (*)(void *, __u32)' (aka 'long (*)(void *, unsigned int)') vs
      'int (*)(void *, int)'
static long (*bpf_get_current_comm)(void *buf, __u32 size_of_buf) = (void *) 16;
              ^
/virtual/include/bcc/helpers.h:460:14: note: previous definition is here
static int (*bpf_get_current_comm)(void *buf, int buf_size) =
             ^
In file included from /virtual/main.c:9:
In file included from /home/huawei/ebpf/bcc/src/cc/libbpf/src/bpf_helpers.h:11:
/home/huawei/ebpf/bcc/src/cc/libbpf/src/bpf_helper_defs.h:411:16: error: redefinition of
      'bpf_get_cgroup_classid' with a different type: '__u32 (*)(struct __sk_buff *)' (aka 'unsigned int
      (*)(struct __sk_buff *)') vs 'u64 (*)(void *)' (aka 'unsigned long long (*)(void *)')
static __u32 (*bpf_get_cgroup_classid)(struct __sk_buff *skb) = (void *) 17;
               ^
/virtual/include/bcc/helpers.h:462:14: note: previous definition is here
static u64 (*bpf_get_cgroup_classid)(void *ctx) =
             ^
In file included from /virtual/main.c:9:
In file included from /home/huawei/ebpf/bcc/src/cc/libbpf/src/bpf_helpers.h:11:
/home/huawei/ebpf/bcc/src/cc/libbpf/src/bpf_helper_defs.h:431:15: error: redefinition of 'bpf_skb_vlan_push'
      with a different type: 'long (*)(struct __sk_buff *, __be16, __u16)' (aka 'long (*)(struct __sk_buff *,
      unsigned short, unsigned short)') vs 'u64 (*)(void *, u16, u16)' (aka 'unsigned long long (*)(void *,
      unsigned short, unsigned short)')
static long (*bpf_skb_vlan_push)(struct __sk_buff *skb, __be16 vlan_proto, __u16 vlan_tci) = (void *) 18;
              ^
/virtual/include/bcc/helpers.h:464:14: note: previous definition is here
static u64 (*bpf_skb_vlan_push)(void *ctx, u16 proto, u16 vlan_tci) =
             ^
In file included from /virtual/main.c:9:
In file included from /home/huawei/ebpf/bcc/src/cc/libbpf/src/bpf_helpers.h:11:
/home/huawei/ebpf/bcc/src/cc/libbpf/src/bpf_helper_defs.h:447:15: error: redefinition of 'bpf_skb_vlan_pop'
      with a different type: 'long (*)(struct __sk_buff *)' vs 'u64 (*)(void *)' (aka
      'unsigned long long (*)(void *)')
static long (*bpf_skb_vlan_pop)(struct __sk_buff *skb) = (void *) 19;
              ^
/virtual/include/bcc/helpers.h:466:14: note: previous definition is here
static u64 (*bpf_skb_vlan_pop)(void *ctx) =
             ^
In file included from /virtual/main.c:9:
In file included from /home/huawei/ebpf/bcc/src/cc/libbpf/src/bpf_helpers.h:11:
/home/huawei/ebpf/bcc/src/cc/libbpf/src/bpf_helper_defs.h:502:15: error: redefinition of
      'bpf_skb_get_tunnel_key' with a different type: 'long (*)(struct __sk_buff *, struct bpf_tunnel_key *,
      __u32, __u64)' (aka 'long (*)(struct __sk_buff *, struct bpf_tunnel_key *, unsigned int, unsigned long
      long)') vs 'int (*)(void *, void *, u32, u64)' (aka 'int (*)(void *, void *, unsigned int, unsigned long
      long)')
static long (*bpf_skb_get_tunnel_key)(struct __sk_buff *skb, struct bpf_tunnel_key *key, __u32 size, __...
              ^
/virtual/include/bcc/helpers.h:468:14: note: previous definition is here
static int (*bpf_skb_get_tunnel_key)(void *ctx, void *to, u32 size, u64 flags) =
             ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
Traceback (most recent call last):
  File "icmp.py", line 6, in <module>
    b = BPF(src_file=prog)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 364, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module b'icmp_parsing.c'

**Comment by yonghong-song** [comment]
could you remove this one?
```
   #include <linux/bpf_helpers.h>
```

**Comment by sachints123** [comment]
> could you remove this one?
> 
> ```
>    #include <linux/bpf_helpers.h>
> ```

Yes, it worked. thank you. 
Can you please give a proper reference guide to follow for (networking use cases)ebpf apis, restricted C, helper functions and python bpf APIs? 
Becauase i am facing issues when i load program and attach function, losing network connectivity with the system where i am attaching ebpf programs.

**Comment by yonghong-song** [comment]
the following link https://github.com/iovisor/bcc/tree/master/docs is a good place to go to bcc internals.
for bpf history, internals, cilium has a good doc https://docs.cilium.io/en/v1.8/bpf/
If after loading program and attach function, you lose network connectivity, if your program is accessing packets, maybe it drops the packet and this cause the issue?

**Comment by sachints123** [comment]
Thank you for sharing the links.
Yes, after correcting the proper action, it worked. Thank you.

**Comment by sachints123** [comment]
Thanks for sharing the info.
