### ISSUE TITLE
Header for BPF_PERF_OUTPUT macro?

### ISSUE THREAD

**Issue by lollipopman** [iovisor/bcc#3159]
I am trying to build a standalone eBPF program for easier development, rather than just an source string in [gobpf](https://github.com/iovisor/gobpf), but I am struggling to include all the necessary headers:
 
I have these at present:
```
#include <linux/kconfig.h>
#include <linux/bpf.h>
#include <uapi/linux/ptrace.h>
#include <bpf/bpf_helpers.h>
```
but none of them contain `BPF_PERF_OUTPUT`:

```
clang-12 \
    -D__KERNEL__ \
    -O2 -emit-llvm -c sourcerts.c \
    -Wno-address-of-packed-member \
    -Wno-pointer-sign \
    -I /lib/modules/5.9.0-1-amd64/source/include \
    -I /usr/include/bpf/include \
    -I /lib/modules/5.9.0-1-amd64/source/arch/x86/include \
    -I /lib/modules/5.9.0-1-amd64/build/include \
    -I /lib/modules/5.9.0-1-amd64/build/arch/x86/include/generated \
    -o - | \
    llc-12 -march=bpf -filetype=obj -o sourcerts.o
sourcerts.c:12:1: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
BPF_PERF_OUTPUT(sourcerts_events);
^
```

Any help on would be greatly appreciated.

**Comment by willfindlay** [comment]
BPF_PERF_OUTPUT is a bcc construction that is handled by the re-writer. You'll need to use the underlying constructs instead. The libbpf directory in this repository has some examples for you.

**Comment by lollipopman** [comment]
thanks @willfindlay, very much appreciated!

**Comment by willfindlay** [comment]
@lollipopman To be clear, when I say libbpf directory I mean https://github.com/iovisor/bcc/tree/master/libbpf-tools
