### ISSUE TITLE
CMake tools - use FILE + GLOB?

### ISSUE THREAD

**Issue by troyengel** [iovisor/bcc#317]
I'm working on the bcc-git packaging and noticed that certain parts of the tools/ tree were not propagating in the build; for example the new 'offtimecpu' utilities are missing from the DESTDIR install target. I'm reading commit c175cf8096523949b3e41400180f04313d147308 here:
````
set(FILES biolatency.8 biosnoop.8 funccount.8 funclatency.8 hardirqs.8
  killsnoop.8 opensnoop.8 pidpersec.8 softirqs.8 syncsnoop.8 tcpaccept.8
  tcpconnect.8 vfscount.8 vfsstat.8)
````
(and the other ones just like it for the other parts), and wondered -- is the better solution for us to use the file(GLOB ...) instead as outlined here? (disclaimer: I'm a cmake newbie)

* https://cmake.org/cmake/help/v3.0/command/file.html
````
file(GLOB FILES *.8)
file(GLOB PROGRAMS *.c *.py)
file(GLOB EXAMPLE_FILES *.txt)
list(REMOVE_ITEM EXAMPLE_FILES CMakeLists.txt)
````
...or something along those lines? The PROGRAMS is a bit difficult to glob out without regex since there's a mix of files with no extensions and .c in there. The bigger point being to try and make the CMake logic generic so that every change/add/delete won't require updating it later. Thoughts?

**Comment by drzaeus77** [comment]
Definitely worth looking into. I've been delinquent and working on some of the stuff in iovisor/iomodules, so there's a bit of a backlog in bcc.

The points you raise about PROGRAMS vs FILES is indeed why I kept the explicit list in this directory. There is probably a way to solve it, cmake provides a mechanism to parse lists, maybe I could glob the files with no extensions in some way. Let me look into it.

Besides that, it is past due time to tag 0.1.8, so my plan is to fix this bug one way or another and then tag.

**Comment by 4ast** [comment]
Should we rename the tools/xx to tools/xx.py ? then GLOB pattern would be much easier to apply and during install into /usr we can drop .py suffix?
as for 0.1.8 tag... could you keep it 0.1.7 for now. Let's reserve version bump for things like changes in API and probably the next one should be 0.2

**Comment by troyengel** [comment]
Awesome, thanks - I'll just go with the correct logic then like so for the bcc-tools-git split child:
````
  cd "${srcdir}/${pkgbase}/build/tools"
  make DESTDIR="${pkgdir}/" install

  cd "${srcdir}/${pkgbase}/build/man"
  make DESTDIR="${pkgdir}/" install
````
...then propagate this to the non-git packaging with 0.1.8 release whenever it's ready and all the stragglers will get sucked in properly (meaning, take out all my hacks). I was messing around with trying to use [!.] in globs to negate any files with a . in them but got nowhere with cmake (but I'm not super familiar with it).

**Comment by troyengel** [comment]
@4ast - this should just work; the minor (micro? part is a symlink, so "libbcc.so.0" should *maybe* be "libbcc.so.0.1" instead, but leaving "libbcc.so.0.1.7" free to be "libbcc.so.0.1.8". But looking at a lot of other libraries on my system, it seems like an API change should end up being libbcc.so.1 instead, ergo I think the middle symlink is supposed to be de-coupled from the release numbering.

````
-rwxr-xr-x  1 root root    14912 Sep  1 12:09 libanl-2.22.so
lrwxrwxrwx  1 root root       11 Sep  1 12:09 libanl.so -> libanl.so.1
lrwxrwxrwx  1 root root       14 Sep  1 12:09 libanl.so.1 -> libanl-2.22.so
````
...as an example of some random library here from the glibc package exemplifying it. So long as libbcc.so.0 == the same API, the 0.1.8 should be innocuous. But when 0.2.0 is released with an API change (is that the plan?) then it would become libbcc.so.1 symlinked to libbcc.so.0.2.0...

**Comment by 4ast** [comment]
libstdc++ didn't change the major number for years.
It is still /usr/lib64/libstdc++.so.6 -> libstdc++.so.6.0.19
but it does internal versioning. In our case the commit 93588503fd4e ("Add ability to set custom cflags when loading programs") changed c/py api. imo such things must bump the version in some way. Whether it's last digit or middle doesn't matter much as long as python side does:
lib = ct.CDLL("libbcc.so.0.1.7")
instead of just "libbcc.so".
or it uses "libbcc.so.0" then we're free to bump minor numbers at any time.

**Comment by troyengel** [comment]
Yeah on your last point, to solve it would be fix the paradigm now for the future and change the existing python to:

    lib = ct.CDLL("libbcc.so.0")

...then we could consider the 0.1.8 the "first stable release of API v0", further releases that changed the API again would require a movement to API v1, represented by libbcc.so.1 symlink and requiring that in your python? I think bcc is still young, not "out in the wild" a lot so there's time to somehow course correct with a plan that's future proof... better now than a year from now IMHO.

Or, another mental thought pattern -- just consider "0.1.x releases are wildly in flux and subject to change" and the API is not stable. The release of 0.2.0 would mark the first stable release of the API, then begin the above rules starting then. Same net result but gives the 0.1.x releases to come the chance to blow up the API and make it better before becoming rigid for real world use.

**Comment by 4ast** [comment]
yep. agree on ct.CDLL("libbcc.so.0") and making 0.2.0 the first stable release.
probably would be good to have few examples/tests that use C and C++ API directly.
