### ISSUE TITLE
example xdp_drop_count failed

### ISSUE THREAD

**Issue by xiaocaio** [iovisor/bcc#3172]
os: centos7.8
kernel: upgrade to 4.4.243(latest long term)
compiler: devtoolset-7 llvmtoolset-7
command: sudo ./xdp/xdp_drop_count.py eth0
bcc: main branch
result: 
could not open bpf map: dropcnt, error: Invalid argument
Traceback (most recent call last):
  File "./xdp/xdp_drop_count.py", line 131, in <module>
    device=offload_device)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 364, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>

how can i solve this problem? thanks

**Comment by yonghong-song** [comment]
4.4 is certainly too old for xdp. From https://github.com/iovisor/bcc/blob/master/docs/kernel-versions.md, xdp needs at least 4.8. The above map error may be due to percpu map. Not sure whether it is supported in centos7.8 4.4 kernel or not.

**Comment by xiaocaio** [comment]
> 4.4 is certainly too old for xdp. From https://github.com/iovisor/bcc/blob/master/docs/kernel-versions.md, xdp needs at least 4.8. The above map error may be due to percpu map. Not sure whether it is supported in centos7.8 4.4 kernel or not.

i changed the kernel from 4.4 to 5.9 mainline.  i compile a simple bpf filter with clang.
#include <linux/bpf.h>
#define SEC(NAME) __attribute__((section(NAME), used))
SEC("prog")
int  xdp_prog_simple(struct xdp_md *ctx)
{
return XDP_DROP;
}
char _license[] SEC("license") = "GPL";

command: 
1. clang -O2 -Wall -target bpf -g -c exam.c -o exam.o
2. sudo ip link set dev eth0 xdp obj exam.o
error display:
RTNETLINK answers: Operation not supported

it seems a error of hyper-v, but i cannot find any document about whether bcc/bpf is supported by hyper-v/virtualbox or not.
any tips for me ? thanks

**Comment by yonghong-song** [comment]
You may want to check whether your iproute2 package is recent or not to support xdp.

**Comment by xiaocaio** [comment]
> You may want to check whether your iproute2 package is recent or not to support xdp.

thanks
