### ISSUE TITLE
BPF_PROG_ARRAY set/get items from python programs

### ISSUE THREAD

**Issue by doup123** [iovisor/bcc#3176]
I have defined in the kernel program a BPF_PROG_ARRAY(fw,10). The array is created and I employ the call function to move to another xdp program. The main issue is related to the python code from which I am trying to set/get items from the BPF_PROG_ARRAY and it crashes. Specifically, I am posting below the code I am using:
**Code:**
    fw = bpf_program.get_table("fw")
    key = fw.Key(1)
    leaf = fw.Leaf(1)
    fw.__setitem__(key,leaf)
**Output:**
    File "/usr/lib/python3/dist-packages/bcc/table.py", line 339, in __setitem__
    raise Exception("Could not update table: %s" % errstr)
    Exception: Could not update table: Invalid argument
Note that I can set/get items from other types of BPF MAPS e.g. BPF_HASH 
Any ideas/comments would be really helpful. 
_P.S._
System: Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-29-generic x86_64)

**Comment by yonghong-song** [comment]
`bpf_prog_array` needs to set a program_fd. Are you sure leaf "1" is a valid program fd?

**Comment by doup123** [comment]
@yonghong-song thank you for the comment. The issue was not finally in the section that I shared before.
I attempted to clean the code and share the part that is working fine.
**Code**:
from bcc import BPF
import ctypes as ct
    device = "eth1"
    mode = BPF.XDP
    b = BPF(src_file = "xdp_prog_array_test.c") # there is a do_tail_call function in the xdp_prog_array_test.c file
    fn = b.load_func("do_tail_call", mode) # the issue seemed to appear in this command as before I was using BPF.KPROBE based on the provided example 
    if mode == BPF.XDP:
        b.attach_xdp(device, fn, flags)
        prog_array = b.get_table("prog_array")
        b1 = BPF(src_file = "./xdp_drop1.c")
        tail_fn = b1.load_func("xdp_drop", mode) # xdp_drop is  a function in the xdp_drop1.c file
        prog_array[ct.c_int(2)] = ct.c_int(tail_fn.fd)

I hope that would be helpful for anyone who has similar issues. 
The ticket can be closed.
