### ISSUE TITLE
Fold option of offcputime raise TypeError

### ISSUE THREAD

**Issue by mmaret-geny** [iovisor/bcc#318]
Running 
sudo ./offcputime -f 1

produce 
Traceback (most recent call last):
  File "./offcputime", line 189, in <module>
    line = k.name + ";"
TypeError: can't concat bytes to str

but it's working fine without the -f.
It looks like a python2/3 issue.
Modifying the shebang to use python2 solve the issue.

**Comment by drzaeus77** [comment]
!a zzz :-(

**Comment by drzaeus77** [comment]
Umm, my last comment was a mistake...must have left an email tab open or something. Anyway, fix incoming.

**Comment by mmaret-geny** [comment]
Thanks !
