### ISSUE TITLE
Tutorial doc. Lesson 16. task_switch.c

### ISSUE THREAD

**Issue by eecheng87** [iovisor/bcc#3188]
Recently, I'm tracing examples given in tutorial.
I stuck in one place of lesson 16:
```c
struct key_t {
    u32 prev_pid;
    u32 curr_pid;
};

BPF_HASH(stats, struct key_t, u64, 1024);
int `(struct pt_regs *ctx, struct task_struct *prev) {
    struct key_t key = {};
    u64 zero = 0, *val;

    key.curr_pid = bpf_get_current_pid_tgid();
    key.prev_pid = prev->pid;

    // could also use `stats.increment(key);`
    val = stats.lookup_or_try_init(&key, &zero);
    if (val) {
      (*val)++;
    }
    return 0;
}
```
Why can we use the address of local variable (`key`) as key of map? How can we guarantee that 
correct address of `key` will be gotten (if it was already in map) when `count_sched` was triggered in future (task switch event occurred)?

Any suggestion will be appreciated!

**Comment by willfindlay** [comment]
The key is not actually a pointer. You are passing in a pointer to a struct, but the actual map is keyed by the struct itself.

So what this is doing is the following:
1. Look up the current PID using a helper.
1. Look up the previous PID from the task struct.
1. Look up the map value at (curr, prev) or create it if it doesn't already exist.
1. Increment the contents of the value pointer.

Hope this helps!

**Comment by eecheng87** [comment]
Thanks for quick reply.

>  but the actual map is keyed by the struct itself.

Did **itself** mean hash table is keyed by `prev_pid` and `cur_pid` pair ?

**Comment by willfindlay** [comment]
> Did **itself** mean hash table is keyed by `prev_pid` and `cur_pid` pair ?

That's right.

**Comment by eecheng87** [comment]
Thanks for your quick reply again, I think issue can be closed.
