### ISSUE TITLE
The README file in this repo has some bad links - [404:NotFound]

### ISSUE THREAD

**Issue by MrCull** [iovisor/bcc#3189]
The markup version of the readme that is displayed for the main page in this repo contains the following bad links:

Status code [404:NotFound] - Link: https://github.com/iovisor/bcc/blob/master/tools/swapin_example.txt
Status code [404:NotFound] - Link: https://github.com/iovisor/bcc/blob/master/tools/vfscount.c
Status code [404:NotFound] - Link: https://github.com/iovisor/bcc/blob/master/tools/vfsstat.c

(The link in the readme’s raw markdown may appear in a different relative format to the links above)

--

**Extra**

Re-check this Repo via: http://githubreadmechecker.com/Home/Search?SingleRepoUri=https%3a%2f%2fgithub.com%2fiovisor%2fbcc
Check all Repos for this GitHub account: http://githubreadmechecker.com/Home/Search?User=iovisor

--

Theses bad links were found by a tool I recently created as part of an new experimental hobby project: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
I (a human) verified that this link is broken and have manually logged this Issue (i.e. this Issue has not been created by a bot).
If this has been in any way helpful then please consider giving the above Repo a Star.

If you have any feedback on the information provided here, or on the tool itself, then please feel free to share your thoughts and pass on the feedback, or log an “Issue”.

**Comment by yonghong-song** [comment]
@MrCull Thanks for reporting these! Could you submit a patch to remove stale links or if possible replace them with proper links?

**Comment by MrCull** [comment]
@yonghong-song see #3199

**Comment by kzys** [comment]
We can close this issue now :)
