### ISSUE TITLE
How to get call stack when tracing TCP?

### ISSUE THREAD

**Issue by prehistoric-penguin** [iovisor/bcc#3191]
I have checked the existed scripts, to get the call stack we usually use `struct pt_regs *ctx`, but for TCP tracing, the common ways are using `TRACEPOINT_PROBE(sock, inet_sock_set_state)` which don't have the `pt_reg struct`, so how to get the call stack? Is there any example?  Thanks!

**Comment by yonghong-song** [comment]
You can get the call stack the same way as kprobe. 
```
#define TRACEPOINT_PROBE(category, event) \
int tracepoint__##category##__##event(struct tracepoint__##category##__##event *args)
```

The context with TRACEPOINT_PROBE is called `args` instead of `ctx`.

**Comment by prehistoric-penguin** [comment]
> You can get the call stack the same way as kprobe.
> 
> ```
> #define TRACEPOINT_PROBE(category, event) \
> int tracepoint__##category##__##event(struct tracepoint__##category##__##event *args)
> ```
> 
> The context with TRACEPOINT_PROBE is called `args` instead of `ctx`.

Could you please provide some links for existed scripts or examples? I am a new comer.

**Comment by yonghong-song** [comment]
You may take a look at bcc/tools/memleak.py.
