### ISSUE TITLE
kernel support policy?

### ISSUE THREAD

**Issue by tehnerd** [iovisor/bcc#3208]
Are there any official kernel support policy? e.g. version xxx (or starting from commit hash zzz) of bcc requires at least kernel yyy to run.
If not - could you please start tracking this?

The issue is that it seems that tools in bcc/tools now requires 5.x+ kernel (in our env we found that it stops to work on ubuntu's 18.04 4.15 kernel after bpf_probe_read was changed to bpf_probe_read_users which is available only in recent kernels)

**Comment by yonghong-song** [comment]
bcc indeed checks the host to see whether bpf_probe_read_user is available or not. If not, it will go back to bpf_probe_read.

```
static std::string check_bpf_probe_read_user(llvm::StringRef probe,
        bool& overlap_addr) {
  if (probe.str() == "bpf_probe_read_user" ||
      probe.str() == "bpf_probe_read_user_str") {
    // Check for probe_user symbols in backported kernel before fallback
    void *resolver = get_symbol_resolver();
    uint64_t addr = 0;
    bool found = bcc_symcache_resolve_name(resolver, nullptr,
                  "bpf_probe_read_user", &addr) >= 0 ? true: false;
    if (found)
      return probe.str();

    /* For arch with overlapping address space, dont use bpf_probe_read for
     * user read. Just error out */
#if defined(__s390x__)
    overlap_addr = true;
    return "";
#endif

    if (probe.str() == "bpf_probe_read_user")
      return "bpf_probe_read";
    else
      return "bpf_probe_read_str";
  }
  return "";
}
```

Maybe we have a bug somewhere. Which tool did you see issues?

**Comment by tehnerd** [comment]
hmm. interesting. indeed. rerun and it works as expected. seems like some transient issue when new tool was running with old version of bcc library. sorry for inconvenience. working as expected indeed
