### ISSUE TITLE
4th argument to syscall probes is incorrect

### ISSUE THREAD

**Issue by harjoc** [iovisor/bcc#3223]
On 5.3-generic ubuntu kernels (and probably all kernels), and bcc v0.16.0, this probe:
```
int syscall__accept4(struct pt_regs *ctx, size_t a, size_t b, size_t c, size_t d)                        
{                                                                                                        
    bpf_trace_printk("%lx %lx\n", a, b);                                                                 
    bpf_trace_printk("%lx %lx\n", c, d);                                                                 
    return 0;
}
```
outputs:
```
3 7ffe2a2dfc40
7ffe2a2dfbd4 7f5c3a75d3a7
```
instead of the correct output from `strace nc -l 12345`:
```
accept4(0x3, 0x7ffe2a2dfc40, 0x7ffe2a2dfbd4, 0x800
```
So the 4th parameter is wrong. Is there a way to get it from pt_regs or from somewhere else ?

**Comment by yonghong-song** [comment]
The bug is fixed with the following commit:
   https://github.com/iovisor/bcc/commit/c23448e34ecd3cc9bfc19f0b43f4325f77c2e4cc
You can workaround manually with similar change to the commit.

**Comment by harjoc** [comment]
Thanks for searching the fix. Another alternative workaround I'm currently using is to probe on sys_accept4 with a function probe instead of a syscall probe.
