### ISSUE TITLE
disksnoop.py errors out

### ISSUE THREAD

**Issue by zstone12** [iovisor/bcc#3230]
So I've been doing the python developer tutorial and when I tried running disksnoop as per lesson 6 I got the following error:
~~~python
bcc git:(master) ✗ sudo python3 examples/tracing/disksnoop.py 
TIME(s) T BYTES LAT(ms) 
Traceback (most recent call last): 
File "examples/tracing/disksnoop.py", line 57, in <module> 
(task, pid, cpu, flags, ts, msg) = b.trace_fields() File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 1156, in trace_fields
pid, cpu, flags,ts = line[:ts_end].split()
ValueError: too many values to unpack (expected 4)
~~~
then I try to print `line[:ts_end]`.
the result is 
`[b'|',` `b'common_file_perm()']`
It seems that there is no data.

I've installed iovisor on Ubuntu:
4.15.0-29-generic Ubuntu 18.04.1 LTS

**Comment by yonghong-song** [comment]
I just tried on my 5.6 kernel with python 3.6, it works fine.

You mentioned there is no data, you can debug step-by-step likes: (1). first check whether bpf_trace_printk() made into /sys/kernel/debug/tracing/trace_pipe or not. If (1) succeeds, then try to `print(msg)` before msg.split() to see what it is.

Looks like in your case, bpf_trace_printk() did not make it. Maybe bpf program is not called at all? You can add a map to bpf program and access it in user space to check whether whether the program has executed or not. You can look at other examples, etc. on how to do this.

**Comment by zstone12** [comment]
thanks a lot.
The key problem is `bpf_trace_printk() `did not work.
There is something wrong with my environment.
My fault.
