### ISSUE TITLE
tcp* error on kernel 5.10

### ISSUE THREAD

**Issue by kong62** [iovisor/bcc#3255]
```
# tcpconnect
In file included from /virtual/main.c:15:
In file included from /lib/modules/5.10.11-1.el7.elrepo.x86_64/build/include/net/sock.h:46:
In file included from /lib/modules/5.10.11-1.el7.elrepo.x86_64/build/include/linux/netdevice.h:38:
In file included from /lib/modules/5.10.11-1.el7.elrepo.x86_64/build/include/net/net_namespace.h:36:
In file included from /lib/modules/5.10.11-1.el7.elrepo.x86_64/build/include/net/netns/bpf.h:9:
/lib/modules/5.10.11-1.el7.elrepo.x86_64/build/include/linux/bpf-netns.h:21:7: error: use of undeclared identifier 'BPF_SK_LOOKUP'; did you mean 'BPF_F_LOCK'?
        case BPF_SK_LOOKUP:
             ^~~~~~~~~~~~~
             BPF_F_LOCK
/virtual/include/bcc/bpf.h:360:2: note: 'BPF_F_LOCK' declared here
        BPF_F_LOCK      = 4, /* spin_lock-ed map_lookup/map_update */
        ^
In file included from /virtual/main.c:15:
In file included from /lib/modules/5.10.11-1.el7.elrepo.x86_64/build/include/net/sock.h:46:
In file included from /lib/modules/5.10.11-1.el7.elrepo.x86_64/build/include/linux/netdevice.h:42:
In file included from /lib/modules/5.10.11-1.el7.elrepo.x86_64/build/include/net/netprio_cgroup.h:11:
In file included from /lib/modules/5.10.11-1.el7.elrepo.x86_64/build/include/linux/cgroup.h:28:
In file included from /lib/modules/5.10.11-1.el7.elrepo.x86_64/build/include/linux/cgroup-defs.h:22:
In file included from /lib/modules/5.10.11-1.el7.elrepo.x86_64/build/include/linux/bpf-cgroup.h:5:
/lib/modules/5.10.11-1.el7.elrepo.x86_64/build/include/linux/bpf.h:1289:12: warning: declaration of 'union bpf_iter_link_info' will not be visible outside of this function [-Wvisibility]
                                        union bpf_iter_link_info *linfo,
                                              ^
1 warning and 1 error generated.
Traceback (most recent call last):
  File "/usr/share/bcc/tools/tcpconnect", line 301, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 358, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>


# tcpdrop 
In file included from /virtual/main.c:5:
In file included from /lib/modules/5.10.11-1.el7.elrepo.x86_64/build/include/net/sock.h:46:
In file included from /lib/modules/5.10.11-1.el7.elrepo.x86_64/build/include/linux/netdevice.h:38:
In file included from /lib/modules/5.10.11-1.el7.elrepo.x86_64/build/include/net/net_namespace.h:36:
In file included from /lib/modules/5.10.11-1.el7.elrepo.x86_64/build/include/net/netns/bpf.h:9:
/lib/modules/5.10.11-1.el7.elrepo.x86_64/build/include/linux/bpf-netns.h:21:7: error: use of undeclared identifier 'BPF_SK_LOOKUP'; did you mean 'BPF_F_LOCK'?
        case BPF_SK_LOOKUP:
             ^~~~~~~~~~~~~
             BPF_F_LOCK
/virtual/include/bcc/bpf.h:360:2: note: 'BPF_F_LOCK' declared here
        BPF_F_LOCK      = 4, /* spin_lock-ed map_lookup/map_update */
        ^
In file included from /virtual/main.c:5:
In file included from /lib/modules/5.10.11-1.el7.elrepo.x86_64/build/include/net/sock.h:46:
In file included from /lib/modules/5.10.11-1.el7.elrepo.x86_64/build/include/linux/netdevice.h:42:
In file included from /lib/modules/5.10.11-1.el7.elrepo.x86_64/build/include/net/netprio_cgroup.h:11:
In file included from /lib/modules/5.10.11-1.el7.elrepo.x86_64/build/include/linux/cgroup.h:28:
In file included from /lib/modules/5.10.11-1.el7.elrepo.x86_64/build/include/linux/cgroup-defs.h:22:
In file included from /lib/modules/5.10.11-1.el7.elrepo.x86_64/build/include/linux/bpf-cgroup.h:5:
/lib/modules/5.10.11-1.el7.elrepo.x86_64/build/include/linux/bpf.h:1289:12: warning: declaration of 'union bpf_iter_link_info' will not be visible outside of this function [-Wvisibility]
                                        union bpf_iter_link_info *linfo,
                                              ^
1 warning and 1 error generated.
Traceback (most recent call last):
  File "/usr/share/bcc/tools/tcpdrop", line 179, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 358, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>
```

```
# uname -r
5.10.11-1.el7.elrepo.x86_64
```
```
# rpm -qa |grep kernel             
kernel-ml-devel-5.10.11-1.el7.elrepo.x86_64
kernel-ml-5.10.11-1.el7.elrepo.x86_64
kernel-ml-tools-libs-5.10.11-1.el7.elrepo.x86_64
kernel-ml-doc-5.10.11-1.el7.elrepo.noarch
kernel-ml-headers-5.10.11-1.el7.elrepo.x86_64
kernel-ml-tools-5.10.11-1.el7.elrepo.x86_64
kernel-ml-tools-libs-devel-5.10.11-1.el7.elrepo.x86_64
```
```
# cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)
```

```
# rpm -qa |grep bcc-tools
bcc-tools-0.15.0-2.el7.x86_64
```

**Comment by yonghong-song** [comment]
This is an issue with older bcc and newer kernel. bcc internal bpf.h does not define BPF_SK_LOOKUP but newer kernel header file uses BPF_SK_LOOKUP. In general, bcc should try to compile again with system bpf uapi headers. I did not see it in your above log.

Anyway, the workaround is to add the definition before including sock.h file.
```
--- a/tools/tcpconnect.py
+++ b/tools/tcpconnect.py
@@ -74,6 +74,7 @@ debug = 0
 # define BPF program
 bpf_text = """
 #include <uapi/linux/ptrace.h>
+#define BPF_SK_LOOKUP 36
 #include <net/sock.h>
 #include <bcc/proto.h>
```

Upgrading to newer bcc should also fix the issue.

**Comment by kong62** [comment]
thanks

**Comment by linecolumn** [comment]
@yonghong-song 

Something is still missing, added "#define BPF_SK_LOOKUP 36" to /usr/share/bcc/tools/tcpconnect:

$ /usr/share/bcc/tools/tcpconnect 
In file included from <built-in>:2:
In file included from /virtual/include/bcc/bpf.h:12:
In file included from /lib/modules/5.10.25-1/build/include/linux/types.h:6:
In file included from /lib/modules/5.10.25-1/build/include/uapi/linux/types.h:14:
In file included from /lib/modules/5.10.25-1/build/include/uapi/linux/posix_types.h:5:
In file included from /lib/modules/5.10.25-1/build/include/linux/stddef.h:5:
In file included from /lib/modules/5.10.25-1/build/include/uapi/linux/stddef.h:2:
In file included from /lib/modules/5.10.25-1/build/include/linux/compiler_types.h:69:
/lib/modules/5.10.25-1/build/include/linux/compiler-clang.h:45:9: warning: '__HAVE_BUILTIN_BSWAP32__' macro redefined [-Wmacro-redefined]
#define __HAVE_BUILTIN_BSWAP32__
        ^
<command line>:4:9: note: previous definition is here
#define __HAVE_BUILTIN_BSWAP32__ 1
        ^
In file included from <built-in>:2:
In file included from /virtual/include/bcc/bpf.h:12:
In file included from /lib/modules/5.10.25-1/build/include/linux/types.h:6:
In file included from /lib/modules/5.10.25-1/build/include/uapi/linux/types.h:14:
In file included from /lib/modules/5.10.25-1/build/include/uapi/linux/posix_types.h:5:
In file included from /lib/modules/5.10.25-1/build/include/linux/stddef.h:5:
In file included from /lib/modules/5.10.25-1/build/include/uapi/linux/stddef.h:2:
In file included from /lib/modules/5.10.25-1/build/include/linux/compiler_types.h:69:
/lib/modules/5.10.25-1/build/include/linux/compiler-clang.h:46:9: warning: '__HAVE_BUILTIN_BSWAP64__' macro redefined [-Wmacro-redefined]
#define __HAVE_BUILTIN_BSWAP64__
        ^
<command line>:5:9: note: previous definition is here
#define __HAVE_BUILTIN_BSWAP64__ 1
        ^
In file included from <built-in>:2:
In file included from /virtual/include/bcc/bpf.h:12:
In file included from /lib/modules/5.10.25-1/build/include/linux/types.h:6:
In file included from /lib/modules/5.10.25-1/build/include/uapi/linux/types.h:14:
In file included from /lib/modules/5.10.25-1/build/include/uapi/linux/posix_types.h:5:
In file included from /lib/modules/5.10.25-1/build/include/linux/stddef.h:5:
In file included from /lib/modules/5.10.25-1/build/include/uapi/linux/stddef.h:2:
In file included from /lib/modules/5.10.25-1/build/include/linux/compiler_types.h:69:
/lib/modules/5.10.25-1/build/include/linux/compiler-clang.h:47:9: warning: '__HAVE_BUILTIN_BSWAP16__' macro redefined [-Wmacro-redefined]
#define __HAVE_BUILTIN_BSWAP16__
        ^
<command line>:3:9: note: previous definition is here
#define __HAVE_BUILTIN_BSWAP16__ 1
        ^
In file included from /virtual/main.c:2:
In file included from /lib/modules/5.10.25-1/build/include/uapi/linux/ptrace.h:143:
In file included from /lib/modules/5.10.25-1/build/arch/x86/include/asm/ptrace.h:97:
/lib/modules/5.10.25-1/build/arch/x86/include/asm/proto.h:14:30: warning: declaration of 'struct task_struct' will not be visible outside of this function [-Wvisibility]
long do_arch_prctl_64(struct task_struct *task, int option, unsigned long arg2);
                             ^
/lib/modules/5.10.25-1/build/arch/x86/include/asm/proto.h:40:34: warning: declaration of 'struct task_struct' will not be visible outside of this function [-Wvisibility]
long do_arch_prctl_common(struct task_struct *task, int option,
                                 ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/5.10.25-1/build/include/net/sock.h:46:
In file included from /lib/modules/5.10.25-1/build/include/linux/netdevice.h:38:
In file included from /lib/modules/5.10.25-1/build/include/net/net_namespace.h:36:
In file included from /lib/modules/5.10.25-1/build/include/net/netns/bpf.h:9:
/lib/modules/5.10.25-1/build/include/linux/bpf-netns.h:21:7: warning: case value not in enumerated type 'enum bpf_attach_type' [-Wswitch]
        case BPF_SK_LOOKUP:
             ^
/virtual/main.c:3:23: note: expanded from macro 'BPF_SK_LOOKUP'
#define BPF_SK_LOOKUP 36
                      ^
In file included from /virtual/main.c:4:
In file included from /lib/modules/5.10.25-1/build/include/net/sock.h:46:
In file included from /lib/modules/5.10.25-1/build/include/linux/netdevice.h:42:
In file included from /lib/modules/5.10.25-1/build/include/net/netprio_cgroup.h:11:
In file included from /lib/modules/5.10.25-1/build/include/linux/cgroup.h:28:
In file included from /lib/modules/5.10.25-1/build/include/linux/cgroup-defs.h:22:
In file included from /lib/modules/5.10.25-1/build/include/linux/bpf-cgroup.h:5:
/lib/modules/5.10.25-1/build/include/linux/bpf.h:858:21: error: field has incomplete type 'enum bpf_link_type'
        enum bpf_link_type type;
                           ^
/lib/modules/5.10.25-1/build/include/linux/bpf.h:858:7: note: forward declaration of 'enum bpf_link_type'
        enum bpf_link_type type;
             ^
/lib/modules/5.10.25-1/build/include/linux/bpf.h:872:17: warning: declaration of 'struct bpf_link_info' will not be visible outside of this function [-Wvisibility]
                              struct bpf_link_info *info);
                                     ^
/lib/modules/5.10.25-1/build/include/linux/bpf.h:1289:12: warning: declaration of 'union bpf_iter_link_info' will not be visible outside of this function [-Wvisibility]
                                        union bpf_iter_link_info *linfo,
                                              ^
/lib/modules/5.10.25-1/build/include/linux/bpf.h:1295:14: warning: declaration of 'struct bpf_link_info' will not be visible outside of this function [-Wvisibility]
                                         struct bpf_link_info *info);
                                                ^
/lib/modules/5.10.25-1/build/include/linux/bpf.h:1333:12: warning: declaration of 'struct bpf_link_info' will not be visible outside of this function [-Wvisibility]
                                struct bpf_link_info *info);
                                       ^
10 warnings and 1 error generated.
Traceback (most recent call last):
  File "/usr/share/bcc/tools/tcpconnect", line 309, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python3.6/site-packages/bcc/__init__.py", line 357, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>

**Comment by yonghong-song** [comment]
by looking at this error
```
 /lib/modules/5.10.25-1/build/include/linux/bpf.h:858:21: error: field has incomplete type 'enum bpf_link_type'
```
That means you have an old version of bcc and newer version kernel. It would be good you can try to upgrade
your bcc to see whether it resolved your issue or not.

**Comment by linecolumn** [comment]
Tried with gcc-9.3 (compiled from source), and with RHET 9.2.1 rpms:

 ```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/rh/gcc-toolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/opt/rh/gcc-toolset-9/root/usr --mandir=/opt/rh/gcc-toolset-9/root/usr/share/man --infodir=/opt/rh/gcc-toolset-9/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl=/builddir/build/BUILD/gcc-9.2.1-20191120/obj-x86_64-redhat-linux/isl-install --disable-libmpx --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 9.2.1 20191120 (Red Hat 9.2.1-2) (GCC) 
```

Still same thingy:

```
/lib/modules/5.10.25-1/build/include/linux/bpf.h:858:21: error: field has incomplete type 'enum bpf_link_type'
        enum bpf_link_type type;
                           ^
```
