### ISSUE TITLE
Compiler error: 

### ISSUE THREAD

**Issue by majianpeng** [iovisor/bcc#3256]
When compile, i met the following error. This because  submodule: libbpf can't sync when i sync bcc.
I think we should sync submodule when do cmake whether src/cc/libbpf existed or no.

> /mnt/trace-tools/eBPF/bcc/src/cc/frontends/clang/b_frontend_action.cc: In member function bool ebpf::BTypeVisitor::VisitVarDecl(clang::VarDecl*):]
> /mnt/trace-tools/eBPF/bcc/src/cc/frontends/clang/b_frontend_action.cc:1449:18: error: BPF_MAP_TYPE_RINGBUF was not declared in this scope; did you mean BPF_MAP_TYPE_QUEUE?
> 1449 |       map_type = BPF_MAP_TYPE_RINGBUF;                                                                                                                                                                         |                  ^~~~~~~~~~~~~~~~~~~~                                                                                                                                                                          |                  BPF_MAP_TYPE_QUEUE
> make[2]: *** [src/cc/frontends/clang/CMakeFiles/clang_frontend.dir/build.make:95: src/cc/frontends/clang/CMakeFiles/clang_frontend.dir/b_frontend_action.cc.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:1065: src/cc/frontends/clang/CMakeFiles/clang_frontend.dir/all] Error 2
> make: *** [Makefile:160: all] Error 2

~

**Comment by yonghong-song** [comment]
Yes, this is because syncing is not properly done. it is tricky what to do if the libbpf directory is not empty. There may be user changes there. Maybe for common not-changed simply-outdated libbpf we can do this. Are you willing to help with a pull request?

**Comment by majianpeng** [comment]
For not-changed, this mean
