### ISSUE TITLE
get_stackid: unexpected trace

### ISSUE THREAD

**Issue by sixsax** [iovisor/bcc#3261]
# Description
get_stackid call print an unexpected output. Not all calls seems to be tracked on the stack.

# System
* bcc 0.17.0-297512a3
* Python 3.6.8
* kernel 5.10.2
* Centos 7

# Frontend Python code
```python
from bcc import BPF
from bcc.utils import printb
from time import sleep
import sys
import argparse

def getParser():
        parser = argparse.ArgumentParser( description="Uprobe a function name into binary", formatter_class=argparse.RawDescriptionHelpFormatter)
        parser.add_argument("-b", "--binary", nargs="?", const="", type=str,help="Specify the binary with full path.",required=True)
        parser.add_argument("-p", "--pid", nargs="?", const="", type=int, help="Specify PID.", required=True)

        return parser

parser = getParser();
args = parser.parse_args()

binary = args.binary
pid = args.pid
function = "trace"

b = BPF(src_file="uprobe_stack.c", debug=0 ) #0x10

try:
        b.attach_uprobe(name=binary, sym_re=".*" , fn_name=function, pid=pid)
except (Exception) as e:
        print("Exception")
        print(str(e))
        parser.print_help()
        exit(0)

stack_traces = b.get_table("stack_traces")

def callback(ctx, data, size):
        event = b['events'].event(data)
        for stack in stack_traces.walk(event.stack_id):
                printb(b"\t%s" % b.sym(stack, pid, show_module=True, show_offset=True))
        print("Printing stack calls, ctrl-c to exit.")

b['events'].open_perf_buffer(callback)

try:
        while 1:
                b.perf_buffer_poll()
except KeyboardInterrupt:
        sys.exit()

```

# Backend C code
```c
#include <linux/ptrace.h>

struct data_t {
        u64 stack_id;
};

BPF_PERF_OUTPUT(events);
BPF_STACK_TRACE(stack_traces, 1024);

int trace(struct pt_regs *ctx) {

        struct data_t data = {};
        int key = stack_traces.get_stackid(ctx, BPF_F_USER_STACK);

        data.stack_id = key;
        events.perf_submit(ctx, &data, sizeof(data));

        return 0;
};
```

# Test C code
```c
#include <stdio.h>
#include <time.h>

void final(){
        printf("final\n");
}

void middle(){
        printf("middle\n");
        final();
}

void start(){
        printf("start\n");
        middle();
}

int main (int argc, char *argv[]){

        sleep(10);
        printf("main\n");
        start();
        sleep(10);
        return 0;
}
```

# Run description
The test code output is following 

```
main
start
middle
final
```
and stack trace output is
```
        start+0x0 [uprobe_stack_c-test]
        __libc_start_main+0xf5 [libc-2.17.so]
Printing stack calls, ctrl-c to exit.
        middle+0x0 [uprobe_stack_c-test]
        main+0x32 [uprobe_stack_c-test]
        __libc_start_main+0xf5 [libc-2.17.so]
Printing stack calls, ctrl-c to exit.
        final+0x0 [uprobe_stack_c-test]
        start+0x18 [uprobe_stack_c-test]
        main+0x32 [uprobe_stack_c-test]
        __libc_start_main+0xf5 [libc-2.17.so]
```

but I would have expected the following one
```
        start+0x0 [uprobe_stack_c-test]
>>>     main
        __libc_start_main+0xf5 [libc-2.17.so]
Printing stack calls, ctrl-c to exit.
        middle+0x0 [uprobe_stack_c-test]
>>>     start
        main+0x32 [uprobe_stack_c-test]
        __libc_start_main+0xf5 [libc-2.17.so]
Printing stack calls, ctrl-c to exit.
        final+0x0 [uprobe_stack_c-test]
>>>     middle
        start+0x18 [uprobe_stack_c-test]
        main+0x32 [uprobe_stack_c-test]
        __libc_start_main+0xf5 [libc-2.17.so]
```

Is there something wrong on my test?

**Comment by sixsax** [comment]
The BPF_STACK_TRACE map is filled by bpf_get_stackid kernel function with following chain:

trace struct
```
struct perf_callchain_entry {
	__u64				nr;
	__u64				ip[]; /* /proc/sys/kernel/perf_event_max_stack */
};
```

```
bpf_get_stackid regs->ip: 0x400587 <start>
	get_perf_callchain
		perf_callchain_user
			ip0: 0x400587 <start>
			
bpf_get_stackid	regs->ip: 0x40056d <middle>:
	get_perf_callchain
		perf_callchain_user
			ip0: 0x40056d <middle>
			ip1: 0x4005d3 <main> = 0x4005a1 + 0x32
			
bpf_get_stackid regs->ip: 0x40055d <final>:
    get_perf_callchain
		perf_callchain_user
		ip0: 0x40055d <final>
		ip1: 0x40059f <start> = 0x400587 + 0x18
		ip2: 0x4005d3 <main> = 0x4005a1 + 0x32
```
I don't know if the trace result is correct but, for sure, it is the same as which one produced kernel side. 
I close the issue.

**Comment by GregHWayne** [comment]
Same problem, when using uprobe and uretprobe, expected stack should be (main->start->middle->final), 
but I got (main->start->final) during uprobe, and  (main->start->middle) during uretprobe.
Don't why one stack is missing.

**Comment by GregHWayne** [comment]
@sixsax Have you got any solutions till now？

**Comment by chenhengqi** [comment]
FYI, please refer to https://github.com/iovisor/bcc/blob/master/tools/offcputime.py#L361 .

**Comment by yonghong-song** [comment]
This might be related to how kernel unwind user stacks.
@GregHWayne How did you compile your programs? To get better stack trace, you should preserve frame pointers.
Also the above synthetic examples have "middle" and "final" functions as tail calls. Compiling the program with optimization level will trigger tail call optimization and some call frame will be gone and this will reflect with
"missing" stacks.

**Comment by sixsax** [comment]
@GregHWayne no, I haven't.
As noted by @yonghong-song we could try passing the following flag to gcc: "-fno-optimize-sibling-calls"

**Comment by GregHWayne** [comment]
> This might be related to how kernel unwind user stacks. @GregHWayne How did you compile your programs? To get better stack trace, you should preserve frame pointers. Also the above synthetic examples have "middle" and "final" functions as tail calls. Compiling the program with optimization level will trigger tail call optimization and some call frame will be gone and this will reflect with "missing" stacks.
@yonghong-song , thanks on your reply.
#test case is extremely simple:
```
#include<stdio.h>
#include<stdlib.h>
int test_final() {
    int a = 32;
    int b = 45;
    int c = a * b + a * b;
    printf("final\n");
    return c;
}
int test_middle() {
    int a = 32;
    int b = 45;
    printf("middle\n");
    int c = test_final();
    c += a * b + a * b;
    return c;
}
int test_start() {
    int a = 32;
    int b = 45;
    printf("start\n");
    int c = test_middle();
    c += a * b + a * b;
    return c;
}
int main(int argc, char** argv) {
    getchar();
    for(int i = 0; i < 1; ++i) {
       test_start();
    }
    return 0;
}
```
#compile options:
`gcc -o hello-bpf -O0 -g  main.cpp -fno-omit-frame-pointer`
"-O0" option is used here, meanwhile, test functions here should not relate to tail call, "-fno-omit-frame-pointer" enables frame-pointers.
#bpftrace acts the same as bpf:
`sudo bpftrace -e 'uprobe:$your_path/hello-bpf:_Z10test_finalv { printf("%s\n", ustack); }'`
`sudo bpftrace -e 'uretprobe:$your_path/hello-bpf:_Z10test_finalv { printf("%s\n", ustack); }'`
#result
```
Attaching 1 probe...

        test_final()+0  // test_middle stack is missing
        test_start()+37
        main+44
        __libc_start_main+245

Attaching 1 probe...

        test_middle()+37 // test_final stack is missing
        test_start()+37
        main+38
        __libc_start_main+245

```

**Comment by GregHWayne** [comment]
> -fno-optimize-sibling-calls



> @GregHWayne no, I haven't. As noted by @yonghong-song we could try passing the following flag to gcc: "-fno-optimize-sibling-calls"

@sixsax , the same result
`gcc -o hello-bpf -O0 -g  main.cpp -fno-omit-frame-pointer -fno-optimize-sibling-calls`

**Comment by GregHWayne** [comment]
> FYI, please refer to https://github.com/iovisor/bcc/blob/master/tools/offcputime.py#L361 .

It seems not a "--stack-storage-size" problem, stackid could be obtained in bpf programs and could be used in traces.walk(stackid)

**Comment by chenhengqi** [comment]
> > FYI, please refer to https://github.com/iovisor/bcc/blob/master/tools/offcputime.py#L361 .
> 
> It seems not a "--stack-storage-size" problem, stackid could be obtained in bpf programs and could be used in traces.walk(stackid)

Hmm, my bad.

**Comment by chenhengqi** [comment]
I got something like this with BCC:

```
get stack:
        [unknown]
        [unknown]
get stack:
        [unknown]
        [unknown]
        [unknown]
get stack:
        [unknown]
        [unknown]
        [unknown]
        [unknown]
get stack:
        [unknown]
        [unknown]
get stack:
        [unknown]
        [unknown]
        [unknown]
get stack:
        [unknown]
        [unknown]
```

With bpftrace:
```
sudo ./bpftrace -e 'uprobe:/home/ubuntu/bpf/github/bcc/tools/testbin:_Z10test_finalv { printf("%s\n", ustack); }'
Attaching 1 probe...

        0x55cf11744169
        0x55cf1174420a
        0x55cf11744248
        0x7f3b63f6e565
```

The tested program is compiled with:
```shell
$ gcc -O0 -g -Wall -fno-omit-frame-pointer -fno-optimize-sibling-calls -o testbin test.cpp
```

**Comment by GregHWayne** [comment]
@chenhengqi when using bpftrace, testbin should be running, like:
$./testbin #(keep running or just getchar())
$sudo bpftrace -e 'uprobe:/home/ubuntu/bpf/github/bcc/tools/testbin:_Z10test_finalv { printf("%s\n", ustack); }'
if bpftrace ran firstly, then testbin ran, bpftrace only got symbol address as your example.

**Comment by GregHWayne** [comment]
Found something interesting, I tried USDT in bpf, it turned out that DTRACE_PROBE could get full stack trace.
Maybe the root problem is uprobe, not bpf_get_stackid in linux kernel.

**Comment by chenhengqi** [comment]
> @chenhengqi when using bpftrace, testbin should be running, like: $./testbin #(keep running or just getchar()) $sudo bpftrace -e 'uprobe:/home/ubuntu/bpf/github/bcc/tools/testbin:_Z10test_finalv { printf("%s\n", ustack); }' if bpftrace ran firstly, then testbin ran, bpftrace only got symbol address as your example.

Actually, I ran `testbin` first.
