### ISSUE TITLE
Tcptop support remote port similar to tcplife

### ISSUE THREAD

**Issue by nvsnvikram** [iovisor/bcc#3292]
I want to filter out the top connections from a particular pid to a specific remote port. Would it be possible to enhance tcptop to support this feature?

**Comment by yonghong-song** [comment]
Current tcptop can already filter based on pid. Are you suggesting to further filter with a specific remote port? it is certainly doable. You can add a filter in the bpf program to only record if the remote port (dport) is what you are interested in.
Could you describe the reason why you want this feature?

**Comment by nvsnvikram** [comment]
According to our stats, we are seeing connections from particular process to a remote end point go down to 0 periodically. I wanted to validate the same using tcplife but it was reporting only connections that open & close. I wanted to see what tcptop reports for the same process and remote port.

**Comment by yonghong-song** [comment]
tcptop output likes:
```
1942017 scribe_cat   ::1:56494                        ::1:2378                              0      0
3403323 configerator ::1:2378                         ::1:65472                             0      0
1942020 scribe_cat   ::1:56500                        ::1:2378                              0      0
```
It has pid, process_name, load ip:port remote_ip:port, send/recv bytes.
Could you try whether you can write a script to parse the output and get the result? This way we do not need to change the tool.

**Comment by nvsnvikram** [comment]
thanks. I have been able to use script over to get the data I need.
