### ISSUE TITLE
'finish_task_switch' is optimized away by GCC 10.2, attach_kprobe failed

### ISSUE THREAD

**Issue by docularxu** [iovisor/bcc#3293]
Since 'finish_task_switch' is such a common tracing point where many bcc tools use, such as in: 
`tools/offcputime.py:b.attach_kprobe(event="finish_task_switch", fn_name="oncpu")`
`libbpf-tools/cpudist.bpf.c:int BPF_KPROBE(finish_task_switch, struct task_struct *prev)
`
 I think it's useful to report this issue here.

I am using GCC 10 and GCC 9 from debian sid stable.
`echo 'deb http://ftp.debian.org/debian sid main' >> /etc/apt/sources.list
`
 Their version details are respectively:
`# gcc --version`
`gcc (Debian 10.2.1-6) 10.2.1 20210110`

`# gcc --version`
`gcc (Debian 9.3.0-22) 9.3.0
`
My environment is an Arm64 machine. And I'm doing a native arm64 build with GCC. The kernel build commands I am using is this, in both gcc 9 and gcc 10 cases:
`  cd linux.git`
`   git checkout -b working-5.11 v5.11`
`   ARCH=arm64 make mrproper O=../linux.buildout`
`   ARCH=arm64 make defconfig O=../linux.buildout`
`   ARCH=arm64 make Image -j 96 O=../linux.buildout`

The results, when built with gcc 9.3: 
`nm ../linux.buildout/kernel/sched/core.o | grep finish_task_switch`
`0000000000001288 t finish_task_switch`

However, when built with gcc 10.2:
`nm ../linux.buildout/kernel/sched/core.o | grep finish_task_switch`
`00000000000012d0 t finish_task_switch.isra.0`

The same symbols (with xxx.isra.0 or without, respectively of course) also appear in 'System.map' and in '/proc/kallsyms' when booting. So, here you can see the problem if I use the kernel built by gcc 10:

bcc tools such as 'offcputime' will report: Failed to attach BPF program ... kprobe finish_task_switch. 
But what really exists in gcc 10 built kernel is "finish_task_switch.isra.0"

**Comment by docularxu** [comment]
In the source level, ( linux.git/kernel/sched/core.c), neither adding `noinline`, nor adding ` asm{""}` can change the behavior of GCC 10 built result.
`static struct rq *finish_task_switch(struct task_struct *prev)
`

The only way to make GCC 10 generate a __clean__ 'finish_task_switch' is deleting the `static`. Sadly.

**Comment by docularxu** [comment]
The suffix "isra.0" may relate to this improvements in GCC 10.

Refer to [1], which states:
"Inter-procedural optimization improvements: The inter-procedural scalar replacement of aggregates (IPA-SRA) pass was re-implemented to work at link-time and can now also remove computing and returning unused return values."

However, such a change of symbol names negatively impacts the tracing tools commonly used in kernel debugging. Such as bcc/eBPF, who __hardcoded__ function names (without the .isra.0 suffix) into their scripts.

[1] https://gcc.gnu.org/gcc-10/changes.html

**Comment by yonghong-song** [comment]
@docularxu Thanks for reporting. Yes, the isra issue is known for quite some time. I think this is what happens with gcc10.
First, for `finish_task_switch` called below,
```
asmlinkage __visible void schedule_tail(struct task_struct *prev)
        __releases(rq->lock)
{       
        struct rq *rq;

        /*
         * New tasks start with FORK_PREEMPT_COUNT, see there and
         * finish_task_switch() for details.
         *
         * finish_task_switch() will drop rq->lock() and lower preempt_count
         * and the preempt_enable() will end up enabling preemption (on
         * PREEMPT_COUNT kernels).
         */
        
        rq = finish_task_switch(prev);
        preempt_enable();
                
        if (current->set_child_tid)
                put_user(task_pid_vnr(current), current->set_child_tid);
        
        calculate_sigpending();
}
```
Notice that the return value is not used, the compiler created another funciton `finish_task_switch.isra.0` by recursively removing any legit code which assigns a return value. That isra.0 function will be used in the above.
The same for the other call side `finish_task_switch` return value is not used.

In the long time, the best is to use trace point. But we have to do analysis to see whether it can solve the same problems as the current tool or not.

In the short term, could you amend the tool such that in case of attach_kprobe failed, searching some `finish_task_switch.isra.*`. I think this can be implement in the common attach_kprobe function with an additional parameter to indicate this behavior is allowed. The default should be not allowed as the *.isra.* functions may change input parameters and it would be good to do this only with the confirmation of the caller.

Could you help with a pull request for this? Thanks!

**Comment by docularxu** [comment]
Hi, @yonghong-song 

sorry for late reply. I spent some time reading the code. As I checked the `attach_kprobe` input parameters, I found this: `event_re`

Why do we re-use `event_re` for a pattern such as:

```
diff --git a/tools/offcputime.py b/tools/offcputime.py
index 7ba5dc51..ba47a47a 100755
--- a/tools/offcputime.py
+++ b/tools/offcputime.py
@@ -251,7 +251,9 @@ if debug or args.ebpf:
 
 # initialize BPF
 b = BPF(text=bpf_text)
-b.attach_kprobe(event="finish_task_switch", fn_name="oncpu")
+b.attach_kprobe(event_re="^finish_task_switch$|^finish_task_switch\.isra\.\d$",
+                fn_name="oncpu")
+# b.attach_kprobe(event="finish_task_switch", fn_name="oncpu")
 matched = b.num_open_kprobes()
 if matched == 0:
     print("error: 0 functions traced. Exiting.", file=stderr)
```

What do you think?

**Comment by yonghong-song** [comment]
@docularxu Oh, yes, event_re should be good enough in this case, I forgot it. Thanks for discovering this better/easier alternative!

**Comment by docularxu** [comment]
Submitted 
https://github.com/iovisor/bcc/pull/3315

**Comment by docularxu** [comment]
Merged.
