### ISSUE TITLE
License mismatch

### ISSUE THREAD

**Issue by jackhumphries** [iovisor/bcc#3312]
Hello,

The following files have an SPDX license identifier that specifies they use both the "LGPL-2.1" and "BSD-2-Clause" licenses.

libbpf-tools/trace_helpers.c
libbpf-tools/trace_helpers.h
libbpf-tools/bits.bpf.h

However, the LICENSE.txt file at the root of the project is for Apache 2.

Could you please clarify which license(s) those three files are under?

Thanks.

**Comment by anakryiko** [comment]
Everything under libbpf-tools is LGPL-2.1 OR BSD-2-Clause, just like SPDX headers say. I'll update LICENSE.txt to mention that most of BCC code is under Apache, but libbpf-tools uses what is specified by SPDX headers.
