### ISSUE TITLE
libbpf: kprobe perf_event_open() failed: No such file or directory

### ISSUE THREAD

**Issue by chenhengqi** [iovisor/bcc#3327]
I compile and run the `xfsslower`, it complains:

```
libbpf: kprobe perf_event_open() failed: No such file or directory
libbpf: prog 'xfs_file_read_iter': failed to create kprobe 'xfs_file_read_iter' perf event: No such file or directory
libbpf: failed to auto-attach program 'xfs_file_read_iter': -2
failed to attach BPF programs
```

According to the man page of `perf_event_open`, I've checked the existence of `/proc/sys/kernel/perf_event_paranoid` and set its value to `1` and `-1`, both NOT working.

Can anyone help with this?

**Comment by chenhengqi** [comment]
ping @ethercflow

**Comment by ethercflow** [comment]
Hi, @chenhengqi  has xfs been loaded?  `lsmod | grep xfs`?

**Comment by chenhengqi** [comment]
@ethercflow  I've load the xfs module and it works now. Thanks
