### ISSUE TITLE
Measure the CPU usage of a eBPF program over time

### ISSUE THREAD

**Issue by ShixiongQi** [iovisor/bcc#3330]
Hi guys,

Is there anyway to measure the CPU usage of a eBPF program? Or maybe counting the CPU cycles consumed by a specific eBPF program over time?

**Comment by MartinAres** [comment]
@ShixiongQi Hi, do you find a solution later?

**Comment by yonghong-song** [comment]
There are two ways to count bpf program cpu cycles (in terms of ns).
First is to use sysctl, /proc/sys/kernel/bpf_stats_enabled, which is global.

The second is to use a programmable interface. See https://lore.kernel.org/bpf/20200430071506.1408910-2-songliubraving@fb.com/

**Comment by MartinAres** [comment]
@yonghong-song Got it. Thank you for your reply!
