### ISSUE TITLE
run memleak in ubuntu20.04 error Failed to compile BPF module <text> 

### ISSUE THREAD

**Issue by bigpigeon** [iovisor/bcc#3348]
hey: 

I want to debug memory leak in ubuntu 20.04 ,but when I run /usr/share/bcc/tool/memleak , throw below error , can anyone  solve this problem, thanks 

```
In file included from /virtual/main.c:2:
In file included from include/uapi/linux/ptrace.h:143:
In file included from ./arch/x86/include/asm/ptrace.h:5:
./arch/x86/include/asm/segment.h:266:2: error: expected '(' after 'asm'
        alternative_io ("lsl %[seg],%[p]",
        ^
./arch/x86/include/asm/alternative.h:240:2: note: expanded from macro 'alternative_io'
        asm_inline volatile (ALTERNATIVE(oldinstr, newinstr, feature)   \
        ^
include/linux/compiler_types.h:239:24: note: expanded from macro 'asm_inline'
#define asm_inline asm __inline
                       ^
1 error generated.
Traceback (most recent call last):
  File "./memleak", line 411, in <module>
    bpf = BPF(text=bpf_source)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 343, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>
```

my kernel version:

    5.8.0-48-generic

my ubuntu version:

    Distributor ID:	Ubuntu
    Description:	Ubuntu 20.04.2 LTS
    Release:	20.04
    Codename:	focal

I  install with **Upstream Nightly Packages** 

    echo "deb [trusted=yes] https://repo.iovisor.org/apt/xenial xenial-nightly main" | sudo tee /etc/apt/sources.list.d/iovisor.list
    sudo apt-get update
    sudo apt-get install bcc-tools libbcc-examples linux-headers-$(uname -r)

**Comment by yonghong-song** [comment]
Could you try to build from source? This is related to macro `asm_inline` which should have been fixed sometime back.

**Comment by hadret** [comment]
It looks to me that you are using wrong distribution for the nightly builds repo -- xenial was 16.04 whereas you are running focal which is 20.04. Can you show which version of `bcc-tools` you've got installed (ex. `apt-cache policy bcc-tools`)?

**Comment by bigpigeon** [comment]
```

**Comment by bigpigeon** [comment]
my bcc-tools version

```
apt-cache policy bcc-tools
bcc-tools:
  Installed: 0.10.0-34.git.6836168
  Candidate: 0.10.0-34.git.6836168
  Version table:
 *** 0.10.0-34.git.6836168 500
        500 https://repo.iovisor.org/apt/xenial xenial-nightly/main amd64 Packages
        500 https://repo.iovisor.org/apt/xenial xenial-nightly/main i386 Packages
        100 /var/lib/dpkg/status
```

**Comment by hadret** [comment]
Right, so the current release is 0.19 -- you are quite behind. As @yonghong-song said, install newer version and it should fix your problem.

**Comment by bigpigeon** [comment]
yes, as @yonghong-song  said, I build bcc with source code was fix it
