### ISSUE TITLE
pass non-stripped binary for BPF.get_user_functions_and_addresses

### ISSUE THREAD

**Issue by jschwinger23** [iovisor/bcc#3353]
Taking funccount, the command to trace a uprobe is `funccount 'p:[bin]:[pattern]'`, and funccount fetches address using the given `[bin]`. Please reference the following snippets:

https://github.com/iovisor/bcc/blob/7fd8cad30f910af0470e00130817442091376ab3/tools/funccount.py#L126-L135

https://github.com/iovisor/bcc/blob/7fd8cad30f910af0470e00130817442091376ab3/tools/funccount.py#L72-L79

However it has become clear that the real world requires a tougher condition on which the tracee binaries are stripped out of symbols (usually with `-ldflags '-s'`), rendering most bcc tools not suitable for production environments.

On the other hand, this can be improved naturally as long as we figure out a way to passing an additional "non-stripped binary" merely serving as symbols provider for `BPF.get_user_functions_and_addresses`, for example, counting on environments, `SYMBOL_LIB=/path/to/non-stripped funccount 'p:/path/to/stripped:pattern'`

I believe this enhancement is valuable  for production environment debugging.

**Comment by yonghong-song** [comment]
Since you have a real use case for this, could you propose a patch for this? bcc indeed tries to find various debug files, see function foreach_sym_core() and find_debug_file().

**Comment by jschwinger23** [comment]
> Since you have a real use case for this, could you propose a patch for this? bcc indeed tries to find various debug files, see function foreach_sym_core() and find_debug_file().

sure, pleasant to contribute, thanks for reply.

**Comment by jschwinger23** [comment]
Got it! I can use env `BCC_SYMFS` to tell bcc where to find the debug files, and that works very well!
