### ISSUE TITLE
kprobe/uprobe aliases for function arguments

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#336]
Aliases for accessing arguments (eg, arg0, arg1, ...) instead of doing so via registers, so that scripts aren't tied to a particular processor architecture. This is complementary to #225.

References: https://en.wikipedia.org/wiki/X86_calling_conventions#System_V_AMD64_ABI and http://x86-64.org/documentation/abi.pdf

So for x86_64 this may just be: RDI, RSI, RDX, RCX, R8, R9, XMM0–7, unless the compiler messes with them (is that possible?).

**Comment by brendangregg** [comment]
This looks fixed by #529, as we can now use PT_REGS_PARM1..N (from src/cc/export/helpers.h).

**Comment by 4ast** [comment]
PT_REGS_PARM1 actually didn't work when I tried it few days ago. Didn't have time to debug
