### ISSUE TITLE
kfunc arguments are wrong/incomplete

### ISSUE THREAD

**Issue by Jolly5** [iovisor/bcc#3388]
I am trying to record connect() system calls using kretfuncs, but for some reason using those results in the target address and port always being 0. Those seem to be mostly fine when using a kprobe instead, though. (This, however, is not a satisfying workaround, since that causes me to lose information about the return value).

My kernel version is *5.11.16-200.fc33.x86_64*.

Here's a minimum reproducible example:

```
from bcc import BPF

def connect_event(cpu, data, size):
    global b
    ev = b["connect_events"].event(data)
    print("%-20d %-10d %-10d %-10d %-8d %x" % (
    ev.ts, ev.pid, ev.tgid, ev.fd, ev.port, ev.addr))

prog = """
#include <linux/sched.h>
#include <linux/socket.h>
#include <linux/in.h>

struct connect_event {
    u64 ts;
    u32 pid;
    u32 tgid;
    u16 port;
    u64 addr;
    int fd;
};
BPF_PERF_OUTPUT(connect_events);

typedef u32 socklen_t;

static void connect_event(unsigned long long *ctx, int sockfd, struct sockaddr_in *addr, socklen_t addrlen) {
    struct connect_event event = {};
    event.ts = bpf_ktime_get_ns();
    u64 both = bpf_get_current_pid_tgid();
    event.pid = both;
    event.tgid = both >> 32;
    event.fd = sockfd;
    event.port = addr->sin_port;
    event.addr = (addr->sin_addr).s_addr;
    
    connect_events.perf_submit(ctx, &event, sizeof(event));
}

KFUNC_PROBE(__sys_connect, int sockfd, struct sockaddr *addr, socklen_t addrlen) {
	connect_event(ctx, sockfd, (struct sockaddr_in *) addr, addrlen);
	return 0;
}
int kprobe____sys_connect(struct pt_regs *ctx, int sockfd, struct sockaddr *addr, socklen_t addrlen) {
	// connect_event((unsigned long long *) ctx, sockfd, (struct sockaddr_in *) addr, addrlen);
	return 0;
}
"""

b = BPF(text=prog)
b["connect_events"].open_perf_buffer(connect_event)

print("%-20s %-10s %-10s %-8s %-10s %s" % ("TIMESTAMP", "PID", "TGID", "SOCKFD", "PORT",  "ADDRESS"))

try:
    while True:
        b.perf_buffer_poll(100)
except KeyboardInterrupt:
    print("Program stopped due to keyboard interrupt.")
```
When running it, all port numbers and addresses turn out to be 0 for me. If I comment out the function call in the 
kfunc and comment in the call from the kprobe, this is no longer the case. A kretfunc behaves in the exact same way as the kfunc in this regard.

I am unsure if this is a bug - if it's not, how can I circumvent this problem?

**Comment by chenhengqi** [comment]
Two possible solutions:
* use both kprobe and kretprobe in your program, see [tcplife](https://github.com/iovisor/bcc/blob/master/tools/tcpconnect.py) in this repo.
* use a tracepoint if it exists.

**Comment by yonghong-song** [comment]
For your KFUNC_PROBE case, does all other fields in `event` data structure have expected results?

**Comment by Jolly5** [comment]
> For your KFUNC_PROBE case, does all other fields in `event` data structure have expected results?

Yes, they do.

It does not seem to be a problem with transmitting the data to the python frontend, because if I did something like this
`event.port = (addr->sin_port) + 1;`
I ended up with all '1's as port number.

**Comment by Jolly5** [comment]
The cause of the problem might not actually be visible to you with what I've provided already.
I modified the example from my original post to have a kprobe, kfunc and kretfunc active at the same time and have the console output specify which of the probes the information came from.

Interestingly, all three of them now produce matching results (with mostly non-zero ports and addresses).

However, when I modified my original, more complex program in the same way, only the kfunc and kprobe produced matching results, the kretfunc still only provided zeroes as addresses and port numbers.

I will keep investigating the issue.

**Comment by Jolly5** [comment]
Okay, the program is just mocking me at this point.

This is my modified example program. If I comment in the connect_event-call in the kprobe, everything works fine, even though the method is exited immediately by the kprobe! If I omit this call however, the ports and addresses keep being all zeroes.

```
from bcc import BPF

# define BPF program
import event

def connect_event(cpu, data, size):
    global b
    ev = b["connect_events"].event(data)
    print("%-10s %-20d %-10d %-10d %-10d %-8d %-15x %x" % (
    "KPROBE" if ev.source == 0 else "KFUNC" if ev.source == 1 else "KRETFUNC", ev.ts, ev.pid, ev.tgid, ev.fd, ev.port, ev.addr, ev.addraddr))

prog = """
#include <linux/sched.h>
#include <linux/socket.h>
#include <linux/in.h>

struct connect_event {
    u64 ts;
    u32 pid;
    u32 tgid;
    u16 port;
    u64 addr;
    int fd;
    int source;
    u64 addraddr;
};
BPF_PERF_OUTPUT(connect_events);

typedef u32 socklen_t;

static inline void connect_event(struct pt_regs *ctx, int sockfd, struct sockaddr_in *addr, socklen_t addrlen, int source) {
    if (!source) // If method was entered from kprobe, exit immediately
        return;
    
    struct connect_event event = {};
    event.ts = bpf_ktime_get_ns();
    u64 both = bpf_get_current_pid_tgid();
    event.pid = both;
    event.tgid = both >> 32;
    event.fd = sockfd;
    event.port = addr->sin_port;
    event.addr = (addr->sin_addr).s_addr;
    event.addraddr = (u64) addr;
    event.source = source;
    
    connect_events.perf_submit(ctx, &event, sizeof(event));
}

KFUNC_PROBE(__sys_connect, int sockfd, struct sockaddr *addr, socklen_t addrlen, int ret) {
	connect_event((struct pt_regs *) ctx, sockfd, (struct sockaddr_in *) addr, addrlen, 1);
	
	return 0;
}
KRETFUNC_PROBE(__sys_connect, int sockfd, struct sockaddr *addr, socklen_t addrlen, int ret) {
	connect_event((struct pt_regs *) ctx, sockfd, (struct sockaddr_in *) addr, addrlen, 2);
	
	return 0;
}
int kprobe____sys_connect(struct pt_regs *ctx, int sockfd, struct sockaddr *addr, socklen_t addrlen) {
        // If the following call is commented in, everything works fine
	// connect_event(ctx, sockfd, (struct sockaddr_in *) addr, addrlen, 0);
	
	return 0;
}
"""

b = BPF(text=prog)
b["connect_events"].open_perf_buffer(connect_event)

print("%-10s %-20s %-10s %-10s %-8s %-10s %-15s %s" % ("TYPE", "TIMESTAMP", "PID", "TGID", "SOCKFD", "PORT",  "ADDRESS", "ADDRLOC"))

try:
    while True:
        b.perf_buffer_poll(100)
except KeyboardInterrupt:
    print("Program stopped due to keyboard interrupt.")
```

I have no idea what's happening here. What could this single method call that exits immediately affect? I can think of two things:
- The if-statement is tipping off the branch predictor and my CPU's branch predictor has a bug which causes this to create a side effect. This, however, seems extremely unlikely to me.
- The method call from the kprobe causes the compiler to create significantly different code. (Compiler bug?)

Of course I might be missing something else here. Feel free to correct me...

**Comment by yonghong-song** [comment]
Thanks for reporting. I found the root cause.
First, the __sys_connect() function signature looks like this in the kernel:
```
int __sys_connect(int fd, struct sockaddr __user *uservaddr, int addrlen)
```
Note that the second parameter is tagged with __user, which means
`uservaddr` points to user memory. In your code, we have
```
    event.port = addr->sin_port;
    event.addr = (addr->sin_addr).s_addr;
```
which tries to access user memory.

If you uncomment the function call in kprobe program like
```
int kprobe____sys_connect(struct pt_regs *ctx, int sockfd, struct sockaddr *addr, socklen_t addrlen) {
        // If the following call is commented in, everything works fine
	connect_event(ctx, sockfd, (struct sockaddr_in *) addr, addrlen, 0);
	
	return 0;
}
```
The rewriter knows connect_event called in kprobe function and will rewrite, `event.port = ..., event.addr = ...` with bpf_probe_read() which still works on x86_64 even for user addresses.

If you commented out the function call in kprobe program, the rewriter won't touch `event.port = ...` and since this should work with kfunc. 

You can enable `debug=8` to see the difference of source code and generated asm code.

Unfortunately, the tracing style `addr->sin_port` only works for *kernel* addresses, so in this case, you will get 0 for a user address. The same for `(addr->sin_addr).s_addr`.

You can fix the code with explicitly using `bpf_probe_read_user` like below:
```
diff --git a/test.py b/test.py
index f58e52b..debe76d 100644
--- a/test.py
+++ b/test.py
@@ -35,8 +35,12 @@ static inline void connect_event(struct pt_regs *ctx, int sockfd, struct sockadd
     event.pid = both;
     event.tgid = both >> 32;
     event.fd = sockfd;
-    event.port = addr->sin_port;
-    event.addr = (addr->sin_addr).s_addr;
+    // event.port = addr->sin_port;
+    // event.addr = (addr->sin_addr).s_addr;
+    bpf_probe_read_user(&event.port, sizeof(event.port), &addr->sin_port);
+    __be32 s_addr = 0;
+    bpf_probe_read_user(&s_addr, sizeof(s_addr), &(addr->sin_addr).s_addr);
+    event.addr = s_addr;
     event.addraddr = (u64) addr;
     event.source = source;
     
@@ -61,7 +65,7 @@ int kprobe____sys_connect(struct pt_regs *ctx, int sockfd, struct sockaddr *addr
 }
 ```

To avoid such instances, we need to bring __user attribute to BTF so we can detect such cases and flag an warning/error for this. I am actually working on this. Thanks!

**Comment by Jolly5** [comment]
A big thanks! I definitely wouldn't have figured this out by myself...

Your explanation makes perfect sense and the proposed solution works as expected. :)
