### ISSUE TITLE
Misuse of bpf_get_current_pid_tgid or PID should be TID ?

### ISSUE THREAD

**Issue by chenhengqi** [iovisor/bcc#3407]
I found some tools use `u32 pid = bpf_get_current_pid_tgid` in their BPF program and expose a `PID` option, is this a misuse of bpf_get_current_pid_tgid or we should change `PID` to `TID` ?

- [x] btrfsdist.py
- [ ] bashreadline.py
- [ ] cachetop.py
- [ ] dcsnoop.py
- [x] ext4dist.py
- [x] gethostlatency.py
- [ ] killsnoop.py
- [ ] llcstat.py
- [ ] mdflush.py
- [ ] mysqld_qslower.py
- [x] nfsdist.py
- [x] solisten.py
- [x] sslsniff.py
- [x] statsnoop.py
- [x] tcpdrop.py
- [ ] wakeuptime.py
- [x] xfsdist.py
- [x] zfsdist.py

I don't know it's intended or I misunderstand this due to my ignorance. :)
Can anyone clarify this ?

**Comment by brendangregg** [comment]
Please see prior tickets where we've discussed this and sorted it out. There may be some cases where the pid still needs to be fixed, but I can't recall offhand all the discussions we've had on this: I'd need to look them up just like you can. Also check the git history for cases where ones have been fixed.

**Comment by chenhengqi** [comment]
Thanks, Brendan. (I am a big fan of you :))

**Comment by chenhengqi** [comment]
Some related commits:

- https://github.com/iovisor/bcc/commit/15d7955e07a942340610f71e44f44046b960e3a8
- https://github.com/iovisor/bcc/pull/674/commits/66bf2e8e0bd7b7367f9a01502dbcac994a063be2
- https://github.com/iovisor/bcc/pull/739/commits/ca7ac22c2be51d6cbe7d7a48ea96f3cde3e50b05

**Comment by chenhengqi** [comment]
The tools listed above either has a `PID` option or has a `PID` column in their output, but use `u32 pid = bpf_get_current_pid_tgid` directly.

I think some of these tools still need to be fixed.

**Comment by yonghong-song** [comment]
@chenhengqi If you feel it needs a change, please help submit a patch. In the past, we indeed made some adjustment from tid (incorrectly named pid) -> real pid. Thanks!

**Comment by brendangregg** [comment]
Yes, #547 has one discussion and those commits are good examples. One thing I'd be careful of: sometimes we use pid as an unique key for storing timestamps (or whatever) in a map, and not to print out. In those cases it should be the kernel PID (what userspace thinks is the TID) so that each thread has a different ID.

So it's not just a matter of looking for the bpf_get_current_pid_tgid() calls. You also have to see how the data is then used. If it's printed out on STDOUT as a "PID", then it should match the pid printed by other tools (top(1), ps(1), etc.). If it's used as a key in a hash, then it probably should be the TID.

**Comment by chenhengqi** [comment]
> Yes, #547 has one discussion and those commits are good examples. One thing I'd be careful of: sometimes we use pid as an unique key for storing timestamps (or whatever) in a map, and not to print out. In those cases it should be the kernel PID (what userspace thinks is the TID) so that each thread has a different ID.
> 
> So it's not just a matter of looking for the bpf_get_current_pid_tgid() calls. You also have to see how the data is then used. If it's printed out on STDOUT as a "PID", then it should match the pid printed by other tools (top(1), ps(1), etc.). If it's used as a key in a hash, then it probably should be the TID.

Yeah, will do in this way.
