### ISSUE TITLE
libbpf-tools: ask for suggestion

### ISSUE THREAD

**Issue by chenyuezhou** [iovisor/bcc#3408]
There are a number of functions under `bcc/src/cc` that can help developers of `libbpf-tools`, such as `bcc_elf*, bcc_proc*...`. Do we need to add these files to the `Makefile` of `libbpf-tools`? Or provide an extra copy of code?

**Comment by yonghong-song** [comment]
cc @davemarchevsky who may have some ideas to restructure the code to be sharable by bcc and libbpf-tools.
