### ISSUE TITLE
Odd unbounded size error

### ISSUE THREAD

**Issue by Jolly5** [iovisor/bcc#3409]
I feel bad for having to ask for your help again, but I am struggling with another odd issue.

I am trying to copy any data sent using the *sendto* system call.
For that, I am reserving the amount of sent bytes as space on the ring buffer and attempt to copy the sent data there.
However, the validator refuses the call to *ringbuf_reserve* because the given size variable is unbounded.
Please note that this is the case even if I make the variable unsigned and limit its maximum size to 1:

This is my MRE:

```
from bcc import BPF

def send_event(cpu, data, size):
    global b
    ev = b["send_data"].event(data)
    print("Received data!")

prog = """
#include <linux/sched.h>
#include <linux/socket.h>
#include <linux/in.h>

BPF_RINGBUF_OUTPUT(send_data, 16);

KRETFUNC_PROBE(__sys_sendto, int sockfd, const void *buf, size_t len, int flags, const struct sockaddr *dest_addr,
                u32 addrlen, ssize_t ret) {
    if (ret < 0)
        return 0;
    
    void *data_out = NULL;
    
    u64 size = ret;
    size &= 0x1;
    data_out = send_data.ringbuf_reserve(size); // This call is refused because the variable size is unbounded...
    
    if (data_out == NULL) {
        return 0;
    }
    
    bpf_probe_read_kernel(data_out, size, buf);
    
    send_data.ringbuf_submit(data_out, 0);
    
    return 0;
}
"""

b = BPF(text=prog)
b["send_data"].open_ring_buffer(send_event)

try:
    while True:
        b.perf_buffer_poll(100)
except KeyboardInterrupt:
    print("Program stopped due to keyboard interrupt.")
```

And this is the output it produces (not all output shown, I removed warning about macro redefinitions):
```
bpf: Failed to load program: Permission denied
arg#0 type is not a struct
Unrecognized arg#0 type PTR
; KRETFUNC_PROBE(__sys_sendto, int sockfd, const void *buf, size_t len, int flags, const struct sockaddr *dest_addr,
0: (79) r6 = *(u64 *)(r1 +48)
1: (b7) r2 = 0
; if (ret < 0)
2: (6d) if r2 s> r6 goto pc+16
 R1=ctx(id=0,off=0,imm=0) R2_w=inv0 R6_w=inv(id=0,umax_value=9223372036854775807,var_off=(0x0; 0x7fffffffffffffff)) R10=fp0
; 
3: (79) r7 = *(u64 *)(r1 +8)
; data_out = bpf_ringbuf_reserve(bpf_pseudo_fd(1, -1), size, 0);
4: (18) r1 = 0xffff8f2dc4f2d200
; size &= 0x1;
6: (57) r6 &= 1
; data_out = bpf_ringbuf_reserve(bpf_pseudo_fd(1, -1), size, 0);
7: (bf) r2 = r6
8: (b7) r3 = 0
9: (85) call bpf_ringbuf_reserve#131
R2 unbounded size, use 'var &= const' or 'if (var < const)'
processed 9 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0
```

**Comment by chenhengqi** [comment]
🤦 

I try `use 'var &= const' or 'if (var < const)'`, both failed.

**Comment by yonghong-song** [comment]
With latest bpf-next, I actually got the following errors,
```
6: (57) r6 &= 1
7: R1_w=map_ptr(id=0,off=0,ks=0,vs=0,imm=0) R2_w=inv0 R6_w=inv(id=0,umax_value=1,var_off=(0x0; 0x1)) R7_w=inv(id=0) R10=fp0
; data_out = bpf_ringbuf_reserve(bpf_pseudo_fd(1, -1), size, 0); // This call is refused because the variable size is unbounded...
7: (bf) r2 = r6
8: R1_w=map_ptr(id=0,off=0,ks=0,vs=0,imm=0) R2_w=inv(id=1,umax_value=1,var_off=(0x0; 0x1)) R6_w=inv(id=1,umax_value=1,var_off=(0x0; 0x1)) R7_w=inv(id=0) R10=fp0
8: (b7) r3 = 0
9: R1_w=map_ptr(id=0,off=0,ks=0,vs=0,imm=0) R2_w=inv(id=1,umax_value=1,var_off=(0x0; 0x1)) R3_w=inv0 R6_w=inv(id=1,umax_value=1,var_off=(0x0; 0x1)) R7_w=inv(id=0) R10=fp0
9: (85) call bpf_ringbuf_reserve#131
R2 is not a known constant'
```

In the kernel, we have,
```
const struct bpf_func_proto bpf_ringbuf_reserve_proto = {
        .func           = bpf_ringbuf_reserve,
        .ret_type       = RET_PTR_TO_ALLOC_MEM_OR_NULL,
        .arg1_type      = ARG_CONST_MAP_PTR,
        .arg2_type      = ARG_CONST_ALLOC_SIZE_OR_ZERO,
        .arg3_type      = ARG_ANYTHING,
};
```
So the second argument (size) must be a constant value or 0.

The error message you saw probably from old kernel which verifier message is not precise.

**Comment by Jolly5** [comment]
Well, that explains it.
Is there any other way to send dynamically sized information to the python frontend?

I am fine with having a an upper bound to the size of the data, but that upper bound should at least be somewhere around 10KB. Yet I do not want to allocate this amount of data for every sendto-call if it's not necessary...

**Comment by yonghong-song** [comment]
Using PERCPU_ARRAY should be safe. For tracing programs, the internal bpf logic ensures BPF program won't migrate to another cpu and the PERCPU_ARRAY, once used by one program, won't be used by another program. If you don't know the exact message size, you can use perf_event_output (events.per_submit()).

**Comment by Jolly5** [comment]
Can you elaborate your last answer a bit further or give me a hint on where to find additional information on that?
I cannot find in the reference manual what you are referring to with `perf_event_output (events.per_submit())`.

Additionally, such documentation on the PERCPU_ARRAY would be very helpful aswell, because your answer raises new questions:
- What exactly are you referring to by "one program" in that context? A thread?
- If a PERCPU_ARRAY can only be used by one program but only one exists per CPU, what happens if there are more programs than CPUs? Does a CPU in bcc not actually refer to a hardware cpu core but rather something completely different?

**Comment by yonghong-song** [comment]
> Can you elaborate your last answer a bit further or give me a hint on where to find additional information on that?
> I cannot find in the reference manual what you are referring to with perf_event_output (events.per_submit()).

This following code is from kernel/bpf/verifier.c:
```
*   R8=map_value(id=0,off=0,ks=4,vs=1952,imm=0) R9_w=map_value(id=0,off=40,ks=4,vs=1952,imm=0)
 * r9 -= r8
 * r5 = r9
 * if r5 > 0x79f goto pc+7
 *    R5_w=inv(id=0,umax_value=1951,var_off=(0x0; 0x7ff))
 * r5 += 1
 * ...
 * call bpf_perf_event_output#25
 *   where .arg5_type = ARG_CONST_SIZE_OR_ZERO
```
It is possible, in early days, it must be a const size, but bpf evolved and now it support non-constant sizes.
For example, if size has a range of [0, 100], the verifier will check memory buffer to at least 100 to accommodate maximum possible size.

Maybe you can try some examples and update the document. The document indeed didn't spell out this explicitly.

 > What exactly are you referring to by "one program" in that context? A thread?
I refer to one bpf program.
> If a PERCPU_ARRAY can only be used by one program but only one exists per CPU, what happens if there are more programs than CPUs? Does a CPU in bcc not actually refer to a hardware cpu core but rather something completely different?
Percpu array may not work for two bpf programs unless two bpf programs attached to the same hooks with the same attach type. The reason is it is possible the second bpf program may run on a different cpu.
So if there is a need to coordinate between different bpf programs, typically you create a hash map with "tid" as the key (or other keys fitting the use case), so both bpf programs can access the map value properly.

**Comment by Jolly5** [comment]
Alright, thank you. I'll try and look into that.
Since the original question has been answered, I close this issue now :)
