### ISSUE TITLE
nfsslower crashes on kernel 5.10.0: cannot attach kprobe, probe entry may not exist

### ISSUE THREAD

**Issue by medislam** [iovisor/bcc#3438]
$ sudo python3 nfsslower.py 
cannot attach kprobe, probe entry may not exist
Traceback (most recent call last):
  File "nfsslower.py", line 277, in <module>
    b.attach_kprobe(event="nfs_file_read", fn_name="trace_rw_entry")
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 683, in attach_kprobe
    raise Exception("Failed to attach BPF program %s to kprobe %s" %
Exception: Failed to attach BPF program b'trace_rw_entry' to kprobe b'nfs_file_read'

**Comment by chenhengqi** [comment]
Do you try `sudo modprobe nfs` ?

**Comment by medislam** [comment]
Thanks for your response.
Yes, the NFS module is loaded, but I still have this error message.
Otherwise, I checked the headers, I didn't find the ```linux/ fs/ nfs /internal.h``` file (which contains the definition of the function being traced), maybe that's the problem.

**Comment by chenhengqi** [comment]
What's the result of 
* `cat /sys/kernel/debug/tracing/available_filter_functions | grep nfs_file_read`
* `cat /proc/kallsyms | grep nfs_file_read`

**Comment by medislam** [comment]
```cat /sys/kernel/debug/tracing/available_filter_functions | grep nfs_file_read```
    ```cat /proc/kallsyms | grep nfs_file_read```

Both commands give no thing
I try 
$ ```sudo cat /sys/kernel/debug/tracing/available_filter_functions | grep nfs | grep read```
kernfs_fop_readdir
kernfs_file_direct_read
kernfs_fop_read
genfs_read
__traceiter_nfsd_read_start [nfsd]
__traceiter_nfsd_read_splice [nfsd]
__traceiter_nfsd_read_vector [nfsd]
__traceiter_nfsd_read_io_done [nfsd]
__traceiter_nfsd_read_done [nfsd]
__traceiter_nfsd_read_err [nfsd]
__traceiter_nfsd_deleg_read [nfsd]
nfsd_last_thread [nfsd]
nfsd_nrthreads [nfsd]
nfsd_get_nrthreads [nfsd]
nfsd_set_nrthreads [nfsd]
nfsctl_transaction_read [nfsd]
write_pool_threads [nfsd]
write_threads [nfsd]
nfsd_proc_readdir [nfsd]
nfsd_proc_readlink [nfsd]
nfsd_proc_read [nfsd]
nfsd_buffered_readdir [nfsd]
nfsd_finish_read [nfsd]
nfsd_splice_read [nfsd]
nfsd_readv [nfsd]
nfsd_read [nfsd]
nfsd_readlink [nfsd]
nfsd_readdir [nfsd]
nfssvc_decode_readargs [nfsd]
nfssvc_decode_readlinkargs [nfsd]
nfssvc_decode_readdirargs [nfsd]
nfssvc_encode_readlinkres [nfsd]
nfssvc_encode_readres [nfsd]
nfssvc_encode_readdirres [nfsd]
nfssvc_release_readres [nfsd]
nfsd3_proc_readlink [nfsd]
nfsd3_proc_read [nfsd]
nfsd3_proc_readdir [nfsd]
nfsd3_proc_readdirplus [nfsd]
nfs3svc_decode_readargs [nfsd]
nfs3svc_decode_readlinkargs [nfsd]
nfs3svc_decode_readdirargs [nfsd]
nfs3svc_decode_readdirplusargs [nfsd]
nfs3svc_encode_readlinkres [nfsd]
nfs3svc_encode_readres [nfsd]
nfs3svc_encode_readdirres [nfsd]
nfsd4_readlink [nfsd]
nfsd4_readdir [nfsd]
nfsd4_read_release [nfsd]
nfsd4_read [nfsd]
read_buf [nfsd]
nfsd4_decode_readdir [nfsd]
nfsd4_encode_read_plus_data [nfsd]
nfsd4_encode_read_plus_hole [nfsd]
nfsd4_encode_read_plus [nfsd]
nfsd4_encode_readlink [nfsd]
nfsd4_encode_readdir [nfsd]
nfsd4_encode_splice_read [nfsd]
nfsd4_encode_readv [nfsd]
nfsd4_encode_read [nfsd]
nfsd4_decode_read [nfsd]
nfsd4_get_readstateid [nfsd]

**Comment by chenhengqi** [comment]
> Thanks for your response.
> Yes, the NFS module is loaded, but I still have this error message.
> Otherwise, I checked the headers, I didn't find the `linux/ fs/ nfs /internal.h` file (which contains the definition of the function being traced), maybe that's the problem.

I guess it's because the NFS module does not load successfully.

**Comment by medislam** [comment]
> > Thanks for your response.
> > Yes, the NFS module is loaded, but I still have this error message.
> > Otherwise, I checked the headers, I didn't find the `linux/ fs/ nfs /internal.h` file (which contains the definition of the function being traced), maybe that's the problem.
> 
> I guess it's because the NFS module does not load successfully.

In the nfs client machine, the ```fs_file_read``` exists, but not in the server machine. I think there is another probe for tracing reads on the server side.

**Comment by chenhengqi** [comment]
Probably `nfsd_file_put` and `nfsd_file_get`

**Comment by medislam** [comment]
For the server side, we can use ```nfsd4_write``` and ```nfsd4_read``` in order to trace write and read requests.
Thanks a lot chenhengqi
