### ISSUE TITLE
bcc/python library is missing `XDP_FLAGS*`

### ISSUE THREAD

**Issue by chenyuezhou** [iovisor/bcc#3445]
The BCC Python library seems to be missing `XDP_FLAGS*` for the flags parameter in the attach_xdp function.

Currently we can set flags directly (1<<1 for XDP_FLAGS_SKB_MODE, 1<< 3 for XDP_FLAGS_HW_MODE...) . However, this may not be very readable and we need to check the flag for each number in the kernel header file. (Or we can add a comment in the code)

Should we provide variables like `bcc.XDP_FLAGS_*`  in the Python library?

**Comment by yonghong-song** [comment]
Yes, you should be fine for that. This is stable uapi. Introducing python __init__.py totally fine.
