### ISSUE TITLE
tools/deadlock.py could not open bpf map: thread_to_held_mutexes, error: Cannot allocate memory

### ISSUE THREAD

**Issue by chenyuezhou** [iovisor/bcc#3453]
```
$./deadlock.py 101565 --binary /lib64/libpthread.so.0
could not open bpf map: thread_to_held_mutexes, error: Cannot allocate memory
Traceback (most recent call last):
  File "./deadlock.py", line 556, in <module>
    main()
  File "./deadlock.py", line 468, in main
    bpf = BPF(src_file=b'deadlock.c')
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 372, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module deadlock.c
```

`libbcc` seems to have set `RLIMIT_MEMLOCK` to `RLIM_INFINITY`. 

I wonder what caused `bpf_create_map_xattr` to fail.

**Comment by yonghong-song** [comment]
The memory requirement for this map `thread_to_held_mutexes` actually is very big:
```
  2097152 * (8 + 16 * 16) = 553648128
```
Could you reduce its size in `deadlock.c` to see whether it passed or not.

Which kernel are you using? In the recent/latest kernel (I didn't check versions), bpf program map/prog memory
won't compared against locked memory any more, instead it compared against cgroup memory. Maybe this is the reason?

**Comment by chenyuezhou** [comment]
@yonghong-song Thanks.

```
$uname -r
5.10.35
```

I've tried to reduce the size of `deadlock.c`,  and it works fine.

reducing the size of `deadlock.c` may not be the best solution. I want to know exactly what limits it has exceeded, and maybe we can output better error messages in `deadlock.c`.

**Comment by chenyuezhou** [comment]
```
$uname -r 
5.10.35
```

I checked my kernel.

The kernel still seems to check for locked memory.

`kernel/bpf/hashtab.c@htab_map_alloc+471`

```
/* if map size is larger than memlock limit, reject it */
err = bpf_map_charge_init(&htab->map.memory, cost);
```

I use `tools/trace.py` find.

```
$./trace.py 'r::bpf_map_area_alloc (!retval)'
PID     TID     COMM            FUNC
5004    5004    deadlock.py     bpf_map_area_alloc
```

`kernel/bpf/hashtab.c@htab_map_alloc+477`

```
err = -ENOMEM;
htab->buckets = bpf_map_area_alloc(htab->n_buckets * 
                                   sizeof(struct bucket), 
                                   htab->map.numa_node);
if (!htab->buckets)
    goto free_charge;
```

Maybe the size of the map is just too large.

**Comment by yonghong-song** [comment]
Yes, just checked as well. Yes, it still used locked memory.

The script works fine on my system which has 64KB default locked memory. So agree with you probably some memory allocation constraint limits how much memory you can allocate at your particular system.

**Comment by jeromemarchand** [comment]
Deadlock still can't work on system with less than about 3GB.  The main memory guzzler seems to be the fixed sized stack_traces (640k entries). Looking at /proc/vmallocinfo there seems to be two 1GB vmalloc  mapping associated with it. Reducing the size of stack_traces to 64k reduce the kernel memory usage significantly and allow to run deadlock on a system with less that 1GB, without even changing the -t and -e default value.
This should probably also be made user adjustable with an option just like -e and -t.
