### ISSUE TITLE
Questionable data when reading sk_buff from within a kprobe

### ISSUE THREAD

**Issue by Jolly5** [iovisor/bcc#3457]
I'm trying to capture outgoing ethernet frames on the local host before they are sent by inserting a kprobe into `__dev_queue_xmit()`.
However, the bytes I extract from the *sk_buff* structure do not match the subsequently captured packets.

I only attempted it for linear skbs up to now, because I already get unexpected results there.
For example, my kprobe reported the following information during a call to `__dev_queue_xmit()`:
```
COMM            PID      TGID     LEN        DATALEN
chronyd         1058     1058     90         0
3431c4b06a8b3c7c3f2023bd08006500d0a57f040f7f0000000000000000000000000000000000006018d11a0f7f00000100000000000000000000000000000060a67f040f7f0000000000000000000000000000000000004001
```
**COMM** is the name of the process which called the function,
**PID** is the calling thread's id and **TGID** its thread group id. **LEN** is the value of `(skb->len - skb->data_len)` and **DATA_LEN** is `skb->data_len`.

Next, the program has copied LEN (in this case 90) bytes starting at `skb->data`.
Since DATALEN is zero, this is a linear skb. Thus, those bytes should contain exactly the frame which is about to be sent, shouldn't they?

Well, Wireshark subsequently recorded this frame:
```
0000   34 31 c4 b0 6a 8b 3c 7c 3f 20 23 bd 08 00 45 00
0010   00 4c 83 93 40 00 40 11 d1 a2 c0 a8 b2 18 c0 a8
0020   b2 01 c8 07 00 7b 00 38 e5 b4 23 00 06 20 00 00
0030   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0040   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
0050   00 00 38 bc 17 13 12 4a 4c c0
```
The first 14 bytes, which are forming the ethernet header, match up perfectly as expected. Everything else doesn't match up at all.
The question now is: **Why do the bytes not match up**?

(Yes, I am certain the frame from Wireshark is indeed the one caused by this call to `__dev_queue_xmit()`. This is because only background programs using the network were running at the time, so the amount of outgoing traffic was rather small. Additionally, the captured frame contains, as expected, 90 bytes. Also, this frame holds an NTP payload, which is just what you'd expect from *chronyd*.)

My kernel version is 5.12.6-200.fc33.x86_64.

An additional interesting observation is, my program reports **exactly the same bytes** (except for the length) every time the function is called. However, the skb->data pointer points to different addresses each time.
There also doesn't seem to be a problem with forwarding the data to the python frontend, because I get different results if I change the data is copied from.

If you want to try it out yourself or have a closer look at my program, here it is:
```python
from bcc import BPF

from ctypes import cast, POINTER, c_char

prog = """
#include <linux/sched.h>
#include <linux/skbuff.h>

struct xmit_event {
    u64 ts;
    u32 pid;
    u32 tgid;
    u32 len;
    u32 datalen;
    u32 packet_buf_ptr;
    char comm[TASK_COMM_LEN];
    
    u64 head;
    u64 data;
    u64 tail;
    u64 end;
};
BPF_PERF_OUTPUT(xmits);

#define PACKET_BUF_SIZE 32768
# define PACKET_BUFS_PER_CPU 15

struct packet_buf {
    char data[PACKET_BUF_SIZE];
};
BPF_PERCPU_ARRAY(packet_buf, struct packet_buf, PACKET_BUFS_PER_CPU);
BPF_PERCPU_ARRAY(packet_buf_head, u32, 1);

int kprobe____dev_queue_xmit(struct pt_regs *ctx, struct sk_buff *skb, void *accel_priv) {
    if (skb == NULL || skb->data == NULL)
        return 0;
    struct xmit_event data = { };
    u64 both = bpf_get_current_pid_tgid();

    data.pid = both;
    if (data.pid == 0)
        return 0;
    data.tgid = both >> 32;
    data.ts = bpf_ktime_get_ns();
    bpf_get_current_comm(&data.comm, sizeof(data.comm));
    data.len = skb->len;
    
    // Copy packet contents
    int slot = 0;
    u32 *packet_buf_ptr = packet_buf_head.lookup(&slot);
    if (packet_buf_ptr == NULL)
        return 0;
    u32 buf_head = *packet_buf_ptr;
    u32 next_buf_head = (buf_head + 1) % PACKET_BUFS_PER_CPU;
    packet_buf_head.update(&slot, &next_buf_head);
    
    struct packet_buf *ringbuf = packet_buf.lookup(&buf_head);
    if (ringbuf == NULL)
        return 0;
    
    u32 skb_data_len = skb->data_len;
    u32 headlen = data.len - skb_data_len;
    headlen &= 0xffffff; // Useless, but validator demands it because "this unsigned(!) variable could otherwise be negative"
    bpf_probe_read_kernel(ringbuf->data, headlen < PACKET_BUF_SIZE ? headlen : PACKET_BUF_SIZE, skb->data);
    data.packet_buf_ptr = buf_head;
    
    data.len = headlen;
    data.datalen = skb_data_len;
    
    data.head = (u64) skb->head;
    data.data = (u64) skb->data;
    data.tail = (u64) skb->tail;
    data.end = (u64) skb->end;
    
    xmits.perf_submit(ctx, &data, sizeof(data));

    return 0;
}

"""

global b

def xmit_received(cpu, data, size):
    global b
    global py_packet_buf
    ev = b["xmits"].event(data)
    print("%-18d %-25s %-8d %-8d %-10d %-10d %-12d %-12d %-12d %-12d" % (ev.ts, ev.comm.decode(), ev.pid, ev.tgid, ev.len, ev.datalen, ev.head, ev.data, ev.tail, ev.end))
    bs = cast(py_packet_buf[ev.packet_buf_ptr][cpu].data, POINTER(c_char))[:ev.len]
    c = bytes(bs)
    print(c.hex())


def observe_kernel():
    # load BPF program
    global b
    b = BPF(text=prog)

    print("%-18s %-25s %-8s %-8s %-10s %-10s %-12s %-12s %-12s %-12s" % ("TS", "COMM", "PID", "TGID", "LEN", "DATALEN", "HEAD", "DATA", "TAIL", "END"))

    b["xmits"].open_perf_buffer(xmit_received)
    global py_packet_buf
    py_packet_buf = b["packet_buf"]

    try:
        while True:
            b.perf_buffer_poll()
    except KeyboardInterrupt:
        print("Kernel observer thread stopped.")

observe_kernel()
```

**Comment by Jolly5** [comment]
Found the issue. I need to create my buffer as `unsigned char data[PACKET_BUF_SIZE];` instead of `char data[PACKET_BUF_SIZE];`
I don't know why signedness makes a difference here though...

**Comment by sebastiaoamaro** [comment]
Hi, @Jolly5 do you know if it is possible to retrieve the IP header from the packet and get the source and destination addresses?

**Comment by Jolly5** [comment]
It might not work because this information *might* be inside of the nonlinear data area, which I found no way to read (see also #2505). I am not sure if this ever happens, I have never noticed it happen at least.

Other than that, this works. I am doing this exact thing in my program as well. See this excerpt:
```python
position = 12

# Check if VLAN-tagged
if packet.data[12:14] == bytes([0x81, 0x00]):
    position += 4

if packet.data[position:position+2] == bytes([0x08, 0x00]):
    position += 2
    # Packet is IPv4, show IP address
    saddr = packet.data[(position+12):(position+16)]
    daddr = packet.data[(position+16):(position+20)]
    source = str(ipaddress.ip_address(saddr))
    dest = str(ipaddress.ip_address(daddr))
````
`packet.data` are the bytes which I got from `__dev_queue_xmit` (actually they are not, but they start with the same bytes).
Those bytes start with the ethernet header, after which the IP header starts. My program first checks for the presence of a VLAN tag, because that would shift the start of the IP header by 4 bytes.
Depending on whether it's present, the start of the IP header is written into position and then the addresses are read from the header. The source address starts at byte 12 of the IPv4 header and the destination address at byte 16, both are 4 bytes long each.
Next, I convert them into their dotted decimal notation using `str(ipaddress.ip_address(addr))`.
Now, this code only works for IPv4, but you could extend it to support IPv6 easily.

**Comment by sebastiaoamaro** [comment]
Thank you so much for the reply! This is the code I am running and it doesn't print any addresses. The packet bytes don't seem to be correct, example:
02420b0100330071642f370068696d004048d580177f00000000000000000000000000000000000040ae90000000000040a5d580177f000000000000000000000049

since they don't seem to have an IP header, no 0800, (I am running iperf3 between docker containers).

```python
def xmit_received(cpu, data, size):
    global b
    global py_packet_buf
    ev = b["xmits"].event(data)
    print("%-18d %-25s %-8d %-8d %-10d %-10d %-12d %-12d %-12d %-12d" % (ev.ts, ev.comm.decode(), ev.pid, ev.tgid, ev.len, ev.datalen, ev.head, ev.data, ev.tail, ev.end))
    bs = cast(py_packet_buf[ev.packet_buf_ptr][cpu].data, POINTER(c_char))[:ev.len]
    c = bytes(bs)

    position = 12

    # Check if VLAN-tagged
    if bs[12:14] == bytes([0x81, 0x00]):
        position += 4

    # Check whether it is actually IPv4
    if bs[position:position+2] == bytes([0x08, 0x00]):
        position += 2
        # Packet is IPv4, show IP address
        saddr = bs[(position+12):(position+16)]
        daddr = bs[(position+16):(position+20)]
        source = str(ipaddress.ip_address(saddr))
        dest = str(ipaddress.ip_address(daddr))
        print(source)
        print(dest)
    print(c.hex())
```

**Comment by Jolly5** [comment]
Hmm... if the bytes are as you specified, there must be something else wrong, probably in the C part.
To be honest, I also still sometimes experience packets whose bytes seem incorrect and haven't yet been able to pinpoint the source of this problem.

Maybe I can help you more, if you show me your EBPF C code aswell.

**Comment by sebastiaoamaro** [comment]
I am using your code I only added that part. The only thing I changed was packet to bs.

**Comment by sebastiaoamaro** [comment]
Forgot to change it to unsigned it seems to work now. I now only need to put that part in C (the checking ips) thank you so much for the help!

**Comment by yonghong-song** [comment]
@Jolly5 @sebastiaoamaro I debugged the "char" vs. "unsigned char" issue. I didn't get to the bottom of it. I believe it is a python related issue. The following is what I got,

Add the following print for python percpu array get_value
```
diff --git a/src/python/bcc/table.py b/src/python/bcc/table.py
index f1a4f795..96648b46 100644
--- a/src/python/bcc/table.py
+++ b/src/python/bcc/table.py
@@ -997,6 +997,11 @@ class PerCpuArray(ArrayBase):
 
     def getvalue(self, key):
         result = super(PerCpuArray, self).__getitem__(key)
+
+        from ctypes import cast, POINTER, c_ubyte
+        rs = cast(result, POINTER(c_ubyte))[:20]
+        print(key, rs)
+
         if self.alignment == 0:
             ret = result
         else:
```

Add the following debug statements in the above code,
```
--- a/skb.py
+++ b/skb.py
@@ -1,6 +1,6 @@
 from bcc import BPF
 
-from ctypes import cast, POINTER, c_char
+from ctypes import cast, POINTER, c_char, c_ubyte
 
 prog = """
 #include <linux/sched.h>
@@ -86,7 +86,9 @@ def xmit_received(cpu, data, size):
     global py_packet_buf
     ev = b["xmits"].event(data)
     print("%-18d %-25s %-8d %-8d %-10d %-10d %-12d %-12d %-12d %-12d" % (ev.ts, ev.comm.decode(), ev.pid, ev.tgid, ev.len, ev.datalen, ev.head, ev.data, ev.tail, ev.end))
-    bs = cast(py_packet_buf[ev.packet_buf_ptr][cpu].data, POINTER(c_char))[:ev.len]
+    print(cast(py_packet_buf[ev.packet_buf_ptr], POINTER(c_ubyte))[0:20])
+    print(cast(py_packet_buf[ev.packet_buf_ptr][0].data, POINTER(c_char))[0:20])
+    bs = cast(py_packet_buf[ev.packet_buf_ptr][cpu].data, POINTER(c_ubyte))[:ev.len]
     c = bytes(bs)
     print(c.hex())
```

I am able to see `print(cast(py_packet_buf[ev.packet_buf_ptr], POINTER(c_ubyte))[0:20])` prints correct value while
`print(cast(py_packet_buf[ev.packet_buf_ptr][0].data, POINTER(c_char))[0:20])` prints a different value.
Here the `value` is 8 bytes aligned.
```
[0, 80, 86, 192, ...]
4 [0, 80, 86, 192, ...]
b'\x00\x00\x00\x00 ...
```

As demonstrated in the above, changing `char` to `unsigned char` can fix the issue.

I am not sure what is really going on here.
Can anybody who knows more python help debug this a little more? I think we need to know this so people can use Percpu arrays in python codes without such strange errors.

**Comment by sebastiaoamaro** [comment]
> Hmm... if the bytes are as you specified, there must be something else wrong, probably in the C part.
> To be honest, I also still sometimes experience packets whose bytes seem incorrect and haven't yet been able to pinpoint the source of this problem.
> 
> Maybe I can help you more, if you show me your EBPF C code aswell.

Hi @Jolly5 I have been trying to put the source and destination addresses (int format) in the xmit_event, but I have not been able to I tried to get parts of this unsigned char data[PACKET_BUF_SIZE] and put them in the xmit_event but I have not been able to, do you know how to do this? My c is not the best I must say as well.

**Comment by Jolly5** [comment]
@sebastiaoamaro can you show me the code you've got so far?
That would also help me understand what exactly you are trying to achieve.

**Comment by sebastiaoamaro** [comment]
> @sebastiaoamaro can you show me the code you've got so far?
> That would also help me understand what exactly you are trying to achieve.

Hi @Jolly5 thanks for the reply, I was able to do what I wanted. Simple shifts got me the IPs in C, if you need that code by any means contact me! A quick question regarding traffic controlling, do you know if there is an attribute in the skb that gives the size of the data being sent through the network? I tried truesize but it doesn't seem to be correct.

**Comment by Jolly5** [comment]
Well... that depends on what exactly you are referring to by data here.
In case you talk about the size of the complete frame (the complete Layer 2 data): As of Kernel 5.12, `skb->len` should do the trick.
