### ISSUE TITLE
bcc/Does bcc support attach cgroup?

### ISSUE THREAD

**Issue by chenyuezhou** [iovisor/bcc#3469]
It seems that `bcc` does not support direct attach to cgroup yet.

**Comment by yonghong-song** [comment]
bcc has the following two functions,
```
  StatusTuple attach_func(int prog_fd, int attachable_fd,
                          enum bpf_attach_type attach_type,
                          uint64_t flags);
  StatusTuple detach_func(int prog_fd, int attachable_fd,
                          enum bpf_attach_type attach_type);
```
which can be used to attach a program to a particular cgroup. Here attachable_fd is the corresponding cgroup fd.

**Comment by chenyuezhou** [comment]
Thank you for your reply. It is a great help!

**Comment by chenyuezhou** [comment]
Can we introduce this into BCC Python？

**Comment by yonghong-song** [comment]
> Can we introduce this into BCC Python？

Yes, we can. We should use the same names, attach_func and detach_func, for python API as well. Could you help craft a patch?

**Comment by chenyuezhou** [comment]
Of course, I'll give it a try

**Comment by chenyuezhou** [comment]
for bcc-python:

```
BPF.attach_func(fn, attachable_fd, attach_type [, flags])
BPF.detach_func(fn, attachable_fd, attach_type)
```

for libbcc

```
StatusTuple attach_func(int prog_fd, int attachable_fd,
                        enum bpf_attach_type attach_type,
                        uint64_t flags);
StatusTuple detach_func(int prog_fd, int attachable_fd,
                        enum bpf_attach_type attach_type);
```

Here attachable_fd is the corresponding cgroup fd.
