### ISSUE TITLE
Is there an API to get the fill ratio of a perf buffer?

### ISSUE THREAD

**Issue by yzhao1012** [iovisor/bcc#3474]
Given a perf buffer, to get the ratio of consumed space vs. the capacity of the perf buffer, this is used to determine how often the perf buffer should be polled.

Is there a ready-made API for this?

**Comment by anakryiko** [comment]
Not for perf buffer. But there is such api for BPF ring buffer, see bpf_ringbuf_query() (https://github.com/torvalds/linux/blob/master/include/uapi/linux/bpf.h#L4131-L4146).

**Comment by yzhao1012** [comment]
Thanks!
