### ISSUE TITLE
There is no notification of event loss using ring buffer

### ISSUE THREAD

**Issue by medislam** [iovisor/bcc#3476]
Hello,
I encountered the event loss problem using ring_buffer, however, the event loss message is not displayed! Is there a way to enable the event loss notification with the ring_buffer, whatever the API: output/submit.
Note, I tried both APIs: ```ring_buffer_submit``` and ```ring_buffer_output```, but nothing is displayed.
I need this message in order to know the total number of lost events.
I use the Linux kernel 5.10 version.
Thank you,

**Comment by chenyuezhou** [comment]
Hello,

For `ringbuf_output`, return 0 on success, or a negative error in case of failure.

For `ringbuf_submit`, its always succeeds.

**Comment by medislam** [comment]
Thank you for your reply.

If I understood correctly, ```ringbuf_output``` must return a negative value in case of event loss?

I have another question if you can answer me. Imagine this scenario, eBPF is building an event (executing the probe handler) but before registering this event, the probe is called yet another time, will ebpf ignore the new event? The old event or records both?

Thank you so much,

**Comment by chenyuezhou** [comment]
sry, I seem to have misunderstood your question.

> If I understood correctly, ringbuf_output must return a negative value in case of event loss? 

That doesn't seem right

```
BPF_CALL_4(bpf_ringbuf_output, struct bpf_map *, map, void *, data, u64, size,
           u64, flags)
{
        struct bpf_ringbuf_map *rb_map;
        void *rec;

        if (unlikely(flags & ~(BPF_RB_NO_WAKEUP | BPF_RB_FORCE_WAKEUP)))
                return -EINVAL;

        rb_map = container_of(map, struct bpf_ringbuf_map, map);
        rec = __bpf_ringbuf_reserve(rb_map->rb, size);
        if (!rec)
                return -EAGAIN;

        memcpy(rec, data, size);
        bpf_ringbuf_commit(rec, flags, false /* discard */);
        return 0;
}
```

`ringbuf_output/ringbuf_submit` should not cause event loss problems if it is running properly.

Could you  provide a simple example of how the event loss you mentioned is caused.

**Comment by chenyuezhou** [comment]
If the lost event is due to the Ring Buffer consumer catching up with the producer. You can check if the `ringbuf_output` returns -EAGAIN.

**Comment by chenyuezhou** [comment]
Hi, 

* Linux kernel 5.10
* 1 CPU cores

I made a few simple adjustments to the script you provided.

```
@@ -42,6 +42,7 @@ program=("""
        u64     timestamp;
        };

+       BPF_ARRAY(counts, u32, 1);
        BPF_RINGBUF_OUTPUT(buffer, 4);

        ssize_t VFS_write(struct pt_regs *ctx,struct file * file, const char __user * buf, size_t count, loff_t * pos){
@@ -60,7 +61,7 @@ program=("""
                event.timestamp = bpf_ktime_get_ns();

                if(buffer.ringbuf_output(&event, sizeof(event), 0) == -EAGAIN){
-                       bpf_trace_printk("EAGAIN");
+                       counts.increment(0);
                }
@@ -95,10 +96,12 @@ b.attach_kprobe(event="vfs_write", fn_name="VFS_write")

 # callback parses messages received from perf_buffer_poll
 def callback(ctx, data, size):
+    global gb_count
     evenement = b["buffer"].event(data)
-    event = (evenement.timestamp)
-    format_ = ("%.0f")
-    print(format_ % event)
+    gb_count += 1
+    # event = (evenement.timestamp)
+    # format_ = ("%.0f")
+    # print(format_ % event)


 b["buffer"].open_ring_buffer(callback)
@@ -110,4 +113,5 @@ try:
         b.ring_buffer_consume()
         # time.sleep(1)
 except KeyboardInterrupt:
-    sys.exit()
+    print(gb_count, b["counts"][0])
+    sys.exit()
```

test with `dd if=/dev/zero of=/dev/null bs=1 count=524288`

`(47058, [c_uint(477233L)])`

total event 47058 + 477233 = 524291

test with `dd if=/dev/zero of=/dev/null bs=1 count=5242880`

`(515592, c_uint(4727291L))`

totoal event 515592 + 4727291 = 5242883

In the test, it looks as if no events are discarded. (Those -EAGAIN need to add a retry.)

**Comment by anakryiko** [comment]
@chenyuezhou is `counts.increment(0);` really how to increment by one?...

@medislam BPF ringbuf doesn't have built-in mechanism to count and report number of dropped samples. That was conscious design decision for the sake of performance. But you can count it on your own, as suggested above. bpf_ringbuf_output() will return < 0 on error (-EAGAIN if there is no space left or we failed to reserve the space for some other reason, which can happen if your BPF program runs in NMI and ringbuf is heavily contended). Similarly, bpf_ringbuf_reserve() will return NULL, if it fails to reserve space, so you can use that as an indication of dropped sample. Once bpf_ringbuf_reserve() succeeds, bpf_ringbuf_submit() will never fail, so you don't have to deal with any error for submit.

**Comment by chenyuezhou** [comment]
> @chenyuezhou is counts.increment(0); really how to increment by one?...

`counts` is an array, `counts.increment(0);` increase counts[0] by 1.

**Comment by medislam** [comment]
@anakryiko @chenyuezhou 
Thank you very much for your answers.

For the perf_submit, 

- I counted the number of lost events (```if (events.perf_submit (ctx, & event, sizeof (event)) <0) event_loss_counts.increment (1);```)
- I increased the size of the perf_buffer to 1GB (```b ["events"].open_perf_buffer (callback, page_cnt = 1 << 18)```)
- I counted the total number of times the probe was executed (```all_counts.increment (0);``` placed at the start of the handler)
- I calculated the number of events recorded in the trace (```wc -l my_trace```)
- I used ```b.perf_buffer_poll()``` to poll events (without timeout)

Here are the results:
event_loss_counts = 0
all_counts = 21349216
the number of events in the trace = 8053498

probably there are  21349216 - 8053498 = 13295718 events non-recorded in the trace.

Where does this loss of events that are not recorded in the track come from?

thank you,

**Comment by chenyuezhou** [comment]
Hi, 

This is my test code.

```python
from bcc import BPF
from bcc.utils import printb

# define BPF program
prog = """
#include <linux/sched.h>

// define output data structure in C
struct data_t {
    u32 pid;
    u64 ts;
    char comm[TASK_COMM_LEN];
};
BPF_ARRAY(counts, u32, 2);
BPF_PERF_OUTPUT(events);

int vfs_read(struct pt_regs *ctx) {
    struct data_t data = {};

    data.pid = bpf_get_current_pid_tgid();
    data.ts = bpf_ktime_get_ns();
    bpf_get_current_comm(&data.comm, sizeof(data.comm));

    counts.increment(0);
    if (events.perf_submit(ctx, &data, sizeof(data)))
        counts.increment(1);

    return 0;
}
"""
b = BPF(text=prog)
b.attach_kprobe(event="vfs_read", fn_name="vfs_read")
cnt = 0
lost = 0

def print_event(cpu, data, size):
    global cnt
    cnt += 1

def lost_cb(lt):
    global lost
    lost += 1

b["events"].open_perf_buffer(print_event, lost_cb=lost_cb)
while 1:
    try:
        b.perf_buffer_poll()
    except KeyboardInterrupt:
        print(cnt, lost, b["counts"][0], b["counts"][1])
        exit()
```

test with `dd`

output: (40969, 59, c_uint(524451L), c_uint(483482L))

A non-0 return from `perf_submit` indicates that the event was not successfully written and a retry is required otherwise the event will be lost.

Events may also be lost when `perf_submit` returns 0, which can be picked up by passing `lost_cb`.

**Comment by anakryiko** [comment]
Those counter.increment() calls are not atomic/synchronized, so whatever you are counting is very misleading. Use lock_xadd() to do proper counting on BPF side. @medislam counters.increment(1) increments counters[1] by 1, not counters[0], so that might explain why event_loss_counts is zero. Also, you need to detach BPF program, drain perf buffer and only then compare counters.

**Comment by medislam** [comment]
@chenyuezhou 
I tried using ```lost_cb ```, but got 
event_loss_counts = 0 (using ```if(events.perf_submit (ctx, &event, sizeof (event)) <0) event_loss_counts.increment(0); ```)
all_counts:  21349216 
recorded_event_count:  9340285
lost:  0

Can ```perf_buffer_poll``` lose events? 
For information, I implemented the same program with bpftrace, and I had all the events in the trace (no loss, I have 21 million events).
I think bpftrace is based on c++ to retrieve events. Is this the reason why bpftrace can catch all events without any loss?

@anakryiko 
I tried to use lock_xadd to increment the total number of events, but I got this error:
```/virtual/main.c:159:26: error: subscripted value is not an array, pointer, or vector lock_xadd(all_counts[0],1);```

For detaching the BPF program, I did  ctrl+c, is this correct ?

**Comment by chenyuezhou** [comment]
> @chenyuezhou
I tried using lost_cb , but I got
event_loss_counts = 0 (using if(events.perf_submit (ctx, &event, sizeof (event)) <0) event_loss_counts.increment(0); )
all_counts: 21349216
the number of events in the trace: 9340285
lost: 0
Can perf_buffer_poll lose events?
For information, I implemented the same program with bpftrace, and I had all the events in the trace (no loss, I have 21 million events).
I think bpftrace is based on c++ to retrieve events. Is this the reason why bpftrace can catch all events without any loss?

Hi @medislam , You can take a look at this article http://blog.itaysk.com/2020/04/20/ebpf-lost-events, it may help you.

**Comment by chenyuezhou** [comment]
> I tried to use lock_xadd to increment the total number of events, but I got this error:
/virtual/main.c:159:26: error: subscripted value is not an array, pointer, or vector lock_xadd(all_counts[0],1);

You can try like this.

```
u32 key = 0;
u32 *val = all_counts.lookup(&key);
if (val) lock_xadd(val, 1);
```

> For detaching the BPF program, I did ctrl+c, is this correct ?

You can try using the `bpftool prog` to see if the BPF program is detached.

**Comment by medislam** [comment]
@chenyuezhou 

In the article  http://blog.itaysk.com/2020/04/20/ebpf-lost-events, it is mentioned that for perf_submit "There’s a check if there’s enough space in the ring buffer (and also the buffer is configured to not overwrite), then we go to fail" 
How can I know whatever the perf buffer is configured to overwrite or not ? may be this is the source of my problem.
Thanks a lot.

**Comment by medislam** [comment]
@anakryiko @chenyuezhou 
I redid the tests using a BCC and bpftrace version of my tracer, I found:
bpftrace version:

- there are 21 million events in the trace (there is no event loss).
- The space used in RAM before launching the test is 1.3Gb
- The space used in RAM after stopping the test is 1.3 Gb

bcc version:

- There are 9 million events in the trace (normally it should be 21 million).
- No event loss message (I think the events are all recorded in the perf buffer).
- The space used in RAM before the launch of the 1.3Gb test
- The space used in RAM after stopping the 5.3 Gb test

There is 4 Gb of data remaining in the RAM, I think those are the events which were not recovered by the function
perf_buffer_poll in user space.

I relaunched the bcc version, and I noticed that each time the space used in the RAM (after the end of the test) is increased by 4Gb.

What do you think ?
Thank you

**Comment by medislam** [comment]
It's okay, I found the source of the problem. It is because of the BPF program stopping before the perf_buffer_poll function has finished fetching all events in user space.

Thank you a lot.
@anakryiko @chenyuezhou
