### ISSUE TITLE
Inconsistent string encoding breaks tools/tplist UI and behavior

### ISSUE THREAD

**Issue by spenczar** [iovisor/bcc#3478]
When I use `tplist`, it prints out identifiers which include a Python string kind identifier in front:

```
-> % sudo tplist -p $(pgrep -f 'python main.py')                     
b'/proc/17593/root/usr/bin/python3.8' b'python':b'gc__start'
b'/proc/17593/root/usr/bin/python3.8' b'python':b'gc__done'
b'/proc/17593/root/usr/bin/python3.8' b'python':b'audit'
b'/proc/17593/root/usr/bin/python3.8' b'python':b'import__find__load__start'
b'/proc/17593/root/usr/bin/python3.8' b'python':b'import__find__load__done'
[...]
```

I would have expected output like this:
```
-> % sudo tplist -p $(pgrep -f 'python main.py')                     
/proc/17593/root/usr/bin/python3.8 python:gc__start
/proc/17593/root/usr/bin/python3.8 python:gc__done
/proc/17593/root/usr/bin/python3.8 python:audit
/proc/17593/root/usr/bin/python3.8 python:import__find__load__start
/proc/17593/root/usr/bin/python3.8 python:import__find__load__done
[...]
```

Furthermore, these mangled strings break filtering. I get no results if I do something like this:
```
-> % sudo tplist -p $(pgrep -f 'python main.py') 'python:*'
-> %
```

Instead, I need to explicitly include string type markers:
```
-> % sudo tplist -p $(pgrep -f 'python main.py') "b'python':*"
b'/proc/17593/root/usr/bin/python3.8' b'python':b'gc__start'
b'/proc/17593/root/usr/bin/python3.8' b'python':b'gc__done'
b'/proc/17593/root/usr/bin/python3.8' b'python':b'audit'
b'/proc/17593/root/usr/bin/python3.8' b'python':b'import__find__load__start'
b'/proc/17593/root/usr/bin/python3.8' b'python':b'import__find__load__done'
```

I think this is because `bcc/usdt.py` [creates `USDTProbe` objects with the raw `probe.contents`](https://github.com/iovisor/bcc/blob/1aeec1ffc5517ed47b249ba74a3e2870af36f865/src/python/bcc/usdt.py#L197) from its C calls. The same is true for [`USDTProbeLocation`s created by `USDTProbe`](https://github.com/iovisor/bcc/blob/1aeec1ffc5517ed47b249ba74a3e2870af36f865/src/python/bcc/usdt.py#L120-L125). These are then [formatted with the `%s` directive](https://github.com/iovisor/bcc/blob/1aeec1ffc5517ed47b249ba74a3e2870af36f865/src/python/bcc/usdt.py#L116-L117) in `USDTProbe.short_name()`, and `tplist` uses `short_name()` for its filtering.

It's tempting to change the `USDTProbe` (and `USDTProbeLocation`) constructors to decode their input values when assigning them to attributes, but I think that would break lots of stuff unless we go through and re-encode them, since those attributes are used directly to make lots of calls to the BCC C libraries. Changing only the display side is maybe safer, but will involve chasing down lots of cases where the strings are displayed. For example, [tplist uses `%s` on probe attributes too directly](https://github.com/iovisor/bcc/blob/master/tools/tplist.py#L83-L84).

I built HEAD from source on Ubuntu 20.04. I'm using Python 3.8.5.

**Comment by yonghong-song** [comment]
This whole thing prefixed with 'b' is for python3 compatibility. If you have any good suggestions on how to improve this, please share and contribute. Thanks for looking into this!

**Comment by spenczar** [comment]
@yonghong-song I don't think this is Python compatibility exactly. This is that bcc/usdt.py is storing values with a type of `bytes` (not string!), but then rendering them with `%s` which does not _decode_ the raw bytes. In Python 2, there was no `bytes` type - just strings, so this would have worked, sort of.

So, I have two possible solutions:
1. We could change the Python constructors to decode data from bytes to strings, and re-encode from strings back into bytes whenever we call `libbcc` C functions. 
2. We could decode from bytes to strings in every spot where values are printed.

I don't know which is preferable. The first feels like a better solution long-term but might be riskier, while the second is going to probably require a few rounds of fixing printing code. Do you have thoughts on which one would be better?

**Comment by yonghong-song** [comment]
I prefer method 2. Maybe we can start with the issue you are facing and gradually fixing other occurrences?

**Comment by spenczar** [comment]
Sounds good. I'll work on a little PR for it.
