### ISSUE TITLE
tools/Dose atomic operations need to be supported？

### ISSUE THREAD

**Issue by chenyuezhou** [iovisor/bcc#3481]
I find that many tools under the tools/ directory currently use `map.increment` or `map.lookup and (*val)++` without lock, which are not atomic operations. In the case of concurrency, the statistical results are not accurate, but if atomic operations are used, there will be a lot of overhead. Do we need to make adjustments or is it better to leave things as they are?

**Comment by yonghong-song** [comment]
I think this needs case-by-case study. For normal counting, non atomic should work just fine if you only need some estimation, the end result may be off say 10 over 1M events, it could be acceptable. If you really want precise results, yes, atomic operations will be preferred. In particular, we hear from somebody complaining the inaccurate results due to concurrency, it is a good sign we should change to use atomic operations.

**Comment by chenyuezhou** [comment]
Thanks, I agree.

(BTW.  Can we provide an option to tools, inform users in the document or `help message` what problems may occur if the accurate collection option is not enabled, and what the overhead will be if enabled?)

**Comment by yonghong-song** [comment]
@chenyuezhou Acutally, I personally didn't do any performance evaluation w.r.t. xadd overhead. Could you help with this? Providing an option for xadd seems overkill. If not enough overhead or a little bit overhead is not an issue, e.g., some top tools, etc. It is okay just using xadd. Most bcc tools should not cause a lot of cpu overhead, so I think it may make sense to replace with xadd if your performance evaluation confirms my suspicion.

**Comment by chenyuezhou** [comment]
> @chenyuezhou Acutally, I personally didn't do any performance evaluation w.r.t. xadd overhead. Could you help with this? Providing an option for xadd seems overkill. If not enough overhead or a little bit overhead is not an issue, e.g., some top tools, etc. It is okay just using xadd. Most bcc tools should not cause a lot of cpu overhead, so I think it may make sense to replace with xadd if your performance evaluation confirms my suspicion.

OK, I'll find suitable machines (multi-core) to test it.

**Comment by yonghong-song** [comment]
Thanks!

**Comment by chenyuezhou** [comment]
# system

kernel version: `5.10.43`
online cpu: `0-7`
bcc-version: `0.20.0-5934161d`

# bpf code

```
BPF_ARRAY(counts, u32, 1);

int vfs_read(struct pt_regs *ctx) {
    int i;
    char ccmd[TASK_COMM_LEN];
    char cmd[2] = "dd";

    if (bpf_get_current_comm(&ccmd, TASK_COMM_LEN)) {
        return 0;
    }

    for (i = 0; i < 2; i++) {
        if (cmd[i] != ccmd[i])
            return 0;
    }

    u32 key = 0;
    u32 *val = counts.lookup(&key);
    if (val == 0) {
        return 0;
    }
    val++;
    return 0;
}

int vfs_atomic_read(struct pt_regs *ctx) {
    int i;
    char ccmd[TASK_COMM_LEN];
    char cmd[2] = "dd";

    if (bpf_get_current_comm(&ccmd, TASK_COMM_LEN)) {
        return 0;
    }

    for (i = 0; i < 2; i++) {
        if (cmd[i] != ccmd[i])
            return 0;
    }

    u32 key = 0;
    u32 *val = counts.lookup(&key);
    if (val == 0) {
        return 0;
    }
    lock_xadd(val, 1);
    return 0;
}
```

# test command 

`dd if=/dev/zero of=/dev/null bs=1 count=5242880`

# result

| No. threads   | th(atomic write) | th(write) | event lost rate(totoal events) |
|  ----  | ----  | ---- | ---- |
| 2 | 1.4MB/s | 1.4 MB/s | 1.3%(10485768) | 
| 4 | 1.3MB/s | 1.3 MB/s | 18.1%(20971536) |
| 8 | 927kB/s | 929kB/s | 16.6%(41943072) |
| 16 | 493kB/s | 494kB/s | 14.8%(83886144) |
| 32 | 237kB/s | 241kB/s | 15.0((167772288) |

Overhead seems to be negligible. But events seem to have lost a lot.

**Comment by chenyuezhou** [comment]
@yonghong-song 

The overhead caused by using `xadd` is almost negligible. Should we adjust some of the BCC tools to use `xadd` for more accurate data collection?

**Comment by yonghong-song** [comment]
@chenyuezhou Currently funclatency.py and biolatency.py already used it. Looking at your performance comparison, it indeed just minor difference, so let converts to xadd then. Thanks!

**Comment by chenyuezhou** [comment]
I find `map.increment` more convenient than `map.lookup, check val, (*val)++` and users may prefer to use `map.increment`. 

I was wondering if we could add an option to `increment()` to make it atomic, or provide another function like `atomic_increment()`.

@yonghong-song Could you give me some suggestions? Thanks.

**Comment by yonghong-song** [comment]
@chenyuezhou Let us just provide `atomic_increment` so people can opt in to use it. There are cases where atomic_increment() is not needed and if we do it automatically and showed up in byte code, it may confuse users.
