### ISSUE TITLE
Python load_func broken in master

### ISSUE THREAD

**Issue by mageshgv** [iovisor/bcc#3489]
There was either a merge conflict or typo in the merge from 2 days back, but load_func fails on master.

This is the wrong code initializing XDP with 37. This variable needs to be renamed:
https://github.com/iovisor/bcc/blob/master/src/python/bcc/__init__.py#L219
Correct value here for XDP (6):
https://github.com/iovisor/bcc/blob/master/src/python/bcc/__init__.py#L151

**Comment by davemarchevsky** [comment]
Looks like #3479 is the PR which added this redefinition. Will figure out what the intended change was there and fix.

**Comment by davemarchevsky** [comment]
Ah, okay, this is a pretty straightforward namespace collision. We're porting enum values from https://elixir.bootlin.com/linux/latest/source/include/uapi/linux/bpf.h (`bpf_prog_type`, `bpf_attach_type` specifically), but not separating them properly here. Should be able to fix in a way that prevents this from happening again.

**Comment by davemarchevsky** [comment]
once #3490 is merged this should be fixed in master
