### ISSUE TITLE
Add macro HASH_OF_MAPS other types of the key

### ISSUE THREAD

**Issue by masibw** [iovisor/bcc#3496]
Hi, `BPF_HASH_OF_MAPS` macro only supports int type key.

I don't know why it doesn't support it, but I wanna use other types of the key. 

I found this [post](https://stackoverflow.com/questions/61214099/functionality-of-the-bpf-hash-of-maps-structure), so maybe we can create `BPF_HASH_OF_MAPS` by using `BPF_TABLE`. But the method isn't clear. And I got some error. So supporting other types of the key is better I think.

The macro definition is [here](https://github.com/iovisor/bcc/blob/2fa54c0bd388898fdda58f30dcfe5a68d6715efc/src/cc/export/helpers.h#L294-L295)
```
#define BPF_HASH_OF_MAPS(_name, _inner_map_name, _max_entries) \
BPF_TABLE("hash_of_maps$" _inner_map_name, int, int, _name, _max_entries)
```

**Comment by yonghong-song** [comment]
@masibw Right, I think to allow custom key_type is good and necessary for BPF_HASH_OF_MAPS. See an example https://github.com/iovisor/bcc/commit/6d88feb202aaf6dbe54ba90f1b17fcf2b5edd107 for SOCKHASH. Maybe you could you help with a pull request? Currently, BPF_TABLE is used, you can just add an key_type parameter to BPF_HASH_OF_MAPS.

**Comment by masibw** [comment]
@yonghong-song,  Okey, I'll try to make PR. Thanks for the good references!

**Comment by masibw** [comment]
Sorry, I'm new to bcc(also new to writing python library), when I rewrote the bcc source code, then What I should do?
As the INSTALL.md says, I will run these commands?
```
mkdir bcc/build; cd bcc/build
cmake ..
make
sudo make install
cmake -DPYTHON_CMD=python3 .. # build python3 binding
pushd src/python/
make
sudo make install
popd
```
After run these commands, Can I use my rewrote code by from bcc import BPF?

**Comment by chenhengqi** [comment]
> Sorry, I'm new to bcc(also new to writing python library), when I rewrote the bcc source code, then What I should do?
> As the INSTALL.md says, I will run these commands?
> 
> ```
> mkdir bcc/build; cd bcc/build
> cmake ..
> make
> sudo make install
> cmake -DPYTHON_CMD=python3 .. # build python3 binding
> pushd src/python/
> make
> sudo make install
> popd
> ```
> 
> After run these commands, Can I use my rewrote code by from bcc import BPF?

Follow this commit https://github.com/iovisor/bcc/commit/6d88feb202aaf6dbe54ba90f1b17fcf2b5edd107 , make changes and install locally, then write a small program to test the new feature locally. Don't think you need to write python library. Correct me if I am wrong.

**Comment by masibw** [comment]
Thanks to reply @chenhengqi 
>make changes and install locally,


This means runs the below commands? 
```
mkdir bcc/build; cd bcc/build
cmake ..
make
sudo make install
cmake -DPYTHON_CMD=python3 .. # build python3 binding
pushd src/python/
make
sudo make install
popd
```

**Comment by yonghong-song** [comment]
The above command just to ensure build successful. You will need to modify below two tests with new macro definition.
```
$ egrep -r HASH_OF_MAPS
cc/test_map_in_map.cc:      BPF_HASH_OF_MAPS(maps_hash, "ex1", 10);
python/test_map_in_map.py:      BPF_HASH_OF_MAPS(maps_hash, "ex1", 10);
```
Please change them to have a struct type as the key.

**Comment by masibw** [comment]
I see. After modifying two tests, How to run the test? `make test PYTHON_TEST_LOGFILE=./log.txt AEGS=-V` ?

**Comment by yonghong-song** [comment]
Let us just use 
```
#define BPF_HASH_OF_MAPS4(_name, _key_type, _inner_map_name, _max_entries)
```
I think it is okay, we didn't maintain `BPF_SOCKHASH` either. The syntax will become
ugly if we want to support backport compatibility (e.g, put `_key_type` at the end.)

To run the test, after build, you can just run `test_libbcc` and `test_map_in_map.py`.
BTW, I think `test_map_in_map.py` is not in CMakefile file and it seems having some
issues (at least for python3). It will be great if you can help fix the issue.

**Comment by masibw** [comment]
Okay, I will write as 
```
#define BPF_HASH_OF_MAPS4(_name, _key_type, _inner_map_name, _max_entries)
```

>To run the test, after build, you can just run test_libbcc and test_map_in_map.py.

Thanks, I'll try it.

>BTW, I think test_map_in_map.py is not in CMakefile file and it seems having some
issues (at least for python3). It will be great if you can help fix the issue.

Yes, I don't think the test is running.
I'll do some digging.
