### ISSUE TITLE
KeyError when reading from BPF map that is simultaneously modified

### ISSUE THREAD

**Issue by goldshtn** [iovisor/bcc#350]
I'm working on a memory leak tracing script that probes alloc and free calls and displays outstanding allocations that weren't freed yet. The full script: [memleak.py](https://github.com/goldshtn/bcc/blob/master/tools/memleak.py) [memleak.c](https://github.com/goldshtn/bcc/blob/master/tools/memleak.c)

It's operating in one of two modes -- uprobes that attach to `malloc`/`free` in a particular process, or kprobes that attach to `__kmalloc`/`kfree`. The BPF program is the same (memleak.c), it's just a matter of attaching to different functions.

The kprobe case (e.g. run `sudo ./memleak.py -i 1`) throws a `KeyError` when attempting to enumerate the BPF hash (`bpf_program.get_table("allocs").items()` is enough to cause this). Apparently, `bpf_lookup_elem` returns an error.

Enumerating the keys works fine. Accessing some values by key also works fine (on my box it's usually the second or third key that causes the `KeyError`). Could there be a race condition between enumerating the keys and accessing the values? I used strace and saw that the `bpf` syscall is failing with ENOENT. The map is being simultaneously modified by the BPF program. What would be the best approach to snapshot the map, if that's the issue?

**Comment by drzaeus77** [comment]
I'll see if I can look at this, but will be traveling overseas so expect delays.

**Comment by goldshtn** [comment]
Thanks, that fixes the issue for me. I'm a bit worried though -- isn't it possible for the Python module to race against the BPF program in general? For example, even retrieving the hash's keys seems like a non-atomic operation that involves multiple `bpf` system calls with `BPF_MAP_GET_NEXT_KEY`.

**Comment by drzaeus77** [comment]
Yes and no, and the race isn't really python specific, any user of the syscall API will experience this. The syscall API is designed in such a way that iterating through it won't be interrupted by key deletions. For instance, if you issue BPF_MAP_GET_NEXT_KEY with a prevkey that has just been deleted, or replaced with a new value, the nextkey that you see will be the same regardless of whether the prevkey is deleted, unchanged, or updated. Iterating through the entire list of keys will give you a stable view of the keys, but not atomic. Meaning, the list isn't a snapshot in time, but neither will it skip any keys or see any key twice.

That said, the api that we expose in the python class is not meant to honor the python api semantics, but to provide a convenience wrapper for the kernel tables. The resulting behavior will therefore be confusing to a native pythonista. This deserves better documentation in the python module.
