### ISSUE TITLE
TRACEPOINT_PROBE not attaching with c++ API

### ISSUE THREAD

**Issue by MiSzostak** [iovisor/bcc#3509]
Hi all,
I'm trying to trace syscalls using the c++ API but the tracepoint doesn't seem to attach. If I use the python API with the same BPF program it works without issues.

Some information about my environment:

- libbcc version: `0.20.0-8e6c05da`
- kernel: `5.11`
- clang++ version: `10.0.1`

The program looks like this:

```cpp
#include <cstdio>
#include <string>

#include <bcc/BPF.h>

const std::string BPF_PROGRAM = R"(
struct data_t {
    u32 pid;
    u64 ts;
    s64 nr;
};

BPF_PERF_OUTPUT(events);

TRACEPOINT_PROBE(raw_syscalls, sys_enter) {
    struct data_t data = {};

    data.pid = bpf_get_current_pid_tgid();
    data.ts = bpf_ktime_get_ns();
    data.nr = args->id;

    events.perf_submit(args, &data, sizeof(data));

    return 0;
}

)";

struct data_t {
    uint32_t pid;
    uint64_t ts;
    long nr;
};

void handle_output(void *cb_cookie, void *data, int data_size) {
    auto info = static_cast<data_t *>(data);
    printf("%5u %ld\n", info->pid, info->nr);
}

int main() {
    ebpf::BPF bpf;
    auto result = bpf.init(BPF_PROGRAM);
    if (result.code() != 0) {
        printf("%s\n", result.msg().c_str());
        return 1;
    }

    auto open_result = bpf.open_perf_buffer("events", &handle_output);
    if (open_result.code() != 0) {
        printf("%s\n", open_result.msg().c_str());
        return 1;
    }

    printf("  PID  NR\n");

    auto perf_buffer = bpf.get_perf_buffer("events");
    if (!perf_buffer) {
        printf("Failed to get perf buffer\n");
        return 1;
    }

    while (true) {
        perf_buffer->poll(100);
    }

    return 0;
}

```

Compiled it with `clang++ -Wall -O3 -o trace trace.cpp -lbcc` and got no errors or warnings. No errors during execution either, but the only thing that appears is the header.

Am I missing something that's required to properly attach the probe? I couldn't find any c++ examples that use `TRACEPOINT_PROBE` so I just compared it with the python examples.

**Comment by chenhengqi** [comment]
Add this line after `bpf.init()` works for me.
```cpp
bpf.attach_tracepoint("raw_syscalls:sys_enter", "tracepoint__raw_syscalls__sys_enter");
```

BTW, you should use the higher 32 bits of `bpf_get_current_pid_tgid` for pid and rearrange fields of data_t to avoid padding.

**Comment by chenhengqi** [comment]
Maybe we can add an auto-attach API for C++ ?

**Comment by MiSzostak** [comment]
@chenhengqi Thanks!
