### ISSUE TITLE
AttributeError:  undefined symbol: bpf_delete_batch

### ISSUE THREAD

**Issue by wingchi-leung** [iovisor/bcc#3530]
I was running a helloWorld program but i get the error: 
`Traceback (most recent call last):
  File "hello.py", line 2, in <module>
    from bcc import BPF
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 27, in <module>
    from .libbcc import lib, bcc_symbol, bcc_symbol_option, bcc_stacktrace_build_id, _SYM_CB_TYPE
  File "/usr/lib/python3/dist-packages/bcc/libbcc.py", line 86, in <module>
    lib.bpf_delete_batch.restype = ct.c_int
  File "/usr/lib/python3.8/ctypes/__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /lib/x86_64-linux-gnu/libbcc.so.0: undefined symbol: bpf_delete_batch`

here is my program :
`#!/usr/bin/python
from bcc import BPF
BPF(text="""
int kprobe__sys_clone(void *ctx){
	bpf_trace_printk("hello,world!\\n");
	return 0;
}
""").trace_print()
`

**Comment by jony-one** [comment]
Most likely this is due to mismatch between source based installation and package based installation, different versions of source installation, etc. Maybe you want to do a clean up and then a clean install?

https://github.com/iovisor/bcc/blob/master/INSTALL.md#ubuntu---binary

**Comment by wingchi-leung** [comment]
> Most likely this is due to mismatch between source based installation and package based installation, different versions of source installation, etc. Maybe you want to do a clean up and then a clean install?
> 
> https://github.com/iovisor/bcc/blob/master/INSTALL.md

thanks! I reinstall it and it work
