### ISSUE TITLE
tracepoint/net/netif_receive_skb data is empty

### ISSUE THREAD

**Issue by Benjamin-Yim** [iovisor/bcc#3532]
i by trace netif_receive_skb  ,this data is empty ,help me review code ,find error.thanks
how to get sk_buff  data,
```c

SEC("tracepoint/net/netif_receive_skb")
int trace_netif_receive_skb(struct trace_event_raw_net_dev_template *ctx)
{
  struct sk_buff *skb = ctx->skbaddr;
  if (NULL != skb)
  {
    unsigned char *end = BPF_CORE_READ(skb, end);
    struct skb_shared_info *share_info = (struct skb_shared_info *)end;
    unsigned int len = BPF_CORE_READ(skb, len);
    unsigned int data_len = BPF_CORE_READ(skb, data_len);
    if (len > 110)
    {
      // print  len: 541,  data_len: 0, len-data_len:541
      bpf_printk("len: %d,  data_len: %d, len-data_len:%d \n", len, data_len, len - data_len);

      __u8 nr_frags;
      nr_frags = BPF_CORE_READ(share_info, nr_frags);
      bpf_printk("skb_frag_t nr_frags :%d \n", nr_frags); // this is  zero

      unsigned char *data;
      bpf_core_read_str(&data, sizeof(data), &skb->data);
      bpf_printk("skb data :%s \n", data);// this is empty 

      if (data_len > 0)
      {
        struct sk_buff *frag_list = BPF_CORE_READ(share_info, frag_list);
        bpf_core_read_str(&data, sizeof(data), &frag_list->data);
        bpf_printk("frag_list -> data: \n"); // this is empty 
      }
    }
  }

  return 0;
}
```

**Comment by chenhengqi** [comment]
I tried print data directly, same result.

I think `bpf_skb_pull_data` helper might help, you can have a try.

**Comment by jony-one** [comment]
@chenhengqi  
i run bpf_skb_pull_data case, print error :
```bash
last_idx 83 first_idx 77
regs=4 stack=0 before 82: (b7) r2 = 8
; err = bpf_skb_pull_data(skb, 50);
84: (bf) r1 = r6
85: (b7) r2 = 50
86: (85) call bpf_skb_pull_data#39
unknown func bpf_skb_pull_data#39
processed 82 insns (limit 1000000) max_states_per_insn 0 total_states 5 peak_states 5 mark_read 3
```

```bash
$ uname -r
5.8.0-59-generic
```

maybe compiler tools ?

**Comment by jony-one** [comment]
> @chenhengqi
> i run bpf_skb_pull_data case, print error :
> 
> ```shell
> last_idx 83 first_idx 77
> regs=4 stack=0 before 82: (b7) r2 = 8
> ; err = bpf_skb_pull_data(skb, 50);
> 84: (bf) r1 = r6
> 85: (b7) r2 = 50
> 86: (85) call bpf_skb_pull_data#39
> unknown func bpf_skb_pull_data#39
> processed 82 insns (limit 1000000) max_states_per_insn 0 total_states 5 peak_states 5 mark_read 3
> ```
> 
> ```shell
> $ uname -r
> 5.8.0-59-generic
> ```
> 
> maybe compiler tools ?

SEC("tracepoint/net/netif_receive_skb")
int trace_netif_receive_skb(struct trace_event_raw_net_dev_template *ctx)
{
  struct sk_buff *skb = ctx->skbaddr;
  if (NULL != skb)
  {
    unsigned char *end = BPF_CORE_READ(skb, end);
    struct skb_shared_info *share_info = (struct skb_shared_info *)end;
    unsigned int len = BPF_CORE_READ(skb, len);
    unsigned int data_len = BPF_CORE_READ(skb, data_len);
    if (len > 110)
    {
      // print  len: 541,  data_len: 0, len-data_len:541
      bpf_printk("len: %d,  data_len: %d, len-data_len:%d \n", len, data_len, len - data_len);

      __u8 nr_frags;
      nr_frags = BPF_CORE_READ(share_info, nr_frags);
      bpf_printk("skb_frag_t nr_frags :%d \n", nr_frags); // this is  zero

      unsigned char *data;
      bpf_core_read_str(&data, sizeof(data), &skb->data);
      bpf_printk("skb data :%s \n", data);// this is empty 
      //# this is not found .....
      bpf_skb_pull_data(skb,0);
      
      if (data_len > 0)
      {
        struct sk_buff *frag_list = BPF_CORE_READ(share_info, frag_list);
        bpf_core_read_str(&data, sizeof(data), &frag_list->data);
        bpf_printk("frag_list -> data: \n"); // this is empty 
      }
    }
  }

  return 0;
}

**Comment by jony-one** [comment]
```c
static const struct bpf_func_proto *
tc_cls_act_func_proto(enum bpf_func_id func_id, const struct bpf_prog *prog)
{
	switch (func_id) {
	case BPF_FUNC_skb_store_bytes:
		return &bpf_skb_store_bytes_proto;
	case BPF_FUNC_skb_load_bytes:
		return &bpf_skb_load_bytes_proto;
	case BPF_FUNC_skb_load_bytes_relative:
		return &bpf_skb_load_bytes_relative_proto;
	case BPF_FUNC_skb_pull_data:
		return &bpf_skb_pull_data_proto;
	case BPF_FUNC_csum_diff:
		return &bpf_csum_diff_proto;
```
so the `bpf_skb_pull_data` support tc ebp ?
