### ISSUE TITLE
BUG: print wrong value using "%p"

### ISSUE THREAD

**Issue by trialley** [iovisor/bcc#3549]
Hi!
I want use python script print some address value. 
The output is wrong when I use "%p", and "%lx" will give the right output.

It looks like this:
bpf_trace_printk("lx\\n",args->ip);        print:  ffffffff84c711fa
bpf_trace_printk("%p\\n",args->ip);     print: 00000000fda14ca0

Is this a bug? Maybe I can help fix it.(or feature ?🤔)

**Comment by chenhengqi** [comment]
Only a subset of format specifiers are supported by BPF.

**Comment by trialley** [comment]
> Only a subset of format specifiers are supported by BPF.

I guess bpftrace supports "%p" and BPF doesn't .
Thanks!

**Comment by anakryiko** [comment]
Kernel's printk() (used internally by bpf_trace_printk()) "obfuscates" pointer values to prevent leaking inner kernel information, which is what happens here. %lx just prints the integer value of the pointer, avoiding this issue.
