### ISSUE TITLE
Expected behavior of USDT Context Overload

### ISSUE THREAD

**Issue by jordalgo** [iovisor/bcc#3550]
For this USDT Context Overload: https://github.com/iovisor/bcc/blob/master/src/cc/usdt/usdt.cc#L413
```
Context::Context(int pid, const std::string &bin_path,
                 uint8_t mod_match_inode_only)
```
Not sure what the expected behavior is for this but in the code it looks like we attach the probe to all processes with the same file path and then only check if the exe path for the passed in pid is not empty. I guess I expected the probe to only attach to the process where both the bin path and the pid match.

**Comment by yonghong-song** [comment]
@davemarchevsky could you help take a look?

**Comment by davemarchevsky** [comment]
@jordalgo and I talked offline as we work at the same company :). Essentially his confusion stems from two things:
* `Context`'s constructor that takes `(pid, bin_path)` doesn't look like it's using `pid` to limit what probes it's adding
* It's unclear to end users why `BPF::attach_usdt` takes a `pid` when `BPF::init_usdt`, which calls `Context` constructors under the hood, also optionally takes a `pid`. 

Some documentation would clear these up, need to see what's changed in USDT code in past year or two before adding.

**Comment by jordalgo** [comment]
@davemarchevsky Great summary. It would be nice if this init variant used the pid to filter USDT initialization so users didn't have to also remember to pass the pid in `attach_usdt` AND `detach_usdt` but I understand that might be a breaking change at this point.
