### ISSUE TITLE
last insn is not an exit or jmp / processed 0 insns..

### ISSUE THREAD

**Issue by wingchi-leung** [iovisor/bcc#3558]
I am trying to get task_struct via pid using the kenel function `find_get_task_by_vpid` or `find_task_by_vpid` , by I get  the error follow. I can't understand what is wrong.  
I test the function  by using `kprobe`  upon and it work. 

```
bpf: Failed to load program: Invalid argument
last insn is not an exit or jmp
processed 0 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0

Traceback (most recent call last):
  File "./newTask.py", line 64, in <module>
    b.attach_kprobe(event="wake_up_new_task", fn_name="do_trace")
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 799, in attach_kprobe
    fn = self.load_func(fn_name, BPF.KPROBE)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 499, in load_func
    raise Exception("Failed to load BPF program %s: %s" %
Exception: Failed to load BPF program b'do_trace': Invalid argument
```

here is how I use:
```
    # include <linux/sched.h>
    # include <linux/string.h>
    # include <uapi/linux/ptrace.h>
    #include  <linux/pid.h>
...
    struct task_struct *target = find_get_task_by_vpid(PID) ;
...
``` 

thank a lot for any ideas.

**Comment by chenhengqi** [comment]
Though BPF allows [calling kernel functions](https://patchwork.kernel.org/project/netdevbpf/cover/20210325015124.1543397-1-kafai@fb.com/#24076855), don't think `find_get_task_by_vpid` is in the allowlist.

**Comment by yonghong-song** [comment]
@chenhengqi is right. these two functions cannot be called in the bpf program.

**Comment by wingchi-leung** [comment]
@yonghong-song  @chenhengqi  oh, my falut . I have two more questions: 1. DO you konw how can I get `task_struct`   by pid number without these function ? 2.Is there  any guide references you read that tell you BPF can't call the function? I want to do some reading too.  thank a lot again!
