### ISSUE TITLE
creating a standlone excutacle script

### ISSUE THREAD

**Issue by Dinakaranevil** [iovisor/bcc#3563]
- how can i create a standalone executable script for filetop its a python script i have modified few functionalities 
- i tried with pyinstaller to create an executable but it fails to do it it has issues with its dependencies 
what is the best way to do it or create an executable or package so its for implementing the process for other machines

**Comment by chenhengqi** [comment]
We have a libbpf filetop tool [here](https://github.com/iovisor/bcc/blob/master/libbpf-tools/filetop.c). It compiles to a single binary.

**Comment by Dinakaranevil** [comment]
how to execute this script

**Comment by chenhengqi** [comment]
Simply run `make` inside libbpf-tools directory, it will create a filetop binary.

**Comment by Dinakaranevil** [comment]
[sample.log](https://github.com/iovisor/bcc/files/6966182/sample.log)
i am getting a couple of errors i wasnt able to install using make inside libbpf-tools  

- os is ubuntu 18.04
- installed bcc using and built from source[link](https://github.com/iovisor/bcc/blob/master/INSTALL.md#ubuntu---source)

**Comment by chenhengqi** [comment]
You need to update your clang installation.

**Comment by Dinakaranevil** [comment]
even after updating i have the same issue

**Comment by Dinakaranevil** [comment]
i will take the compilation error as a seperate issue
