### ISSUE TITLE
How do I access thread local storage in BPF programs ?

### ISSUE THREAD

**Issue by Masterlvng** [iovisor/bcc#3575]
Hi all,
I want to access thread local storage,  for example the "g struct" in golang store in tls.
How can I do that? Thank you :)

**Comment by chenhengqi** [comment]
I think it is not possible to access thread local storage in BPF programs, but you can use uprobe to trace a function which has a g struct argument.

**Comment by Masterlvng** [comment]
Thank you @chenhengqi

**Comment by jazevedo620** [comment]
In case anyone stumbles across this, it *is* possible to access thread local storage in eBPF programs; Delve has an example implementation: https://github.com/go-delve/delve/pull/2654.

**Comment by chenhengqi** [comment]
Thanks for the information, will look into this later.

**Comment by yonghong-song** [comment]
The bcc example (bcc/examples/cpp/pyperf) also illustrates a way to access the tls data,
```
#if __x86_64__
// thread_struct->fs was renamed to fsbase in
// https://github.com/torvalds/linux/commit/296f781a4b7801ad9c1c0219f9e87b6c25e196fe
// so depending on kernel version, we need to account for that
#if LINUX_VERSION_CODE < KERNEL_VERSION(4, 7, 0)
  void* tls_base = (void*)task->thread.fs;
#else
  void* tls_base = (void*)task->thread.fsbase;
#endif
#elif __aarch64__
  void* tls_base = (void*)task->thread.tp_value;
#else
#error "Unsupported platform"
#endif
```
