### ISSUE TITLE
Multiple libbpf.c.o in libbcc_bpf.a

### ISSUE THREAD

**Issue by vt-alt** [iovisor/bcc#3582]
While building the package for ALT Linux we noticed that there are two different `libbpf.c.o` objects in `libbcc_bpf.a`.

```
builder@x86_64:~/RPM/BUILD/bcc-0.19.0$ ar tv ./x86_64-alt-linux/src/cc/libbcc_bpf.a | grep libbpf.c.o
rw-r--r-- 0/0 119400 Jan  1 00:00 1970 libbpf.c.o
rw-r--r-- 0/0 760500 Jan  1 00:00 1970 libbpf.c.o
```
What is the point of having two partly same objects in the static library?
Why two different `libbpf.c.o` are created?

There is build log | grep libbpf.c.o | grep static:
* [  3%] Building C object src/cc/CMakeFiles/bpf-static.dir/libbpf.c.o
* cd /usr/src/RPM/BUILD/bcc-0.19.0/x86_64-alt-linux/src/cc && /usr/bin/clang  -I/usr/lib/llvm-12.0/include/../tools/clang/include -I/usr/src/RPM/BUILD/bcc-0.19.0/src -I/usr/src/RPM/BUILD/bcc-0.19.0/x86_64-alt-linux/src -I/usr/src/RPM/BUILD/bcc-0.19.0/x86_64-alt-linux/src/cc -I/usr/src/RPM/BUILD/bcc-0.19.0/src/cc -I/usr/src/RPM/BUILD/bcc-0.19.0/x86_64-alt-linux/src/cc/frontends/b -I/usr/src/RPM/BUILD/bcc-0.19.0/src/cc/frontends/b -I/usr/src/RPM/BUILD/bcc-0.19.0/src/cc/frontends/clang -I/usr/lib/llvm-12.0/include -I/usr/src/RPM/BUILD/bcc-0.19.0/src/cc/libbpf/include -I/usr/src/RPM/BUILD/bcc-0.19.0/src/cc/libbpf/include/uapi -pipe -grecord-gcc-switches -Wall -g -O2 -flto -Wall -fPIC -Wno-unused-result -O2 -g -DNDEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -MD -MT src/cc/CMakeFiles/bpf-static.dir/libbpf.c.o -MF CMakeFiles/bpf-static.dir/libbpf.c.o.d -o CMakeFiles/bpf-static.dir/libbpf.c.o -c /usr/src/RPM/BUILD/bcc-0.19.0/src/cc/libbpf.c
* [ 25%] Building C object src/cc/CMakeFiles/bpf-static.dir/libbpf/src/libbpf.c.o
* cd /usr/src/RPM/BUILD/bcc-0.19.0/x86_64-alt-linux/src/cc && /usr/bin/clang  -I/usr/lib/llvm-12.0/include/../tools/clang/include -I/usr/src/RPM/BUILD/bcc-0.19.0/src -I/usr/src/RPM/BUILD/bcc-0.19.0/x86_64-alt-linux/src -I/usr/src/RPM/BUILD/bcc-0.19.0/x86_64-alt-linux/src/cc -I/usr/src/RPM/BUILD/bcc-0.19.0/src/cc -I/usr/src/RPM/BUILD/bcc-0.19.0/x86_64-alt-linux/src/cc/frontends/b -I/usr/src/RPM/BUILD/bcc-0.19.0/src/cc/frontends/b -I/usr/src/RPM/BUILD/bcc-0.19.0/src/cc/frontends/clang -I/usr/lib/llvm-12.0/include -I/usr/src/RPM/BUILD/bcc-0.19.0/src/cc/libbpf/include -I/usr/src/RPM/BUILD/bcc-0.19.0/src/cc/libbpf/include/uapi -pipe -grecord-gcc-switches -Wall -g -O2 -flto -Wall -fPIC -Wno-unused-result -O2 -g -DNDEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -MD -MT src/cc/CMakeFiles/bpf-static.dir/libbpf/src/libbpf.c.o -MF CMakeFiles/bpf-static.dir/libbpf/src/libbpf.c.o.d -o CMakeFiles/bpf-static.dir/libbpf/src/libbpf.c.o -c /usr/src/RPM/BUILD/bcc-0.19.0/src/cc/libbpf/src/libbpf.c
* /usr/bin/llvm-ar qc libbcc_bpf.a CMakeFiles/bpf-static.dir/libbpf.c.o CMakeFiles/bpf-static.dir/perf_reader.c.o CMakeFiles/bpf-static.dir/libbpf/src/bpf.c.o CMakeFiles/bpf-static.dir/libbpf/src/bpf_prog_linfo.c.o CMakeFiles/bpf-static.dir/libbpf/src/btf.c.o CMakeFiles/bpf-static.dir/libbpf/src/btf_dump.c.o CMakeFiles/bpf-static.dir/libbpf/src/hashmap.c.o CMakeFiles/bpf-static.dir/libbpf/src/libbpf.c.o CMakeFiles/bpf-static.dir/libbpf/src/libbpf_errno.c.o CMakeFiles/bpf-static.dir/libbpf/src/libbpf_probes.c.o CMakeFiles/bpf-static.dir/libbpf/src/netlink.c.o CMakeFiles/bpf-static.dir/libbpf/src/nlattr.c.o CMakeFiles/bpf-static.dir/libbpf/src/ringbuf.c.o CMakeFiles/bpf-static.dir/libbpf/src/str_error.c.o CMakeFiles/bpf-static.dir/libbpf/src/xsk.c.o

**Comment by anakryiko** [comment]
BCC has its own src/cc/libbpf.c file, which is not really a libbpf, but rather some low-level internal BPF-related  BCC-specific code. I agree it would make sense to rename it to something different, but does it cause any issues in the first place?

**Comment by vt-alt** [comment]
We wanted to adopt [this Fedora's script to convert LLVM IR bitcode objects into ELF objects](https://src.fedoraproject.org/rpms/redhat-rpm-config/blob/rawhide/f/brp-llvm-compile-lto-elf). but It fails to do the job, because it extracts all files from `.a` archive, then iterate over the extracted files, and pack them back. When some objects have the same filenames process misses converting one copy of it, so that one object in the archive remains unconverted from bitcode. (One copy is overwritten on extraction and one copy remains non-replaced with `ar r`.

After some internal discussion, we decided not to implement this feature at all. So, we can close this issue.
