### ISSUE TITLE
Not able to Execute the executable that was created using lib_bpf filetop example

### ISSUE THREAD

**Issue by Dinakaranevil** [iovisor/bcc#3583]
So i tried installing bcc from source for ubuntu 20.04 after installing i went i lib_bpf folder and tried to make it created a bunch of executables when i try to run those executables i am getting this error 

libbpf: failed to find valid kernel BTF
libbpf: Error loading vmlinux BTF: -3
libbpf: failed to load object 'filetop_bpf'
libbpf: failed to load BPF skeleton 'filetop_bpf': -3
failed to load BPF object: -3

Installed pahole with version v1.17
kernel version 5.8.0-1041-aws
opeating system ubuntu 20.04

Tried to change these flags as well 
CONFIG_DEBUG_INFO_BTF=y
CONFIG_DEBUG_INFO=y
 
Another thing i could observe is when i try to sudo make 

 INSTALL  bpf.h libbpf.h btf.h libbpf_common.h libbpf_legacy.h xsk.h bpf_helpers.h bpf_helper_defs.h bpf_tracing.h bpf_endian.h bpf_core_read.h skel_internal.h
  INSTALL  libbpf.pc
  INSTALL  libbpf.a

**Comment by chenhengqi** [comment]
See the comments in this PR https://github.com/iovisor/bcc/pull/3577
