### ISSUE TITLE
 get task_struct via pid 

### ISSUE THREAD

**Issue by wingchi-leung** [iovisor/bcc#3595]
I am trying to get task_struct via pid using the kenel function` find_get_task_by_vpid `or `find_task_by_vpid ` , but BPF is not allow to call this function. 

so how can I get it by bcc without using these function?

**Comment by yonghong-song** [comment]
There is no helper in bpf to get task_struct given a pid.  What is your use case? If it possible to filter based on pid?
Getting task struct given a arbitrary pid inside bpf program has a race with potential that (1). pid has been recycled and it is not what you want, (2). process with pid may be existing, making fields not accurate etc.

**Comment by wingchi-leung** [comment]
I am tracing every new born process in the system and try to find the one that belong to  a given father process. 
So I want to get `task_struct`   and using `children` or `parent` to  travel the list of  process family 
What's more, the helper function `list_entry` is also not allow to call, so I am really get stuck , any ideas for me will be appreciated .

**Comment by wingchi-leung** [comment]
I find a bcc's way to figure the probelm ,thanking for answer my question

**Comment by wingchi-leung** [comment]
I find an  another way to figure my problem, thank for answer my question ~

**Comment by wingchi-leung** [comment]
I find an another way to solve my problem, thank for answer my question ~
