### ISSUE TITLE
tools/opensnoop.py: fails with spaces in file names

### ISSUE THREAD

**Issue by chneukirchen** [iovisor/bcc#361]
opensnoop uses a native protocol to communicate filename and return code of open to the python script, which is then parsed by `(filename, ret_s) = msg.split(" ")`.  This breaks when a file name contains a space.

As a simple fix, one could use `%d %s\\n` and then `(ret_s, filename) = msg.split(" ", 1)`.

**Comment by brendangregg** [comment]
Thanks, I've submitted a fix for now. Future versions of these tools will use a different means to pass data back (bpf_perf_event_output).

**Comment by chneukirchen** [comment]
This will also avoid the `trace_printk` warning in dmesg then? If so, +1.

**Comment by brendangregg** [comment]
Was fixed, closing ticket. Still needs future work (bpf_perf_event_output).
