### ISSUE TITLE
Possible bug in kretprobe

### ISSUE THREAD

**Issue by ghostpepper108** [iovisor/bcc#3621]
I am using kernel 5.10.0. The function _int syscall__openat(struct pt_regs *ctx, int dfd, const char __user *filename, int flags)_ does not return the value in filename when kretprobe is used, but returns when kprobe is used.

What could be the issue?

Thanks

**Comment by yonghong-song** [comment]
For kretprobe, you only get return value. Since your kernel is recent enough, maybe you want to use KRETFUNC_PROBE which preserves input parameters?

**Comment by yonghong-song** [comment]
If you use KRETFUNC_PROTO and want to get `filename`, the best is to pick a non-syscall entry point which has `filename` as for 5.10 syscall (__x64_sys_openat) the argument is `struct pt_regs *regs)` and there is no `filename` there.

**Comment by ghostpepper108** [comment]
Thank you.
