### ISSUE TITLE
update memleak, from BCC to CO-RE

### ISSUE THREAD

**Issue by ferodevil** [iovisor/bcc#3631]
how to switch from BCC to CO-RE？mainly for uprobe，as the project list below, do we need parse ELF to calculate specific function？Is there an easier way to do this？

https://github.com/libbpf/libbpf-bootstrap/blob/master/examples/c/uprobe.c

**Comment by chenhengqi** [comment]
Right. Please refer to following tools:

* https://github.com/iovisor/bcc/blob/master/libbpf-tools/gethostlatency.c
* https://github.com/iovisor/bcc/blob/master/libbpf-tools/funclatency.c

We have some helper functions to do that.

**Comment by ferodevil** [comment]
ok，thanks
