### ISSUE TITLE
bpf_get_current_ppid()

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#364]
(Before I forget) I've wanted the PPID, and don't necessarily have the task_struct to get it. Eg, execsnoop prints new processes, where it's pretty helpful to know who the PPID is. (I guess I can trace fork() as well to get it, but PPID should be a common need.)

**Comment by goldshtn** [comment]
Should be possible to address this once we have the `task_struct` from #220.

**Comment by brendangregg** [comment]
Right; I'll close this ticket since #220 will address it.
