### ISSUE TITLE
Tools broken by the renaming of the state field of task_struct

### ISSUE THREAD

**Issue by jeromemarchand** [iovisor/bcc#3658]
There has been some cleanup of the state field of task_struct and to ensure all places has been converted, the field has been rename __state (see commit 2f064a59a1 ("sched: Change task_struct::state"). Several tools are affected by this change:
- runqlat
- runqslower
- offcputime
- offwaketime
- criticalstat

**Comment by chenhengqi** [comment]
Create a new PR https://github.com/iovisor/bcc/pull/3659 to fix the corresponding libbpf-tools.

**Comment by hygoni** [comment]
suffering same issue here on linux v5.15-rc7.
me too looking forward to the patch!
