### ISSUE TITLE
runqlat.py fails to find include file sched.h (enqueue_task)

### ISSUE THREAD

**Issue by mcaleavya** [iovisor/bcc#367]
root@henky:/var/tmp/bcc/tools# ./runqlat.py 
<bcc-memory-buffer>:3:10: fatal error: 'kernel/sched/sched.h' file not found
#include "kernel/sched/sched.h" 

I worked around this by installing the linux source and linking to the header, should there be a dependancy on this?

**Comment by drzaeus77** [comment]
I think that's actually a false dependency.

1. `struct rq *rq` isn't actually dereferenced in the bpf prog, so it can either be forward declared or defined as a `void *` instead
2. `struct task_struct *p` is available in `<linux/sched.h>`, which should work without any linux source being made available

**Comment by drzaeus77** [comment]
Looks like all of these tools need to start being included in test infrastructure!
