### ISSUE TITLE
Not able to debug lsm hook on tracepipe

### ISSUE THREAD

**Issue by Dinakaranevil** [iovisor/bcc#3697]
```

SEC("lsm/bprm_check_security")
int BPF_PROG(security_inode_getattr,struct linux_binprm *bprm)
{
bpf_printk("entered lsm hook\n");
return 0;
}
```
I am not able to this print message on trace pipe
After reading some discussion 
I understood that there should be bpf flag in the below statement if that's the reason how to enable it please guide me on it
```
CONFIG_LSM="lockdown,yama,integrity,apparmor"
```
kernel version:- 5.13.0-20-generic
os:-ubuntu 22.04

**Comment by yonghong-song** [comment]
Yes, as you already discovered. Your system config should have 'bpf' in CONFIG_LSM.
There is a kernel boot parameter `lsm=...`. Not sure whether it works or not, maybe you can try to tweak the boot command line in ubuntu 22.04.
