### ISSUE TITLE
Undefined behavior in Probe::finalize_locations

### ISSUE THREAD

**Issue by eduardo-elizondo** [iovisor/bcc#3701]
Currently, the implementation of `Probe::finalize_locations` uses `std::sort` with a lambda that does not guarantee strict weak ordering which leads to undefined behavior.

This should be replaced by a lambda that satisfies the requirements of the sort comparator.

Here's a proposed solution for this issue: https://github.com/iovisor/bcc/pull/3700

**Comment by yonghong-song** [comment]
Thanks, #3700 just got merged.
