### ISSUE TITLE
batch method not in libbpf.h

### ISSUE THREAD

**Issue by hsqStephenZhang** [iovisor/bcc#3709]
i wonder why bpf_delete_batch, bpf_lookup_batch are not included in libbpf.h, i prevent rust's bindgen from bind these methods because bindgen only include header files

**Comment by egobillot** [comment]
Hi,
I have got the answer : I probably forget it. It was 6 month ago, so I do not remember correctly but yes it looks like I forget to add it.
Sorry.

**Comment by yonghong-song** [comment]
@egobillot could you send a patch for this? Thanks!

**Comment by hsqStephenZhang** [comment]
i just add some [patch](https://github.com/iovisor/bcc/pull/3711), hope it's useful
