### ISSUE TITLE
repo.iovisor.org certificate expired

### ISSUE THREAD

**Issue by igorwwwwwwwwwwwwwwwwwwww** [iovisor/bcc#3724]
We just started seeing apt failures on our fleet due to the `repo.iovisor.org` certificate expiring.

Reproducer:

```bash
➜  ~ curl -v https://repo.iovisor.org/apt/xenial

*   Trying 104.199.116.191...
* TCP_NODELAY set
* Connected to repo.iovisor.org (104.199.116.191) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, certificate expired (557):
* SSL certificate problem: certificate has expired
* Closing connection 0

curl: (60) SSL certificate problem: certificate has expired
```

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
We ran into this same issue 3 months ago: https://gitlab.com/gitlab-com/gl-infra/production/-/issues/5430#note_663058873.

**Comment by yonghong-song** [comment]
@drzaeus77 could you help take a look?

**Comment by sboyd-m** [comment]
They are using a letsencrypt cert, but clearly are not renewing it automatically, which is annoying. Also, the more formal contact-us page on their website is hilariously broken, as the text emails are not the same as the links underneath them. It is very difficult to not scream.

**Comment by xuyixin1996** [comment]
encounter the same issue.

can verify via the below command.

```
root# echo | openssl s_client -servername repo.iovisor.org -connect repo.iovisor.org:443
CONNECTED(00000003)
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = repo.iovisor.org
verify error:num=10:certificate has expired
notAfter=Nov 25 14:03:41 2021 GMT <-----
verify return:1
depth=0 CN = repo.iovisor.org
notAfter=Nov 25 14:03:41 2021 GMT <-----
verify return:1
```

**Comment by xuyixin1996** [comment]
As mentioned in https://github.com/iovisor/bcc/blob/master/INSTALL.md, they suggest to build the bcc from source code. Which works for me in my case.

**Comment by lichenglife** [comment]
> We ran into this same issue 3 months ago: https://gitlab.com/gitlab-com/gl-infra/production/-/issues/5430#note_663058873.



> We ran into this same issue 3 months ago: https://gitlab.com/gitlab-com/gl-infra/production/-/issues/5430#note_663058873.

Does this mean that the update will be available in three months? Just like the picture says expires on December 25, 2021. Does everyone have an alternative?

**Comment by sboyd-m** [comment]
Letsencryp certificates only last 3 months, so it means whoever is supposed to renew this is a lazy asshat and has done this multiple times

**Comment by shadyabhi** [comment]
Damn, still not renewed. This is one thing that can definitely be automated. Is there a way I can get involved to automate this for the project?

```
shadyabhi@nuc10i7fnh:~/Playground/kubernetes$ echo | openssl s_client -connect repo.iovisor.org:443 2>&1| openssl x509 -noout -dates -subject -issuer
notBefore=Aug 27 14:03:42 2021 GMT
notAfter=Nov 25 14:03:41 2021 GMT
subject=CN = repo.iovisor.org
issuer=C = US, O = Let's Encrypt, CN = R3
shadyabhi@nuc10i7fnh:~/Playground/kubernetes$
```

**Comment by iammattcoleman** [comment]
Echoing @shadyabhi's sentiment - can I help automate this? `certbot` is supposed to enable hands-off certificate rotation. Given this repo's importance, it should really have a valid certificate.

**Comment by yonghong-song** [comment]
@iammattcoleman @shadyabhi , @drzaeus77 has helped restart the certificate bot. Could you check whether it works or not?

**Comment by iammattcoleman** [comment]
Yes, the certificate is valid now.

**Comment by iammattcoleman** [comment]
I suspect that, like me, a lot of people may have glossed over the warning in INSTALL.md that says the Ubuntu repositories are completely outdated. Fixing this issue may lead to a lot of new issues asking where current packages are. Sadly, the only option for Ubuntu at the moment is to build from source.

**Comment by PromiseChan** [comment]
The apt-key in  INSTALL.md does not work in my ubuntu, 
I just  ignore the cert for that domain, using [[yonghong-song](https://github.com/yonghong-song) 's](https://github.com/iovisor/bcc/issues/3724#issuecomment-1021618465) command
