### ISSUE TITLE
Is there an API in BCC to print the byte code of a particular probe?

### ISSUE THREAD

**Issue by yzhao1012** [iovisor/bcc#3738]
Let me know if you need more information. Below are what we went through so far.

# Background
We use BCC to deploy uprobes. We encountered a case where (seemingly) the compiled BPF byte code couldn't pass BPF verified when being deployed. We found a work around by inserting inlined assembly code into C code to disable Clang optimization. As shown below:
```
  ...
  size_t data_buf_size_minus_1 = data_buf_size - 1;
  // This is the added assmebly to prevent Clang from optimizing away the variable.
  asm volatile("" : "+r"(data_buf_size_minus_1) :);
  data_buf_size = data_buf_size_minus_1 + 1;
  ...
```

We want to investigate and gain more insights from this case. One way is to examine the probe's byte code with and without this assembly code, and see what's being changed.

# Problem
We tried to use set flags to 0x2 in BPF::BPF(flags, ...) to print the BPF byte code. But it prints too much code. And it's not clear which part of the byte code corresponds to a specific probe.

We also tried to add a `set_flag(flags) { flags_ = flags; }` API in BPF, and call it right before calling the `BPF::attach_urpbe()` API as below:
```
BPF bpf;
bpf.set_flag(0x2);
bpf.attach_uprobe(...);
```
This seems working. We saw that the amount of bpf byte code printed is much less than those from setting flags in BPF::BPF().

# Another problem
Another problem is that when the bpf verifier failed, it does not print the whole byte code of the probe, only the portion from the beginning until the part that triggers the verification failure.

# Questions
* Is the `BPF::set_flag()` trick correctly print out the byte code as above shown?
* Is there a way to print the whole bpf code even if the deployment failed?

**Comment by yonghong-song** [comment]
@yzhao1012 thanks for reporting the issue. To answer your question first,
> Is the BPF::set_flag() trick correctly print out the byte code as above shown?
Yes, flag 0x2 corresponds to bpf program load log_level=1 which will print out the verification logs.
> Is there a way to print the whole bpf code even if the deployment failed?
The verifier will not print out the whole bpf code if verification failed. But you can use flag 0x8 (or flag 0xa: for 0x2 and 0x8) to print out the bpf code at source level.

I will be extremely curious about what the problem or verification failure you encountered and how the below workaround can fix it.
```
  ...
  size_t data_buf_size_minus_1 = data_buf_size - 1;
  // This is the added assmebly to prevent Clang from optimizing away the variable.
  asm volatile("" : "+r"(data_buf_size_minus_1) :);
  data_buf_size = data_buf_size_minus_1 + 1;
  ...
```
If you have a reproducible case, I can also take a look. it would be good if we can enhance llvm and/or kernel to resolve this failure.

**Comment by yzhao1012** [comment]
Thanks Yonghong!

I'll try to create a sample code for reproducing.

The source code is at https://github.com/pixie-io/pixie/blob/4f83a214756a8ca1834f52ea0d4c7a9627acffb2/src/stirling/source_connectors/socket_tracer/bcc_bpf/go_http2_trace.c#L797

There is a lot of layers on top of BCC, so I dont think it makes sense to read that directly.

**Comment by yonghong-song** [comment]
@yzhao1012 Thanks. So it is for kernel 4.14. The newer kernel should be okay.
In 4.14, we have
```
static const struct bpf_func_proto bpf_probe_read_proto = {
        .func           = bpf_probe_read,
        .gpl_only       = true,
        .ret_type       = RET_INTEGER,
        .arg1_type      = ARG_PTR_TO_UNINIT_MEM,
        .arg2_type      = ARG_CONST_SIZE,
        .arg3_type      = ARG_ANYTHING,
};
```
The size is ARG_CONST_SIZE which cannot be 0.

In 4.19, we have
```
static const struct bpf_func_proto bpf_probe_read_proto = {
        .func           = bpf_probe_read,
        .gpl_only       = true,
        .ret_type       = RET_INTEGER,
        .arg1_type      = ARG_PTR_TO_UNINIT_MEM,
        .arg2_type      = ARG_CONST_SIZE_OR_ZERO,
        .arg3_type      = ARG_ANYTHING,
};
```
size 0 is permitted.
