### ISSUE TITLE
tcpconnect vs tcpconnlat

### ISSUE THREAD

**Issue by yugeshk** [iovisor/bcc#3745]
Hi,

Looking at the `.bpf.c` code for `tcpconnect` and `tcpconnlat` I notice that tcpconnect uses `kprobe / kretprobe` on `tcp_v4_connect` while `tcpconnlat` uses `fentry/tcp_v4_connect` and `fentry/tcp_rcv_state_process` (with a return 0, if the state was not `TCP_SYN_SENT`). I do not understand why that is the case. Even for tcpconnlat because of the check for `TCP_SYN_SENT`, using the same thing that `tcpconnect` did should also have been fine because the `connect()` call is blocking till it gets a response (returns on SYN ACK).

It would be great if you can help me understand this.

Thanks!

**Comment by yonghong-song** [comment]
This is some explanation. tcpconnect and tcpconnlat initially implementation tries to mimic what bcc/tools does, which is using kprobes. tcpconnect is implemented early so it uses kprobe. But later when implementing tcpconnlat it is decided to use fentry, which will not work for some earlier version of kernel, but it is considered fine.

Yes, tcpconnect can use fentry as well. The difference is just a historic artifact.

**Comment by chenhengqi** [comment]
`tcpconnect` is used to trace active TCP connections, as the comment says:

> All connection attempts are traced, even if they ultimately fail.

So using either `kprobe/kretprobe` or `fentry/fexit` on `tcp_v4_connect` is sufficient.

As for `tcpconnlat`, it's trying to measure the latency between `TCP_SYN_SENT` and `TCP_ESTABLISHED`(on receiving SYN/ACK)/`TCP_CLOSE`(on receiving RST). So it choose `tcp_rcv_state_process` as a tracing target.

In both cases, either `kprobe/kretprobe` or `fentry/fexit` is OK.

**Comment by yugeshk** [comment]
Ok, this answers my question, thanks! :)
