### ISSUE TITLE
pid as a builtin

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#375]
```
u32 pid = bpf_get_current_pid_tgid();
```

This is so common that I wonder if we can make "pid" a builtin, such that if "pid" is used (and pid is not declared otherwise), the above line is automatically inserted at the start of the function, instead of letting it error with "pid undefined".

**Comment by 4ast** [comment]
I think that's too tricky. We already have non-trivial mix where we do implicit probe_read.
imo the user should add such line explicitly.

**Comment by brendangregg** [comment]
ok

**Comment by goldshtn** [comment]
I think this can be closed?

**Comment by brendangregg** [comment]
Ok, I'll close it. I'll rationalize it as I think bcc is aiming to be an explicit language, so you can see clearly what is going on, even if that makes it more verbose.
