### ISSUE TITLE
Module error | ImportError: cannot import name BPFAttachType

### ISSUE THREAD

**Issue by wolf1892** [iovisor/bcc#3767]
`from bcc import BPF, BPFAttachType, lib`

Throws error BPFAttachType not found, referenced used from /examples/networking/sockmap.py

Env: Ubuntu(4.15.0-163-generic)

**Comment by chenhengqi** [comment]
What is your BCC version ?

**Comment by wolf1892** [comment]
Hope this is how one checks it...
```
>>> import bcc
>>> print bcc.__version__
0.10.0
```

**Comment by chenhengqi** [comment]
You need to update your BCC to recent releases.
