### ISSUE TITLE
filetop dev always 0

### ISSUE THREAD

**Issue by zhuanxuhit** [iovisor/bcc#3824]
in Linux version 4.14, i run filetop, and find 
```
struct info_t info = {
        .pid = pid,
        .inode = file->f_inode->i_ino,
        .dev = file->f_inode->i_rdev,
    };
```
dev always 0

**Comment by chenhengqi** [comment]
Maybe we should use `file->f_inode->i_sb->s_dev` instead.

**Comment by yonghong-song** [comment]
i_rdev is 0 if it’s not a character device or block device node in generic handling, it was then been customized for different file systems and it may be set to 0 or a real dev_t value depending on the file system.

s_dev is the block device of the underlying filesystem.

Maybe you could help debug a little bit to find which inode has i_rdev 0 and then use 'find <path> -inum <inode num>' to find what it is?

**Comment by chenhengqi** [comment]
According to `man 2 statx`, there are two different device IDs:
```
/* If this file represents a device, then the next two
    fields contain the ID of the device */
__u32 stx_rdev_major;  /* Major ID */
__u32 stx_rdev_minor;  /* Minor ID */

/* The next two fields contain the ID of the device
    containing the filesystem where the file resides */
__u32 stx_dev_major;   /* Major ID */
__u32 stx_dev_minor;   /* Minor ID */
```

The `rdev` is from device drivers' perspective, and is not zero when we stat a device file(special file, like `/dev/loop0`). The `rdev` is shown as `Device type` in `stat` output.

The `dev` is from filesystem's perspective and is shown as `Device` field in `stat` output.

https://github.com/torvalds/linux/blob/df0cc57e057f18e44dac8e6c18aba47ab53202f9/fs/stat.c#L46-L52

I think we should combine these two fields to uniquely identify a device on a running system.

**Comment by yonghong-song** [comment]
LGTM. Agree that 'dev' itself may not represent the special device like `/dev/loop0`. We need to add  `rdev` to the key as well to differentiate `/dev/loop0` and `/dev/loop1`.

**Comment by chenhengqi** [comment]
Thanks. Happy new year !
