### ISSUE TITLE
tutorial bcc python: `disksnoop.py` not working

### ISSUE THREAD

**Issue by irevoire** [iovisor/bcc#3825]
Hello,

I'm following the [tutorial bcc python](https://github.com/iovisor/bcc/blob/master/docs/tutorial_bcc_python_developer.md#lesson-6-disksnooppy) and when I try to execute the disksnooppy example I get this error:
```
/virtual/main.c:20:37: error: incomplete definition of type 'struct request'
                bpf_trace_printk("%d %x %d\n", req->__data_len,
                                               ~~~^
include/linux/blkdev.h:24:8: note: forward declaration of 'struct request'
struct request;
       ^
/virtual/main.c:21:10: error: incomplete definition of type 'struct request'
                    req->cmd_flags, delta / 1000);
                    ~~~^
include/linux/blkdev.h:24:8: note: forward declaration of 'struct request'
struct request;
       ^
2 errors generated.
Traceback (most recent call last):
  File "/root/bcc/./examples/tracing/disksnoop.py", line 20, in <module>
    b = BPF(text="""
  File "/usr/lib/python3.10/site-packages/bcc/__init__.py", line 479, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>
```

And the thing is, the only occurrence of `blkdev.h` on my computer is found in `/tmp/kheaders-5.16.1-arch1-1/include/linux/blkdev.h`.
And it effectively starts with a sequence of empty structs:
```C
# head -n 35 /tmp/kheaders-5.16.1-arch1-1/include/linux/blkdev.h
/* SPDX-License-Identifier: GPL-2.0 */
#ifndef _LINUX_BLKDEV_H
#define _LINUX_BLKDEV_H

#include <linux/sched.h>
#include <linux/genhd.h>
#include <linux/list.h>
#include <linux/llist.h>
#include <linux/minmax.h>
#include <linux/timer.h>
#include <linux/workqueue.h>
#include <linux/wait.h>
#include <linux/bio.h>
#include <linux/gfp.h>
#include <linux/rcupdate.h>
#include <linux/percpu-refcount.h>
#include <linux/blkzoned.h>
#include <linux/sbitmap.h>

struct module;
struct request_queue;
struct elevator_queue;
struct blk_trace;
struct request;
struct sg_io_hdr;
struct blkcg_gq;
struct blk_flush_queue;
struct kiocb;
struct pr_ops;
struct rq_qos;
struct blk_queue_stats;
struct blk_stat_callback;
struct blk_crypto_profile;
```

**Comment by chenhengqi** [comment]
You need `kernel-devel` or `kernel-headers` packages.

**Comment by PillTime** [comment]
> You need `kernel-devel` or `kernel-headers` packages.

I don't think this is the issue since I have the kernel headers and I get the same problem.
I think the tutorial is simply outdated, because `struct request` is no longer in `include/linux/blkdev.h`, and I don't think the function `blk_account_io_done` is traceable either because it is `static inline`d now.

[5.16.1](https://elixir.bootlin.com/linux/v5.16.1/source/block/blk.h#L353) vs [4.20.10](https://elixir.bootlin.com/linux/v4.20.10/source/block/blk-core.c#L2722)

**Comment by netedwardwu** [comment]
static inline is untraceable, maybe we should consider biosnoop way
https://github.com/iovisor/bcc/blob/master/tools/biosnoop.py#L173

**Comment by chenhengqi** [comment]
> > You need `kernel-devel` or `kernel-headers` packages.
> 
> I don't think this is the issue since I have the kernel headers and I get the same problem. I think the tutorial is simply outdated, because `struct request` is no longer in `include/linux/blkdev.h`, and I don't think the function `blk_account_io_done` is traceable either because it is `static inline`d now.
> 
> [5.16.1](https://elixir.bootlin.com/linux/v5.16.1/source/block/blk.h#L353) vs [4.20.10](https://elixir.bootlin.com/linux/v4.20.10/source/block/blk-core.c#L2722)

You are right. See #3869 and #3748.
