### ISSUE TITLE
Include instruction limit increase in https://github.com/iovisor/bcc/blob/master/docs/kernel-versions.md

### ISSUE THREAD

**Issue by yzhao1012** [iovisor/bcc#3846]
Was the instruction limit increased to 1 million in 5.2?
But that was not listed on the versions page.

**Comment by chenhengqi** [comment]
The limit bumps to 1M by the following commit in v5.2.

https://github.com/torvalds/linux/commit/c04c0d2b968ac45d6ef020316808ef6c82325a82

And the [document](https://www.kernel.org/doc/html/v5.3/bpf/bpf_design_QA.html#q-what-are-the-verifier-limits) says:

> The only way to know that the program is going to be accepted by the verifier is to try to load it.

**Comment by yonghong-song** [comment]
@yzhao1012 This 1 million insn limit is enforced in two different places: (1) the number of insns passed to the kernel must be <= 1M, and (2). the number of insns processed by the verifier must be <= 1M. Note that (1) is different from (2) as (1) may contain some dead code and the verifier actually will ignore *some* dead code. Feel free to provide a pull request to add an entry in the versions page for this information.
