### ISSUE TITLE
port kprobe

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#385]
A port of the useful kprobe tool. See:
https://github.com/brendangregg/perf-tools/blob/master/examples/kprobe_example.txt .

It deliberately follows the style of the kprobe interface: 
https://www.kernel.org/doc/Documentation/trace/kprobetrace.txt

The following commands should work:

1. ./kprobe p:do_sys_open
2. ./kprobe r:do_sys_open
3. ./kprobe 'r:do_sys_open $retval'
4. ./kprobe 'r:do_sys_open rval=$retval'
5. ./kprobe 'p:do_sys_open mode=%cx:u16'
6. ./kprobe 'p:do_sys_open filename=+0(%si):string'
7. ./kprobe -d 10 'p:do_sys_open filename=+0(%si):string' > out
8. ./kprobe -p 1696 'p:do_sys_open filename=+0(%si):string' 
9. ./kprobe 'p:do_sys_open filename=+0(%si):string' 'filename ~ "*stat"'
10. ./kprobe 'p:bio_alloc %ax %bx %cx %dx'
11. ./kprobe 'p:bio_alloc %ax:u32'
12. ./kprobe 'p:bio_alloc ax=%ax'
13. ./kprobe 'r:bio_alloc $retval'
14. ./kprobe -s 'p:tcp_init_cwnd'

(9) might be hard for now. The rest should be doable. If "+0(%si)" is too strange to port, then "*%si" might be suitable (when we know that we're going to s/%si/ctx->si/, so this becomes *ctx->si).

The output can be improved. I'd go with the columns: TIME(s), PID, COMM, FUNC, where FUNC == function name traced. If arguments are printed (most of these examples), and extra column ARGS is added.

With bcc, some advanced syntax should be possible, inspired by argdist:

15. ./kprobe 'p:do_sys_open(int dfd, const char __user *filename, int flags, umode_t mode) mode'
16. ./kprobe 'p:do_sys_open(int dfd, const char __user *filename, int flags, umode_t mode) filename:string'

**Comment by 4ast** [comment]
though I've used kprobe quite a bit, I found that syntax is impossible to remember.
I don't think we should follow it.

**Comment by brendangregg** [comment]
We can and should have much nicer tracers. eg, a "ktrace" tool.

The point of kprobe was a front-end to the syntax already in Linux: Documentation/trace/kprobetrace.txt

**Comment by goldshtn** [comment]
Maybe we can combine kprobe and uprobe into one tool? The code would be almost identical...

**Comment by brendangregg** [comment]
I'll file a separate ticket for a ktrace, or just "trace" for both user & kernel, and retire this ticket for now. Alexei has a point: it should use syntax that's as intuitive as possible to make it easier to remember.

I like the idea of a separate ktrace & utrace, but then I might have bias from studying Documentation/trace/kprobetrace.txt and Documentation/trace/uprobetracer.txt. It might be less intimidating as separate tools: you could tell an application developer to check out utrace_examples.txt, and it's all user-level stuff, and a kernel developer to check out ktrace_examples.txt, and it's all kernel-level stuff. If the code is so close, then one can be a symlink to the other.
