### ISSUE TITLE
tcpconnect with dns query option crashes in kernel 5.14 and above

### ISSUE THREAD

**Issue by kreddkrikk** [iovisor/bcc#3859]
Running the `tcpconnect` tool with the `-d` option causes a crash in kernel 5.14 and above. This is because of this line in the string `dns_bpf_text`:

``` 
   if (msghdr->msg_iter.type != ITER_IOVEC)
```

The `type` field in `struct iov_iter` was changed to `iter_type` in kernel 5.14. Replacing `type` with `iter_type` in the line above fixes the problem for me.

**Comment by chenhengqi** [comment]
Just opened #3860

**Comment by sebastianblunt** [comment]
This is failing for me on linux-hardened (5.16.17). It seems `BPF.kernel_struct_has_field(b'iov_iter', b'iter_type')` is returning an error `libbpf: failed to find valid kernel BTF`, as it seems linux-hardened doesn't have it enabled.

Changing the script to unconditionally use `iter_type` works.

**Comment by chenhengqi** [comment]
Does your system compiled with `CONFIG_DEBUG_INFO_BTF=y` ?

**Comment by sebastianblunt** [comment]
No, and that is the problem. Removing the check and hardcoding `iter_type` works.
