### ISSUE TITLE
`tplist` cannot scan some binaries, such as python3 on aarch64

### ISSUE THREAD

**Issue by viniciusd** [iovisor/bcc#3861]
When using tplist on aarch64 against some binaries, such as the python3 interpreter, it fails and indefinitely prints:

```
Parse error:
    -4@[sp, 136]
```

I've traced it into the USDT class initialization, [which calls](https://github.com/iovisor/bcc/blob/master/src/python/bcc/usdt.py#L139) `lib.bcc_usdt_new_frompath(path.encode('ascii'))`. Then it gets into the native code.

From my understanding, it ends up in the `ArgumentParser_aarch64`, which is failing to match the instruction with the given regexes.

I could try to fix it with some guidance if it's of interest to the maintainers.

**Comment by yonghong-song** [comment]
@viniciusd Thanks for reporting and being willing to help fix the issue. Please go ahead to work on this and submit a pull request. If you have any question, you can ask in this thread or the pull request.

**Comment by viniciusd** [comment]
Just installed the most recent version from the `master` branch and I couldn't reproduce the issue. It seems the problem is from the packaged version I was using. I guess it is just a matter of time while they do not update the package.

Thanks for your availability!
