### ISSUE TITLE
ktrace

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#387]
Or "trace". A simple tool to trace kernel functions and print selected arguments. Possible user-level as well (or have a separate "utrace").

This would be used primarily for debugging. Prior examples of such tools include https://github.com/brendangregg/perf-tools/blob/master/examples/kprobe_example.txt and https://github.com/brendangregg/perf-tools/blob/master/examples/uprobe_example.txt. This ticket is a follow on from #385.

Possible usage:

1. ktrace do_sys_open
2. ktrace r:do_sys_return
3. ktrace 'do_sys_open "%s", %si'
4. ktrace 'do_sys_open "%s %d", %si, %di'
5. ktrace 'do_sys_open "%s", filename' 
6. ktrace 'do_sys_open (%di == 42) "%s", filename' 
7. ktrace 'do_sys_open "%s", %si' 'r:do_sys_open'

I've dropped the "printf()", "if" syntax, and p: to make entry tracing the default. 'r:' for return tracing. The principle here is that it should be a simple tool that does:

> Trace A, if B, print C.

As simple as possible, and where B & C are optional.

If such shortcuts are just too strange, then we could be explicit:

1. ktrace p:do_sys_open
2. ktrace r:do_sys_open
3. ktrace 'p:do_sys_open printf("%s", %si)'
4. ktrace 'p:do_sys_open printf(""%s %d", %si, %di)'
5. ktrace 'p:do_sys_open printf("%s", filename)' 
6. ktrace 'p:do_sys_open if (%di == 42) { printf("%s", filename); }' 
7. ktrace 'p:do_sys_open printf("%s", %si)' 'r:do_sys_open'

Although this is starting to look like a programming language, and a user may then try declaring variables and calling other functions, only to be disappointed that only "if" and "printf" are supported. This particular tool shouldn't be a do-everything programming language: just trace A, if B, print C.

Output columns could be TIME(s), PID, COMM, FUNC, where FUNC == function name traced. If arguments are printed, an extra column ARGS is added. If a return probe is traced, an RVAL column is added.

**Comment by goldshtn** [comment]
Not sure about 5 and 6: where would the `filename` argument come from?

**Comment by brendangregg** [comment]
Come to think of it, most users won't want to mess with registers. These should be:

1. ktrace do_sys_open
1. ktrace r:do_sys_return
1. ktrace 'do_sys_open "%s", arg1'
1. ktrace 'do_sys_open "%s %d", arg1, arg2'
1. ktrace 'do_sys_open "%s", filename'
1. ktrace 'do_sys_open (arg2 == 42) "%s", filename'
1. ktrace 'do_sys_open "%s", arg1' 'r:do_sys_open'

With or without the extra printf() syntax, and where arg1..N comes from #336 .

As for filename... How is bcc working right now, regarding walking structs? Is it just using standard headers (.h's) and not code (.c)? In which case, we'd have to specify the function arguments (like argdist) or require source to be available somehow (which may be onerous).

**Comment by goldshtn** [comment]
I'm afraid the if syntax will also need to know the argument type. Unless you zero-extend everything to 64 bits and do conditionals on that. And it won't support strings in any case at this point, right?

**Comment by brendangregg** [comment]
It's in the printf() format specifier. printf("%s %u %d %llu %lld %hu %hd %c", ...

These 8 format specifiers should cover a lot.

**Comment by goldshtn** [comment]
Yes but that means you can't take a conditional on one argument and trace another argument. Feels rather brittle and surprising ...

**Comment by brendangregg** [comment]
Could cast the conditional variable if need be. Eg:

1. ktrace do_sys_open "mode: %d", arg2
1. ktrace do_sys_open ((u32)arg2 == 0) "read only"

Not great examples, but anyway, in both cases we've specified the type. Oh, and we should be able to include arbitrary text in the output string (like printf).

And without a cast, it would default to u64.

**Comment by goldshtn** [comment]
Makes sense, yeah. Do you want to split the work? :-) Or is that more of a wish list?

**Comment by brendangregg** [comment]
Wish list: if you want to take a swing at it, please go ahead. :) I was going to try a bit more tcp tracing next.

**Comment by brendangregg** [comment]
Also should see if @4ast likes the new syntax

**Comment by goldshtn** [comment]
Cool; in any case I assume the output should go through BPF_PERF. I recall an issue where you had some trouble setting up a kernel version that supports it. What is the short path to getting it to work?

**Comment by brendangregg** [comment]
I'd go with the latest 4.5, and you might need my "if 1" from #363 .

**Comment by goldshtn** [comment]
All right, I have a prototype here: https://github.com/goldshtn/bcc/tree/trace

There are plenty of bugs, no proper validation, and I'm using bpf_trace_printk while waiting for #392 to be merged. Still, I think it shows that the general idea is viable. It's not going to be a lot of fun parsing the format string and getting the variables in shape for the BPF_PERF struct though. It could be nice to have a helper like bpf_trace_printk that just generates the string...

**Comment by goldshtn** [comment]
All right, I switched from bpf_trace_printk to BPF_PERF_OUTPUT. There are still some issues, particularly around reading strings, but it's looking pretty close.

**Comment by goldshtn** [comment]
@brendangregg I'd appreciate your feedback so far: https://github.com/goldshtn/bcc/tree/trace

Before opening a PR I'd like to see if there are any low-hanging fruits that I should take care of.

```
# ./trace.py '__kmalloc (arg1>100 && arg1<200) "allocating %d bytes", arg1' 'r:__kmalloc (retval==0) "kmalloc failed!"'
p:`__kmalloc FLT=(ctx->di>100 && ctx->di<200) ACT=['d']/[' ctx->di']
r:`__kmalloc FLT=(ctx->ax==0) ACT=[]/[]
TIME       PID    COMM         FUNC         MSG
09:27:43   22406  python       __kmalloc    allocating 176 bytes
09:27:43   22330  kworker/3:0  __kmalloc    allocating 152 bytes
09:27:45   22330  kworker/3:0  __kmalloc    allocating 152 bytes
09:27:47   22330  kworker/3:0  __kmalloc    allocating 152 bytes
09:27:50   22330  kworker/3:0  __kmalloc    allocating 152 bytes
09:27:52   22330  kworker/3:0  __kmalloc    allocating 152 bytes
09:27:54   22330  kworker/3:0  __kmalloc    allocating 152 bytes
09:27:56   22330  kworker/3:0  __kmalloc    allocating 152 bytes
^C
```

**Comment by brendangregg** [comment]
Awesome! First comment: I tried the first example (do_sys_open) and it went into a feedback loop of tracing itself. strace said:

```
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=118, ...}) = 0
open("/proc/4540/comm", O_RDONLY)       = 16
fstat(16, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
fstat(16, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
lseek(16, 0, SEEK_CUR)                  = 0
fstat(16, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f4832b8d000
lseek(16, 0, SEEK_CUR)                  = 0
read(16, "python\n", 1024)              = 7
fstat(16, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
lseek(16, 0, SEEK_CUR)                  = 7
read(16, "", 1024)                      = 0
close(16)                               = 0
munmap(0x7f4832b8d000, 4096)            = 0
write(1, "19:18:21   4540   python       d"..., 45) = 45
```

Maybe this is because of using the strftime? Perhaps it needs a default filter that excludes its own PID?

**Comment by goldshtn** [comment]
It's because I'm getting the comm by reading /proc/PID/comm, so there's an `open` in there. I guess it would make sense to exclude the current pid by default. Also, maybe I should collect the comm in the kernel. But I just felt it would be easier and possibly faster in the user script. What do you think?

**Comment by goldshtn** [comment]
Ugh, sorry, just realized that I forgot to cache the comm by pid. And then realized that I can't cache the comm by pid because the pid can be reused. And so I really do have to get the comm in the BPF program and pass it along to user mode.

**Comment by brendangregg** [comment]
Need to make do with bpf_get_current_comm().

Just wanted to explain this weirdness if you didn't know already:

```
# ./trace.py -p 4879 'do_sys_open "%s %s", arg2, ctx->si'
p:`do_sys_open FLT=1 ACT=['s', 's']/[' ctx->si', ' ctx->si']
TIME       PID    COMM         FUNC         MSG
19:51:33   4879   bash         do_sys_open  date.txt date.txt
```

It's because do_sys_open() is:

```
long do_sys_open(int dfd, const char __user *filename, int flags, umode_t mode)
```

And not the open(2) syscall, where *filename would have been the 1st argument.

We really need static tracepoints for the syscalls. Tracing do_sys* and sys* are hacks.

**Comment by brendangregg** [comment]
I'm still using it, it's pretty nice. Some minor things:

- Needs to support %x, %lx, %llx print format modifiers, for hex output

- The debug output (line before header) should only be shown with a -v:

```
# ./trace.py 'sys_read (arg3 > 20000) "read %d bytes", arg3'
p:`sys_read FLT=(ctx->dx > 20000) ACT=['d']/[' ctx->dx']
TIME       PID    COMM         FUNC         MSG
20:31:04   7236   dd           sys_read     read 1048576 bytes
20:31:04   7236   dd           sys_read     read 1048576 bytes
20:31:04   7236   dd           sys_read     read 1048576 bytes
```

I think that example is pretty nice, BTW.

- I'd tweak column widths a little, to be:

print("%-8s %-6s %-12s %-16s %s" % ("TIME", "PID", "COMM", "FUNC", "MSG"))

Don't need the extra spaces on TIME, and I keep tracing functions longer than 12 chars.

I'd also not truncate the function name, and letting push out the MSG column when necessary. We can trunc COMM, to keep things neat, but it'll be ok to mess up the last one.

- Print "MSG" header only if a message was specified. "./trace do_sys_open" alone shouldn't have that column. Also, maybe it should be called "ARGS" instead, or just "-". It's not really message, and it may not just be args. Calling it "-" may be the safest bet. :)

- first time I tried user-mode:

```
# ./trace.py 'bash:readline'
bash:`readline FLT=1 ACT=[]/[]
TIME       PID    COMM         FUNC         MSG
^C
```

second time

```
# ./trace.py 'p:bash:readline'
p:`bash FLT=1 ACT=[]/[]
write(/sys/kernel/debug/tracing/kprobe_events, "p:kprobes/p_bash bash") failed: No such file or directory
TIME       PID    COMM         FUNC         MSG
Segmentation fault
```

third time:

```
# ./trace.py 'bash`readline'
p:bash`readline FLT=1 ACT=[]/[]
Traceback (most recent call last):
  File "./trace.py", line 342, in <module>
    probe.attach(bpf, args.verbose)
  File "./trace.py", line 269, in attach
    self._attach_u(bpf)
  File "./trace.py", line 294, in _attach_u
    pid=self.pid)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 816, in attach_uprobe
    (path, addr) = BPF._check_path_symbol(name, sym, addr)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 787, in _check_path_symbol
    raise Exception("could not find library %s" % name)
Exception: could not find library bash
```

Right, this isn't a library.

I'm not sure I like switching to backquote as the library delimiter, although it is the obvious choice if not a colon. I thought the argdist syntax was consistent and straightforward:

- p::kfunc
- r::kfunc
- p:lib:ufunc
- r:lib:ufunc

which could be enhanced with shortcuts:

- kfunc (== p::kfunc)
- lib:ufunc (== p:lib:ufunc)

(I'm tempted to suggest taking trace and making it ktrace, which looks almost complete, and then work on utrace separately, without worrying about kernel functions as part of the syntax.. anyway..)

As for adding /bin/bash readline, maybe it needs to be:

- trace 'p:.text:readline' -c /bin/bash
- trace 'p:bash:readline' -c /bin/bash

The 1st form is using the name of the segment (".text"), to indicate matching on the specified command ("-c"). I don't like it. If we have had a better name (like "cmd", "target", "process"), we could use it, but we have to avoid clashing with libraries. Maybe, as a shortcut, it should just be "." !

The 2nd form is probably the more intuitive: I'm running bash, and I have libraries. This is a bash function. So that library field should be bash. Ditto for mysql, node, etc.

trace can support both.

PS, entry to readline isn't interesting. The return is either:

- trace 'r:bash:readline "entered: %s", retval'
- trace 'r:.:readline "entered: %s", retval'

Maybe at some point in the future we'll s/retval/rval/ in this & argdist. There's some symmetry to argN & rval.

**Comment by goldshtn** [comment]
It should work with /usr/bin/bash. This is really a uprobes thing, I'm pretty sure it's the same with your uprobe tool and with perf etc. I can try resolving bash as a library before adding the probe, and if that fails do a `which bash`. Not sure if it could lead to conflicts but will try. 

Re the syntax, it's either all three parts or there can be ambiguity. Consider r:func -- is it a kretprobe on func or an entry probe on libr`func? I wanted something nicer than r::func, p::func. But I don't mind going back to the argdist syntax, it's even easier to parse. 

Thoughts?

**Comment by goldshtn** [comment]
Just pushed another commit that fixes most of the above issues (except the %x specifiers and the ` vs. : controversy). The major good news is that you can do `./trace.py 'r:bash`readline "%s", retval'` and it figures out /usr/bin/bash for you.

**Comment by brendangregg** [comment]
Much prefer : to `. Consistent with other delimiters (and it is another delimiter), and also easier and clearer to include in documentation (slides, printed, word processors - which love to mess with quotes), and easier to say.

Type backquote. No, not that quote, the other quote. The one under tilde. There, to the next of your 1 key...

I don't think there's an ambiguity issue. Here's the options:

- p::kfunc
- r::kfunc
- p:lib:ufunc
- r:lib:ufunc
- kfunc (== p::kfunc)
- lib:ufunc (== p:lib:ufunc)

r:func is a uprobe of func from libr.

r:r:func is a uretprobe of func from libr.

r::func is a kretprobe of func.

**Comment by goldshtn** [comment]
Yeah, that actually makes sense. I just pushed a few more changes. I'll implement the optional delimiters and then I think it's ready for a PR. Along the way I've also added special keywords for getting the pid, tgid, uid, gid, and CPU number (all from the BPF helpers). I think it would be cool to add bpf_get_prandom_u32 as well, but there's a problem with it, which I'll open a separate issue for.

**Comment by brendangregg** [comment]
trace is awesome, thanks!
