### ISSUE TITLE
klockstat Uses Incorrect kprobe When CONFIG_DEBUG_LOCK_ALLOC is Set

### ISSUE THREAD

**Issue by aauren** [iovisor/bcc#3882]
When the kernel config `DEBUG_LOCK_ALLOC` is set, the kprobe for `mutex_lock` appears to change to `mutex_lock_nested` which means that `klockstat` will not be able to set the correct kernel probe (here: https://github.com/iovisor/bcc/blob/master/tools/klockstat.py#L432-L433) and will experience the following error:

```
# klockstat -i 5 -n 10
cannot attach kprobe, probe entry may not exist
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.10/klockstat", line 432, in <module>
    b.attach_kretprobe(event="mutex_lock", fn_name="mutex_lock_return")
  File "/usr/lib/python3.10/site-packages/bcc/__init__.py", line 872, in attach_kretprobe
    raise Exception("Failed to attach BPF program %s to kretprobe %s" %
Exception: Failed to attach BPF program b'mutex_lock_return' to kretprobe b'mutex_lock'
```

Looking at `/sys/kernel/debug/tracing/error_log` shows:
```
[86294.825300] trace_kprobe: error: Invalid probed address or symbol
  Command: r:kprobes/r_mutex_lock_bcc_62628 mutex_lock
```

However, patching `klockstat` to instead attach to the `mutex_lock_nested` kprobe allows `klockstat` to work again.

Patch below:
```
$ cat klockstat.patch
--- old/klockstat       2022-02-24 20:50:19.055305306 +0000
+++ new/klockstat       2022-02-24 20:50:59.636482177 +0000
@@ -429,8 +429,8 @@

 if not is_support_kfunc:
     b.attach_kprobe(event="mutex_unlock",  fn_name="mutex_unlock_enter")
-    b.attach_kretprobe(event="mutex_lock", fn_name="mutex_lock_return")
-    b.attach_kprobe(event="mutex_lock",    fn_name="mutex_lock_enter")
+    b.attach_kretprobe(event="mutex_lock_nested", fn_name="mutex_lock_return")
+    b.attach_kprobe(event="mutex_lock_nested",    fn_name="mutex_lock_enter")

 enabled = b.get_table("enabled");
```

Not sure exactly the best way to check for this that is within the convention of this repo or I would submit the PR myself as this seems pretty straight forward.

**Comment by chenhengqi** [comment]
You can use `BPF.get_kprobe_functions` to check whether symbol exists.

**Comment by aauren** [comment]
Thanks for the tip @chenhengqi.

I have created: #3886 which should resolve this.
