### ISSUE TITLE
user version of event_re for regex uprobe matches

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#389]
maybe sym_re? would be used by funccount.

**Comment by brendangregg** [comment]
Needed for sane tracing of C++ binaries, where the symbols are C++ signatures. Eg, tracing mysqld's _Z16dispatch_command19enum_server_commandP3THDPcj. Should be able to use ".*dispatch_command.*".

**Comment by goldshtn** [comment]
This was added in #730 so that `stackcount` can support regexes. This might be a good time to update `funccount` as well -- perhaps add the same level of support for uprobes, tracepoints, USDT. (Probably track as a separate issue though.)

**Comment by brendangregg** [comment]
funccount needs updating, yes.

Just realized it'll simplify the tools diagram: I currently have two arrows on the left, one for spanning user-level and one for kernel-level. Eventually it'll just be one arrow (also with stacksnoop, funclatency).

**Comment by brendangregg** [comment]
I think this is now sym_re in #730 . closing.
