### ISSUE TITLE
Does BPF class (BCC C++ API) support pinned BPF program?

### ISSUE THREAD

**Issue by yzhao1012** [iovisor/bcc#3905]
There is support for pinned maps:
https://github.com/iovisor/bcc/blob/master/docs/reference_guide.md#pinned-maps

To use persistent BPF programs, as https://lwn.net/Articles/664688/ mentioned that bpf programs and maps are all supported as persistent objects, what needs to be configured in the API?

If the API does not support pinned BPF program, then what's the reason for that?

**Comment by yonghong-song** [comment]
Take a look at tests/cc/test_pinned_table.cc which have a few examples.

**Comment by yzhao1012** [comment]
Thanks!
