### ISSUE TITLE
trace_perf_output.py raises NameError: global name 'multiprocessing' is not defined

### ISSUE THREAD

**Issue by goldshtn** [iovisor/bcc#391]
On the current master with the `#if 1` patch to libbpf.c (#363) to make it work on my kernel:

```
$ sudo ./trace_perf_output.py 
Traceback (most recent call last):
  File "./trace_perf_output.py", line 43, in <module>
    b["events"].open_perf_buffer(cb)
  File "/usr/lib/python2.7/site-packages/bcc/table.py", line 371, in open_perf_buffer
    for i in range(0, multiprocessing.cpu_count()):
NameError: global name 'multiprocessing' is not defined
```

Other examples work fine, all the tests pass as well. It's worthwhile to note that there is no test that exercises `open_perf_buffer`.

I suspect this has something to do with order of imports, or possibly circular imports. `__init__.py` imports stuff from `table.py`, whereas `table.py` relies on the `import multiprocessing` performed in `__init__.py`. I'm very far from being a Python expert, so I might be totally wrong.

Just to clarify, I do have the multiprocessing module installed:

```
$ python
Python 2.7.10 (default, Sep 24 2015, 17:50:09) 
[GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import multiprocessing
>>> multiprocessing.cpu_count()
4
>>> 
```

**Comment by goldshtn** [comment]
I can also confirm that everything works fine on 5e3ccf0710cd73e61055888f59a54084ba7dbc62, so it must be #390 that broke something :cat:

**Comment by drzaeus77** [comment]
Will fix. The point about open_perf_buffer is well taken. Also, the import in __init__.py has no influence on the imports in table.py. The files are independent, table.py is simply missing `import multiprocessing`.

**Comment by goldshtn** [comment]
I tried adding `import multiprocessing` to `table.py`, and got an error about missing other symbols declared in `__init__.py`, such as `open_kprobes`.
