### ISSUE TITLE
inject.py doesn't work

### ISSUE THREAD

**Issue by redwood9** [iovisor/bcc#3911]
On both devices, I found inject.py(bcc/tools/inject.py) didn't work properly
- In Linux kernel 4.18, it generates a segment error
- In Linux kernel 5.14, it will prompt "unknown func BPF_override_return #58"

How can I adjust it to work properly?
Thank you very much for your help

========
**device 1**
[root@localhost ~]# uname -r
4.18.0-365.el8.x86_64
[root@localhost ~]# cat /etc/centos-release
CentOS Stream release 8
[root@localhost ~]# /usr/share/bcc/tools/inject.py kmalloc -v 'd_alloc_parallel(struct dentry *parent, const struct qstr *name)(STRCMP(name->name, 'bananas'))'
#include <linux/mm.h>

struct pid_struct {
    u64 curr_call; /* book keeping to handle recursion */
    u64 conds_met; /* stack pointer */
    u64 stack[2];
};
BPF_HASH(m, u32, struct pid_struct);
BPF_ARRAY(count, u32, 1);
int d_alloc_parallel_entry(struct pt_regs *ctx, struct dentry *parent, const struct qstr *name)
{
        u32 pid = bpf_get_current_pid_tgid();

        /*
         * Early exit for probability case
         */
        if (false)
               return 0;
        /*
         * Top level function init map
         */
        struct pid_struct p_struct = {0, 0};
        m.insert(&pid, &p_struct);

        struct pid_struct *p = m.lookup(&pid);
        if (!p)
                return 0;
        /*
         * preparation for predicate, if necessary
         */

        char *str_0_1 = name->name;
        bool is_true_0_1 = true;
	is_true_0_1 &= *(str_0_1++) == 'b';
	is_true_0_1 &= *(str_0_1++) == 'a';
	is_true_0_1 &= *(str_0_1++) == 'n';
	is_true_0_1 &= *(str_0_1++) == 'a';
	is_true_0_1 &= *(str_0_1++) == 'n';
	is_true_0_1 &= *(str_0_1++) == 'a';
	is_true_0_1 &= *(str_0_1++) == 's';
	is_true_0_1 &= *(str_0_1++) == '\0';

        /*
         * Generate entry logic
         */

        if (p->conds_met >= 2)
                return 0;
        if (p->conds_met == 0 && (is_true_0_1)) {
                p->stack[0] = p->curr_call;
                p->conds_met++;
        }
        p->curr_call++;
        return 0;
}
int d_alloc_parallel_exit(struct pt_regs *ctx)
{
        u32 pid = bpf_get_current_pid_tgid();
        struct pid_struct *p = m.lookup(&pid);
        if (!p)
                return 0;
        p->curr_call--;
        /*
         * Generate exit logic
         */

        if (p->conds_met < 1 || p->conds_met >= 3)
                return 0;
        if (p->stack[p->conds_met - 1] == p->curr_call)
                p->conds_met--;

        /*
         * Top level function clean up map
         */
        m.delete(&pid);

        return 0;
}
int should_failslab_entry(struct pt_regs *ctx, struct kmem_cache *s, gfp_t gfpflags)
{
        u32 overridden = 0;
        int zero = 0;
        u32* val;
        val = count.lookup(&zero);
        if (val)
            overridden = *val;
        /*
         * preparation for predicate, if necessary
         */

        /*
         * If this is the only call in the chain and predicate passes
         */
        if (2 == 1 && (true) && overridden < -1) {
                count.atomic_increment(zero);
                bpf_override_return(ctx, -ENOMEM);
                return 0;
        }
        u32 pid = bpf_get_current_pid_tgid();
        struct pid_struct *p = m.lookup(&pid);
        if (!p)
                return 0;
        /*
         * If all conds have been met and predicate passes
         */
        if (p->conds_met == 1 && (true) && overridden < -1) {
                count.atomic_increment(zero);
                bpf_override_return(ctx, -ENOMEM);
        }
        return 0;
}

/virtual/main.c:32:15: warning: initializing 'char *' with an expression of type 'const unsigned char *const' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        char *str_0_1 = name->name;
              ^         ~~~~~~~~~~
/virtual/main.c:96:23: error: no member named 'atomic_increment' in 'struct count_table_t'
                count.atomic_increment(zero);
                ~~~~~ ^
/virtual/main.c:108:23: error: no member named 'atomic_increment' in 'struct count_table_t'
                count.atomic_increment(zero);
                ~~~~~ ^



**device 2:**
[root@VM-3-87-centos ~]# uname -r
5.4.119-1-**-0008

[root@VM-3-87-centos ~]# /usr/share/bcc/tools/inject kmalloc -v 'd_alloc_parallel(struct dentry *parent, const struct qstr *name)(STRCMP(name->name, 'bananas'))'
#include <linux/mm.h>

struct pid_struct {
    u64 curr_call; /* book keeping to handle recursion */
    u64 conds_met; /* stack pointer */
    u64 stack[2];
};
BPF_HASH(m, u32, struct pid_struct);
BPF_ARRAY(count, u32, 1);
int d_alloc_parallel_entry(struct pt_regs *ctx, struct dentry *parent, const struct qstr *name)
{
        u32 pid = bpf_get_current_pid_tgid();
        
        /*
         * Early exit for probability case
         */
        if (false)
               return 0;
        /*
         * Top level function init map
         */
        struct pid_struct p_struct = {0, 0};
        m.insert(&pid, &p_struct);
        

        struct pid_struct *p = m.lookup(&pid);

        if (!p)
                return 0;

        /*
         * preparation for predicate, if necessary
         */
         
        char *str_0_1 = name->name;
        bool is_true_0_1 = true;
        is_true_0_1 &= *(str_0_1++) == 'b';
        is_true_0_1 &= *(str_0_1++) == 'a';
        is_true_0_1 &= *(str_0_1++) == 'n';
        is_true_0_1 &= *(str_0_1++) == 'a';
        is_true_0_1 &= *(str_0_1++) == 'n';
        is_true_0_1 &= *(str_0_1++) == 'a';
        is_true_0_1 &= *(str_0_1++) == 's';
        is_true_0_1 &= *(str_0_1++) == '\0';

        /*
         * Generate entry logic
         */
        

        if (p->conds_met >= 2)
                return 0;
        if (p->conds_met == 0 && (is_true_0_1)) {
                p->stack[0] = p->curr_call;
                p->conds_met++;
        }

        p->curr_call++;

        return 0;
}
int d_alloc_parallel_exit(struct pt_regs *ctx)
{
        u32 pid = bpf_get_current_pid_tgid();

        struct pid_struct *p = m.lookup(&pid);

        if (!p)
                return 0;

        p->curr_call--;

        /*
         * Generate exit logic
         */
        
        if (p->conds_met < 1 || p->conds_met >= 3)
                return 0;

        if (p->stack[p->conds_met - 1] == p->curr_call)
                p->conds_met--;
        
        
        /*
         * Top level function clean up map
         */
        m.delete(&pid);
        
        return 0;
}
int should_failslab_entry(struct pt_regs *ctx, struct kmem_cache *s, gfp_t gfpflags)
{
        u32 overridden = 0;
        int zero = 0;
        u32* val;

        val = count.lookup(&zero);
        if (val)
            overridden = *val;

        /*
         * preparation for predicate, if necessary
         */
         
        /*
         * If this is the only call in the chain and predicate passes
         */
        if (2 == 1 && (true) && overridden < -1) {
                count.atomic_increment(zero);
                bpf_override_return(ctx, -ENOMEM);
                return 0;
        }
        u32 pid = bpf_get_current_pid_tgid();

        struct pid_struct *p = m.lookup(&pid);

        if (!p)
                return 0;

        /*
         * If all conds have been met and predicate passes
         */
        if (p->conds_met == 1 && (true) && overridden < -1) {
                count.atomic_increment(zero);
                bpf_override_return(ctx, -ENOMEM);
        }
        return 0;
}

/virtual/main.c:35:15: warning: initializing 'char *' with an expression of type 'const unsigned char *const' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
        char *str_0_1 = name->name;
              ^         ~~~~~~~~~~
1 warning generated.
bpf: Failed to load program: Invalid argument
0: (bf) r6 = r1
1: (b7) r7 = 0
2: (63) *(u32 *)(r10 -4) = r7
last_idx 2 first_idx 0
regs=80 stack=0 before 1: (b7) r7 = 0
3: (18) r1 = 0xffff88825ad2c800
5: (bf) r2 = r10
6: (07) r2 += -4
7: (85) call bpf_map_lookup_elem#1
8: (15) if r0 == 0x0 goto pc+1
 R0_w=map_value(id=0,off=0,ks=4,vs=4,imm=0) R6_w=ctx(id=0,off=0,imm=0) R7_w=invP0 R10=fp0 fp-8=mmmm????
9: (61) r7 = *(u32 *)(r0 +0)
 R0_w=map_value(id=0,off=0,ks=4,vs=4,imm=0) R6_w=ctx(id=0,off=0,imm=0) R7_w=invP0 R10=fp0 fp-8=mmmm????
10: (85) call bpf_get_current_pid_tgid#14
11: (63) *(u32 *)(r10 -8) = r0
12: (18) r1 = 0xffff888519e1ec00
14: (bf) r2 = r10
15: (07) r2 += -8
16: (85) call bpf_map_lookup_elem#1
17: (15) if r0 == 0x0 goto pc+20
 R0_w=map_value(id=0,off=0,ks=4,vs=32,imm=0) R6=ctx(id=0,off=0,imm=0) R7=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R10=fp0 fp-8=mmmmmmmm
18: (67) r7 <<= 32
19: (77) r7 >>= 32
20: (18) r1 = 0xffffffff
22: (1d) if r7 == r1 goto pc+15
 R0=map_value(id=0,off=0,ks=4,vs=32,imm=0) R1=inv4294967295 R6=ctx(id=0,off=0,imm=0) R7=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R10=fp0 fp-8=mmmmmmmm
23: (79) r1 = *(u64 *)(r0 +8)
 R0=map_value(id=0,off=0,ks=4,vs=32,imm=0) R1_w=inv4294967295 R6=ctx(id=0,off=0,imm=0) R7=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R10=fp0 fp-8=mmmmmmmm
24: (55) if r1 != 0x1 goto pc+13
 R0=map_value(id=0,off=0,ks=4,vs=32,imm=0) R1_w=inv1 R6=ctx(id=0,off=0,imm=0) R7=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R10=fp0 fp-8=mmmmmmmm
25: (61) r1 = *(u32 *)(r10 -4)
26: (63) *(u32 *)(r10 -12) = r1
27: (18) r1 = 0xffff88825ad2c800
29: (bf) r2 = r10
30: (07) r2 += -12
31: (85) call bpf_map_lookup_elem#1
32: (15) if r0 == 0x0 goto pc+2
 R0=map_value(id=0,off=0,ks=4,vs=4,imm=0) R6=ctx(id=0,off=0,imm=0) R7=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R10=fp0 fp-8=mmmmmmmm fp-16=mmmm????
33: (b7) r1 = 1
34: (c3) lock *(u32 *)(r0 +0) += r1
 R0=map_value(id=0,off=0,ks=4,vs=4,imm=0) R1_w=inv1 R6=ctx(id=0,off=0,imm=0) R7=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R10=fp0 fp-8=mmmmmmmm fp-16=mmmm????
 R0=map_value(id=0,off=0,ks=4,vs=4,imm=0) R1_w=inv1 R6=ctx(id=0,off=0,imm=0) R7=inv(id=0,umax_value=4294967295,var_off=(0x0; 0xffffffff)) R10=fp0 fp-8=mmmmmmmm fp-16=mmmm????
35: (bf) r1 = r6
36: (b7) r2 = -12
37: (85) call bpf_override_return#58
unknown func bpf_override_return#58
processed 34 insns (limit 1000000) max_states_per_insn 0 total_states 3 peak_states 3 mark_read 3

Traceback (most recent call last):
  File "/usr/share/bcc/tools/inject", line 525, in <module>
    Tool().run()
  File "/usr/share/bcc/tools/inject", line 520, in run
    self._attach_probes()
  File "/usr/share/bcc/tools/inject", line 492, in _attach_probes
    p.attach(self.bpf)
  File "/usr/share/bcc/tools/inject", line 305, in attach
    fn_name=self.func_name)
  File "/usr/lib/python3.6/site-packages/bcc/__init__.py", line 836, in attach_kprobe
    fn = self.load_func(fn_name, BPF.KPROBE)
  File "/usr/lib/python3.6/site-packages/bcc/__init__.py", line 523, in load_func
    (func_name, errstr))
Exception: Failed to load BPF program b'should_failslab_entry': Invalid argument

**Comment by chenhengqi** [comment]
For the first case, you don't have `atomic_increment` in your installation, build from source should work.

**Comment by redwood9** [comment]
Thanks a lot for your reply
I used the latest tag V0.24.0 to recompile, there are still errors

[root@localhost bpf]# /usr/share/bcc/tools/inject kmalloc -v 'd_alloc_parallel(struct dentry *parent, const struct qstr *name)(STRCMP(name->name, 'bananas'))'
: CommandLine Error: Option 'openmp-ir-builder-optimistic-attributes' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options

**Comment by redwood9** [comment]
> build

Thanks a lot for your reply
I used the latest tag V0.24.0 to recompile, there are still errors

[root@localhost bpf]# /usr/share/bcc/tools/inject kmalloc -v 'd_alloc_parallel(struct dentry *parent, const struct qstr *name)(STRCMP(name->name, 'bananas'))'
: CommandLine Error: Option 'openmp-ir-builder-optimistic-attributes' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options

**Comment by redwood9** [comment]
> For the first case, you don't have `atomic_increment` in your installation, build from source should work.

Thanks a lot for your reply
I used the latest tag V0.24.0 to recompile, there are still errors

[root@localhost bpf]# /usr/share/bcc/tools/inject kmalloc -v 'd_alloc_parallel(struct dentry *parent, const struct qstr *name)(STRCMP(name->name, 'bananas'))'
: CommandLine Error: Option 'openmp-ir-builder-optimistic-attributes' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options

**Comment by redwood9** [comment]
> For the first case, you don't have `atomic_increment` in your installation, build from source should work.

In my centos 8(Linux kernel 4.18), bcc 0.24.0 recompile, It works！

Thanks very much

PS: It need cmake ..   -DENABLE_LLVM_SHARED=1, otherwise "Option 'openmp-ir-Builder-optimize-attributes' registered more than once!"

But in  kernel 5.14, it is still doesn't work

**Comment by yonghong-song** [comment]
> But in kernel 5.14, it is still doesn't work

What kind of issue you are seeing? If the error is
```
37: (85) call bpf_override_return#58
unknown func bpf_override_return#58
processed 34 insns (limit 1000000) max_states_per_insn 0 total_states 3 peak_states 3 mark_read 3
```
then the reason is the kernel doesn't support bpf_override_return. The helper is only available if
CONFIG_BPF_KPROBE_OVERRIDE is on, could you check that in your host?

**Comment by redwood9** [comment]
> The helper is only available if
> CONFIG_BPF_KPROBE_OVERRIDE is on, could you check that in your host?

YES， CONFIG_BPF_KPROBE_OVERRIDE is not set. Thanks for your reply!

------
grep -i BPF /boot/config-`uname -r`
CONFIG_CGROUP_BPF=y
CONFIG_BPF=y
CONFIG_BPF_SYSCALL=y
# CONFIG_BPF_JIT_ALWAYS_ON is not set
CONFIG_NETFILTER_XT_MATCH_BPF=m
# CONFIG_BPFILTER is not set
CONFIG_NET_CLS_BPF=m
# CONFIG_NET_ACT_BPF is not set
CONFIG_BPF_JIT=y
CONFIG_BPF_STREAM_PARSER=y
CONFIG_HAVE_EBPF_JIT=y
CONFIG_BPF_EVENTS=y
# CONFIG_BPF_KPROBE_OVERRIDE is not set
# CONFIG_TEST_BPF is not set

**Comment by redwood9** [comment]
> > The helper is only available if
> > CONFIG_BPF_KPROBE_OVERRIDE is on, could you check that in your host?
> 
> YES， CONFIG_BPF_KPROBE_OVERRIDE is not set. Thanks for your reply!
> 
> ```
> grep -i BPF /boot/config-`uname -r`
> CONFIG_CGROUP_BPF=y
> CONFIG_BPF=y
> CONFIG_BPF_SYSCALL=y
> # CONFIG_BPF_JIT_ALWAYS_ON is not set
> CONFIG_NETFILTER_XT_MATCH_BPF=m
> # CONFIG_BPFILTER is not set
> CONFIG_NET_CLS_BPF=m
> # CONFIG_NET_ACT_BPF is not set
> CONFIG_BPF_JIT=y
> CONFIG_BPF_STREAM_PARSER=y
> CONFIG_HAVE_EBPF_JIT=y
> CONFIG_BPF_EVENTS=y
> # CONFIG_BPF_KPROBE_OVERRIDE is not set
> # CONFIG_TEST_BPF is not set
> ```

I recompile kernel 5.14.0 and open "CONFIG_BPF_KPROBE_OVERRIDE", inject is run correctly, but It does not work. 
My example is:
/usr/share/bcc/tools/inject -v kmalloc 'ext4_init_io_end(struct inode *inode, gfp_t flags)((1==1 ))'

Is inject unavailable in 5.14?
![image](https://user-images.githubusercontent.com/1522256/160275721-adfc29ec-e25f-453d-b2d4-6e97d914d941.png)

![image](https://user-images.githubusercontent.com/1522256/160275794-d2e71d11-24ee-4b09-a253-8dbd5ed01296.png)
