### ISSUE TITLE
./offcputime.py    AttributeError: type object 'BPF' has no attribute 'kernel_struct_has_field'

### ISSUE THREAD

**Issue by oreak** [iovisor/bcc#3920]
[ying@fedora bcc]$ sudo  ./offcputime.py 5
Traceback (most recent call last):
  File "/data/tools/bcc/./offcputime.py", line 216, in <module>
    if BPF.kernel_struct_has_field(b'task_struct', b'__state') == 1:
AttributeError: type object 'BPF' has no attribute 'kernel_struct_has_field'

**Comment by oreak** [comment]
> 

Linux fedora 5.16.13-200.fc35.x86_64 #1 SMP PREEMPT Tue Mar 8 22:50:58 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by oreak** [comment]
> [ying@fedora bcc]$ sudo ./offcputime.py 5 Traceback (most recent call last): File "/data/tools/bcc/./offcputime.py", line 216, in if BPF.kernel_struct_has_field(b'task_struct', b'__state') == 1: AttributeError: type object 'BPF' has no attribute 'kernel_struct_has_field'

hello_world.py  running properly 

[ying@fedora bcc]$ sudo ./hello.py 
b' electron-wechat-172429  [010] d..31 582109.158228: bpf_trace_printk: Hello, World!'
b''
b'         systemd-1       [008] d..31 582109.205293: bpf_trace_printk: Hello, World!'
b''

**Comment by chenhengqi** [comment]
You need to build from source.

**Comment by oreak** [comment]
> You need to build from source.

ok , Thanks

**Comment by baiwfg2** [comment]
I built bymyself, but it still show this error.

`Linux vm 6.2.0-35-generic #35~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Oct  6 10:23:26 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`
bcc 0.29

**Comment by chenhengqi** [comment]
You may still reference to the old installation of BCC, try removing them and reinstall.
