### ISSUE TITLE
bashreadline fails to compile BPF program: R1 type=inv expected=fp

### ISSUE THREAD

**Issue by goldshtn** [iovisor/bcc#393]
I'm having the same problem with my trace work (#387), and decided to check against a ground truth... On the latest master I am getting the following:

```
# ./bashreadline.py                            
bpf: Permission denied
0: (bf) r6 = r1
1: (b7) r1 = 0
2: (7b) *(u64 *)(r10 -8) = r1
3: (7b) *(u64 *)(r10 -16) = r1
4: (7b) *(u64 *)(r10 -24) = r1
5: (7b) *(u64 *)(r10 -32) = r1
6: (7b) *(u64 *)(r10 -40) = r1
7: (7b) *(u64 *)(r10 -48) = r1
8: (7b) *(u64 *)(r10 -56) = r1
9: (7b) *(u64 *)(r10 -64) = r1
10: (7b) *(u64 *)(r10 -72) = r1
11: (7b) *(u64 *)(r10 -80) = r1
12: (7b) *(u64 *)(r10 -88) = r1
13: (79) r1 = *(u64 *)(r6 +80)
14: (15) if r1 == 0x0 goto pc+20
 R1=inv R6=ctx R10=fp
15: (85) call 14
16: (67) r0 <<= 32
17: (77) r0 >>= 32
18: (7b) *(u64 *)(r10 -88) = r0
19: (79) r3 = *(u64 *)(r6 +80)
20: (bf) r7 = r10
21: (07) r7 += -88
22: (bf) r1 = r7
23: (07) r1 += 8
24: (b7) r2 = 80
25: (85) call 4
R1 type=inv expected=fp
```

**Comment by 4ast** [comment]
is your llvm  < 3.7.1 ?

**Comment by goldshtn** [comment]
I'm using http://llvm.org/releases/3.7.0/clang+llvm-3.7.0-x86_64-fedora22.tar.xz per the install instructions for Fedora.

**Comment by 4ast** [comment]
that bug was fixed in 3.7.1 or later.

**Comment by goldshtn** [comment]
I'm willing to try, but last time I was building clang from source, the result wouldn't work no matter what. I believe @drzaeus77 was investigating it. Can I expect it to work now?

**Comment by drzaeus77** [comment]
I've tested the following on F23 and it worked:

1. compile clang from source (3.7.1)
2. install clang to a local directory (e.g. `$HOME/llvm/build/install`)
3. set PATH to include the above install/bin dir (e.g. `$HOME/llvm/build/install/bin`)
4. build bcc, being sure to use gcc as the compiler not clang

You shouldn't have to edit any CMakeLists.txt files in bcc to get the above step working, if it complains then something went wrong.

**Comment by goldshtn** [comment]
I'm on F22 right now, crossing fingers :-)

**Comment by drzaeus77** [comment]
Oh in that case the binary clang 3.7.1 should work. All the recent issues have been with F23.

**Comment by goldshtn** [comment]
Oh even better. Where do I get binary clang 3.7.1? (Might be worthwhile updating INSTALL.md)

**Comment by goldshtn** [comment]
Sorry for being thick, found it of course. 
http://llvm.org/releases/3.7.1/clang+llvm-3.7.1-x86_64-fedora22.tar.xz
