### ISSUE TITLE
tcpconnect DNS correlation doesn't work with IPv6 DNS

### ISSUE THREAD

**Issue by sebastianblunt** [iovisor/bcc#3933]
`tcpconnect -d` reports `No DNS Query` when DNS queries are sent over IPv6 instead of IPv4.

Can be reproduced by setting `2606:4700:4700::64` in resolv.conf.

It is able to correlate AAAA queries.

**Comment by chenhengqi** [comment]
@sebastianblunt Could you try #3938 ?

**Comment by sebastianblunt** [comment]
That works for me, thanks!
