### ISSUE TITLE
Handling lost samples

### ISSUE THREAD

**Issue by Anjali05** [iovisor/bcc#3941]
Hi, 

I am using `perf_buffer` in my eBFP script which traces kernel level locks. There are many samples that are lost when I run the script to trace locks acquired by a workload. I have tried increasing the page count, but it is not very helpful,  the script still reports lost samples. I am wondering if there is a way to handle this better in the code. Ideally, there should not be any lost sample for my use case. I would really appreciate any pointer/helper with this.

Thanks in advance,
Anjali

**Comment by chenhengqi** [comment]
* Have you tried `klockstat` from BCC, what's the result ?
* What value did you set for page count and timeout (for `perf_buffer_poll`) ?
* How intensive is your target workload ?

**Comment by Anjali05** [comment]
@chenhengqi I tried the new API with `wakeup_events` set to 10,  `page_cnt` to 65536 with no `timeout` but I still see sample loss. Do you have any other suggestions?

**Comment by chenhengqi** [comment]
Do you try increasing `wakeup_events` ?

**Comment by Anjali05** [comment]
@chenhengqi I did try with 50 too but didn't work. I will try again with maybe 100, 150...

**Comment by Anjali05** [comment]
@chenhengqi I tried with different sizes till 1000 but it's still losing samples. I was wondering if there is an upper limit on the number of `wakeup_events`. Also, just to make sure, with `wakeup_events` the ring buffer polls in batches when the number of events becomes the size of `wakeup_events` instead of polling every event, right?

**Comment by Anjali05** [comment]
@chenhengqi Is there a way I control the number of sample I want to collect(list collect 20% of the total)? I am fine losing some samples but I would like to keep an account for that. The problem is that for spin-locks the number of events is too high and my program does not stop after the time I would like it to stop. And just continues to print the number of samples lost and continue running. I guess the events is too huge for the trace program to handle and if I can control the number of samples I want to collect, I can atleast stop the trace from running.

**Comment by chenhengqi** [comment]
> Also, just to make sure, with wakeup_events the ring buffer polls in batches when the number of events becomes the size of wakeup_events instead of polling every event, right?

Yes, or timeout whichever first.

**Comment by chenhengqi** [comment]
> @chenhengqi Is there a way I control the number of sample I want to collect(list collect 20% of the total)? I am fine losing some samples but I would like to keep an account for that. The problem is that for spin-locks the number of events is too high and my program does not stop after the time I would like it to stop. And just continues to print the number of samples lost and continue running. I guess the events is too huge for the trace program to handle and if I can control the number of samples I want to collect, I can atleast stop the trace from running.

I think you can do some filtering to achive that, for example `cpu_id == 0`.
