### ISSUE TITLE
Port CodegenLLVM::optimize to new pass manager

### ISSUE THREAD

**Issue by MaskRay** [iovisor/bcc#3947]
Using LLVM's legacy PM for optimization pipeline was [deprecated in 13.0.0](https://releases.llvm.org/13.0.0/docs/ReleaseNotes.html#changes-to-the-llvm-ir) and the relevant functionality was scheduled to be removed after 14.0.0 (got delayed). The legacy PM for code generation (assembly, object file generation; mainly addPassesToEmitFile) is still supported.

Clang dropped legacy PM support in [D123609](https://reviews.llvm.org/D123609) (milestone: 15.0.0). I plan to remove instrumentation passes like gcov, PGO, and sanitizers (milestone: 15.0.0).

LLVM's legacy PM for optimization pipeline may be completely removed in 16.0.0 (`llvm::create*Pass`, `populateModulePassManager`, etc). llvm-project `clang/lib/CodeGen/BackendUtil.cpp` can serve as an example using the new pass manager.

**Comment by chenhengqi** [comment]
I will take this one when #3956 landed. :)
