### ISSUE TITLE
Warning: usdt.cc returning address of local temporary object

### ISSUE THREAD

**Issue by briangreenery** [iovisor/bcc#3949]
When compiling bcc `0.24` with clang `14.0.1`, I get the following warning:

```
bcc/src/cc/usdt/usdt.cc:547:12: warning: returning address of local temporary object [-Wreturn-stack-address]
    return p->get_arg_ctype(arg_index).c_str();
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
bcc/src/cc/usdt/usdt.cc:556:12: warning: returning address of local temporary object [-Wreturn-stack-address]
    return p->get_arg_ctype(arg_index).c_str();
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
```

I'm not familiar with this code, but at first glance it does appear like it is returning a pointer into a temporary `std::string`:

https://github.com/iovisor/bcc/blob/7c02284faa2968d86720f416ea51cc74d446ab37/src/cc/usdt/usdt.cc#L554-L561
https://github.com/iovisor/bcc/blob/7c02284faa2968d86720f416ea51cc74d446ab37/src/cc/usdt.h#L255-L257

**Comment by chenhengqi** [comment]
How do you trigger these warning ?

**Comment by yonghong-song** [comment]
LGTM. Thanks!

**Comment by yonghong-song** [comment]
> How do you trigger these warning ?

This can be triggered with cmake option CMAKE_C_COMPILER and CMAKE_CXX_COMPILER setting to clang/clang++.
