### ISSUE TITLE
Cannot print bytecode with debug flags

### ISSUE THREAD

**Issue by xingtingkai** [iovisor/bcc#3998]
I am having trouble printing out the bytecode with debug=0x2 in BPF instantiation. I have checked the program with strace and the program is loaded as bpf(BPF_PROG_LOAD,...) is called. I changed debug flags from 0x2 to 0x10 and it prints out the bytecode with register states successfully. Curious why 0x2 doesn't print out the bytecode

from bcc import BPF

prog = """
int hello(void *ctx) {
    bpf_trace_printk("Hello, World!\\n");
    return 0;
}
"""

b = BPF(text=prog, debug=0x2)
b.attach_kprobe(event=b.get_syscall_fnname("clone"), fn_name="hello")

print("%-18s %-16s %-6s %s" % ("TIME(s)", "COMM", "PID", "MESSAGE"))

while 1:
    try:
        (task, pid, cpu, flags, ts, msg) = b.trace_fields()
    except ValueError:
        continue
    print("%-18.9f %-16s %-6d %s" % (ts, task, pid, msg))

**Comment by yonghong-song** [comment]
debug=0x2 intends to dump insn in case of verification failure. If verification will succeed and you still want to dump insns, please try debug=8 to dump insns based on dwarf, or debug=16 to dump insns processed by verifier.

**Comment by xingtingkai** [comment]
That explains. Thank you
