### ISSUE TITLE
Ubuntu (jammy 22.04) installation not working 

### ISSUE THREAD

**Issue by joelcisnerosss** [iovisor/bcc#4039]
I've been trying to install bcc on ubuntu(source) to start calling the tools through the terminal but I keep getting mistakes. The guide doesn't have any guide on how to run or test installation so I tested commands similar to Amazon Linux 2 `sudo /usr/share/bcc/tools/execsnoop` but it didn't work with a path error. Navigating to directory and running sudo python3 execsnoop.py Im getting this error: 

`Traceback (most recent call last):
  File "/home/ubuntu/bcc/tools/execsnoop.py", line 21, in <module>
    from bcc import BPF
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 27, in <module>
    from .libbcc import lib, bcc_symbol, bcc_symbol_option, bcc_stacktrace_build_id, _SYM_CB_TYPE
  File "/usr/lib/python3/dist-packages/bcc/libbcc.py", line 20, in <module>
    lib.bpf_module_create_b.restype = ct.c_void_p
  File "/usr/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/local/lib/libbcc.so.0: undefined symbol: bpf_module_create_b`

I get the same output if I run commands following the Package installation. 

I followed installation step by step and these are my machine's configurations: 

Kernel version: 5.15.0-1004-
Clang version: 14.0.0-1ubuntu1
Bison version: 3.8.2
LLVM version: 14.0.0
cmake version: 3.22.1
gcc version: 11.2.0
flex version: 2.6.4

**Comment by yiqinguo** [comment]
I have the same problem

**Comment by yiqinguo** [comment]
I have the same problem

**Comment by advaithcurpod** [comment]
I also have the same problem. Why is this issue closed?

**Comment by Tptogiar** [comment]
I also have the same problem. Why is this issue closed?

**Comment by louxiu** [comment]
If you installed bpftrace with apt, then uninstall it (python3-bpfcc bpftrace etc.).
