### ISSUE TITLE
[Feature Request] add flags parameter for perf_submit 

### ISSUE THREAD

**Issue by jschwinger233** [iovisor/bcc#4048]
The current `perf_submit`  (`int perf_submit((void *)ctx, (void *)data, u32 `) doesn't accept flags, but hardcodes the `CUR_CPU_IDENTIFIER` flags in the frondend:

```c
        } else if (memb_name == "perf_submit") {
          string name = string(Ref->getDecl()->getName());
          string arg0 = rewriter_.getRewrittenText(expansionRange(Call->getArg(0)->getSourceRange()));
          string args_other = rewriter_.getRewrittenText(expansionRange(SourceRange(GET_BEGINLOC(Call->getArg(1)),
                                                           GET_ENDLOC(Call->getArg(2)))));
          txt = "bpf_perf_event_output(" + arg0 + ", bpf_pseudo_fd(1, " + fd + ")";
          txt += ", CUR_CPU_IDENTIFIER, " + args_other + ")";
```

However the flags parameter for bpf_perf_event_output matters, as there is a hidden feature that allows user to specify the upper 32 bits of the flags as a number of bytes to include the skb/xdp payload in the event data. Please see the comments in the kernel:

```
		/* The XDP perf_event_output handler will use the upper 32 bits
		 * of the flags argument as a number of bytes to include of the
		 * packet payload in the event data. If the size is too big, the
		 * call to bpf_perf_event_output will fail and return -EFAULT.
		 *
		 * See bpf_xdp_event_output in net/core/filter.c.
		 *
		 * The BPF_F_CURRENT_CPU flag means that the event output fd
		 * will be indexed by the CPU number in the event map.
		 */
```
https://github.com/torvalds/linux/blob/b13baccc3850ca8b8cccbf8ed9912dbaa0fdf7f3/samples/bpf/xdp_sample_pkts_kern.c#L28-L37

So I was wondering if it's reasonable to add the flags parameter for perf_submit.

**Comment by chenhengqi** [comment]
You can use `perf_submit_skb`.
