### ISSUE TITLE
usage of attach_perf_event

### ISSUE THREAD

**Issue by Hankin-Liu** [iovisor/bcc#4067]
Are there any doc to discribe how to attach perf events using bcc?
I saw llcstat use attach_perf_event api. Where can I find the usage of attach_perf_event?

**Comment by yezhem** [comment]
attach_perf_event  just call the BPF::attach_perf_event -> bpf_attach_perf_event -> syscall(__NR_perf_event_open)
you can check the system call https://man7.org/linux/man-pages/man2/perf_event_open.2.html
