### ISSUE TITLE
How to insert new entry into HASH_OF_MAPS' outer map in BCC C

### ISSUE THREAD

**Issue by jschwinger233** [iovisor/bcc#4073]
The example demonstrates the usage of BPF_HASH_OF_MAPS in BCC by inserting into the outer map in userspace:

https://github.com/iovisor/bcc/blob/5657c7dce897e600fb9dc7fceb56ed5ffdd6d1ca/tests/python/test_map_in_map.py#L58-L63

I was wondering if there is an approach to insert into the outer map in kernel (BCC C) instead of userspace (BCC Python).

Correct me if I'm wrong, function bpf_map_update_elem in bpf-helpers(7) requires a argument of struct bpf_map *, but I am afraid it's not available in BCC C?

**Comment by chenhengqi** [comment]
What's your use-case ?

**Comment by jschwinger233** [comment]
> What's your use-case ?

It's a sophisticated scenario, where I am developing a debugger using bpf and wanna keep track of frame pointers(bp) for each thread, so the data structure is designed to be of type map[ThreadID -> array[FramePointer]].

**Comment by chenhengqi** [comment]
It is impossible for now.

https://github.com/torvalds/linux/blob/4b0986a3613c92f4ec1bdc7f60ec66fea135991f/kernel/bpf/verifier.c#L5732-L5736

You can use hash maps and make `ThreadID` + `array index` as key.

**Comment by jschwinger233** [comment]
> It is impossible for now.
> 
> https://github.com/torvalds/linux/blob/4b0986a3613c92f4ec1bdc7f60ec66fea135991f/kernel/bpf/verifier.c#L5732-L5736
> 
> You can use hash maps and make `ThreadID` + `array index` as key.

Thank your very much, you're so smart and kind, wish I can treat you to a meal next time I am back to China.
