### ISSUE TITLE
RISC-V Ubuntu 22.04 Exception: fatal error: 'asm/types.h' file not found

### ISSUE THREAD

**Issue by xmzzz** [iovisor/bcc#4081]
Does bcc support RISC-V? I try to run the tools in /usr/share/bcc/tools/ but get an error.
I installed the Ubuntu 22.04 operating system in the RISC-V environment simulated by QEMU, and installed bcc from the source code. The version is bcc release v0.24.0.But getting below Error:
```
ubuntu@ubuntu:~$ /usr/share/bcc/tools/tcptop
In file included from <built-in>:2:
In file included from /virtual/include/bcc/bpf.h:12:
In file included from include/linux/types.h:6:
include/uapi/linux/types.h:5:10: fatal error: 'asm/types.h' file not found
#include <asm/types.h>
         ^~~~~~~~~~~~~
1 error generated.
Traceback (most recent call last):
  File "/usr/share/bcc/tools/tcptop", line 244, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 475, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>
```
My system information is as follows:
```
ubuntu@ubuntu:~$ uname -r
5.15.0-1014-generic
ubuntu@ubuntu:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy
ubuntu@ubuntu:~$ dpkg-query -s linux-headers-$(uname -r)
Package: linux-headers-5.15.0-1014-generic
Status: install ok installed
Priority: optional
Section: devel
Installed-Size: 40771
Maintainer: Ubuntu Kernel Team <kernel-team@lists.ubuntu.com>
Architecture: riscv64
Source: linux-riscv
Version: 5.15.0-1014.16
Provides: linux-headers, linux-headers-3.0
Depends: linux-riscv-headers-5.15.0-1014, libc6 (>= 2.34), libelf1 (>= 0.142), libssl3 (>= 3.0.0~~alpha1), zlib1g (>= 1:1.2.3.3)
Description: Linux kernel headers for version 5.15.0 on RISC-V SMP
 This package provides kernel header files for version 5.15.0 on
 RISC-V SMP.
 .
 This is for sites that want the latest kernel headers.  Please read
 /usr/share/doc/linux-headers-5.15.0-1014/debian.README.gz for details.
```

**Comment by yzhao1012** [comment]
Never saw reporting of BCC using on RISC-V CPUs. Would love to hear from the community members if anyone had relevant experiences.

**Comment by dlan17** [comment]
I think there is currently no RISC-V support in bcc which means we need to spend some effort porting it, personally I would like to see RV64 support added first..

here is more verbose log while debug is enabled, and we can see it call x86 bits
#  slabratetop
Running from kernel directory at: /lib/modules/5.18.7-gentoo-riscv64/source
clang -cc1 -triple x86_64-unknown-linux-gnu -emit-llvm-bc -emit-llvm-uselists -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name main.c -mrelocation-model pic -pic-level 2 -pic-is-pie -fno-jump-tables -mframe-pointer=none -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -target-cpu x86-64 -tune-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debug-info-kind=constructor -dwarf-version=5 -debugger-tuning=gdb -fcoverage-compilation-dir=/usr/src/linux-5.18.7-gentoo -nostdsysteminc -nobuiltininc -resource-dir ../../../../lib/clang/14.0.6 -isystem /virtual/lib/clang/include -include ./include/linux/kconfig.h -include /virtual/include/bcc/bpf.h -include /virtual/include/bcc/bpf_workaround.h -include /virtual/include/bcc/helpers.h -isystem /virtual/include -I /root -D __BPF_TRACING__ -I arch/riscv64/include/ -I /lib/modules/5.18.7-gentoo-riscv64/build/arch/riscv64/include/generated -I include -I /lib/modules/5.18.7-gentoo-riscv64/build/include -I arch/riscv64/include/uapi -I /lib/modules/5.18.7-gentoo-riscv64/build/arch/riscv64/include/generated/uapi -I include/uapi -I /lib/modules/5.18.7-gentoo-riscv64/build/include/generated/uapi -D __KERNEL__ -D KBUILD_MODNAME="bcc" -O2 -Wno-deprecated-declarations -Wno-gnu-variable-sized-type-not-at-end -Wno-pragma-once-outside-header -Wno-address-of-packed-member -Wno-unknown-warning-option -Wno-unused-value -Wno-pointer-sign -fdebug-compilation-dir=/usr/src/linux-5.18.7-gentoo -ferror-limit 19 -fgnuc-version=4.2.1 -vectorize-loops -vectorize-slp -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o main.bc -x c /virtual/main.c
In file included from <built-in>:2:
In file included from /virtual/include/bcc/bpf.h:12:
In file included from include/linux/types.h:6:
include/uapi/linux/types.h:5:10: fatal error: 'asm/types.h' file not found
#include <asm/types.h>
         ^~~~~~~~~~~~~

**Comment by yonghong-song** [comment]
risc-v is not supported in bcc yet.
