### ISSUE TITLE
libbpf: failed to add legacy kprobe event for 'vfs_open+0x0': No such file or directory

### ISSUE THREAD

**Issue by Ephemeraler** [iovisor/bcc#4087]
I execute 'cat /proc/kallsyms | grep vfs_open', it can be found in system. Why I get this error msg.

**Comment by chenhengqi** [comment]
Do you have tracefs/debugfs mounted ?

**Comment by Ephemeraler** [comment]
> Do you have tracefs/debugfs mounted ?
@chenhengqi I guess this problem is related to the system configuration, such as CONFIG_KPROBES*. In my system, I find only CONFIG_HAVE_KPROBES=y. But I am not sure which Config about Kprobe is causing this problem.

**Comment by chenhengqi** [comment]
Try `cat /proc/mounts | grep debug`.

**Comment by Ephemeraler** [comment]
> Try `cat /proc/mounts | grep debug`.

@chenhengqi yes, the system has mountted tracefs and debugfs. I can use tracepoint on BPF, I will recompile kernel to modify config in order to find cause. Maybe CONFIG_KPROBES need to set.

**Comment by yonghong-song** [comment]
Yes, CONFIG_KPROBES is necessary for kprobe support.

**Comment by irenge** [comment]
Please close the issue once resolved :)
