### ISSUE TITLE
kprobe events need to be deleted on exit

### ISSUE THREAD

**Issue by 4ast** [iovisor/bcc#41]
after running tests:
$ cat kprobe_events
p:kprobes/p_sys_write sys_write
p:kprobes/p_sys_read sys_read
p:kprobes/p_htab_map_get_next_key htab_map_get_next_key
p:kprobes/p_schedule_50 schedule+50
p:kprobes/p_blk_start_request blk_start_request
p:kprobes/p_blk_update_request blk_update_request
p:kprobes/p_sys_clone sys_clone

both exit and Ctrl-C need to delete kprobe events

**Comment by drzaeus77** [comment]
Closed with #49
