### ISSUE TITLE
Cannot run bpf program with capabilities CAP_BPF, CAP_SYS_ADMIN enabled. 

### ISSUE THREAD

**Issue by syogaraj** [iovisor/bcc#4107]
Hi,

I'm trying to run the bpf program from a non-root user without enabling the `unprivileged_bpf_disabled` flag. 

I've modified the killsnoop program to include the user id in the output. I had set the capabilities `CAP_BPF` for python using `setcap` and ran the program.

`sudo setcap CAP_BPF=+eip /usr/bin/python3.9`

<details><summary>Exception with CAP_BPF</summary>
<pre>
bpf: Failed to load program: Operation not permitted
Traceback (most recent call last):
  File "/home/yogaraj/bpf_programs/killsnoop.py", line 38, in attach_kprobes
    self.bpf.attach_kprobe(event=self.kill_syscall_name, fn_name=b"syscall__kill")
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 679, in attach_kprobe
    fn = self.load_func(fn_name, BPF.KPROBE)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 408, in load_func
    raise Exception("Need super-user privileges to run")
Exception: Need super-user privileges to run
</pre>

</details>

I had set `CAP_SYS_ADMIN` along with `CAP_BPF` for the python executable and re-ran the program.

`sudo setcap CAP_BPF,CAP_SYS_ADMIN=+eip /usr/bin/python3.9`

This time it throwed `create_probe_event: open(/sys/kernel/debug/tracing/kprobe_events): Permission denied`
<details><summary>Exception with CAP_BPF and CAP_SYS_ADMIN</summary>
<pre>
create_probe_event: open(/sys/kernel/debug/tracing/kprobe_events): Permission denied
2022-07-15 12:56:22,917 - agent - CRITICAL - [core.process.killsnoop] - Traceback (most recent call last):
  File "/home/yogaraj/bpf_programs/killsnoop.py", line 38, in attach_kprobes
    self.bpf.attach_kprobe(event=self.kill_syscall_name, fn_name=b"syscall__kill")
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 683, in attach_kprobe
    raise Exception("Failed to attach BPF program %s to kprobe %s" %
Exception: Failed to attach BPF program b'syscall__kill' to kprobe b'sys_kill'
</pre>
</details>

<details><summary> Host details</summary>
<pre>$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
</pre>

<pre>
$ uname -a
Linux 192.168.1.8  5.10.106 #2 SMP Mon Apr 4 12:45:20 IST 2022 x86_64 GNU/Linux
</pre>

</details>

Can you please check and advise on how to run the bpf programs via capabilities?

**Comment by chenhengqi** [comment]
I think this is not related to BPF capabilities, just because you don't have access to debugfs.

**Comment by syogaraj** [comment]
@chenhengqi Thanks for the reply. The user from which I was testing doesn't have access to debugfs. So, I ran `chmod` command to provide access for `/sys/kernel/debug` and tried again. 

This time, the error was `cannot attach kprobe, probe entry may not exist`. The same program is able to attach the kprobe when I try it with sudo. Are there any other capabilities/permissions that should be enabled for running the BPF programs?

**Comment by chenhengqi** [comment]
You might find something like this in dmesg:
```
Failed to create system directory kprobes
```

Maybe you can try remount the debugfs/tracefs with non-root user ?

**Comment by syogaraj** [comment]
@chenhengqi please feel free to close this issue. Our servers require debugfs as root user only. We chose to use libbpf for writing the bpf programs.

Is there any option in bcc to print the generated .c source files?

**Comment by chenhengqi** [comment]
Try `b = BPF(text=bpf_text, debug=4)`.

**Comment by syogaraj** [comment]
Yes, I tried this method already. Is there any way to make bcc print the vanilla bpf code (without bcc's rewrite)?

**Comment by chenhengqi** [comment]
AFAIK, no.

**Comment by syogaraj** [comment]
Thanks for your time @chenhengqi . Closing this issue.
