### ISSUE TITLE
perf record/report like libbpf-tools tool ?

### ISSUE THREAD

**Issue by vincentmli** [iovisor/bcc#4111]
Hi,

I used to run `perf record`, `perf report` or even just `perf top` to check system wide run time CPU hot code path for production system high CPU issue. now combine `perf` and `ebpf`, I see there is [[RFC 0/6] perf record: Implement off-cpu profiling with BPF (v3)](https://lore.kernel.org/bpf/20220518224725.742882-1-namhyung@kernel.org/#r), but that requires user space `perf` tool that some system may not have. I just wonder, is similar tool can be made from  libbpf like example tools  in libbpf-tools ? a single binary to run in as many environment as possible?

**Comment by vincentmli** [comment]
oh I did find offcputime from libbpf-tools, but is off cpu and it is not easy to interpret the result without flame graph, and offcputime from libbpf-tools seems like folded output to support flame graph too. I am looking for on cpu libbpf-tools tool with kernel/user space symbols output sorted like `perf top`

**Comment by yunwei37** [comment]
Hi! I found this in the pull requests: https://github.com/iovisor/bcc/pull/3782 
Is it what you want?

**Comment by vincentmli** [comment]
> Hi! I found this in the pull requests: #3782 Is it what you want?

it seems does what I am looking for, it would be nice https://github.com/iovisor/bcc/pull/3782 could sort the function output like `perf top` with cpu cycles percentage like below, this is easier to interpret for users

```
Samples: 2K of event 'cpu-clock:pppH', 4000 Hz, Event count (approx.): 92512047 
Overhead  Shared Object               Symbol                                    
   4.47%  [kernel]                    [k] finish_task_switch                    
   4.39%  [kernel]                    [k] __lock_text_start                     
   3.54%  perf                        [.] 0x00000000002ec44d                    
   3.30%  perf                        [.] 0x00000000002ec453                    
   2.77%  perf                        [.] 0x00000000002e3797                    
   2.69%  libc.so.6                   [.] __nss_database_lookup                 
   2.62%  perf                        [.] sched_getcpu                          
   2.25%  libc.so.6                   [.] __default_morecore                    
   2.04%  [kernel]                    [k] syscall_enter_from_user_mode          
   1.84%  [kernel]                    [k] clear_page_erms                       
   1.39%  [kernel]                    [k] kallsyms_expand_symbol.
```
