### ISSUE TITLE
get_table() not working for BPF_SOCKMAP in python bcc

### ISSUE THREAD

**Issue by aishwarya25252** [iovisor/bcc#4112]
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/bcc/__init__.py", line 631, in get_table
    return Table(self, map_id, map_fd, keytype, leaftype, name, reducer=reducer)
  File "/usr/lib/python3.10/site-packages/bcc/table.py", line 313, in Table
    raise Exception("Unknown table type %d" % ttype)
Exception: Unknown table type 15`

**Comment by aishwarya25252** [comment]
Main question is how should I attach the verdict and parser function to the sockmap in python bcc ?

**Comment by chenhengqi** [comment]
See example here https://github.com/iovisor/bcc/blob/master/examples/networking/sockmap.py .

**Comment by aishwarya25252** [comment]
Hey thanks... I was able to kind of figer it out from this example, maybe a bit more on documentation would also help . Thanks 👍🏻
