### ISSUE TITLE
undefined symbol: bpf_module_create_b

### ISSUE THREAD

**Issue by lizhiyuell** [iovisor/bcc#4114]
Hi, I'm installing bcc [v0.24.0](https://github.com/iovisor/bcc/releases/tag/v0.24.0) in Ubuntu 18.04.1. The compiling is fine, but when I run example code `/usr/share/bcc/tools/offcputime`, I get the following errors:

```
Traceback (most recent call last):
  File "/usr/share/bcc/tools/offcputime", line 14, in <module>
    from bcc import BPF
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 27, in <module>
    from .libbcc import lib, _CB_TYPE, bcc_symbol, bcc_symbol_option, _SYM_CB_TYPE
  File "/usr/lib/python2.7/dist-packages/bcc/libbcc.py", line 20, in <module>
    lib.bpf_module_create_b.restype = ct.c_void_p
  File "/usr/lib/python2.7/ctypes/__init__.py", line 379, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 384, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/x86_64-linux-gnu/libbcc.so.0: undefined symbol: bpf_module_create_b
```

I install llvm and clang with `sudo apt-get install libllvm6.0 llvm-6.0-dev libclang-6.0-dev`.
Referring to issue #2222, I remove the previously installed bpfcc-tools and recompile the code, but the problem still exists.

How cloud I fix this problem? Thanks.

**Comment by chenhengqi** [comment]
Try using python3.

**Comment by lizhiyuell** [comment]
> Try using python3.

Changing to python3 works perfectly. Thanks.

**Comment by Tronginx** [comment]
I figured out the following solution worked for me:

`cp -r /root/ebpf/bcc/build/src/python/bcc-python3/bcc/* /usr/lib/python3/dist-packages/bcc/`

replace the first parameter with your bcc python library location.

Souce: https://blog.csdn.net/libocdf/article/details/130466925

**Comment by chenhengqi** [comment]
Please refer to https://github.com/iovisor/bcc/issues/4583.
