### ISSUE TITLE
libbpf-tools will support linux header ?

### ISSUE THREAD

**Issue by yezhem** [iovisor/bcc#4133]
Due to some reason, many env cannot generate vmlinux.h, only can use the linux header file.

**Comment by chenhengqi** [comment]
You don't need to regenerate vmlinux.h.

**Comment by yezhem** [comment]
> You don't need to regenerate vmlinux.h.

@chenhengqi if there no vmlinux.h, only can include the kernel header file in vmlinux.h and compile it ?

**Comment by yezhem** [comment]
> Of course you can use kernel headers, vmlinux.h is just a simple way for that purpose.

I mean can provide the new vmlinux.h file includes kernel header in libbpf-tools?

**Comment by chenhengqi** [comment]
What's the use case here ?

**Comment by yezhem** [comment]
> What's the use case here ?

@chenhengqi when I compile libbpf-tools, I need to create a new vmlinux.h and include the kernel header file, and modify the Makefile to include the correct directory. any other methods to compile the bpf tools or provide the kernel header just like bcc will be more convenient?

**Comment by chenhengqi** [comment]
> I need to create a new vmlinux.h and include the kernel header file, and modify the Makefile to include the correct directory

What is missing in vmlinux.h in this repo ? Why do you need to include kernel header files ?

**Comment by yezhem** [comment]
> > I need to create a new vmlinux.h and include the kernel header file, and modify the Makefile to include the correct directory
> 
> What is missing in vmlinux.h in this repo ? Why do you need to include kernel header files ?

@chenhengqi my cross-compile environment has no vmlinux.h and only has kernel header files, the vmlinux.h provided is version 515, but my kernel version is not the same as it, can use the vmlinux-515.h?

**Comment by chenhengqi** [comment]
No need to be the same, you can use vmlinux-515.h or whatever, as long as it matches the target arch.

**Comment by yezhem** [comment]
> No need to be the same, you can use vmlinux-515.h or whatever, as long as it matches the target arch.

ok, i will try it.
