### ISSUE TITLE
opensnoop and trace path arg is empty

### ISSUE THREAD

**Issue by dengrui** [iovisor/bcc#4146]
**Environment :** Actually my device is a cellphone.
**kernel** : kernel 4.9 (all CONFIG_* needed are set)
**ARCH** : arm64
**OS** : chroot to Debian GNU/Linux 10 (buster)
**bcc source code** : bcc-src-with-submodule.zip v0.24.0 (https://github.com/iovisor/bcc/releases/download/v0.24.0/bcc-src-with-submodule.zip) 
**kernel headers** : build from kernel, kernel-headers.tar.gz

**After build from source code , I tried :**

root@localhost:/usr/share/bcc/tools# python3 opensnoop 
PID    COMM               FD ERR PATH
883    sensors@1.0-ser    21   0 
883    sensors@1.0-ser    21   0 
908    msm_irqbalance      6   0 
908    msm_irqbalance      6   0 
908    msm_irqbalance      6   0 
908    msm_irqbalance      6   0 
908    msm_irqbalance      6   0 
908    msm_irqbalance      6   0 
908    msm_irqbalance      6   0 
908    msm_irqbalance      6   0 
609    logd.writer        16   0 
609    logd.writer        16   0 

**The PATH column is empty.**

root@localhost:/usr/share/bcc/tools# python3 trace 'sys_execve "%s", arg1'    
PID     TID     COMM            FUNC             -
21800   21800   sh              sys_execve       b''
21802   21802   sh              sys_execve       b''
21803   21803   sh              sys_execve       b''

**The arg1 column is empty too.**

How did this happen? Does anyone know the reason ?

**Comment by chenhengqi** [comment]
See #2253 and #3783.

**Comment by dengrui** [comment]
> See #2253 and #3783.

Thanks a lot!
