### ISSUE TITLE
bcc can't backtrace python language stack

### ISSUE THREAD

**Issue by zxgm** [iovisor/bcc#4150]
bcc/ebpf traces the dynamic library called by the python language, eg, cudart.so of tensorflow or python application call libc.so, cannot trace the python language stack.
tenminal output:
python application:
![image](https://user-images.githubusercontent.com/17983863/183322396-fcb4ae1d-c4ff-46ad-8d3e-ffb420144cec.png)
bcc code about output stack:
![image](https://user-images.githubusercontent.com/17983863/183326160-a0379ee7-83a0-4375-a59c-4fd70851a535.png)

bcc terminal output:
![image](https://user-images.githubusercontent.com/17983863/183322526-ad01c5f7-2c5d-43d5-a62b-68b56f390c56.png)

Anyone encountered this problem? Is there any way to achieve this?

**Comment by zxgm** [comment]
The application calling the dynamic library has been closed, so the obtained stack is unknown.
Encountered a new problem, traced the cuda api call of tensorflow, but now it can only be traced back to the c/c++ code and stopped, and cannot be traced back to the python code
![image](https://user-images.githubusercontent.com/17983863/183384451-ebc58c0f-85ce-4d40-bcf6-a1f3d13bd2bc.png)

**Comment by davemarchevsky** [comment]
Is my understanding correct here: you have a python application calling into a c library, and would like stack tracing to include both the python stack and c stack stitched together in a reasonable way?

If so, the `bcc` tools are working as expected, as they are just reporting the stack that `perf_events` subsystem gives them, which has no visibility into the python stack. Walking the python stack and joining with C/system stack requires a fairly complex BPF program that makes assumptions about internals of the python runtime and therefore is brittle.

At FB we have a profiler (`pyperf`) that does this, current iteration isn't open-source, but some old versions are. See `examples/cpp/pyperf` in this repo and `tools/testing/selftests/bpf/progs/pyperf*` in linux kernel repo.

Anyways, you'd have to implement something similar or integrate existing example code into your tool to make this work.

**Comment by zxgm** [comment]
The answer that i want, thanks a lot.
