### ISSUE TITLE
Got error of "dubious ownership" when adding a new submodule

### ISSUE THREAD

**Issue by ThinkerYzu1** [iovisor/bcc#4190]
I sent PR #4186 days ago.  I got an error message from CI saying that it can not checkout the submodule I added for "dubious ownership."  It suggests me to run `git config --global --add safe.directory /bcc/libbpf-tools/blazesym` and it will add lines to my local ~/.gitconfig.  So, I guess that someone should do that against the image of CI containers to make CI work properly.   So, how can I make it happen?

 https://github.com/iovisor/bcc/pull/4186

**Comment by davemarchevsky** [comment]
I commented on the PR
