### ISSUE TITLE
[RFC] Allowing public access to container packages

### ISSUE THREAD

**Issue by chantra** [iovisor/bcc#4191]
#4180 will allow reducing the CI build time from currently ~27 min (ex https://github.com/iovisor/bcc/actions/runs/2884705757) to ~18 min (ex: https://github.com/iovisor/bcc/actions/runs/2877531574) by leveraging pre-build CI containers.

Those containers are build on a regular basis, as well as when master is updated: https://github.com/iovisor/bcc/blob/master/.github/workflows/publish-build-containers.yml

While they can be pulled directly through this project CI, the containers cannot be pulled by people outside the org:
```
$ docker pull ghcr.io/iovisor/bcc:ubuntu-18.04                       
Trying to pull ghcr.io/iovisor/bcc:ubuntu-18.04...
Error: initializing source docker://ghcr.io/iovisor/bcc:ubuntu-18.04: unable to retrieve auth token: invalid username/password: unauthorized
```

because the package has its visibility set to "private" in https://github.com/orgs/iovisor/packages/container/bcc/settings

More about visibility/permission is available at https://docs.github.com/en/packages/learn-github-packages/configuring-a-packages-access-control-and-visibility

If the visibility was set to "public", then people couild easily access the pre-built containers to build bcc and run their test on vs having them to go through building the container themselves.

So here comes my question, can we set this container package to public? Is there any concerns about this?
It seems that currently packages cannot be set to "public" because the setting is disabled by the organization administrators. Can this be overriden?
cc @davemarchevsky

**Comment by davemarchevsky** [comment]
This was done by @4ast , closing
