### ISSUE TITLE
centos7 has err 

### ISSUE THREAD

**Issue by zhenghr2021** [iovisor/bcc#4208]
cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)
uname -r
4.4.215-1.el7.elrepo.x86_64

yum install -y epel-release
yum update -y
yum groupinstall -y "Development tools"
yum install -y elfutils-libelf-devel cmake3
yum install -y luajit luajit-devel  # for Lua support

#LLVM
curl  -LO  http://releases.llvm.org/7.0.1/llvm-7.0.1.src.tar.xz
curl  -LO  http://releases.llvm.org/7.0.1/cfe-7.0.1.src.tar.xz
tar -xf cfe-7.0.1.src.tar.xz
tar -xf llvm-7.0.1.src.tar.xz

mkdir clang-build
mkdir llvm-build

cd llvm-build
cmake3 -G "Unix Makefiles" -DLLVM_TARGETS_TO_BUILD="BPF;X86" \
  -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr ../llvm-7.0.1.src
make
sudo make install

cd ../clang-build
cmake3 -G "Unix Makefiles" -DLLVM_TARGETS_TO_BUILD="BPF;X86" \
  -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr ../cfe-7.0.1.src
make
sudo make install

yum install -y bcc-tools

=========================ERR===========================

./memleak  -a -p  27056
could not open./memleak  -a -p  27056
could not open bpf map: stack_traces, error: Invalid argument
Traceback (most recent call last):
  File "./memleak", line 419, in <module>
    bpf = BPF(text=bpf_source)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 325, in __init__
    raise Exception("Failed to compile BPF text")
Exception: Failed to compile BPF text
 bpf map: stack_traces, error: Invalid argument
Traceback (most recent call last):
  File "./memleak", line 419, in <module>
    bpf = BPF(text=bpf_source)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 325, in __init__
    raise Exception("Failed to compile BPF text")
Exception: Failed to compile BPF text

**Comment by zhenghr2021** [comment]
/****************  Try source code compilation ：bcc-src-with-submodule.tar.gz   **************/

mkdir bcc/build; cd bcc/build
cmake3 ..
[root@localhost build]# make
[  0%] Building CXX object src/cc/frontends/clang/CMakeFiles/clang_frontend.dir/__/__/common.cc.o
/home/download/bcc/src/cc/common.cc: In function ‘ebpf::field_kind_t ebpf::_get_field_kind(const string&, std::string&, std::string&, int*)’:
/home/download/bcc/src/cc/common.cc:178:59: error: no matching function for call to ‘std::basic_string<char>::replace(long unsigned int, long unsigned int, std::basic_string<char>&, int)’
       field_name.replace(pos1 + 1, pos2 - pos1 - 1, dim, 0);
                                                           ^
/home/download/bcc/src/cc/common.cc:178:59: note: candidates are:
In file included from /usr/include/c++/4.8.2/string:52:0,
                 from /usr/include/c++/4.8.2/bits/locale_classes.h:40,
                 from /usr/include/c++/4.8.2/bits/ios_base.h:41,
                 from /usr/include/c++/4.8.2/ios:42,
                 from /usr/include/c++/4.8.2/istream:38,
                 from /usr/include/c++/4.8.2/fstream:38,
                 from /home/download/bcc/src/cc/common.cc:16:
/usr/include/c++/4.8.2/bits/basic_string.h:1429:7: note: std::basic_string<_CharT, _Traits, _Alloc>& std::basic_string<_CharT, _Traits, _Alloc>::replace(std::basic_string<_CharT, _Traits, _Alloc>::size_type, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const std::basic_string<_CharT, _Traits, _Alloc>&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]
       replace(size_type __pos, size_type __n, const basic_string& __str)
       ^
/usr/include/c++/4.8.2/bits/basic_string.h:1429:7: note:   candidate expects 3 arguments, 4 provided
/usr/include/c++/4.8.2/bits/basic_string.h:1451:7: note: std::basic_string<_CharT, _Traits, _Alloc>& std::basic_string<_CharT, _Traits, _Alloc>::replace(std::basic_string<_CharT, _Traits, _Alloc>::size_type, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const std::basic_string<_CharT, _Traits, _Alloc>&, std::basic_string<_CharT, _Traits, _Alloc>::size_type, std::basic_string<_CharT, _Traits, _Alloc>::size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]
       replace(size_type __pos1, size_type __n1, const basic_string& __str,
       ^
/usr/include/c++/4.8.2/bits/basic_string.h:1451:7: note:   candidate expects 5 arguments, 4 provided
/usr/include/c++/4.8.2/bits/basic_string.h:1476:7: note: std::basic_string<_CharT, _Traits, _Alloc>& std::basic_string<_CharT, _Traits, _Alloc>::replace(std::basic_string<_CharT, _Traits, _Alloc>::size_type, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const _CharT*, std::basic_string<_CharT, _Traits, _Alloc>::size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]
       replace(size_type __pos, size_type __n1, const _CharT* __s,
       ^
/usr/include/c++/4.8.2/bits/basic_string.h:1476:7: note:   no known conversion for argument 3 from ‘std::basic_string<char>’ to ‘const char*’
/usr/include/c++/4.8.2/bits/basic_string.h:1496:7: note: std::basic_string<_CharT, _Traits, _Alloc>& std::basic_string<_CharT, _Traits, _Alloc>::replace(std::basic_string<_CharT, _Traits, _Alloc>::size_type, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const _CharT*) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]
       replace(size_type __pos, size_type __n1, const _CharT* __s)
       ^
/usr/include/c++/4.8.2/bits/basic_string.h:1496:7: note:   candidate expects 3 arguments, 4 provided
/usr/include/c++/4.8.2/bits/basic_string.h:1520:7: note: std::basic_string<_CharT, _Traits, _Alloc>& std::basic_string<_CharT, _Traits, _Alloc>::replace(std::basic_string<_CharT, _Traits, _Alloc>::size_type, std::basic_string<_CharT, _Traits, _Alloc>::size_type, std::basic_string<_CharT, _Traits, _Alloc>::size_type, _CharT) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]
       replace(size_type __pos, size_type __n1, size_type __n2, _CharT __c)
       ^
/usr/include/c++/4.8.2/bits/basic_string.h:1520:7: note:   no known conversion for argument 3 from ‘std::basic_string<char>’ to ‘std::basic_string<char>::size_type {aka long unsigned int}’
/usr/include/c++/4.8.2/bits/basic_string.h:1538:7: note: std::basic_string<_CharT, _Traits, _Alloc>& std::basic_string<_CharT, _Traits, _Alloc>::replace(std::basic_string<_CharT, _Traits, _Alloc>::iterator, std::basic_string<_CharT, _Traits, _Alloc>::iterator, const std::basic_string<_CharT, _Traits, _Alloc>&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::basic_string<_CharT, _Traits, _Alloc>::iterator = __gnu_cxx::__normal_iterator<char*, std::basic_string<char> >; typename _Alloc::rebind<_CharT>::other::pointer = char*]
       replace(iterator __i1, iterator __i2, const basic_string& __str)
       ^
/usr/include/c++/4.8.2/bits/basic_string.h:1538:7: note:   candidate expects 3 arguments, 4 provided
/usr/include/c++/4.8.2/bits/basic_string.h:1557:7: note: std::basic_string<_CharT, _Traits, _Alloc>& std::basic_string<_CharT, _Traits, _Alloc>::replace(std::basic_string<_CharT, _Traits, _Alloc>::iterator, std::basic_string<_CharT, _Traits, _Alloc>::iterator, const _CharT*, std::basic_string<_CharT, _Traits, _Alloc>::size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::basic_string<_CharT, _Traits, _Alloc>::iterator = __gnu_cxx::__normal_iterator<char*, std::basic_string<char> >; typename _Alloc::rebind<_CharT>::other::pointer = char*; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]
       replace(iterator __i1, iterator __i2, const _CharT* __s, size_type __n)
       ^
/usr/include/c++/4.8.2/bits/basic_string.h:1557:7: note:   no known conversion for argument 1 from ‘long unsigned int’ to ‘std::basic_string<char>::iterator {aka __gnu_cxx::__normal_iterator<char*, std::basic_string<char> >}’
/usr/include/c++/4.8.2/bits/basic_string.h:1578:7: note: std::basic_string<_CharT, _Traits, _Alloc>& std::basic_string<_CharT, _Traits, _Alloc>::replace(std::basic_string<_CharT, _Traits, _Alloc>::iterator, std::basic_string<_CharT, _Traits, _Alloc>::iterator, const _CharT*) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::basic_string<_CharT, _Traits, _Alloc>::iterator = __gnu_cxx::__normal_iterator<char*, std::basic_string<char> >; typename _Alloc::rebind<_CharT>::other::pointer = char*]
       replace(iterator __i1, iterator __i2, const _CharT* __s)
       ^
/usr/include/c++/4.8.2/bits/basic_string.h:1578:7: note:   candidate expects 3 arguments, 4 provided
/usr/include/c++/4.8.2/bits/basic_string.h:1599:7: note: std::basic_string<_CharT, _Traits, _Alloc>& std::basic_string<_CharT, _Traits, _Alloc>::replace(std::basic_string<_CharT, _Traits, _Alloc>::iterator, std::basic_string<_CharT, _Traits, _Alloc>::iterator, std::basic_string<_CharT, _Traits, _Alloc>::size_type, _CharT) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::basic_string<_CharT, _Traits, _Alloc>::iterator = __gnu_cxx::__normal_iterator<char*, std::basic_string<char> >; typename _Alloc::rebind<_CharT>::other::pointer = char*; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]
       replace(iterator __i1, iterator __i2, size_type __n, _CharT __c)
       ^
/usr/include/c++/4.8.2/bits/basic_string.h:1599:7: note:   no known conversion for argument 1 from ‘long unsigned int’ to ‘std::basic_string<char>::iterator {aka __gnu_cxx::__normal_iterator<char*, std::basic_string<char> >}’
/usr/include/c++/4.8.2/bits/basic_string.h:1623:9: note: template<class _InputIterator> std::basic_string<_CharT, _Traits, _Alloc>& std::basic_string<_CharT, _Traits, _Alloc>::replace(std::basic_string<_CharT, _Traits, _Alloc>::iterator, std::basic_string<_CharT, _Traits, _Alloc>::iterator, _InputIterator, _InputIterator) [with _InputIterator = _InputIterator; _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]
         replace(iterator __i1, iterator __i2,
         ^
/usr/include/c++/4.8.2/bits/basic_string.h:1623:9: note:   template argument deduction/substitution failed:
/home/download/bcc/src/cc/common.cc:178:59: note:   cannot convert ‘(pos1 + 1ul)’ (type ‘long unsigned int’) to type ‘std::basic_string<char>::iterator {aka __gnu_cxx::__normal_iterator<char*, std::basic_string<char> >}’
       field_name.replace(pos1 + 1, pos2 - pos1 - 1, dim, 0);
                                                           ^
In file included from /usr/include/c++/4.8.2/string:52:0,
                 from /usr/include/c++/4.8.2/bits/locale_classes.h:40,
                 from /usr/include/c++/4.8.2/bits/ios_base.h:41,
                 from /usr/include/c++/4.8.2/ios:42,
                 from /usr/include/c++/4.8.2/istream:38,
                 from /usr/include/c++/4.8.2/fstream:38,
                 from /home/download/bcc/src/cc/common.cc:16:
/usr/include/c++/4.8.2/bits/basic_string.h:1636:7: note: std::basic_string<_CharT, _Traits, _Alloc>& std::basic_string<_CharT, _Traits, _Alloc>::replace(std::basic_string<_CharT, _Traits, _Alloc>::iterator, std::basic_string<_CharT, _Traits, _Alloc>::iterator, _CharT*, _CharT*) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::basic_string<_CharT, _Traits, _Alloc>::iterator = __gnu_cxx::__normal_iterator<char*, std::basic_string<char> >; typename _Alloc::rebind<_CharT>::other::pointer = char*]
       replace(iterator __i1, iterator __i2, _CharT* __k1, _CharT* __k2)
       ^
/usr/include/c++/4.8.2/bits/basic_string.h:1636:7: note:   no known conversion for argument 1 from ‘long unsigned int’ to ‘std::basic_string<char>::iterator {aka __gnu_cxx::__normal_iterator<char*, std::basic_string<char> >}’
/usr/include/c++/4.8.2/bits/basic_string.h:1646:7: note: std::basic_string<_CharT, _Traits, _Alloc>& std::basic_string<_CharT, _Traits, _Alloc>::replace(std::basic_string<_CharT, _Traits, _Alloc>::iterator, std::basic_string<_CharT, _Traits, _Alloc>::iterator, const _CharT*, const _CharT*) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::basic_string<_CharT, _Traits, _Alloc>::iterator = __gnu_cxx::__normal_iterator<char*, std::basic_string<char> >; typename _Alloc::rebind<_CharT>::other::pointer = char*]
       replace(iterator __i1, iterator __i2,
       ^
/usr/include/c++/4.8.2/bits/basic_string.h:1646:7: note:   no known conversion for argument 1 from ‘long unsigned int’ to ‘std::basic_string<char>::iterator {aka __gnu_cxx::__normal_iterator<char*, std::basic_string<char> >}’
/usr/include/c++/4.8.2/bits/basic_string.h:1657:7: note: std::basic_string<_CharT, _Traits, _Alloc>& std::basic_string<_CharT, _Traits, _Alloc>::replace(std::basic_string<_CharT, _Traits, _Alloc>::iterator, std::basic_string<_CharT, _Traits, _Alloc>::iterator, std::basic_string<_CharT, _Traits, _Alloc>::iterator, std::basic_string<_CharT, _Traits, _Alloc>::iterator) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::basic_string<_CharT, _Traits, _Alloc>::iterator = __gnu_cxx::__normal_iterator<char*, std::basic_string<char> >; typename _Alloc::rebind<_CharT>::other::pointer = char*]
       replace(iterator __i1, iterator __i2, iterator __k1, iterator __k2)
       ^
/usr/include/c++/4.8.2/bits/basic_string.h:1657:7: note:   no known conversion for argument 1 from ‘long unsigned int’ to ‘std::basic_string<char>::iterator {aka __gnu_cxx::__normal_iterator<char*, std::basic_string<char> >}’
/usr/include/c++/4.8.2/bits/basic_string.h:1667:7: note: std::basic_string<_CharT, _Traits, _Alloc>& std::basic_string<_CharT, _Traits, _Alloc>::replace(std::basic_string<_CharT, _Traits, _Alloc>::iterator, std::basic_string<_CharT, _Traits, _Alloc>::iterator, std::basic_string<_CharT, _Traits, _Alloc>::const_iterator, std::basic_string<_CharT, _Traits, _Alloc>::const_iterator) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::basic_string<_CharT, _Traits, _Alloc>::iterator = __gnu_cxx::__normal_iterator<char*, std::basic_string<char> >; typename _Alloc::rebind<_CharT>::other::pointer = char*; std::basic_string<_CharT, _Traits, _Alloc>::const_iterator = __gnu_cxx::__normal_iterator<const char*, std::basic_string<char> >; typename _Alloc::rebind<_CharT>::other::const_pointer = const char*]
       replace(iterator __i1, iterator __i2,
       ^
/usr/include/c++/4.8.2/bits/basic_string.h:1667:7: note:   no known conversion for argument 1 from ‘long unsigned int’ to ‘std::basic_string<char>::iterator {aka __gnu_cxx::__normal_iterator<char*, std::basic_string<char> >}’
/usr/include/c++/4.8.2/bits/basic_string.h:1692:21: note: std::basic_string<_CharT, _Traits, _Alloc>& std::basic_string<_CharT, _Traits, _Alloc>::replace(std::basic_string<_CharT, _Traits, _Alloc>::iterator, std::basic_string<_CharT, _Traits, _Alloc>::iterator, std::initializer_list<_Tp>) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::basic_string<_CharT, _Traits, _Alloc>::iterator = __gnu_cxx::__normal_iterator<char*, std::basic_string<char> >; typename _Alloc::rebind<_CharT>::other::pointer = char*]
       basic_string& replace(iterator __i1, iterator __i2,
                     ^
/usr/include/c++/4.8.2/bits/basic_string.h:1692:21: note:   candidate expects 3 arguments, 4 provided
make[2]: *** [src/cc/frontends/clang/CMakeFiles/clang_frontend.dir/__/__/common.cc.o] Error 1
make[1]: *** [src/cc/frontends/clang/CMakeFiles/clang_frontend.dir/all] Error 2
make: *** [all] Error 2

**Comment by bigbang009** [comment]
i have the same error, did you have solved it? how to solve it?

**Comment by v587xpt** [comment]
i have the same error, did you have solved it? how to solve it?
