### ISSUE TITLE
when excuting the tcplife.py, the "RX_KB " filed is abnormally large, has anyone had this problem?

### ISSUE THREAD

**Issue by XueChe** [iovisor/bcc#4218]
1. when excuting the tcplife.py, the results were as follows:
$ ./tcplife.py
/virtual/main.c:3:9: warning: 'KBUILD_MODNAME' macro redefined [-Wmacro-redefined]
#define KBUILD_MODNAME "foo"
        ^
<command line>:3:9: note: previous definition is here
#define KBUILD_MODNAME "bcc"
        ^
1 warning generated.
PID   COMM       LADDR           LPORT RADDR           RPORT TX_KB RX_KB MS
0     swapper/4  10.68.14.102    9282  10.173.63.40    26900 20971520 **1759511199089920** 13.22
164829 gko3       10.68.14.102    422   10.59.224.45    34945     0 **16114460133425152** 66.86
164829 gko3       10.68.14.102    422   10.59.224.45    34933     0 **16114460133425152** 67.46
180536 fork-resou 10.68.14.102    26927 10.195.126.17   8605  4194304 **6474217058993088** 3.10
78291 gcms_sdk_s 10.68.14.102    27554 10.174.5.18     9293  4194304 **16255197621781760** 5.25
18260 naming-age 127.0.0.1       793   127.0.0.1       39336 12582912 **13440722732580992** 1.70
7391  generator- 127.0.0.1       39336 127.0.0.1       793   8388608 13510816598851648 1.73
164829 gko3       10.68.14.102    12381 10.216.114.162  18695 4194304 8303529529705088 6.91
18260 naming-age 127.0.0.1       793   127.0.0.1       39338 12582912 13440722732580928 1.69
7391  generator- 127.0.0.1       39338 127.0.0.1       793   8388608 13510816598851648 1.67
7391  generator- 127.0.0.1       39340 127.0.0.1       793   8388608 13510816598851648 1.59
18260 naming-age 127.0.0.1       793   127.0.0.1       39340 12582912 13440722732580992 1.61
164829 gko3       10.68.14.102    422   10.174.44.38    28672 8388608 16395935110137088 137.09
78291 gcms_sdk_s 10.68.14.102    27577 10.174.5.18     9293  4194304 16255197621781760 5.29
146604 gko3       10.68.14.102    8290  10.176.92.27    22312     0 16114460133425152 99.49
71807 fork-sessi 10.68.14.102    29778 10.173.148.158  8616  4194304 16255197621781760 0.59
71807 fork-sessi 10.68.14.102    29777 10.173.148.158  8616  4194304 16255197621781760 0.59
71807 fork-sessi 10.68.14.102    33051 10.173.37.160   8627  4194304 16255197621781760 0.56
180536 fork-resou 10.68.14.102    23213 10.173.110.36   8870  4194304 16255197621781760 3.26
131218 gcms_sdk_s 10.68.14.102    9284  10.174.74.168   29764 138412032 5418960774236544 145.29
78291 gcms_sdk_s 10.68.14.102    27591 10.174.5.18     9293  4194304 16255197621781760 5.44
11771 gcms_sdk_s 10.68.14.102    9283  10.175.139.168  11497     0 16114460133425152 6.13
180420 noah-clien ::ffff:127.0.0.1 780   ::ffff:127.0.0.1 34234 4194304 13792291575562304 0.44
6773  noah-ci    127.0.0.1       34234 127.0.0.1       780   4194304 14144135296450624 0.81
180420 noah-clien ::ffff:127.0.0.1 780   ::ffff:127.0.0.1 34260 4194304 13792291575562304 0.53
6773  noah-ci    127.0.0.1       34260 127.0.0.1       780   4194304 14144135296450624 0.61
180420 noah-clien ::ffff:127.0.0.1 780   ::ffff:127.0.0.1 34260 4194304 13792291575562304 0.36
6773  noah-ci    127.0.0.1       34260 127.0.0.1       780   4194304 14144135296450624 0.43
......

2. However, excuting the command of "ss" on the same machine, the results are look like normal, as follows:
$ ss -int -o state established
Recv-Q Send-Q                                              Local Address:Port                                                             Peer Address:Port
0      0                                                    10.68.14.102:10866                                                          10.190.249.141:3198
	 ts sack cubic wscale:8,8 rto:11 rtt:0.99/0.06 ato:39 mss:1448 rcvmss:1448 advmss:1448 cwnd:20 ssthresh:24 bytes_acked:545112276 **bytes_received:487360421** segs_out:1267158 segs_in:1221960 data_segs_out:736252 data_segs_in:701610 send 234.0Mbps lastsnd:763 lastrcv:761 lastack:761 pacing_rate 280.8Mbps delivery_rate 143.0Mbps app_limited busy:334869ms retrans:0/1 rcv_rtt:1.83 rcv_space:58400 minrtt:0.912
0      0                                                    10.68.14.102:9284                                                            10.190.218.95:13596
	 ts sack cubic wscale:8,8 rto:11 rtt:0.836/0.059 ato:40 mss:1448 rcvmss:1448 advmss:1448 cwnd:20 ssthresh:20 bytes_acked:39892 **bytes_received:20670** segs_out:42 segs_in:29 data_segs_out:33 data_segs_in:18 send 277.1Mbps lastsnd:3123 lastrcv:3126 lastack:3122 pacing_rate 332.4Mbps delivery_rate 84.7Mbps app_limited busy:8ms rcv_rtt:1513.73 rcv_space:57920 minrtt:0.812
0      0                                                    10.68.14.102:12503                                                           10.173.52.140:8999
	 ts sack cubic wscale:8,8 rto:11 rtt:0.107/0.017 ato:40 mss:1448 rcvmss:1448 advmss:1448 cwnd:20 ssthresh:20 bytes_acked:1099655 **bytes_received:27452686** segs_out:4053 segs_in:19945 data_segs_out:1148 data_segs_in:19226 send 2165.2Mbps lastsnd:4842 lastrcv:4830 lastack:4830 pacing_rate 2580.2Mbps delivery_rate 757.8Mbps app_limited busy:88ms reordering:300 rcv_rtt:9.612 rcv_space:632385 minrtt:0.081
0      0                                                    10.68.14.102:9283                                                           10.190.247.231:26030
	 ts sack cubic wscale:8,8 rto:11 rtt:0.966/0.011 ato:40 mss:1448 rcvmss:1448 advmss:1448 cwnd:44 ssthresh:31 bytes_acked:2246922 bytes_received:102618 segs_out:1619 segs_in:248 data_segs_out:1574 data_segs_in:86 send 527.6Mbps lastsnd:2499 lastrcv:2504 lastack:2498 pacing_rate 632.8Mbps delivery_rate 389.3Mbps busy:91ms rcv_rtt:2643.46 rcv_space:57920 minrtt:0.92
0      0                                                    10.68.14.102:8706                                                           10.173.114.139:19590
	 ts sack cubic wscale:8,8 rto:11 rtt:0.138/0.042 ato:40 mss:1448 rcvmss:536 advmss:1448 cwnd:20 ssthresh:55 bytes_acked:260029801 bytes_received:4668584 segs_out:261108 segs_in:104816 data_segs_out:216054 data_segs_in:45035 send 1678.8Mbps lastsnd:1157 lastrcv:1157 lastack:1157 pacing_rate 3339.5Mbps delivery_rate 739.4Mbps busy:8808ms retrans:0/8 reordering:69 rcv_rtt:12225 rcv_space:63395 minrtt:0.067
0      0                                                    10.68.14.102:48901                                                             10.68.40.86:50927
	 ts sack cubic wscale:8,8 rto:11 rtt:0.053/0.011 ato:40 mss:1448 rcvmss:536 advmss:1448 cwnd:20 ssthresh:20 bytes_acked:68854 bytes_received:16468 segs_out:152 segs_in:154 data_segs_out:76 data_segs_in:76 send 4371.3Mbps lastsnd:20500551 lastrcv:20500552 lastack:20500551 pacing_rate 5196.6Mbps delivery_rate 297.0Mbps app_limited busy:8ms rcv_space:57920 minrtt:0.046
0      0                                                    10.68.14.102:39169                                                            10.220.9.115:8704
	 ts sack cubic wscale:8,8 rto:34 rtt:23.452/0.031 ato:40 mss:1448 rcvmss:536 advmss:1448 cwnd:20 bytes_acked:5342562 bytes_received:18237 segs_out:4651 segs_in:1394 data_segs_out:4009 data_segs_in:640 send 9.9Mbps lastsnd:91812 lastrcv:91789 lastack:91789 pacing_rate 19.8Mbps delivery_rate 7.4Mbps app_limited busy:15672ms rcv_space:58400 minrtt:23.424
0      0                                                    10.68.14.102:9283                                                            10.190.218.99:18100
	 ts sack cubic wscale:8,8 rto:11 rtt:0.968/0.038 ato:40 mss:1448 rcvmss:1448 advmss:1448 cwnd:20 ssthresh:20 bytes_acked:470600 bytes_received:147879 segs_out:465 segs_in:294 data_segs_out:368 data_segs_in:194 send 239.3Mbps lastsnd:1829 lastrcv:1829 lastack:1828 pacing_rate 287.2Mbps delivery_rate 188.5Mbps app_limited busy:98ms rcv_rtt:2468.24 rcv_space:57920 minrtt:0.928
0      0                                                    10.68.14.102:24279                                                           10.160.37.155:19201
	 ts sack cubic wscale:8,8 rto:38 rtt:27.66/0.047 ato:40 mss:1448 rcvmss:536 advmss:1448 cwnd:20 ssthresh:20 bytes_acked:202704017 bytes_received:4279808 segs_out:522040 segs_in:490351 data_segs_out:177506 data_segs_in:82304 send 8.4Mbps lastsnd:11218 lastrcv:11190 lastack:11190 pacing_rate 10.1Mbps delivery_rate 2.2Mbps app_limited busy:1925186ms rcv_rtt:189463 rcv_space:58660 minrtt:27.614
0      0                                                    10.68.14.102:48901                                                            10.68.56.160:46775
	 ts sack cubic wscale:8,8 rto:11 rtt:0.048/0.006 ato:40 mss:1448 rcvmss:536 advmss:1448 cwnd:20 bytes_acked:12017 bytes_received:2820 segs_out:26 segs_in:28 data_segs_out:13 data_segs_in:13 send 4826.7Mbps lastsnd:3869209751 lastrcv:3869211901 lastack:3869209751 pacing_rate 9504.8Mbps delivery_rate 304.8Mbps app_limited rcv_space:57920 minrtt:0.049
....

3. the linux kernel verison is 4.14

**Has anyone had this problem? Thanks~**

**Comment by chenhengqi** [comment]
Could you try libbpf-tools/tcplife and see if there is the same problem ?

**Comment by XueChe** [comment]
您好,我已收到您的邮件.我会尽快回复您的.

**Comment by chenhengqi** [comment]
Great.

**Comment by XueChe** [comment]
您好,我已收到您的邮件.我会尽快回复您的.
