### ISSUE TITLE
errors with the latest kernel tree

### ISSUE THREAD

**Issue by 4ast** [iovisor/bcc#423]
$ funccount.par 'vfs*'
>
/virtual/main.c:7:1: error: could not open bpf map: Argument list too long
BPF_HASH(counts, struct key_t);
^
/virtual/include/bcc/helpers.h:92:37: note: expanded from macro 'BPF_HASH'
  BPF_HASHX(__VA_ARGS__, BPF_HASH3, BPF_HASH2, BPF_HASH1)(__VA_ARGS__)
                                    ^
/virtual/include/bcc/helpers.h:87:42: note: expanded from macro 'BPF_HASHX'
#define BPF_HASHX(_1, _2, _3, NAME, ...) NAME
                                         ^
/virtual/include/bcc/helpers.h:83:3: note: expanded from macro 'BPF_HASH2'
  BPF_TABLE("hash", _key_type, u64, _name, 10240)
  ^
/virtual/include/bcc/helpers.h:46:4: note: expanded from macro 'BPF_TABLE'
}; \
   ^
/virtual/main.c:14:11: error: expected initialized handle for bpf_table
    val = counts.lookup_or_init(&key, &zero);
          ^
2 errors generated.
>

**Comment by drzaeus77** [comment]
Worked perfectly fine for me on tip of net-next. Why is your kernel giving back E2BIG for bpf_map_create? Is the struct mismatched somehow, or did gcc/clang do something weird?

**Comment by 4ast** [comment]
'ulimit -l unlimited' solved it. Turned out my patches were returning e2big when I was doing pre-charge of memlimit...

**Comment by computer5student** [comment]
I have the same problem when I try to allocate a large hashmap:

_/virtual/main.c:24:1: error: could not open bpf map: Argument list too long
is maps/hash map type enabled in your kernel?
BPF_HASH(delmap, u32, struct deldata, 100000000);
^
/virtual/include/bcc/helpers.h:119:26: note: expanded from macro 'BPF_HASH'
  BPF_HASHX(__VA_ARGS__, BPF_HASH4, BPF_HASH3, BPF_HASH2, BPF_HASH1)(__VA_ARGS__)_

For smaller numbers there is no problem and the program works.

$ ulimit -a
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 60732
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 60732
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

**Comment by yonghong-song** [comment]
This is not a bug. With 100M elements, the hash table maximum size may reach 64_bytes * 100M = 6.4G. The maximum hash table size (roughly) is 4GB in the kernel implementation.
