### ISSUE TITLE
use of undeclared identifier 'bpf_object_open_opts'

### ISSUE THREAD

**Issue by longhao54** [iovisor/bcc#4239]
I'm trying to compile tcplife

kernel version: 5.15.0-46-generic
system: Ubuntu 22.04.1 LTS
clang Version: Ubuntu clang version 14.0.0-1ubuntu1
bpftool Version: /usr/lib/linux-tools/5.15.0-46-generic/bpftool v5.15.39

Workdir: bcc/libbpf-tools

run: 
    clang -g -O2 -target bpf -D__TARGET_ARCH_x86_64 -I/usr/include/x86_64-linux-gnu -I. -c tcplife.bpf.c -o tcplife.bpf.o
    bpftool gen skeleton tcplife.bpf.o > tcplife.skel.h
    is successed

but when i try command: 
    clang -g -O2 -Wall -I . -c tcplife.c -o tcplife.o   faild  and show

tcplife.c:145:2: warning: implicit declaration of function 'LIBBPF_OPTS' is invalid in C99 [-Wimplicit-function-declaration]
        LIBBPF_OPTS(bpf_object_open_opts, open_opts);
        ^
tcplife.c:145:14: error: use of undeclared identifier 'bpf_object_open_opts'
        LIBBPF_OPTS(bpf_object_open_opts, open_opts);
                    ^
tcplife.c:145:36: error: use of undeclared identifier 'open_opts'
        LIBBPF_OPTS(bpf_object_open_opts, open_opts);
                                          ^
tcplife.c:164:25: error: use of undeclared identifier 'open_opts'
        err = ensure_core_btf(&open_opts);
                               ^
tcplife.c:170:32: error: use of undeclared identifier 'open_opts'
        obj = tcplife_bpf__open_opts(&open_opts);
                                      ^
tcplife.c:212:24: error: too many arguments to function call, expected 3, have 6
                              handle_event, handle_lost_events, NULL, NULL);
                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/bpf/libbpf.h:682:1: note: 'perf_buffer__new' declared here
perf_buffer__new(int map_fd, size_t page_cnt,
^
tcplife.c:244:20: error: use of undeclared identifier 'open_opts'
        cleanup_core_btf(&open_opts);
                          ^
1 warning and 6 errors generated.

**Comment by chenhengqi** [comment]
Just run `make` to build the tools.
