### ISSUE TITLE
Complie error using llvm-6.0

### ISSUE THREAD

**Issue by XiDianZuoYun** [iovisor/bcc#4283]
Sorry to bother you, when I followed the installation tutorial of INSTALL.MD to install, I got the following error in the make step:
`/usr/lib/llvm-6.0/include/clang/AST/DeclOpenMP.h:97:1: warning: multi-line comment [-Wcomment]
 /// #pragma omp declare reduction (foo : int,float : omp_out += omp_in) \
 ^
/home/zhanghongyi/github/bcc/src/cc/frontends/clang/loader.cc: In function ‘int ebpf::{anonymous}::CreateFromArgs(clang::CompilerInvocation&, const ArgStringList&, clang::DiagnosticsEngine&)’:
/home/zhanghongyi/github/bcc/src/cc/frontends/clang/loader.cc:183:77: error: no matching function for call to ‘clang::CompilerInvocation::CreateFromArgs(clang::CompilerInvocation&, const ArgStringList&, clang::DiagnosticsEngine&)’
   return clang::CompilerInvocation::CreateFromArgs(invocation, ccargs, diags);
                                                                             ^
In file included from /usr/lib/llvm-6.0/include/clang/Frontend/CompilerInstance.h:16:0,
                 from /home/zhanghongyi/github/bcc/src/cc/frontends/clang/loader.cc:43:
/usr/lib/llvm-6.0/include/clang/Frontend/CompilerInvocation.h:144:15: note: candidate: static bool clang::CompilerInvocation::CreateFromArgs(clang::CompilerInvocation&, const char* const*, const char* const*, clang::DiagnosticsEngine&)
   static bool CreateFromArgs(CompilerInvocation &Res,
               ^~~~~~~~~~~~~~
`
How can I fix this erro? 
By the way, I have to overwirte CMakeList.txt like the following picture, because configure will fail without this: 
![image](https://user-images.githubusercontent.com/29877338/196163914-60f5b750-2fc7-47bd-97cb-a6d89d7e2cf6.png)

**Comment by chenhengqi** [comment]
Please upgrade your LLVM to version 11 or above.

**Comment by XiDianZuoYun** [comment]
> 

Thank you, the problem is solved, after my llvm version has been updated to 12.x
