### ISSUE TITLE
installing guide for wsl2 out of date

### ISSUE THREAD

**Issue by log2cn** [iovisor/bcc#4304]
installing guide is out of date for the latest wsl2, i.e. kernel 5.15.68.1 in 29th.September.

**Comment by chenhengqi** [comment]
Please help with a PR, thanks.

**Comment by log2dx** [comment]
it seems that the latest WSL2's `.config` by default enables no modules.
I used `make allmodconfig`, it **does** work but spends a long long long time to compile.
