### ISSUE TITLE
biosnoop.py binary error

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#431]
From comments on my post http://www.brendangregg.com/blog/2016-03-05/linux-bpf-superpowers.html :

"
Hi, using biosnoop.py actually returns a bunch of TypeError exceptions for me.
Linux kernel version: 4.4.3-1
Python version: 3.5.1

sudo ./biosnoop.py
...
Traceback (most recent call last):
File "_ctypes/callbacks.c", line 234, in 'calling callback function'
File "/usr/lib/python3.5/site-packages/bcc/table.py", line 376, in <lambda>
fn = _RAW_CB_TYPE(lambda _, data, size: callback(cpu, data, size))
File "./biosnoop.py", line 157, in print_event
if not re.match('\?', event.name):
File "/usr/lib/python3.5/re.py", line 163, in match
return _compile(pattern, flags).match(string)

Problem seems to be that event.name contains binary chars, while the regexp at line 157 of biosnoop.py expects printable characters.
Rewriting line 157 as follows:
if not re.match(b'\?', event.name):
solves the issue on my machine.
Disclaimer: I'm not a Python expert.
"

**Comment by drzaeus77** [comment]
That change is fine. Want me to commit on their behalf?
