### ISSUE TITLE
Does kretprobe only get return values? Is there any way to get parameters from the kretprobe?

### ISSUE THREAD

**Issue by XiaoNuoZ** [iovisor/bcc#4310]
```
SEC("kretprobe/vfs_rename")
int trace_vfs_rename_end (struct pt_regs *ctx) 
{
	struct renamefile_event_end_t event = {};
	event.id = bpf_get_current_pid_tgid();
    event.code = PT_REGS_RC(ctx);
    bpf_perf_event_output(ctx, &rename_end_event, BPF_F_CURRENT_CPU, &event, sizeof(event));

	return 0;
}
```

It can only get the return value, but I need the file name

**Comment by chenhengqi** [comment]
You can capture the arguments at kprobe and store them in a map.

If you use a recent enough kernel, you can try fexit.

**Comment by XiaoNuoZ** [comment]
> 
thank you for your help.
but, I use kprobe to get parameters, it can't prevent error sending, so I have to use kretprobe to get code to prevent error printing.  For example, use a regular user to move the root user's files.
I want to execute the vfs_rename function after it finishes, so I want to be able to get the file name by taking arguments in the kretprobe.

**Comment by chenhengqi** [comment]
FYI, please refer to:

https://github.com/iovisor/bcc/blob/aee989c72ca6607a013f3f8927eb09e17d5f41bb/libbpf-tools/gethostlatency.bpf.c#L43-L52

**Comment by XiaoNuoZ** [comment]
> FYI, please refer to:
> 
> https://github.com/iovisor/bcc/blob/aee989c72ca6607a013f3f8927eb09e17d5f41bb/libbpf-tools/gethostlatency.bpf.c#L43-L52
thanks a lot
