### ISSUE TITLE
Why does my executable fail to execute on other Linux systems? 

### ISSUE THREAD

**Issue by XiaoNuoZ** [iovisor/bcc#4320]
Hi there,
I am an ebpf novice and use the go development language.
The kernel of the development environment is 5.10.0,It runs without any problems.
The kernel of a system that failed to execute the program is 4.19.0.It doesn't have a /sys/kernel/btf folder.
![image](https://user-images.githubusercontent.com/46923935/200468113-41c208f6-f960-45fd-ad79-725abd7c7c3d.png)

so,I changed the address of `cilium/ebpf/btf/btf.go/LoadKernelSpec()` to the current project and downloaded a corresponding kernel of vmlinux.
![image](https://user-images.githubusercontent.com/46923935/200468778-24ab2706-c3fb-411b-83ce-9b4d5f9460b4.png)
![image](https://user-images.githubusercontent.com/46923935/200468837-685ca083-6593-47e4-ad57-166df80b7bc7.png)

I don't know if this is the right migration.It sent an error.
![image](https://user-images.githubusercontent.com/46923935/200467976-cc180bfb-f38b-48d6-b0cc-d76d34227542.png)

Can you help me?
Thanks!

**Comment by chenhengqi** [comment]
Recompile your kernel with `CONFIG_DEBUG_INFO_BTF` enabled or refer to [btfhub](https://github.com/aquasecurity/btfhub).

**Comment by XiaoNuoZ** [comment]
> 重新编译你的内核`CONFIG_DEBUG_INFO_BTF`启用或参考[btfhub](https://github.com/aquasecurity/btfhub)。



> 
Thank you for your help!
CONFIG_DEBUG_INFO_BTF has not been changed, it should be correct
![image](https://user-images.githubusercontent.com/46923935/200581033-b9df06bc-67a3-4b52-9b54-f8eda9a66b1e.png)
I adopted the cilium/ebpf framework,It doesn't seem to have a LIBBPF OPTS equivalent
