### ISSUE TITLE
Error saving to map in a loop

### ISSUE THREAD

**Issue by andreyandvitya** [iovisor/bcc#4325]
Hi!
I'm trying to write a tool that collects metrics about asynchronous operations. To do this, I need to trace syscall sys_enter_io_submit. This syscall has an argument which is an array of pointers to a structure iocb (args->iocbpp). I am looping through these elements and trying to save some of them to use in another syscall. But when i try to add element to map then I get error. I also tried saving u64 elements not related to args->iocbpp to another map instead, but got the same error.
Tell me what I'm doing wrong please.

Specs:
- ubuntu 22.04
- kernel version 5.19
- bcc builded from source code (last version)

Script and error below.

**Script**:
```
from bcc import BPF

bpf_source = """
#include <linux/aio_abi.h>

BPF_HASH(mymap, struct iocb*, u64);

TRACEPOINT_PROBE(syscalls, sys_enter_io_submit)
{    
    u64 counter = 0;

    for(u64 i = 0; i < args->nr; ++i) {
        if((args->iocbpp[i])->aio_lio_opcode == 0) {
            mymap.update(&(args->iocbpp[i]), &counter);
            counter++;
        }
    }
    return 0;
}
"""

bpf = BPF(text=bpf_source)
print("program loaded")

try:
    while 1: pass
except KeyboardInterrupt:
    exit()
```

**Error**:
```
bpf: Failed to load program: Permission denied
reg type unsupported for arg#0 function tracepoint__syscalls__sys_enter_io_submit#27
0: R1=ctx(off=0,imm=0) R10=fp0
; TRACEPOINT_PROBE(syscalls, sys_enter_io_submit)
0: (bf) r6 = r1                       ; R1=ctx(off=0,imm=0) R6_w=ctx(off=0,imm=0)
1: (b7) r7 = 0                        ; R7_w=0
; u64 counter = 0;
2: (7b) *(u64 *)(r10 -8) = r7         ; R7_w=P0 R10=fp0 fp-8_w=00000000
; for(u64 i = 0; i < args->nr; ++i) {
3: (79) r1 = *(u64 *)(r6 +24)         ; R1_w=scalar() R6_w=ctx(off=0,imm=0)
; for(u64 i = 0; i < args->nr; ++i) {
4: (15) if r1 == 0x0 goto pc+5        ; R1_w=scalar()
5: (b7) r8 = 0                        ; R8_w=0
6: (05) goto pc+5
; if((args->iocbpp[i])->aio_lio_opcode == 0) {
12: (79) r2 = *(u64 *)(r6 +32)        ; R2_w=scalar() R6=ctx(off=0,imm=0)
; if((args->iocbpp[i])->aio_lio_opcode == 0) {
13: (0f) r2 += r7                     ; R2_w=scalar() R7=P0
14: (79) r2 = *(u64 *)(r2 +0)
R2 invalid mem access 'scalar'
processed 10 insns (limit 1000000) max_states_per_insn 0 total_states 1 peak_states 1 mark_read 1

Traceback (most recent call last):
  File "/home/andr/loop.py", line 22, in <module>
    bpf = BPF(text=bpf_source)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 487, in __init__
    self._trace_autoload()
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 1465, in _trace_autoload
    fn = self.load_func(func_name, BPF.TRACEPOINT)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 526, in load_func
    raise Exception("Failed to load BPF program %s: %s" %
Exception: Failed to load BPF program b'tracepoint__syscalls__sys_enter_io_submit': Permission denied

```

**Comment by chenhengqi** [comment]
```
struct iocb* key = args->iocbpp[i];
mymap.update(&key, &counter);
```

**Comment by andreyandvitya** [comment]
> ```
> struct iocb* key = args->iocbpp[i];
> mymap.update(&key, &counter);
> ```

Thanks for the answer!
This is the first thing I tried myself. This gives the same error.

**Comment by chenhengqi** [comment]
```
bpf_probe_read_kernel(&opcode, sizeof(opcode), &key->aio_lio_opcode);
```

**Comment by andreyandvitya** [comment]
Thanks, this helped. But now I got the error I got from the beginning. This program cannot iterate the required number of times in a loop. The maximum number of iterations it can do is approximately 45,000 cycles. (tried to replace args->nr with a constant). I tried to make the cycle as easy as possible.
I wanted to ask if there is some way to iterate over the data from the arguments the required number of times so that there is no "Program too large" error. I tried using bpf_loop but that didn't work. Perhaps I used it incorrectly (I could not find examples of its use).
Could you help with this? Thanks for your time!

Code:
```
#include <linux/aio_abi.h>

BPF_HASH(mymap, struct iocb*, u64);

TRACEPOINT_PROBE(syscalls, sys_enter_io_submit)
{    
    u64 counter = 0;
    
    struct iocb **iocbs;
    bpf_probe_read_kernel(&iocbs, sizeof(iocbs), &args->iocbpp);

    u64 opcode = 0;
    struct iocb *key;
    for(u64 i = 0; i < args->nr; ++i) {
        bpf_probe_read_kernel(&key, sizeof(key), &(iocbs[i]));
        bpf_probe_read_kernel(&opcode, sizeof(opcode), &key->aio_lio_opcode);

        mymap.update(&key, &counter);
    }
    return 0;
}
```

Error
```
bpf: Argument list too long. Program  too large (39 insns), at most 4096 insns
```

**Comment by chenhengqi** [comment]
Isn't 45000 large enough ?

Typically, we have the following pattern to convince the BPF verifier that the loop is finite:

https://github.com/iovisor/bcc/blob/3eb3875228aec6b6ab71b43da6114f9c610ec1f6/libbpf-tools/execsnoop.bpf.c#L86

https://github.com/iovisor/bcc/blob/3eb3875228aec6b6ab71b43da6114f9c610ec1f6/libbpf-tools/tcpconnect.bpf.c#L59

**Comment by andreyandvitya** [comment]
Thanks a lot, it helped!
Sorry, I incorrectly stated my thought above. In my example, args->nr in practical examples was always equal to 1. But as I understand it, the verifier thought that this number could be much larger and did not allow the program to start. And if I put a large constant instead of args->nr (for example, 45000), then the verifier stopped giving an error.

But in my case, this number could potentially be very large (<=65535). And as I understand it, it will not be possible to run the program, because it is really very large for the verifier?

**Comment by chenhengqi** [comment]
FYI, https://github.com/iovisor/bcc/issues/3846#issuecomment-1039343388 .
