### ISSUE TITLE
tcplife: make output line-buffered

### ISSUE THREAD

**Issue by reinierpost** [iovisor/bcc#4329]
I'd like to request a new option for `tcplife`: line-buffered output.

Why:

We've been setting up a new TCP-based service and we'd like to monitor its performance. In particular, we'd like to log the duration of the TCP connections made. It seems`tcplife` should seems to be able to do this, so I created a super simple systemd service that calls `tcplife` and made a few test calls. No output. I then called `tcplife | cat`. No output. Not even the header.

This is easily fixed by inserting
```
import functools
print = functools.partial(print, flush=True)
```
after the existing `import`s, to make making `tcplife` use line-buffered output.

This will allow anyone to use `tcplife` to set up a service to monitor (low-volume) TCP connections.
I suppose it would be better to add this as a command-line option.

More options could be added to improve this, e.g. an option to omit the header and one to print more detailed timestamps.

**Comment by reinierpost** [comment]
This can already be achieved by using `sudo python3 -u /usr/sbin/tcplife-bpfcc` (I'm on Ubuntu), but it would be nice to have the option in the utility itself.

**Comment by chenhengqi** [comment]
See #3922. Feel free to open a PR.

Personally, I prefer the `python3 -u` way, so that we don't have to touch every tool.

**Comment by reinierpost** [comment]
Good point. I'm closing this and continuing there.
I didn't at all expect this tool to buffer its output; it's a logging tool after all.

**Comment by reinierpost** [comment]
Closing, as the issue is more general.
