### ISSUE TITLE
Access the elements of the kernel structure

### ISSUE THREAD

**Issue by andreyandvitya** [iovisor/bcc#4343]
A few days ago I was dealing with the iteration problem in a loop(#4325). It was solved by a constant limitation of the number of iterations. 
But now I'm trying to access the elements of the kernel structure(iocbpp) in a loop (iocbpp This is an array where the element is a pointer to the iocb structure).
I was able to get an iocbpp array(res = 0):
```
struct iocb **iocbs;
res = bpf_probe_read_kernel(&iocbs, sizeof(iocbs), &(args->iocbpp));
```
But then I want to get the element iocbs[i]->aio_lio_opcode. I try to do this:
```
u64 opcode = 0;
struct iocb *cb;

for(u64 i = 0; i < args->nr && i < 100; ++i) {
    res1 = bpf_probe_read_kernel(&cb, sizeof(cb), &iocbs[i]);
    res2 = bpf_probe_read_kernel(&opcode, sizeof(opcode), &(cb->aio_lio_opcode));
}
```
But in this case I get an error: ```res1 = -34 and res2 = -34```.
Please tell me what the problem may be.

Thanks

Specs:
- ubuntu 22.04
- kernel version 5.19
- bcc builded from source code (last version)

Full Script:
```
from bcc import BPF

bpf_source = """
#include <linux/aio_abi.h>

TRACEPOINT_PROBE(syscalls, sys_enter_io_submit)
{
    struct iocb **iocbs;
    int res = bpf_probe_read_kernel(&iocbs, sizeof(iocbs), &(args->iocbpp));

    u64 opcode = 0;
    struct iocb *cb;

    for(u64 i = 0; i < args->nr && i < 100; ++i) {
        res = bpf_probe_read_kernel(&cb, sizeof(cb), &iocbs[i]);
        res = bpf_probe_read_kernel(&opcode, sizeof(opcode), &(cb->aio_lio_opcode));
    }
    return 0;
}
"""

bpf = BPF(text=bpf_source)
print("program loaded")

try:
    while 1: pass
except KeyboardInterrupt:
    exit()
```

**Comment by woodpenker** [comment]
`sizeof(iocbs)` means sizeof struct iocb ** pointer, dito sizeof(cb). And iocbs or cb is NULL pointer with no mem initted.

**Comment by andreyandvitya** [comment]
Yes, it is, but it shouldn't matter here. ```sizeof()``` gives just the number of bytes to copy. In my case it is 8 and this is true for the pointer size. But I still tried to allocate ```cb``` and ```iocbs```. If I understand correctly, bpf does not make it possible to dynamically allocate memory using malloc for example. So I used a temporary element to allocate pointers, but it gives the same error:
```
struct iocb tmp_cb = {0};
struct iocb *cb = &tmp_cb;
struct iocb **iocbs = &cb;

int res = bpf_probe_read_kernel(&iocbs, sizeof(iocbs), &(args->iocbpp));
u64 opcode = 0;

for(u64 i = 0; i < args->nr && i < MAX_IOCBS; ++i) {
    res = bpf_probe_read_kernel(&cb, sizeof(u64), &iocbs[i]);
    res = bpf_probe_read_kernel(&opcode, sizeof(opcode), &(cb->aio_lio_opcode));
}
```

Please tell me if it is possible to somehow get a field from the iocbpp structure in a loop(```iocbpp[i]->aio_lio_opcode```)?
```u64 lio_opcode = (args->iocbpp[i])->aio_lio_opcode;``` and using
```bpf_probe_read_kernel(&lio_opcode, sizeof(lio_opcode), &((args->iocbpp[i])->aio_lio_opcode));``` is not suitable. This usage gives an error ```R1 invalid mem access 'scalar'```

**Comment by yonghong-song** [comment]
The error -34 is:

    #define ERANGE          34      /* Math result not representable */

basically means the address is not in kernel address range. Based on the name of tracepoint (sys_enter_io_summit), I suspect args->iocbpp is a user space address. It is possible that the initial args->iocbpp is copied to kernel so that is why bpf_probe_read_kernel is successful. But later pointer chasing might need bpf_probe_read_user() instead.

**Comment by andreyandvitya** [comment]
Thank you very much for your time!
Tried using bpf_probe_read_user and it helped.
