### ISSUE TITLE
offwaketime -p no stacks

### ISSUE THREAD

**Issue by ceeaspb** [iovisor/bcc#436]
For some reason I can't get any stacks when specifying a pid for offwaketime.

kernel:
Linux ubuntu-xenial 4.4.0-12-generic #28-Ubuntu SMP Wed Mar 9 00:33:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

bcc installed from source

**Comment by drzaeus77** [comment]
@brendangregg Seems that pid is uninitialized in `oncpu`:

```c
int oncpu(struct pt_regs *ctx, struct task_struct *p) {
    u32 pid;
    u64 ts, *tsp;

    // record previous thread sleep time
    if (FILTER) {
        pid = p->pid;
```
followed by:
```python
if args.pid:
    filter = 'pid == %s' % args.pid

```

**Comment by brendangregg** [comment]
thanks @drzaeus77 . fix coming.

**Comment by ceeaspb** [comment]
@brendangregg @drzaeus77 thanks. unfortunately this didn't seem to work for me. I'll try and see if I can get any debug out of it / else suggest some.

**Comment by evverx** [comment]
@ceeaspb , maybe https://github.com/iovisor/bcc/issues/558
`offwaketime` doesn't capture those offcpus too.
