### ISSUE TITLE
offwaketime userspace stack

### ISSUE THREAD

**Issue by ceeaspb** [iovisor/bcc#437]
Would it be possible to get the userspace stack? 
eg. I can't see where these calls are coming from in the java runtime. 

```
    waker:           java
    ffffffff8181c832 entry_SYSCALL_64_fastpath
    ffffffff81101861 sys_futex
    ffffffff8110162e do_futex
    ffffffff810ffa2c futex_wake_op
    -                -
    ffffffff81818755 schedule
    ffffffff810fe902 futex_wait_queue_me
    ffffffff810fec16 futex_wait
    ffffffff81101400 do_futex
    ffffffff81101861 sys_futex
    ffffffff8181c832 entry_SYSCALL_64_fastpath
    target:          java
        19974615
```

**Comment by brendangregg** [comment]
Soon; this functionality should come with #231 , which also means kernel support and a newer kernel. @4ast has already coded it (stackmap) which made it into net-next, and hopefully the kernel very soon. So that will probably mean 4.6.

The trick here is that we're in kernel context with kernel regs, but we want to start walking the user-level frame pointer. So BPF needs task_pt_regs() or an equivalent. Anyway, it's coming.

As for the use case -- yes, I've seen this exact Java futex() stack, and want the Java methods to see which lock it is. :)

**Comment by ceeaspb** [comment]
ok thanks, not long then.

**Comment by anarazel** [comment]
I started to work on this (for offwaketime and offcpu), but ran into a pretty high wall. If I understand correctly `BPF_F_USER_STACK` builds userspace backtraces using frame pointers. Unfortunately glibc, even when adding  `-fno-omit-frame-pointer` to `CFLAGS`, compiles the code for a number of syscalls with explicit `-fomit-frame-pointer` additions. That's because the 6th argument is transported in `%ebp` for those.  Relevant for offwaketime/offcpu are `epoll_wait` (via `epoll_pwait`) and `semtimedop`.

```
andres@alap3:~/src/glibc$ ack 'CFLAGS.*fomit-frame'
sysdeps/unix/sysv/linux/Makefile
146:CFLAGS-getpid.o = -fomit-frame-pointer
147:CFLAGS-getpid.os = -fomit-frame-pointer

sysdeps/unix/sysv/linux/i386/Makefile
7:CFLAGS-epoll_pwait.o += -fomit-frame-pointer
8:CFLAGS-epoll_pwait.os += -fomit-frame-pointer
9:CFLAGS-mmap.o += -fomit-frame-pointer
10:CFLAGS-mmap.os += -fomit-frame-pointer
11:CFLAGS-mmap64.o += -fomit-frame-pointer
12:CFLAGS-mmap64.os += -fomit-frame-pointer
17:CFLAGS-semtimedop.o += -fomit-frame-pointer
18:CFLAGS-semtimedop.os += -fomit-frame-pointer

stdlib/Makefile
108:CFLAGS-system.os = -fomit-frame-pointer

nptl/Makefile
450:CFLAGS-pthread_self.os += -fomit-frame-pointer

posix/Makefile
207:CFLAGS-wordexp.os = -fomit-frame-pointer
212:CFLAGS-spawn.os = -fomit-frame-pointer
214:CFLAGS-spawnp.os = -fomit-frame-pointer
216:CFLAGS-spawni.os = -fomit-frame-pointer
221:CFLAGS-execve.os = -fomit-frame-pointer
222:CFLAGS-fexecve.os = -fomit-frame-pointer
223:CFLAGS-execv.os = -fomit-frame-pointer
224:CFLAGS-execle.os = -fomit-frame-pointer
225:CFLAGS-execl.os = -fomit-frame-pointer
226:CFLAGS-execvp.os = -fomit-frame-pointer
227:CFLAGS-execlp.os = -fomit-frame-pointer
```

For me epoll_wait()  is a real problem - for now I'm probably going to just reimplement it manually via the the epoll_wait syscall instead of epoll_pwait as glibc does. But I bet this problem is going to become bigger :(

**Comment by ceeaspb** [comment]
Prompted for some reason by this thread, http://mail.openjdk.java.net/pipermail/hotspot-dev/2016-November/025142.html, and after an evening's copy and pasting from the support like you said that is now in the other tools, I think I have this working. eg.
I should be able to put together a PR for it.

@brendangregg I could probably also merge/update your chaintest code if you didn't take it any further / if that is of interest? ie. https://gist.github.com/brendangregg/c67039252268ec5e66ba

```
    waker:           java 4656
    7f52790b070a     start_thread
    7f5279ab348d     [unknown]
    7f5279aaf541     [unknown]
    7f52787efce6     jni_CallStaticVoidMethod
    7f52787ed5c7     jni_invoke_static(JNIEnv_*, JavaValue*, _jobject*, JNICallType, _jmethodID*, JNI_ArgumentPusher*, Thread*) [clone .isra.82] [clone .constprop.89]
    7f52787ccd43     JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*)
    7f52610004e7     call_stub
    7f5261007e54     Interpreter
    7f52611b027c     Ljava/util/concurrent/Executors$DelegatedExecutorService;::submit->Ljava/util/concurrent/AbstractExecutorService;::submit->Ljava/util/concurrent/ThreadPoolExecutor;::execute->Ljava/util/concurrent/LinkedBlockingQueue;::offer->Ljava/util/concurrent/LinkedBlockingQueue;::signalNotEmpty->Ljava/util/concurrent/locks/ReentrantLock;::unlock->Ljava/util/concurrent/locks/AbstractQueuedSynchronizer;::release->Ljava/util/concurrent/locks/AbstractQueuedSynchronizer;::unparkSuccessor->Ljava/util/concurrent/locks/LockSupport;::unpark
    7f52611858fc     Lsun/misc/Unsafe;::unpark
    ffffffff83e8bbbb entry_SYSCALL_64_fastpath
    ffffffff8370c785 SyS_futex
    ffffffff8370c5a0 do_futex
    ffffffff8370a5a3 futex_wake_op
    -                -
    ffffffff836ac511 finish_task_switch
    ffffffff83e86e46 schedule
    ffffffff83709344 futex_wait_queue_me
    ffffffff83709f96 futex_wait
    ffffffff8370c3e7 do_futex
    ffffffff8370c785 SyS_futex
    ffffffff83e8bbbb entry_SYSCALL_64_fastpath
    7f52790b6510     __pthread_cond_wait
    178              [unknown]
    7f52611727ea     Lsun/misc/Unsafe;::park
    7f5261196cac     Ljava/util/concurrent/locks/AbstractQueuedSynchronizer$ConditionObject;::await->Ljava/util/concurrent/locks/LockSupport;::park
    7f52611941bc     Ljava/util/concurrent/LinkedBlockingQueue;::take
    7f52611927bc     Ljava/util/concurrent/ThreadPoolExecutor;::getTask
    7f5261007d80     Interpreter
    7f5261007ffd     Interpreter
    7f5261008042     Interpreter
    7f52610004e7     call_stub
    7f52787ccd43     JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*)
    7f52787ca2b7     JavaCalls::call_virtual(JavaValue*, KlassHandle, Symbol*, Symbol*, JavaCallArguments*, Thread*)
    7f52787ca897     JavaCalls::call_virtual(JavaValue*, Handle, KlassHandle, Symbol*, Symbol*, Thread*)
    7f527880c164     thread_entry(JavaThread*, Thread*)
    7f5278b79a2b     JavaThread::thread_main_inner()
    7f5278b79eef     JavaThread::run()
    7f5278a21192     java_start(Thread*)
    7f52790b070a     start_thread
    target:          java 4657
```

**Comment by ceeaspb** [comment]
I didn't spot #545

**Comment by andredasilvapinto** [comment]
Was this ever added?

I can't see Java stacks when using offwaketime:

`    waker:           epollEventLoopG 7667
    entry_SYSCALL_64_after_hwframe
    do_syscall_64
    __x64_sys_futex
    do_futex
    futex_wake
    wake_up_q
    try_to_wake_up
    _raw_spin_unlock_irqrestore
    ret_from_intr
    do_IRQ
    irq_exit
    __softirqentry_text_start
    net_rx_action
    ena_io_poll
    ena_clean_rx_irq
    napi_gro_frags
    netif_receive_skb_internal
    __netif_receive_skb_one_core
    ip_rcv
    ip_local_deliver
    ip_local_deliver_finish
    tcp_v4_rcv
    tcp_v4_do_rcv
    tcp_rcv_established
    tcp_data_queue
    sock_def_readable
    __wake_up_common_lock
    __wake_up_common
    ep_poll_callback
    __wake_up_common
    --               --
    finish_task_switch
    __sched_text_start
    schedule
    schedule_hrtimeout_range_clock
    ep_poll
    do_epoll_wait
    __x64_sys_epoll_pwait
    do_syscall_64
    entry_SYSCALL_64_after_hwframe
    epoll_pwait
    [unknown]
    target:          epollEventLoopG 7654
        1000
`

notice the `[unknown]` block.

This is with bcc 0.10.0-1.amzn2.0.1 and openjdk 11.0.6 running:

`offwaketime -m 1000 -p $PID --stack-storage-size 900000 30`
