### ISSUE TITLE
error: incomplete definition of type 'struct signal_struct'

### ISSUE THREAD

**Issue by nihilitysoul** [iovisor/bcc#4403]
My kernel version is 5.0.0-23-generic, now I have change my kernel to 5.4.0-135-generic,but it still not work.

```
/virtual/main.c:62:61: error: incomplete definition of type 'struct signal_struct'
    bpf_probe_read_kernel_str(&pgid, sizeof(pgid), t->signal->pids[2]);
                                                   ~~~~~~~~~^
include/linux/posix-timers.h:154:9: note: forward declaration of 'struct signal_struct'
        struct signal_struct    *it_signal;
               ^
/virtual/main.c:118:61: error: incomplete definition of type 'struct signal_struct'
    bpf_probe_read_kernel_str(&pgid, sizeof(pgid), t->signal->pids[2]);
                                                   ~~~~~~~~~^
include/linux/posix-timers.h:154:9: note: forward declaration of 'struct signal_struct'
        struct signal_struct    *it_signal;
               ^
2 errors generated.
Traceback (most recent call last):
  File "escape_detect.py", line 132, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 479, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>
```

Can someone help me?

**Comment by chenhengqi** [comment]
Please make sure you have proper kernel devel package installed.

**Comment by nihilitysoul** [comment]
> Are they linux-kernel-headers and kernel-package?
![1](https://user-images.githubusercontent.com/67935208/209622506-4ec9ecc6-43b7-456c-b16e-4693dc9ca579.png)
![2](https://user-images.githubusercontent.com/67935208/209622524-aedfcb0d-1b90-41af-bc7f-f4c030b6500b.png)

**Comment by chenhengqi** [comment]
https://github.com/iovisor/bcc/blob/master/INSTALL.md#ubuntu---binary

**Comment by nihilitysoul** [comment]
> https://github.com/iovisor/bcc/blob/master/INSTALL.md#ubuntu---binary

![1](https://user-images.githubusercontent.com/67935208/209756934-11129bc3-1fef-45de-8a03-51fba8cc472e.png)
I choose [building from source](https://github.com/iovisor/bcc/blob/master/INSTALL.md#ubuntu---source) to install the lastest version.

**Comment by chenhengqi** [comment]
Please post a complete reproducible test case here.

**Comment by nihilitysoul** [comment]
> Please post a complete reproducible test case here.
The full code is here, thank you very much for helping me.
`from __future__ import print_function
from bcc import BPF
import argparse
from subprocess import call
import os
import numpy as np


# arguments
parser = argparse.ArgumentParser(
    description="Detect docker escape attack",
    formatter_class=argparse.RawDescriptionHelpFormatter)
parser.add_argument("-e", "--establish", action="store_true",
    help="establish the path database")
parser.add_argument("-c", "--clear", action="store_true",
    help="clear the screen")
parser.add_argument("interval", nargs="?", default=1,
    help="output interval, in seconds")
args = parser.parse_args()
mode = int(args.establish)
clear = int(args.clear)
interval = int(args.interval)


# load BPF program
bpf_text = """
#include <uapi/linux/ptrace.h>
#include <linux/fs.h>
#include <linux/sched.h>


struct path_t{
    u32 pid;
    u32 pgid;
    char comm[TASK_COMM_LEN];
    char filename[NAME_MAX];
};

BPF_PERF_OUTPUT(paths);

TRACEPOINT_PROBE(syscalls, sys_enter_open)
{
    struct task_struct *t = (struct task_struct *)bpf_get_current_task();
    u32 pgid;
    bpf_probe_read_kernel_str(&pgid, sizeof(pgid), t->signal->pids[2]);
    struct path_t path = {};
    path.pgid = pgid;
    path.pid = bpf_get_current_pid_tgid() >> 32;
    bpf_probe_read_user_str(path.filename, NAME_MAX, args->filename);
    bpf_get_current_comm(&path.comm, TASK_COMM_LEN);
    paths.perf_submit(args, &path, sizeof(path));
}

TRACEPOINT_PROBE(syscalls, sys_enter_openat)
{
    struct task_struct *t = (struct task_struct *)bpf_get_current_task();
    u32 pgid;
    bpf_probe_read_kernel_str(&pgid, sizeof(pgid), t->signal->pids[2]);
    struct path_t path = {};
    path.pgid = pgid;
    path.pid = bpf_get_current_pid_tgid() >> 32;
    bpf_probe_read_user_str(path.filename, NAME_MAX, args->filename);
    bpf_get_current_comm(&path.comm, TASK_COMM_LEN);
    paths.perf_submit(args, &path, sizeof(path));
}
"""

b = BPF(text=bpf_text)

print('Tracing... Output every %d secs. Hit Ctrl-C to end' % interval)

def print_path(cpu, data, size):
    event = b["paths"].event(data)
    filename = event.filename.decode()
    order = filename.rfind('/')
    if order != -1:
        path = filename[:order]
        print(path)

b["paths"].open_perf_buffer(print_path)

exiting = 0
while 1:
    try:
        b.perf_buffer_poll()
    except KeyboardInterrupt:
        exiting = 1

    if clear:
        call("clear")
    else:
        pass

    if exiting:
        print("Detaching...")
        exit()
`

**Comment by nihilitysoul** [comment]
> Please post a complete reproducible test case here.

The full code is here, thank you very much for helping me.

```
from __future__ import print_function
from bcc import BPF
import argparse
from subprocess import call
import os
import numpy as np


# arguments
parser = argparse.ArgumentParser(
    description="Detect docker escape attack",
    formatter_class=argparse.RawDescriptionHelpFormatter)
parser.add_argument("-e", "--establish", action="store_true",
    help="establish the path database")
parser.add_argument("-c", "--clear", action="store_true",
    help="clear the screen")
parser.add_argument("interval", nargs="?", default=1,
    help="output interval, in seconds")
args = parser.parse_args()
mode = int(args.establish)
clear = int(args.clear)
interval = int(args.interval)


# load BPF program
bpf_text = """
#include <uapi/linux/ptrace.h>
#include <linux/fs.h>
#include <linux/sched.h>


struct path_t{
    u32 pid;
    u32 pgid;
    char comm[TASK_COMM_LEN];
    char filename[NAME_MAX];
};

BPF_PERF_OUTPUT(paths);

TRACEPOINT_PROBE(syscalls, sys_enter_open)
{
    struct task_struct *t = (struct task_struct *)bpf_get_current_task();
    u32 pgid;
    bpf_probe_read_kernel_str(&pgid, sizeof(pgid), t->signal->pids[2]);
    struct path_t path = {};
    path.pgid = pgid;
    path.pid = bpf_get_current_pid_tgid() >> 32;
    bpf_probe_read_user_str(path.filename, NAME_MAX, args->filename);
    bpf_get_current_comm(&path.comm, TASK_COMM_LEN);
    paths.perf_submit(args, &path, sizeof(path));
}

TRACEPOINT_PROBE(syscalls, sys_enter_openat)
{
    struct task_struct *t = (struct task_struct *)bpf_get_current_task();
    u32 pgid;
    bpf_probe_read_kernel_str(&pgid, sizeof(pgid), t->signal->pids[2]);
    struct path_t path = {};
    path.pgid = pgid;
    path.pid = bpf_get_current_pid_tgid() >> 32;
    bpf_probe_read_user_str(path.filename, NAME_MAX, args->filename);
    bpf_get_current_comm(&path.comm, TASK_COMM_LEN);
    paths.perf_submit(args, &path, sizeof(path));
}
"""

b = BPF(text=bpf_text)

print('Tracing... Output every %d secs. Hit Ctrl-C to end' % interval)

def print_path(cpu, data, size):
    event = b["paths"].event(data)
    filename = event.filename.decode()
    order = filename.rfind('/')
    if order != -1:
        path = filename[:order]
        print(path)

b["paths"].open_perf_buffer(print_path)

exiting = 0
while 1:
    try:
        b.perf_buffer_poll()
    except KeyboardInterrupt:
        exiting = 1

    if clear:
        call("clear")
    else:
        pass

    if exiting:
        print("Detaching...")
        exit()
```

**Comment by chenhengqi** [comment]
You need:
```c
#include <linux/sched/signal.h>
```

**Comment by nihilitysoul** [comment]
> You need:
> 
> ```c
> #include <linux/sched/signal.h>
> ```

Thanks very much, It work.
