### ISSUE TITLE
segfault on tracing missing tracepoint

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#443]
I can trace block_rq_complete but not block_rq_insert, likely due to the current tracepoint workaround. This ticket is to change the error behavior to something like "WARNING: tracepoint cannot currently be probed" instead of the segfault.

```
root@bgregg-build-i-xxx:/mnt/src/bcc/tools# ./trace.py 't:block:block_rq_complete'
TIME     PID    COMM         FUNC             
20:10:32 0      swapper/0    block_rq_complete 
20:10:32 0      swapper/0    block_rq_complete 
20:10:32 0      swapper/0    block_rq_complete 
20:10:32 0      swapper/0    block_rq_complete 
20:10:32 0      swapper/0    block_rq_complete 
20:10:32 0      swapper/0    block_rq_complete 
20:10:32 20843  run          block_rq_complete 
20:10:32 0      swapper/0    block_rq_complete 
20:10:32 0      swapper/0    block_rq_complete 
20:10:32 1973   supervise    block_rq_complete 
20:10:32 1973   supervise    block_rq_complete 
20:10:32 1973   supervise    block_rq_complete 
20:10:32 20850  supervise    block_rq_complete 
20:10:32 20850  run          block_rq_complete 
20:10:32 20850  run          block_rq_complete 

root@bgregg-build-i-xxx:/mnt/src/bcc/tools# ./trace.py 't:block:block_rq_insert'
write(/sys/kernel/debug/tracing/kprobe_events, "p:kprobes/p_perf_trace_block_rq_insert perf_trace_block_rq_insert") failed: No such file or directory
TIME     PID    COMM         FUNC             
Segmentation fault

root@bgregg-build-i-xxx:/mnt/src/bcc/tools# grep perf_trace_block_rq_insert /proc/kallsyms 

root@bgregg-build-i-xxx:/mnt/src/bcc/tools# grep perf_trace_block_rq_complete /proc/kallsyms 
ffffffff8137d9d0 t perf_trace_block_rq_complete
```

**Comment by goldshtn** [comment]
Thanks, it definitely shouldn't crash in that case. Will fix. I've made that fix in argdist already I think. 

In any case it would be great to think about a more bulletproof way to figure out the function to trace. I'm thinking about parsing the kernel headers looking for the DEFINE_EVENT or TRACE_EVENT macros and figuring out the function name. Don't know if it's feasible or even worth it... Also, if the same trace function is used for multiple tracepoints (which happens), the probe would have to determine which one we are hitting -- somehow.

**Comment by brendangregg** [comment]
The amount of effort you've done on this tracepoint workaround is admirable, but I do wonder if your time might be better spent looking at doing a #327 implementation instead of more kernel tracepoint work. ie, what you've done right now (with a crash fix) may be good enough until there is kernel support and we revisit it then.

I hacked a workaround for USDT using ftrace ( http://www.brendangregg.com/blog/2015-07-03/hacking-linux-usdt-ftrace.html and https://gist.github.com/brendangregg/f1b3d09c14088522065b ). I think you'll find that hackery pretty similar to what you've been doing with kernel tracepoints, and, such USDT hackery may in fact be the optimal implementation. ie, I don't know if there's any kernel support required.

#327 is the only "prio:high" feature left that no one has worked on yet.

**Comment by goldshtn** [comment]
Sounds like a cool project to tackle. I'll take a closer look at USDT probes over the next couple of evenings.
