### ISSUE TITLE
Monitoring the cuda with bcc

### ISSUE THREAD

**Issue by Johnny-dai-git** [iovisor/bcc#4435]
HI, 

I am trying to monitor the GPU usage with some specific program like tensorflow or PyTorch. To be more specific, I am very interested in the API cudaMalloc && cudaFree API.  However, I did not find corresponding events listed in the /sys/kernel/debug/tracing/available_events.

Is that possible for me to use the kprobe or uprobe to monitor these api with ebpf program ?

Best Regards,

**Comment by woodpenker** [comment]
AFAIK, you may hook `cudaMalloc/cudaFree` with uprobe, they are exported by libcudart.
