### ISSUE TITLE
Using the C++ api to attach a program to an xdp socket.

### ISSUE THREAD

**Issue by suhrm** [iovisor/bcc#4445]
Hi,  I am currently working on a project where we want to load different eBPF programs depending on runtime inputs. In essence, I want to redirect some traffic to an AF_XDP socket in userspace and pass other traffic to the kernel.

I have managed to get this working using a clang compiled filter and libxdp's helper functions however I am unable to reproduce the same with libbcc.

I can see that the python API has an attach_xdp but there is no obvious equivalent in the C++ API.

As such I would appreciate it if someone could point me in the right direction.

Regards.

**Comment by chenhengqi** [comment]
You can use the `bpf_attach_xdp()` API.

**Comment by suhrm** [comment]
It works.

Thanks for the quick reply :)

Regards.
