### ISSUE TITLE
Compared with previous release versions, the source package of v0.26.0 is too large

### ISSUE THREAD

**Issue by kwb0523** [iovisor/bcc#4465]
I found that the source code package of v0.26.0 is much larger than the previous version. The main reason is that it contains the  .git file, which takes up a large part of the space. I want to know whether this is necessary, or is it included by mistake?

**Comment by yonghong-song** [comment]
It is a mistake. Will ensure to remove it for later releases. Thanks for pointing this out.

**Comment by kwb0523** [comment]
OK, Thanks!
