### ISSUE TITLE
OL 7.9 -- modprobe: FATAL: Module kheaders not found.

### ISSUE THREAD

**Issue by apachipa** [iovisor/bcc#4504]

**Comment by apachipa** [comment]
Hi, 

I get below error after installing bcc-tools from repo and run it on Oracle Linux 7.9. 
Did anyone came across it and solved it ?

Any help or suggestions to fix it would be much appreciated. 

modprobe: FATAL: Module kheaders not found.
chdir(/lib/modules/3.10.0-1160.81.1.0.1.el7.x86_64/build): No such file or directory
Traceback (most recent call last):
  File "./biolatency", line 206, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 325, in __init__
    raise Exception("Failed to compile BPF text")
Exception: Failed to compile BPF text

**Comment by chenhengqi** [comment]
You need kernel headers package.

**Comment by apachipa** [comment]
@chenhengqi - Thank you for the reply. I did install kernel headers and devel packages. I still get same error. 

Any other suggestions ?

**Comment by apachipa** [comment]
ok got that fixed now. I had to manually download and install kernel-devel package. Running kernel vs Kernel-devel were different. All is working now.
