### ISSUE TITLE
build-libs.sh error

### ISSUE THREAD

**Issue by racaarddd** [iovisor/bcc#4510]
In file included from /mysharedir/usr/local/include/clang/AST/RecursiveASTVisitor.h:16:0,
                 from /home/software/bpftrace-master/bcc/src/cc/frontends/clang/b_frontend_action.h:23,
                 from /home/software/bpftrace-master/bcc/src/cc/frontends/clang/loader.cc:57:
/mysharedir/usr/local/include/clang/AST/Attr.h: In static member function ‘static clang::ParamIdx clang::ParamIdx::deserialize(clang::ParamIdx::SerialType)’:
/mysharedir/usr/local/include/clang/AST/Attr.h:261:48: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     ParamIdx P(*reinterpret_cast<ParamIdx *>(&S));
                                                ^
/mysharedir/usr/local/include/clang/AST/Attr.h:261:49: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     ParamIdx P(*reinterpret_cast<ParamIdx *>(&S));
                                                 ^
make[2]: *** [CMakeFiles/Makefile2:592: src/cc/frontends/clang/CMakeFiles/clang_frontend.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:599: src/cc/frontends/clang/CMakeFiles/clang_frontend.dir/rule] Error 2
make: *** [Makefile:311: clang_frontend] Error 2

**Comment by chenhengqi** [comment]
Please raise the issue to bpftrace.
