### ISSUE TITLE
why gethostlatency host field displays ip or hostname?

### ISSUE THREAD

**Issue by vsxen** [iovisor/bcc#4552]
For example
```
# ./gethostlatency
TIME      PID    COMM          LATms HOST
06:10:24  28011  chronyc          90.00  127.0.0.1
06:10:24  28011  kubelet          90.00  k8s-node1

```

**Comment by chenhengqi** [comment]
That depends on what is passing to getaddrinfo/gethostbyname syscalls.

**Comment by vsxen** [comment]
你要是觉得找个问题很白痴可以不回复的，但是请不管关闭。

https://man7.org/linux/man-pages/man3/getaddrinfo.3.html
https://www.brendangregg.com/blog/2016-02-08/linux-ebpf-bcc-uprobes.html
