### ISSUE TITLE
AttributeError: /lib/x86_64-linux-gnu/libbcc.so.0: undefined symbol: bpf_module_create_b

### ISSUE THREAD

**Issue by jileilxinlix** [iovisor/bcc#4554]
1. I install BCC use source follow :**INSTALL.md.**
2. My system:
  uname -a
  **Linux liujilei-virtual-machine 5.19.0-35-generic #36~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb 17 15:17:25 UTC 2 x86_64 
  x86_64 x86_64 GNU/Linux**
  so i install the depends: **sudo apt install -y bison build-essential cmake flex git libedit-dev \
   libllvm14 llvm-14-dev libclang-14-dev python3 zlib1g-dev libelf-dev libfl-dev python3-setuptools**

3. build follow:
**git clone https://github.com/iovisor/bcc.git
mkdir bcc/build; cd bcc/build
cmake ..
make
sudo make install
cmake -DPYTHON_CMD=python3 .. # build python3 binding
pushd src/python/
make
sudo make install
popd**

4. run example:
cd bcc/example
python3 hello_word.py and error:
python3 hello_world.py 
Traceback (most recent call last):
  File "/home/liujilei/BCC/bcc/examples/hello_world.py", line 9, in <module>
    from bcc import BPF
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 27, in <module>
    from .libbcc import lib, bcc_symbol, bcc_symbol_option, bcc_stacktrace_build_id, _SYM_CB_TYPE
  File "/usr/lib/python3/dist-packages/bcc/libbcc.py", line 20, in <module>
    lib.bpf_module_create_b.restype = ct.c_void_p
  File "/usr/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /lib/x86_64-linux-gnu/libbcc.so.0: undefined symbol: bpf_module_create_b

Has anyone encountered this problem?

**Comment by chenhengqi** [comment]
`bpf_module_create_b` is removed by commit b8ff0856798da23f88266d28ede33ebd423729f5, perhaps your libbcc.so is a leftover from your previous installation.

**Comment by jileilxinlix** [comment]
@chenhengqi  yes, thank you for your replay, after i clean all the install bcc package and remake by source code ,that could work.
