### ISSUE TITLE
How to rewrite string comparison in BPF programs

### ISSUE THREAD

**Issue by jiangxiaobin96** [iovisor/bcc#4561]
```
static int equal_to_true(const char *cs, const char *ct, int size)
{
    int len = 0;
    unsigned char c1, c2;
    for (len=0;len<size;len++) {
        c1 = *cs++;
        c2 = *ct++;
        if (c1 != c2) return c1 < c2 ? -1 : 1;
        if (!c1) break;
     }
     return 0;
}

int do_something(...) {
    char fname[256];
    char *cmp = "string";
    bpf_probe_read_str(&fname, sizeof(fname), (void *)filename);
    if (!equal_to_true(fname, cmp, sizeof(fname))) {
        bpf_trace_printk("equal\n");
    }
}
```
The code has two string, one get from bpf_probe_read_str and the other can get at compile-time. When doing comparison, I meet some errors.
```
bpf: Failed to load program: Invalid argument
unknown opcode 00
processed 0 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0

HINT: The 'unknown opcode' can happen if you reference a global or static variable, or data in read-only section. For example, 'char *p = "hello"' will result in p referencing a read-only section, and 'char p[] = "hello"' will have "hello" stored on the stack.
```

some questions confused me:
1. I tried many sizeof(fname) and found some like `equal_to_true(fname, cmp, 4)`(when size=4 or 10 or 32...) can run without error, but report errors when size bigger.
2. Actually I tried `strncmp`  for test and it works when size smaller than 5.
3. [__builtin_memcmp](https://stackoverflow.com/questions/60383861/failure-to-compare-strings-with-ebpf)  has other some problems.

So why cmp operation in BPF program limit comparison size and how I can realize string comparison in my scenario.

**Comment by chenhengqi** [comment]
Please post a minimal script for reproducing the issue.

**Comment by jiangxiaobin96** [comment]
```Python
from bcc import BPF
b = BPF(src_file="test.c")
b.attach_kprobe(event="filp_close", fn_name="close")
b.trace_print()
```
```c
#include <linux/sched.h>
#include <uapi/linux/ptrace.h>
#include <linux/fs.h>
#include <linux/fdtable.h>
#include <linux/bpf.h>

static __always_inline  int equal_to_true(const char *cs, const char *ct, int size)
{
    int len = 0;
    unsigned char c1, c2;
    for (len=0;len<size;len++) {
        c1 = *cs++;
        c2 = *ct++;
        if (c1 != c2) return c1 < c2 ? -1 : 1;
        if (!c1) break;
     }
     return 0;
}

BPF_PERF_OUTPUT(events);
int close(struct pt_regs *ctx, struct file *filp, fl_owner_t id)
{
    char fname[256];
    struct file *file = NULL;
    file = filp;
    if(!file) return 0;
    char *string = "string";
    bpf_probe_read_str(&fname, sizeof(fname), (void *)file->f_path.dentry->d_name.name);
    bpf_trace_printk("%d\n", equal_to_true(fname, string, sizeof(fname)));
    return 0;
}
```

**Comment by chenhengqi** [comment]
Try:
```c
for (len = 0; len < (size & 0xff); len++) {
```

`size & 0xff` tells the BPF verifier that the loop is bound.

**Comment by jiangxiaobin96** [comment]
Thanks for your reply., It works. I also found some details about [ebpf loop](https://stackoverflow.com/questions/56107380/are-loops-allowed-in-linuxs-bpf-programs) and wonder if ebpf support unbound loop like `while(true)`.
Because ebpf program needs to run in kernel, verifier cannot allow unbound loop which probably destroy kernel. But if the developer know when to break the loop, is there any way to bypass bpf verifier.
An example:
```
static int signal = 0;
int kprobe_a(...) {
    while (signal == 0) {}
}
int kprobe_b(...) {
    signal = 1;
}
```
If we ensure function kprobe_b must be run when kprobe_a in while loop, Is it possible to be implemented?

**Comment by chenhengqi** [comment]
AFAIK, nope.

**Comment by jiangxiaobin96** [comment]
Some problems in my code, `sizeof(fname) = 256` and `size & 0xff` equal to 0. Is there any problems?

If i use `for` loop to wait some seconds, what's the max loop that ebpf can support.
I tried the following code
```
#pragma clang loop unroll(full)
for(i=0;i<0xfffffff;i++) {}
```
the program can run but it seems no waiting time.




> Try:
> 
> ```c
> for (len = 0; len < (size & 0xff); len++) {
> ```
> 
> `size & 0xff` tells the BPF verifier that the loop is bound.
