### ISSUE TITLE
Failed to attach BPF program b'kprobe__sys_clone' to kprobe b'__arm64_sys_clone'

### ISSUE THREAD

**Issue by vanxv** [iovisor/bcc#4563]
enviment:
board: rk3588 
arm64
redroid:13.0.0:run debian system

debug information:
```
root@localhost:/tmp/bcc/examples# python3 hello_world.py
create_probe_event: open(/sys/kernel/tracing/kprobe_events): No such file or directory
Traceback (most recent call last):
  File "/tmp/bcc/examples/hello_world.py", line 12, in <module>
    BPF(text='int kprobe__sys_clone(void *ctx) { bpf_trace_printk("Hello, World!\\n"); return 0; }').trace_print()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 483, in __init__
    self._trace_autoload()
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 1448, in _trace_autoload
    self.attach_kprobe(
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 840, in attach_kprobe
    raise Exception("Failed to attach BPF program %s to kprobe %s" %
Exception: Failed to attach BPF program b'kprobe__sys_clone' to kprobe b'__arm64_sys_clone'
```

**Comment by chenhengqi** [comment]
https://github.com/iovisor/bcc/blob/master/docs/kernel_config.md

Please make sure you have kprobes enabled.

**Comment by vanxv** [comment]
> https://github.com/iovisor/bcc/blob/master/docs/kernel_config.md
> 
> Please make sure you have kprobes enabled.

大佬 ebpf过andriod检测 咋那么难，可否加你下v哈？

**Comment by vanxv** [comment]
root@localhost:/usr/share/bcc/examples# grep BPF /boot/config-5.10.110-rockchip-rk3588
CONFIG_CGROUP_BPF=y
CONFIG_BPF=y
CONFIG_BPF_SYSCALL=y
CONFIG_ARCH_WANT_DEFAULT_BPF_JIT=y
# CONFIG_BPF_UNPRIV_DEFAULT_OFF is not set
# CONFIG_BPF_PRELOAD is not set
CONFIG_NETFILTER_XT_MATCH_BPF=m
CONFIG_BPFILTER=y
CONFIG_BPFILTER_UMH=m
CONFIG_NET_CLS_BPF=m
# CONFIG_NET_ACT_BPF is not set
# CONFIG_BPF_JIT is not set
CONFIG_BPF_STREAM_PARSER=y
CONFIG_LWTUNNEL_BPF=y
CONFIG_HAVE_EBPF_JIT=y
CONFIG_BPF_EVENTS=y
# CONFIG_TEST_BPF is not set

----------

kprobes config not open.

**Comment by lxy417** [comment]
![image](https://user-images.githubusercontent.com/33677809/232055748-43683439-9027-4f2c-9c8e-2b3a6b4139cf.png)
I have a similar problem with you. Have you solved it? I'm not sure if my kernel configuration is correct.

**Comment by zydmtaichi** [comment]
The issue is not solved. I encountered the same problem when run the example bitehist.py #5124
