### ISSUE TITLE
undefined symbol: bpf_module_create_b in Ubuntu22.04

### ISSUE THREAD

**Issue by pallavsingh** [iovisor/bcc#4581]
Hi All, 

I am getting following error while running hello_world.py  in Ubuntu22.04
I am following the steps mentioned in this repository for installation : https://github.com/iovisor/bcc/blob/master/INSTALL.md#ubuntu---source

root@pallav-virtual-machine:/usr/share/bcc/examples# which python
/usr/bin/python
root@pallav-virtual-machine:/usr/share/bcc/examples# python --version
Python 3.10.6
root@pallav-virtual-machine:/usr/share/bcc/examples# python hello_world.py
Traceback (most recent call last):
  File "/usr/share/bcc/examples/hello_world.py", line 9, in <module>
    from bcc import BPF
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 27, in <module>
    from .libbcc import lib, bcc_symbol, bcc_symbol_option, bcc_stacktrace_build_id, _SYM_CB_TYPE
  File "/usr/lib/python3/dist-packages/bcc/libbcc.py", line 20, in <module>
    lib.bpf_module_create_b.restype = ct.c_void_p
  File "/usr/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/x86_64-linux-gnu/libbcc.so.0: undefined symbol: bpf_module_create_b
root@pallav-virtual-machine:/usr/share/bcc/examples# uname -a
Linux pallav-virtual-machine 5.19.0-40-generic #41~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 31 16:00:14 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
root@pallav-virtual-machine:/usr/share/bcc/examples# echo $PATH
/usr/share/bcc/tools:/usr/share/bcc/examples:/usr/share/bcc/tools:/usr/share/bcc/examples:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

How cloud I fix this problem? 

Thanks
Pallav Singh

**Comment by pallavsingh** [comment]
Solution :  
 git clone --recursive https://github.com/iovisor/bcc.git
  git checkout v0.26.0
  cd bcc/
  mkdir build; cd build
  cmake ../ -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_LLVM_SHARED=1 -DCMAKE_PREFIX_PATH=/usr/lib/llvm-14
  make -j10
  make install
  cmake -DPYTHON_CMD=python3 ..
  pushd src/python/
  make
  sudo make install
  popd
  cd /usr/share/bcc/examples/
  ls
  python hello_world.py
  history


sudo apt-get install liblzma-dev
sudo apt-get install libluajit-5.1-dev


vi ~/.bashrc 
bcctools=/usr/share/bcc/tools
bccexamples=/usr/share/bcc/examples
export PATH=$bcctools:$bccexamples:$PATH

**Comment by jlecours** [comment]
I was hopeful this would work for me. Instead I get this:
```
devinvisible@PC-ZG3DpvI:/usr/share/bcc/examples$ python hello_world.py
Traceback (most recent call last):
  File "/usr/share/bcc/examples/hello_world.py", line 9, in <module>
    from bcc import BPF
ImportError: cannot import name 'BPF' from 'bcc' (/home/devinvisible/.local/lib/python3.10/site-packages/bcc/__init__.py)
```

**Comment by pallavsingh** [comment]
sudo apt-get install liblzma-dev
sudo apt-get install libluajit-5.1-dev
sudo apt install libdebuginfod-dev

sudo apt install -y zip bison build-essential cmake clang flex git libedit-dev \
  libllvm14 llvm-14-dev libclang-14-dev python3 zlib1g-dev libelf-dev libfl-dev python3-setuptools \
  liblzma-dev libdebuginfod-dev arping netperf iperf

vi ~/.bashrc
bcctools=/usr/share/bcc/tools
bccexamples=/usr/share/bcc/examples
export PATH=$bcctools:$bccexamples:$PATH

sudo apt-get install bpfcc-tools linux-headers-$(uname -r)
sudo ln -s /usr/bin/python3.10 /usr/bin/python
  
  git clone --recursive https://github.com/iovisor/bcc.git
  git checkout v0.26.0
  cd bcc/
  mkdir build; cd build
  cmake ../ -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_LLVM_SHARED=1 -DCMAKE_PREFIX_PATH=/usr/lib/llvm-14
  make -j10
  make install
  cmake -DPYTHON_CMD=python3 ..
  pushd src/python/
  make
  sudo make install
  popd
  cd /usr/share/bcc/examples/
  python hello_world.py

Check your Python version and its Linking . It may be causing issue. I tried it gain and it works for me.
