### ISSUE TITLE
runqlen / cpuunclaimed get wrong result for Linux kernel > 5.7.0

### ISSUE THREAD

**Issue by ismhong** [iovisor/bcc#4602]
runqlen / cpuunclaimed add `check_runnable_weight_field()` as workaround to check `runnable_weight` presents in `struct cfs_rq` in `kernel/sched/sched.h by trying to access `runnable_weight` field of `struct sched_entity` in `include/linux/sched.h`. Please check more details in PR https://github.com/iovisor/bcc/pull/1510 and https://github.com/iovisor/bcc/pull/2164.

Unfortunately, the `runnable_weight` field of `struct cfs_rq` is removed, but the `runnable_weight` field of `struct sched_entity` is remiand by following patchset series from Linux version 5.7.0.
- https://yhbt.net/lore/all/20200214152729.6059-4-vincent.guittot@linaro.org/
    - https://github.com/torvalds/linux/commit/0dacee1bfa70e171be3a12a30414c228453048d2
- https://yhbt.net/lore/all/20200214152729.6059-5-vincent.guittot@linaro.org/
    - https://github.com/torvalds/linux/commit/9f68395333ad7f5bfe2f83473fed363d4229f11c

Please also check the source of Linux below.
- include/linux/sched.h
    - https://elixir.bootlin.com/linux/v5.7/source/include/linux/sched.h#L475
- kernel/sched/sched.h
    - https://elixir.bootlin.com/linux/v5.7/source/kernel/sched/sched.h#L502

I can fix it with following workaround and verified on Linux 5.10.70, but it seems this is not properly solution for creating PR.
```
  123 // Declare enough of cfs_rq to find nr_running, since we can't #import the
  124 // header. This will need maintenance. It is from kernel/sched/sched.h:
  125 struct cfs_rq_partial {
  126     struct load_weight load;
+ 127 #if LINUX_VERSION_CODE < KERNEL_VERSION(5, 7, 0)
  128     RUNNABLE_WEIGHT_FIELD
+ 129 #endif
  130     unsigned int nr_running, h_nr_running;
  131 };
```
Hi @yonghong-song,
I am willing to create PR to fix this issue, could you please help to give me some advice how to fix this in properly way? Thank you. :)

**Comment by yonghong-song** [comment]
@ismhong Thanks for the reporting. I think we could fix in the following way:
  1. If BPF.kernel_struct_has_field(b'cfs_rq', b'runnable_weight') == 1, then the field exists, otherwise,
  2. do a compiler check + your above kernel version 5.7 guard
  
I think most of recent kernels should already have BTF enabled. Not sure about 5.7 kernel or not, could you double check?
Hopefully in the distant future, BTF is available for all kernels, and we can remove step 2.

Please also fix cpuunclaimed.py which has similar problem to runqlen.py.

**Comment by ismhong** [comment]
@yonghong-song 
I have created a PR to fix this issue, but I am not sure why it didn't pass smoke test below.
https://github.com/iovisor/bcc/actions/runs/4912388699/jobs/8771353011?pr=4606#step:10:1432

It seems this failure isn't caused by my changes. Could you please give me some advice to fix it? Thank you. :)

**Comment by ismhong** [comment]
Fixed by PR https://github.com/iovisor/bcc/pull/4606.
Close this ticket.
