### ISSUE TITLE
The execsnoop run error on arm64

### ISSUE THREAD

**Issue by Homio** [iovisor/bcc#4640]
Hi,
  I use BCC on nvidia orin-x, The system info shows below:

> Linux tegra-ubuntu 5.10.120-rt70-tegra #5 SMP PREEMPT RT Thu Jun 1 15:55:46 CST 2023 aarch64 aarch64 aarch64 GNU/Linux

  The commit version of 5c92af6, execsnoop run error with below log:

> cannot attach kprobe, probe entry may not exist
> Traceback (most recent call last):
>   File "/usr/share/bcc/tools/execsnoop", line 246, in <module>
>     b.attach_kprobe(event=execve_fnname, fn_name="syscall__execve")
>   File "/usr/lib/python3/dist-packages/bcc-0.27.0+5c92af6a-py3.8.egg/bcc/__init__.py", line 855, in attach_kprobe
> Exception: Failed to attach BPF program b'syscall__execve' to kprobe b'sys_execve', it's not traceable (either non-existing, inlined, or marked as "notrace")

Because the line 244 of execsnoop which is `execve_fnname = b.get_syscall_fnname("execve")` return error result. It should be `__arm64_sys_execve`

**Comment by yonghong-song** [comment]
could you try latest bcc from source? This should work. Check `__init__.py`, we have
```
    _syscall_prefixes = [
        b"sys_",
        b"__x64_sys_",
        b"__x32_compat_sys_",
        b"__ia32_compat_sys_",
        b"__arm64_sys_",
        b"__s390x_sys_",
        b"__s390_sys_",
    ] 
```
etc.

**Comment by Homio** [comment]
@yonghong-song Great! I have tried the latest version, the bug is fixed. 👍
