### ISSUE TITLE
runqlat issue with __state replaced by state in Latest Kernels

### ISSUE THREAD

**Issue by pgowda-cve** [iovisor/bcc#4645]
Hi,

root@qemux86-64:~# uname -a
Linux qemux86-64 6.1.33-yocto-standard #1 SMP PREEMPT_DYNAMIC Thu Jun 15 03:08:03 UTC 2023 x86_64 Gx

I am trying to run runqlat as:-
/usr/share/bcc/tools/runqlat 1 5

However, facing the following error as:-

libbpf: failed to find valid kernel BTF
/virtual/main.c:92:15: error: no member named 'state' in 'struct task_struct'
    if (prev->state == TASK_RUNNING) {
        ~~~~  ^
1 error generated.
Traceback (most recent call last):
  File "/usr/share/bcc/tools/runqlat", line 293, in <module>
    b = BPF(text=bpf_text)
        ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/bcc/__init__.py", line 479, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>


After investigating, it was due to the modification of state to __state in latest kernels.
The following commit addressed the issue which checks whether the struct "task_struct" has __state or state
https://github.com/chenhengqi/bcc/commit/d3cf5dcecfaeb6d8d346e2228626a7dbe506ad38
However, I am still having the STATE_FIELD returning state that is resulting in the issue.

The following modification of hard coding the "__state" in runqlat.py file fixed the issue.
---  if (prev->STATE_FIELD == TASK_RUNNING) { 
+++ if (prev->STATE_FIELD == TASK_RUNNING) {

Can you please let me know if anything is missed from my side that's resulting in the issue?

Thanks

**Comment by chenhengqi** [comment]
You should enable `CONFIG_DEBUG_INFO_BTF` in your kernel.

**Comment by pgowda-cve** [comment]
Thanks for your valuable comments.
After enabling the above option in Kernel, I am getting following error

BTF: .tmp_vmlinux.btf: pahole (false) is not available
Failed to generate BTF for vmlinux
Try to disable CONFIG_DEBUG_INFO_BTF

Can you please let me know the extra kernel configurations that should be enabled to fix the issue?

**Comment by yonghong-song** [comment]
You need to install 'pahole' in your build environment which is, e..g, in fedora, in `dwarves` package.

**Comment by pgowda-cve** [comment]
Thanks for the comments and suggestions.
