### ISSUE TITLE
bpf-cpufreq looks for the wrong cpu number

### ISSUE THREAD

**Issue by carofe82** [iovisor/bcc#4651]
This is the error:

```
# bpf-cpufreq 
failed to open '/sys/devices/system/cpu/cpu12/cpufreq/scaling_cur_freq': No such file or directory
failed to init freqs
```

```
bpf-opensnoop --name=bpf-cpufreq
PID    COMM              FD ERR PATH
49029  bpf-cpufreq        3   0 /etc/ld.so.cache
49029  bpf-cpufreq        3   0 /lib64/libelf.so.1
49029  bpf-cpufreq        3   0 /lib64/libz.so.1
49029  bpf-cpufreq        3   0 /lib64/libc.so.6
49029  bpf-cpufreq        3   0 /lib64/libzstd.so.1
49029  bpf-cpufreq        3   0 /sys/devices/system/cpu/possible
49029  bpf-cpufreq        3   0 /sys/kernel/btf/vmlinux
49029  bpf-cpufreq        9   0 /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq
49029  bpf-cpufreq        9   0 /sys/devices/system/cpu/cpu1/cpufreq/scaling_cur_freq
49029  bpf-cpufreq        9   0 /sys/devices/system/cpu/cpu2/cpufreq/scaling_cur_freq
49029  bpf-cpufreq        9   0 /sys/devices/system/cpu/cpu3/cpufreq/scaling_cur_freq
49029  bpf-cpufreq        9   0 /sys/devices/system/cpu/cpu4/cpufreq/scaling_cur_freq
49029  bpf-cpufreq        9   0 /sys/devices/system/cpu/cpu5/cpufreq/scaling_cur_freq
49029  bpf-cpufreq        9   0 /sys/devices/system/cpu/cpu6/cpufreq/scaling_cur_freq
49029  bpf-cpufreq        9   0 /sys/devices/system/cpu/cpu7/cpufreq/scaling_cur_freq
49029  bpf-cpufreq        9   0 /sys/devices/system/cpu/cpu8/cpufreq/scaling_cur_freq
49029  bpf-cpufreq        9   0 /sys/devices/system/cpu/cpu9/cpufreq/scaling_cur_freq
49029  bpf-cpufreq        9   0 /sys/devices/system/cpu/cpu10/cpufreq/scaling_cur_freq
49029  bpf-cpufreq        9   0 /sys/devices/system/cpu/cpu11/cpufreq/scaling_cur_freq
49029  bpf-cpufreq       -1   2 /sys/devices/system/cpu/cpu12/cpufreq/scaling_cur_freq
```

```
# cat /sys/devices/system/cpu/possible
0-31
```

```
inxi --cpu --system -z
System:
  Kernel: 6.3.8-200.fc38.x86_64 arch: x86_64 bits: 64 Console: pty pts/1
    Distro: Fedora release 38 (Thirty Eight)
CPU:
  Info: 6-core model: AMD Ryzen 5 5600G with Radeon Graphics bits: 64
    type: MT MCP cache: L2: 3 MiB
  Speed (MHz): avg: 1608 min/max: 1400/4464 cores: 1: 1400 2: 3900 3: 1400
    4: 1400 5: 1400 6: 1400 7: 1400 8: 1400 9: 1400 10: 1400 11: 1400 12: 1400
```

It looks to me that the tool should be using /sys/devices/system/cpu/present

https://github.com/torvalds/linux/blob/master/Documentation/admin-guide/cputopology.rst
> present: CPUs that have been identified as being present in the system [cpu_present_mask]

It seems that the problem may be here:  https://github.com/libbpf/libbpf/blob/7984737fbf3b2a14a86321387bb62abb16cfc4ed/src/libbpf.c#L12130
```c
int libbpf_num_possible_cpus(void)
{
	static const char *fcpu = "/sys/devices/system/cpu/possible";
	static int cpus;
...
```
.. which is used by the cpufreq tool:
https://github.com/iovisor/bcc/blob/e4dc8b2f23e12be53abeb6a18ff94e18a998c29e/libbpf-tools/cpufreq.c#L212
```c
nr_cpus = libbpf_num_possible_cpus();
```
... and the iterates over that to get the values from `/sys/devices/system/cpu/...`

This library may need a different function that gives the number of present CPUs.

I also submitted this issue over here: https://bugzilla.redhat.com/show_bug.cgi?id=2217179

**Comment by carofe82** [comment]
I was trying to contribute with the PR but I'm having a hard time compiling and generating the libbpf tools. 
I already did the `cmake .` and the `make` and I can get it to compile:
```
[100%] Linking CXX executable test_libbcc
[100%] Built target test_libbcc
```

I was wondering if there is "right way" to develop on those tools on `libbpf-tools`. Any help would be welcome :).

**Comment by carofe82** [comment]
> I was trying to contribute with the PR but I'm having a hard time compiling and generating the libbpf tools. I already did the `cmake .` and the `make` and I can get it to compile:
> 
> ```
> [100%] Linking CXX executable test_libbcc
> [100%] Built target test_libbcc
> ```
> 
> I was wondering if there is "right way" to develop on those tools on `libbpf-tools`. Any help would be welcome :).

Never mind, I was able to compile it and try solutions.

**Comment by carofe82** [comment]
I started a PR to add the number of present CPUs to the API: https://github.com/libbpf/libbpf/pull/701

**Comment by yonghong-song** [comment]
In the tool, we already have,
```
        for (i = 0; i < nr_cpus; i++) {
                fd = syscall(__NR_perf_event_open, &attr, -1, i, -1, 0);
                if (fd < 0) {
                        /* Ignore CPU that is offline */
                        if (errno == ENODEV)
                                continue;
                        fprintf(stderr, "failed to init perf sampling: %s\n",
                                strerror(errno));
                        return -1;
                } 
...
```
See the above, if ENODEV err code, that cpu will be skipped. Isn't this enough? Maybe error code changed with newer kernels? What error code did you see in your system?

**Comment by yonghong-song** [comment]
It is possible that we remember which cpus are failing during perf event open and later on filtering out those cpu's in scaling_cur_freq loop? Does this work?

**Comment by carofe82** [comment]
@yonghong-song ,
I think that would work, ... returning somehow the CPUs that do work after the call to `open_and_attach_perf_event` and then `init_freqs_hmz` with that information should do it. Perhaps a look into the `links` array.
I can work on a PR with that approach, and do some testing on my machines of those scenarios.

**Comment by carofe82** [comment]
@yonghong-song ,
The PR: https://github.com/iovisor/bcc/pull/4653
Thank you.

**Comment by carofe82** [comment]
The PR https://github.com/iovisor/bcc/pull/4653 fixes this issue. Closing.
