### ISSUE TITLE
Install on WSL2

### ISSUE THREAD

**Issue by massoudasadi** [iovisor/bcc#4670]
i have problem with installing on WSL.

when i try to run bellow command 

`sudo make modules_install`

got error 

`arch/x86/Makefile:142: CONFIG_X86_X32 enabled but no binutils support
  DEPMOD  /lib/modules/5.15.90.1-microsoft-standard-WSL2+`

**Comment by massoudasadi** [comment]
@realsnick nope. use [](https://github.com/aya-rs/aya) instead. easily installed on WSL2

**Comment by srayuws** [comment]
I had the same issue. And I solved it by removing the `CONFIG_X86_X32` in my `.config` file.

**Comment by massoudasadi** [comment]
@srayuws everything works normally ?

**Comment by srayuws** [comment]
When running the helloworld program, I got some warnings. Some other issue (sorry, I forget which one) said compile the bcc from source and install it can remove these warnings.
I have not done that. 

But if you ignore the warnings, at least the hello world works as expected.

**Comment by massoudasadi** [comment]
i wrote comprehensive guide on my [blog](https://massoudasadiblog.blogspot.com/2024/07/ebpf-on-wsl2-kernel-version-6x-ubuntu.html)

**Comment by massoudasadi** [comment]
@srayuws check my [blog](https://massoudasadiblog.blogspot.com/2024/07/ebpf-on-wsl2-kernel-version-6x-ubuntu.html)

**Comment by massoudasadi** [comment]
i wrote comprehensive guide on my [blog](https://massoudasadiblog.blogspot.com/2024/07/ebpf-on-wsl2-kernel-version-6x-ubuntu.html)

**Comment by massoudasadi** [comment]
i wrote comprehensive guide on my [blog](https://massoudasadiblog.blogspot.com/2024/07/ebpf-on-wsl2-kernel-version-6x-ubuntu.html)
