### ISSUE TITLE
usage of flags in bpf_get_stackid

### ISSUE THREAD

**Issue by Anjali05** [iovisor/bcc#4675]
I am working on a bcc script and I need to trace the kernel stacks. I am a bit confused about what to set the flags value while calling bpf_get_stackid. I have seen example programs using 0, 3 for kernel stack and also BPF_F_REUSE_STACKID. Can someone  shed some light on what the difference is between these? Thanks in advance!

**Comment by chenhengqi** [comment]
Please refer to the manpage https://man7.org/linux/man-pages/man7/bpf-helpers.7.html
* 0 for getting kernel stack
* 3 is the number of stack frames to skip
