### ISSUE TITLE
Do some of the tools in bpftrace require the development of a BCC version?

### ISSUE THREAD

**Issue by kuroro99** [iovisor/bcc#4719]
I have been reading the book  https://github.com/brendangregg/bpf-perf-tools-book recently, and it mentions that some tools only have a bpftrace version, such as mlock and kmem. I would like to know if it is necessary to develop the same functionality in BCC. If so, I would be willing to provide a list of tools that need to be adapted and submit a pull request.

**Comment by brendangregg** [comment]
Thanks for the offer, however, if I thought they belonged in bcc I would
have already put them there. Having too many tools makes it harder for
newcomers to wade through them and harder to maintain.

If, however, you have a strong production case story for one of the missing
tools (e.g., your company does a blog post on why it saved the day), then
I'd reconsider adding it to bcc.
