### ISSUE TITLE
Can not call BPF kernel functions from BPF programs (Implicit Function Declaration Warning)

### ISSUE THREAD

**Issue by MohammadrezaRezvani** [iovisor/bcc#4740]
I'm currently working with BPF Kernel Functions (kfuncs) and have been referencing the documentation provided in the [BPF Kernel Functions (kfuncs)](https://static.lwn.net/kerneldoc/bpf/kfuncs.html#bpf-kernel-functions-kfuncs). My primary objective is to create a new kfunc to call a kernel function from eBPF space.

However, I've encountered a problem when calling any of the kfuncs defined in [helpers.c](https://elixir.bootlin.com/linux/v6.2/source/kernel/bpf/helpers.c). Specifically, I receive the following warning:
```
implicit declaration of function 'bpf_task_acquire' is invalid in C99 [-Wimplicit-function-declaration]
```
Due to this warning, the BPF program fails to load. 'bpf_task_acquire' is clearly defined in [helpers.c:1842](https://elixir.bootlin.com/linux/v6.2/source/kernel/bpf/helpers.c#L1842). Below is the code snippet I'm using for testing:

```
#!/usr/bin/python
from bcc import BPF

bpf_program = """
#include <linux/ptrace.h>
#include <linux/sched.h>
#include <linux/bpf.h>

int trace_event(struct pt_regs *ctx) {
    bpf_trace_printk("In trace_event(struct pt_regs *ctx)\\n");
    
    struct task_struct *task = (struct task_struct *)bpf_task_acquire(NULL);

    return 0;
}
"""
b = BPF(text=bpf_program)
b.attach_tracepoint(tp="sched:sched_process_fork", fn_name="trace_event")
b.trace_print()
```

'bpf_task_acquire' belongs to the 'generic_kfunc_set' group ([helpers.c:2069](https://elixir.bootlin.com/linux/v6.2/source/kernel/bpf/helpers.c#2069)), which should be callable from TRACING programs ([helpers.c:2111](https://elixir.bootlin.com/linux/v6.2/source/kernel/bpf/helpers.c#2111)). I've encountered this issue not only with 'bpf_task_acquire' but also with other kfuncs, including ones I've written myself. I've also tested 'bpf_obj_new_impl', 'bpf_cgroup_acquire', and 'bpf_rcu_read_lock' (though I don't expect the last one to work. I was desperate!).

This is the code I added to helpers.c for my own kfunc:
```
#include <asm/msr.h>

...

int bpf_rdmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 *q)
{
	return rdmsrl_on_cpu(cpu, msr_no, q);
}

int bpf_wrmsrl_on_cpu(unsigned int cpu, u32 msr_no, u64 q)
{
	return wrmsrl_on_cpu(cpu, msr_no, q);	
}

...

BTF_SET8_START(msr_func_set)
BTF_ID_FLAGS(func, bpf_rdmsrl_on_cpu)
BTF_ID_FLAGS(func, bpf_wrmsrl_on_cpu)
BTF_SET8_END(msr_func_set)

static const struct btf_kfunc_id_set msr_kfunc_set = {
	.owner = THIS_MODULE,
	.set   = &msr_func_set,
};

...

ret = ret ?: register_btf_kfunc_id_set(BPF_PROG_TYPE_TRACING, &msr_kfunc_set);
ret = ret ?: register_btf_kfunc_id_set(BPF_PROG_TYPE_TRACEPOINT, &msr_kfunc_set);
ret = ret ?: register_btf_kfunc_id_set(BPF_PROG_TYPE_KPROBE, &msr_kfunc_set);

...

```

and I am trying to test my kfuncs like this:

```
#!/usr/bin/python
from bcc import BPF

bpf_program = """
#include <linux/ptrace.h>
#include <linux/sched.h>
#include <linux/bpf.h>

TRACEPOINT_PROBE(sched, sched_process_fork)
{
        bpf_trace_printk("In KFUNC_PROBE(vfs_open)\\n");
	    
        u64 epb;
        int ret;
        
        ret = bpf_rdmsrl_on_cpu(0, 432, &epb);
        if (ret < 0)
            return ret;
        
        bpf_trace_printk("Testing energy_perf_bias_show = %u", epb);
  
        return 0; 
}

"""
b = BPF(text=bpf_program)trace_print()
```

I can see all kfuncs (including my own) listed at `/sys/kernel/debug/tracing/available_filter_functions`. Also, the `BPF.support_kfunc()` flag is ture.

I can't find any header to include for the compiler to find the kfunc. From my understanding, helpers do not need any include and all other functions defined in helpers.c can be called with no problem except the kfuncs.

I'm running my tests on a virtual machine with Ubuntu 22.04 and kernel version 6.2.0. I built and installed BPF from the BCC GitHub repo using the tag 'v0.28.0'. Every other program I ran seems to work on this setup.

I'm wondering if I've misunderstood something about kfuncs or if there might be an issue with my approach. 

Should I consider another approach, such as writing a new helper function, or is there a solution that I might be missing?

I appreciate any insights or assistance. Thank you.

**Comment by rjsu26** [comment]
If you declare the functions in your bpf program as :
```
struct cgroup *bpf_cgroup_acquire(struct cgroup *p) __ksym;

struct cgroup *bpf_cgroup_kptr_get(struct cgroup **pp) __ksym;

void bpf_cgroup_release(struct cgroup *p) __ksym;

struct cgroup *bpf_cgroup_ancestor(struct cgroup *cgrp, int level) __ksym;
```

Then it should be fine

**Comment by MohammadrezaRezvani** [comment]
Thank you for taking the time to respond to my problem.


After adding the provided code, I encountered an error indicating missing function body:
```
error: expected function body after function declaration
struct cgroup *bpf_cgroup_acquire(struct cgroup *p) __ksym;
                                                    ^
error: expected function body after function declaration
struct cgroup *bpf_cgroup_kptr_get(struct cgroup **pp) __ksym;
                                                       ^
error: expected function body after function declaration
void bpf_cgroup_release(struct cgroup *p) __ksym;
                                         ^
error: expected function body after function declaration
struct cgroup *bpf_cgroup_ancestor(struct cgroup *cgrp, int level) __ksym;
                                                                   ^
warning: implicit declaration of function 'bpf_task_acquire' is invalid in C99 [-Wimplicit-function-declaration]
```

I greatly appreciate any more help with this issue.

**Comment by rjsu26** [comment]
Okay, so the `__ksym` macro is not recognized. 
You can include `#include <bpf/bpf_helpers.h>` where this macro is basically defined as `#define __ksym __attribute__((section(".ksyms")))`

**Comment by matthew-olson-intel** [comment]
@MohammadrezaRezvani Is your problem resolved now?

**Comment by MohammadrezaRezvani** [comment]
Yes. Thanks to @rjsu26. I really appreciate the help.

**Comment by brendangregg** [comment]
Thanks @rjsu26 and @matthew-olson-intel .

**Comment by FauraSol** [comment]
When including ``#include <bpf/bpf_helpers.h>``, I receive an error indicating that the file cannot be found. After including it using the absolute path, I get the error: ``fatal error: 'bpf_helper_defs.h' file not found`` (the bpf/bpf_helpers.h includes this file via a relative path). After copying ``bpf_helper_defs.h`` to the corresponding directory, I encounter a conflict with the definition in ``/virtual/include/bcc/helpers.h``.

Could you please provide guidance on how to resolve this issue?

**Comment by MohammadrezaRezvani** [comment]
I'm not 100% sure what’s causing the issue, but it might be a conflict between libbpf and bcc, which I don’t have much experience with. That said, here’s where I’d start troubleshooting:
1) Make sure libbpf is installed properly. The `bpf_helpers.h` file comes with libbpf, so if it’s not set up right, that could be the problem.
2) If you’re still getting errors, double-check that the include paths for clang are set up properly so it can find bpf_helpers.h and bpf_helper_defs.h.

If the problem persists, it’d be helpful to know more about the code you’re trying to compile and how you’re building it. That could give me or someone else more to work with to help you out.

Hope this helps.

**Comment by shubhe25p** [comment]
I am facing the same issue, if possible can you please help me out @MohammadrezaRezvani ? I am trying to access to RCU protected fields in task_struct via BCC, I forward declared bpf_rcu_read_unlock and bpf_rcu_read_lock as mentioned above but when including #include <bpf/bpf_helpers.h>, I receive an error indicating that the file cannot be found.
