### ISSUE TITLE
Facing error in tunnel_monitor main function

### ISSUE THREAD

**Issue by TahirAhmed916** [iovisor/bcc#486]
Hi i am trying to run tunnel monitor but facing this error. Also facing same kind of issue in neighbousharing program.
test@ubuntu:~/examples/networking/tunnel_monitor$ sudo python main.py
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    from simulation import Simulation
  File "/home/test/examples/networking/tunnel_monitor/simulation.py", line 1
    ../simulation.py
    ^
SyntaxError: invalid syntax

**Comment by drzaeus77** [comment]
Hi @TahirAhmed916 
Sorry for the slow reply, this looks like maybe somehow the symlink didn't get installed properly on your system when cloning the repository.

It should look something like the following:
```bash
$ ls -l simulation.py 
lrwxrwxrwx 1 bblanco bblanco 16 Nov 10 23:22 simulation.py -> ../simulation.py
```

**Comment by goldshtn** [comment]
@TahirAhmed916 I'm closing for now, please reopen if you still run into this error.
