### ISSUE TITLE
why networking/tunnel_monitor example is failing?

### ISSUE THREAD

**Issue by asifhasnain** [iovisor/bcc#491]
Hi, I am using Ubuntu 14.04 with kernel version 4.4.0-040400-generic as a VM in a virtualbox. While executing tunnel_monitor example, ./setup worked correctly but 'python main.py' failed..

dev@dev-u14:~/iovisor/bcc/examples/networking/tunnel_monitor$ sudo python main.py 
Launching host 1 of 9
Launching host 2 of 9
Launching host 3 of 9
Launching host 4 of 9
Launching host 5 of 9
Launching host 6 of 9
Launching host 7 of 9
Launching host 8 of 9
Launching host 9 of 9
Starting tunnel 1 of 9
Process Process-10:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(_self._args, *_self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyroute2/netns/process/proxy.py", line 88, in NSPopenServer
    child = subprocess.Popen(_argv, *_kwarg)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Thanks

**Comment by asifhasnain** [comment]
seems to be pyroute2 bug..

**Comment by svinota** [comment]
I'm to investigate it asap.

**Comment by svinota** [comment]
@asifhasnain no, it isn't. The script tries to start `netserver`:

```
[pid 15591] clone(strace: Process 15592 attached
child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f02861529d0) = 15592
[pid 15592] execve("/sbin/netserver", ["netserver", "-D"], [/* 21 vars */]) = -1 ENOENT (No such file or directory)
[pid 15592] execve("/usr/sbin/netserver", ["netserver", "-D"], [/* 21 vars */]) = -1 ENOENT (No such file or directory)
[pid 15592] execve("/usr/bin/netserver", ["netserver", "-D"], [/* 21 vars */]) = -1 ENOENT (No such file or directory)
[pid 15592] execve("/bin/netserver", ["netserver", "-D"], [/* 21 vars */]) = -1 ENOENT (No such file or directory)
[pid 15592] execve("/usr/local/sbin/netserver", ["netserver", "-D"], [/* 21 vars */]) = -1 ENOENT (No such file or directory)
[pid 15592] execve("/usr/local/bin/netserver", ["netserver", "-D"], [/* 21 vars */]) = -1 ENOENT (No such file or directory)
[pid 15592] exit_group(255)             = ?
[pid 15592] +++ exited with 255 +++
[pid 15591] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=15592, si_uid=0, si_status=255, si_utime=0, si_stime=0} ---
[pid 15591] wait4(15592, [{WIFEXITED(s) && WEXITSTATUS(s) == 255}], 0, NULL) = 15592
Process Process-10:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib64/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/peet/Projects/pyroute2/pyroute2/netns/process/proxy.py", line 88, in NSPopenServer
    child = subprocess.Popen(*argv, **kwarg)
  File "/usr/lib64/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'netserver'
[pid 15591] wait4(15592, 0x7ffe8d333014, WNOHANG, NULL) = -1 ECHILD (No child processes)
[pid 15591] exit_group(1)               = ?
[pid 15591] +++ exited with 1 +++
```

from `git blame main.py`:
```
5891757a examples/tunnel_stats.py        (Brenden Blanco 2015-06-23 06:53:47 -0700 42)     cmd = ["netserver", "-D"]
```

@drzaeus77 , what the `netserver` is?

**Comment by asifhasnain** [comment]
@svinota netserver is the server program of netperf. Installing netperf should solve the issue (like Fedora, must be mentioned in Ubuntu dependencies).

Thanks

**Comment by drzaeus77** [comment]
@asifhasnain can you run strace on your system where it fails and share the output?

**Comment by asifhasnain** [comment]
@drzaeus77 strace output is attached.
[tmp.txt](https://github.com/iovisor/bcc/files/230257/tmp.txt)

**Comment by drzaeus77** [comment]
In that run you neglected root:
```
10291 write(2, "NetlinkError", 12)      = 12
10291 write(2, ": ", 2)                 = 2
10291 write(2, "(1, 'Operation not permitted')", 30) = 30
```

Can you run again with sudo strace, same as your original bug report?

**Comment by asifhasnain** [comment]
My bad. Please check this..
[tmp2.txt](https://github.com/iovisor/bcc/files/230391/tmp2.txt)

**Comment by svinota** [comment]
in the log:
> interface br100 exists

It's 'cause of the previous run.
Pls remove all the `host[0-9].*` namespaces (veth will be removed automatically):
```
ip netns list | awk '/^host/ {system("sudo ip netns del "$1)}'
```
And remove br100:
```
sudo ip link del br100
```

Most probably it will work then — if you have `netserver`. But if not, clean up again and collect pls:
```
sudo strace -e trace=process,network -f python main.py
```
Thanks.

**Comment by asifhasnain** [comment]
I did the clean run. Nevertheless, installing netperf (after looking at your trace message) solved the problem.

However, wasn't able to see anything on the chord diagram; in the presence of running main.sh and the traffic.sh script. Any comments or thoughts on that will be helpful..
![output](https://cloud.githubusercontent.com/assets/3188474/14719052/f2472c4c-07c7-11e6-813e-f33a2b62509c.png)

**Comment by drzaeus77** [comment]
Can you start with the output of tc to show that traffic is flowing over the monitored interface.

example:
```bash
$ sudo ip net exec host0 tc -s qdisc show dev eth0
qdisc sfq 1: root refcnt 2 limit 127p quantum 1514b depth 127 divisor 1024 
 Sent 335094 bytes 694 pkt (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0 
qdisc ingress ffff: parent ffff:fff1 ---------------- 
 Sent 347993 bytes 852 pkt (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0 
```

**Comment by asifhasnain** [comment]
Output:

`$ sudo ip netns exec host0 tc -s qdisc show dev eth0
qdisc sfq 1: root refcnt 2 limit 127p quantum 1514b depth 127 divisor 1024 
 Sent 1365760 bytes 2747 pkt (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0 
qdisc ingress ffff: parent ffff:fff1 ---------------- 
 Sent 1362390 bytes 3016 pkt (dropped 0, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0 
`

**Comment by MQasimSarfraz** [comment]
I was facing a similar issue and it turned out that my machine was big endian and udp->port in monitor.c has a value of 46354 rather then 4789 (set in main.py). 

Following check in udp switch/case statement of monitor.c solved issue for me:
case 46354: goto vxlan;

**Comment by 4ast** [comment]
@MQasimSarfraz how about fixing it with something like 'case ntohs(4789): goto vxlan' ?
similar fix is needed for the rest of the switch cases in monitor.c, right?

**Comment by MQasimSarfraz** [comment]
@4ast it worked with the suggested solution. I have pushed the change at https://github.com/iovisor/bcc/pull/535.
