### ISSUE TITLE
Failed to build with LLVM 18

### ISSUE THREAD

**Issue by 12101111** [iovisor/bcc#4931]
In https://github.com/iovisor/bcc/pull/1289 , `-nopie` is used when compiler is clang
In https://github.com/llvm/llvm-project/commit/cac82e26c642d55672b1de6f3d026826c89994ec , clang 18+ don't accept `-nopie` except on OpenBSD

This lead to a build error `error: unsupported option '-nopie' for target ` when compile bcc using clang-18

**Comment by yonghong-song** [comment]
Could you send a patch for this? Currently bcc supports llvm >= 12, so it is okay to remove -nopie from bcc.
