### ISSUE TITLE
Strange compiler errors, maybe a missing bounds check?

### ISSUE THREAD

**Issue by aaronpuchert** [iovisor/bcc#497]
I tried the `argdist` script with a large number of arguments and ran into some weird errors. Up to 4 arguments, everything is fine:
```
# ./argdist -H 'p:c:dummy(int a, int b, int c, int d):int:a'
could not determine address of symbol dummy
```

Of course this symbol doesn't exist, but that's not the point. For 5 and 6 arguments there is an error message because I have too many arguments for one function:
```
# ./argdist -H 'p:c:dummy(int a, int b, int c, int d, int e):int:a'
error: in function dummy_probe0 i32 (%struct.pt_regs*, i32, i32, i32, i32, i32)
defined with too many args

# ./argdist -H 'p:c:dummy(int a, int b, int c, int d, int e, int f):int:a'
error: in function dummy_probe0 i32 (%struct.pt_regs*, i32, i32, i32, i32, i32, i32)
defined with too many args
```
This is a helpful error message. Apparently the ABI doesn't allow what I want. But what if I have 7 or 8 arguments?
```
# ./argdist -H 'p:c:dummy(int a, int b, int c, int d, int e, int f, int g):int:a'
/virtual/main.c:10:83: error: no member named '𜹝g' in 'struct pt_regs'
{a = ctx->di;b = ctx->si;c = ctx->dx;d = ctx->cx;e = ctx->r8;f = ctx->r9;g = ctx-><U+1CE5D>g<U+007F>;
                                                                             ~~~  ^
1 error generated.
Failed to compile BPF module 
# ./argdist -H 'p:c:dummy(int a, int b, int c, int d, int e, int f, int g, int h):int:a'
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted (core dumped)
```

I did some brief investigation into the last error. The exception is thrown by the `std::string(const char *)` constructor called in `bool BTypeVisitor::VisitFunctionDecl(FunctionDecl *D)`, `src/cc/frontends/clang/b_frontend_action.cc`, line 259. The exception is thrown because the passed pointer is a null pointer. Since `calling_conv_regs` contains exactly 6 strings, this may happen if `d >= 6`, or equivalently if `fn_args_.size() >= 8`. In our case, we have that many arguments.

Should there be a bounds check to catch that error earlier? I didn't notice any, the code just seems to iterate through how many arguments there are.

Two notes:
* This is not about the `arg_dist` script, although someone could add checks there to prevent the error earlier. It's about the exception thrown for more arguments.
* I'm using the latest stable versions of bcc (0.1.8) and LLVM/Clang (3.8.0). If the issue is already solved in the current development branches, I wouldn't have noticed.

**Comment by drzaeus77** [comment]
This looks valid, I will look into it. Thanks!
