### ISSUE TITLE
http-parse-complete.py script in networking/http_filter example is failing..

### ISSUE THREAD

**Issue by asifhasnain** [iovisor/bcc#501]
I tried http-parse-complete.py but it fails to load BPF program..
Stdout: 
[stdout_http_filter.txt](https://github.com/iovisor/bcc/files/232879/stdout_http_filter.txt)
strace: 
[httpcf_output.txt](https://github.com/iovisor/bcc/files/232880/httpcf_output.txt)

@mbertrone can you take a look?

**Comment by 4ast** [comment]
109: (85) call 1
110: (7b) *(u64 *)(r10 -32) = r0
...
116: (bf) r3 = r10
117: (07) r3 += -32
...
120: (85) call 2
invalid indirect read from stack off -32+0 size 4

the kernel pointer returned from bpf_map_lookup() is used as value for bpf_map_update()
such leaking of kernel addresses are disallowed for non-root.

**Comment by mbertrone** [comment]
Sorry for the delay @asifhasnain 

please retry http-parse-complete.py now, the problem should be solved

**Comment by fooozhe** [comment]
Same issue before. And after I updated the codes, it worked well. Nice work!
