### ISSUE TITLE
could not open bpf map error occurred when value of BPF_HASH exceeds 4 MB

### ISSUE THREAD

**Issue by drusong** [iovisor/bcc#5084]
## Problem
+ When using BPF_HASH with large value element that exceeds 4 MB, the following error was encountered:
 > could not open bpf map: large_read_buffer_ht, error: Argument list too long
Traceback (most recent call last):
  File "./large_value.py", line 47, in <module>
    b = BPF(text=program)
        ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 479, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>

+ `BPF` program as follows:  
```python
  #! /usr/bin/python3
from __future__ import print_function
from bcc import BPF
from time import sleep
import threading

program  = r"""
#include <linux/bpf.h>
#include <linux/ptrace.h>
#define LARGE_BUFFER_LEN (4 << 20) // size 4 MB
typedef struct large_buffer_type {
    u32 actual_len;
    char buffer[LARGE_BUFFER_LEN];
} large_buffer_t;

BPF_HASH(large_read_buffer_ht, int, large_buffer_t, 100);

int handle_large_value_func_start(struct pt_regs *ctx) {
    return 0;
}
"""
```

+ through the bpf program above, a BPF_HASH called large_read_buffer_ht with value struct **around 4MB and 100 entries,  the bpf program compilation failed, throwing error in Part 1; but after changing the buffer size to  around 3MB(by setting LARGE_BUFFER_LEN to  3 << 20), the program compilation succeeded, and managed to run successfully**

## Question
+ Is there any single value element size limit on BPF_HASH under Kernel 6.1.76?  and if it exists, what's the limit and why?
+ Are there any other memory limits on BPF_HASH like total memory etc?

Thanks.

**Comment by yonghong-song** [comment]
It is possible that due to the following check in kernel/bpf/hashtab.c
```
if ((u64)attr->key_size + attr->value_size >= KMALLOC_MAX_SIZE -
	   sizeof(struct htab_elem))
		/* if key_size + value_size is bigger, the user space won't be
		 * able to access the elements via bpf syscall. This check
		 * also makes sure that the elem_size doesn't overflow and it's
		 * kmalloc-able later in htab_map_update_elem()
		 */
		return -E2BIG;
```

**Comment by drusong** [comment]
> It is possible that due to the following check in kernel/bpf/hashtab.c
> 
> ```
> if ((u64)attr->key_size + attr->value_size >= KMALLOC_MAX_SIZE -
> 	   sizeof(struct htab_elem))
> 		/* if key_size + value_size is bigger, the user space won't be
> 		 * able to access the elements via bpf syscall. This check
> 		 * also makes sure that the elem_size doesn't overflow and it's
> 		 * kmalloc-able later in htab_map_update_elem()
> 		 */
> 		return -E2BIG;
> ```

Thanks, it's clear now due to KMALLOC_MAX_SIZE(default 4 MB setting), total size of key and value of a BPF_HASH leaf can not exceed 4 MB.
