### ISSUE TITLE
USDT error: type object 'BPF' has no attribute 'find_library'

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#509]
Testing USDT in case we can close #327 now, but hit this:

```
# ./trace.py -p 3560 'u:node:http__server__request'
type object 'BPF' has no attribute 'find_library'
```

Maybe this function got dropped in #495 ? ... and maybe it's trace.py that needs updating? Just guessing.

**Comment by vmg** [comment]
Ouch! Sorry for the oversight. Fixed in #511.
