### ISSUE TITLE
process id printed in tcpconnect is different than the one in ps command output

### ISSUE THREAD

**Issue by babuveld** [iovisor/bcc#5145]
Hi,

The process id printed from the ps command output is different than the one printed in tcpconnect. Because of this if I pass the process ID to tcpconnect -p <PID> it doesn't track the tcp connect calls correctly.

In below example tcpconnect shows PID during connect as 4599 and ps command shows PID as 32387.

Is there some conversion to do for the PID from ps command before using it with bcc tools? This is on linux machine.

```
 bash-5.1# ./tcpconnect
Tracing connect ... Hit Ctrl-C to end
PID    COMM         IP    SADDR            DADDR            DPORT
4599   tcpClient    4  <source ip>      <dst ip>         60321  

bash-5.1# ps -ef | grep tcpClient
root     32387 24610  0 22:53 ?        00:00:01  tcpClient
bash-5.1#
```

**Comment by yonghong-song** [comment]
Maybe you runs ./tcpconnect in the container (namespace)? In this case, the pid in ./tcpconnect will the pid from root namespace and the pid in 'ps' will be in that container pid.
