### ISSUE TITLE
Support resolving addresses via /tmp/perf-pid.map

### ISSUE THREAD

**Issue by markdrayton** [iovisor/bcc#548]
It's common for JITs (Java, HHVM, etc) to write a `/tmp/perf-<pid>.map` to map addresses to JITed code. BCC should support symbolizing using this data.

**Comment by brendangregg** [comment]
Also consider container environments, where we are running bcc/BPF from the host, and the container /tmp/perf*.map files are in other directories for each container, and the PID may not match (what the container guest thinks is the PID, is not the same as what the host thinks is the PID).

**Comment by markdrayton** [comment]
> Also consider container environments, where we are running bcc/BPF from the host, and the container /tmp/perf*.map files are in other directories for each container ..

Yes, I've been encountering this complication a lot recently :-/ I have a working diff that reads symbols from `/tmp/perf-pid.map` but I need to put some more effort into making it work with containers/different namespaces. I'll try to find time to wrap it up.

**Comment by abirchall** [comment]
>  I have a working diff that reads symbols from /tmp/perf-pid.map but I need to put some more effort into making it work with containers/different namespaces. I'll try to find time to wrap it up.

Is it worth getting some basic PID support out (for non-container environments) first and iterating?
I ask this question partly as a learning opportunity because I'm not sure whether iteration like this is encouraged / discouraged in the open source community.

I'm also curious what we'd like to support and at what level. LXC? Chroot? Namespace? Cgroup?

**Comment by markdrayton** [comment]
> I'm also curious what we'd like to support and at what level. LXC? Chroot? Namespace? cgroup?

I think we just need to support finding the `/tmp/perf-pid.map` when the target process isn't in the same PID namepace or filesystem root. We can find the PID inside the target namespace by reading `NSpid` in `/proc/pid/status` on the outside, and we get get the path to the process's root dir from `readlink /proc/pid/root`. I'm not aware of any special handling needed for LXC or cgroups (but please shout if there is something I missed!)

**Comment by brendangregg** [comment]
Should we close this issue now?

**Comment by markdrayton** [comment]
Whoops, yes.
