### ISSUE TITLE
Ubuntu binary install seems do not work?

### ISSUE THREAD

**Issue by huinghuang** [iovisor/bcc#549]
Seeing the "No module named bcc"  error with the ubuntu binary install:

$sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys D4284CDD
$echo "deb http://52.8.15.63/apt trusty main" | sudo tee /etc/apt/sources.list.d/iovisor.list
$sudo apt-get update
$sudo apt-get install binutils bcc bcc-tools libbcc-examples python-bcc

Test: $ sudo python /usr/share/bcc/examples/hello_world.py
Traceback (most recent call last):
  File "/usr/share/bcc/examples/hello_world.py", line 9, in <module>
    from bcc import BPF
ImportError: No module named bcc

BTW, I do not find o __init__.pyc under /usr/share/bc - is this the reason?
root@vm1:/usr/share/bcc# ls -l
total 12
drwxr-xr-x 5 root root 4096 2016-05-23 16:27 examples
drwxr-xr-x 3 root root 4096 2016-05-23 16:06 man
drwxr-xr-x 3 root root 4096 2016-05-23 16:23 tools

Thanks!

**Comment by zaafar** [comment]
You will find __init__.py and rest of python files in following directory
/usr/lib/python2.7/dist-packages/bcc

I have just tested on ubuntu-14 and it's working fine.
Can you send output of following commands.
"lsb_release -c" and "uname -r"

**Comment by huinghuang** [comment]
"You will find init.py and rest of python files in following directory
/usr/lib/python2.7/dist-packages/bcc" 

This is the reason for the bcc error :) my default python version is 2.6, while all the bcc files are under /usr/lib/python2.7/. Thanks!

**Comment by nanofaroque** [comment]
If someone still having an issue:
Here is my configurations: Amazon EC2 instance with Ubuntu and I was having issue 
```
'File "/usr/share/bcc/examples/hello_world.py", line 9, in
from bcc import BPF
ImportError: No module named bcc'
```
Run `find /usr/lib -name bcc`
and see where is your bcc, in my case, it was showing some like 
`/usr/lib/python3/dist-packages/bcc`

So it is clear that my bcc packages are inside python3. To run the `hello_world.py`

I had to run like this: 
sudo python3 hello_world.py
