### ISSUE TITLE
offcputime doesn't capture some offcpus

### ISSUE THREAD

**Issue by evverx** [iovisor/bcc#558]
![offcpu-limitations](https://cloud.githubusercontent.com/assets/10195800/15631722/34b93f22-2580-11e6-9f8a-f2e6325033b0.png)

Example:
```sh
$ sudo /usr/share/bcc/tools/old/offcputime -uf 10 >off-cpu &

$ sleep 15

# there is no "big sleep"
$ grep '^sleep;' off-cpu
sleep;int_ret_from_sys_call;syscall_return_slowpath;exit_to_usermode_loop;schedule 121
```

```sh
$ sudo /usr/share/bcc/tools/execsnoop -xt
TIME(s) PCOMM            PID    RET ARGS
0.001   bash             24430    0 /usr/bin/sudo /usr/share/bcc/tools/old/offcputime -uf 10
0.011   sudo             24431    0 /usr/share/bcc/tools/old/offcputime -uf 10
3.776   bash             24432    0 /bin/sleep 15
28.839  bash             24435    0 /bin/grep --color=auto ^sleep; off-cpu
```
I'm not sure. Is this an expected behavior?

**Comment by markdrayton** [comment]
This is expected. offcputime can only say how much time a task spent off the CPU if it saw both the on->off and off->on transitions.

In your example it would (assuming a zero startup time, which is unlikely) see the initial on->off transition of the big sleep but the script ends before the sleeping process wakes up and goes off->on. I guess it could calculate the time slept so far but it'd be misleading. 

It's similar for tasks that went off CPU before offcputime started -- the script will see them wake up but as it has no idea when they went to sleep it can't do anything reasonable.

**Comment by evverx** [comment]
> but the script ends before the sleeping process wakes up and goes off->on. I guess it could calculate the time slept so far but it'd be misleading.

Maybe. But `offcputime` could print warning at least. Something like:
```
    start = b.get_table("start")
    for pid, offcpu_start in start.iteritems():
        print_to_stderr("excluding offcputime for pid={0} (1)".format(pid, end_time - offcpu_start))
    start.clear()
```

**Comment by brendangregg** [comment]
Yes, expected behavior. I suppose it could print a warning, but it's going to be very common (likely almost 100% of the time), and probably better stated in the man page: something like "it only traces off-CPU times that began and ended while tracing".

**Comment by evverx** [comment]
Well, makes sense: #560

**Comment by evverx** [comment]
I think we need `-c`:
```
-c CMD Start the probes, run CMD, and exit when CMD finishes.
```
But I think that's another issue.
