### ISSUE TITLE
bcc-lua is not being built because LuaJIT cannot be found by cmake

### ISSUE THREAD

**Issue by goldshtn** [iovisor/bcc#566]
On FC22, I installed luajit and luajit-devel and am getting the following output from cmake:

```
$ cmake .. -DCMAKE_INSTALL_PREFIX=/usr
-- The C compiler identification is GNU 5.3.1
-- The CXX compiler identification is GNU 5.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Latest recognized Git tag is v0.1.8
-- Git HEAD is 5815f41afff62bb176ec57a7bea3a3efc9c5f2a0
-- Revision is 0.1.8-5815f41a
-- Found BISON: /usr/bin/bison (found version "3.0.2") 
-- Found FLEX: /usr/bin/flex (found version "2.6.0") 
-- Found LLVM: /usr/local/include
-- Found LibElf: /usr/lib64/libelf.so  
-- Performing Test ELF_GETSHDRSTRNDX
-- Performing Test ELF_GETSHDRSTRNDX - Success
-- Using static-libstdc++
-- Could NOT find LuaJIT (missing:  LUAJIT_LIBRARIES) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/vagrant/bcc/build
$ luajit -v
LuaJIT 2.0.3 -- Copyright (C) 2005-2014 Mike Pall. http://luajit.org/
$ lua -v
Lua 5.3.2  Copyright (C) 1994-2015 Lua.org, PUC-Rio
```

Because LuaJIT can't be found, make doesn't build bcc-lua. Is there anything else I need to configure so that LuaJIT support is picked up by cmake?

/cc @vmg

**Comment by markdrayton** [comment]
You can do:

    LUAJIT_DIR=/path/to/luajit-2.0 cmake .. -DCMAKE_INSTALL_PREFIX=/usr

https://github.com/iovisor/bcc/pull/524 contains some previous discussion on this.

**Comment by goldshtn** [comment]
Thanks @markdrayton but it doesn't help. I'm getting the same error after pointing LUAJIT_DIR to /usr/bin (which is where luajit-2.0.3 is on my system). In any case, the error doesn't complain about LUAJIT_DIR but rather LUAJIT_LIBRARIES.

**Comment by drzaeus77** [comment]
On the Fedora buildbot I had to install luajit from source, which I let install to the default /usr/local.

**Comment by markdrayton** [comment]
Hrm.

`LUAJIT_LIBRARIES` is set from FindLuaJIT.cmake:

https://github.com/iovisor/bcc/blob/master/cmake/FindLuaJIT.cmake

I just downloaded the FC22 luajit and luajit-devel RPMs and see the -devel package doesn't contain a static libluajit library (needed at https://github.com/iovisor/bcc/blob/master/cmake/FindLuaJIT.cmake#L47), only a shared version:

    $ rpm -qlp luajit-devel-2.0.3-4.fc22.x86_64.rpm | grep libluajit
    /usr/lib64/libluajit-5.1.so

Presumably this is the issue here. Maybe you can try appending `libluajit-5.1.so` to https://github.com/iovisor/bcc/blob/master/cmake/FindLuaJIT.cmake#L47? Though I guess even if this works it'll mean `bcc-lua` won't be statically linked :-/

**Comment by drzaeus77** [comment]
This discussion sounds familiar, but I can't find the comment thread where it took place. In any case, Fedora is very opinionated when it comes to static libraries, this came up when trying to link against clang as well.. They really try to avoid shipping them. The options pretty much boil down to supporting shared libs or vendoring luajit.

**Comment by 4ast** [comment]
the beauty of luajit that it's self contained static lib. Going shared removes this main advantage. One can argue that we can do shared llvm libs too. I think fedora has -static version of libs. If they don't have it for luajit, they better add it, because we're not the only one needing it.

**Comment by goldshtn** [comment]
Closing for now, because @drzaeus77 's suggestion to build LuaJIT from source worked.
