### ISSUE TITLE
tracepoint example

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#567]
I was looking for a simple example of instrumenting a tracepoint, and didn't find one, so wrote the following. Is this ok to submit for examples/tracing, or am I using the wrong interface? (I'm wondering if I've used the kprobe hack that predates tracepoint support. Is there a much better way nowadays?)

```Python
#!/usr/bin/python
#
# tracepoint  Example of instrumenting a kernel tracepoint.
#             For Linux, uses BCC, BPF. Embedded C.
#
# test by running this, then in another shell:
#   dd if=/dev/urandom of=/dev/null bs=1k count=10
#
# Copyright 2016 Netflix, Inc.
# Licensed under the Apache License, Version 2.0 (the "License")

from __future__ import print_function
from bcc import BPF, Tracepoint
import argparse

# arguments
parser = argparse.ArgumentParser(
    description="Tracepoint example: traces random:urandom_read")
parser.add_argument("-v", "--verbose", action="store_true",
    help="print BPF program")
args = parser.parse_args()

# 1. tracepoint argument stashing
tp = Tracepoint.enable_tracepoint("random", "urandom_read")
bpf_text = '#include <uapi/linux/ptrace.h>\n'
bpf_text += tp.generate_decl()
bpf_text += tp.generate_entry_probe()
bpf_text += tp.generate_struct()

# 2. BPF program
bpf_text += """
int printarg(struct pt_regs *ctx) {
    // Fetch struct of tracepoint args. The following references a map and
    // a struct defined by (1). Run with -v to see the full BPF program.
    u64 tid = bpf_get_current_pid_tgid();
    u64 *di = __trace_di.lookup(&tid);
    if (di == 0) { return 0; }
    struct urandom_read_trace_entry args = {};
    bpf_probe_read(&args, sizeof(args), (void *)*di);

    bpf_trace_printk("%d\\n", args.got_bits);
    return 0;
};
"""
if args.verbose:
    print(bpf_text)

# 3. load BPF program
b = BPF(text=bpf_text)
Tracepoint.attach(b)
b.attach_kprobe(event="perf_trace_urandom_read", fn_name="printarg")

# header
print("%-18s %-16s %-6s %s" % ("TIME(s)", "COMM", "PID", "GOTBITS"))

# format output
while 1:
    try:
        (task, pid, cpu, flags, ts, msg) = b.trace_fields()
    except ValueError:
        continue
    print("%-18.9f %-16s %-6d %s" % (ts, task, pid, msg))
```

**Comment by brendangregg** [comment]
Ok, so that was indeed the hacky kprobe workaround approach.

Looks like tracepoints is in 4.7 (see BPF_PROG_TYPE_TRACEPOINT), so we need bcc support, and then we'll be able to have a hello world example, that's hopefully shorter!

**Comment by brendangregg** [comment]
Here's a proposed "hello world" for how I think it could work, given tracepoint support:

```Python
#!/usr/bin/python
#
# tracepoint  Example of instrumenting a kernel tracepoint.
#             For Linux, uses BCC, BPF. Embedded C.
#
# test by running this, then in another shell:
#   dd if=/dev/urandom of=/dev/null bs=1k count=10

from __future__ import print_function
from bcc import BPF

# define BPF program
bpf_text = """
#include <uapi/linux/ptrace.h>

int printarg(struct pt_regs *ctx) {
    struct random_urandom_read_trace_entry args = {};
    bpf_probe_read(&args, sizeof(args), (void *)*PT_REGS_TP(ctx));

    bpf_trace_printk("%d\\n", args.got_bits);
    return 0;
};
"""

# load BPF program
b = BPF(text=bpf_text)
b.attach_tracepoint(category="random", event="urandom_read", fn_name="printarg")

# header
print("%-18s %-16s %-6s %s" % ("TIME(s)", "COMM", "PID", "GOTBITS"))

# format output
while 1:
    try:
        (task, pid, cpu, flags, ts, msg) = b.trace_fields()
    except ValueError:
        continue
    print("%-18.9f %-16s %-6d %s" % (ts, task, pid, msg))
```

So BPF.attach_tracepoint() would need to add to the BPF program the definition for the tracepoint's data struct, in this case "random_urandom_read_trace_entry", composed of the probe name separated by an underscore, and followed by "_trace_entry". I also added a PT_REGS_TP() for the tracepoint's data location.

**Comment by 4ast** [comment]
> int printarg(struct pt_regs *ctx) {
>    struct random_urandom_read_trace_entry args = {};
>    bpf_probe_read(&args, sizeof(args), (void *)*PT_REGS_TP(ctx));
> }

the agrument to tracepoint program is the actual tracepoint data, not pt_regs.
so probe_read is unnecessary. The whole 'struct random_urandom_read_trace_entry'
is there in the buffer already created by kernel tracepoint mechanism ready for bpf program to poke into.
Like in samples/bpf/offwaketime_kern.c
```
struct sched_switch_args {
        unsigned long long pad;
        char prev_comm[16];
        int prev_pid;
        int prev_prio;
        long long prev_state;
        char next_comm[16];
        int next_pid;
        int next_prio;
};
SEC("tracepoint/sched/sched_switch")
int oncpu(struct sched_switch_args *ctx)
{
        u32 pid = ctx->prev_pid;
```

**Comment by brendangregg** [comment]
Oh, right, wow. That's pretty nice. So the bcc program could potentially just be:

```Python
# define BPF program
bpf_text = """
#include <uapi/linux/ptrace.h>

int printarg(struct random_urandom_read_trace_entry *args) {
    bpf_trace_printk("%d\\n", args.got_bits);
    return 0;
};
"""

# load BPF program
b = BPF(text=bpf_text)
b.attach_tracepoint(category="random", event="urandom_read", fn_name="printarg")
```

Provided the attach_tracepoint() call could declare the struct random_urandom_read_trace_entry.

Or maybe the struct name itself could be the hint.

```
int printarg(struct tracepoint_args_random_urandom_read *args) {
```

So if it starts with "tracepoint_args", bcc parses the rest for the tracepoint name, then looks it up from the tracepoint /format file.

**Comment by 4ast** [comment]
> So if it starts with "tracepoint_args", bcc parses the rest for the tracepoint name, then looks it up from the tracepoint /format file.

that is great idea!
definitely clang rewriter can detect that and add appropriate struct definition.
I would prefer double underscore like:
int printarg(struct TP__random__urandom_read *args) {

**Comment by brendangregg** [comment]
Perfect!
