### ISSUE TITLE
man page notes about bpf_perf_event_output(): 4.5 or 4.4?

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#569]
Many man pages have:

> This makes use of a Linux 4.5 feature (bpf_perf_event_output());
> for kernels older than 4.5, see the version under tools/old,
> which uses an older mechanism.

Which I think I wrote. But I just checked on 4.4 (Ubuntu Xenial), and these tools are working fine. I think bpf_perf_event_output() did make it into 4.4 ( http://lxr.free-electrons.com/source/kernel/trace/bpf_trace.c?v=4.4#L223 ), which would mean these man pages need a s/4.5/4.4/g.

**Comment by 4ast** [comment]
looks like it got into 4.4 somehow :)

**Comment by matthew-olson-intel** [comment]
It looks like this is fixed now. Time to close it?

```
$ grep -R "4\.5"
biolatpcts.8: read     95us 175us 305us 515us 895us 985us 995us 1.5ms 2.5ms 3.5ms 4.5ms  10ms
biolatpcts.8: flush     5us   5us   5us   5us   5us   5us   5us   5us   5us 1.5ms 4.5ms 5.5ms
```

**Comment by brendangregg** [comment]
Thanks for checking @matthew-olson-intel, closing.
