### ISSUE TITLE
Proper tracepoint support in BCC

### ISSUE THREAD

**Issue by goldshtn** [iovisor/bcc#587]
(Discussion from #585 about tracepoint support should move here if necessary.)

Kernel 4.7 will have native BPF support for tracepoints, using a new BPF program type. BCC should support this as well. Here are the pieces I think are necessary -- @brendangregg @4ast @drzaeus77 please let me know if I'm missing anything.

- [x] Add `attach_tracepoint` to the BPF module, which would take the tracepoint name (probably as two components, e.g. "sched" and "sched_switch") and a function name from the BPF program
- [x] Add `attach_tracepoint` to libbbc, which is very similar to the other attach functions, but it uses the proper BPF program type and the proper debugfs configuration to enable the probe
- [x] Add special treatment to the rewriter so that when a tracepoint is attached, the tracepoint arguments structure is automatically generated with some agreed-upon name that the BPF program can reference (see below)

This is the ideal API, C side:

```c
int probe_sched_switch(struct TP__sched__sched_switch__args *args) {
  bpf_trace_printk("switching from %u to %u\n", args->prev_pid, args->next_pid);
  return 0;
}
```

Python side:

```python
b = BPF(...)
b.attach_tracepoint(category="sched", event="sched_switch", fn_name="probe_sched_switch")
```

**Comment by 4ast** [comment]
all makes sense.
can we make 'category="sched", event="sched_switch"' a bit less verbose?
like tp="sched:sched_switch" ?

**Comment by goldshtn** [comment]
Sure.

**Comment by goldshtn** [comment]
The first two tasks are taken care of by #590. Regarding the third one, I am not really familiar with the clang rewriter internals so I'm not sure how to proceed. It shouldn't be terribly hard to generate the struct automatically from the `format` file (although a bit harder from C++ than from Python), but I don't know where to put the code that generates it 😈 . Any pointers would be appreciated!

**Comment by goldshtn** [comment]
@drzaeus77 If you could please give me a couple of pointers on where to put the automatic tracepoint struct generation, I'll get the whole thing wrapped up. Thanks 😄

**Comment by drzaeus77** [comment]
Let me look into it.

**Comment by drzaeus77** [comment]
Oops, didn't mean to close.

**Comment by goldshtn** [comment]
@drzaeus77 I'm trying to embed the tracepoint args structure when visiting the function declaration, in [`BTypeVisitor::VisitFunctionDecl`](https://github.com/iovisor/bcc/blob/master/src/cc/frontends/clang/b_frontend_action.cc#L253). I'm basically just calling `rewriter_.InsertText(D->getLocStart(), struct_decl)` to place the structure declaration right before the function. However, the compiler complains that it doesn't see the declaration -- as if it doesn't appear in the resulting program. 

So, first, is there an easy way to see the rewritten program? And second, am I missing something that has to be done in addition to just adding the struct declaration before the function?

**Comment by goldshtn** [comment]
@drzaeus77 I think I understand what I did wrong; the rewrites are applied, but only at the second pass of compilation. Which means that if the rewrites are necessary for the program to compile, the first pass fails with an error and we can't proceed. So, it looks like the rewriter is not something we can use for automatically generating the tracepoint structures. I am now experimenting with an approach where they are created on the Python side before passing the program text to bcc.

**Comment by goldshtn** [comment]
@drzaeus77 So, I have a prototype of creating the tracepoint structures on the Python side, but I don't particularly like it. It means we have to read the source files before passing them to bcc, and it also means the same effort would have to be duplicated for the Lua wrapper.

I don't know enough about the Clang API, but is there a way to build a rewriter that operates only on top-level function declarations and doesn't require the function bodies to be syntactically valid? Consider the following example:

```c
int tracepoint__irq__irq_handler_entry(struct TP__irq__irq_handler_entry *args) {
  bpf_trace_printk("IRQ %u\n", args->irq);
  return 0;
}
```

The body of the function requires a definition for `struct TP__irq__irq_handler_entry`, but the declaration doesn't. If we can apply a rewrite step that generates that structure, but doesn't require the function bodies to be valid, we can take care of the structures in one step, and then apply the existing rewriter that takes care of everything else. Is that feasible?

**Comment by 4ast** [comment]
right the problem with clang rewriter is exactly as you described :(
generating on python side is not great, since there are users that want to use bcc c++ api directly.
I guess before feeding into 1st pass of clang, bcc lib can do grep through the source and insert the struct.
That's not a pretty hack either, but if later we can find a way to hook into clang during the parsing we can still do that without any changes to py/lua/c++ scripts.

**Comment by goldshtn** [comment]
I *think* I figured something out. I'm building another front end action, which would run and rewrite the source before the 1st phase. We would ignore errors coming from this phase and feed the rewritten output to the existing pipeline. I think this can work -- just need to give it a bit more work.

**Comment by 4ast** [comment]
sounds great to me!

**Comment by drzaeus77** [comment]
Yes, that sounds feasible, it can be a bit tricky to have compilable C syntax at each phase of the rewriter.

If it helps, you might also consider things like constructing a custom header file, that can be injected as a custom -i/virtual/myheader.h in the internal flag arguments to the `compilation` unit in src/cc/frontends/clang/loader.cc. For instance, see the list of kflags that get pushed at the beginning, including the internal helpers.h file.

**Comment by goldshtn** [comment]
It's not going to be compilable. That's the problem really - I want to take a function declaration with a struct that's not defined and define it as a rewrite step. I think it should work even though the body of the function doesn't compile. At least that's what it looks like from some sample code I tried. So, I can do a rewrite and ignore the errors, then feed the result into the rest of the pipeline. Or, as you point out, instead of rewriting I could generate a virtual header file. That's a bit cleaner because the front end action won't need a rewriter at all in that case.

**Comment by goldshtn** [comment]
@4ast @drzaeus77 @brendangregg  I have a WIP in progress [here](https://github.com/iovisor/bcc/compare/master...goldshtn:auto-tp), would appreciate any comments before I add some tests and wrap this up into a PR. Note that `attach_tracepoint` is now optional, I added a special case (similar to what we had for kprobes) for functions that start with "tracepoint__" and attach the tracepoint automatically.

Usage example:

```python
#!/usr/bin/env python

from bcc import BPF
from time import sleep

bpf = BPF(text="""
#include <linux/ptrace.h>

BPF_HASH(count, u32, u32);

int tracepoint__irq__irq_handler_entry(struct TP__irq__irq_handler_entry *args) {
    u32 key = args->irq;
    u32 val = 0;
    u32 *existing_val = count.lookup_or_init(&key, &val);
    (*existing_val)++;
    return 0;
}

struct key_t {
    int protocol;
    u64 slot;
};

BPF_HISTOGRAM(transitions, struct key_t);

int tracepoint__net__net_dev_start_xmit(struct TP__net__net_dev_start_xmit *args) {
    struct key_t key = {0};
    key.protocol = args->protocol;
    key.slot = bpf_log2l(args->len);
    transitions.increment(key);
    return 0;
}
""")

print("Counting interrupts and net xmits, Ctrl-C to quit...")
try:
    sleep(999999)
except KeyboardInterrupt:
    pass

print("")
counts = bpf["count"]
print("%-8s %-8s" % ("IRQ", "COUNT"))
for k, v in counts.items():
    print("%-8d %-8d" % (k.value, v.value))

print("")
transitions = bpf["transitions"]
transitions.print_log2_hist("len", "protocol")
```

Sample run:

```
# ~vagrant/test_bcc_tp.py
Counting interrupts and net xmits, Ctrl-C to quit...
^C
IRQ      COUNT
24       8
27       65


protocol = 2048
     len                 : count     distribution
         0 -> 1          : 0        |                                        |
         2 -> 3          : 0        |                                        |
         4 -> 7          : 0        |                                        |
         8 -> 15         : 0        |                                        |
        16 -> 31         : 0        |                                        |
        32 -> 63         : 0        |                                        |
        64 -> 127        : 36       |****************************************|
       128 -> 255        : 7        |*******                                 |
       256 -> 511        : 6        |******                                  |
```

**Comment by 4ast** [comment]
awesome! the example looks great!
Can we use TP__ or tracepoint__ prefix for both func name and struct name just to be consistent? otherwise the obvious question why they are different?
Having both of them specifying full event path also seems redundant.
Can we do something like:
int tracepoint__net__net_dev_start_xmit(struct _ *args)
where 'struct _' is the same for all tracepoints, since we can hack it away before clang parses it for real?

On the code size...
ignoring '__data_loc' is buggy, since it can be in the middle. Ex: btrfs/btrfs_space_reservation

I thought about using only simple types u8,u16 that can be derived from 'size' field,
instead of
tp_struct += "\t" + field_type + " " + field_name + ";\n";
since some of the 'field_type' will be 'loff_t', 'dev_t', etc
which will require appropriate #include 
but if we can keep real types it's certainly better.

**Comment by goldshtn** [comment]
@4ast: I think Clang's rewriter API is quite limited and would make some of these ideas a bit difficult to implement. For example, suppose the user puts a "struct _ * args" in there. The only interface I have at the rewriter level is to replace the string "struct _ *" (which I can obtain from the QualType) with something else. And it might be fragile in case the reported QualType is not exactly the same thing mentioned in the signature, and then the replacement would fail. For example, if the signature says "A*" the reported type can be "A *" (with a space) and string replacement wouldn't work. I think the rewriter API doesn't give you direct access to the AST so you can't do any smart replace work. 

What could work is omitting the argument completely. So the user would write:

```c
int tracepoint__irq__irq_handler_entry() {
  int irq = args->irq;
  ...
}
```

And we would transform the signature so it includes the "struct NNN * args". What do you think? 

Also, not sure what the verdict is on the tracepoint field types. Do you want to keep the original pid_t, dev_t etc. or replace them with a generic integral type? The current solution is actually easier because it also supports arrays etc. (e.g. "char prev_comm[16]").

**Comment by 4ast** [comment]
yeah, good points. I like 'tracepoint__irq__irq_handler_entry()' as well.
I think it's cleaner to keep original types. If that will cause issues we can reconsider.
Thank you for tackling this. I think it's starting to look pretty awesome!

**Comment by goldshtn** [comment]
@4ast: Unfortunately it turns out that even adding a parameter is not easy with Clang :-(

I don't have access to the source location of the function's parameter list (only the declaration start and the start of the body), so I can't insert the new parameter using the rewriter without resorting to horrible hacks like taking the start location of the body and going backward a predefined number of bytes, which would break in the presence of extraneous spaces.

Another option I see is that the user writes:

```c
int tracepoint__irq__irq_handler_entry(void * any_name) {
  bpf_trace_printk("%d\n", args->irq);
  return 0;
}
```

... and we generate an extra statement at the beginning of the function that does something like:

```c
struct TP__irq__irq_handler_entry * args = any_name;
```

This can be potentially confusing to the user because they have to use `args` and not the parameter name in the function body. On the other hand, it's relatively easy to implement.

Another option I can experiment with is that the user writes:

```c
int tracepoint__irq__irq_handler_entry(void * any_name) {
  bpf_trace_printk("%d\n", any_name->irq);
  return 0;
}
```

... and we still generate a statement at the beginning of the function that declares:

```c
struct TP__irq__irq_handler_entry * __real_args = any_name;
```

... and we also replace any references to `any_name` with references to `__real_args` inside the function's body. This is a bit more tricky but I think is doable using Clang's `VisitNNN` API.

Finally, we could also offer a macro:

```c
#define TP_PROBE(category, event) \
  int tracepoint__##category__##event(struct TP__##category__##event * args)
```

That would be almost effortless, but a bit inconsistent with the current approach we have for defining probes. Thoughts?

**Comment by goldshtn** [comment]
@4ast: [Implementation of the alternative with TRACEPOINT_PROBE macro](https://github.com/iovisor/bcc/compare/master...goldshtn:auto-tp)

I think it's not bad:

```c
TRACEPOINT_PROBE(irq, irq_handler_entry) {
  bpf_trace_printk("%d\n", args->irq);
  return 0;
}
```

**Comment by 4ast** [comment]
agree. the macro looks the best. do you still need to have different prefixes in there?
TP__ vs tracepoint__ ?

**Comment by goldshtn** [comment]
I don't know if it's a good idea that the function and the struct would have the same name though.

**Comment by 4ast** [comment]
C allows to have the same name for function and for struct.
With the same name I was thinking to try something like:
#define TP1 tracepoint__irq__irq_handler_entry
int TP1(struct TP1 *args) {
}

**Comment by goldshtn** [comment]
OK, I think it's wrapped up now (opened PR #602). I added a test and made both the function and the struct follow the naming convention `tracepoint__category__event`.
