### ISSUE TITLE
compile error /bcc/src/cc/frontends/clang/b_frontend_action.cc:268:24: error: ‘class clang::FunctionDecl’ has no member named ‘params’

### ISSUE THREAD

**Issue by liubogithub** [iovisor/bcc#597]
[root@localhost build]# make
Scanning dependencies of target clang_frontend
[  2%] Building CXX object src/cc/frontends/clang/CMakeFiles/clang_frontend.dir/loader.cc.o
[  4%] Building CXX object src/cc/frontends/clang/CMakeFiles/clang_frontend.dir/b_frontend_action.cc.o
/home/bcc/src/cc/frontends/clang/b_frontend_action.cc: In member function ‘bool ebpf::BTypeVisitor::VisitFunctionDecl(clang::FunctionDecl*)’:
/home/bcc/src/cc/frontends/clang/b_frontend_action.cc:268:24: error: ‘class clang::FunctionDecl’ has no member named ‘params’
     for (auto arg : D->params()) {
                        ^
make[2]: *** [src/cc/frontends/clang/CMakeFiles/clang_frontend.dir/b_frontend_action.cc.o] Error 1
make[1]: *** [src/cc/frontends/clang/CMakeFiles/clang_frontend.dir/all] Error 2
make: *** [all] Error 2

----------
I compiled llvm and clang by following INSTALL.md and I checked that there is no '->params' in the definition of FunctionDecl (in llvm/tools/clang/include/clang/AST/).

Am I missing anything important?

**Comment by drzaeus77** [comment]
This is an api change in clang 3.9, I have a pretty simple fix but I'm away
from my computer for the weekend. The change is to use normal iterators
(begin/end) rather than params (which is renamed to parameters).
