### ISSUE TITLE
Python module unregisters probes only at-exit, not when the BPF object is destroyed

### ISSUE THREAD

**Issue by goldshtn** [iovisor/bcc#605]
There's a somewhat un-intuitive behavior in the Python bcc module. Namely, probes are added to a `BPF` object instance -- either automatically through `__init__` or manually via methods such as `attach_kprobe` etc. However, probes are automatically deleted only at program exit -- in the `cleanup_probes` global function, which is registered with `@atexit.register` to run on shutdown.

This makes for brittle code, and in fact we have 3 tests in test_histogram.py, which rely on this behavior unintentionally. The first test attaches a probe, doesn't detach it, and the subsequent tests work because the probe is still attached -- even though the wrong probe function is being invoked. (Discovered as I broke the build in #602.)

I propose that in addition to the `@atexit.register` cleanup function, we also add an explicit `close` method to the `BPF` object that will unregister probes that were added through that `BPF` object. We should encourage probe cleanup at the `BPF` object level.

/cc @drzaeus77

**Comment by 4ast** [comment]
makes sense to me

**Comment by markdrayton** [comment]
> I propose that in addition to the @atexit.register cleanup function, we also add an explicit close method to the BPF object that will unregister probes that were added through that BPF object.

Do we need anything fancier than calling `cleanup_kprobes` from the `BPF.close` method of a `BPF` object here? As far as I can see this'll only unregister probes that were registered by that object.

**Comment by goldshtn** [comment]
I might be missing something trivial, but why would it only unregister probes that were registered by that object?

**Comment by goldshtn** [comment]
Oh and if we could call it "cleanup" or something while we're at it. It's not cleaning only kprobes for a while now.

**Comment by markdrayton** [comment]
Oh, doh, you're right — I forgot that `open_kprobes` and friends are global to the module, not a `BPF` instance.

> Oh and if we could call it "cleanup" or something while we're at it. It's not cleaning only kprobes for a while now.

Yeah, I spotted that one too.

**Comment by markdrayton** [comment]
I think my earlier comments were confusing. By

> As far as I can see this'll only unregister probes that were registered by that object.

I meant that calling the global `cleanup_kprobes` from a `cleanup` method on `BPF` would only remove probes that were added by the instantiated `BPF` object. In other words, no probes/tracepoints that existed before the `BPF` module was instantiated would be touched. It'd just do what the current cleanup does but on demand.

Adding a method to call `cleanup_kprobes` then using this in the histogram/probe_count tests seems to do the trick. I'll update #614 when I get a moment.

**Comment by goldshtn** [comment]
Just to make sure: you are now tracking the probes/tracepoints on the BPF object level, so that you can clean up only the probes added by that object?

**Comment by markdrayton** [comment]
> Just to make sure: you are now tracking the probes/tracepoints on the BPF object level, so that you can clean up only the probes added by that object?

That wasn't my original intention (I misunderstood) but looking more closely it's clear that is what is needed. So yes :)

It turns out there is some additional stuff to clean up here. `open_kprobes` (and perhaps the other probe types) can contain a mix of `str` and `unicode` (on 2.7) keys, depending on how they were added. For instance, probe regex matches come from the output of `awk`, which runs through `str.decode()` to produce `unicode` keys, but non-regex probes are registered with `str` keys. Only `str`-keyed probes are removed at the moment:

https://github.com/iovisor/bcc/blob/master/src/python/bcc/__init__.py#L49

I'll fix this up too. I hope to get a new PR out today.

**Comment by markdrayton** [comment]
I think this is all done now. Ready to close?
