### ISSUE TITLE
Bitfield access

### ISSUE THREAD

**Issue by markdrayton** [iovisor/bcc#613]
BCC doesn't currently support accessing bitfields. We can work around this by accessing a nearby member and moving pointers appropriately (e.g. #270) but these tricks are very brittle and will likely be upset by changes across kernel versions.

Any idea what would need to be done to make accessing bitfields by name work?

**Comment by 4ast** [comment]
plain C doesn't have a way to figure out the bit position of the bitfield, but clang should have this data. Can we teach clang rewriter to replace bitfield access within probe_read to normal load plus mask? Other ideas?
tcpaccept.py is a primary candidate for this cleanup to access sk_protocol in kernel independent way.
@goldshtn @drzaeus77

**Comment by krkini16** [comment]
@4ast The workaround in #270 seems very specific--I've tried something similar in order to access
icsk_ca_state as below
`u8 ca_state = 0;
 bpf_probe_read(&ca_state, 1, (void *)((long)&icsk->icsk_ca_state) - 3);` 

yet unfortunately the 
`error: address of bit-field requested
    bpf_probe_read(&ca_state, 1, (void *)((long)&icsk->icsk_ca_state) - 3);
`

Still occurs. has any progress been made or are there any suggestions?

**Comment by Eichhoernchen** [comment]
You need to read a non bitfield member and calculate the offset towards the member (here -3) to the byte representing the bitfield. Afterwards you can use bitmasks to select the appropriate byte..

I got here as I also wanted to read the icsk_ca_state field, yet even with this trick bcc has a problem with as it seems to again rewrite the the bpf_probe_read...

The following statement:
``` 
void my_rcv_established(struct pt_regs *ctx, struct sock *sk, struct sk_buff *skb, const struct tcphdr *th, unsigned int len)
{
    struct tcp_sock *tp = (struct tcp_sock *)sk;
    struct inet_connection_sock *inet = (struct inet_connection_sock *)sk;
    //...
    u8 ca_state = 0;
    bpf_probe_read(&ca_state, 1, (void *)((long)&inet->icsk_retransmits) - 1);
```
the last line is transformed into:
```
bpf_probe_read(&ca_state, 1, (void *)((long)&({ typeof(__u8) _val; memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)inet + offsetof(struct inet_connection_sock, icsk_retransmits)); _val; })) - 1);
```
There seems to be one additional bpf_probe_read that should not be there, can I enforce that this is not happening?

**Comment by Eichhoernchen** [comment]
Ahh I found a workaround:

By defining a proper struct everything works out:
```
   struct access_bitfield_ca_state {
        u8 pad0[offsetof(struct inet_connection_sock, icsk_retransmits)-2];
        u8 ca_state;
    };
```

```
        struct access_bitfield_ca_state* accessor = (struct access_bitfield_ca_state*)tp;
        u8 ca_state = 0;
        ca_state = accessor->ca_state;
        ca_state &= 0x3F;

```

So by moving the magic to the struct it works out

**Comment by brendangregg** [comment]
We'll fix this by documenting the workaround as part of #270 .
