### ISSUE TITLE
error: too many arguments to function call

### ISSUE THREAD

**Issue by markdrayton** [iovisor/bcc#653]
I'm trying to update dcsnoop.py to use PERF_EVENT_OUTPUT (#540). Since there are two places that submit data back to userspace I made a simple wrapper function to deduplicate this code:

``` c
enum lookup_type {
    LOOKUP_MISS,
    LOOKUP_REFERENCE,
};

struct data_t {
    u32 pid;  // PID as in the userspace term (i.e. task->tgid in kernel)
    enum lookup_type type;
    char comm[TASK_COMM_LEN];
    char name[MAX_FILE_LEN];
};

BPF_PERF_OUTPUT(events);

void submit_event(struct pt_regs *ctx, void *name, int type, u32 pid)
{
    struct data_t data = {
        .pid = pid,
        .type = type,
    };
    bpf_get_current_comm(&data.comm, sizeof(data.comm));
    bpf_probe_read(&data.name, sizeof(data.name), name);
    events.perf_submit(ctx, &data, sizeof(data));
}

// later

submit_event(ctx, (void *)nd->last.name, LOOKUP_REFERENCE, pid);
```

(full code at https://gist.github.com/markdrayton/9c7751b1bc64184af90e83ee52140c0c)

When running I get:

```
/virtual/main.c:51:23: error: too many arguments to function call, expected single argument 'ctx', have 4 arguments
    submit_event(ctx, (void *)({ typeof(const unsigned char *) _val; memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)nd + offsetof(struct nameidata, last.name)); _val; }), LOOKUP_REFERENCE, pid);
    ~~~~~~~~~~~~      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/virtual/main.c:35:1: note: 'submit_event' declared here
__attribute__((section(".bpf.fn.submit_event")))
^
/virtual/main.c:77:23: error: too many arguments to function call, expected single argument 'ctx', have 4 arguments
    submit_event(ctx, (void *)ep->name, LOOKUP_MISS, pid);
    ~~~~~~~~~~~~      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/virtual/main.c:35:1: note: 'submit_event' declared here
__attribute__((section(".bpf.fn.submit_event")))
^
2 errors generated.
```

If I drop the final argument (`pid`) I then get complaints that I passed 3 arguments when only 1 was expected.

What am I missing?

**Comment by 4ast** [comment]
try 'static inline void submit_event'.
global functions are considered independent bpf programs and 'void *name, int type, u32 pid' are fake args that clang rewrite will try to derive from registers.
@palmtenor just updated the tutorial to mention that. may be we need to be more explicit.
@drzaeus77 is there a way to detect such things? like that global function is called from another global function and 'static inline' it automatically?

**Comment by markdrayton** [comment]
Thank did the trick. Thanks. I'll leave this open so @drzaeus77 can respond but feel free to close after that.

**Comment by drzaeus77** [comment]
Not trivial at first glance, but probably doable. I tried a simple:

```patch
diff --git a/src/cc/frontends/clang/b_frontend_action.cc b/src/cc/frontends/clang/b_frontend_action.cc
index d4734c7..6b04b8d 100644
--- a/src/cc/frontends/clang/b_frontend_action.cc
+++ b/src/cc/frontends/clang/b_frontend_action.cc
@@ -489,6 +489,9 @@ bool BTypeVisitor::VisitCallExpr(CallExpr *Call) {
               SourceRange(Call->getLocStart(), Call->getLocEnd()), text);
         }
       }
+    } else if (Decl->isExternallyVisible()) {
+      error(Call->getLocStart(), "cannot call non-inline helper function");
+      return false;
     }
   }
   return true;
```

But that catches plenty of non-static non-inline functions that are called inside kernel header files. Some other logic is required.

**Comment by goldshtn** [comment]
Maybe we could emit this error only for functions declared in the current source file? It would catch most problematic cases I think.

**Comment by drzaeus77** [comment]
Yes that is the next check, but I have to re-familiarize myself with the clang::SourceManager class to be able to make that determination.

**Comment by drzaeus77** [comment]
Have something, will send a PR shortly.
