### ISSUE TITLE
biosnoop broken and dealing with multiple old versions

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#658]
```
# ./biosnoop.py 
/virtual/main.c:80:26: error: use of undeclared identifier 'REQ_WRITE'; did you mean 'REQ_OP_WRITE'?
    if (req->cmd_flags & REQ_WRITE) {
                         ^~~~~~~~~
                         REQ_OP_WRITE
include/linux/blk_types.h:233:2: note: 'REQ_OP_WRITE' declared here
        REQ_OP_WRITE,
        ^
1 warning and 1 error generated.
Traceback (most recent call last):
  File "./biosnoop.py", line 112, in <module>
    """, debug=0)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 166, in __init__
    raise Exception("Failed to compile BPF module %s" % src_file)
Exception: Failed to compile BPF module 
```

Latest linux changed REQ_WRITE to REQ_OP_WRITE.

Easy fix, but it'll then break for 4.4 users. We could have the script detect both, but that way may lie madness: having scripts with kernel version stuff baked in.

I'm inclined to keep /tools just for the latest kernel, and /tools/old for older versions.

But /tools/old already has an older biosnoop.py! So... Make a series? biosnoop.0.py, biosnoop.1.py?

**Comment by brendangregg** [comment]
Or a series could have the kernel version in the name, making it easier to find. I think they may be:

biosnoop.4.1.py
biosnoop.4.4.py

**Comment by 4ast** [comment]
in the newer kernel req->cmd_flags & REQ_WRITE is equivalent to op_is_write(req_op(req))
I would do something like:
#ifdef REQ_WRITE
#define CHECK(reg) (req->cmd_flags & REQ_WRITE)
#else 
#define CHECK(reg) (op_is_write(req_op(req)))
#endif 

If we can keep one file it's better.

**Comment by brendangregg** [comment]
Ok, but how do you feel about a comment above that that says:

```C
/*
 * Linux 4.7 changed how write flags were tested, so we handle both pre- and
 * post cases here. This pre-code should be removed once 4.6 is too old to
 * warrant support. Please avoid such kernel version tests as much as possible:
 * they inflate the code, test, and maintenance burden.
 */
```

So that:

1. We don't encourage anyone to do similar tests needlessly.
2. We've documented the kernel version, and left instructions for future maintainer.

**Comment by 4ast** [comment]
I agree with the spirit of such comment. It would be good to mention that distros like redhat don't run off-the-shelf kernels and amount of backports can make version comparison inaccurate. It's a hard problem. kprobe is unstable. Converting tools to use tracepoints could help a bit.

**Comment by brendangregg** [comment]
... Either I'm making a dumb mistake, or something might be wrong with macro processing. I did the change, it didn't work, so unwound some of the macros:

```C
#ifdef REQ_WRITE
#define REQ_IS_WRITE(req) (req->cmd_flags & REQ_WRITE)
#else 
#define REQ_IS_WRITE(req) ((req->cmd_flags >> REQ_OP_SHIFT) == REQ_OP_WRITE)
#endif
```

but it still doesn't compile - inv memory access errors. Full script:

https://gist.github.com/brendangregg/e3049d2be744776efee5a00415065e9b

If, instead, I do the ifdef's in the function code, like:

```C
#ifdef REQ_WRITE
if (req->cmd_flags & REQ_WRITE) {
#else 
if ((req->cmd_flags >> REQ_OP_SHIFT) == REQ_OP_WRITE) {
#endif
        data.rwflag = 1;
    } else {
        data.rwflag = 0;
    }
```

It works.

**Comment by drzaeus77** [comment]
Rewriter can't handle macros that need rewrite. I've started experimenting
with trying to do IR level rewrite instead, which should in theory avoid
this increasingly frequent issue, but no idea yet on how feasible that
approach will be.
