### ISSUE TITLE
bcc-tools now need kernel source

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#660]
Followed INSTALL.md on Ubuntu Xenial:

```
# /usr/share/bcc/tools/biosnoop 
chdir(/lib/modules/4.4.0-28-generic/source): No such file or directory
Traceback (most recent call last):
  File "/usr/share/bcc/tools/biosnoop", line 112, in <module>
    """, debug=0)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 197, in __init__
    raise Exception("Failed to compile BPF module %s" % src_file)
Exception: Failed to compile BPF module 
```

/lib/modules/4.4.0-28-generic/source is not installed.

Exact same server image, from a month ago:

```
# /usr/share/bcc/tools/biosnoop 
TIME(s)        COMM           PID    DISK    T  SECTOR    BYTES   LAT(ms)
0.000000000    jbd2/xvda1-8   299    xvda1   W  556056    12288      0.11
0.001318000    jbd2/xvda1-8   299    xvda1   W  556080    4096       0.05
```

/lib/modules/4.4.0-28-generic/source is still not installed. But the tools worked.

Working version:

```
# cksum /usr/lib/python2.7/dist-packages/bcc/__init__.py
346899254 30118 /usr/lib/python2.7/dist-packages/bcc/__init__.py
# wc /usr/lib/python2.7/dist-packages/bcc/__init__.py
  792  2737 30118 /usr/lib/python2.7/dist-packages/bcc/__init__.py
```

**Comment by pchaigno** [comment]
Are you sure this is an issue with `bcc` itself? I tested it after compiling from sources. I tried commits `a1333bc` (from a month ago), `31cd104` (7 Feb), `5bd0eb2` (26 Jan), and `c6009c5` (today). In each case, I got the `chdir(/lib/modules/4.4.0-28-generic/source): No such file or directory` error.

**Comment by vRobM** [comment]
I just ran into the same problem on 16.04. even after installing kernel-source, it still doesn't work. Creating the source dir didn't help either. What is it expecting?

`:/usr/share/bcc/tools$ ./bashreadline
chdir(/lib/modules/4.4.0-34-generic/source): No such file or directory
Traceback (most recent call last):
  File "./bashreadline", line 51, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 197, in __init__
    raise Exception("Failed to compile BPF module %s" % src_file)
Exception: Failed to compile BPF module
`

**Comment by drzaeus77** [comment]
What version of python-bcc/libbcc do you have installed? From source, or
debian?

**Comment by vRobM** [comment]
`:/usr/share/bcc/tools$ dpkg -l | grep bcc
ii  bcc-tools                           0.1.8-410.git.c6009c5               all          Command line tools for BPF Compiler Collection (BCC)
ii  libbcc                              0.1.8-410.git.c6009c5               amd64        Shared Library for BPF Compiler Collection (BCC)
ii  libcc1-0:amd64                      5.4.0-6ubuntu1~16.04.2              amd64        GCC cc1 plugin for GDB
ii  python-bcc                          0.1.8-410.git.c6009c5               all          Python wrappers for BPF Compiler Collection (BCC)`

**Comment by drzaeus77** [comment]
Okay then probably #657 broke this, but fixed it for debian.

Specifically:
https://github.com/iovisor/bcc/pull/657/commits/c6688dda4e856be43b8651afe92d7e32e63faea9

**Comment by brendangregg** [comment]
Anyone know a way to fix this for both Ubuntu and Debian? I've set the label to be high priority, since I think this breaks bcc for Ubuntu users right now.

**Comment by drzaeus77** [comment]
I thought the change in #657 should have fixed this for Ubuntu and broke it again for debian. Is that not the case?

**Comment by brendangregg** [comment]
sorry, I'll retest

**Comment by brendangregg** [comment]
ok, now works on Ubuntu. I'll close this ticket unless people say it's still broken!

**Comment by vRobM** [comment]
Confirmed, works after update.
