### ISSUE TITLE
Is it possible that tracing OpenFlow packets using BCC?

### ISSUE THREAD

**Issue by TaekhoNam** [iovisor/bcc#673]
Hello, I'm a student from Korea.

I already traced some types of packets including TCP using BCC in I/O Visor project.
But, I could not success trace OpenFlow packet. Is it possible using BCC?

I want to implement an application using I/O Visor BCC with SDN environment. 
So, Tracing the OpenFlow packet is the most important function of my application.

If it can be possible, I wonder how to do it.
Please give some recommendation for it.

Thank you.

**Comment by brendangregg** [comment]
Does any kernel- or user-level software on your system, particularly functions, execute to process the packets? If so, then yes, it can be traced.

**Comment by TaekhoNam** [comment]
Thanks you so much.
I got it cause your clear answer.

I will try it. Thank you so much again :D
