### ISSUE TITLE
tcpconnect: filter based on destination port

### ISSUE THREAD

**Issue by chantra** [iovisor/bcc#681]
Currently one can specify a process id to monitor for tcpconnects. Would there be any value doing so for a specific port. The specific case this is trying to solve is "tell me what is initiating connection to port X".

Currently, this can be achieve with a bit of `grep`ping, but it may be convenient to not track every connections within `trace_connect_entry` if we don't care about them in the first place.

I would assume we can access the destination port through `struct sock *sk` in  `trace_connect_entry` and return early if this is not matching the port of interest.

**Comment by brendangregg** [comment]
Sure, makes sense. since -p is taken... maybe -P PORT, --port PORT.

Some tools will need to differentiate between destination and source ports, but I don't think this one needs to or should.

**Comment by chantra** [comment]
I will look into this when times allow. I can't seem to be able to assign to myself, please do if you can.
