### ISSUE TITLE
filelife no output

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#703]
On my Linux 4.8-rc4, vfs_create() isn't being called, so filelife doesn't work.

```
 # /apps/perf-tools/bin/kprobe -s p:ext4_create
Tracing kprobe ext4_create. Ctrl-C to end.
       supervise-3245  [001] d... 6061999.906742: ext4_create: (ext4_create+0x0/0x1b0)
       supervise-3245  [001] d... 6061999.906751: <stack trace>
 => do_filp_open
 => do_sys_open
 => SyS_open
 => entry_SYSCALL_64_fastpath
```

Looks like creates will be coming from the open() path instead.

Options:
A. also trace open()s with the O_CREAT flag, or,
B. trace the return of filename_create(), which gives us the dentry *.

These can be done in addition to tracing vfs_create(). We won't get double output, since only one vfs_unlink() is called.

**Comment by dark** [comment]
Same issue for me on 4.7.4.

While testing changes in #700 , I could only see entries created by an ecryptfs mount, but nothing through ext4.

**Comment by brendangregg** [comment]
Gah, filename_create() isn't firing on my latest 4.8 kernel, even though the symbol is there. Inlined in this code-path? Looking for an alternate, maybe security_inode_create().
