### ISSUE TITLE
tplist: Print USDT raw arguments for debugging in super-verbose mode

### ISSUE THREAD

**Issue by goldshtn** [iovisor/bcc#711]
This requires adding a function in libbcc to expose the raw argument data. @4ast Did you want this to be printed per location (and indeed the argument sizes and values can be different in each location), or just the largest argument size as we report in #710?

**Comment by 4ast** [comment]
not sure what you mean by the largest size.
I was imagining that every probe will have different set of args and we print whatever bcc recognizes.
Then it's useful for the person who adds dynamic probe to the code and can examine
the assembler code that probe is indeed capturing correct registers
and useful to probe user (bcc script writer) that will come at some later time and
can also check that bcc script will pick the right bits.
In other way, I'm thinking how we debug big application that is being actively developed while in parallel sdt.h file is being hacked too and bcc side is also evolving.
Many moving pieces and hopefully tplist can be one stop shop for debugging.
cc @palmtenor

**Comment by brendangregg** [comment]
I think @goldshtn might be referring to how one probe name can be instrumented in multiple locations? In which case, the arguments should be the same (by virtue of the programmer making them the same).

Eg, I'm looking at MySQL right now:

```
  stapsdt              0x0000004d	NT_STAPSDT (SystemTap probe descriptors)
    Provider: mysql
    Name: read__row__start
    Location: 0x00000000011e4eb1, Base: 0x00000000017cc440, Semaphore: 0x0000000001ccd424
    Arguments: 8@496(%rax) 8@512(%rax) -4@$1
  stapsdt              0x0000004d	NT_STAPSDT (SystemTap probe descriptors)
    Provider: mysql
    Name: read__row__start
    Location: 0x00000000011e4f0a, Base: 0x00000000017cc440, Semaphore: 0x0000000001ccd424
    Arguments: 8@496(%rax) 8@512(%rax) -4@$1
```

One probe, two locations, same arguments.

**Comment by goldshtn** [comment]
@4ast: What I meant was whether you want the information at the location level, or just at the probe level, because as @brendangregg notes, there might be multiple locations for each probe. What's more, the argument sizes don't necessarily have to agree. For example, you could have an integer argument that in one location would be found in an Rnn register (64-bit), in another location would be simply a hard-coded 32-bit constant, and in a third location would be in an Exx register (32-bit). That's why I asked if you'd want the actual nitty-gritty details at the location level, including the register, stack offset, etc., or something more general like "this probe here has two arguments".

**Comment by 4ast** [comment]
to me 'max verbosity' is nitty-gritty details.
There is 'readelf' to print those annotations, of course. I was hoping that tplist will print the same details _after_ parsing them. I think it should help developers of probes, of sdt.h, of scripts, of tplist.

**Comment by goldshtn** [comment]
Not sure what the difference between readelf output and what you expect from tplist should be. If you want the exact location of the argument (stack offset, register, size etc.) that's exactly what you get from readelf...

**Comment by 4ast** [comment]
the difference is to print it _after_ parsing. To see that what ArgumentParser::parse understood.

**Comment by goldshtn** [comment]
OK, so hopefully it would be the same output *if* libbcc understood the format correctly, and you'd use that to debug any changes you plan to make to sdt.h and scripts. Right?

**Comment by 4ast** [comment]
exactly
