### ISSUE TITLE
distributed bridge example isn't working on ubuntu xenial

### ISSUE THREAD

**Issue by zaafar** [iovisor/bcc#713]
Kernel: 4.4.0-41-generic
Description:	Ubuntu 16.04.1 LTS
bcc installed via: https://repo.iovisor.org/apt/xenial xenial-nightly main

Upon debugging I found out that while setting tunnel key or getting kernel key in tunnel.c via following call

`bpf_skb_{set,get}_tunnel_key(skb, &tkey, sizeof(tkey), 0);`

bcc pass sizeof(tkey) as 28 bytes where as in kernel headers the key structure is of 8 bytes. If I change the above statement and pass 8 (as shown below) rather than sizeof(tkey) this example start working.

`bpf_skb_{set,get}_tunnel_key(skb, &tkey, 8, 0);`

Maybe I am wrong but is this due to upgrading headers with 4.5 features in #424 and then removing checks in #472. What should be the posible fix for this?

**Comment by 4ast** [comment]
I think the cleaner fix is to use offsetof(struct bpf_tunnel_key, remote_ipv6[1]) instead of 8,
other than that the proposed fix looks good.
