### ISSUE TITLE
argdist to clear histograms

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#718]
I'm trying to catch an intermittent problem with argdist, and it's rolling output is great, but since it is using cumulative counters it's hard to spot the output where things went awry. Shouldn't it clear the maps for each interval by default? Maybe do that, then have an option for cumulative mode? //CC @goldshtn

**Comment by goldshtn** [comment]
Yes, I totally agree that it makes sense to clear the maps by default. Fixed in #719.
