### ISSUE TITLE
Build broken on GCC6

### ISSUE THREAD

**Issue by abeutot** [iovisor/bcc#735]
It looks like the build fails using GCC6 since the introduction of this commit (d19e0cb06390c552c09085caebddbb0d1ef19f6e) but I wouldn't know for sure since it is the first time I tried to compile this project.

I get the same error message as here https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70129.

**Comment by 4ast** [comment]
@dark 
I guess we can check whether compiler is gcc6 or above
or just revert it. Thoughts?

**Comment by dark** [comment]
I think that this commit is cursed :) 
I will add a workaround for gcc6 for now.

**Comment by dark** [comment]
I don't have easy access to a machine with gcc6 yet.
@abeutot Could you please check if the commit above fixes the build on gcc6, or is there something else to look at? Thanks!

**Comment by abeutot** [comment]
@dark it does fix the fix the build indeed for me. Thanks :)
