### ISSUE TITLE
retire stacksnoop

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#737]
Now that we have trace.py -K and -U for kernel and user stacks, we might not need tools/stacksnoop.

I wanted to bring this up before @goldshtn fixes it :)

I think it might make sense to move stacksnoop to examples/tracing, since it's a short example of stack walking, and then delete stacksnoop's _example.txt file and man page (since it's no longer a tool). I can do a PR, just wanted to raise it here first.

**Comment by goldshtn** [comment]
LOL. I wanted to say the same thing, it looks like we don't need stacksnoop. It can make a nice example.

**Comment by 4ast** [comment]
if trace.py is really a replacement then we should be able to replace stacksnoop with the wrapper of trace.py. The new stacksnoop.py would just call trace.py with appropriate args?
