### ISSUE TITLE
Run-time detection of kernel headers location for containers (follow up of #397)

### ISSUE THREAD

**Issue by alban** [iovisor/bcc#743]
I am trying to run bcc from within a Docker container. The Dockerfile has the following:

```
FROM zlim/bcc
RUN apt-get update -y && apt-get install -y bash runit conntrack iproute2 \
    util-linux curl python bcc-tools python-bcc libbcc
```

And then, I run the Docker container with options like:

```
docker run --rm --privileged -v /var/run:/var/run \
    -v /lib/modules:/lib/modules --net=host --pid=host ...
```

It does not always find the file `./include/linux/kconfig.h`, depending on the host distributions. According to https://github.com/iovisor/bcc/issues/397#issuecomment-186033921, the headers can be in the `sources` or in the `build` directory, depending on distributions. And the compilation option `-DBCC_KERNEL_HAS_SOURCE_DIR=1` allows to distinguish that.

But at build-time of the Docker image, I don't know yet whether the host distribution will split the `source` and `build` directories.

Could bcc do the check of `source` or `build` at run-time instead of build-time? In my example, the bcc package in "zlim/bcc" image, based on Ubuntu 16.04, might not use the correct compilation option, depending on where the Docker image is executed. And this fails on CoreOS, which has `/lib/modules/4.6.3-coreos/{build,source}`.

/cc @iaguis @asymmetric

**Comment by krnowak** [comment]
There is the code for that here, just needs testing - https://github.com/kinvolk/bcc/tree/krnowak/kernel-dirs-at-runtime

**Comment by schu** [comment]
> There is the code for that here, just needs testing - https://github.com/kinvolk/bcc/tree/krnowak/kernel-dirs-at-runtime

Tested manually on Debian testing, works for me :+1:

**Comment by 4ast** [comment]
@krnowak interesting idea! Could you send a PR, so we can test it broadly? cc @drzaeus77 @dark

**Comment by schu** [comment]
> Could you send a PR, so we can test it broadly?

We opened a PR: https://github.com/iovisor/bcc/pull/823
