### ISSUE TITLE
tcplife: misses passive connections closed by server

### ISSUE THREAD

**Issue by pchaigno** [iovisor/bcc#788]
tcplife misses passive connections when they are closed by the server.
You can reproduce with:

```
server$ nc -vl 8888 > /dev/null
Listening on [0.0.0.0] (family 0, port 8888)
Connection from [client] port 8888 [tcp/*] accepted (family 2, sport 37444)
^C
```

```
client$ nc -v server 8888 < /dev/urandom 
Connection to server 8888 port [tcp/*] succeeded!
```

The PID/comm for passive connections is [retrieved on the `LAST-ACK` state only](https://github.com/iovisor/bcc/blob/b0468d927d262b495f1f736ebfb0007f7c4818a4/tools/tcplife.py#L149-L151), thus missing connections closed by the server (`FIN-WAIT-1` state).

/cc @brendangregg

**Comment by brendangregg** [comment]
fixed by #788, closing.
