### ISSUE TITLE
mmap: Cannot allocate memory

### ISSUE THREAD

**Issue by vitalyvch** [iovisor/bcc#791]
If I re-run opensnoop.py many-many times I get:

> "mmap: Cannot allocate memory"

Do you have any idea about the root of issue?

System: Ubuntu 16.04 LTS

**Comment by pchaigno** [comment]
I couldn't reproduce with 10100 runs of the [last version of `opensnoop.py`](https://github.com/iovisor/bcc/blob/8e6109bfec75918c39e56ebdbd5c0ad6ac0bde17/tools/opensnoop.py). I couldn't notice any increase in the usage of memory either. I'm under Ubuntu 16.04.1 LTS with Linux 4.4.0-45-generic.

How did you stop `opensnoop.py` after each run?

**Comment by goldshtn** [comment]
@vitalyvch Are there any additional steps we can take to reproduce this? Or can this be closed?

**Comment by vitalyvch** [comment]
Most likely we should it close now.
