### ISSUE TITLE
execsnoop error on 4.8.6-1.el7.elrepo.x86_64

### ISSUE THREAD

**Issue by mufeedusman** [iovisor/bcc#797]
Upgraded my kernel (CentOS) from,

> 3.10.0-327.el7.x86_64 to 4.8.6-1.el7.elrepo.x86_64

And installed bcc-tools following,

```
# echo -e '[iovisor]\nbaseurl=https://repo.iovisor.org/yum/nightly/f23/$basearch\nenabled=1\ngpgcheck=0' | sudo tee /etc/yum.repos.d/iovisor.repo
# yum install bcc-tools

# rpm -qa | grep bcc
python-bcc-0.2.0-86.git.7671594.x86_64
libbcc-0.2.0-86.git.7671594.x86_64
bcc-tools-0.2.0-86.git.7671594.x86_64
```

But _execsnoop_ failed with the following,

```
# ./execsnoop
chdir(/lib/modules/4.8.6-1.el7.elrepo.x86_64/source): No such file or directory
Traceback (most recent call last):
  File "./execsnoop", line 143, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python2.7/site-packages/bcc/__init__.py", line 240, in __init__
    raise Exception("Failed to compile BPF module %s" % src_file)
Exception: Failed to compile BPF module
```

What am I doing wrong?

**Comment by markdrayton** [comment]
You need to install whatever provides `/lib/modules/4.8.6-1.el7.elrepo.x86_64/source`. This is probably the `kernel-devel` package (make sure you install the one that matches your running kernel version).

**Comment by mufeedusman** [comment]
Looks like that helped to move one step forward but,
```
# ./execsnoop 
In file included from <built-in>:316:
In file included from <command line>:7:
/virtual/include/bcc/helpers.h:25:2: error: "CONFIG_BPF_SYSCALL is undefined, please check your .config or ask your Linux distro to enable this feature"
#error "CONFIG_BPF_SYSCALL is undefined, please check your .config or ask your Linux distro to enable this feature"
```
So I need to recompile the kernel?

**Comment by markdrayton** [comment]
Yes, you need CONFIG_BPF_SYSCALL so you'll have to recompile your kernel. See https://github.com/iovisor/bcc/blob/master/INSTALL.md#kernel-configuration for full kernel information.

**Comment by goldshtn** [comment]
It's actually pretty bad news if recent CentOS kernels have BPF disabled by default. Haven't seen this on Fedora or Ubuntu.

**Comment by mufeedusman** [comment]
I could see the following enabled by default,

```
~# grep CONFIG.*BPF /boot/config-4.8.6-1.el7.elrepo.x86_64 
CONFIG_BPF=y
# CONFIG_BPF_SYSCALL is not set
CONFIG_NETFILTER_XT_MATCH_BPF=m
CONFIG_NET_CLS_BPF=m
CONFIG_NET_ACT_BPF=m
CONFIG_BPF_JIT=y
CONFIG_HAVE_EBPF_JIT=y
# CONFIG_TEST_BPF is not set
```

**Comment by goldshtn** [comment]
@mufeedusman Can this issue be closed? It looks like we got to the bottom of it.

**Comment by mufeedusman** [comment]
@goldshtn Sure. Let me do that.

**Comment by mufeedusman** [comment]
The CentOS kernel used for this (4.8.6-1.el7.elrepo.x86_64) doesn't have the CONFIG_BPF_SYSCALL parameter compiled and enabled in the current branch.

**Comment by ceeaspb** [comment]
centos kernel-ml has been updated - https://elrepo.org/bugs/view.php?id=690
4.4.33 / 4.8.9
