### ISSUE TITLE
Is there a way to get parent pid from bpf code?

### ISSUE THREAD

**Issue by vitalyvch** [iovisor/bcc#799]
I digged through API and found nothing.

**Comment by 4ast** [comment]
bpf_get_current_task() was added to be able to access arbitrary task_struct fields including task->real_parent->pid|tgid.
See tools/mountsnoop.py for example.

**Comment by vitalyvch** [comment]
THANKS.

**Comment by vitalyvch** [comment]
I have tried it. This solution does not work.

Most likely we should think about exporting getppid() syscall inside VM.

**Comment by markdrayton** [comment]
> I have tried it. This solution does not work.

Can you elaborate on this? What code did you try and on which kernel? How did it not work (error, silent failure, etc)?

**Comment by vitalyvch** [comment]
Kernel 4.8.0-34, 

```C
{
        bool t = false;
        struct task_struct *task;
        struct task_struct *real_parent_task;
        u64 ppid;

        task = (struct task_struct *)bpf_get_current_task();

        /** XXX Something wrong is here */
        bpf_probe_read(&real_parent_task,
                sizeof(real_parent_task),
                &task->real_parent);

        bpf_probe_read(&ppid,
               sizeof(ppid),
               &real_parent_task->pid);

        if (ppid == TRACED_PID)
            t |= true;
}
```

TRACED_PID is obtained via getppid() syscall and never match task->real_parent->pid or task->real_parent->tgid for unknown reason.

Currently, I think it happens because getppid() obtain ppid in a bit different way: http://lxr.free-electrons.com/source/kernel/sys.c?v=4.8#L847

**Comment by alban** [comment]
@vitalyvch could you check the return value of bpf_probe_read() and print it with bpf_trace_printk() to trace_pipe to see if it return -EFAULT or something?

Also, `struct task_struct` contains:
```
        pid_t                           pid;
        pid_t                           tgid;
```
- pid here is called tid in userspace, with syscall gettid
- tgid here is called pid in userspace, with syscall getpid (AFAIU)

So I think tgid is the correct one to use. Is the parent process is single-threaded? Is the parent process/thread still alive when you do the test?

Have you tried to print ppid and TRACED_PID with bpf_trace_printk() to see how they look like?

**Comment by firogh** [comment]
> bpf_get_current_task() was added to be able to access arbitrary task_struct fields including task->real_parent->pid|tgid.
> See tools/mountsnoop.py for example.
Is this safe to dereference task->real_parent->pid? Is it possible to crash the kernel?
