### ISSUE TITLE
bpf-map fd leak

### ISSUE THREAD

**Issue by goldshtn** [iovisor/bcc#806]
The following program leaks a bpf-map file descriptor every second (verify with `lsof | grep bpf-map`). I've added `None` assignments and even a `gc.collect` call to rule out any possibility of some object not getting reclaimed because of the Python runtime. It looks like we genuinely have a leak somewhere whereby the map fd is not getting closed. 

```
#!/usr/bin/env python

from bcc import BPF
from time import sleep
import gc

prog = """
BPF_HASH(map);

int probe(struct pt_regs *ctx) {
    return 0;
}
"""

while True:
    bpf = BPF(text=prog)
    bpf.attach_kprobe(event="__kmalloc", fn_name="probe")
    m = bpf["map"]
    m.items()
    bpf.cleanup()
    m = None
    bpf = None
    gc.collect()
    sleep(1)
```

/cc @4ast @drzaeus77

**Comment by drzaeus77** [comment]
Why call bpf.attach_kprobe on the same event multiple times? That probably overwrites the internal map keeping track of the perf structure.

**Comment by goldshtn** [comment]
It is a new `BPF` object. Discarding the whole thing and loading a new program, essentially. @drzaeus77

**Comment by goldshtn** [comment]
I can see this map fd is being opened in `b_frontend_action.cc` when compiling the program. The fd is then hard-coded into the program. I don't see anywhere where it is then closed.

**Comment by goldshtn** [comment]
@drzaeus77 I think I found the underlying issue; when the `BPFModule` is destroyed, it removes shared (exported) tables, which closes their fd, but regular tables are not removed. What's more, the `BPFModule` is not really destroyed when the `BPF` Python object is destroyed. Fixing both of these bugs seems to work. Will open a PR shortly.
