### ISSUE TITLE
Unable to run hello world on ubuntu 14.04

### ISSUE THREAD

**Issue by brycefisher** [iovisor/bcc#816]
I've tried to follow the instructions for binary installation of bcc on ubuntu 14.04 from INSTALL.md. However, I'm seeing errors when running the hello world:

```bash
# python /usr/share/bcc/examples/tracing/task_switch.py
Traceback (most recent call last):
  File "/usr/share/bcc/examples/tracing/task_switch.py", line 5, in <module>
    from bcc import BPF
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 28, in <module>
    from .libbcc import lib, _CB_TYPE, bcc_symbol, _SYM_CB_TYPE
  File "/usr/lib/python2.7/dist-packages/bcc/libbcc.py", line 116, in <module>
    lib.bpf_attach_perf_event.restype = ct.c_int;
  File "/usr/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/x86_64-linux-gnu/libbcc.so.0: undefined symbol: bpf_attach_perf_event
```

This error looks to me as though the debug symbols in my system libc are not available, thus python ctypes is unable to do FFI into BPF.

Here's my uname -a: `Linux [...] 4.5.1-040501-generic #201604121331 SMP Tue Apr 12 17:33:29 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

I found these similar threads, but they didn't seem quite the same:

 * https://github.com/iovisor/bcc/issues/311 -- for fedora, whereas I'm on ubuntu
 * https://github.com/iovisor/bcc/issues/549 -- wrong system python version, whereas:

```bash
$ python --version
Python 2.7.6
```

**Comment by brendangregg** [comment]
My guess is it's pulling in an old version of libbcc somehow. Did you start with an apt-get install of bcc-tools?

Also, how did you get a 4.5.1 kernel on ubuntu 14.04? I'd have expected a different kernel, unless you just replaced it manually.

**Comment by brycefisher** [comment]
That makes a lot of sense. I did apt-get install bcc-tools. I replaced it manually following the directions in the INSTALL.md for ubuntu.

It sounds like perhaps starting from a stock ubuntu 16.04 might be better than continuing to massage my current install?

**Comment by brendangregg** [comment]
16.04 is probably better (but a slightly older kernel), but maybe you can fix your situation by doing an apt-get remove bcc-tools. So long as the old libbcc library stops getting loaded, your new built version should start working.

**Comment by brycefisher** [comment]
Great! I'll give that a try.

**Comment by brycefisher** [comment]
@brendangregg that totally fixed my install! thank you
