### ISSUE TITLE
Frontend shared libs not installed

### ISSUE THREAD

**Issue by r4f4** [iovisor/bcc#841]
I'm packaging BCC for Fedora. When I compile the libbcc.so file and analyse it with ldd, I get:

$ ldd /usr/lib64/libbcc.so.0.2.0 
	linux-vdso.so.1 (0x00007ffc76dfd000)
	libb_frontend.so => not found
	libclang_frontend.so => not found
        [...]

Should the shared objects from src/cc/frontends/ also be installed with the 'make install' command? Or am I missing something?

**Comment by drzaeus77** [comment]
No, the shared libs should not be packaged. They are supposed to be built as .a files internally and statically linked into libbcc.so.

**Comment by r4f4** [comment]
So isn't it better to make the STATIC explicit in the respective CMakeLists.txt's? In my compilation the .so's are being generated instead of .a's.

**Comment by drzaeus77** [comment]
If that fixes the compile for your case please send a PR. On our fedora (24, rawhide) buildbots the current cmake generates .a's by default, so I'm a bit surprised that you have found a difference.

**Comment by r4f4** [comment]
Right. I'm using Fedora 25. I'll try on Fedora 24 and, if it works, check what's different between the cmakes.

**Comment by r4f4** [comment]
Oh, I found out the problem. I was using the "%cmake" macro and it defines -DBUILD_SHARED_LIBS=ON. Since the type of the lib was not explicitly set in CMakeLists.txt, it used this variable to decided to build a shared object.
