### ISSUE TITLE
trace.py to have timestamp options

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#854]
Something like:

```
  -T, --time            include time column on output (HH:MM:SS)
  -t, --timestamp       include timestamp on output (seconds.fraction)
```

Which might mean dropping the current timestamp column and only including it with -T.

Here's why I was prompted:

```
# ./trace.py 'p::__dev_get_by_name "lookup: %s", arg2' 'r::__dev_get_by_name "returned: 0x%x", retval'
TIME     PID    TID    COMM         FUNC             -
00:46:46 1703   1703   snmpd        __dev_get_by_name returned: 0xac89f000
00:46:46 1703   1703   snmpd        __dev_get_by_name returned: 0xa4bc2000
00:46:46 1703   1703   snmpd        __dev_get_by_name returned: 0xa4bc2000
00:46:46 1703   1703   snmpd        __dev_get_by_name lookup: lo
00:46:46 1703   1703   snmpd        __dev_get_by_name lookup: eth0
00:46:46 1703   1703   snmpd        __dev_get_by_name lookup: eth0
00:46:49 1703   1703   snmpd        __dev_get_by_name returned: 0xac89f000
00:46:49 1703   1703   snmpd        __dev_get_by_name returned: 0xa4bc2000
00:46:49 1703   1703   snmpd        __dev_get_by_name lookup: lo
00:46:49 1703   1703   snmpd        __dev_get_by_name lookup: eth0
00:46:49 1703   1703   snmpd        __dev_get_by_name lookup: eth0
00:46:49 1703   1703   snmpd        __dev_get_by_name returned: 0xa4bc2000
```

It's pretty awesome that I can trace the entry and return value so easily (BTW, you can reproduce this just by running "ifconfig lo0" in another window). But with output like the above, it's mixed up (I think), and I can't easily associate the entry to the return. With a -t option, and sufficient resolution (microseconds) I could sort by time and see what happened on the same PID/TIDs.

**Comment by brendangregg** [comment]
Oh, and for some reason I'd tried two probes with trace.py earlier and it didn't work -- only traced one of them. If I can reproduce I'll file. Maybe that was fixed in the meantime?...

**Comment by emfree** [comment]
It looks like passing `-o`/`--offset` prints relative timestamps, e.g.: 
```
# ./trace.py -o 'p::__dev_get_by_name "lookup: %s", arg2' 'r::__dev_get_by_name "returned: 0x%x", retval'
TIME     PID    TID    COMM         FUNC             -
13.57432 10633  10633  ifconfig     __dev_get_by_name returned: 0x7ca8d000
13.57422 10633  10633  ifconfig     __dev_get_by_name lookup: lo
13.57549 10633  10633  ifconfig     __dev_get_by_name returned: 0x7ca8d000
13.57579 10633  10633  ifconfig     __dev_get_by_name returned: 0x7ca8d000
13.57595 10633  10633  ifconfig     __dev_get_by_name returned: 0x7ca8d000
13.57538 10633  10633  ifconfig     __dev_get_by_name lookup: lo
13.57572 10633  10633  ifconfig     __dev_get_by_name lookup: lo
```

That seems like it could already be enough for this use case?

**Comment by brendangregg** [comment]
@emfree ah, right, yes. I missed that. I don't like -o/--offset, though, as -o is usually for output file. Am I being too picky? @goldshtn, would you mind if we changed -o/--offset to be -t/--timestamp? It's behavior is ok, just a name change.

**Comment by goldshtn** [comment]
No objection at all. Putting on my list...

**Comment by goldshtn** [comment]
@brendangregg There was a `-t` already, which filtered by thread id. Renamed to `-L`, and then added `-T` and `-t` for time and timestamp, respectively -- see #865.
