### ISSUE TITLE
u* tools: gracefully handle missing USDT probes

### ISSUE THREAD

**Issue by goldshtn** [iovisor/bcc#866]
It is more than likely that some people will try to use the u* tools on processes that don't have the required USDT probes (e.g. Oracle JDK, Node.js built without `--enable-dtrace` and so on). Make sure this condition is appropriately reported, in a way that isn't misleading. 

_Reported by @ceeaspb_

**Comment by ceeaspb** [comment]
@brendangregg @goldshtn fyi I have submitted requests to get the USDT probes built into the Oracle JDK
http://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8173263 / https://bugs.openjdk.java.net/browse/JDK-8173263

and http://zulu.org/forum/thread/usdt-probes-for-zulu-on-linux/

**Comment by goldshtn** [comment]
This would be very nice to have in the Oracle JDK.
