### ISSUE TITLE
couldn't allocate output register for constraint (kretprobe with kernel functions)

### ISSUE THREAD

**Issue by ton31337** [iovisor/bcc#869]
```
int kretprobe__enqueue_to_backlog(struct pt_regs *ctx, struct sk_buff *skb, int cpu)
{
        struct softnet_data *sd;
        unsigned int qlen;
        int ret = PT_REGS_RC(ctx);

        bpf_probe_read(sd, sizeof(sd), &per_cpu(softnet_data, cpu));
        qlen = skb_queue_len(&sd->input_pkt_queue);

        if (ret == NET_RX_DROP)
                bpf_trace_printk("droped packet for cpu %d, qlen: %d\\n", cpu, qlen);

        return 0;
}
```
error:
```
error: couldn't allocate output register for constraint 'r' at line 2153290099
```

anyone have some ideas what's wrong here or what should be changed?

**Comment by brendangregg** [comment]
Is it the per_cpu() causing problems? ... Can you solve this without it? Eg, dig the softnet_data * from a function argument.

**Comment by ton31337** [comment]
this function doesn't have this struct as argument

**Comment by brendangregg** [comment]
Lots to try. Find another function. Maybe it is a member of another struct argument. If the function is unrelated to that codepath, then maybe it can be associated by some UUID, like struct sk_buff *.

Or dig more into why per_cpu() fails.
