### ISSUE TITLE
llvm trunk: clang frontend broken

### ISSUE THREAD

**Issue by wr0112358** [iovisor/bcc#876]
Recent changes to lib/Transforms/IPO/AlwaysInliner.cpp in llvm trunk breaks usage of Attribute::AlwaysInline in bpf_module.cc

Attributes 'noinline and alwaysinline' are incompatible!
i64 (i8*, i64)* @load_dword
Attributes 'noinline and alwaysinline' are incompatible!
i16 (i16)* @bpf_htons
Attributes 'noinline and alwaysinline' are incompatible!
i32 (i32)* @bpf_htonl
Attributes 'noinline and alwaysinline' are incompatible!
i64 (i64)* @bpf_htonll
Attributes 'noinline and alwaysinline' are incompatible!
void ()* @smp_send_stop
Attributes 'noinline and alwaysinline' are incompatible!
void (i32)* @smp_send_reschedule
Attributes 'noinline and alwaysinline' are incompatible!
void (i32)* @smp_prepare_cpus
Attributes 'noinline and alwaysinline' are incompatible!
i32 (i32, %struct.task_struct*)* @__cpu_up
Attributes 'noinline and alwaysinline' are incompatible!
void (i32)* @smp_cpus_done
Attributes 'noinline and alwaysinline' are incompatible!
void ()* @smp_prepare_boot_cpu
Attributes 'noinline and alwaysinline' are incompatible!
i32 (%struct.pt_regs*)* @trace_read_entry
Attributes 'noinline and alwaysinline' are incompatible!
i32 (%struct.pt_regs*)* @trace_write_entry
Attributes 'noinline and alwaysinline' are incompatible!
i16 (i16)* @bpf_ntohs
Attributes 'noinline and alwaysinline' are incompatible!
i32 (i32)* @bpf_ntohl
Attributes 'noinline and alwaysinline' are incompatible!
i64 (i64)* @bpf_ntohll
Traceback (most recent call last):
  File "/opt/bcc_git/share/bcc/tools/filetop", line 153, in <module>
    b = BPF(text=bpf_text)
  File "/opt/bcc_git/lib/python2.7/site-packages/bcc/__init__.py", line 240, in __init__
    raise Exception("Failed to compile BPF module %s" % src_file)
Exception: Failed to compile BPF module

**Comment by 4ast** [comment]
@drzaeus77
