### ISSUE TITLE
execsnoop fails to run on 4.10 kernels

### ISSUE THREAD

**Issue by dsahern** [iovisor/bcc#877]
$ /usr/share/bcc/tools/execsnoop
In file included from /virtual/main.c:3:
In file included from include/linux/sched.h:61:
In file included from include/linux/cgroup-defs.h:19:
include/linux/bpf-cgroup.h:22:24: error: use of undeclared identifier 'MAX_BPF_ATTACH_TYPE'
        struct bpf_prog *prog[MAX_BPF_ATTACH_TYPE];
                              ^
include/linux/bpf-cgroup.h:23:35: error: use of undeclared identifier 'MAX_BPF_ATTACH_TYPE'
        struct bpf_prog __rcu *effective[MAX_BPF_ATTACH_TYPE];
                                         ^
include/linux/bpf-cgroup.h:32:10: warning: declaration of 'enum bpf_attach_type' will not be visible outside of this function
      [-Wvisibility]
                         enum bpf_attach_type type);
                              ^
include/linux/bpf-cgroup.h:37:15: warning: declaration of 'enum bpf_attach_type' will not be visible outside of this function
      [-Wvisibility]
                       enum bpf_attach_type type);
                            ^
include/linux/bpf-cgroup.h:41:10: warning: declaration of 'enum bpf_attach_type' will not be visible outside of this function
      [-Wvisibility]
                                enum bpf_attach_type type);
                                     ^
include/linux/bpf-cgroup.h:44:16: warning: declaration of 'enum bpf_attach_type' will not be visible outside of this function
      [-Wvisibility]
                               enum bpf_attach_type type);
                                    ^
In file included from /virtual/main.c:4:
include/linux/fs.h:2648:9: warning: comparison of unsigned enum expression < 0 is always false [-Wtautological-compare]
        if (id < 0 || id >= READING_MAX_ID)
            ~~ ^ ~
5 warnings and 2 errors generated.
Traceback (most recent call last):
  File "/usr/share/bcc/tools/execsnoop", line 143, in <module>
    b = BPF(text=bpf_text)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 240, in __init__
    raise Exception("Failed to compile BPF module %s" % src_file)
Exception: Failed to compile BPF module

**Comment by brendangregg** [comment]
Works for me, although someone really should fix this warning:

```
# uname -a
Linux bgregg-xenial-build-i-0849f9e8b879fa200 4.10.0-rc1-virtual #1 SMP Thu Dec 29 22:29:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
 # /mnt/src/bcc/tools/execsnoop.py 
In file included from /virtual/main.c:4:
include/linux/fs.h:2648:9: warning: comparison of unsigned enum expression < 0 is always false [-Wtautological-compare]
        if (id < 0 || id >= READING_MAX_ID)
            ~~ ^ ~
1 warning generated.
PCOMM            PID    PPID   RET ARGS
run              11424  2578     0 ./run
setuidgid        11424  2578     0 /usr/local/bin/setuidgid nobody /command/multilog t ./main
multilog         11424  2578     0 /command/multilog t ./main
run              11425  2577     0 ./run
run              11425  2577    -2 /command/bash 
run              11425  2577    -2 /usr/local/bin/bash 
run              11425  2577    -2 /usr/local/sbin/bash 
bash             11425  2577     0 /bin/bash 
```

Did you make headers_install?

**Comment by drzaeus77** [comment]
Failed for me (kernel == 4.9). I'm working to update [virtual_]bpf.h, currently seeing some other weird issue that is preventing me from pushing the simple fix.

**Comment by brendangregg** [comment]
Yes, I'm missing CONFIG_CGROUP_BPF (and I see that that's related to the macro). Rebuilding...

**Comment by brendangregg** [comment]
yes, I hit it with CONFIG_CGROUP_BPF.

**Comment by ribalda** [comment]
For what is worth, the warning is already fixed on linux-next

https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/include/linux/fs.h?id=cbfd0c1001bedb4b051cf4a1f5df24f1500381bc

Regards!
