### ISSUE TITLE
SSL cert for repo.iovisor.org expired

### ISSUE THREAD

**Issue by jason-azze** [iovisor/bcc#879]
Here's the message that says it all...

repo.iovisor.org uses an invalid security certificate. The certificate
expired on 12/29/2016 10:35 PM. The current time is 12/30/2016 10:33
AM. Error code: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by drzaeus77** [comment]
Hmm, letsencrypt didn't do it's job! Will investigate.

**Comment by drzaeus77** [comment]
It should be working now.
