### ISSUE TITLE
funclatency does not match any functions in the code

### ISSUE THREAD

**Issue by kartiksura** [iovisor/bcc#880]
Hi Team,

I am trying to profile a sample program (given below) to profile the functions in the code. However I am not able to get it working. 
I find bcc promising as Systemtap just crashes when I try to profile RIBS 
https://github.com/Adaptv/ribs2

**Description:**

**OS**: Ubuntu 14.04

Kernel Config:
CONFIG_BPF=y
CONFIG_BPF_SYSCALL=y
CONFIG_NETFILTER_XT_MATCH_BPF=m
CONFIG_NET_CLS_BPF=m
CONFIG_NET_ACT_BPF=m
CONFIG_BPF_JIT=y
CONFIG_HAVE_BPF_JIT=y
CONFIG_BPF_EVENTS=y
CONFIG_TEST_BPF=m

**Kernel**: 4.6.0-040600-generic

------------------------------------------------
funclatency /home/ksura16/square:*  -p 17920 -F
**0 functions matched by "/home/ksura16/square:*". Exiting.**

------------------------------------------------
cc square.c -o square -g
cat square.c 
#include<stdio.h>
// function prototype, also called function declaration
float square ( float x );                               
// main function, program starts from here

int main( )               
{
    float m, n ;
    printf ( "\nEnter some number for finding square \n");
    scanf ( "%f", &m ) ;
    // function call
while(1){
    n = square ( m ) ;                      
    printf ( "\nSquare of the given number %f is %f",m,n );
}
}

float square ( float x )   // function definition
{
    float p ;
    p = x * x ;
    return ( p ) ;
}

**Comment by brendangregg** [comment]
Works for me (Linux 4.9-rc5):

```
# /mnt/src/bcc/tools/funccount.py ./square:'*' -p `pgrep -n square`
Tracing 11 functions for "./square:*"... Hit Ctrl-C to end.
^C
FUNC                                    COUNT
square                                 258558
Detaching...

# /mnt/src/bcc/tools/funclatency.py './square:square' -p `pgrep -n square`
In file included from /virtual/main.c:3:
In file included from /lib/modules/4.9.0-rc5-virtual/build/include/linux/blkdev.h:9:
In file included from /lib/modules/4.9.0-rc5-virtual/build/include/linux/genhd.h:64:
In file included from /lib/modules/4.9.0-rc5-virtual/build/include/linux/device.h:24:
In file included from /lib/modules/4.9.0-rc5-virtual/build/include/linux/pinctrl/devinfo.h:21:
In file included from /lib/modules/4.9.0-rc5-virtual/build/include/linux/pinctrl/consumer.h:17:
In file included from /lib/modules/4.9.0-rc5-virtual/build/include/linux/seq_file.h:10:
/lib/modules/4.9.0-rc5-virtual/build/include/linux/fs.h:2693:9: warning: comparison of unsigned enum expression < 0 is always false [-Wtautological-compare]
        if (id < 0 || id >= READING_MAX_ID)
            ~~ ^ ~
1 warning generated.
Tracing 1 functions for "./square:square"... Hit Ctrl-C to end.
^C
     nsecs               : count     distribution
         0 -> 1          : 0        |                                        |
         2 -> 3          : 0        |                                        |
         4 -> 7          : 0        |                                        |
         8 -> 15         : 0        |                                        |
        16 -> 31         : 0        |                                        |
        32 -> 63         : 0        |                                        |
        64 -> 127        : 0        |                                        |
       128 -> 255        : 0        |                                        |
       256 -> 511        : 0        |                                        |
       512 -> 1023       : 0        |                                        |
      1024 -> 2047       : 0        |                                        |
      2048 -> 4095       : 156204   |****************************************|
      4096 -> 8191       : 232      |                                        |
      8192 -> 
```

Now, my gcc left symbols in the binary. Eg:

```
# objdump -tT square | grep square
square:     file format elf64-x86-64
0000000000000000 l    df *ABS*	0000000000000000              square.c
0000000000400643 g     F .text	000000000000001f              square
```

If your compiler didn't, or if you ran "strip" on the binary, you'd be unable to trace those symbol names.

```
# file square
square: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=7a0f3406c866640dc55b0e458248bc693f42f6f4, not stripped
```

mine is "not stripped".

**Comment by kartiksura** [comment]
I did not do anything to the binary (please see below). 
Anyway I will now try again with linux 4.9-rc5  and update this thread.

objdump -tT square | grep square
square:     file format elf64-x86-64
0000000000000000 l    df *ABS*	0000000000000000              square.c
0000000000400654 g     F .text	0000000000000025              square
root@kartik-buntu:/home/ksura16# file square
square: ELF 64-bit LSB  executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=4ccf507224c69055b55904161eab498073eec651, not stripped

**Comment by brendangregg** [comment]
Hm. Older version of bcc? uprobe support was more recently added to funclatency. "funclatency -h" should include:

```
usage: funclatency.py [-h] [-p PID] [-i INTERVAL] [-T] [-u] [-m] [-F] [-r]
[...]
    ./funclatency 'c:*printf'       # time the *printf family of functions
```

**Comment by brendangregg** [comment]
BTW, 4.9 is better than 4.9-rc5. I just happen to have that -rc on hand.

**Comment by kartiksura** [comment]
Well I started exploring bcc just few days back so I dont think its old. I am installing 4.9 right now.

**Comment by brendangregg** [comment]
Yes, but it depends if you did a git clone (newest), or a apt-get (probably an old version).

**Comment by kartiksura** [comment]
You are right. It was an old version. I got the latest one. 
I am seeing newer kind of error, but  atleast moving ahead.

./funclatency.py '/home/ksura16/square:*' -p `pgrep -n square`
Traceback (most recent call last):
  File "./funclatency.py", line 204, in <module>
    b.attach_uprobe(name=library, sym_re=pattern, fn_name="trace_func_entry")
TypeError: attach_uprobe() got an unexpected keyword argument 'sym_re'

**Comment by brendangregg** [comment]
Now I'm guessing the tool is referring to an old libbcc library. Maybe apt-get remove, or manually remove the old libbcc library? Gotta make sure it uses your newly built one.

**Comment by kartiksura** [comment]
Thanks Brendan! It is working now. 

Now my roadmap is:
1. To run the latency profiling on my production code. It does user-mode threads and own memory management, so I am hoping it will not crash (systemtap+flamegraph, my old favourite crashed)

2. As the function calls would be concurrent, I will have to devise a way to resolve it.

3. The server is code intensive (ad-tech) hence if the output of profiling 'all' the functions is too large, I might want to write some automation to randomly rotate among all the functions and aggregate the result (not sure if I would need it)

4. Use some visualization (i think heatmap would suit it better than flamegraph ) to see the hotspots

**Comment by brendangregg** [comment]
Closing issue, as I think it's ok now. Please reopen if you think otherwise.
