### ISSUE TITLE
iterations over CPU: problem with offline CPUs

### ISSUE THREAD

**Issue by andihit** [iovisor/bcc#893]
Since kernel version 4.9.0 BPF stopped working in a KVM guest. The problem are calls to `perf_event_open` with CPU identifiers which do not exist (`ENODEV`). The root cause for this is that the current code assumes ascending numbered CPUs.

However, on my KVM guest I have these online CPUs:
```
$ cat /sys/devices/system/cpu/online
0-11,16-27
```

There are other reasons for non-ascending CPU numbers aswell, e.g. CPU hotplugging.

I already started working on a patch (see https://github.com/Catalysts/bcc/commit/00e3b797f9994d7fc207dd44a5a81939850c2391), but unfortunately I can't get the `BPF_PERF_OUTPUT` table working. All unit tests pass except the one I added (`test_perf_buffer_for_each_cpu`).

I suspect the error happens due to the indexing of the `PerfEventArray`; the array contains `num_cpus` entries, therefore I had to map CPU identifiers to an array index: https://github.com/Catalysts/bcc/commit/00e3b797f9994d7fc207dd44a5a81939850c2391#diff-8f7d7667d81c5d2a4dbabef190179d8fL521
Probably I have to map the incoming data from each CPU ring buffer to the correct index too, but I couldn't find the place in the code (seems that everything is handled directly by callbacks).
Any tips?

Probably the `PerCpu*` Python data structures need to be updated as well.

**Comment by 4ast** [comment]
Thanks for working on it.
bcc needs a similar fix we did for kernel samples:
https://github.com/torvalds/linux/blob/master/tools/testing/selftests/bpf/bpf_util.h#L9
the kernel returns as many elements are there are _possible_ cpus, not _online_ cpus.
In some cases (especially in VMs running on top of odd hypervisors) num_possible can be 64 or even 256 whereas online_cpus is small which may cause crashes in user space or stack corruptions.
cc @brendangregg @drzaeus77

**Comment by brendangregg** [comment]
@andihit thanks for the progress; I don't know much about how PerfEventArray works yet either.

**Comment by andihit** [comment]
Thanks for the info @4ast!
I updated the `max_entries` of the `BPF_MAP_TYPE_PERF_EVENT_ARRAY` array, now the unit test and my bpf scripts which use `BPF_PERF_OUTPUT` work again.
PR: #908

**Comment by andihit** [comment]
sorry for the noise, I just rebased the changes onto the latest master branch
