### ISSUE TITLE
Attaching kretprobe with bpf_prog_load() to syscall on Fedora: Permission denied

### ISSUE THREAD

**Issue by vitalyvch** [iovisor/bcc#901]
code:

```C
/*
 * kretprobe__SyS_read -- SyS_read() exit handler
 */
int
kretprobe__SyS_read(struct pt_regs *ctx)
{
    struct first_step_t *fsp;
    struct ev_dt_t ev = {};

    u64 cur_nsec = bpf_ktime_get_ns();

    u64 pid_tid = bpf_get_current_pid_tgid();
    fsp = tmp_i.lookup(&pid_tid);
    if (fsp == 0)
        return 0;

    ev.sc_id = __NR_read; /* SysCall ID */
    ev.arg_1 = fsp->arg_1;
    ev.arg_2 = fsp->arg_2;
    ev.arg_3 = fsp->arg_3;
    ev.arg_4 = fsp->arg_4;
    ev.arg_5 = fsp->arg_5;
    ev.arg_6 = fsp->arg_6;
    ev.pid_tid = pid_tid;
    ev.start_ts_nsec = fsp->start_ts_nsec;
    ev.finish_ts_nsec = cur_nsec;
    ev.ret = PT_REGS_RC(ctx);

    const size_t ev_size = offsetof(struct ev_dt_t, sc_name);
    events.perf_submit(ctx, &ev, ev_size);

    tmp_i.delete(&pid_tid);

    return 0;
}
```

debug:

```Assembly
0: (bf) r6 = r1
1: (b7) r8 = 0
2: (7b) *(u64 *)(r10 -8) = r8
3: (7b) *(u64 *)(r10 -16) = r8
4: (7b) *(u64 *)(r10 -24) = r8
5: (7b) *(u64 *)(r10 -32) = r8
6: (7b) *(u64 *)(r10 -40) = r8
7: (7b) *(u64 *)(r10 -48) = r8
8: (7b) *(u64 *)(r10 -56) = r8
9: (7b) *(u64 *)(r10 -64) = r8
10: (7b) *(u64 *)(r10 -72) = r8
11: (7b) *(u64 *)(r10 -80) = r8
12: (7b) *(u64 *)(r10 -88) = r8
13: (7b) *(u64 *)(r10 -96) = r8
14: (7b) *(u64 *)(r10 -104) = r8
15: (7b) *(u64 *)(r10 -112) = r8
16: (7b) *(u64 *)(r10 -120) = r8
17: (7b) *(u64 *)(r10 -128) = r8
18: (7b) *(u64 *)(r10 -136) = r8
19: (7b) *(u64 *)(r10 -144) = r8
20: (7b) *(u64 *)(r10 -152) = r8
21: (7b) *(u64 *)(r10 -160) = r8
22: (7b) *(u64 *)(r10 -168) = r8
23: (7b) *(u64 *)(r10 -176) = r8
24: (7b) *(u64 *)(r10 -184) = r8
25: (7b) *(u64 *)(r10 -192) = r8
26: (7b) *(u64 *)(r10 -200) = r8
27: (7b) *(u64 *)(r10 -208) = r8
28: (7b) *(u64 *)(r10 -216) = r8
29: (7b) *(u64 *)(r10 -224) = r8
30: (7b) *(u64 *)(r10 -232) = r8
31: (7b) *(u64 *)(r10 -240) = r8
32: (7b) *(u64 *)(r10 -248) = r8
33: (7b) *(u64 *)(r10 -256) = r8
34: (7b) *(u64 *)(r10 -264) = r8
35: (7b) *(u64 *)(r10 -272) = r8
36: (7b) *(u64 *)(r10 -280) = r8
37: (7b) *(u64 *)(r10 -288) = r8
38: (7b) *(u64 *)(r10 -296) = r8
39: (7b) *(u64 *)(r10 -304) = r8
40: (7b) *(u64 *)(r10 -312) = r8
41: (7b) *(u64 *)(r10 -320) = r8
42: (7b) *(u64 *)(r10 -328) = r8
43: (7b) *(u64 *)(r10 -336) = r8
44: (7b) *(u64 *)(r10 -344) = r8
45: (7b) *(u64 *)(r10 -352) = r8
46: (7b) *(u64 *)(r10 -360) = r8
47: (7b) *(u64 *)(r10 -368) = r8
48: (7b) *(u64 *)(r10 -376) = r8
49: (7b) *(u64 *)(r10 -384) = r8
50: (7b) *(u64 *)(r10 -392) = r8
51: (7b) *(u64 *)(r10 -400) = r8
52: (7b) *(u64 *)(r10 -408) = r8
53: (7b) *(u64 *)(r10 -416) = r8
54: (7b) *(u64 *)(r10 -424) = r8
55: (7b) *(u64 *)(r10 -432) = r8
56: (7b) *(u64 *)(r10 -440) = r8
57: (7b) *(u64 *)(r10 -448) = r8
58: (7b) *(u64 *)(r10 -456) = r8
59: (7b) *(u64 *)(r10 -464) = r8
60: (7b) *(u64 *)(r10 -472) = r8
61: (7b) *(u64 *)(r10 -480) = r8
62: (7b) *(u64 *)(r10 -488) = r8
63: (7b) *(u64 *)(r10 -496) = r8
64: (7b) *(u64 *)(r10 -504) = r8
65: (7b) *(u64 *)(r10 -512) = r8
66: (7b) *(u64 *)(r10 -520) = r8
invalid stack off=-520 size=8
```

From my point of view it looks like bcc issue.

Also it happened only on Fedora.

@ldorau, please provide details about Fedora and package versions.

@marcinslusarz, @GBuella, @ldorau, @plebioda, @sarahjelinek

**Comment by ldorau** [comment]
Fedora release 24 (Twenty Four) Workstation
kernel 4.8.13-200.fc24.x86_64

All bcc packets:
# rpm -qa | grep bcc
python-bcc-0.2.0-106.git.0d5d25e.x86_64
libbcc-0.2.0-106.git.0d5d25e.x86_64
bcc-tools-0.2.0-106.git.0d5d25e.x86_64

**Comment by ldorau** [comment]
From strace:
bpf(BPF_PROG_LOAD, {prog_type=BPF_PROG_TYPE_KPROBE, insn_cnt=124, insns=0x7f4a318903e8, license="GPL", log_level=1, log_size=65536, log_buf=0x3614a10, kern_version=264205}, 48) = -1 EACCES (Permission denied)

**Comment by brendangregg** [comment]
"invalid stack off=-520 size=8"

Looks like your program declares too much local variable storage, and is exceeding the BPF stack. That would be a problem with your program. I'd need to see the program in full.

**Comment by brendangregg** [comment]
gist.github.com might work better for pasting (pastebin.com crashed when I tried to load it).

Well that's odd. Maybe the llvm/bcc versions on Fedora are compiling the struct to be larger?

You can see it initializing a large blob of memory to be zero:

```
1: (b7) r8 = 0
2: (7b) *(u64 *)(r10 -8) = r8
3: (7b) *(u64 *)(r10 -16) = r8
4: (7b) *(u64 *)(r10 -24) = r8
5: (7b) *(u64 *)(r10 -32) = r8
6: (7b) *(u64 *)(r10 -40) = r8
7: (7b) *(u64 *)(r10 -48) = r8
8: (7b) *(u64 *)(r10 -56) = r8
```

Which I'd think was the output struct. We should improve these debug messages over time.

Also, looks like you're implementing strace in eBPF. Which is fine if that's what you need to do. Just wanted to say that I usually look for a more targeted solution to a given problem -- narrowing down what I'm tracing, and trying to summarize things in-kernel instead of dumping everything per-event.

**Comment by vitalyvch** [comment]
Hm ... 

> Which I'd think was the output struct.

I think now I understand the problem.

> Also, looks like you're implementing strace in eBPF.

Kind of.

> Which is fine if that's what you need to do.

Yes, we need exactly this.

> I'm tracing, and trying to summarize things in-kernel instead of dumping everything per-event.

We need advanced post-processing.

**Comment by ldorau** [comment]
This issue occurred on 0.2.0-106.git.0d5d25e - the latest package build available for Fedora 24. After updating bcc from sources to the latest master, the issue does not exist any longer and it can be closed. Thanks.

**Comment by brendangregg** [comment]
ok, thanks for confirming, closing ticket...
