### ISSUE TITLE
Packages for Fedora 24 are not being updated

### ISSUE THREAD

**Issue by ldorau** [iovisor/bcc#902]
Packages for Fedora 24 are not being updated. The last version is 0.2.0-106.git.0d5d25e.
Please update packages.

@marcinslusarz, @GBuella, @sarahjelinek, @vitalyvch

**Comment by mslusarz** [comment]
It seems it's already resolved. I can see packages from yesterday here: https://repo.iovisor.org/yum/nightly/f24/x86_64/

**Comment by vitalyvch** [comment]
Probably that was triggered manually.

**Comment by drzaeus77** [comment]
I have migrated to a new jenkins setup, nightlies are being run for fc24, fc25, and ubuntu1604. Other distros (fc23, ubuntu1404) are no longer being updated.

**Comment by ldorau** [comment]
Thanks!
