### ISSUE TITLE
trace.py to support argument dereferencing like argdist.py

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bcc#907]
This currently works in argdist:

```
./argdist.py -v -C 'p::SyS_nanosleep(const struct timespec *req):long:req->tv_nsec'
```

Which is pretty awesome.

But it doesn't work in trace, eg:

```
./trace.py 'p::SyS_nanosleep(const struct timespec *req) "sleep for %d sec %d ns", req->tv_sec, req->tv_nsec'
```
I wasn't able to come up with a workaround, involving just casting arg1/2/... as whatever, since 
it requires some explicit bpf_probe_reads()s.

CC @goldshtn

**Comment by goldshtn** [comment]
Yeah, it would be nice to have. Only problem is that `trace` currently considers a parenthesized expression preceding the format string to be a filter. E.g. you could say `p::SyS_nanosleep (arg1 != 0) "%x", arg1`. Maybe we're stretching it a bit too far.

**Comment by brendangregg** [comment]
Another problem is I'm starting to use trace more and more. :) I'll be demoing it tomorrow at linux.conf.au.

Yes, trace/argdist shouldn't try to do everything, but this one thing... well, two things, if argdist also gets parenthesized tests some day to match trace. :)

Some ideas:

```
p::SyS_nanosleep(const struct timespec *req) (arg1 != 0) "%x", arg1
p::SyS_nanosleep(const struct timespec *req) if (arg1 != 0) "%x", arg1
p::SyS_nanosleep(const struct timespec *req) /arg1 != 0/ "%x", arg1
```

In the first case, the test parenthesis group could be identified as one that contains a '[=<>]'. I don't think those chars appear in function prologues.

"if" could be a keywoard.

And we could just use '/', like awk's RE syntax.

**Comment by goldshtn** [comment]
Well, good thing argdist already has filters -- check out the man page 😇 

Also, here's from the examples:

```
argdist -p 2780 -C 'p:c:write(int fd, char* buf, size_t len):char*:buf:fd==1'
```

The `fd==1` part is the filter.

**Comment by goldshtn** [comment]
All right, take a look at #911. Hopefully in time for your talk at LinuxConf :smile:
