### ISSUE TITLE
Using bcc/bpf to profilie algorithms

### ISSUE THREAD

**Issue by LieberBarry** [iovisor/bcc#912]
Many of the tools in bcc are geared towards monitoring, but many of the capabilities provided by dynamic tracing would be useful to me as a way to simplify profiling applications during development:

1. Measuring Enter/Exit duration for arbitrary functions in user mode. 

I'd like to use this to compare the perf of various algos and to get a breakdown of the time contributions of various parts of the algo. Perhaps best described as a non-statistical cachegrind. 

The tool needs to output an observation for each call on return. It need to (optionally) output csv so the results can be easily aggregated and visualized. It should optionally output summary statistics. It needs to allow me to specify a tag field that identifies the run, so I can combine it with others and perform comparisons. Is there interest in a PR for something like this? Probably a similar but distinct cousin to `funclatency`.
 
2.  I'm looking for a way to isolate perf events (cache misses, TLB, faults,etc) to a specific function(s) in user code dynamically. 

There's often a lot of setup/teardown required to execute an algorithm, so profiling the entire application provide polluted counts. There's also the need to isolate the algo as much as possible. Sometimes the code is part of an existing application and I'm trying to quickly figure out if an alternative implementation would be a significant win. I don't want to have write throwaway harnesses to isolate existing code, that's exactly what dynamic tracing should make obsolete.

So I'd like to use dynamic instrumentation to toggle perf events on/off on entry/exit from a function and capture the results. Nesting measurements would be nice, but not necessary to begin with.

Is this kind of dynamic instrumentation possible with bcc or is this the wrong tool for the job?

**Comment by brendangregg** [comment]
> 1. Measuring Enter/Exit duration for arbitrary functions in user mode.

funclatency can do that, one function at a time. And that's probably a good thing with the current implementation of using uprobes, which adds overhead. If you were tracing many user functions, I'd stop trusting the latency measurements.

> 2. I'm looking for a way to isolate perf events (cache misses, TLB, faults,etc) to a specific function(s) in user code dynamically.

perf can solve that problems (you want to use PEBS events) by overflow sampling then post filtering to the functions you care about.

Sure, you could use BPF, and then filter PMCs based on the value of a map that was updated from other dynamic probes, which likely has lower overhead (but not certain: if your dynamic tracing was too aggressive, this would be cheaper to just use perf).

But I believe people solve this with perf_event_open and doing ENABLE/DISABLE ioctls in their code.

I'd take this up on the perf-users mailing list.

**Comment by brendangregg** [comment]
>>> Measuring Enter/Exit duration for arbitrary functions in user mode.
>>
>> funclatency can do that, one function at a time. And that's probably a good thing with the current 
>> implementation of using uprobes, which adds overhead. If you were tracing many user functions, I'd 
>> stop trusting the latency measurements.
>
> It can but produces aggregate histograms exclusively, not raw measurements

You really want per-event function latency? I would say use funcslower, but I can't find where I put it (maybe I never wrote it?). It would be similar to the other *slower tools, so, example usage:

```
funcslower vfs_write           # only show kernel vfs_write() calls slower than, say, 1 ms
funcslower vfs_write 10       # ... slower than 10 ms
funcslower -u vfs_write 10       # ... slower than 10 us
funcslower vfs_write 0       # dump all calls
funcslower c:open            # trace libc open()
funcslower bash:readline      # trace bash's readline()
funcslower vfs_read vfs_write   # trace both these
```

> nor summary stats (akin to `perf stat --repeat`). 

funclatency has -i

> The question is would you like a PR?

I think funcslower would make sense. I still can't find it (I thought I'd already written it).

I would not like to see something that allowed you to do this:

```
funcslower c:*        # time all functions in libc
funcslower vfs*        # time all vfs functions
```

... as the risk of shooting yourself in the foot by tracing too much is high. Even if the tool worked (and bcc didn't reject it for tracing too many probes), I'd stop trusting the latency measurements it reported. I've done and debugged this before.

>>perf can solve that problems (you want to use PEBS events) by overflow sampling then post 
>> filtering to the functions you care about.
>
>My measurements are on the order of 10-100ms, , the near-cycle accuracy of PEBS is >superfluous.
>
>I've never heard of "overflow sampling" and can't find any reference to it, can you suggest a >resource?

An interrupt for every 10k LLC misses, for example. perf's -c.

I still think you might be unaware of a different approach. I think you're thinking that you need to read PMCs on entry and return to a function, in order to get function-related stats. I almost never do it that way due to overhead -- and instead just do overflow sampling with the collection of stack traces or IPs.

**Comment by goldshtn** [comment]
Just noting that argdist has a magic $latency keyword that you can use in ret probes to collect invocation time (in ns). There should be an example.

**Comment by brendangregg** [comment]
thanks, I'll do a separate ticket for the creation of funcslower and mention argdist.

(The more I use argdist, the more I wonder if we should rename it to be something simpler (to match trace), like, just "dist"....)

**Comment by LieberBarry** [comment]
> funclatency has -i

That's still a histogram, not individual measurements. But I really need individual datums. The histogram bins are too coarse and a histogram is not an appropriate aggregation in my case. I also need a dataset I can use to estimate a distribution for what I'm measuring (with higher accuracy than... ASCII (-: ).

The bcc tools seem generally targeted towards either whole-system or long-running processes. Tools for diagnosis issues in production. Of course, that's something bpf does very well, so it makes sense. But dynamic tracing has other use cases, and it's just an oversight that prevents the same tools from addressing those cases as well. 

> Just noting that argdist has a magic $latency keyword 

Yes! that gives me the numerical information I need, with the only nuisance being that it insists on being `top`-like, I get one event every time I run my program -- why force me to aggregate?

**Comment by LieberBarry** [comment]
> ... as the risk of shooting yourself in the foot by tracing too much is high. Even if the tool worked (and bcc didn't reject it for tracing too many probes), I'd stop trusting the latency measurements it reported. I've done and debugged this before.

Sure. Just a thought on this issue with `tcptop`. Is the overhead generally due to the callback, or the work involved in collecting the events and aggregating them? Assuming a nop callback is cheap enough, you could use the data collected over a short amount of time to identify the firehoses, than generate an adapted filter that ignores those pids. Admittedly, I'm speaking out of relative ignorance about the bpf mechanism.

**Comment by brendangregg** [comment]
> and it's just an oversight that prevents the same tools from addressing those cases as well.

It's not an oversight. Per-event tracing is the last, dumbest, thing we want to do. BPF's great advantage over other per-event tools is maps for kernel summaries, which greatly reduce overhead. If funclatency's latency summary isn't meeting your need, then how can it? Linear histograms were added recently -- and funclatency (and argdist) probably should have an option to use them.

As a last resort, we do per-event tracing. I'd like to see summary tools done first, and encourage people to use them, before per-event tools. If we began with the latter, people would needlessly shoot themselves in the foot, and it would give BPF a bad name -- not showing the true value of the technology.

**Comment by brendangregg** [comment]
Submitted #915 for funcslower, the tool you use after you've tried funclatency & argdist.

**Comment by LieberBarry** [comment]
funclatency's latency summary gives me what I'm looking for -- by accident. It's a hack to treat incidentally single event histograms as a poor-man's per-event report, and In an output format that's intended for humans, not postprocessing. That's why a specific tool (or mode) has a place and I'm glad you agree. #915 would solve half my problem, thanks.

Keeping the tracing experience free is a strong point, but there's difference In allowing the output format to be (be) adjust(able) to the event rate. There'e an apperent need for a conventional way to measure the impact of a bpf program on the system, and to be able to ratelimit based on it. I think You mentioned accounting is in the works in one of your talks. I hope you'll reevaluate when it lands.

Closing in favor of #915. I'll roll my own for a function-hooking alternative to `perf stat`.
