### ISSUE TITLE
Symbol resolution code should support external debuginfo

### ISSUE THREAD

**Issue by goldshtn** [iovisor/bcc#930]
A lot of binaries ship OOTB without debuginfo embedded, and require a debuginfo package (e.g. on FC, `dnf debuginfo-install pkg-name` will usually install the debuginfo into /usr/lib/debug). The current ELF scanning code that produces symbol names doesn't take debuginfo files into account. As a result, it's impossible to resolve symbols in any of our stack-tracing tools for any binary/SO that doesn't have debuginfo embedded, even if external debuginfo is installed.

It seems like FC and Ubuntu put debuginfo in /usr/lib/debug, and it seems like gdb on all platforms automatically knows to look there. So I'd say it would make sense for our symbol resolver to automatically try and find symbols there before giving up. Thoughts?

/cc @vmg @markdrayton @brendangregg

**Comment by vitalyvch** [comment]
Very good idea.

@mslusarz

**Comment by markdrayton** [comment]
Agreed, this will be very useful. `show debug-file-directory` in GDB shows the paths it'll search under, and the `.gnu_debuglink` section of a binary shows the name (and a checksum) of the corresponding debuginfo file:

```
$ objdump --full-contents --section=.gnu_debuglink /bin/ls

/bin/ls:     file format elf64-x86-64

Contents of section .gnu_debuglink:
 0000 6c732e64 65627567 00000000 47497305  ls.debug....GIs.
```

**Comment by markdrayton** [comment]
(Not that I am suggesting invoking GDB here; just that we can check the search paths of various distros this way.)
