### ISSUE TITLE
Segfault in bpf_attach_kprobe()

### ISSUE THREAD

**Issue by ldorau** [iovisor/bcc#933]
bpf_attach_kprobe() prints:
```
write(/sys/kernel/debug/tracing/kprobe_events, "r:kprobes/r_SyS_uselib SyS_uselib") failed: No such file or directory
```
and then segmentation fault occurs.

Environment: Fedora 24, kernel 4.9.6-100.fc24.x86_64, bcc  v0.2.0-279-gb79b589

@marcinslusarz, @GBuella, @sarahjelinek, @vitalyvch

**Comment by vitalyvch** [comment]
#939

**Comment by goldshtn** [comment]
Seeing that this is a duplicate, can it be closed?

**Comment by vitalyvch** [comment]
Originally these issues happened with different usecases in different environments, but now it looks like they have the same reason.

@ldorau, What do you think about it?

**Comment by ldorau** [comment]
Yes, it can be closed now.
