### ISSUE TITLE
biosnoop Lost samples

### ISSUE THREAD

**Issue by libbkmz** [iovisor/bcc#966]
Hello, I need to capture all IO events. I've tried biosnoop and it's working fine! But sometimes I'm getting this error:

    2.004204001    kworker/0:3    26040  xvdb    W  41950344  65536      0.34
    Lost 10 samples
    2.104204001    kworker/0:3    26040  xvdb    W  31950344  65536      0.28

I've found, that it produced here:
https://github.com/iovisor/bcc/blob/master/src/cc/perf_reader.c#L238

But I can't setup debug evironment for bcc and can't get detailed information about this issue. 
How ca I avoid this issue? How can I increase ring-buffer for perf events?

**Comment by markdrayton** [comment]
The ring buffer size is hardcoded at the moment:

https://github.com/iovisor/bcc/blob/master/src/cc/perf_reader.c#L29

This is something I have also wanted to increase at times. From a quick look it seems we could plumb a size through from Python's `open_perf_buffer`. I think that adding a command line flag to set the buffer size for every script would be undesirable — a lot of extra boilerplate code, and it might not even be possible to find a flag that we can use consistently across scripts — so how about an environment variable that can override the default size? `BCC_PERF_BUFFER_PAGECNT`? @brendangregg, @4ast, @goldshtn: any opinions?

**Comment by markdrayton** [comment]
Actually `-b` and `-B` both appear to be unused in all current tools. If we do want to use a command line flag those are obvious candidates.

**Comment by brendangregg** [comment]
I've hit this too with some tools. Would be good to fix.

If some tools sometimes need a buffer so large it doesn't make sense to have that the default, like trace.py which can trace anything, then having a -b might make sense. But things like execsnoop, opensnoop, and probably biosnoop, should have some reasonable limits that should work for everyone, which we could hardcode in the tool. I'd rather not clutter all tools (increase functional complexity) by adding rarely used options if possible.

I don't have much of an opinion on a environment variable. Only if we find people need to use it, then either fix the script (hardcode a suitable size), or if that hardcoded size would be excessively large as a default, then have the -b.

**Comment by 4ast** [comment]
not too excited about envvar. I'd prefer to improve/increase default, make it larger for tools that hit it and finally let the tool specify it via -b. Probably very few tools would actually need it?

**Comment by libbkmz** [comment]
Thanks for information. I would try to change this value and rerun my experiment. 

But, I have some restriction policy regarding lost samples, I'm not allowed to skip any IO requests. So, how can I be motified inside python biosnoop about this:
https://github.com/iovisor/bcc/blob/master/src/cc/perf_reader.c#L239

When PERF_RECORD_LOST is occured, I need to know this inside https://github.com/iovisor/bcc/blob/master/tools/biosnoop.py#L154 this event. Simple solution I see, is to make assert insted just of printing. But I'm not sure that it will be good. May be there is more elegant solution?

**Comment by brendangregg** [comment]
... reminds me of the DTraceToolkit: I had to tune bufsize/dynvarsize on about a dozen tools out of over 200. I never had to expose it as a -b like tunable, although I never had a tool like trace.py where it can trace completely different events. So I think several tools we'd need to hardcode it (like biosnoop), and trace.py gets a -b.

**Comment by markdrayton** [comment]
@brendangregg, @4ast: okay, increases where typically needed and a `-b` for `trace.py`. I'll make a PR.

@libbkmz: maybe we could run a callback when events are dropped? cc @palmtenor

**Comment by vitalyvch** [comment]
How about solution from #884

**Comment by vitalyvch** [comment]
Stable way to reproduce "Lost samples":

dd if=/dev/zero of=/dev/null count=20000000

It generates about 1500000 IO events per second and libbcc could not handle them at all.

**Comment by goldshtn** [comment]
@vitalyvch It would not help tool users if we declare that variable as extern in libbcc. However, the suggestions made above (to increase the buffer for specific high-rate tools, and to provide a -b argument for trace) should be sufficient.

**Comment by vitalyvch** [comment]
@goldshtn Yes, my point is than ot will made API more clean and more consistent for tool writers.

**Comment by goldshtn** [comment]
@vitalyvch And even then, it is far better to provide an explicit function that changes this value (as discussed in this issue) rather than declare it as extern in some header as you propose in #884.

**Comment by vitalyvch** [comment]
@goldshtn Definitely :-)

**Comment by brendangregg** [comment]
@vitalyvch /dev/zero to /dev/null shouldn't be traced by biosnoop, and isn't when I test it. Did you mean as a workload for trace.py and read/write?

**Comment by vitalyvch** [comment]
@brendangregg I'm sorry. I just was a bit inattentive. But yes, currently I recognise this workload as generates the highest rate of read/write events. It should be good for trace.py or for looking of performance bottlenecks.

**Comment by markdrayton** [comment]
@libbkmz #997 makes the buffer 8x larger for some tools, including biosnoop. Does that help?

**Comment by goldshtn** [comment]
I'm closing for now, if the increased buffer size still doesn't help -- we should look into this again. @libbkmz
