### ISSUE TITLE
Commit 1e6df40 reverted by mistake?

### ISSUE THREAD

**Issue by r4f4** [iovisor/bcc#973]
The commit 1e6df40 fixing a unused import seems to have been reverted by commit a112514. Without it, the following error happens:
$: ./cpudist 
Traceback (most recent call last):
  File "./cpudist", line 15, in <module>
    from bcc import BPF, Tracepoint
ImportError: cannot import name 'Tracepoint'

**Comment by goldshtn** [comment]
Ugh, that's not good. Both of the files undone in that commit were recently merged in PRs #925 and #926. I'm on my phone right now - can you see if anything else was reverted?

**Comment by r4f4** [comment]
That seems to be all.

**Comment by goldshtn** [comment]
Then would you mind doing a PR that replays the changes that commit undid? The pid fixes in ardgist and that import in cpudist...

**Comment by goldshtn** [comment]
Fixed by #974, right?

**Comment by r4f4** [comment]
Yes. I'm sorry I forgot to add that to the commit message.

**Comment by goldshtn** [comment]
Closing, this was fixed. Thanks @r4f4!
