### ISSUE TITLE
bcc trace ubuntu packages are somehow broken for user probes for types smaller than 64bit

### ISSUE THREAD

**Issue by Fiedzia** [iovisor/bcc#991]
A simple c program that uses 1-byte counter:

```c
#include <sys/sdt.h>
#include <stdio.h>

    int main(void)
    {
      unsigned char i=0;
      for(i=0;;i++) {
          if(i>100) i=0;
          printf("%d\n",i);
          DTRACE_PROBE1(foo, bar, i);
      };
      return 0;
    }
```

gcc -I /usr/include/x86_64-linux-gnu/sys test.c

./a.out

now, in second shell
```sh
sudo stap -x `pidof a.out` -e 'probe process.mark("bar") { printf("%s\n", $$vars); }'
```
this will print increasing values, as expected

now bcc:
```sh
sudo /usr/share/bcc/tools/trace  -p `pidof a.out`  'u::bar "%d", arg1'
```
shows only 0's

Same thing for packages from bcc repository as well as snap.
Works fine for 64 bit values (signed or not).

Ubuntu 16.10

**Comment by goldshtn** [comment]
Thank you for filing this, I have a fix in #992.

**Comment by Fiedzia** [comment]
Thank you. When could I expect updated packages?

**Comment by goldshtn** [comment]
I think it's nightly. @4ast do you know?

**Comment by 4ast** [comment]
cc @drzaeus77

**Comment by drzaeus77** [comment]
See https://buildbot.iovisor.org/jenkins/job/bcc-nightly/

Every night @ 1:32 AM UST.
